gmmlNew: TopologyFileSpace::TopologyAngle Class Reference
TopologyFileSpace::TopologyAngle Class Reference
#include <topologyangle.hpp>
Public Member Functions
TopologyAngle ()
TopologyAngle (std::vector< std::string > angle_atoms, std::vector< std::string > residue_names)
std::vector< std::string > GetAngles ()
TopologyAngleType * GetAngleType ()
bool GetIncludingHydrogen ()
std::vector< std::string > GetResidueNames ()
void SetAngles (std::vector< std::string > angles)
void SetAnlgeType (TopologyAngleType *angle_type)
void SetIncludingHydrogen (bool including_hydrogen)
void SetResidueNames (std::vector< std::string > residue_names)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 12 of file topologyangle.hpp.
Constructor & Destructor Documentation
TopologyAngle::TopologyAngle ()
Definition at line 11 of file topologyangle.cc.
{}
TopologyFileSpace::TopologyAngle::TopologyAngle (std::vector< std::string > angle_atoms, std::vector< std::string > residue_names)
Member Function Documentation
vector< string > TopologyAngle::GetAngles ()
Definition at line 30 of file topologyangle.cc.
Referenced by TopologyFileSpace::TopologyFile::AddAngle(), TopologyFileSpace::TopologyFile::ResolveAnglesIncHydrogenSection(), and TopologyFileSpace::TopologyFile::ResolveAnglesWithoutHydrogenSection().
{
    return angles_;
}
TopologyAngleType * TopologyAngle::GetAngleType ()
Definition at line 34 of file topologyangle.cc.
Referenced by TopologyFileSpace::TopologyFile::AddAngle(), TopologyFileSpace::TopologyFile::ParseSections(), TopologyFileSpace::TopologyFile::ResolveAnglesIncHydrogenSection(), and TopologyFileSpace::TopologyFile::ResolveAnglesWithoutHydrogenSection().
{
    return angle_type_;
}
bool TopologyAngle::GetIncludingHydrogen ()
Definition at line 38 of file topologyangle.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveAnglesIncHydrogenSection(), and TopologyFileSpace::TopologyFile::ResolveAnglesWithoutHydrogenSection().
{
    return including_hydrogen_;
}
vector< string > TopologyAngle::GetResidueNames ()
Definition at line 42 of file topologyangle.cc.
Referenced by TopologyFileSpace::TopologyFile::AddAngle().
{
    return residue_names_;
}
void TopologyAngle::Print (std::ostream & out = std::cout)
Definition at line 82 of file topologyangle.cc.
References TopologyFileSpace::TopologyAngleType::Print().
Referenced by TopologyFileSpace::TopologyFile::Print().
{
    out << "Angle: " << residue_names_.at(0) << ":" << angles_.at(0) << "-" << residue_names_.at(1) << ":" << angles_.at(1) << "-" << residue_names_.at(2) << ":" << angles_.at(2) << endl;
    out << "\t ";
    angle_type_->Print(out);
    out << ", Including Hydrogen: ";
    if(including_hydrogen_)
        out << "YES";
    else
        out << "NO";
    out << endl;
}
void TopologyAngle::SetAngles (std::vector< std::string > angles)
Definition at line 50 of file topologyangle.cc.
{
    angles_.clear();
    for(vector<string>::iterator it = angles.begin(); it != angles.end(); it++)
    {
        angles_.push_back(*it);
    }
}
void TopologyAngle::SetAnlgeType (TopologyAngleType * angle_type)
Definition at line 58 of file topologyangle.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyAnglesFromAssembly(), and TopologyFileSpace::TopologyFile::ParseSections().
{
    angle_type_ = angle_type;
}
void TopologyAngle::SetIncludingHydrogen (bool including_hydrogen)
Definition at line 62 of file topologyangle.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyAnglesFromAssembly(), and TopologyFileSpace::TopologyFile::ParseSections().
{
    including_hydrogen_ = including_hydrogen;
}
void TopologyAngle::SetResidueNames (std::vector< std::string > residue_names)
Definition at line 66 of file topologyangle.cc.
{
    residue_names_.clear();
    for(vector<string>::iterator it = residue_names.begin(); it != residue_names.end(); it++)
    {
        residue_names_.push_back(*it);
    }
}
The documentation for this class was generated from the following files:
includes/FileSet/TopologyFileSpace/topologyangle.hpp
src/FileSet/TopologyFileSpace/topologyangle.cc