#ifndef INCLUDES_MOLECULARMETADATA_GLYCAM_BONDLENGTHBYTYPEPAIR_HPP
#define INCLUDES_MOLECULARMETADATA_GLYCAM_BONDLENGTHBYTYPEPAIR_HPP
#include <string>

namespace GlycamMetadata
{
    double GetBondLengthForAtomTypes(std::string query1, std::string query2);
}
#endif // INCLUDES_MOLECULARMETADATA_GLYCAM_BONDLENGTHBYTYPEPAIR_HPP
