#!/bin/bash

##
## This code generates the file defined by OutputFile, below.
##
## That file, in turn, is called by residue-name-mappings.bash, which
## generates the mappings for the code generating script,
## make_glycam06_residue_name-2-type_lookup.bash
##

#################################################
#################################################
#################################################
###
### This is terrible code.  For the love of all
### that is good and true in the world, someone
### please dry it out!
###
#################################################
#################################################
#################################################

##
## File With All Residue Names
##
ResidueNames='../All_Residues.txt'

##
## Carbohydrate Definitions Output File
##
OutputFile='3_carbohydrate_residue_tags.bash'
if [ -e ${OutputFile} ] ; then
  rm ${OutputFile}
fi

##
## For debugging: a list of residues handled by this script 
##
ScriptHandledList='List_of_residues_in_Carb_Defs_bash.txt'
if [ -e ${ScriptHandledList} ] ; then
  rm ${ScriptHandledList}
fi
## comment this out if you want a file written that will list all the
## residues that this script is managing
##
ScriptHandledList='/dev/null'

echo "#!/bin/bash
##
##  File named ${OutputFile} generated by script ${0} on $(date).
##  This file contains definitions of the carbohydrate residues in 
##  the GLYCAM06 non-EP parameter set.
##
##  This file should be called from res-name-mappings.bash
##" > ${OutputFile}

#####################
## Aldoses
#####################

## Plain hexose monosaccharides
## For most of these, the gauche effect is handled below
TYPE_BASE=' carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 '
for i in T N E F L G K M Q H ; do 
	## alpha D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	## beta D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
for i in t n e f l g k m q h ; do 
	## alpha L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	## beta L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done

## N-acetyl hexose monosaccharides
TYPE_BASE=' carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl '
for i in V Y W ; do 
	## alpha D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	## beta D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
for i in v y w ; do 
	## alpha L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	## beta L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done

## bacillosamine
TYPE_BASE=' carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl beta gauche-effect=na '
	# D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.Bc$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.Bc$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	# L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.bc$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.bc$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
## glucosamine hexose monosaccharides
TYPE_BASE=' carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 amine D-isomer '
	# alpha
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.YN$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.YN$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	# beta
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.Yn$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.Yn$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
## glucosamine hexose monosaccharides, protonated
TYPE_BASE=' carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=+1 amine D-isomer protonated '
	# alpha
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.YNP$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.YNP$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	# beta
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.YnP$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.YnP$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
## N-sulfo-glucosamine hexose monosaccharides
TYPE_BASE=' carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-sulfo '
	# alpha
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.YS$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.YS$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	# beta
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.Ys$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.Ys$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	# alpha
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.yS$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.yS$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	# beta
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep  ^.ys$  ${ResidueNames} >> ${OutputFile}
    	grep  ^.ys$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
## uronates (acids)
TYPE_BASE=' carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=-1 uronate gauche-effect=na '
for i in O Z U ; do 
	## alpha D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	## beta D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
for i in o z u ; do 
	## alpha L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	## beta L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
## protonated uronates
TYPE_BASE=' carbohydrate monosaccharide pyranose aldose n-carbon=6 alpha L-isomer formal-charge=0 uronate protonated gauche-effect=na '
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} \" " >> ${OutputFile}
	echo 'NAMES[${i}]=" YuAP "' >> ${OutputFile}
    	echo 'YuAP' >> ${ScriptHandledList}
TYPE_BASE=' carbohydrate monosaccharide pyranose aldose n-carbon=6 beta D-isomer formal-charge=0 uronate protonated gauche-effect=na '
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} \" " >> ${OutputFile}
	echo 'NAMES[${i}]=" 0ZBP "' >> ${OutputFile}
    	echo '0ZBP' >> ${ScriptHandledList}

## unsaturated uronates
TYPE_BASE=' carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=-1 uronate unsaturated-uronate gauche-effect=na ' 
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} \" " >> ${OutputFile}
	echo 'NAMES[${i}]=" 045 245 "' >> ${OutputFile}
    	echo  "045
245" >> ${ScriptHandledList}

# gauche effect defaults
# gluco like
GAUCHETYPE=' N E G M Y W n e g m y w  '
for i in ${GAUCHETYPE} ; do 
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" gauche-effect=gluco \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${OutputFile}
	echo '"' >> ${OutputFile}
done
GAUCHETYPE=' YN Yn YNP YnP YS Ys yS ys '
for i in ${GAUCHETYPE} ; do 
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" gauche-effect=gluco \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}$  ${ResidueNames} >> ${OutputFile}
	echo '"' >> ${OutputFile}
done
# galacto like
GAUCHETYPE='T L I K V t l i k v'
for i in ${GAUCHETYPE} ; do 
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" gauche-effect=galacto \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${OutputFile}
	echo '"' >> ${OutputFile}
done
# deoxy, so although there is an exocyclic C6, there is no gauche effect
GAUCHETYPE='F Q H f q h'
for i in ${GAUCHETYPE} ; do 
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" gauche-effect=na \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${OutputFile}
	echo '"' >> ${OutputFile}
done

## Plain pentose monosaccharides
TYPE_BASE=' carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na '
for i in A D R X ; do 
	## alpha D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	## beta D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
for i in a d r x ; do 
	## alpha L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	## beta L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
TYPE_BASE=' carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown '
for i in A D R X ; do 
	## alpha D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}D$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}D$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	## beta D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}U$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}U$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
for i in a d r x ; do 
	## alpha L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}D$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}D$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	## beta L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}U$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}U$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
## Deoxy pentose monosaccharides
## Tyvelose, Abequose
TYPE_BASE=' carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 deoxy gauche-effect=na '
for i in AE TV ; do 
	# alpha
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
for i in Ae Tv ; do 
	# beta
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
for i in tV ; do 
	# alpha
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
for i in tv ; do 
	# beta
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done

## All aldoses that can be 'aglycon' terminals via anomeric-to-anomeric linkage
AllStandardAldoses='T N E F L G K M Q H t n e f l g k m q h 
V Y W  v y w  O Z U  o z u  A D R X  a d r x  '
AllSpecialAldoses=' AE TV  Ae Tv  tV  tv  Bc bc YN Yn YNP YnP YS Ys yS ys'
echo "## aldose monosacharides that can be aglycons " >> ${OutputFile}
for i in ${AllStandardAldoses} ; do
        echo 'i=$((i+1))' >> ${OutputFile}
        echo "TYPES[\${i}]=\" aglycon \" " >> ${OutputFile}
        echo 'NAMES[${i}]="' >> ${OutputFile}
        grep   ^1${i}[ABDU]$  ${ResidueNames} >> ${OutputFile}
        echo '"' >> ${OutputFile}
done
for i in ${AllSpecialAldoses} ; do                    
        echo 'i=$((i+1))' >> ${OutputFile}
        echo "TYPES[\${i}]=\" aglycon \" " >> ${OutputFile}
        echo 'NAMES[${i}]="' >> ${OutputFile}
        grep   ^1${i}$  ${ResidueNames} >> ${OutputFile}
        echo '"' >> ${OutputFile}
done

#####################
## Ketoses
#####################

## Plain hexose monosaccharides
TYPE_BASE=' carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown '
for i in C P B J ; do 
	## alpha D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	## beta D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
for i in c p b j ; do 
	## alpha L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}A$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	## beta L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}B$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
TYPE_BASE=' carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown '
for i in C P B J ; do 
	## alpha D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}D$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}D$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	## beta D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}U$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}U$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
for i in c p b j ; do 
	## alpha L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} alpha L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}D$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}D$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
	## beta L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} beta L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}U$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}U$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done

#####################
## Uloses
#####################
## Pyranose only
## KDO
TYPE_BASE=' carbohydrate monosaccharide pyranose ketose n-carbon=8 formal-charge=-1 alpha D-isomer deoxy ulosonate gauche-effect=unknown '
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} \" " >> ${OutputFile}
	echo 'NAMES[${i}]=" KDO "' >> ${OutputFile}
	echo 'KDO' >> ${ScriptHandledList}
## KDN 
TYPE_BASE=' carbohydrate monosaccharide pyranose ketose n-carbon=9 formal-charge=-1 alpha D-isomer deoxy ulosonate gauche-effect=unknown'
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} \" " >> ${OutputFile}
	echo 'NAMES[${i}]=" KDN "' >> ${OutputFile}
	echo 'KDN' >> ${ScriptHandledList}
## Neu5Ac Neu5Gc
TYPE_BASE=' carbohydrate monosaccharide pyranose ketose n-carbon=9 formal-charge=-1 alpha deoxy ulosonate gauche-effect=sialic-acid-tail '
for i in SA GL ; do 
	## alpha D
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
for i in sA gL ; do 
	## alpha L
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.${i}$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.${i}$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
done
TYPE_BASE=' carbohydrate monosaccharide pyranose ketose n-carbon=9 formal-charge=-1 beta deoxy ulosonate gauche-effect=sialic-acid-tail '
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} D-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.SB$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.SB$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}
TYPE_BASE=' carbohydrate monosaccharide pyranose ketose n-carbon=9 formal-charge=-1 beta deoxy ulosonate gauche-effect=sialic-acid-tail '
	echo 'i=$((i+1))' >> ${OutputFile}
	echo "TYPES[\${i}]=\" ${TYPE_BASE} L-isomer \" " >> ${OutputFile}
	echo 'NAMES[${i}]="' >> ${OutputFile}
    	grep   ^.sB$  ${ResidueNames} >> ${OutputFile}
    	grep   ^.sB$  ${ResidueNames} >> ${ScriptHandledList}
	echo '"' >> ${OutputFile}


## All ketoses that can be 'aglycon' terminals via anomeric-to-anomeric linkage
AllStandardKetoses=' C P B J c p b j S s '
AllSpecialKetoses=' GL gL '
echo "## aldose monosacharides that can be aglycons " >> ${OutputFile}
for i in ${AllStandardKetoses} ; do
        echo 'i=$((i+1))' >> ${OutputFile}
        echo "TYPES[\${i}]=\" aglycon \" " >> ${OutputFile}
        echo 'NAMES[${i}]="' >> ${OutputFile}
        grep   ^1${i}[ABDU]$  ${ResidueNames} >> ${OutputFile}
        echo '"' >> ${OutputFile}
done
for i in ${AllSpecialKetoses} ; do                    
        echo 'i=$((i+1))' >> ${OutputFile}
        echo "TYPES[\${i}]=\" aglycon \" " >> ${OutputFile}
        echo 'NAMES[${i}]="' >> ${OutputFile}
        grep   ^1${i}$  ${ResidueNames} >> ${OutputFile}
        echo '"' >> ${OutputFile}
done
