#!/bin/bash
##
##  File named 3_carbohydrate_residue_tags.bash generated by script 0_grep_residues.bash on Do 21 Dez 2023 12:53:26 CET.
##  This file contains definitions of the carbohydrate residues in 
##  the GLYCAM06 non-EP parameter set.
##
##  This file should be called from res-name-mappings.bash
##
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha D-isomer " 
NAMES[${i}]="
PTA
QTA
RTA
UTA
STA
VTA
XTA
6TA
TTA
WTA
YTA
4TA
ZTA
3TA
2TA
1TA
0TA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta D-isomer " 
NAMES[${i}]="
PTB
QTB
RTB
UTB
STB
VTB
XTB
6TB
TTB
WTB
YTB
4TB
ZTB
3TB
2TB
1TB
0TB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha D-isomer " 
NAMES[${i}]="
PNA
QNA
RNA
UNA
SNA
VNA
XNA
6NA
TNA
WNA
YNA
4NA
ZNA
3NA
2NA
1NA
0NA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta D-isomer " 
NAMES[${i}]="
PNB
QNB
RNB
UNB
SNB
VNB
XNB
6NB
TNB
WNB
YNB
4NB
ZNB
3NB
2NB
1NB
0NB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha D-isomer " 
NAMES[${i}]="
PEA
QEA
REA
UEA
SEA
VEA
XEA
6EA
TEA
WEA
YEA
4EA
ZEA
3EA
2EA
1EA
0EA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta D-isomer " 
NAMES[${i}]="
PEB
QEB
REB
UEB
SEB
VEB
XEB
6EB
TEB
WEB
YEB
4EB
ZEB
3EB
2EB
1EB
0EB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha D-isomer " 
NAMES[${i}]="
TFA
WFA
YFA
4FA
ZFA
3FA
2FA
1FA
0FA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta D-isomer " 
NAMES[${i}]="
TFB
WFB
YFB
4FB
ZFB
3FB
2FB
1FB
0FB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha D-isomer " 
NAMES[${i}]="
PLA
QLA
RLA
ULA
SLA
VLA
XLA
6LA
TLA
WLA
YLA
4LA
ZLA
3LA
2LA
1LA
0LA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta D-isomer " 
NAMES[${i}]="
PLB
QLB
RLB
ULB
SLB
VLB
XLB
6LB
TLB
WLB
YLB
4LB
ZLB
3LB
2LB
1LB
0LB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha D-isomer " 
NAMES[${i}]="
PGA
QGA
RGA
UGA
SGA
VGA
XGA
6GA
TGA
WGA
YGA
4GA
ZGA
3GA
2GA
1GA
0GA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta D-isomer " 
NAMES[${i}]="
PGB
QGB
RGB
UGB
SGB
VGB
XGB
6GB
TGB
WGB
YGB
4GB
ZGB
3GB
2GB
1GB
0GB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha D-isomer " 
NAMES[${i}]="
PKA
QKA
RKA
UKA
SKA
VKA
XKA
6KA
TKA
WKA
YKA
4KA
ZKA
3KA
2KA
1KA
0KA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta D-isomer " 
NAMES[${i}]="
PKB
QKB
RKB
UKB
SKB
VKB
XKB
6KB
TKB
WKB
YKB
4KB
ZKB
3KB
2KB
1KB
0KB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha D-isomer " 
NAMES[${i}]="
PMA
QMA
RMA
UMA
SMA
VMA
XMA
6MA
TMA
WMA
YMA
4MA
ZMA
3MA
2MA
1MA
0MA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta D-isomer " 
NAMES[${i}]="
PMB
QMB
RMB
UMB
SMB
VMB
XMB
6MB
TMB
WMB
YMB
4MB
ZMB
3MB
2MB
1MB
0MB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha D-isomer " 
NAMES[${i}]="
TQA
WQA
YQA
4QA
ZQA
3QA
2QA
1QA
0QA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta D-isomer " 
NAMES[${i}]="
TQB
WQB
YQB
4QB
ZQB
3QB
2QB
1QB
0QB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha D-isomer " 
NAMES[${i}]="
THA
WHA
YHA
4HA
ZHA
3HA
2HA
1HA
0HA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta D-isomer " 
NAMES[${i}]="
THB
WHB
YHB
4HB
ZHB
3HB
2HB
1HB
0HB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha L-isomer " 
NAMES[${i}]="
PtA
QtA
RtA
UtA
StA
VtA
XtA
6tA
TtA
WtA
YtA
4tA
ZtA
3tA
2tA
1tA
0tA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta L-isomer " 
NAMES[${i}]="
PtB
QtB
RtB
UtB
StB
VtB
XtB
6tB
TtB
WtB
YtB
4tB
ZtB
3tB
2tB
1tB
0tB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha L-isomer " 
NAMES[${i}]="
PnA
QnA
RnA
UnA
SnA
VnA
XnA
6nA
TnA
WnA
YnA
4nA
ZnA
3nA
2nA
1nA
0nA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta L-isomer " 
NAMES[${i}]="
PnB
QnB
RnB
UnB
SnB
VnB
XnB
6nB
TnB
WnB
YnB
4nB
ZnB
3nB
2nB
1nB
0nB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha L-isomer " 
NAMES[${i}]="
PeA
QeA
ReA
UeA
SeA
VeA
XeA
6eA
TeA
WeA
YeA
4eA
ZeA
3eA
2eA
1eA
0eA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta L-isomer " 
NAMES[${i}]="
PeB
QeB
ReB
UeB
SeB
VeB
XeB
6eB
TeB
WeB
YeB
4eB
ZeB
3eB
2eB
1eB
0eB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha L-isomer " 
NAMES[${i}]="
TfA
WfA
YfA
4fA
ZfA
3fA
2fA
1fA
0fA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta L-isomer " 
NAMES[${i}]="
TfB
WfB
YfB
4fB
ZfB
3fB
2fB
1fB
0fB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha L-isomer " 
NAMES[${i}]="
PlA
QlA
RlA
UlA
SlA
VlA
XlA
6lA
TlA
WlA
YlA
4lA
ZlA
3lA
2lA
1lA
0lA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta L-isomer " 
NAMES[${i}]="
PlB
QlB
RlB
UlB
SlB
VlB
XlB
6lB
TlB
WlB
YlB
4lB
ZlB
3lB
2lB
1lB
0lB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha L-isomer " 
NAMES[${i}]="
PgA
QgA
RgA
UgA
SgA
VgA
XgA
6gA
TgA
WgA
YgA
4gA
ZgA
3gA
2gA
1gA
0gA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta L-isomer " 
NAMES[${i}]="
PgB
QgB
RgB
UgB
SgB
VgB
XgB
6gB
TgB
WgB
YgB
4gB
ZgB
3gB
2gB
1gB
0gB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha L-isomer " 
NAMES[${i}]="
PkA
QkA
RkA
UkA
SkA
VkA
XkA
6kA
TkA
WkA
YkA
4kA
ZkA
3kA
2kA
1kA
0kA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta L-isomer " 
NAMES[${i}]="
PkB
QkB
RkB
UkB
SkB
VkB
XkB
6kB
TkB
WkB
YkB
4kB
ZkB
3kB
2kB
1kB
0kB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha L-isomer " 
NAMES[${i}]="
PmA
QmA
RmA
UmA
SmA
VmA
XmA
6mA
TmA
WmA
YmA
4mA
ZmA
3mA
2mA
1mA
0mA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta L-isomer " 
NAMES[${i}]="
PmB
QmB
RmB
UmB
SmB
VmB
XmB
6mB
TmB
WmB
YmB
4mB
ZmB
3mB
2mB
1mB
0mB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha L-isomer " 
NAMES[${i}]="
TqA
WqA
YqA
4qA
ZqA
3qA
2qA
1qA
0qA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta L-isomer " 
NAMES[${i}]="
TqB
WqB
YqB
4qB
ZqB
3qB
2qB
1qB
0qB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  alpha L-isomer " 
NAMES[${i}]="
ThA
WhA
YhA
4hA
ZhA
3hA
2hA
1hA
0hA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0  beta L-isomer " 
NAMES[${i}]="
ThB
WhB
YhB
4hB
ZhB
3hB
2hB
1hB
0hB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl  alpha D-isomer " 
NAMES[${i}]="
QVA
UVA
VVA
6VA
WVA
4VA
3VA
1VA
0VA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl  beta D-isomer " 
NAMES[${i}]="
QVB
UVB
VVB
6VB
WVB
4VB
3VB
1VB
0VB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl  alpha D-isomer " 
NAMES[${i}]="
QYA
UYA
VYA
6YA
WYA
4YA
3YA
1YA
0YA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl  beta D-isomer " 
NAMES[${i}]="
QYB
UYB
VYB
6YB
WYB
4YB
3YB
1YB
0YB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl  alpha D-isomer " 
NAMES[${i}]="
QWA
UWA
VWA
6WA
WWA
4WA
3WA
1WA
0WA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl  beta D-isomer " 
NAMES[${i}]="
QWB
UWB
VWB
6WB
WWB
4WB
3WB
1WB
0WB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl  alpha L-isomer " 
NAMES[${i}]="
QvA
UvA
VvA
6vA
WvA
4vA
3vA
1vA
0vA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl  beta L-isomer " 
NAMES[${i}]="
QvB
UvB
VvB
6vB
WvB
4vB
3vB
1vB
0vB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl  alpha L-isomer " 
NAMES[${i}]="
QyA
UyA
VyA
6yA
WyA
4yA
3yA
1yA
0yA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl  beta L-isomer " 
NAMES[${i}]="
QyB
UyB
VyB
6yB
WyB
4yB
3yB
1yB
0yB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl  alpha L-isomer " 
NAMES[${i}]="
QwA
UwA
VwA
6wA
WwA
4wA
3wA
1wA
0wA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl  beta L-isomer " 
NAMES[${i}]="
QwB
UwB
VwB
6wB
WwB
4wB
3wB
1wB
0wB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl beta gauche-effect=na  D-isomer " 
NAMES[${i}]="
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-acetyl beta gauche-effect=na  L-isomer " 
NAMES[${i}]="
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 amine D-isomer  alpha " 
NAMES[${i}]="
QYN
WYN
VYN
3YN
UYN
4YN
6YN
1YN
0YN
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 amine D-isomer  beta " 
NAMES[${i}]="
QYn
VYn
WYn
3Yn
UYn
6Yn
4Yn
1Yn
0Yn
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=+1 amine D-isomer protonated  alpha " 
NAMES[${i}]="
QYNP
WYNP
VYNP
3YNP
UYNP
4YNP
6YNP
1YNP
0YNP
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=+1 amine D-isomer protonated  beta " 
NAMES[${i}]="
QYnP
UYnP
VYnP
6YnP
WYnP
4YnP
3YnP
1YnP
0YnP
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-sulfo  alpha D-isomer " 
NAMES[${i}]="
QYS
UYS
VYS
6YS
WYS
4YS
3YS
1YS
0YS
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-sulfo  beta D-isomer " 
NAMES[${i}]="
QYs
UYs
VYs
6Ys
WYs
4Ys
3Ys
1Ys
0Ys
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-sulfo  alpha L-isomer " 
NAMES[${i}]="
QyS
UyS
VyS
6yS
WyS
4yS
3yS
1yS
0yS
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=0 N-sulfo  beta L-isomer " 
NAMES[${i}]="
Qys
Uys
Vys
6ys
Wys
4ys
3ys
1ys
0ys
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=-1 uronate gauche-effect=na  alpha D-isomer " 
NAMES[${i}]="
TOA
WOA
YOA
4OA
ZOA
3OA
2OA
1OA
0OA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=-1 uronate gauche-effect=na  beta D-isomer " 
NAMES[${i}]="
TOB
WOB
YOB
4OB
ZOB
3OB
2OB
1OB
0OB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=-1 uronate gauche-effect=na  alpha D-isomer " 
NAMES[${i}]="
TZA
WZA
YZA
4ZA
ZZA
3ZA
2ZA
1ZA
0ZA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=-1 uronate gauche-effect=na  beta D-isomer " 
NAMES[${i}]="
TZB
WZB
YZB
4ZB
ZZB
3ZB
2ZB
1ZB
0ZB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=-1 uronate gauche-effect=na  alpha D-isomer " 
NAMES[${i}]="
TUA
WUA
YUA
4UA
ZUA
3UA
2UA
1UA
0UA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=-1 uronate gauche-effect=na  beta D-isomer " 
NAMES[${i}]="
TUB
WUB
YUB
4UB
ZUB
3UB
2UB
1UB
0UB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=-1 uronate gauche-effect=na  alpha L-isomer " 
NAMES[${i}]="
ToA
WoA
YoA
4oA
ZoA
3oA
2oA
1oA
0oA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=-1 uronate gauche-effect=na  beta L-isomer " 
NAMES[${i}]="
ToB
WoB
YoB
4oB
ZoB
3oB
2oB
1oB
0oB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=-1 uronate gauche-effect=na  alpha L-isomer " 
NAMES[${i}]="
TzA
WzA
YzA
4zA
ZzA
3zA
2zA
1zA
0zA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=-1 uronate gauche-effect=na  beta L-isomer " 
NAMES[${i}]="
TzB
WzB
YzB
4zB
ZzB
3zB
2zB
1zB
0zB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=-1 uronate gauche-effect=na  alpha L-isomer " 
NAMES[${i}]="
TuA
WuA
YuA
4uA
ZuA
3uA
2uA
1uA
0uA
4uA3
0uA1
4uA1
4uA2
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=-1 uronate gauche-effect=na  beta L-isomer " 
NAMES[${i}]="
TuB
WuB
YuB
4uB
ZuB
3uB
2uB
1uB
0uB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 alpha L-isomer formal-charge=0 uronate protonated gauche-effect=na  " 
NAMES[${i}]=" YuAP "
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 beta D-isomer formal-charge=0 uronate protonated gauche-effect=na  " 
NAMES[${i}]=" 0ZBP "
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=6 formal-charge=-1 uronate unsaturated-uronate gauche-effect=na  " 
NAMES[${i}]=" 045 245 "
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
PNA
QNA
RNA
UNA
SNA
VNA
XNA
6NA
TNA
WNA
YNA
4NA
ZNA
3NA
2NA
1NA
0NA
PNB
QNB
RNB
UNB
SNB
VNB
XNB
6NB
TNB
WNB
YNB
4NB
ZNB
3NB
2NB
1NB
0NB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
PEA
QEA
REA
UEA
SEA
VEA
XEA
6EA
TEA
WEA
YEA
4EA
ZEA
3EA
2EA
1EA
0EA
PEB
QEB
REB
UEB
SEB
VEB
XEB
6EB
TEB
WEB
YEB
4EB
ZEB
3EB
2EB
1EB
0EB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
PGA
QGA
RGA
UGA
SGA
VGA
XGA
6GA
TGA
WGA
YGA
4GA
ZGA
3GA
2GA
1GA
0GA
PGB
QGB
RGB
UGB
SGB
VGB
XGB
6GB
TGB
WGB
YGB
4GB
ZGB
3GB
2GB
1GB
0GB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
PMA
QMA
RMA
UMA
SMA
VMA
XMA
6MA
TMA
WMA
YMA
4MA
ZMA
3MA
2MA
1MA
0MA
PMB
QMB
RMB
UMB
SMB
VMB
XMB
6MB
TMB
WMB
YMB
4MB
ZMB
3MB
2MB
1MB
0MB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
QYA
UYA
VYA
6YA
WYA
4YA
3YA
1YA
0YA
QYB
UYB
VYB
6YB
WYB
4YB
3YB
1YB
0YB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
QWA
UWA
VWA
6WA
WWA
4WA
3WA
1WA
0WA
QWB
UWB
VWB
6WB
WWB
4WB
3WB
1WB
0WB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
PnA
QnA
RnA
UnA
SnA
VnA
XnA
6nA
TnA
WnA
YnA
4nA
ZnA
3nA
2nA
1nA
0nA
PnB
QnB
RnB
UnB
SnB
VnB
XnB
6nB
TnB
WnB
YnB
4nB
ZnB
3nB
2nB
1nB
0nB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
PeA
QeA
ReA
UeA
SeA
VeA
XeA
6eA
TeA
WeA
YeA
4eA
ZeA
3eA
2eA
1eA
0eA
PeB
QeB
ReB
UeB
SeB
VeB
XeB
6eB
TeB
WeB
YeB
4eB
ZeB
3eB
2eB
1eB
0eB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
PgA
QgA
RgA
UgA
SgA
VgA
XgA
6gA
TgA
WgA
YgA
4gA
ZgA
3gA
2gA
1gA
0gA
PgB
QgB
RgB
UgB
SgB
VgB
XgB
6gB
TgB
WgB
YgB
4gB
ZgB
3gB
2gB
1gB
0gB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
PmA
QmA
RmA
UmA
SmA
VmA
XmA
6mA
TmA
WmA
YmA
4mA
ZmA
3mA
2mA
1mA
0mA
PmB
QmB
RmB
UmB
SmB
VmB
XmB
6mB
TmB
WmB
YmB
4mB
ZmB
3mB
2mB
1mB
0mB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
QyA
UyA
VyA
6yA
WyA
4yA
3yA
1yA
0yA
QyB
UyB
VyB
6yB
WyB
4yB
3yB
1yB
0yB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
QwA
UwA
VwA
6wA
WwA
4wA
3wA
1wA
0wA
QwB
UwB
VwB
6wB
WwB
4wB
3wB
1wB
0wB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
QYN
WYN
VYN
3YN
UYN
4YN
6YN
1YN
0YN
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
QYn
VYn
WYn
3Yn
UYn
6Yn
4Yn
1Yn
0Yn
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
QYNP
WYNP
VYNP
3YNP
UYNP
4YNP
6YNP
1YNP
0YNP
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
QYnP
UYnP
VYnP
6YnP
WYnP
4YnP
3YnP
1YnP
0YnP
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
QYS
UYS
VYS
6YS
WYS
4YS
3YS
1YS
0YS
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
QYs
UYs
VYs
6Ys
WYs
4Ys
3Ys
1Ys
0Ys
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
QyS
UyS
VyS
6yS
WyS
4yS
3yS
1yS
0yS
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=gluco " 
NAMES[${i}]="
Qys
Uys
Vys
6ys
Wys
4ys
3ys
1ys
0ys
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=galacto " 
NAMES[${i}]="
PTA
QTA
RTA
UTA
STA
VTA
XTA
6TA
TTA
WTA
YTA
4TA
ZTA
3TA
2TA
1TA
0TA
PTB
QTB
RTB
UTB
STB
VTB
XTB
6TB
TTB
WTB
YTB
4TB
ZTB
3TB
2TB
1TB
0TB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=galacto " 
NAMES[${i}]="
PLA
QLA
RLA
ULA
SLA
VLA
XLA
6LA
TLA
WLA
YLA
4LA
ZLA
3LA
2LA
1LA
0LA
PLB
QLB
RLB
ULB
SLB
VLB
XLB
6LB
TLB
WLB
YLB
4LB
ZLB
3LB
2LB
1LB
0LB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=galacto " 
NAMES[${i}]="
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=galacto " 
NAMES[${i}]="
PKA
QKA
RKA
UKA
SKA
VKA
XKA
6KA
TKA
WKA
YKA
4KA
ZKA
3KA
2KA
1KA
0KA
PKB
QKB
RKB
UKB
SKB
VKB
XKB
6KB
TKB
WKB
YKB
4KB
ZKB
3KB
2KB
1KB
0KB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=galacto " 
NAMES[${i}]="
QVA
UVA
VVA
6VA
WVA
4VA
3VA
1VA
0VA
QVB
UVB
VVB
6VB
WVB
4VB
3VB
1VB
0VB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=galacto " 
NAMES[${i}]="
PtA
QtA
RtA
UtA
StA
VtA
XtA
6tA
TtA
WtA
YtA
4tA
ZtA
3tA
2tA
1tA
0tA
PtB
QtB
RtB
UtB
StB
VtB
XtB
6tB
TtB
WtB
YtB
4tB
ZtB
3tB
2tB
1tB
0tB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=galacto " 
NAMES[${i}]="
PlA
QlA
RlA
UlA
SlA
VlA
XlA
6lA
TlA
WlA
YlA
4lA
ZlA
3lA
2lA
1lA
0lA
PlB
QlB
RlB
UlB
SlB
VlB
XlB
6lB
TlB
WlB
YlB
4lB
ZlB
3lB
2lB
1lB
0lB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=galacto " 
NAMES[${i}]="
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=galacto " 
NAMES[${i}]="
PkA
QkA
RkA
UkA
SkA
VkA
XkA
6kA
TkA
WkA
YkA
4kA
ZkA
3kA
2kA
1kA
0kA
PkB
QkB
RkB
UkB
SkB
VkB
XkB
6kB
TkB
WkB
YkB
4kB
ZkB
3kB
2kB
1kB
0kB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=galacto " 
NAMES[${i}]="
QvA
UvA
VvA
6vA
WvA
4vA
3vA
1vA
0vA
QvB
UvB
VvB
6vB
WvB
4vB
3vB
1vB
0vB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=na " 
NAMES[${i}]="
TFA
WFA
YFA
4FA
ZFA
3FA
2FA
1FA
0FA
TFB
WFB
YFB
4FB
ZFB
3FB
2FB
1FB
0FB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=na " 
NAMES[${i}]="
TQA
WQA
YQA
4QA
ZQA
3QA
2QA
1QA
0QA
TQB
WQB
YQB
4QB
ZQB
3QB
2QB
1QB
0QB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=na " 
NAMES[${i}]="
THA
WHA
YHA
4HA
ZHA
3HA
2HA
1HA
0HA
THB
WHB
YHB
4HB
ZHB
3HB
2HB
1HB
0HB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=na " 
NAMES[${i}]="
TfA
WfA
YfA
4fA
ZfA
3fA
2fA
1fA
0fA
TfB
WfB
YfB
4fB
ZfB
3fB
2fB
1fB
0fB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=na " 
NAMES[${i}]="
TqA
WqA
YqA
4qA
ZqA
3qA
2qA
1qA
0qA
TqB
WqB
YqB
4qB
ZqB
3qB
2qB
1qB
0qB
"
i=$((i + 1))
TYPES[${i}]=" gauche-effect=na " 
NAMES[${i}]="
ThA
WhA
YhA
4hA
ZhA
3hA
2hA
1hA
0hA
ThB
WhB
YhB
4hB
ZhB
3hB
2hB
1hB
0hB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  alpha D-isomer " 
NAMES[${i}]="
TAA
WAA
YAA
4AA
ZAA
3AA
2AA
1AA
0AA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  beta D-isomer " 
NAMES[${i}]="
TAB
WAB
YAB
4AB
ZAB
3AB
2AB
1AB
0AB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  alpha D-isomer " 
NAMES[${i}]="
TDA
WDA
YDA
4DA
ZDA
3DA
2DA
1DA
0DA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  beta D-isomer " 
NAMES[${i}]="
TDB
WDB
YDB
4DB
ZDB
3DB
2DB
1DB
0DB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  alpha D-isomer " 
NAMES[${i}]="
TRA
WRA
YRA
4RA
ZRA
3RA
2RA
1RA
0RA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  beta D-isomer " 
NAMES[${i}]="
TRB
WRB
YRB
4RB
ZRB
3RB
2RB
1RB
0RB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  alpha D-isomer " 
NAMES[${i}]="
TXA
WXA
YXA
4XA
ZXA
3XA
2XA
1XA
0XA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  beta D-isomer " 
NAMES[${i}]="
TXB
WXB
YXB
4XB
ZXB
3XB
2XB
1XB
0XB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  alpha L-isomer " 
NAMES[${i}]="
TaA
WaA
YaA
4aA
ZaA
3aA
2aA
1aA
0aA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  beta L-isomer " 
NAMES[${i}]="
TaB
WaB
YaB
4aB
ZaB
3aB
2aB
1aB
0aB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  alpha L-isomer " 
NAMES[${i}]="
TdA
WdA
YdA
4dA
ZdA
3dA
2dA
1dA
0dA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  beta L-isomer " 
NAMES[${i}]="
TdB
WdB
YdB
4dB
ZdB
3dB
2dB
1dB
0dB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  alpha L-isomer " 
NAMES[${i}]="
TrA
WrA
YrA
4rA
ZrA
3rA
2rA
1rA
0rA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  beta L-isomer " 
NAMES[${i}]="
TrB
WrB
YrB
4rB
ZrB
3rB
2rB
1rB
0rB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  alpha L-isomer " 
NAMES[${i}]="
TxA
WxA
YxA
4xA
ZxA
3xA
2xA
1xA
0xA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 gauche-effect=na  beta L-isomer " 
NAMES[${i}]="
TxB
WxB
YxB
4xB
ZxB
3xB
2xB
1xB
0xB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  alpha D-isomer " 
NAMES[${i}]="
nAD
tAD
uAD
5AD
ZAD
3AD
2AD
1AD
0AD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  beta D-isomer " 
NAMES[${i}]="
nAU
tAU
uAU
5AU
ZAU
3AU
2AU
1AU
0AU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  alpha D-isomer " 
NAMES[${i}]="
nDD
tDD
uDD
5DD
ZDD
3DD
2DD
1DD
0DD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  beta D-isomer " 
NAMES[${i}]="
nDU
tDU
uDU
5DU
ZDU
3DU
2DU
1DU
0DU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  alpha D-isomer " 
NAMES[${i}]="
nRD
tRD
uRD
5RD
ZRD
3RD
2RD
1RD
0RD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  beta D-isomer " 
NAMES[${i}]="
nRU
tRU
uRU
5RU
ZRU
3RU
2RU
1RU
0RU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  alpha D-isomer " 
NAMES[${i}]="
nXD
tXD
uXD
5XD
ZXD
3XD
2XD
1XD
0XD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  beta D-isomer " 
NAMES[${i}]="
nXU
tXU
uXU
5XU
ZXU
3XU
2XU
1XU
0XU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  alpha L-isomer " 
NAMES[${i}]="
naD
taD
uaD
5aD
ZaD
3aD
2aD
1aD
0aD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  beta L-isomer " 
NAMES[${i}]="
naU
taU
uaU
5aU
ZaU
3aU
2aU
1aU
0aU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  alpha L-isomer " 
NAMES[${i}]="
ndD
tdD
udD
5dD
ZdD
3dD
2dD
1dD
0dD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  beta L-isomer " 
NAMES[${i}]="
ndU
tdU
udU
5dU
ZdU
3dU
2dU
1dU
0dU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  alpha L-isomer " 
NAMES[${i}]="
nrD
trD
urD
5rD
ZrD
3rD
2rD
1rD
0rD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  beta L-isomer " 
NAMES[${i}]="
nrU
trU
urU
5rU
ZrU
3rU
2rU
1rU
0rU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  alpha L-isomer " 
NAMES[${i}]="
nxD
txD
uxD
5xD
ZxD
3xD
2xD
1xD
0xD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose aldose n-carbon=5 formal-charge=0 gauche-effect=unknown  beta L-isomer " 
NAMES[${i}]="
nxU
txU
uxU
5xU
ZxU
3xU
2xU
1xU
0xU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 deoxy gauche-effect=na  alpha D-isomer " 
NAMES[${i}]="
YAE
2AE
4AE
1AE
0AE
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 deoxy gauche-effect=na  alpha D-isomer " 
NAMES[${i}]="
YTV
4TV
2TV
1TV
0TV
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 deoxy gauche-effect=na  beta D-isomer " 
NAMES[${i}]="
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 deoxy gauche-effect=na  beta D-isomer " 
NAMES[${i}]="
YTv
4Tv
2Tv
1Tv
0Tv
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 deoxy gauche-effect=na  alpha L-isomer " 
NAMES[${i}]="
YtV
4tV
2tV
1tV
0tV
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose aldose n-carbon=5 formal-charge=0 deoxy gauche-effect=na  beta L-isomer " 
NAMES[${i}]="
Ytv
4tv
2tv
1tv
0tv
"
## aldose monosacharides that can be aglycons 
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1TA
1TB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1NA
1NB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1EA
1EB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1FA
1FB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1LA
1LB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1GA
1GB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1KA
1KB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1MA
1MB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1QA
1QB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1HA
1HB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1tA
1tB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1nA
1nB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1eA
1eB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1fA
1fB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1lA
1lB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1gA
1gB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1kA
1kB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1mA
1mB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1qA
1qB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1hA
1hB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1VA
1VB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1YA
1YB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1WA
1WB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1vA
1vB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1yA
1yB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1wA
1wB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1OA
1OB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1ZA
1ZB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1UA
1UB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1oA
1oB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1zA
1zB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1uA
1uB
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1AA
1AB
1AD
1AU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1DA
1DB
1DD
1DU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1RA
1RB
1RD
1RU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1XA
1XB
1XD
1XU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1aA
1aB
1aD
1aU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1dA
1dB
1dD
1dU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1rA
1rB
1rD
1rU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1xA
1xB
1xD
1xU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1AE
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1TV
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1Tv
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1tV
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1tv
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1YN
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1Yn
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1YNP
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1YnP
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1YS
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1Ys
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1yS
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1ys
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha D-isomer " 
NAMES[${i}]="
yCA
vCA
nCA
uCA
TCA
YCA
ZCA
1CA
xCA
sCA
tCA
5CA
WCA
4CA
3CA
2CA
0CA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta D-isomer " 
NAMES[${i}]="
yCB
xCB
vCB
sCB
nCB
tCB
uCB
5CB
TCB
WCB
YCB
4CB
ZCB
3CB
1CB
2CB
0CB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha D-isomer " 
NAMES[${i}]="
yPA
vPA
nPA
uPA
TPA
YPA
ZPA
1PA
xPA
sPA
tPA
5PA
WPA
4PA
3PA
2PA
0PA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta D-isomer " 
NAMES[${i}]="
yPB
xPB
vPB
sPB
nPB
tPB
uPB
5PB
TPB
WPB
YPB
4PB
ZPB
3PB
1PB
2PB
0PB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha D-isomer " 
NAMES[${i}]="
yBA
vBA
nBA
uBA
TBA
YBA
ZBA
1BA
xBA
sBA
tBA
5BA
WBA
4BA
3BA
2BA
0BA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta D-isomer " 
NAMES[${i}]="
yBB
xBB
vBB
sBB
nBB
tBB
uBB
5BB
TBB
WBB
YBB
4BB
ZBB
3BB
1BB
2BB
0BB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha D-isomer " 
NAMES[${i}]="
yJA
vJA
nJA
uJA
TJA
YJA
ZJA
1JA
xJA
sJA
tJA
5JA
WJA
4JA
3JA
2JA
0JA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta D-isomer " 
NAMES[${i}]="
yJB
xJB
vJB
sJB
nJB
tJB
uJB
5JB
TJB
WJB
YJB
4JB
ZJB
3JB
1JB
2JB
0JB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha L-isomer " 
NAMES[${i}]="
ycA
xcA
vcA
scA
ncA
tcA
ucA
5cA
TcA
WcA
YcA
4cA
ZcA
3cA
1cA
2cA
0cA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta L-isomer " 
NAMES[${i}]="
ycB
vcB
ncB
ucB
TcB
YcB
ZcB
1cB
xcB
scB
tcB
5cB
WcB
4cB
3cB
2cB
0cB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha L-isomer " 
NAMES[${i}]="
ypA
xpA
vpA
spA
npA
tpA
upA
5pA
TpA
WpA
YpA
4pA
ZpA
3pA
1pA
2pA
0pA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta L-isomer " 
NAMES[${i}]="
ypB
vpB
npB
upB
TpB
YpB
ZpB
1pB
xpB
spB
tpB
5pB
WpB
4pB
3pB
2pB
0pB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha L-isomer " 
NAMES[${i}]="
ybA
xbA
vbA
sbA
nbA
tbA
ubA
5bA
TbA
WbA
YbA
4bA
ZbA
3bA
1bA
2bA
0bA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta L-isomer " 
NAMES[${i}]="
ybB
vbB
nbB
ubB
TbB
YbB
ZbB
1bB
xbB
sbB
tbB
5bB
WbB
4bB
3bB
2bB
0bB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha L-isomer " 
NAMES[${i}]="
yjA
xjA
vjA
sjA
njA
tjA
ujA
5jA
TjA
WjA
YjA
4jA
ZjA
3jA
1jA
2jA
0jA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta L-isomer " 
NAMES[${i}]="
yjB
vjB
njB
ujB
TjB
YjB
ZjB
1jB
xjB
sjB
tjB
5jB
WjB
4jB
3jB
2jB
0jB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha D-isomer " 
NAMES[${i}]="
PCD
RCD
SCD
XCD
TCD
YCD
ZCD
1CD
QCD
UCD
VCD
6CD
WCD
4CD
3CD
2CD
0CD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta D-isomer " 
NAMES[${i}]="
PCU
QCU
RCU
UCU
SCU
VCU
XCU
6CU
TCU
WCU
YCU
4CU
ZCU
3CU
1CU
2CU
0CU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha D-isomer " 
NAMES[${i}]="
PPD
RPD
SPD
XPD
TPD
YPD
ZPD
1PD
QPD
UPD
VPD
6PD
WPD
4PD
3PD
2PD
0PD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta D-isomer " 
NAMES[${i}]="
PPU
QPU
RPU
UPU
SPU
VPU
XPU
6PU
TPU
WPU
YPU
4PU
ZPU
3PU
1PU
2PU
0PU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha D-isomer " 
NAMES[${i}]="
PBD
RBD
SBD
XBD
TBD
YBD
ZBD
1BD
QBD
UBD
VBD
6BD
WBD
4BD
3BD
2BD
0BD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta D-isomer " 
NAMES[${i}]="
PBU
QBU
RBU
UBU
SBU
VBU
XBU
6BU
TBU
WBU
YBU
4BU
ZBU
3BU
1BU
2BU
0BU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha D-isomer " 
NAMES[${i}]="
PJD
RJD
SJD
XJD
TJD
YJD
ZJD
1JD
QJD
UJD
VJD
6JD
WJD
4JD
3JD
2JD
0JD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta D-isomer " 
NAMES[${i}]="
PJU
QJU
RJU
UJU
SJU
VJU
XJU
6JU
TJU
WJU
YJU
4JU
ZJU
3JU
1JU
2JU
0JU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha L-isomer " 
NAMES[${i}]="
PcD
QcD
RcD
UcD
ScD
VcD
XcD
6cD
TcD
WcD
YcD
4cD
ZcD
3cD
1cD
2cD
0cD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta L-isomer " 
NAMES[${i}]="
PcU
RcU
ScU
XcU
TcU
YcU
ZcU
1cU
QcU
UcU
VcU
6cU
WcU
4cU
3cU
2cU
0cU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha L-isomer " 
NAMES[${i}]="
PpD
QpD
RpD
UpD
SpD
VpD
XpD
6pD
TpD
WpD
YpD
4pD
ZpD
3pD
1pD
2pD
0pD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta L-isomer " 
NAMES[${i}]="
PpU
RpU
SpU
XpU
TpU
YpU
ZpU
1pU
QpU
UpU
VpU
6pU
WpU
4pU
3pU
2pU
0pU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha L-isomer " 
NAMES[${i}]="
PbD
QbD
RbD
UbD
SbD
VbD
XbD
6bD
TbD
WbD
YbD
4bD
ZbD
3bD
1bD
2bD
0bD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta L-isomer " 
NAMES[${i}]="
PbU
RbU
SbU
XbU
TbU
YbU
ZbU
1bU
QbU
UbU
VbU
6bU
WbU
4bU
3bU
2bU
0bU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  alpha L-isomer " 
NAMES[${i}]="
PjD
QjD
RjD
UjD
SjD
VjD
XjD
6jD
TjD
WjD
YjD
4jD
ZjD
3jD
1jD
2jD
0jD
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide furanose ketose n-carbon=6 formal-charge=0 gauche-effect=unknown  beta L-isomer " 
NAMES[${i}]="
PjU
RjU
SjU
XjU
TjU
YjU
ZjU
1jU
QjU
UjU
VjU
6jU
WjU
4jU
3jU
2jU
0jU
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=8 formal-charge=-1 alpha D-isomer deoxy ulosonate gauche-effect=unknown  " 
NAMES[${i}]=" 0KO "
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=9 formal-charge=-1 alpha D-isomer deoxy ulosonate gauche-effect=unknown " 
NAMES[${i}]=" 0KN "
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=9 formal-charge=-1 alpha deoxy ulosonate gauche-effect=sialic-acid-tail  D-isomer internal" 
NAMES[${i}]="
ASA
BSA
CSA
FSA
DSA
GSA
ISA
9SA
ESA
HSA
JSA
8SA
KSA
7SA
4SA
2SA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=9 formal-charge=-1 alpha deoxy ulosonate gauche-effect=sialic-acid-tail  D-isomer external" 
NAMES[${i}]="
0SA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=9 formal-charge=-1 alpha deoxy ulosonate gauche-effect=sialic-acid-tail  D-isomer internal" 
NAMES[${i}]="
AGL
BGL
CGL
FGL
DGL
GGL
IGL
9GL
EGL
HGL
JGL
8GL
KGL
7GL
4GL
2GL
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=9 formal-charge=-1 alpha deoxy ulosonate gauche-effect=sialic-acid-tail  D-isomer external" 
NAMES[${i}]="
0GL
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=9 formal-charge=-1 alpha deoxy ulosonate gauche-effect=sialic-acid-tail  L-isomer " 
NAMES[${i}]="
AsA
BsA
EsA
HsA
DsA
GsA
KsA
7sA
CsA
FsA
JsA
8sA
IsA
9sA
4sA
2sA
0sA
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=9 formal-charge=-1 alpha deoxy ulosonate gauche-effect=sialic-acid-tail  L-isomer " 
NAMES[${i}]="
AgL
BgL
EgL
HgL
DgL
GgL
KgL
7gL
CgL
FgL
JgL
8gL
IgL
9gL
4gL
2gL
0gL
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=9 formal-charge=-1 beta deoxy ulosonate gauche-effect=sialic-acid-tail  D-isomer " 
NAMES[${i}]="
ASB
BSB
ESB
HSB
DSB
GSB
KSB
7SB
CSB
FSB
JSB
8SB
ISB
9SB
4SB
2SB
0SB
"
i=$((i + 1))
TYPES[${i}]="  carbohydrate monosaccharide pyranose ketose n-carbon=9 formal-charge=-1 beta deoxy ulosonate gauche-effect=sialic-acid-tail  L-isomer " 
NAMES[${i}]="
AsB
BsB
CsB
FsB
DsB
GsB
IsB
9sB
EsB
HsB
JsB
8sB
KsB
7sB
4sB
2sB
0sB
"
## aldose monosacharides that can be aglycons 
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1CA
1CB
1CD
1CU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1PA
1PB
1PD
1PU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1BA
1BB
1BD
1BU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1JA
1JB
1JD
1JU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1cA
1cB
1cD
1cU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1pA
1pB
1pD
1pU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1bA
1bB
1bD
1bU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
1jA
1jB
1jD
1jU
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
"
i=$((i + 1))
TYPES[${i}]=" aglycon " 
NAMES[${i}]="
"
