gmmlNew: PrepFileSpace::PrepFile Class Reference
PrepFileSpace::PrepFile Class Reference
#include <prepfile.hpp>
Public Types
typedef std::map< std::string,
PrepFileResidue * > ResidueMap
Public Member Functions
PrepFile (const std::string &prep_file)
PrepFile ()
~PrepFile ()
ResidueMap & GetResidues ()
std::vector< std::string > GetAllResidueNames ()
gmml::ResidueNameMap GetAllResidueNamesMap ()
std::vector< std::string > GetAllAtomNamesOfResidue (std::string residue_name)
void SetPath (std::string path)
void SetResidues (ResidueMap residues)
void Read (std::ifstream &in_file)
PrepFileResidue * ProcessResidueSection (std::ifstream &in_file)
void Write (const std::string &prep_file)
void BuildPrepFile (std::ofstream &out_stream)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 13 of file prepfile.hpp.
Member Typedef Documentation
typedef std::map< std::string, PrepFileResidue* > PrepFileSpace::PrepFile::ResidueMap
Definition at line 22 of file prepfile.hpp.
Constructor & Destructor Documentation
PrepFile::PrepFile (const std::string & prep_file)
Close the parameter files
Definition at line 19 of file prepfile.cc.
{
    path_ = prep_file;
    std::ifstream in_file;
    if(std::ifstream(prep_file.c_str()))
        in_file.open(prep_file.c_str());
    else
    {
        throw PrepFileProcessingException(__LINE__, "Prep file not found");
    }
    Read(in_file);
    in_file.close();            /// Close the parameter files
}
PrepFile::PrepFile ()
Definition at line 33 of file prepfile.cc.
{
    path_ = "";
    residues_ = ResidueMap();
}
PrepFile::~PrepFile ()
Definition at line 39 of file prepfile.cc.
{
    residues_.clear();
    residues_ = ResidueMap();
}
Member Function Documentation
void PrepFile::BuildPrepFile (std::ofstream & out_stream)
Definition at line 148 of file prepfile.cc.
References gmml::dNotSet, PrepFileSpace::PrepFileAtom::GetAngle(), PrepFileSpace::PrepFileAtom::GetAngleIndex(), PrepFileSpace::PrepFileResidue::GetAtomNameByIndex(), PrepFileSpace::PrepFileResidue::GetAtoms(), PrepFileSpace::PrepFileAtom::GetBondIndex(), PrepFileSpace::PrepFileAtom::GetBondLength(), PrepFileSpace::PrepFileAtom::GetCharge(), PrepFileSpace::PrepFileResidue::GetCharge(), PrepFileSpace::PrepFileAtom::GetDihedral(), PrepFileSpace::PrepFileAtom::GetDihedralIndex(), PrepFileSpace::PrepFileResidue::GetDummyAtomType(), PrepFileSpace::PrepFileResidue::GetImproperDihedrals(), PrepFileSpace::PrepFileAtom::GetIndex(), PrepFileSpace::PrepFileResidue::GetLoops(), PrepFileSpace::PrepFileAtom::GetName(), PrepFileSpace::PrepFileResidue::GetName(), PrepFileSpace::PrepFileResidue::GetStringFormatOfCoordinateType(), PrepFileSpace::PrepFileResidue::GetStringFormatOfDummyAtomOmission(), PrepFileSpace::PrepFileResidue::GetStringFormatOfDummyAtomPosition(), PrepFileSpace::PrepFileResidue::GetStringFormatOfGeometryType(), PrepFileSpace::PrepFileResidue::GetStringFormatOfOutputFormat(), PrepFileSpace::PrepFileAtom::GetStringFormatOfTopologicalType(), PrepFileSpace::PrepFileResidue::GetTitle(), and PrepFileSpace::PrepFileAtom::GetType().
{
    stream << endl
           << endl;
    for(ResidueMap::iterator it = residues_.begin(); it != residues_.end(); it++)
    {
        PrepFileResidue* residue = (*it).second;
        stream << residue->GetTitle() << endl << endl
               << left << setw(4) << residue->GetName() << " " << right << setw(3) << residue->GetStringFormatOfCoordinateType() << " "
               << setw(1) << residue->GetStringFormatOfOutputFormat() << endl
               << residue->GetStringFormatOfGeometryType() << " " << residue->GetStringFormatOfDummyAtomOmission() << " "
               << residue->GetDummyAtomType() << " " << residue->GetStringFormatOfDummyAtomPosition() << endl
               << right << setw(8) << fixed << setprecision(3) << residue->GetCharge() << endl;
        PrepFileResidue::PrepFileAtomVector atoms = residue->GetAtoms();
        for(PrepFileResidue::PrepFileAtomVector::iterator it1 = atoms.begin(); it1 != atoms.end(); it1++)
        {
            PrepFileAtom* atom = (*it1);
            stream << right << setw(2) << atom->GetIndex() << " " << left << setw(4) << atom->GetName() << " " << left << setw(3) << atom->GetType() << " "
                   << setw(1) << atom->GetStringFormatOfTopologicalType() << " " << right << setw(2) << atom->GetBondIndex() << " " << right << setw(2) << atom->GetAngleIndex() << " "
                   << right << setw(2) << atom->GetDihedralIndex() << " ";
            if(atom->GetBondLength() != dNotSet)
                stream << right << setw(8) << fixed << setprecision(3) << atom->GetBondLength() << " ";
            else
                stream << right << setw(8) << fixed << setprecision(3) << 0.0 << " ";
            if(atom->GetAngle() != dNotSet)
                   stream << right << setw(8) << fixed << setprecision(3) << atom->GetAngle() << " ";
            else
                stream << right << setw(8) << fixed << setprecision(3) << 0.0 << " ";
            if(atom->GetDihedral() != dNotSet)
                stream << right << setw(8) << fixed << setprecision(3) << atom->GetDihedral();
            else
                stream << right << setw(8) << fixed << setprecision(3) << 0.0;
            stream << "    " << right << setw(8) << fixed << setprecision(4) << atom->GetCharge() << endl;
        }
        stream << endl;
        PrepFileResidue::DihedralVector dihedrals = residue->GetImproperDihedrals();
        if (dihedrals.size() != 0)
        {
            stream << "IMPROPER" << endl;
            for(PrepFileResidue::DihedralVector::iterator it2 = dihedrals.begin(); it2 != dihedrals.end(); it2++)
            {
                PrepFileResidue::Dihedral dihedral = (*it2);
                stream << left << setw(4) << dihedral.at(0) << left << setw(4) << dihedral.at(1) << left << setw(4) << dihedral.at(2) << left << setw(4) << dihedral.at(3) << endl
                       << endl;
            }
        }
        PrepFileResidue::Loop loops = residue->GetLoops();
        if(loops.size() != 0)
        {
            stream << "LOOP" << endl;
            for(PrepFileResidue::Loop::iterator it3 = loops.begin(); it3 != loops.end(); it3++)
            {
                int first_atom_index = (*it3).first;
                int second_atom_index = (*it3).second;
                stream << residue->GetAtomNameByIndex(first_atom_index) << " " << residue->GetAtomNameByIndex(second_atom_index) << endl;
            }
        }
        stream << endl
               << "DONE" << endl;
    }
    stream << "STOP";
}
vector< string > PrepFile::GetAllAtomNamesOfResidue (std::string residue_name)
Definition at line 72 of file prepfile.cc.
References PrepFileSpace::PrepFileResidue::GetAtoms(), and PrepFileSpace::PrepFileAtom::GetName().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::GetAllAtomNamesOfResidueFromMultiplePrepFiles().
{
    vector<string> atom_names_of_residue;
    ResidueMap residue_map = GetResidues();
    PrepFileResidue* prep_file_residue = residue_map[residue_name];
    vector<PrepFileAtom*> atoms = prep_file_residue->GetAtoms();
    for(vector<PrepFileAtom*>::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        PrepFileAtom* atom = (*it);
        atom_names_of_residue.push_back(atom->GetName());
    }
    return atom_names_of_residue;
}
vector< string > PrepFile::GetAllResidueNames ()
Definition at line 52 of file prepfile.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::GetAllAtomNamesOfResidueFromMultiplePrepFiles(), PdbPreprocessorSpace::PdbPreprocessor::GetAllResidueNamesFromMultiplePrepFiles(), and PdbPreprocessorSpace::PdbPreprocessor::GetAllResidueNamesFromMultiplePrepFilesMap().
{
    vector<string> residue_names;
    for(PrepFile::ResidueMap::iterator it = residues_.begin(); it != residues_.end(); it++){
        string residue_name = (*it).first;
        residue_names.push_back(residue_name);
    }
    return residue_names;
}
ResidueNameMap PrepFile::GetAllResidueNamesMap ()
Definition at line 62 of file prepfile.cc.
{
    ResidueNameMap residue_names = ResidueNameMap();
    for(PrepFile::ResidueMap::iterator it = residues_.begin(); it != residues_.end(); it++){
        string residue_name = (*it).first;
        residue_names[residue_name] = residue_name;
    }
    return residue_names;
}
PrepFile::ResidueMap & PrepFile::GetResidues ()
Definition at line 47 of file prepfile.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), MolecularModeling::Assembly::BuildStructureByPrepFileInformation(), PdbPreprocessorSpace::PdbPreprocessor::GetAllAtomNamesOfResidueNamesFromMultiplePrepFiles(), and PdbPreprocessorSpace::PdbPreprocessor::GetAllResiduesFromMultiplePrepFilesMap().
{
    return residues_;
}
void PrepFile::Print (std::ostream & out = std::cout)
Definition at line 215 of file prepfile.cc.
{
    for(ResidueMap::iterator it = residues_.begin(); it != residues_.end(); it++)
    {
        out << "**********************************************************************************" << endl;
        it->second->Print(out);
    }
}
PrepFileResidue * PrepFile::ProcessResidueSection (std::ifstream & in_file)
Definition at line 122 of file prepfile.cc.
References PrepFileSpace::PrepFileResidue::LoadFromStream().
{
    PrepFileResidue* residue = new PrepFileResidue();
    residue = residue->LoadFromStream(in_file);
    return residue;
}
void PrepFile::Read (std::ifstream & in_file)
Definition at line 108 of file prepfile.cc.
References PrepFileSpace::PrepFileResidue::name_.
{
    string header1, header2;
    getline(in_file, header1);
    getline(in_file, header2);
    PrepFileResidue *residue = ProcessResidueSection(in_file);
    while (residue != NULL)
    {
        residues_[residue->name_] = residue;
        residue = ProcessResidueSection(in_file);
    }
}
void PrepFile::SetPath (std::string path)
Definition at line 89 of file prepfile.cc.
{
    path_ = path;
}
void PrepFile::SetResidues (ResidueMap residues)
Definition at line 94 of file prepfile.cc.
Referenced by MolecularModeling::Assembly::BuildPrepFileStructureFromAssembly().
{
    residues_.clear();
    for(ResidueMap::iterator it = residues.begin(); it != residues.end(); it++)
    {
        PrepFileResidue* residue = (*it).second;
        string residue_name = (*it).first;
        residues_[residue_name] = residue;
    }
}
void PrepFile::Write (const std::string & prep_file)
Definition at line 128 of file prepfile.cc.
{
    std::ofstream out_file;
    try
    {
        out_file.open(prep_file.c_str());
    }
    catch(...)
    {
        throw PrepFileProcessingException(__LINE__,"File could not be created");
    }
    try
    {
        this->BuildPrepFile(out_file);
    }
    catch(...)
    {
        out_file.close();
    }
}
The documentation for this class was generated from the following files:
includes/ParameterSet/PrepFileSpace/prepfile.hpp
src/ParameterSet/PrepFileSpace/prepfile.cc