gmmlNew: PdbFileSpace::PdbScaleN Class Reference
PdbFileSpace::PdbScaleN Class Reference
#include <pdbscalen.hpp>
Public Member Functions
PdbScaleN ()
PdbScaleN (std::stringstream &stream_block)
std::string GetRecordName ()
int GetN ()
Geometry::Coordinate GetScaleVector ()
double GetU ()
void SetRecordName (const std::string record_name)
void SetN (int n)
void SetScaleVector (Geometry::Coordinate scale_vector)
void SetU (double u)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 15 of file pdbscalen.hpp.
Constructor & Destructor Documentation
PdbScaleN::PdbScaleN ()
Definition at line 13 of file pdbscalen.cc.
:scale_vector_() {}
PdbFileSpace::PdbScaleN::PdbScaleN (std::stringstream & stream_block)
Member Function Documentation
int PdbScaleN::GetN ()
Definition at line 58 of file pdbscalen.cc.
Referenced by PdbFileSpace::PdbFile::ResolveScaleCard().
                   {
    return n_;
}
string PdbScaleN::GetRecordName ()
Definition at line 54 of file pdbscalen.cc.
Referenced by PdbFileSpace::PdbFile::ResolveScaleCard().
{
    return record_name_;
}
Geometry::Coordinate PdbScaleN::GetScaleVector ()
Definition at line 62 of file pdbscalen.cc.
Referenced by PdbFileSpace::PdbFile::ResolveScaleCard().
{
    return scale_vector_;
}
double PdbScaleN::GetU ()
Definition at line 66 of file pdbscalen.cc.
Referenced by PdbFileSpace::PdbFile::ResolveScaleCard().
                      {
    return u_;
}
void PdbScaleN::Print (std::ostream & out = std::cout)
Definition at line 93 of file pdbscalen.cc.
References gmml::dNotSet, gmml::iNotSet, and Geometry::Coordinate::Print().
{
    out << "Record Name: " << record_name_;
    if(n_ != iNotSet)
        out << n_;
    else
        out << " ";
    out << ", Origin: ";
    scale_vector_.Print(out);
    out << ", U: ";
    if(u_ != dNotSet)
        out << u_;
    else
        out << " ";
    out << endl;
}
void PdbScaleN::SetN (int n)
Definition at line 78 of file pdbscalen.cc.
{
    n_ = n;
}
void PdbScaleN::SetRecordName (const std::string record_name)
Definition at line 74 of file pdbscalen.cc.
{
    record_name_ = record_name;
}
void PdbScaleN::SetScaleVector (Geometry::Coordinate scale_vector)
Definition at line 82 of file pdbscalen.cc.
{
    scale_vector_ = scale_vector;
}
void PdbScaleN::SetU (double u)
Definition at line 86 of file pdbscalen.cc.
{
    u_ = u;
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbscalen.hpp
src/FileSet/PdbFileSpace/pdbscalen.cc