gmmlNew: MolecularModeling::Atom Class Reference
MolecularModeling::Atom Class Reference
#include <atom.hpp>
Public Types
typedef std::vector
< Geometry::Coordinate * > CoordinateVector
Public Member Functions
Atom ()
Residue * GetResidue ()
std::string GetName ()
CoordinateVector GetCoordinates ()
std::string GetChemicalType ()
std::string GetDescription ()
std::string GetElementSymbol ()
AtomNode * GetNode ()
std::string GetId ()
void SetResidue (Residue *residue)
void SetName (std::string name)
void SetCoordinates (CoordinateVector coordinates)
void AddCoordinate (Geometry::Coordinate *coordinate)
void SetChemicalType (std::string chemical_type)
void SetDescription (std::string description)
void SetElementSymbol (std::string element_symbol)
void SetNode (AtomNode *node)
void SetId (std::string id)
void Print (std::ostream &out=std::cout)
std::string GetAtomType ()
double GetCharge ()
double GetMass ()
double GetRadius ()
void SetAtomType (std::string atom_type)
void SetCharge (double charge)
void SetMass (double mass)
void SetRadius (double radius)
Detailed Description
Definition at line 17 of file atom.hpp.
Member Typedef Documentation
typedef std::vector<Geometry::Coordinate*> MolecularModeling::Atom::CoordinateVector
Definition at line 26 of file atom.hpp.
Constructor & Destructor Documentation
Atom::Atom ()
Definition at line 14 of file atom.cc.
{
    node_ = NULL;
}
Member Function Documentation
void Atom::AddCoordinate (Geometry::Coordinate * coordinate)
Definition at line 74 of file atom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), and MolecularModeling::Assembly::BuildAssemblyFromTopologyCoordinateFile().
{
    coordinates_.push_back(coordinate);
}
string MolecularDynamicAtom::GetAtomType () [inherited]
Definition at line 14 of file moleculardynamicatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly(), MolecularModeling::Assembly::BuildPrepFileStructureFromAssembly(), MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly(), MolecularModeling::Assembly::CountNumberOfAngleTypes(), MolecularModeling::Assembly::CountNumberOfAtomTypes(), MolecularModeling::Assembly::CountNumberOfBondTypes(), MolecularModeling::Assembly::CountNumberOfDihedrals(), MolecularModeling::Assembly::CountNumberOfDihedralsExcludingHydrogen(), MolecularModeling::Assembly::CountNumberOfDihedralsIncludingHydrogen(), MolecularModeling::Assembly::CountNumberOfDihedralTypes(), MolecularModeling::Assembly::ExtractTopologyAnglesFromAssembly(), MolecularModeling::Assembly::ExtractTopologyAngleTypesFromAssembly(), MolecularModeling::Assembly::ExtractTopologyBondsFromAssembly(), MolecularModeling::Assembly::ExtractTopologyBondTypesFromAssembly(), MolecularModeling::Assembly::ExtractTopologyDihedralsFromAssembly(), and MolecularModeling::Assembly::ExtractTopologyDihedralTypesFromAssembly().
{
    return atom_type_;
}
double MolecularDynamicAtom::GetCharge () [inherited]
Definition at line 18 of file moleculardynamicatom.cc.
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly(), MolecularModeling::Assembly::BuildPrepFileStructureFromAssembly(), MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly(), and MolecularModeling::Assembly::ExtractPdbModelCardFromAssembly().
{
    return charge_;
}
string Atom::GetChemicalType ()
Definition at line 34 of file atom.cc.
{
    return chemical_type_;
}
Atom::CoordinateVector Atom::GetCoordinates ()
Definition at line 30 of file atom.cc.
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly(), MolecularModeling::Assembly::BuildStructureByDistance(), MolecularModeling::Assembly::CalculateCenterOfGeometry(), MolecularModeling::Assembly::ExtractPdbModelCardFromAssembly(), and MolecularModeling::Assembly::GetAllCoordinates().
{
    return coordinates_;
}
string Atom::GetDescription ()
Definition at line 38 of file atom.cc.
Referenced by MolecularModeling::Assembly::ExtractPdbModelCardFromAssembly().
{
    return description_;
}
string Atom::GetElementSymbol ()
Definition at line 42 of file atom.cc.
Referenced by MolecularModeling::Assembly::ExtractPdbModelCardFromAssembly().
{
    return element_symbol_;
}
string Atom::GetId ()
Definition at line 50 of file atom.cc.
Referenced by MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), MolecularModeling::Assembly::BuildStructureByLIBFileInformation(), MolecularModeling::Assembly::BuildStructureByPDBFileInformation(), MolecularModeling::Assembly::BuildStructureByPrepFileInformation(), MolecularModeling::Assembly::BuildStructureByTOPFileInformation(), MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly(), MolecularModeling::Assembly::CountNumberOfAngles(), MolecularModeling::Assembly::CountNumberOfAnglesExcludingHydrogen(), MolecularModeling::Assembly::CountNumberOfAnglesIncludingHydrogen(), MolecularModeling::Assembly::CountNumberOfAngleTypes(), MolecularModeling::Assembly::CountNumberOfDihedrals(), MolecularModeling::Assembly::CountNumberOfDihedralsExcludingHydrogen(), MolecularModeling::Assembly::CountNumberOfDihedralsIncludingHydrogen(), MolecularModeling::Assembly::CountNumberOfDihedralTypes(), MolecularModeling::Assembly::CountNumberOfExcludedAtoms(), MolecularModeling::Assembly::ExtractTopologyBondsFromAssembly(), and MolecularModeling::Assembly::ExtractTopologyBondTypesFromAssembly().
{
    return id_;
}
double MolecularDynamicAtom::GetMass () [inherited]
Definition at line 22 of file moleculardynamicatom.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    return mass_;
}
string Atom::GetName ()
Definition at line 26 of file atom.cc.
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly(), MolecularModeling::Assembly::BuildPrepFileStructureFromAssembly(), MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), MolecularModeling::Assembly::BuildStructureByLIBFileInformation(), MolecularModeling::Assembly::BuildStructureByPrepFileInformation(), MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly(), MolecularModeling::Assembly::CountNumberOfAnglesExcludingHydrogen(), MolecularModeling::Assembly::CountNumberOfAnglesIncludingHydrogen(), MolecularModeling::Assembly::CountNumberOfBondsExcludingHydrogen(), MolecularModeling::Assembly::CountNumberOfBondsIncludingHydrogen(), MolecularModeling::Assembly::CountNumberOfDihedralsExcludingHydrogen(), MolecularModeling::Assembly::CountNumberOfDihedralsIncludingHydrogen(), MolecularModeling::Assembly::ExtractPdbModelCardFromAssembly(), MolecularModeling::Assembly::ExtractTopologyAnglesFromAssembly(), MolecularModeling::Assembly::ExtractTopologyBondsFromAssembly(), MolecularModeling::Assembly::ExtractTopologyDihedralsFromAssembly(), and MolecularModeling::Residue::Print().
{
    return name_;
}
AtomNode * Atom::GetNode ()
Definition at line 46 of file atom.cc.
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly(), MolecularModeling::Assembly::BuildPrepFileStructureFromAssembly(), MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly(), MolecularModeling::Assembly::CountNumberOfAngles(), MolecularModeling::Assembly::CountNumberOfAnglesExcludingHydrogen(), MolecularModeling::Assembly::CountNumberOfAnglesIncludingHydrogen(), MolecularModeling::Assembly::CountNumberOfAngleTypes(), MolecularModeling::Assembly::CountNumberOfBonds(), MolecularModeling::Assembly::CountNumberOfBondsExcludingHydrogen(), MolecularModeling::Assembly::CountNumberOfBondsIncludingHydrogen(), MolecularModeling::Assembly::CountNumberOfBondTypes(), MolecularModeling::Assembly::CountNumberOfDihedrals(), MolecularModeling::Assembly::CountNumberOfDihedralsExcludingHydrogen(), MolecularModeling::Assembly::CountNumberOfDihedralsIncludingHydrogen(), MolecularModeling::Assembly::CountNumberOfDihedralTypes(), MolecularModeling::Assembly::CountNumberOfExcludedAtoms(), MolecularModeling::Assembly::ExtractTopologyDihedralsFromAssembly(), MolecularModeling::Assembly::ExtractTopologyDihedralTypesFromAssembly(), and MolecularModeling::Assembly::GetAllAtomsOfAssemblyWithAtLeastThreeNeighbors().
{
    return node_;
}
double MolecularDynamicAtom::GetRadius () [inherited]
Definition at line 26 of file moleculardynamicatom.cc.
{
    return radius_;
}
Residue * Atom::GetResidue ()
Definition at line 22 of file atom.cc.
Referenced by MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), MolecularModeling::Assembly::BuildStructureByLIBFileInformation(), MolecularModeling::Assembly::BuildStructureByPrepFileInformation(), MolecularModeling::Assembly::ExtractPdbModelCardFromAssembly(), MolecularModeling::Assembly::ExtractTopologyAnglesFromAssembly(), MolecularModeling::Assembly::ExtractTopologyBondsFromAssembly(), MolecularModeling::Assembly::ExtractTopologyDihedralsFromAssembly(), MolecularModeling::AtomNode::Print(), and MolecularModeling::Residue::Print().
{
    return residue_;
}
void Atom::Print (std::ostream & out = std::cout)
Reimplemented from MolecularModeling::MolecularDynamicAtom.
Definition at line 102 of file atom.cc.
References Geometry::Coordinate::Print().
Referenced by MolecularModeling::Residue::Print().
{
    out << "Atom name: " << name_ << endl;
    out << "Coordinates: " << endl;
    if(coordinates_.size() != 0)
    {
        for(CoordinateVector::iterator it = coordinates_.begin(); it != coordinates_.end(); it++)
        {
            Geometry::Coordinate* coordinate = *it;
            out << "\t";
            coordinate->Print(out);
            out << endl;
        }
    }
    out << "**************** Structure *****************" << endl;
    if(node_ != NULL)
        node_->Print(out);
    out << endl;
}
void MolecularDynamicAtom::SetAtomType (std::string atom_type) [inherited]
Definition at line 34 of file moleculardynamicatom.cc.
{
    atom_type_ = atom_type;
}
void MolecularDynamicAtom::SetCharge (double charge) [inherited]
Definition at line 38 of file moleculardynamicatom.cc.
{
    charge_ = charge;
}
void Atom::SetChemicalType (std::string chemical_type)
Definition at line 78 of file atom.cc.
{
    chemical_type_ = chemical_type;
}
void Atom::SetCoordinates (CoordinateVector coordinates)
Definition at line 66 of file atom.cc.
{
    coordinates_.clear();
    for(CoordinateVector::iterator it = coordinates.begin(); it != coordinates.end(); it++)
    {
        coordinates_.push_back(*it);
    }
}
void Atom::SetDescription (std::string description)
Definition at line 82 of file atom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile().
{
    description_ = description;
}
void Atom::SetElementSymbol (std::string element_symbol)
Definition at line 86 of file atom.cc.
{
    element_symbol_ = element_symbol;
}
void Atom::SetId (std::string id)
Definition at line 94 of file atom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), MolecularModeling::Assembly::BuildAssemblyFromTopologyCoordinateFile(), and MolecularModeling::Assembly::BuildAssemblyFromTopologyFile().
{
    id_ = id;
}
void MolecularDynamicAtom::SetMass (double mass) [inherited]
Definition at line 42 of file moleculardynamicatom.cc.
{
    mass_ = mass;
}
void Atom::SetName (std::string name)
Definition at line 62 of file atom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), MolecularModeling::Assembly::BuildAssemblyFromTopologyCoordinateFile(), and MolecularModeling::Assembly::BuildAssemblyFromTopologyFile().
{
    name_ = name;
}
void Atom::SetNode (AtomNode * node)
Definition at line 90 of file atom.cc.
Referenced by MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), MolecularModeling::Assembly::BuildStructureByDistance(), MolecularModeling::Assembly::BuildStructureByLIBFileInformation(), MolecularModeling::Assembly::BuildStructureByPDBFileInformation(), MolecularModeling::Assembly::BuildStructureByPrepFileInformation(), and MolecularModeling::Assembly::BuildStructureByTOPFileInformation().
{
    node_ = node;
}
void MolecularDynamicAtom::SetRadius (double radius) [inherited]
Definition at line 46 of file moleculardynamicatom.cc.
{
    radius_ = radius;
}
void Atom::SetResidue (Residue * residue)
Definition at line 58 of file atom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), MolecularModeling::Assembly::BuildAssemblyFromTopologyCoordinateFile(), and MolecularModeling::Assembly::BuildAssemblyFromTopologyFile().
{
    residue_ = residue;
}
The documentation for this class was generated from the following files:
includes/MolecularModeling/atom.hpp
src/MolecularModeling/atom.cc