gmmlNew: PdbPreprocessorSpace::PdbPreprocessorChainTermination Class Reference
PdbPreprocessorSpace::PdbPreprocessorChainTermination Class Reference
#include <pdbpreprocessorchaintermination.hpp>
Public Member Functions
PdbPreprocessorChainTermination ()
PdbPreprocessorChainTermination (char chain_id, int starting_sequence_number, int ending_sequence_number, char starting_residue_insertion_code, char ending_residue_insertion_code)
char GetResidueChainId ()
int GetStartingResidueSequenceNumber ()
int GetEndingResidueSequenceNumber ()
gmml::PossibleNChainTermination GetSelectedNTermination ()
gmml::PossibleCChainTermination GetSelectedCTermination ()
char GetStartingResidueInsertionCode ()
char GetEndingResidueInsertionCode ()
std::string GetStringFormatOfSelectedNTermination ()
std::string GetStringFormatOfSelectedCTermination ()
std::string GetStringFormatOfNTermination (gmml::PossibleNChainTermination n_termination)
std::string GetStringFormatOfCTermination (gmml::PossibleCChainTermination c_termination)
std::vector< std::string > GetAllPossibleNChainTerminationAsString ()
std::vector< std::string > GetAllPossibleCChainTerminationAsString ()
void SetResidueChainId (char residue_chain_id)
void SetStartingResidueSequenceNumber (int starting_residue_sequence_number)
void SetEndingResidueSequenceNumber (int ending_residue_sequence_number)
void SetSelectedNTermination (gmml::PossibleNChainTermination selected_n_termination)
void SetSelectedCTermination (gmml::PossibleCChainTermination selected_c_termination)
void SetStartingResidueInsertionCode (char starting_residue_insertion_code)
void SetEndingResidueInsertionCode (char ending_residue_insertion_code)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 14 of file pdbpreprocessorchaintermination.hpp.
Constructor & Destructor Documentation
PdbPreprocessorChainTermination::PdbPreprocessorChainTermination ()
Definition at line 11 of file pdbpreprocessorchaintermination.cc.
{}
PdbPreprocessorChainTermination::PdbPreprocessorChainTermination (char chain_id, int starting_sequence_number, int ending_sequence_number, char starting_residue_insertion_code, char ending_residue_insertion_code)
Definition at line 13 of file pdbpreprocessorchaintermination.cc.
                                                                                                                                                                                                                  :
    residue_chain_id_(chain_id), starting_residue_sequence_number_(starting_sequence_number), ending_residue_sequence_number_(ending_sequence_number),
    starting_residue_insertion_code_(starting_residue_insertion_code), ending_residue_insertion_code_(ending_residue_insertion_code)
{
    selected_n_termination_ = (PossibleNChainTermination)2;
    selected_c_termination_ = (PossibleCChainTermination)3;
}
Member Function Documentation
vector< string > PdbPreprocessorChainTermination::GetAllPossibleCChainTerminationAsString ()
Definition at line 117 of file pdbpreprocessorchaintermination.cc.
References gmml::CO2, GetStringFormatOfCTermination(), and gmml::NH2.
{
    vector<string> all_possible_c_chian_termination_as_string;
    for(int possible_c_chian_termination = NH2; possible_c_chian_termination != CO2; possible_c_chian_termination++)
        all_possible_c_chian_termination_as_string.push_back(GetStringFormatOfCTermination((PossibleCChainTermination)possible_c_chian_termination));
    return all_possible_c_chian_termination_as_string;
}
vector< string > PdbPreprocessorChainTermination::GetAllPossibleNChainTerminationAsString ()
Definition at line 109 of file pdbpreprocessorchaintermination.cc.
References gmml::COCH3, GetStringFormatOfNTermination(), and gmml::NH3.
{
    vector<string> all_possible_n_chian_termination_as_string;
    for(int possible_n_chian_termination = COCH3; possible_n_chian_termination != NH3; possible_n_chian_termination++)
        all_possible_n_chian_termination_as_string.push_back(GetStringFormatOfNTermination((PossibleNChainTermination)possible_n_chian_termination));
    return all_possible_n_chian_termination_as_string;
}
char PdbPreprocessorChainTermination::GetEndingResidueInsertionCode ()
Definition at line 48 of file pdbpreprocessorchaintermination.cc.
{
    return ending_residue_insertion_code_;
}
int PdbPreprocessorChainTermination::GetEndingResidueSequenceNumber ()
Definition at line 32 of file pdbpreprocessorchaintermination.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains().
{
    return ending_residue_sequence_number_;
}
char PdbPreprocessorChainTermination::GetResidueChainId ()
Definition at line 24 of file pdbpreprocessorchaintermination.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains().
{
    return residue_chain_id_;
}
PossibleCChainTermination PdbPreprocessorChainTermination::GetSelectedCTermination ()
Definition at line 40 of file pdbpreprocessorchaintermination.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains().
{
    return selected_c_termination_;
}
PossibleNChainTermination PdbPreprocessorChainTermination::GetSelectedNTermination ()
Definition at line 36 of file pdbpreprocessorchaintermination.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains().
{
    return selected_n_termination_;
}
char PdbPreprocessorChainTermination::GetStartingResidueInsertionCode ()
Definition at line 44 of file pdbpreprocessorchaintermination.cc.
{
    return starting_residue_insertion_code_;
}
int PdbPreprocessorChainTermination::GetStartingResidueSequenceNumber ()
Definition at line 28 of file pdbpreprocessorchaintermination.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains().
{
    return starting_residue_sequence_number_;
}
string PdbPreprocessorChainTermination::GetStringFormatOfCTermination (gmml::PossibleCChainTermination c_termination)
Definition at line 94 of file pdbpreprocessorchaintermination.cc.
Referenced by GetAllPossibleCChainTerminationAsString(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains().
{
    switch(c_termination)
    {
        case 1:
            return "NHE";
        case 2:
            return "NME";
        case 3:
            return "CO2-";
        default:
            return "";
    }
}
string PdbPreprocessorChainTermination::GetStringFormatOfNTermination (gmml::PossibleNChainTermination n_termination)
Definition at line 81 of file pdbpreprocessorchaintermination.cc.
Referenced by GetAllPossibleNChainTerminationAsString(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains().
{
    switch (n_termination)
    {
        case 1:
            return "ACE";
        case 2:
            return "NH3+";
        default:
            return "";
    }
}
string PdbPreprocessorChainTermination::GetStringFormatOfSelectedCTermination ()
Definition at line 66 of file pdbpreprocessorchaintermination.cc.
Referenced by Print(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains().
{
    switch(selected_c_termination_)
    {
        case 1:
            return "NHE";
        case 2:
            return "NME";
        case 3:
            return "CO2-";
        default:
            return "";
    }
}
string PdbPreprocessorChainTermination::GetStringFormatOfSelectedNTermination ()
Definition at line 53 of file pdbpreprocessorchaintermination.cc.
Referenced by Print(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains().
{
    switch (selected_n_termination_)
    {
        case 1:
            return "ACE";
        case 2:
            return "NH3+";
        default:
            return "";
    }
}
void PdbPreprocessorChainTermination::Print (std::ostream & out = std::cout)
Definition at line 160 of file pdbpreprocessorchaintermination.cc.
References GetStringFormatOfSelectedCTermination(), and GetStringFormatOfSelectedNTermination().
{
    out << "Chain id " << residue_chain_id_
         << ", Start sequence number: " << starting_residue_sequence_number_
         << ", End sequence number: " << ending_residue_sequence_number_
         << ", Start insertion code: " << starting_residue_insertion_code_
         << ", End insertion code: " << ending_residue_insertion_code_
         << ", Selected n termination: " << GetStringFormatOfSelectedNTermination()
         << ", Selected c termination: " << GetStringFormatOfSelectedCTermination()
         << endl;
}
void PdbPreprocessorChainTermination::SetEndingResidueInsertionCode (char ending_residue_insertion_code)
Definition at line 152 of file pdbpreprocessorchaintermination.cc.
{
    ending_residue_insertion_code_ = ending_residue_insertion_code;
}
void PdbPreprocessorChainTermination::SetEndingResidueSequenceNumber (int ending_residue_sequence_number)
Definition at line 136 of file pdbpreprocessorchaintermination.cc.
{
    ending_residue_sequence_number_ = ending_residue_sequence_number;
}
void PdbPreprocessorChainTermination::SetResidueChainId (char residue_chain_id)
Definition at line 128 of file pdbpreprocessorchaintermination.cc.
{
    residue_chain_id_ = residue_chain_id;
}
void PdbPreprocessorChainTermination::SetSelectedCTermination (gmml::PossibleCChainTermination selected_c_termination)
Definition at line 144 of file pdbpreprocessorchaintermination.cc.
{
    selected_c_termination_ = selected_c_termination;
}
void PdbPreprocessorChainTermination::SetSelectedNTermination (gmml::PossibleNChainTermination selected_n_termination)
Definition at line 140 of file pdbpreprocessorchaintermination.cc.
{
    selected_n_termination_ = selected_n_termination;
}
void PdbPreprocessorChainTermination::SetStartingResidueInsertionCode (char starting_residue_insertion_code)
Definition at line 148 of file pdbpreprocessorchaintermination.cc.
{
    starting_residue_insertion_code_ = starting_residue_insertion_code;
}
void PdbPreprocessorChainTermination::SetStartingResidueSequenceNumber (int starting_residue_sequence_number)
Definition at line 132 of file pdbpreprocessorchaintermination.cc.
{
    starting_residue_sequence_number_ = starting_residue_sequence_number;
}
The documentation for this class was generated from the following files:
includes/Resolver/PdbPreprocessor/pdbpreprocessorchaintermination.hpp
src/Resolver/PdbPreprocessor/pdbpreprocessorchaintermination.cc