gmmlNew: TopologyFileSpace::TopologyBondType Class Reference
TopologyFileSpace::TopologyBondType Class Reference
#include <topologybondtype.hpp>
Public Member Functions
TopologyBondType ()
TopologyBondType (int index, double force_constant, double equilibrium_value)
int GetIndex ()
double GetForceConstant ()
double GetEquilibriumValue ()
void SetIndex (int index)
void SetForceConstant (double force_constant)
void SetEquilibriumValue (double equilibrium_value)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 10 of file topologybondtype.hpp.
Constructor & Destructor Documentation
TopologyBondType::TopologyBondType ()
Definition at line 10 of file topologybondtype.cc.
{}
TopologyBondType::TopologyBondType (int index, double force_constant, double equilibrium_value)
Definition at line 12 of file topologybondtype.cc.
                                                                                             :
    index_(index), force_constant_(force_constant), equilibrium_value_(equilibrium_value) {}
Member Function Documentation
double TopologyBondType::GetEquilibriumValue ()
Definition at line 26 of file topologybondtype.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveBondEquilValueSection().
{
    return equilibrium_value_;
}
double TopologyBondType::GetForceConstant ()
Definition at line 22 of file topologybondtype.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveBondForceConstantSection().
{
    return force_constant_;
}
int TopologyBondType::GetIndex ()
Definition at line 18 of file topologybondtype.cc.
Referenced by TopologyFileSpace::TopologyFile::AddBondType(), TopologyFileSpace::TopologyFile::GetBondTypeByIndex(), TopologyFileSpace::TopologyFile::ResolveBondsIncHydrogenSection(), and TopologyFileSpace::TopologyFile::ResolveBondsWithoutHydrogenSection().
{
    return index_;
}
void TopologyBondType::Print (std::ostream & out = std::cout)
Definition at line 54 of file topologybondtype.cc.
Referenced by TopologyFileSpace::TopologyBond::Print(), and TopologyFileSpace::TopologyFile::Print().
{
    out << "Bond index: " << index_
         << ", Force constant: " << force_constant_
         << ", Equilibrium value: " << equilibrium_value_;
}
void TopologyBondType::SetEquilibriumValue (double equilibrium_value)
Definition at line 43 of file topologybondtype.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyBondTypesFromAssembly().
{
    equilibrium_value_ = equilibrium_value;
}
void TopologyBondType::SetForceConstant (double force_constant)
Definition at line 39 of file topologybondtype.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyBondTypesFromAssembly().
{
    force_constant_ = force_constant;
}
void TopologyBondType::SetIndex (int index)
Definition at line 35 of file topologybondtype.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyBondTypesFromAssembly().
{
    index_ = index;
}
The documentation for this class was generated from the following files:
includes/FileSet/TopologyFileSpace/topologybondtype.hpp
src/FileSet/TopologyFileSpace/topologybondtype.cc