gmmlNew: TopologyFileSpace::TopologyDihedral Class Reference
TopologyFileSpace::TopologyDihedral Class Reference
#include <topologydihedral.hpp>
Public Member Functions
TopologyDihedral ()
TopologyDihedral (std::vector< std::string > dihedral_atoms, std::vector< std::string > residue_names)
std::vector< std::string > GetDihedrals ()
TopologyDihedralType * GetDihedralType ()
bool GetIsImproper ()
bool GetIgnoredGroupInteraction ()
bool GetIncludingHydrogen ()
std::vector< std::string > GetResidueNames ()
void SetDihedrals (std::vector< std::string > dihedrals)
void SetDihedralType (TopologyDihedralType *dihedral_type)
void SetIsImproper (bool is_improper)
void SetIgnoredGroupInteraction (bool ignored_group_interaction)
void SetIncludingHydrogen (bool including_hydrogen)
void SetResidueNames (std::vector< std::string > residue_names)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 11 of file topologydihedral.hpp.
Constructor & Destructor Documentation
TopologyDihedral::TopologyDihedral ()
Definition at line 11 of file topologydihedral.cc.
{}
TopologyFileSpace::TopologyDihedral::TopologyDihedral (std::vector< std::string > dihedral_atoms, std::vector< std::string > residue_names)
Member Function Documentation
vector< string > TopologyDihedral::GetDihedrals ()
Definition at line 30 of file topologydihedral.cc.
Referenced by TopologyFileSpace::TopologyFile::AddDihedral(), TopologyFileSpace::TopologyFile::ResolveDihedralsIncHydrogenSection(), and TopologyFileSpace::TopologyFile::ResolveDihedralsWithoutHydrogenSection().
{
    return dihedrals_;
}
TopologyDihedralType * TopologyDihedral::GetDihedralType ()
Definition at line 34 of file topologydihedral.cc.
Referenced by TopologyFileSpace::TopologyFile::AddDihedral(), TopologyFileSpace::TopologyFile::ParseSections(), TopologyFileSpace::TopologyFile::ResolveDihedralsIncHydrogenSection(), and TopologyFileSpace::TopologyFile::ResolveDihedralsWithoutHydrogenSection().
{
    return dihedral_type_;
}
bool TopologyDihedral::GetIgnoredGroupInteraction ()
Definition at line 42 of file topologydihedral.cc.
Referenced by TopologyFileSpace::TopologyFile::ParseSections(), TopologyFileSpace::TopologyFile::ResolveDihedralsIncHydrogenSection(), and TopologyFileSpace::TopologyFile::ResolveDihedralsWithoutHydrogenSection().
{
    return ignored_group_interaction_;
}
bool TopologyDihedral::GetIncludingHydrogen ()
Definition at line 46 of file topologydihedral.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveDihedralsIncHydrogenSection(), and TopologyFileSpace::TopologyFile::ResolveDihedralsWithoutHydrogenSection().
{
    return including_hydrogen_;
}
bool TopologyDihedral::GetIsImproper ()
Definition at line 38 of file topologydihedral.cc.
Referenced by TopologyFileSpace::TopologyFile::ParseSections(), TopologyFileSpace::TopologyFile::ResolveDihedralsIncHydrogenSection(), and TopologyFileSpace::TopologyFile::ResolveDihedralsWithoutHydrogenSection().
{
    return is_improper_;
}
vector< string > TopologyDihedral::GetResidueNames ()
Definition at line 50 of file topologydihedral.cc.
Referenced by TopologyFileSpace::TopologyFile::AddDihedral().
{
    return residue_names_;
}
void TopologyDihedral::Print (std::ostream & out = std::cout)
Definition at line 98 of file topologydihedral.cc.
References TopologyFileSpace::TopologyDihedralType::Print().
Referenced by TopologyFileSpace::TopologyFile::Print().
{
    out << "Dihedral: " << residue_names_.at(0) << ":" << dihedrals_.at(0) << "-" << residue_names_.at(1) << ":" << dihedrals_.at(1) << "-" <<  residue_names_.at(3) << ":"  <<
           dihedrals_.at(2) << "-" << residue_names_.at(3) << ":" << dihedrals_.at(3) << endl;
    out << "\t ";
    dihedral_type_->Print(out);
    out << ", Including Hydrogen: ";
    if(including_hydrogen_)
        out << "YES";
    else
        out << "NO";
    out << ", Improper: ";
    if(is_improper_)
        out << "YES";
    else
        out << "NO";
    out << ", Ignored Group Interaction: ";
    if(ignored_group_interaction_)
        out << "YES";
    else
        out << "NO";
    out << endl;
}
void TopologyDihedral::SetDihedrals (std::vector< std::string > dihedrals)
Definition at line 58 of file topologydihedral.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralsFromAssembly().
{
    dihedrals_.clear();
    for(vector<string>::iterator it = dihedrals.begin(); it != dihedrals.end(); it++)
    {
        dihedrals_.push_back(*it);
    }
}
void TopologyDihedral::SetDihedralType (TopologyDihedralType * dihedral_type)
Definition at line 66 of file topologydihedral.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralsFromAssembly(), and TopologyFileSpace::TopologyFile::ParseSections().
{
    dihedral_type_ = dihedral_type;
}
void TopologyDihedral::SetIgnoredGroupInteraction (bool ignored_group_interaction)
Definition at line 74 of file topologydihedral.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralsFromAssembly(), and TopologyFileSpace::TopologyFile::ParseSections().
{
    ignored_group_interaction_ = ignored_group_interaction;
}
void TopologyDihedral::SetIncludingHydrogen (bool including_hydrogen)
Definition at line 78 of file topologydihedral.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralsFromAssembly(), and TopologyFileSpace::TopologyFile::ParseSections().
{
    including_hydrogen_ = including_hydrogen;
}
void TopologyDihedral::SetIsImproper (bool is_improper)
Definition at line 70 of file topologydihedral.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralsFromAssembly(), and TopologyFileSpace::TopologyFile::ParseSections().
{
    is_improper_ = is_improper;
}
void TopologyDihedral::SetResidueNames (std::vector< std::string > residue_names)
Definition at line 82 of file topologydihedral.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralsFromAssembly().
{
    residue_names_.clear();
    for(vector<string>::iterator it = residue_names.begin(); it != residue_names.end(); it++)
    {
        residue_names_.push_back(*it);
    }
}
The documentation for this class was generated from the following files:
includes/FileSet/TopologyFileSpace/topologydihedral.hpp
src/FileSet/TopologyFileSpace/topologydihedral.cc