gmmlNew: LibraryFileSpace::LibraryFileAtom Class Reference
LibraryFileSpace::LibraryFileAtom Class Reference
#include <libraryfileatom.hpp>
Public Member Functions
LibraryFileAtom ()
LibraryFileAtom (std::string type, std::string name, int residue_index, int atom_index, int atomic_number, double charge)
LibraryFileAtom (std::string type, std::string name, int residue_index, int atom_index, int atomic_number, double charge, Geometry::Coordinate coordinate, std::vector< int > bonded_atoms_indices, int atom_order)
std::string GetType ()
std::string GetName ()
Return atom name.
int GetResidueIndex ()
Return the residue index in the list of residues in the library file that the current atom belongs to it.
int GetAtomIndex ()
return atom index in the belonging residue
int GetAtomicNumber ()
Return atomic number of the atom.
double GetCharge ()
Return charge of the atom.
Geometry::Coordinate GetCoordinate ()
Return position of the atom.
std::vector< int > GetBondedAtomsIndices ()
Return all bonded atom indices of the atom.
int GetAtomOrder ()
Return inserting order of the atom in a residue.
void SetType (const std::string type)
void SetName (const std::string name)
Set atom name.
void SetResidueIndex (int residue_index)
Set the index of the residue in the list of residues in the library file that the current atom belongs to it.
void SetAtomIndex (int atom_index)
Set the atom index in its residue.
void SetAtomicNumber (int atomic_number)
Set the atomic number of the atom.
void SetCoordinate (Geometry::Coordinate &coordinate)
Set the postion of the atom.
void SetBondedAtomsIndices (const std::vector< int > bonded_atoms_indices)
Set all the bonded atom indices to the current atom.
void AddBondedAtomIndex (int index)
Add a new bonded atom index to the list of bonded atom indices.
void SetAtomOrder (int atom_order)
Set the order of insertion of the current atom into its residue.
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 11 of file libraryfileatom.hpp.
Constructor & Destructor Documentation
LibraryFileAtom::LibraryFileAtom ()
Definition at line 12 of file libraryfileatom.cc.
                                 : type_(""), name_(""), residue_index_(-1), atom_index_(-1), atomic_number_(0), charge_(0.0), coordinate_(),
    atom_order_(0) {}
LibraryFileSpace::LibraryFileAtom::LibraryFileAtom (std::string type, std::string name, int residue_index, int atom_index, int atomic_number, double charge)
LibraryFileSpace::LibraryFileAtom::LibraryFileAtom (std::string type, std::string name, int residue_index, int atom_index, int atomic_number, double charge, Geometry::Coordinate coordinate, std::vector< int > bonded_atoms_indices, int atom_order)
Member Function Documentation
void LibraryFileAtom::AddBondedAtomIndex (int index)
Add a new bonded atom index to the list of bonded atom indices.
Definition at line 140 of file libraryfileatom.cc.
{
    bonded_atoms_indices_.push_back(index);
}
int LibraryFileAtom::GetAtomicNumber ()
Return atomic number of the atom.
Definition at line 59 of file libraryfileatom.cc.
Referenced by LibraryFileSpace::LibraryFile::ResolveAtomSection().
{
    return atomic_number_;
}
int LibraryFileAtom::GetAtomIndex ()
return atom index in the belonging residue
Definition at line 53 of file libraryfileatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), LibraryFileSpace::LibraryFile::ResolveAtomSection(), and LibraryFileSpace::LibraryFile::ResolveConnectivitySection().
{
    return atom_index_;
}
int LibraryFileAtom::GetAtomOrder ()
Return inserting order of the atom in a residue.
Definition at line 83 of file libraryfileatom.cc.
Referenced by LibraryFileSpace::LibraryFileResidue::AddAtom().
{
    return atom_order_;
}
vector< int > LibraryFileAtom::GetBondedAtomsIndices ()
Return all bonded atom indices of the atom.
Definition at line 77 of file libraryfileatom.cc.
Referenced by MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), MolecularModeling::Assembly::BuildStructureByLIBFileInformation(), and LibraryFileSpace::LibraryFile::ResolveConnectivitySection().
{
    return bonded_atoms_indices_;
}
double LibraryFileAtom::GetCharge ()
Return charge of the atom.
Definition at line 65 of file libraryfileatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), and LibraryFileSpace::LibraryFile::ResolveAtomSection().
{
    return charge_;
}
Coordinate LibraryFileAtom::GetCoordinate ()
Return position of the atom.
Definition at line 71 of file libraryfileatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), LibraryFileSpace::LibraryFile::ResolvePositionSection(), PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains(), PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChainsWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    return coordinate_;
}
string LibraryFileAtom::GetName ()
Return atom name.
Definition at line 41 of file libraryfileatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), MolecularModeling::Assembly::BuildStructureByLIBFileInformation(), LibraryFileSpace::LibraryFile::GetAllAtomNamesOfResidue(), PdbPreprocessorSpace::PdbPreprocessor::GetAllAtomNamesOfResidueNamesFromMultipleLibFiles(), LibraryFileSpace::LibraryFileResidue::GetLibraryAtomByAtomName(), LibraryFileSpace::LibraryFile::ResolveAtomSection(), PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains(), PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChainsWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    return name_;
}
int LibraryFileAtom::GetResidueIndex ()
Return the residue index in the list of residues in the library file that the current atom belongs to it.
Definition at line 47 of file libraryfileatom.cc.
Referenced by LibraryFileSpace::LibraryFile::ResolveAtomSection().
{
    return residue_index_;
}
string LibraryFileAtom::GetType ()
Return atom type
Definition at line 35 of file libraryfileatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), and LibraryFileSpace::LibraryFile::ResolveAtomSection().
{
    return type_;
}
void LibraryFileAtom::Print (std::ostream & out = std::cout)
Definition at line 154 of file libraryfileatom.cc.
References Geometry::Coordinate::GetX(), Geometry::Coordinate::GetY(), and Geometry::Coordinate::GetZ().
{
    out << setw(2) << atom_order_
        << setw(6) << name_
        << setw(6) << type_
        << setw(6) << residue_index_
        << setw(6) << atom_index_
        << setw(10) << charge_
        << setw(15) << coordinate_.GetX() << ", " << setw(15) << coordinate_.GetY() << ", " << setw(15) << coordinate_.GetZ();
}
void LibraryFileAtom::SetAtomicNumber (int atomic_number)
Set the atomic number of the atom.
Definition at line 116 of file libraryfileatom.cc.
{
    atomic_number_ = atomic_number;
}
void LibraryFileAtom::SetAtomIndex (int atom_index)
Set the atom index in its residue.
Definition at line 110 of file libraryfileatom.cc.
{
    atom_index_ = atom_index;
}
void LibraryFileAtom::SetAtomOrder (int atom_order)
Set the order of insertion of the current atom into its residue.
Definition at line 146 of file libraryfileatom.cc.
Referenced by LibraryFileSpace::LibraryFile::Read().
{
    atom_order_ = atom_order;
}
void LibraryFileAtom::SetBondedAtomsIndices (const std::vector< int > bonded_atoms_indices)
Set all the bonded atom indices to the current atom.
Definition at line 130 of file libraryfileatom.cc.
{
    bonded_atoms_indices_.clear();
    for(vector<int>::const_iterator it = bonded_atoms_indices.begin(); it != bonded_atoms_indices.end(); it++)
    {
        bonded_atoms_indices_.push_back(*it);
    }
}
void LibraryFileAtom::SetCoordinate (Geometry::Coordinate & coordinate)
Set the postion of the atom.
Definition at line 122 of file libraryfileatom.cc.
References Geometry::Coordinate::GetX(), Geometry::Coordinate::GetY(), Geometry::Coordinate::GetZ(), Geometry::Coordinate::SetX(), Geometry::Coordinate::SetY(), and Geometry::Coordinate::SetZ().
{
    coordinate_.SetX(coordinate.GetX());
    coordinate_.SetY(coordinate.GetY());
    coordinate_.SetZ(coordinate.GetZ());
}
void LibraryFileAtom::SetName (const std::string name)
Set atom name.
Definition at line 98 of file libraryfileatom.cc.
{
    name_ = name;
}
void LibraryFileAtom::SetResidueIndex (int residue_index)
Set the index of the residue in the list of residues in the library file that the current atom belongs to it.
Definition at line 104 of file libraryfileatom.cc.
{
    residue_index_ = residue_index;
}
void LibraryFileAtom::SetType (const std::string type)
Set atom type
Definition at line 92 of file libraryfileatom.cc.
{
    type_ = type;
}
The documentation for this class was generated from the following files:
includes/ParameterSet/LibraryFileSpace/libraryfileatom.hpp
src/ParameterSet/LibraryFileSpace/libraryfileatom.cc