gmmlNew: ParameterFileSpace::ParameterFileDihedralTerm Class Reference
ParameterFileSpace::ParameterFileDihedralTerm Class Reference
#include <parameterfiledihedralterm.hpp>
Public Member Functions
ParameterFileDihedralTerm ()
ParameterFileDihedralTerm (int factor, double force_constant, double phase, double periodicity, const std::string &dscr="")
int GetFactor ()
double GetForceConstant ()
double GetPhase ()
double GetPeriodicity ()
std::string GetDscr ()
void SetFactor (int factor)
void SetForceConstant (double force_constant)
void SetPhase (double phase)
void SetPeriodicity (double periodicity)
void SetDscr (std::string dscr)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 9 of file parameterfiledihedralterm.hpp.
Constructor & Destructor Documentation
ParameterFileDihedralTerm::ParameterFileDihedralTerm ()
Definition at line 13 of file parameterfiledihedralterm.cc.
                                                     :
    factor_(dNotSet), force_constant_(dNotSet), phase_(dNotSet), periodicity_(dNotSet), dscr_("") {}
ParameterFileDihedralTerm::ParameterFileDihedralTerm (int factor, double force_constant, double phase, double periodicity, const std::string & dscr = "")
Definition at line 16 of file parameterfiledihedralterm.cc.
                                                                                                                                               :
    factor_(factor), force_constant_(force_constant), phase_(phase), periodicity_(periodicity), dscr_(dscr) {}
Member Function Documentation
std::string ParameterFileDihedralTerm::GetDscr ()
Definition at line 39 of file parameterfiledihedralterm.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveDihedralSection(), and ParameterFileSpace::ParameterFile::ResolveImproperDihedralSection().
{
    return dscr_;
}
int ParameterFileDihedralTerm::GetFactor ()
Definition at line 23 of file parameterfiledihedralterm.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveDihedralSection().
{
    return factor_;
}
double ParameterFileDihedralTerm::GetForceConstant ()
Definition at line 27 of file parameterfiledihedralterm.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralTypesFromAssembly(), ParameterFileSpace::ParameterFile::ResolveDihedralSection(), and ParameterFileSpace::ParameterFile::ResolveImproperDihedralSection().
{
    return force_constant_;
}
double ParameterFileDihedralTerm::GetPeriodicity ()
Definition at line 35 of file parameterfiledihedralterm.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralTypesFromAssembly(), ParameterFileSpace::ParameterFile::ResolveDihedralSection(), and ParameterFileSpace::ParameterFile::ResolveImproperDihedralSection().
{
    return periodicity_;
}
double ParameterFileDihedralTerm::GetPhase ()
Definition at line 31 of file parameterfiledihedralterm.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralTypesFromAssembly(), ParameterFileSpace::ParameterFile::ResolveDihedralSection(), and ParameterFileSpace::ParameterFile::ResolveImproperDihedralSection().
{
    return phase_;
}
void ParameterFileDihedralTerm::Print (std::ostream & out = std::cout)
Definition at line 70 of file parameterfiledihedralterm.cc.
References gmml::dNotSet, and gmml::iNotSet.
{
    if(factor_ == iNotSet)
        out << std::setw(10) << "--";
    else
        out << std::setw(10) << factor_;
    if(force_constant_ == dNotSet)
        out << std::setw(10) << "--";
    else
        out << std::setw(10) << force_constant_;
    if(phase_ == dNotSet)
        out << std::setw(10) << "--";
    else
        out << std::setw(10) << phase_;
    if(periodicity_ == dNotSet)
        out << std::setw(12) << "--";
    else
        out << std::setw(12) << periodicity_;
    out << std::setw(60) << dscr_
        << std::endl;
}
void ParameterFileDihedralTerm::SetDscr (std::string dscr)
Definition at line 63 of file parameterfiledihedralterm.cc.
Referenced by ParameterFileSpace::ParameterFile::ProcessDihedral(), and ParameterFileSpace::ParameterFile::ProcessImproperDihedral().
{
    dscr_ = dscr;
}
void ParameterFileDihedralTerm::SetFactor (int factor)
Definition at line 47 of file parameterfiledihedralterm.cc.
Referenced by ParameterFileSpace::ParameterFile::ProcessDihedral(), and ParameterFileSpace::ParameterFile::ProcessImproperDihedral().
{
    factor_ = factor;
}
void ParameterFileDihedralTerm::SetForceConstant (double force_constant)
Definition at line 51 of file parameterfiledihedralterm.cc.
Referenced by ParameterFileSpace::ParameterFile::ProcessDihedral(), and ParameterFileSpace::ParameterFile::ProcessImproperDihedral().
{
    force_constant_ = force_constant;
}
void ParameterFileDihedralTerm::SetPeriodicity (double periodicity)
Definition at line 59 of file parameterfiledihedralterm.cc.
Referenced by ParameterFileSpace::ParameterFile::ProcessDihedral(), and ParameterFileSpace::ParameterFile::ProcessImproperDihedral().
{
    periodicity_ = periodicity;
}
void ParameterFileDihedralTerm::SetPhase (double phase)
Definition at line 55 of file parameterfiledihedralterm.cc.
Referenced by ParameterFileSpace::ParameterFile::ProcessDihedral(), and ParameterFileSpace::ParameterFile::ProcessImproperDihedral().
{
    phase_ = phase;
}
The documentation for this class was generated from the following files:
includes/ParameterSet/ParameterFileSpace/parameterfiledihedralterm.hpp
src/ParameterSet/ParameterFileSpace/parameterfiledihedralterm.cc