######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 20 15:19:23 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              includes \
              includes/ParameterSet/ParameterFileSpace \
              src/ParameterSet/ParameterFileSpace
INCLUDEPATH += . includes/ParameterSet/ParameterFileSpace includes

# Input
HEADERS += includes/common.hpp \
           includes/utils.hpp \
           includes/ParameterSet/ParameterFileSpace/parameterfile.hpp \
           includes/ParameterSet/ParameterFileSpace/parameterfileangle.hpp \
           includes/ParameterSet/ParameterFileSpace/parameterfileatom.hpp \
           includes/ParameterSet/ParameterFileSpace/parameterfilebond.hpp \
           includes/ParameterSet/ParameterFileSpace/parameterfiledihedral.hpp \
           includes/ParameterSet/ParameterFileSpace/parameterfiledihedralterm.hpp \
           includes/ParameterSet/ParameterFileSpace/parameterfileprocessingexception.hpp \
    includes/ParameterSet/PrepFileSpace/prepfileatom.hpp \
    includes/ParameterSet/PrepFileSpace/prepfileresidue.hpp \
    includes/ParameterSet/PrepFileSpace/prepfile.hpp \
    includes/ParameterSet/PrepFileSpace/prepfileprocessingexception.hpp \
    includes/ParameterSet/LibraryFileSpace/libraryfileatom.hpp \
    includes/Geometry/coordinate.hpp \
    includes/ParameterSet/LibraryFileSpace/libraryfileresidue.hpp \
    includes/ParameterSet/LibraryFileSpace/libraryfile.hpp \
    includes/ParameterSet/LibraryFileSpace/libraryfileprocessingexception.hpp \
    includes/FileSet/CoordinateFileSpace/coordinatefileprocessingexception.hpp \
    includes/FileSet/CoordinateFileSpace/coordinatefile.hpp
SOURCES += main.cc \
           src/ParameterSet/ParameterFileSpace/parameterfile.cc \
           src/ParameterSet/ParameterFileSpace/parameterfileangle.cc \
           src/ParameterSet/ParameterFileSpace/parameterfileatom.cc \
           src/ParameterSet/ParameterFileSpace/parameterfilebond.cc \
           src/ParameterSet/ParameterFileSpace/parameterfiledihedral.cc \
           src/ParameterSet/ParameterFileSpace/parameterfiledihedralterm.cc \
           src/ParameterSet/ParameterFileSpace/parameterfileprocessingexception.cc \
    src/ParameterSet/PrepFileSpace/prepfileatom.cc \
    src/ParameterSet/PrepFileSpace/prepfileresidue.cc \
    src/ParameterSet/PrepFileSpace/prepfile.cc \
    src/ParameterSet/PrepFileSpace/prepfileprocessingexception.cc \
    src/Geometry/coordinate.cc \
    src/ParameterSet/LibraryFileSpace/libraryfileatom.cc \
    src/ParameterSet/LibraryFileSpace/libraryfileresidue.cc \
    src/ParameterSet/LibraryFileSpace/libraryfile.cc \
    src/ParameterSet/LibraryFileSpace/libraryfileprocessingexception.cc \
    src/FileSet/CoordinateFileSpace/coordinatefileprocessingexception.cc \
    src/FileSet/CoordinateFileSpace/coordinatefile.cc
