######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 20 15:19:23 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              includes \
              includes/ParameterSet/ParameterFileSpace \
              src/ParameterSet/ParameterFileSpace
INCLUDEPATH += . includes/ParameterSet/ParameterFileSpace includes

# Input
HEADERS += includes/common.hpp \
           includes/utils.hpp \
           includes/ParameterSet/ParameterFileSpace/parameterfile.hpp \
           includes/ParameterSet/ParameterFileSpace/parameterfileangle.hpp \
           includes/ParameterSet/ParameterFileSpace/parameterfileatom.hpp \
           includes/ParameterSet/ParameterFileSpace/parameterfilebond.hpp \
           includes/ParameterSet/ParameterFileSpace/parameterfiledihedral.hpp \
           includes/ParameterSet/ParameterFileSpace/parameterfiledihedralterm.hpp \
           includes/ParameterSet/ParameterFileSpace/parameterfileprocessingexception.hpp
SOURCES += main.cc \
           src/ParameterSet/ParameterFileSpace/parameterfile.cc \
           src/ParameterSet/ParameterFileSpace/parameterfileangle.cc \
           src/ParameterSet/ParameterFileSpace/parameterfileatom.cc \
           src/ParameterSet/ParameterFileSpace/parameterfilebond.cc \
           src/ParameterSet/ParameterFileSpace/parameterfiledihedral.cc \
           src/ParameterSet/ParameterFileSpace/parameterfiledihedralterm.cc \
           src/ParameterSet/ParameterFileSpace/parameterfileprocessingexception.cc
