gmmlNew: PdbFileSpace::PdbResidueModification Class Reference
PdbFileSpace::PdbResidueModification Class Reference
#include <pdbresiduemodification.hpp>
Public Member Functions
PdbResidueModification ()
PdbResidueModification (const std::string &id_code, const std::string &residue_name, char chain_id, int sequence_number, char insertion_code, const std::string &standard_residue_name, const std::string &dscr)
PdbResidueModification (std::stringstream &stream_block)
std::string GetIdCode ()
std::string GetResidueName ()
char GetChainId ()
int GetSequenceNumber ()
char GetInsertionCode ()
std::string GetStandardResidueName ()
std::string GetDscr ()
void SetIdCode (const std::string id_code)
void SetResidueName (const std::string residue_name)
void SetChainId (char chain_id)
void SetSequenceNumber (int sequence_number)
void SetInsertionCode (char insertion_code)
void SetStandardResidueName (const std::string standard_residue_name)
void SetDscr (const std::string dscr)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 12 of file pdbresiduemodification.hpp.
Constructor & Destructor Documentation
PdbResidueModification::PdbResidueModification ()
Definition at line 14 of file pdbresiduemodification.cc.
                                               : id_code_(""), residue_name_(""), chain_id_(' '), sequence_number_(dNotSet),
    insertion_code_(' '), standard_residue_name_(""), dscr_("") {}
PdbFileSpace::PdbResidueModification::PdbResidueModification (const std::string & id_code, const std::string & residue_name, char chain_id, int sequence_number, char insertion_code, const std::string & standard_residue_name, const std::string & dscr)
PdbFileSpace::PdbResidueModification::PdbResidueModification (std::stringstream & stream_block)
Member Function Documentation
char PdbResidueModification::GetChainId ()
Definition at line 65 of file pdbresiduemodification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveModificationResidueCard().
{
    return chain_id_;
}
std::string PdbResidueModification::GetDscr ()
Definition at line 85 of file pdbresiduemodification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveModificationResidueCard().
{
    return dscr_;
}
std::string PdbResidueModification::GetIdCode ()
Definition at line 55 of file pdbresiduemodification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveModificationResidueCard().
{
    return id_code_;
}
char PdbResidueModification::GetInsertionCode ()
Definition at line 75 of file pdbresiduemodification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveModificationResidueCard().
{
    return insertion_code_;
}
std::string PdbResidueModification::GetResidueName ()
Definition at line 60 of file pdbresiduemodification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveModificationResidueCard().
{
    return residue_name_;
}
int PdbResidueModification::GetSequenceNumber ()
Definition at line 70 of file pdbresiduemodification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveModificationResidueCard().
{
    return sequence_number_;
}
std::string PdbResidueModification::GetStandardResidueName ()
Definition at line 80 of file pdbresiduemodification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveModificationResidueCard().
{
    return standard_residue_name_;
}
void PdbResidueModification::Print (std::ostream & out = std::cout)
Definition at line 135 of file pdbresiduemodification.cc.
References gmml::iNotSet.
{
    out << "ID Code: " << id_code_
        << ", Residue Name: " << residue_name_
        << ", Chain Identifier: " << chain_id_
        << ", Sequence Number: ";
    if(sequence_number_ != iNotSet)
        out << sequence_number_;
    else
        out << " ";
    out << ", Insertion Code: " << insertion_code_
        << ", Standard Residue Name: " << standard_residue_name_
        << ", Description: " << dscr_ << endl;
}
void PdbResidueModification::SetChainId (char chain_id)
Definition at line 103 of file pdbresiduemodification.cc.
{
    chain_id_ = chain_id;
}
void PdbResidueModification::SetDscr (const std::string dscr)
Definition at line 123 of file pdbresiduemodification.cc.
{
    dscr_ = dscr;
}
void PdbResidueModification::SetIdCode (const std::string id_code)
Definition at line 93 of file pdbresiduemodification.cc.
{
    id_code_ = id_code;
}
void PdbResidueModification::SetInsertionCode (char insertion_code)
Definition at line 113 of file pdbresiduemodification.cc.
{
    insertion_code_ = insertion_code;
}
void PdbResidueModification::SetResidueName (const std::string residue_name)
Definition at line 98 of file pdbresiduemodification.cc.
{
    residue_name_ = residue_name;
}
void PdbResidueModification::SetSequenceNumber (int sequence_number)
Definition at line 108 of file pdbresiduemodification.cc.
{
    sequence_number_ = sequence_number;
}
void PdbResidueModification::SetStandardResidueName (const std::string standard_residue_name)
Definition at line 118 of file pdbresiduemodification.cc.
{
    standard_residue_name_ = standard_residue_name;
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbresiduemodification.hpp
src/FileSet/PdbFileSpace/pdbresiduemodification.cc