gmmlNew: TopologyFileSpace::TopologyAngleType Class Reference
TopologyFileSpace::TopologyAngleType Class Reference
#include <topologyangletype.hpp>
Public Member Functions
TopologyAngleType ()
TopologyAngleType (int index, double force_constant, double equilibrium_value)
int GetIndex ()
double GetForceConstant ()
double GetEquilibriumValue ()
void SetIndex (int index)
void SetForceConstant (double force_constant)
void SetEquilibriumValue (double equilibrium_value)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 10 of file topologyangletype.hpp.
Constructor & Destructor Documentation
TopologyAngleType::TopologyAngleType ()
Definition at line 10 of file topologyangletype.cc.
{}
TopologyAngleType::TopologyAngleType (int index, double force_constant, double equilibrium_value)
Definition at line 12 of file topologyangletype.cc.
                                                                                               :
    index_(index), force_constant_(force_constant), equilibrium_value_(equilibrium_value) {}
Member Function Documentation
double TopologyAngleType::GetEquilibriumValue ()
Definition at line 26 of file topologyangletype.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveAngleEquilValueSection().
{
    return equilibrium_value_;
}
double TopologyAngleType::GetForceConstant ()
Definition at line 22 of file topologyangletype.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveAngleForceConstantSection().
{
    return force_constant_;
}
int TopologyAngleType::GetIndex ()
Definition at line 18 of file topologyangletype.cc.
Referenced by TopologyFileSpace::TopologyFile::AddAngleType(), TopologyFileSpace::TopologyFile::GetAngleTypeByIndex(), TopologyFileSpace::TopologyFile::ResolveAnglesIncHydrogenSection(), and TopologyFileSpace::TopologyFile::ResolveAnglesWithoutHydrogenSection().
{
    return index_;
}
void TopologyAngleType::Print (std::ostream & out = std::cout)
Definition at line 54 of file topologyangletype.cc.
Referenced by TopologyFileSpace::TopologyAngle::Print(), and TopologyFileSpace::TopologyFile::Print().
{
    out << "Angle index: " << index_
         << ", Force constant: " << force_constant_
         << ", Equilibrium value: " << equilibrium_value_;
}
void TopologyAngleType::SetEquilibriumValue (double equilibrium_value)
Definition at line 43 of file topologyangletype.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyAngleTypesFromAssembly().
{
    equilibrium_value_ = equilibrium_value;
}
void TopologyAngleType::SetForceConstant (double force_constant)
Definition at line 39 of file topologyangletype.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyAngleTypesFromAssembly().
{
    force_constant_ = force_constant;
}
void TopologyAngleType::SetIndex (int index)
Definition at line 35 of file topologyangletype.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyAngleTypesFromAssembly().
{
    index_ = index;
}
The documentation for this class was generated from the following files:
includes/FileSet/TopologyFileSpace/topologyangletype.hpp
src/FileSet/TopologyFileSpace/topologyangletype.cc