gmmlNew: ParameterFileSpace::ParameterFileDihedral Class Reference
ParameterFileSpace::ParameterFileDihedral Class Reference
#include <parameterfiledihedral.hpp>
Public Member Functions
ParameterFileDihedral ()
ParameterFileDihedral (const std::vector< std::string > &types, const ParameterFileDihedralTerm &term, double scee=gmml::dNotSet, double scnb=gmml::dNotSet, bool is_generic=false, bool is_improper=false)
std::vector< std::string > GetTypes ()
std::vector
< ParameterFileDihedralTerm > GetTerms ()
double GetScee ()
double GetScnb ()
bool GetIsGeneric ()
bool GetIsImproper ()
void SetTypes (const std::vector< std::string > types)
void SetTerms (const std::vector< ParameterFileDihedralTerm > terms)
void AddTerm (ParameterFileDihedralTerm term)
void SetScee (double scee)
void SetScnb (double scnb)
void SetIsGeneric (bool is_generic)
void SetIsImproper (bool is_improper)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 12 of file parameterfiledihedral.hpp.
Constructor & Destructor Documentation
ParameterFileDihedral::ParameterFileDihedral ()
Definition at line 14 of file parameterfiledihedral.cc.
    : types_(), terms_(), scee_(dNotSet), scnb_(dNotSet), is_generic_(false), is_improper_(false) {}
ParameterFileDihedral::ParameterFileDihedral (const std::vector< std::string > & types, const ParameterFileDihedralTerm & term, double scee = gmml::dNotSet, double scnb = gmml::dNotSet, bool is_generic = false, bool is_improper = false)
Definition at line 17 of file parameterfiledihedral.cc.
    : types_(types), terms_(), scee_(scee), scnb_(scnb), is_generic_(is_generic), is_improper_(is_improper)
{
    terms_.push_back(term);
}
Member Function Documentation
void ParameterFileDihedral::AddTerm (ParameterFileDihedralTerm term)
Definition at line 78 of file parameterfiledihedral.cc.
Referenced by ParameterFileSpace::ParameterFile::ProcessDihedral(), and ParameterFileSpace::ParameterFile::ProcessImproperDihedral().
{
    terms_.push_back(term);
}
bool ParameterFileDihedral::GetIsGeneric ()
Definition at line 48 of file parameterfiledihedral.cc.
{
    return is_generic_;
}
bool ParameterFileDihedral::GetIsImproper ()
Definition at line 53 of file parameterfiledihedral.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveDihedralSection(), and ParameterFileSpace::ParameterFile::ResolveImproperDihedralSection().
{
    return is_improper_;
}
double ParameterFileDihedral::GetScee ()
Definition at line 38 of file parameterfiledihedral.cc.
{
    return scee_;
}
double ParameterFileDihedral::GetScnb ()
Definition at line 43 of file parameterfiledihedral.cc.
{
    return scnb_;
}
std::vector< ParameterFileDihedralTerm > ParameterFileDihedral::GetTerms ()
Definition at line 33 of file parameterfiledihedral.cc.
Referenced by ParameterFileSpace::ParameterFile::ProcessDihedral(), ParameterFileSpace::ParameterFile::ProcessImproperDihedral(), ParameterFileSpace::ParameterFile::ResolveDihedralSection(), and ParameterFileSpace::ParameterFile::ResolveImproperDihedralSection().
{
    return terms_;
}
std::vector< std::string > ParameterFileDihedral::GetTypes ()
Definition at line 28 of file parameterfiledihedral.cc.
Referenced by ParameterFileSpace::ParameterFile::ProcessDihedral(), and ParameterFileSpace::ParameterFile::ProcessImproperDihedral().
{
    return types_;
}
void ParameterFileDihedral::Print (std::ostream & out = std::cout)
Definition at line 101 of file parameterfiledihedral.cc.
References gmml::dNotSet.
{
    for(std::vector<std::string>::iterator it = types_.begin(); it != types_.end(); it++)
    {
        if(it != types_.end() - 1)
        {
            out << std::setw(4) << (*it)
                << std::setw(2) << "-";
        }
        else
            out << std::setw(4) << (*it);
    }
    if(is_generic_ == true)
        out << std::setw(10) << "YES";
    else
        out << std::setw(10) << "NO";
    if(is_improper_ == true)
        out << std::setw(10) << "YES";
    else
        out << std::setw(10) << "NO";
    if(scee_ == dNotSet)
        out << std::setw(6) << "--";
    else
        out << std::setw(6) << scee_;
    if(scnb_ == dNotSet)
        out << std::setw(6) << "--";
    else
        out << std::setw(6) << scnb_;
    for(std::vector<ParameterFileDihedralTerm>::iterator it = terms_.begin(); it != terms_.end(); it++)
    {
        if(it == terms_.begin())
            it->Print(out);
        else
        {
            out << std::setw(54) << "";
            it -> Print(out);
        }
    }
}
void ParameterFileDihedral::SetIsGeneric (bool is_generic)
Definition at line 90 of file parameterfiledihedral.cc.
Referenced by ParameterFileSpace::ParameterFile::ProcessDihedral(), and ParameterFileSpace::ParameterFile::ProcessImproperDihedral().
{
    is_generic_ = is_generic;
}
void ParameterFileDihedral::SetIsImproper (bool is_improper)
Definition at line 94 of file parameterfiledihedral.cc.
Referenced by ParameterFileSpace::ParameterFile::ProcessDihedral(), and ParameterFileSpace::ParameterFile::ProcessImproperDihedral().
{
    is_improper_ = is_improper;
}
void ParameterFileDihedral::SetScee (double scee)
Definition at line 82 of file parameterfiledihedral.cc.
{
    scee_ = scee;
}
void ParameterFileDihedral::SetScnb (double scnb)
Definition at line 86 of file parameterfiledihedral.cc.
{
    scnb_ = scnb;
}
void ParameterFileDihedral::SetTerms (const std::vector< ParameterFileDihedralTerm > terms)
Definition at line 70 of file parameterfiledihedral.cc.
{
    terms_.clear();
    for(std::vector<ParameterFileDihedralTerm>::iterator it = terms.begin(); it != terms.end(); it++)
    {
        terms_.push_back(*it);
    }
}
void ParameterFileDihedral::SetTypes (const std::vector< std::string > types)
Definition at line 62 of file parameterfiledihedral.cc.
{
    types_.clear();
    for(std::vector<std::string>::iterator it = types.begin(); it != types.end(); it++)
    {
        types_.push_back(*it);
    }
}
The documentation for this class was generated from the following files:
includes/ParameterSet/ParameterFileSpace/parameterfiledihedral.hpp
src/ParameterSet/ParameterFileSpace/parameterfiledihedral.cc