gmmlNew: PrepFileSpace::PrepFileAtom Class Reference
PrepFileSpace::PrepFileAtom Class Reference
#include <prepfileatom.hpp>
Public Member Functions
PrepFileAtom ()
PrepFileAtom (int index, const std::string &name, const std::string &type, TopologicalType topological_type, int bond_index, int angle_index, int dihedral_index, double bond_length, double angle, double dihedral, double charge)
PrepFileAtom (std::string &line)
Create a prep file atom by a formatted line.
TopologicalType ExtractAtomTopologicalType (std::istream &ss)
void Print (std::ostream &out=std::cout)
int GetIndex ()
std::string GetName ()
std::string GetType ()
TopologicalType GetTopologicalType ()
int GetBondIndex ()
int GetAngleIndex ()
int GetDihedralIndex ()
double GetBondLength ()
double GetAngle ()
double GetDihedral ()
double GetCharge ()
std::string GetStringFormatOfTopologicalType (TopologicalType topological_type)
std::string GetStringFormatOfTopologicalType ()
TopologicalType GetTopologicalTypeFromString (std::string topological_type)
void SetIndex (int index)
void SetName (std::string name)
void SetType (std::string type)
void SetTopologicalType (TopologicalType topological_type)
void SetBondIndex (int bond_index)
void SetAngleIndex (int angle_index)
void SetDihedralIndex (int dihedral_index)
void SetBondLength (double bond_length)
void SetAngle (double angle)
void SetDihedral (double dihedral)
void SetCharge (double charge)
Public Attributes
int index_
std::string name_
std::string type_
TopologicalType topological_type_
int bond_index_
int angle_index_
int dihedral_index_
double bond_length_
double angle_
double dihedral_
double charge_
Detailed Description
Definition at line 23 of file prepfileatom.hpp.
Constructor & Destructor Documentation
PrepFileAtom::PrepFileAtom ()
Definition at line 14 of file prepfileatom.cc.
                           : index_(0), name_(""), type_(""), topological_type_(kTopTypeM), bond_index_(0), angle_index_(0), dihedral_index_(0),
    bond_length_(dNotSet), angle_(dNotSet), dihedral_(dNotSet), charge_(dNotSet) {}
PrepFileSpace::PrepFileAtom::PrepFileAtom (int index, const std::string & name, const std::string & type, TopologicalType topological_type, int bond_index, int angle_index, int dihedral_index, double bond_length, double angle, double dihedral, double charge)
PrepFileAtom::PrepFileAtom (std::string & line)
Create a prep file atom by a formatted line.
Definition at line 23 of file prepfileatom.cc.
References angle_, angle_index_, bond_index_, bond_length_, charge_, dihedral_, dihedral_index_, ExtractAtomTopologicalType(), index_, name_, topological_type_, and type_.
{
    std::stringstream ss(line);
    ss >> index_
       >> name_
       >> type_;
    topological_type_ = ExtractAtomTopologicalType(ss);
    ss >> bond_index_
       >> angle_index_
       >> dihedral_index_
       >> bond_length_
       >> angle_
       >> dihedral_
       >> charge_;
}
Member Function Documentation
TopologicalType PrepFileAtom::ExtractAtomTopologicalType (std::istream & ss)
Extract corresponding topological type from a stream line Return value is an enumeration type
Definition at line 46 of file prepfileatom.cc.
References PrepFileSpace::kTopType3, PrepFileSpace::kTopTypeB, PrepFileSpace::kTopTypeE, PrepFileSpace::kTopTypeM, and PrepFileSpace::kTopTypeS.
Referenced by PrepFileAtom().
{
    string s;
    ss >> s;
    if (s == "M")
        return kTopTypeM;
    else if (s == "S")
        return kTopTypeS;
    else if (s == "B")
        return kTopTypeB;
    else if (s == "E")
        return kTopTypeE;
    else
        return kTopType3;
}
double PrepFileAtom::GetAngle ()
Definition at line 97 of file prepfileatom.cc.
References angle_.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), and PrepFileSpace::PrepFile::BuildPrepFile().
{
    return angle_;
}
int PrepFileAtom::GetAngleIndex ()
Definition at line 85 of file prepfileatom.cc.
References angle_index_.
Referenced by PrepFileSpace::PrepFile::BuildPrepFile().
{
    return angle_index_;
}
int PrepFileAtom::GetBondIndex ()
Definition at line 81 of file prepfileatom.cc.
References bond_index_.
Referenced by PrepFileSpace::PrepFile::BuildPrepFile().
{
    return bond_index_;
}
double PrepFileAtom::GetBondLength ()
Definition at line 93 of file prepfileatom.cc.
References bond_length_.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), and PrepFileSpace::PrepFile::BuildPrepFile().
{
    return bond_length_;
}
double PrepFileAtom::GetCharge ()
Definition at line 105 of file prepfileatom.cc.
References charge_.
Referenced by PrepFileSpace::PrepFile::BuildPrepFile().
{
    return charge_;
}
double PrepFileAtom::GetDihedral ()
Definition at line 101 of file prepfileatom.cc.
References dihedral_.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), and PrepFileSpace::PrepFile::BuildPrepFile().
{
    return dihedral_;
}
int PrepFileAtom::GetDihedralIndex ()
Definition at line 89 of file prepfileatom.cc.
References dihedral_index_.
Referenced by PrepFileSpace::PrepFile::BuildPrepFile().
{
    return dihedral_index_;
}
int PrepFileAtom::GetIndex ()
Definition at line 65 of file prepfileatom.cc.
References index_.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), PrepFileSpace::PrepFile::BuildPrepFile(), PrepFileSpace::PrepFileResidue::GetAtomNameByIndex(), and PrepFileSpace::PrepFileResidue::GetBondingsOfResidue().
{
    return index_;
}
std::string PrepFileAtom::GetName ()
Definition at line 69 of file prepfileatom.cc.
References name_.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), PrepFileSpace::PrepFile::BuildPrepFile(), MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), MolecularModeling::Assembly::BuildStructureByPrepFileInformation(), PrepFileSpace::PrepFile::GetAllAtomNamesOfResidue(), PrepFileSpace::PrepFileResidue::GetAtomNameByIndex(), and PrepFileSpace::PrepFileResidue::GetPrepAtomByName().
{
    return name_;
}
string PrepFileAtom::GetStringFormatOfTopologicalType (TopologicalType topological_type)
Definition at line 108 of file prepfileatom.cc.
References PrepFileSpace::kTopType3, PrepFileSpace::kTopType4, PrepFileSpace::kTopTypeB, PrepFileSpace::kTopTypeE, PrepFileSpace::kTopTypeM, and PrepFileSpace::kTopTypeS.
Referenced by PrepFileSpace::PrepFile::BuildPrepFile().
{
    switch(topological_type)
    {
        case kTopTypeE:
            return "E";
        case kTopTypeS:
            return "S";
        case kTopTypeB:
            return "B";
        case kTopType3:
            return "3";
        case kTopType4:
            return "4";
        case kTopTypeM:
            return "M";
        default:
            return "E";
    }
}
string PrepFileAtom::GetStringFormatOfTopologicalType ()
Definition at line 128 of file prepfileatom.cc.
References PrepFileSpace::kTopType3, PrepFileSpace::kTopType4, PrepFileSpace::kTopTypeB, PrepFileSpace::kTopTypeE, PrepFileSpace::kTopTypeM, PrepFileSpace::kTopTypeS, and topological_type_.
{
    switch(topological_type_)
    {
        case kTopTypeE:
            return "E";
        case kTopTypeS:
            return "S";
        case kTopTypeB:
            return "B";
        case kTopType3:
            return "3";
        case kTopType4:
            return "4";
        case kTopTypeM:
            return "M";
        default:
            return "E";
    }
}
TopologicalType PrepFileAtom::GetTopologicalType ()
Definition at line 77 of file prepfileatom.cc.
References topological_type_.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), and PrepFileSpace::PrepFileResidue::GetBondingsOfResidue().
{
    return topological_type_;
}
TopologicalType PrepFileAtom::GetTopologicalTypeFromString (std::string topological_type)
Definition at line 148 of file prepfileatom.cc.
References PrepFileSpace::kTopType3, PrepFileSpace::kTopType4, PrepFileSpace::kTopTypeB, PrepFileSpace::kTopTypeE, PrepFileSpace::kTopTypeM, and PrepFileSpace::kTopTypeS.
{
    if(topological_type.compare("E") == 0)
        return kTopTypeE;
    if(topological_type.compare("S") == 0)
        return kTopTypeS;
    if(topological_type.compare("B") == 0)
        return kTopTypeB;
    if(topological_type.compare("3") == 0)
        return kTopType3;
    if(topological_type.compare("4") == 0)
        return kTopType4;
    if(topological_type.compare("M") == 0)
        return kTopTypeM;
    else
        return kTopTypeE;
}
std::string PrepFileAtom::GetType ()
Definition at line 73 of file prepfileatom.cc.
References type_.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), PrepFileSpace::PrepFile::BuildPrepFile(), and PrepFileSpace::PrepFileResidue::GetBondingsOfResidue().
{
    return type_;
}
void PrepFileAtom::Print (std::ostream & out = std::cout)
Definition at line 217 of file prepfileatom.cc.
References angle_, angle_index_, bond_index_, bond_length_, charge_, dihedral_, dihedral_index_, index_, PrepFileSpace::kTopType3, PrepFileSpace::kTopType4, PrepFileSpace::kTopTypeB, PrepFileSpace::kTopTypeE, PrepFileSpace::kTopTypeM, PrepFileSpace::kTopTypeS, name_, topological_type_, and type_.
{
    out << setw(3) << index_
        << setw(6) << name_
        << setw(6) << type_;
    if(topological_type_ == kTopTypeE)
        out << setw(3) << "E";
    else if(topological_type_ == kTopTypeS)
        out << setw(3) << "S";
    else if(topological_type_ == kTopTypeB)
        out << setw(3) << "B";
    else if(topological_type_ == kTopType3)
        out << setw(3) << "3";
    else if(topological_type_ == kTopType4)
        out << setw(3) << "4";
    else if(topological_type_ == kTopTypeM)
        out << setw(3) << "M";
    else
        out << setw(3) << "-";
    out << setw(4) << bond_index_
        << setw(4) << angle_index_
        << setw(4) << dihedral_index_
        << setw(10) << bond_length_
        << setw(10) << angle_
        << setw(10) << dihedral_
        << setw(10) << charge_;
//        << endl;
}
void PrepFileAtom::SetAngle (double angle)
Definition at line 202 of file prepfileatom.cc.
References angle_.
{
    angle_ = angle;
}
void PrepFileAtom::SetAngleIndex (int angle_index)
Definition at line 190 of file prepfileatom.cc.
References angle_index_.
{
    angle_index_ = angle_index;
}
void PrepFileAtom::SetBondIndex (int bond_index)
Definition at line 186 of file prepfileatom.cc.
References bond_index_.
{
    bond_index_ = bond_index;
}
void PrepFileAtom::SetBondLength (double bond_length)
Definition at line 198 of file prepfileatom.cc.
References bond_length_.
{
    bond_length_ = bond_length;
}
void PrepFileAtom::SetCharge (double charge)
Definition at line 210 of file prepfileatom.cc.
References charge_.
{
    charge_ = charge;
}
void PrepFileAtom::SetDihedral (double dihedral)
Definition at line 206 of file prepfileatom.cc.
References dihedral_.
{
    dihedral_ = dihedral;
}
void PrepFileAtom::SetDihedralIndex (int dihedral_index)
Definition at line 194 of file prepfileatom.cc.
References dihedral_index_.
{
    dihedral_index_ = dihedral_index;
}
void PrepFileAtom::SetIndex (int index)
Definition at line 170 of file prepfileatom.cc.
References index_.
{
    index_ = index;
}
void PrepFileAtom::SetName (std::string name)
Definition at line 174 of file prepfileatom.cc.
References name_.
{
    name_ = name;
}
void PrepFileAtom::SetTopologicalType (TopologicalType topological_type)
Definition at line 182 of file prepfileatom.cc.
References topological_type_.
{
    topological_type_ = topological_type;
}
void PrepFileAtom::SetType (std::string type)
Definition at line 178 of file prepfileatom.cc.
References type_.
{
    type_ = type;
}
Member Data Documentation
double PrepFileSpace::PrepFileAtom::angle_
Angle; fill by the 9th column of the residue section of the file
Definition at line 243 of file prepfileatom.hpp.
Referenced by GetAngle(), PrepFileAtom(), Print(), and SetAngle().
int PrepFileSpace::PrepFileAtom::angle_index_
Angle index; fill by the 6th column of the residue section of the file
Definition at line 240 of file prepfileatom.hpp.
Referenced by GetAngleIndex(), PrepFileAtom(), Print(), and SetAngleIndex().
int PrepFileSpace::PrepFileAtom::bond_index_
Bond index; fill by the 5th column of the residue section of the file
Definition at line 239 of file prepfileatom.hpp.
Referenced by GetBondIndex(), PrepFileAtom(), Print(), and SetBondIndex().
double PrepFileSpace::PrepFileAtom::bond_length_
Bond length; fill by the 8th column of the residue section of the file
Definition at line 242 of file prepfileatom.hpp.
Referenced by GetBondLength(), PrepFileAtom(), Print(), and SetBondLength().
double PrepFileSpace::PrepFileAtom::charge_
Charge; fill by the 11th column of the residue section of the file Sample line of the residue section of a prep file: 4 H1 H1 M 3 2 1 1.000 90.0 180.0 0.0
Definition at line 245 of file prepfileatom.hpp.
Referenced by GetCharge(), PrepFileAtom(), Print(), and SetCharge().
double PrepFileSpace::PrepFileAtom::dihedral_
Dihedral; fill by the 10th column of the residue section of the file
Definition at line 244 of file prepfileatom.hpp.
Referenced by GetDihedral(), PrepFileAtom(), Print(), and SetDihedral().
int PrepFileSpace::PrepFileAtom::dihedral_index_
Dihedral index; fill by the 7th column of the residue section of the file
Definition at line 241 of file prepfileatom.hpp.
Referenced by GetDihedralIndex(), PrepFileAtom(), Print(), and SetDihedralIndex().
int PrepFileSpace::PrepFileAtom::index_
Atom index; fill by the first column of the residue section of the file
Definition at line 235 of file prepfileatom.hpp.
Referenced by GetIndex(), PrepFileAtom(), Print(), and SetIndex().
std::string PrepFileSpace::PrepFileAtom::name_
Atom name; fill by the second column of the residue section of the file
Definition at line 236 of file prepfileatom.hpp.
Referenced by GetName(), PrepFileAtom(), Print(), and SetName().
TopologicalType PrepFileSpace::PrepFileAtom::topological_type_
Topological type (for chain extraction of the residue); fill by th 4th column of the residue section of the file
Definition at line 238 of file prepfileatom.hpp.
Referenced by GetStringFormatOfTopologicalType(), GetTopologicalType(), PrepFileAtom(), Print(), and SetTopologicalType().
std::string PrepFileSpace::PrepFileAtom::type_
Atom type; fill by the third column of the residue section of the file
Definition at line 237 of file prepfileatom.hpp.
Referenced by GetType(), PrepFileAtom(), Print(), and SetType().
The documentation for this class was generated from the following files:
includes/ParameterSet/PrepFileSpace/prepfileatom.hpp
src/ParameterSet/PrepFileSpace/prepfileatom.cc