gmmlNew: PdbFileSpace::PdbModelResidueSet Class Reference
PdbFileSpace::PdbModelResidueSet Class Reference
#include <pdbmodelresidueset.hpp>
Public Types
typedef std::vector
< PdbAtomCard * > AtomCardVector
typedef std::vector
< PdbHeterogenAtomCard * > HeterogenAtomCardVector
Public Member Functions
PdbModelResidueSet ()
PdbModelResidueSet (std::stringstream &residue_set_block)
AtomCardVector GetAtoms ()
HeterogenAtomCardVector GetHeterogenAtoms ()
void SetAtoms (AtomCardVector atoms)
void AddAtom (PdbAtomCard *atom)
void SetHeterogenAtoms (HeterogenAtomCardVector heterogen_atoms)
void AddHeterogenAtom (PdbHeterogenAtomCard *heterogen_atom)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 17 of file pdbmodelresidueset.hpp.
Member Typedef Documentation
typedef std::vector<PdbAtomCard*> PdbFileSpace::PdbModelResidueSet::AtomCardVector
Definition at line 26 of file pdbmodelresidueset.hpp.
typedef std::vector<PdbHeterogenAtomCard*> PdbFileSpace::PdbModelResidueSet::HeterogenAtomCardVector
Definition at line 30 of file pdbmodelresidueset.hpp.
Constructor & Destructor Documentation
PdbModelResidueSet::PdbModelResidueSet ()
Definition at line 13 of file pdbmodelresidueset.cc.
{}
PdbFileSpace::PdbModelResidueSet::PdbModelResidueSet (std::stringstream & residue_set_block)
Member Function Documentation
void PdbModelResidueSet::AddAtom (PdbAtomCard * atom)
Definition at line 106 of file pdbmodelresidueset.cc.
Referenced by MolecularModeling::Assembly::ExtractPdbModelCardFromAssembly().
{
    atoms_.push_back(atom);
}
void PdbModelResidueSet::AddHeterogenAtom (PdbHeterogenAtomCard * heterogen_atom)
Definition at line 119 of file pdbmodelresidueset.cc.
Referenced by MolecularModeling::Assembly::ExtractPdbModelCardFromAssembly().
{
    heterogen_atoms_.push_back(heterogen_atom);
}
PdbModelResidueSet::AtomCardVector PdbModelResidueSet::GetAtoms ()
Definition at line 86 of file pdbmodelresidueset.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbFileSpace::PdbFile::GetAllAtomsInOrder(), PdbFileSpace::PdbFile::GetAllAtomsOfResidue(), PdbFileSpace::PdbFile::GetAllAtomsOfResidues(), PdbFileSpace::PdbFile::GetAllResidueNames(), PdbFileSpace::PdbFile::GetAllResidueNamesFromAtomCard(), PdbFileSpace::PdbFile::GetAllResidues(), PdbFileSpace::PdbFile::GetAllResiduesFromAtomCard(), PdbFileSpace::PdbFile::GetAtomBySerialNumber(), PdbFileSpace::PdbFile::GetAtomOfResidueByAtomKey(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return atoms_;
}
PdbModelResidueSet::HeterogenAtomCardVector PdbModelResidueSet::GetHeterogenAtoms ()
Definition at line 90 of file pdbmodelresidueset.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbFileSpace::PdbFile::GetAllAtomsInOrder(), PdbFileSpace::PdbFile::GetAllAtomsOfResidue(), PdbFileSpace::PdbFile::GetAllAtomsOfResidues(), PdbFileSpace::PdbFile::GetAllResidueNames(), PdbFileSpace::PdbFile::GetAllResidues(), PdbFileSpace::PdbFile::GetAtomBySerialNumber(), PdbFileSpace::PdbFile::GetAtomOfResidueByAtomKey(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return heterogen_atoms_;
}
void PdbModelResidueSet::Print (std::ostream & out = std::cout)
Definition at line 131 of file pdbmodelresidueset.cc.
Referenced by PdbFileSpace::PdbModel::Print().
{
    out << "----------------- Atoms -------------" << endl;
    for(PdbModelResidueSet::AtomCardVector::iterator it = atoms_.begin(); it != atoms_.end(); it++)
    {
        (*it)->Print(out);
    }
    out << endl << "-------------- Heterogen Atoms --------------" << endl;
    for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it = heterogen_atoms_.begin(); it != heterogen_atoms_.end(); it++)
    {
        (*it)->Print(out);
    }
    out << endl;
}
void PdbModelResidueSet::SetAtoms (PdbModelResidueSet::AtomCardVector atoms)
Definition at line 98 of file pdbmodelresidueset.cc.
Referenced by PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    atoms_.clear();
    for(AtomCardVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        atoms_.push_back(*it);
    }
}
void PdbModelResidueSet::SetHeterogenAtoms (PdbModelResidueSet::HeterogenAtomCardVector heterogen_atoms)
Definition at line 111 of file pdbmodelresidueset.cc.
Referenced by PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    heterogen_atoms_.clear();
    for(HeterogenAtomCardVector::iterator it = heterogen_atoms.begin(); it != heterogen_atoms.end(); it++)
    {
        heterogen_atoms_.push_back(*it);
    }
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbmodelresidueset.hpp
src/FileSet/PdbFileSpace/pdbmodelresidueset.cc