gmmlNew: PdbFileSpace::PdbHelix Class Reference
PdbFileSpace::PdbHelix Class Reference
#include <pdbhelix.hpp>
Public Types
typedef std::vector
< PdbHelixResidue * > HelixResidueVector
Public Member Functions
PdbHelix ()
PdbHelix (const std::string &helix_id, int helix_serial_number, HelixResidueVector helix_residues, PdbHelixClass helix_class, const std::string &comment, double helix_length)
PdbHelix (std::stringstream &stream_block)
std::string GetHelixId ()
int GetHelixSerialNumber ()
HelixResidueVector GetHelixResidues ()
PdbHelixClass GetHelixClass ()
std::string GetComment ()
double GetHelixLength ()
void SetHelixId (const std::string helix_id)
void SetHelixSerialNumber (int helix_serial_number)
void SetHelixResidues (const HelixResidueVector helix_residues)
void AddHelixResidue (PdbHelixResidue *helix_residue)
void SetHelixClass (PdbHelixClass helix_class)
void SetComment (const std::string &comment)
void SetHelixLength (double helix_length)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 32 of file pdbhelix.hpp.
Member Typedef Documentation
typedef std::vector<PdbHelixResidue*> PdbFileSpace::PdbHelix::HelixResidueVector
Definition at line 41 of file pdbhelix.hpp.
Constructor & Destructor Documentation
PdbHelix::PdbHelix ()
Definition at line 15 of file pdbhelix.cc.
: helix_id_(""), helix_serial_number_(dNotSet), helix_class_(POLYPROLINE), comment_(""), helix_length_(dNotSet) {}
PdbFileSpace::PdbHelix::PdbHelix (const std::string & helix_id, int helix_serial_number, HelixResidueVector helix_residues, PdbHelixClass helix_class, const std::string & comment, double helix_length)
PdbFileSpace::PdbHelix::PdbHelix (std::stringstream & stream_block)
Member Function Documentation
void PdbHelix::AddHelixResidue (PdbHelixResidue * helix_residue)
Definition at line 188 of file pdbhelix.cc.
{
    helix_residues_.push_back(helix_residue);
}
string PdbHelix::GetComment ()
Definition at line 156 of file pdbhelix.cc.
Referenced by PdbFileSpace::PdbFile::ResolveHelixCard().
{
    return comment_;
}
PdbHelixClass PdbHelix::GetHelixClass ()
Definition at line 151 of file pdbhelix.cc.
Referenced by PdbFileSpace::PdbFile::ResolveHelixCard().
{
    return helix_class_;
}
string PdbHelix::GetHelixId ()
Definition at line 136 of file pdbhelix.cc.
Referenced by PdbFileSpace::PdbFile::ResolveHelixCard().
{
    return helix_id_;
}
double PdbHelix::GetHelixLength ()
Definition at line 161 of file pdbhelix.cc.
Referenced by PdbFileSpace::PdbFile::ResolveHelixCard().
{
    return helix_length_;
}
PdbHelix::HelixResidueVector PdbHelix::GetHelixResidues ()
Definition at line 146 of file pdbhelix.cc.
Referenced by PdbFileSpace::PdbFile::ResolveHelixCard().
{
    return helix_residues_;
}
int PdbHelix::GetHelixSerialNumber ()
Definition at line 141 of file pdbhelix.cc.
Referenced by PdbFileSpace::PdbFile::ResolveHelixCard().
{
    return helix_serial_number_;
}
void PdbHelix::Print (std::ostream & out = std::cout)
Definition at line 215 of file pdbhelix.cc.
References gmml::dNotSet, gmml::iNotSet, and PdbFileSpace::UnknownHelix.
{
    out << "Helix ID: " << helix_id_
        << ", Helix Serial Number: ";
    if(helix_serial_number_ != iNotSet)
        out << helix_serial_number_;
    else
        out << " ";
    out << endl
        << "=============== Helix Residues ==============" << endl;
    for(PdbHelix::HelixResidueVector::iterator it = helix_residues_.begin(); it != helix_residues_.end(); it++)
    {
        (*it)->Print(out);
    }
    out << "Helix Class: ";
    if(helix_class_ != UnknownHelix)
        out << helix_class_;
    else
        out << " ";
    out << ", Comments: " << comment_
        << "Helix Length: ";
    if(helix_length_ != dNotSet)
        out << helix_length_ ;
    else
        out << " ";
    out << endl << endl;
}
void PdbHelix::SetComment (const std::string & comment)
Definition at line 198 of file pdbhelix.cc.
{
    comment_ = comment;
}
void PdbHelix::SetHelixClass (PdbHelixClass helix_class)
Definition at line 193 of file pdbhelix.cc.
{
    helix_class_ = helix_class;
}
void PdbHelix::SetHelixId (const std::string helix_id)
Definition at line 169 of file pdbhelix.cc.
{
    helix_id_ = helix_id;
}
void PdbHelix::SetHelixLength (double helix_length)
Definition at line 203 of file pdbhelix.cc.
{
    helix_length_ = helix_length;
}
void PdbHelix::SetHelixResidues (const HelixResidueVector helix_residues)
Definition at line 179 of file pdbhelix.cc.
{
    helix_residues_.clear();
    for(PdbHelix::HelixResidueVector::const_iterator it = helix_residues.begin(); it != helix_residues.end(); it++)
    {
        helix_residues_.push_back(*it);
    }
}
void PdbHelix::SetHelixSerialNumber (int helix_serial_number)
Definition at line 174 of file pdbhelix.cc.
{
    helix_serial_number_ = helix_serial_number;
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbhelix.hpp
src/FileSet/PdbFileSpace/pdbhelix.cc