gmmlNew: TopologyFileSpace::TopologyBond Class Reference
TopologyFileSpace::TopologyBond Class Reference
#include <topologybond.hpp>
Public Member Functions
TopologyBond ()
TopologyBond (std::vector< std::string > bonds, std::vector< std::string > residue_names)
std::vector< std::string > GetBonds ()
TopologyBondType * GetBondType ()
bool GetIncludingHydrogen ()
std::vector< std::string > GetResidueNames ()
void SetBonds (std::vector< std::string > bonds)
void SetBondType (TopologyBondType *bond_type)
void SetIncludingHydrogen (bool including_hydrogen)
void SetResidueNames (std::vector< std::string > residue_names)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 11 of file topologybond.hpp.
Constructor & Destructor Documentation
TopologyBond::TopologyBond ()
Definition at line 11 of file topologybond.cc.
{}
TopologyFileSpace::TopologyBond::TopologyBond (std::vector< std::string > bonds, std::vector< std::string > residue_names)
Member Function Documentation
vector< string > TopologyBond::GetBonds ()
Definition at line 30 of file topologybond.cc.
Referenced by TopologyFileSpace::TopologyFile::AddBond(), MolecularModeling::Assembly::BuildStructureByTOPFileInformation(), TopologyFileSpace::TopologyFile::ResolveBondsIncHydrogenSection(), and TopologyFileSpace::TopologyFile::ResolveBondsWithoutHydrogenSection().
{
    return bonds_;
}
TopologyBondType * TopologyBond::GetBondType ()
Definition at line 34 of file topologybond.cc.
Referenced by TopologyFileSpace::TopologyFile::AddBond(), TopologyFileSpace::TopologyFile::ParseSections(), TopologyFileSpace::TopologyFile::ResolveBondsIncHydrogenSection(), and TopologyFileSpace::TopologyFile::ResolveBondsWithoutHydrogenSection().
{
    return bond_type_;
}
bool TopologyBond::GetIncludingHydrogen ()
Definition at line 38 of file topologybond.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveBondsIncHydrogenSection(), and TopologyFileSpace::TopologyFile::ResolveBondsWithoutHydrogenSection().
{
    return including_hydrogen_;
}
vector< string > TopologyBond::GetResidueNames ()
Definition at line 42 of file topologybond.cc.
Referenced by TopologyFileSpace::TopologyFile::AddBond(), and MolecularModeling::Assembly::BuildStructureByTOPFileInformation().
{
    return residue_names_;
}
void TopologyBond::Print (std::ostream & out = std::cout)
Definition at line 82 of file topologybond.cc.
References TopologyFileSpace::TopologyBondType::Print().
Referenced by TopologyFileSpace::TopologyFile::Print().
{
    out << "Bond: " << residue_names_.at(0) << ":" << bonds_.at(0) << "-" << residue_names_.at(1) << ":" << bonds_.at(1) << endl;
    out << "\t ";
    bond_type_->Print(out);
    out << ", Including Hydrogen: ";
    if(including_hydrogen_)
        out << "YES";
    else
        out << "NO";
    out << endl;
}
void TopologyBond::SetBonds (std::vector< std::string > bonds)
Definition at line 50 of file topologybond.cc.
{
    bonds_.clear();
    for(vector<string>::iterator it = bonds.begin(); it != bonds.end(); it++)
    {
        bonds_.push_back(*it);
    }
}
void TopologyBond::SetBondType (TopologyBondType * bond_type)
Definition at line 58 of file topologybond.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyBondsFromAssembly(), and TopologyFileSpace::TopologyFile::ParseSections().
{
    bond_type_ = bond_type;
}
void TopologyBond::SetIncludingHydrogen (bool including_hydrogen)
Definition at line 62 of file topologybond.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyBondsFromAssembly(), and TopologyFileSpace::TopologyFile::ParseSections().
{
    including_hydrogen_ = including_hydrogen;
}
void TopologyBond::SetResidueNames (std::vector< std::string > residue_names)
Definition at line 66 of file topologybond.cc.
{
    residue_names_.clear();
    for(vector<string>::iterator it = residue_names.begin(); it != residue_names.end(); it++)
    {
        residue_names_.push_back(*it);
    }
}
The documentation for this class was generated from the following files:
includes/FileSet/TopologyFileSpace/topologybond.hpp
src/FileSet/TopologyFileSpace/topologybond.cc