gmmlNew: PdbFileSpace::PdbFormula Class Reference
PdbFileSpace::PdbFormula Class Reference
#include <pdbformula.hpp>
Public Member Functions
PdbFormula ()
PdbFormula (const std::string &heterogen_identifier, int component_number, const std::string &chemical_formula)
PdbFormula (std::stringstream &specification_block)
std::string GetHeterogenIdentifier ()
int GetComponentNumber ()
std::string GetChemicalFormula ()
void SetHeterogenIdentifier (const std::string heterogen_identifier)
void SetComponentNumber (int component_number)
void SetChemicalFormula (const std::string chemical_formula)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 12 of file pdbformula.hpp.
Constructor & Destructor Documentation
PdbFormula::PdbFormula ()
Definition at line 14 of file pdbformula.cc.
: heterogen_identifier_(""), component_number_(dNotSet), chemical_formula_("") {}
PdbFileSpace::PdbFormula::PdbFormula (const std::string & heterogen_identifier, int component_number, const std::string & chemical_formula)
PdbFileSpace::PdbFormula::PdbFormula (std::stringstream & specification_block)
Member Function Documentation
string PdbFormula::GetChemicalFormula ()
Definition at line 62 of file pdbformula.cc.
Referenced by PdbFileSpace::PdbFile::ResolveFormulaCard().
{
    return chemical_formula_;
}
int PdbFormula::GetComponentNumber ()
Definition at line 57 of file pdbformula.cc.
Referenced by PdbFileSpace::PdbFile::ResolveFormulaCard().
{
    return component_number_;
}
string PdbFormula::GetHeterogenIdentifier ()
Definition at line 52 of file pdbformula.cc.
Referenced by PdbFileSpace::PdbFile::ResolveFormulaCard().
{
    return heterogen_identifier_;
}
void PdbFormula::Print (std::ostream & out = std::cout)
Definition at line 92 of file pdbformula.cc.
References gmml::iNotSet.
{
    out << "Heterogen ID: " << heterogen_identifier_
        << ", Component Number: ";
    if(component_number_ != iNotSet)
        out << component_number_;
    else
        out << " ";
    out << "Chemical Formula: " << chemical_formula_ << endl;
}
void PdbFormula::SetChemicalFormula (const std::string chemical_formula)
Definition at line 80 of file pdbformula.cc.
{
    chemical_formula_ = chemical_formula;
}
void PdbFormula::SetComponentNumber (int component_number)
Definition at line 75 of file pdbformula.cc.
{
    component_number_ = component_number;
}
void PdbFormula::SetHeterogenIdentifier (const std::string heterogen_identifier)
Definition at line 70 of file pdbformula.cc.
{
    heterogen_identifier_ = heterogen_identifier;
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbformula.hpp
src/FileSet/PdbFileSpace/pdbformula.cc