gmmlNew: PdbFileSpace::PdbHeterogenAtomCard Class Reference
PdbFileSpace::PdbHeterogenAtomCard Class Reference
#include <pdbheterogenatomcard.hpp>
Public Types
typedef PdbAtom PdbHeterogenAtom
typedef std::map< int,
PdbHeterogenAtom * > PdbHeterogenAtomMap
Public Member Functions
PdbHeterogenAtomCard ()
PdbHeterogenAtomCard (std::stringstream &stream_block, std::string index)
std::string GetRecordName ()
PdbHeterogenAtomMap GetHeterogenAtoms ()
void SetRecordName (const std::string record_name)
void SetHeterogenAtoms (PdbHeterogenAtomMap heterogen_atoms)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 15 of file pdbheterogenatomcard.hpp.
Member Typedef Documentation
typedef PdbAtom PdbFileSpace::PdbHeterogenAtomCard::PdbHeterogenAtom
Definition at line 24 of file pdbheterogenatomcard.hpp.
typedef std::map<int, PdbHeterogenAtom*> PdbFileSpace::PdbHeterogenAtomCard::PdbHeterogenAtomMap
Definition at line 28 of file pdbheterogenatomcard.hpp.
Constructor & Destructor Documentation
PdbHeterogenAtomCard::PdbHeterogenAtomCard ()
Definition at line 13 of file pdbheterogenatomcard.cc.
: record_name_("HETATM") {}
PdbFileSpace::PdbHeterogenAtomCard::PdbHeterogenAtomCard (std::stringstream & stream_block, std::string index)
Member Function Documentation
PdbHeterogenAtomCard::PdbHeterogenAtomMap PdbHeterogenAtomCard::GetHeterogenAtoms ()
Definition at line 46 of file pdbheterogenatomcard.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbFileSpace::PdbFile::GetAllAtomsInOrder(), PdbFileSpace::PdbFile::GetAllAtomsOfResidue(), PdbFileSpace::PdbFile::GetAllAtomsOfResidues(), PdbFileSpace::PdbFile::GetAllResidueNames(), PdbFileSpace::PdbFile::GetAllResidues(), PdbFileSpace::PdbFile::GetAtomBySerialNumber(), PdbFileSpace::PdbFile::GetAtomOfResidueByAtomKey(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return heterogen_atoms_;
}
string PdbHeterogenAtomCard::GetRecordName ()
Definition at line 41 of file pdbheterogenatomcard.cc.
Referenced by PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), and PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber().
{
    return record_name_;
}
void PdbHeterogenAtomCard::Print (std::ostream & out = std::cout)
Definition at line 77 of file pdbheterogenatomcard.cc.
References gmml::iNotSet.
{
    out << "Record Name: " << record_name_ << endl <<
           "________________ Heterogen Atoms ___________________" << endl;
    for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it = heterogen_atoms_.begin(); it != heterogen_atoms_.end(); it++)
    {
        out << "Atom Serial Number: ";
        if((it)->first != iNotSet)
            out << (it)->first << endl;
        else
            out << " " << endl;
        (it)->second->Print();
        out << endl;
    }
}
void PdbHeterogenAtomCard::SetHeterogenAtoms (PdbHeterogenAtomMap heterogen_atoms)
Definition at line 59 of file pdbheterogenatomcard.cc.
Referenced by PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), MolecularModeling::Assembly::ExtractPdbModelCardFromAssembly(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    heterogen_atoms_.clear();
    for(PdbHeterogenAtomMap::iterator it = heterogen_atoms.begin(); it != heterogen_atoms.end(); it++)
    {
        PdbHeterogenAtom* heterogen_atom = (*it).second;
        int serial_number = (*it).first;
        heterogen_atoms_[serial_number] = heterogen_atom;
    }
}
void PdbHeterogenAtomCard::SetRecordName (const std::string record_name)
Definition at line 54 of file pdbheterogenatomcard.cc.
Referenced by PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), and PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber().
{
    record_name_ = record_name;
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbheterogenatomcard.hpp
src/FileSet/PdbFileSpace/pdbheterogenatomcard.cc