gmmlNew: PdbPreprocessorSpace::PdbPreprocessorMissingResidue Class Reference
PdbPreprocessorSpace::PdbPreprocessorMissingResidue Class Reference
#include <pdbpreprocessormissingresidue.hpp>
Public Member Functions
PdbPreprocessorMissingResidue ()
PdbPreprocessorMissingResidue (char chain_id, int start_index, int end_index, int index_before_gap, int index_after_gap, char starting_residue_insertion_code, char ending_residue_insertion_code)
char GetResidueChainId ()
int GetStartingResidueSequenceNumber ()
int GetEndingResidueSequenceNumber ()
int GetResidueBeforeGap ()
int GetResidueAfterGap ()
gmml::PossibleNChainTermination GetSelectedNTermination ()
gmml::PossibleCChainTermination GetSelectedCTermination ()
char GetStartingResidueInsertionCode ()
char GetEndingResidueInsertionCode ()
std::string GetStringFormatOfSelectedNTermination ()
std::string GetStringFormatOfSelectedCTermination ()
std::string GetStringFormatOfNTermination (gmml::PossibleNChainTermination n_termination)
std::string GetStringFormatOfCTermination (gmml::PossibleCChainTermination c_termination)
std::vector< std::string > GetAllPossibleNChainTerminationAsString ()
std::vector< std::string > GetAllPossibleCChainTerminationAsString ()
void SetResidueChainId (char residue_chain_id)
void SetStartingResidueSequenceNumber (int starting_residue_sequence_number)
void SetEndingResidueSequenceNumber (int ending_residue_sequence_number)
void SetResidueBeforeGap (int residue_before_gap)
void SetResidueAfterGap (int residue_after_gap)
void SetSelectedNTermination (gmml::PossibleNChainTermination selected_n_termination)
void SetSelectedCTermination (gmml::PossibleCChainTermination selected_c_termination)
void SetStartingResidueInsertionCode (char starting_residue_insertion_code)
void SetEndingResidueInsertionCode (char ending_residue_insertion_code)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 12 of file pdbpreprocessormissingresidue.hpp.
Constructor & Destructor Documentation
PdbPreprocessorMissingResidue::PdbPreprocessorMissingResidue ()
Definition at line 11 of file pdbpreprocessormissingresidue.cc.
{}
PdbPreprocessorMissingResidue::PdbPreprocessorMissingResidue (char chain_id, int start_index, int end_index, int index_before_gap, int index_after_gap, char starting_residue_insertion_code, char ending_residue_insertion_code)
Definition at line 13 of file pdbpreprocessormissingresidue.cc.
                                                                                                                                                                                                                               :
    residue_chain_id_(chain_id), starting_residue_sequence_number_(start_index), ending_residue_sequence_number_(end_index),
    residue_before_gap_(index_before_gap), residue_after_gap_(index_after_gap),
    starting_residue_insertion_code_(starting_residue_insertion_code), ending_residue_insertion_code_(ending_residue_insertion_code)
{
    selected_n_termination_ = (PossibleNChainTermination)1;
    selected_c_termination_ = (PossibleCChainTermination) 2;
}
Member Function Documentation
vector< string > PdbPreprocessorMissingResidue::GetAllPossibleCChainTerminationAsString ()
Definition at line 126 of file pdbpreprocessormissingresidue.cc.
References gmml::CO2, GetStringFormatOfCTermination(), and gmml::NH2.
{
    vector<string> all_possible_c_chian_termination_as_string;
    for(int possible_c_chian_termination = NH2; possible_c_chian_termination != CO2; possible_c_chian_termination++)
        all_possible_c_chian_termination_as_string.push_back(GetStringFormatOfCTermination((PossibleCChainTermination)possible_c_chian_termination));
    return all_possible_c_chian_termination_as_string;
}
vector< string > PdbPreprocessorMissingResidue::GetAllPossibleNChainTerminationAsString ()
Definition at line 118 of file pdbpreprocessormissingresidue.cc.
References gmml::COCH3, GetStringFormatOfNTermination(), and gmml::NH3.
{
    vector<string> all_possible_n_chian_termination_as_string;
    for(int possible_n_chian_termination = COCH3; possible_n_chian_termination != NH3; possible_n_chian_termination++)
        all_possible_n_chian_termination_as_string.push_back(GetStringFormatOfNTermination((PossibleNChainTermination)possible_n_chian_termination));
    return all_possible_n_chian_termination_as_string;
}
char PdbPreprocessorMissingResidue::GetEndingResidueInsertionCode ()
Definition at line 57 of file pdbpreprocessormissingresidue.cc.
{
    return ending_residue_insertion_code_;
}
int PdbPreprocessorMissingResidue::GetEndingResidueSequenceNumber ()
Definition at line 33 of file pdbpreprocessormissingresidue.cc.
{
    return ending_residue_sequence_number_;
}
int PdbPreprocessorMissingResidue::GetResidueAfterGap ()
Definition at line 41 of file pdbpreprocessormissingresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    return residue_after_gap_;
}
int PdbPreprocessorMissingResidue::GetResidueBeforeGap ()
Definition at line 37 of file pdbpreprocessormissingresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    return residue_before_gap_;
}
char PdbPreprocessorMissingResidue::GetResidueChainId ()
Definition at line 25 of file pdbpreprocessormissingresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    return residue_chain_id_;
}
PossibleCChainTermination PdbPreprocessorMissingResidue::GetSelectedCTermination ()
Definition at line 49 of file pdbpreprocessormissingresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    return selected_c_termination_;
}
PossibleNChainTermination PdbPreprocessorMissingResidue::GetSelectedNTermination ()
Definition at line 45 of file pdbpreprocessormissingresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    return selected_n_termination_;
}
char PdbPreprocessorMissingResidue::GetStartingResidueInsertionCode ()
Definition at line 53 of file pdbpreprocessormissingresidue.cc.
{
    return starting_residue_insertion_code_;
}
int PdbPreprocessorMissingResidue::GetStartingResidueSequenceNumber ()
Definition at line 29 of file pdbpreprocessormissingresidue.cc.
{
    return starting_residue_sequence_number_;
}
string PdbPreprocessorMissingResidue::GetStringFormatOfCTermination (gmml::PossibleCChainTermination c_termination)
Definition at line 103 of file pdbpreprocessormissingresidue.cc.
Referenced by GetAllPossibleCChainTerminationAsString(), PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    switch(c_termination)
    {
        case 1:
            return "NHE";
        case 2:
            return "NME";
        case 3:
            return "CO2-";
        default:
            return "";
    }
}
string PdbPreprocessorMissingResidue::GetStringFormatOfNTermination (gmml::PossibleNChainTermination n_termination)
Definition at line 90 of file pdbpreprocessormissingresidue.cc.
Referenced by GetAllPossibleNChainTerminationAsString(), PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    switch (n_termination)
    {
        case 1:
            return "ACE";
        case 2:
            return "NH3+";
        default:
            return "";
    }
}
string PdbPreprocessorMissingResidue::GetStringFormatOfSelectedCTermination ()
Definition at line 75 of file pdbpreprocessormissingresidue.cc.
Referenced by Print(), PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    switch(selected_c_termination_)
    {
        case 1:
            return "NHE";
        case 2:
            return "NME";
        case 3:
            return "CO2-";
        default:
            return "";
    }
}
string PdbPreprocessorMissingResidue::GetStringFormatOfSelectedNTermination ()
Definition at line 62 of file pdbpreprocessormissingresidue.cc.
Referenced by Print(), PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    switch (selected_n_termination_)
    {
        case 1:
            return "ACE";
        case 2:
            return "NH3+";
        default:
            return "";
    }
}
void PdbPreprocessorMissingResidue::Print (std::ostream & out = std::cout)
Definition at line 177 of file pdbpreprocessormissingresidue.cc.
References GetStringFormatOfSelectedCTermination(), and GetStringFormatOfSelectedNTermination().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::Print().
{
    out << "Chain: " << starting_residue_sequence_number_ << "-" << ending_residue_sequence_number_ << "(" << residue_chain_id_ << ")"
           << ", Residue insertion code before gap: " << starting_residue_insertion_code_
              << ", Residue insertion code after gap: " << ending_residue_insertion_code_
        << ", Residue before gap: " << residue_before_gap_
        << ", Selected c termination: " << GetStringFormatOfSelectedCTermination()
        << ", Residue after gap: " << residue_after_gap_
        << ", Selected n termination: " << GetStringFormatOfSelectedNTermination()
        << endl;
}
void PdbPreprocessorMissingResidue::SetEndingResidueInsertionCode (char ending_residue_insertion_code)
Definition at line 169 of file pdbpreprocessormissingresidue.cc.
{
    ending_residue_insertion_code_ = ending_residue_insertion_code;
}
void PdbPreprocessorMissingResidue::SetEndingResidueSequenceNumber (int ending_residue_sequence_number)
Definition at line 145 of file pdbpreprocessormissingresidue.cc.
{
    ending_residue_sequence_number_ = ending_residue_sequence_number;
}
void PdbPreprocessorMissingResidue::SetResidueAfterGap (int residue_after_gap)
Definition at line 153 of file pdbpreprocessormissingresidue.cc.
{
    residue_after_gap_ = residue_after_gap;
}
void PdbPreprocessorMissingResidue::SetResidueBeforeGap (int residue_before_gap)
Definition at line 149 of file pdbpreprocessormissingresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    residue_before_gap_ = residue_before_gap;
}
void PdbPreprocessorMissingResidue::SetResidueChainId (char residue_chain_id)
Definition at line 137 of file pdbpreprocessormissingresidue.cc.
{
    residue_chain_id_ = residue_chain_id;
}
void PdbPreprocessorMissingResidue::SetSelectedCTermination (gmml::PossibleCChainTermination selected_c_termination)
Definition at line 161 of file pdbpreprocessormissingresidue.cc.
{
    selected_c_termination_ = selected_c_termination;
}
void PdbPreprocessorMissingResidue::SetSelectedNTermination (gmml::PossibleNChainTermination selected_n_termination)
Definition at line 157 of file pdbpreprocessormissingresidue.cc.
{
    selected_n_termination_ = selected_n_termination;
}
void PdbPreprocessorMissingResidue::SetStartingResidueInsertionCode (char starting_residue_insertion_code)
Definition at line 165 of file pdbpreprocessormissingresidue.cc.
{
    starting_residue_insertion_code_ = starting_residue_insertion_code;
}
void PdbPreprocessorMissingResidue::SetStartingResidueSequenceNumber (int starting_residue_sequence_number)
Definition at line 141 of file pdbpreprocessormissingresidue.cc.
{
    starting_residue_sequence_number_ = starting_residue_sequence_number;
}
The documentation for this class was generated from the following files:
includes/Resolver/PdbPreprocessor/pdbpreprocessormissingresidue.hpp
src/Resolver/PdbPreprocessor/pdbpreprocessormissingresidue.cc