gmmlNew: TopologyFileSpace::TopologyDihedralType Class Reference
TopologyFileSpace::TopologyDihedralType Class Reference
#include <topologydihedraltype.hpp>
Public Member Functions
TopologyDihedralType ()
TopologyDihedralType (int index, double force_constant, double periodicity, double phase, double scee, double scnb)
int GetIndex ()
double GetPeriodicity ()
double GetPhase ()
double GetScee ()
double GetScnb ()
double GetForceConstant ()
void SetIndex (int index)
void SetPeriodicity (double periodicity)
void SetPhase (double phase)
void SetScee (double scee)
void SetScnb (double scnb)
void SetForceConstant (double force_constant)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 10 of file topologydihedraltype.hpp.
Constructor & Destructor Documentation
TopologyDihedralType::TopologyDihedralType ()
Definition at line 10 of file topologydihedraltype.cc.
{}
TopologyDihedralType::TopologyDihedralType (int index, double force_constant, double periodicity, double phase, double scee, double scnb)
Definition at line 12 of file topologydihedraltype.cc.
                                                                                                                                       :
    index_(index), force_constant_(force_constant), periodicity_(periodicity), phase_(phase), scee_(scee), scnb_(scnb) {}
Member Function Documentation
double TopologyDihedralType::GetForceConstant ()
Definition at line 38 of file topologydihedraltype.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveDihedralForceConstantSection().
{
    return force_constant_;
}
int TopologyDihedralType::GetIndex ()
Definition at line 18 of file topologydihedraltype.cc.
Referenced by TopologyFileSpace::TopologyFile::AddDihedralType(), TopologyFileSpace::TopologyFile::GetDihedralTypeByIndex(), TopologyFileSpace::TopologyFile::ResolveDihedralsIncHydrogenSection(), and TopologyFileSpace::TopologyFile::ResolveDihedralsWithoutHydrogenSection().
{
    return index_;
}
double TopologyDihedralType::GetPeriodicity ()
Definition at line 22 of file topologydihedraltype.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveDihedralPeriodicitySection().
{
    return periodicity_;
}
double TopologyDihedralType::GetPhase ()
Definition at line 26 of file topologydihedraltype.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveDihedralPhaseSection().
{
    return phase_;
}
double TopologyDihedralType::GetScee ()
Definition at line 30 of file topologydihedraltype.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveSceeScaleFactorSection().
{
    return scee_;
}
double TopologyDihedralType::GetScnb ()
Definition at line 34 of file topologydihedraltype.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveScnbScaleFactorSection().
{
    return scnb_;
}
void TopologyDihedralType::Print (std::ostream & out = std::cout)
Definition at line 79 of file topologydihedraltype.cc.
Referenced by TopologyFileSpace::TopologyDihedral::Print(), and TopologyFileSpace::TopologyFile::Print().
{
    out << "Dihedral index: " << index_
         << ", Periodicity: " << periodicity_
         << ", Phase: " << phase_
         << ", SCEE: " << scee_
         << ", SCNB: " << scnb_
         << ", Force constant: " << force_constant_;
}
void TopologyDihedralType::SetForceConstant (double force_constant)
Definition at line 67 of file topologydihedraltype.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralTypesFromAssembly().
{
    force_constant_ = force_constant;
}
void TopologyDihedralType::SetIndex (int index)
Definition at line 47 of file topologydihedraltype.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralTypesFromAssembly().
{
    index_ = index;
}
void TopologyDihedralType::SetPeriodicity (double periodicity)
Definition at line 51 of file topologydihedraltype.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralTypesFromAssembly().
{
    periodicity_ = periodicity;
}
void TopologyDihedralType::SetPhase (double phase)
Definition at line 55 of file topologydihedraltype.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralTypesFromAssembly().
{
    phase_ = phase;
}
void TopologyDihedralType::SetScee (double scee)
Definition at line 59 of file topologydihedraltype.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralTypesFromAssembly().
{
    scee_ = scee;
}
void TopologyDihedralType::SetScnb (double scnb)
Definition at line 63 of file topologydihedraltype.cc.
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralTypesFromAssembly().
{
    scnb_ = scnb;
}
The documentation for this class was generated from the following files:
includes/FileSet/TopologyFileSpace/topologydihedraltype.hpp
src/FileSet/TopologyFileSpace/topologydihedraltype.cc