gmmlNew: TopologyFileSpace::TopologyResidue Class Reference
TopologyFileSpace::TopologyResidue Class Reference
#include <topologyresidue.hpp>
Public Types
typedef std::map< std::string,
TopologyAtom * > TopologyAtomMap
Public Member Functions
TopologyResidue ()
TopologyResidue (std::string residue_name, TopologyAtomMap atoms, int index, int starting_atom_index)
std::string GetResidueName ()
TopologyAtomMap GetAtoms ()
TopologyAtom * GetAtomByIndex (int index)
int GetIndex ()
int GetStartingAtomIndex ()
void SetResidueName (std::string residue_name)
void AddAtom (TopologyAtom *atom)
void SetIndex (int index)
void SetStartingAtomIndex (int starting_atom_index)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 13 of file topologyresidue.hpp.
Member Typedef Documentation
typedef std::map<std::string, TopologyAtom*> TopologyFileSpace::TopologyResidue::TopologyAtomMap
Definition at line 19 of file topologyresidue.hpp.
Constructor & Destructor Documentation
TopologyResidue::TopologyResidue ()
Definition at line 13 of file topologyresidue.cc.
References gmml::iNotSet.
{
    residue_name_ = "";
    atoms_ = TopologyAtomMap();
    index_ = iNotSet;
    starting_atom_index_ = iNotSet;
}
TopologyFileSpace::TopologyResidue::TopologyResidue (std::string residue_name, TopologyAtomMap atoms, int index, int starting_atom_index)
Member Function Documentation
void TopologyResidue::AddAtom (TopologyAtom * atom)
Definition at line 70 of file topologyresidue.cc.
References TopologyFileSpace::TopologyAtom::GetAtomName().
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    atoms_[atom->GetAtomName()] = atom;
}
TopologyAtom * TopologyResidue::GetAtomByIndex (int index)
Definition at line 44 of file topologyresidue.cc.
References TopologyFileSpace::TopologyAtom::GetIndex().
Referenced by TopologyFileSpace::TopologyFile::GetAtomTypeIndexMap(), TopologyFileSpace::TopologyFile::ResolveAmberAtomTypeSection(), TopologyFileSpace::TopologyFile::ResolveAtomicNumberSection(), TopologyFileSpace::TopologyFile::ResolveAtomNameSection(), TopologyFileSpace::TopologyFile::ResolveAtomTypeIndexSection(), TopologyFileSpace::TopologyFile::ResolveChargeSection(), TopologyFileSpace::TopologyFile::ResolveExcludedAtomsListSection(), TopologyFileSpace::TopologyFile::ResolveMassSection(), TopologyFileSpace::TopologyFile::ResolveNonbondedParmIndexSection(), TopologyFileSpace::TopologyFile::ResolveNumberExcludedAtomsSection(), TopologyFileSpace::TopologyFile::ResolveRadiiSection(), TopologyFileSpace::TopologyFile::ResolveScreenSection(), and TopologyFileSpace::TopologyFile::ResolveTreeChainClassificationSection().
{
    for(TopologyAtomMap::iterator it = atoms_.begin(); it != atoms_.end(); it++)
    {
        TopologyAtom* atom = (*it).second;
        if(atom->GetIndex() == index)
            return atom;
    }
    return NULL;
}
TopologyResidue::TopologyAtomMap TopologyResidue::GetAtoms ()
Definition at line 40 of file topologyresidue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromTopologyCoordinateFile(), MolecularModeling::Assembly::BuildAssemblyFromTopologyFile(), TopologyFileSpace::TopologyAssembly::GetAtomIndexByName(), TopologyFileSpace::TopologyFile::GetAtomTypeIndexMap(), TopologyFileSpace::TopologyFile::ResolveAmberAtomTypeSection(), TopologyFileSpace::TopologyFile::ResolveAtomicNumberSection(), TopologyFileSpace::TopologyFile::ResolveAtomNameSection(), TopologyFileSpace::TopologyFile::ResolveAtomTypeIndexSection(), TopologyFileSpace::TopologyFile::ResolveChargeSection(), TopologyFileSpace::TopologyFile::ResolveExcludedAtomsListSection(), TopologyFileSpace::TopologyFile::ResolveMassSection(), TopologyFileSpace::TopologyFile::ResolveNonbondedParmIndexSection(), TopologyFileSpace::TopologyFile::ResolveNumberExcludedAtomsSection(), TopologyFileSpace::TopologyFile::ResolveRadiiSection(), TopologyFileSpace::TopologyFile::ResolveScreenSection(), and TopologyFileSpace::TopologyFile::ResolveTreeChainClassificationSection().
{
    return atoms_;
}
int TopologyResidue::GetIndex ()
Definition at line 54 of file topologyresidue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromTopologyCoordinateFile(), MolecularModeling::Assembly::BuildAssemblyFromTopologyFile(), and TopologyFileSpace::TopologyAssembly::GetResidueByIndex().
{
    return index_;
}
string TopologyResidue::GetResidueName ()
Definition at line 36 of file topologyresidue.cc.
Referenced by TopologyFileSpace::TopologyAssembly::AddResidue(), TopologyFileSpace::TopologyFile::ResolveResidueLabelSection(), and TopologyFileSpace::TopologyAssembly::SetResidues().
{
    return residue_name_;
}
int TopologyResidue::GetStartingAtomIndex ()
Definition at line 58 of file topologyresidue.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveResiduePointersSection().
{
    return starting_atom_index_;
}
void TopologyResidue::Print (std::ostream & out = std::cout)
Definition at line 90 of file topologyresidue.cc.
References TopologyFileSpace::TopologyAtom::Print().
Referenced by TopologyFileSpace::TopologyAssembly::Print().
{
    out << "Residue Name: " << residue_name_ << ", Residue Index: " << index_ << ", Starting Atom Index: " << starting_atom_index_ << endl << endl;
//    out << "------------------------------------- " << residue_name_ << " --------------------------------------" << endl;
    for(TopologyAtomMap::iterator it = atoms_.begin(); it != atoms_.end(); it++)
    {
//        string atom_name = (*it).first;
        TopologyAtom* atom = (*it).second;
        atom->Print(out);
    }
}
void TopologyResidue::SetIndex (int index)
Definition at line 74 of file topologyresidue.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    index_ = index;
}
void TopologyResidue::SetResidueName (std::string residue_name)
Definition at line 66 of file topologyresidue.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    residue_name_ = residue_name;
}
void TopologyResidue::SetStartingAtomIndex (int starting_atom_index)
Definition at line 78 of file topologyresidue.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    starting_atom_index_ = starting_atom_index;
}
The documentation for this class was generated from the following files:
includes/FileSet/TopologyFileSpace/topologyresidue.hpp
src/FileSet/TopologyFileSpace/topologyresidue.cc