gmmlNew: MolecularModeling::MolecularDynamicAtom Class Reference
MolecularModeling::MolecularDynamicAtom Class Reference
#include <moleculardynamicatom.hpp>
Public Member Functions
MolecularDynamicAtom ()
std::string GetAtomType ()
double GetCharge ()
double GetMass ()
double GetRadius ()
void SetAtomType (std::string atom_type)
void SetCharge (double charge)
void SetMass (double mass)
void SetRadius (double radius)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 9 of file moleculardynamicatom.hpp.
Constructor & Destructor Documentation
MolecularDynamicAtom::MolecularDynamicAtom ()
Definition at line 9 of file moleculardynamicatom.cc.
: atom_type_(""), charge_(0.0), mass_(0.0), radius_(0.0) {}
Member Function Documentation
string MolecularDynamicAtom::GetAtomType ()
Definition at line 14 of file moleculardynamicatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly(), MolecularModeling::Assembly::BuildPrepFileStructureFromAssembly(), MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly(), MolecularModeling::Assembly::CountNumberOfAngleTypes(), MolecularModeling::Assembly::CountNumberOfAtomTypes(), MolecularModeling::Assembly::CountNumberOfBondTypes(), MolecularModeling::Assembly::CountNumberOfDihedrals(), MolecularModeling::Assembly::CountNumberOfDihedralsExcludingHydrogen(), MolecularModeling::Assembly::CountNumberOfDihedralsIncludingHydrogen(), MolecularModeling::Assembly::CountNumberOfDihedralTypes(), MolecularModeling::Assembly::ExtractTopologyAnglesFromAssembly(), MolecularModeling::Assembly::ExtractTopologyAngleTypesFromAssembly(), MolecularModeling::Assembly::ExtractTopologyBondsFromAssembly(), MolecularModeling::Assembly::ExtractTopologyBondTypesFromAssembly(), MolecularModeling::Assembly::ExtractTopologyDihedralsFromAssembly(), and MolecularModeling::Assembly::ExtractTopologyDihedralTypesFromAssembly().
{
    return atom_type_;
}
double MolecularDynamicAtom::GetCharge ()
Definition at line 18 of file moleculardynamicatom.cc.
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly(), MolecularModeling::Assembly::BuildPrepFileStructureFromAssembly(), MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly(), and MolecularModeling::Assembly::ExtractPdbModelCardFromAssembly().
{
    return charge_;
}
double MolecularDynamicAtom::GetMass ()
Definition at line 22 of file moleculardynamicatom.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    return mass_;
}
double MolecularDynamicAtom::GetRadius ()
Definition at line 26 of file moleculardynamicatom.cc.
{
    return radius_;
}
void MolecularDynamicAtom::Print (std::ostream & out = std::cout)
Reimplemented in MolecularModeling::Atom.
Definition at line 54 of file moleculardynamicatom.cc.
{
}
void MolecularDynamicAtom::SetAtomType (std::string atom_type)
Definition at line 34 of file moleculardynamicatom.cc.
{
    atom_type_ = atom_type;
}
void MolecularDynamicAtom::SetCharge (double charge)
Definition at line 38 of file moleculardynamicatom.cc.
{
    charge_ = charge;
}
void MolecularDynamicAtom::SetMass (double mass)
Definition at line 42 of file moleculardynamicatom.cc.
{
    mass_ = mass;
}
void MolecularDynamicAtom::SetRadius (double radius)
Definition at line 46 of file moleculardynamicatom.cc.
{
    radius_ = radius;
}
The documentation for this class was generated from the following files:
includes/MolecularModeling/moleculardynamicatom.hpp
src/MolecularModeling/moleculardynamicatom.cc