gmmlNew: MolecularModeling::Assembly Class Reference
MolecularModeling::Assembly Class Reference
#include <assembly.hpp>
Public Types
typedef std::vector< Assembly * > AssemblyVector
typedef std::vector< Residue * > ResidueVector
typedef std::vector< Atom * > AtomVector
typedef std::vector
< Geometry::Coordinate * > CoordinateVector
Public Member Functions
Assembly ()
Assembly (std::vector< std::string > file_paths, gmml::InputFileType type)
Assembly (std::vector< std::vector< std::string > > file_paths, std::vector< gmml::InputFileType > types)
std::string GetName ()
AssemblyVector GetAssemblies ()
ResidueVector GetResidues ()
std::string GetChemicalType ()
int GetSequenceNumber ()
double GetTotalMass ()
Geometry::Coordinate GetCenterOfMass ()
Geometry::Coordinate GetCenterOfGeometry ()
std::string GetDescription ()
std::string GetSourceFile ()
gmml::InputFileType GetSourceFileType ()
int GetModelIndex ()
AtomVector GetAllAtomsOfAssembly ()
ResidueVector GetAllResiduesOfAssembly ()
CoordinateVector GetAllCoordinates ()
void SetName (std::string name)
void SetAssemblies (AssemblyVector assemblies)
void AddAssembly (Assembly *assembly)
void SetResidues (ResidueVector residues)
void AddResidue (Residue *residue)
void SetChemicalType (std::string chemical_type)
void SetSequenceNumber (int sequence_number)
void SetTtoalMass (double total_mass)
void SetCenterOfMass (Geometry::Coordinate center_of_mass)
void SetCenterOfGeometry (Geometry::Coordinate center_of_geometry)
void SetDescription (std::string description)
void SetSourceFile (std::string source_file)
void SetSourceFileType (gmml::InputFileType source_file_type)
void SetModelIndex (int model_index)
void BuildAssemblyFromPdbFile (std::string pdb_file_path)
void BuildAssemblyFromTopologyFile (std::string topology_file_path)
void BuildAssemblyFromLibraryFile (std::string library_file_path)
void BuildAssemblyFromTopologyCoordinateFile (std::string topology_file_path, std::string coordinate_file_path)
void BuildAssemblyFromPrepFile (std::string prep_file_path)
PdbFileSpace::PdbFile * BuildPdbFileStructureFromAssembly ()
void ExtractPdbModelCardFromAssembly (PdbFileSpace::PdbModelResidueSet *residue_set, int &serial_number, int &sequence_number, int model_number)
void ExtractTopologyBondTypesFromAssembly (std::vector< std::vector< std::string > > &inserted_bond_types, Atom *assembly_atom, Atom *neighbor, ParameterFileSpace::ParameterFile::BondMap &bonds, int &bond_type_counter, TopologyFileSpace::TopologyFile *topology_file)
void ExtractTopologyBondsFromAssembly (std::vector< std::vector< std::string > > &inserted_bonds, std::vector< std::vector< std::string > > &inserted_bond_tyoes, Atom *assembly_atom, Atom *neighbor, TopologyFileSpace::TopologyFile *topology_file)
PrepFileSpace::PrepFile * BuildPrepFileStructureFromAssembly ()
TopologyFileSpace::TopologyFile * BuildTopologyFileStructureFromAssembly (std::string parameter_file_path)
void ExtractTopologyAngleTypesFromAssembly (Atom *assembly_atom, Atom *neighbor, Atom *neighbor_of_neighbor, std::vector< std::vector< std::string > > &inserted_angle_types, int &angle_type_counter, TopologyFileSpace::TopologyFile *topology_file, ParameterFileSpace::ParameterFile::AngleMap &angles)
void ExtractTopologyAnglesFromAssembly (Atom *assembly_atom, Atom *neighbor, Atom *neighbor_of_neighbor, std::vector< std::vector< std::string > > &inserted_angles, std::vector< std::vector< std::string > > &inserted_angle_types, TopologyFileSpace::TopologyFile *topology_file)
void ExtractTopologyDihedralTypesFromAssembly (Atom *assembly_atom, Atom *neighbor, Atom *neighbor_of_neighbor, Atom *neighbor_of_neighbor_neighbor, std::vector< std::string > &inserted_dihedral_types, int &dihedral_type_counter, TopologyFileSpace::TopologyFile *topology_file, ParameterFileSpace::ParameterFile::DihedralMap &dihedrals)
void ExtractTopologyDihedralsFromAssembly (Atom *assembly_atom, Atom *neighbor, Atom *neighbor_of_neighbor, Atom *neighbor_of_neighbor_neighbor, std::vector< std::vector< std::string > > &inserted_dihedrals, std::vector< std::string > &inserted_dihedral_types, ParameterFileSpace::ParameterFile::DihedralMap &dihedrals, TopologyFileSpace::TopologyFile *topology_file)
CoordinateFileSpace::CoordinateFile * BuildCoordinateFileStructureFromAssembly ()
LibraryFileSpace::LibraryFile * BuildLibraryFileStructureFromAssembly ()
void BuildStructure (gmml::BuildingStructureOption building_option, std::vector< std::string > options, std::vector< std::string > file_paths)
void BuildStructureByDistance (double cutoff=gmml::dCutOff, int model_index=0)
void BuildStructureByOriginalFileBondingInformation ()
void BuildStructureByPDBFileInformation ()
void BuildStructureByTOPFileInformation ()
void BuildStructureByLIBFileInformation ()
void BuildStructureByPrepFileInformation ()
void BuildStructureByDatabaseFilesBondingInformation (std::vector< gmml::InputFileType > types, std::vector< std::string > file_paths)
void CalculateCenterOfGeometry ()
int CountNumberOfAtoms ()
int CountNumberOfAtomTypes ()
int CountNumberOfResidues ()
int CountNumberOfBondsIncludingHydrogen ()
int CountNumberOfBondsExcludingHydrogen ()
int CountNumberOfBonds ()
int CountNumberOfBondTypes ()
int CountNumberOfAnglesIncludingHydrogen ()
int CountNumberOfAnglesExcludingHydrogen ()
int CountNumberOfAngles ()
int CountNumberOfAngleTypes ()
int CountNumberOfDihedralsIncludingHydrogen (std::string parameter_file_path)
int CountNumberOfDihedralsExcludingHydrogen (std::string parameter_file_path)
int CountNumberOfDihedrals (std::string parameter_file_path)
std::vector< std::vector
< std::string > > CreateAllAtomTypePermutationsforDihedralType (std::string atom_type1, std::string atom_type2, std::string atom_type3, std::string atom_type4)
std::vector< std::vector
< std::string > > CreateAllAtomTypePermutationsforImproperDihedralType (std::string atom_type1, std::string atom_type2, std::string atom_type3, std::string atom_type4)
int CountNumberOfDihedralTypes (std::string parameter_file_path)
AtomVector GetAllAtomsOfAssemblyWithAtLeastThreeNeighbors ()
int CountNumberOfExcludedAtoms ()
int CountMaxNumberOfAtomsInLargestResidue ()
void ClearAssembly ()
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 24 of file assembly.hpp.
Member Typedef Documentation
typedef std::vector<Assembly*> MolecularModeling::Assembly::AssemblyVector
Definition at line 30 of file assembly.hpp.
typedef std::vector<Atom*> MolecularModeling::Assembly::AtomVector
Definition at line 32 of file assembly.hpp.
typedef std::vector<Geometry::Coordinate*> MolecularModeling::Assembly::CoordinateVector
Definition at line 33 of file assembly.hpp.
typedef std::vector<Residue*> MolecularModeling::Assembly::ResidueVector
Definition at line 31 of file assembly.hpp.
Constructor & Destructor Documentation
Assembly::Assembly ()
Definition at line 61 of file assembly.cc.
: description_(""), center_of_geometry_(0,0,0), model_index_(0) {}
MolecularModeling::Assembly::Assembly (std::vector< std::string > file_paths, gmml::InputFileType type)
MolecularModeling::Assembly::Assembly (std::vector< std::vector< std::string > > file_paths, std::vector< gmml::InputFileType > types)
Member Function Documentation
void Assembly::AddAssembly (Assembly * assembly)
Definition at line 280 of file assembly.cc.
References GetName(), GetSourceFile(), gmml::MULTIPLE, and SetSequenceNumber().
{
    if(assemblies_.size() == 0)
    {
        assemblies_.push_back(this);
        assembly->SetSequenceNumber(assemblies_.size() + 1);
        assemblies_.push_back(assembly);
        stringstream ss;
        ss << this->name_ << "-" << assembly->GetName();
        this->name_ = ss.str();
        this->residues_ = ResidueVector();
        this->chemical_type_ = "";
        this->sequence_number_ = 1;
        this->total_mass_ = 0;
        this->center_of_geometry_ = Coordinate();
        this->center_of_mass_ = Coordinate();
        stringstream sss;
        sss << this->source_file_ << "#" << assembly->GetSourceFile();
        this->source_file_ = sss.str();
        source_file_type_ = gmml::MULTIPLE;
        model_index_ = 0;
    }
    else
    {
        stringstream ss;
        ss << this->name_ << "-" << assembly->GetName();
        assembly->SetSequenceNumber(assemblies_.size() + 1);
        assemblies_.push_back(assembly);
    }
}
void Assembly::AddResidue (Residue * residue)
Definition at line 318 of file assembly.cc.
Referenced by BuildAssemblyFromPdbFile(), and BuildAssemblyFromTopologyFile().
{
    residues_.push_back(residue);
}
void Assembly::BuildAssemblyFromLibraryFile (std::string library_file_path)
Definition at line 521 of file assembly.cc.
References MolecularModeling::Residue::AddAtom(), MolecularModeling::Atom::AddCoordinate(), MolecularModeling::Residue::AddHeadAtom(), MolecularModeling::Residue::AddTailAtom(), ClearAssembly(), LibraryFileSpace::LibraryFileAtom::GetAtomIndex(), LibraryFileSpace::LibraryFileResidue::GetAtoms(), LibraryFileSpace::LibraryFileAtom::GetCharge(), LibraryFileSpace::LibraryFileAtom::GetCoordinate(), LibraryFileSpace::LibraryFileResidue::GetHeadAtomIndex(), LibraryFileSpace::LibraryFileResidue::GetName(), LibraryFileSpace::LibraryFileAtom::GetName(), LibraryFileSpace::LibraryFile::GetResidues(), LibraryFileSpace::LibraryFileResidue::GetTailAtomIndex(), LibraryFileSpace::LibraryFileAtom::GetType(), MolecularModeling::Residue::SetAssembly(), MolecularModeling::Atom::SetId(), MolecularModeling::Residue::SetId(), MolecularModeling::Residue::SetName(), MolecularModeling::Atom::SetName(), and MolecularModeling::Atom::SetResidue().
{
    this->ClearAssembly();
    LibraryFile* library_file = new LibraryFile(library_file_path);
    sequence_number_ = 1;
    LibraryFile::ResidueMap library_residues = library_file->GetResidues();
    stringstream ss;
    for(LibraryFile::ResidueMap::iterator it = library_residues.begin(); it != library_residues.end(); it++)
    {
        Residue* assembly_residue = new Residue();
        assembly_residue->SetAssembly(this);
        string residue_name = (*it).first;
        assembly_residue->SetName(residue_name);
        assembly_residue->SetId(residue_name);
        LibraryFileResidue* library_residue = (*it).second;
        int lib_res_tail_atom_index = library_residue->GetTailAtomIndex();
        int lib_res_head_atom_index = library_residue->GetHeadAtomIndex();
        string library_residue_name = library_residue->GetName();
        if(distance(library_residues.begin(), it) == (int)library_residues.size()-1)
            ss << library_residue_name;
        else
            ss << library_residue_name << "-";
        LibraryFileResidue::AtomMap library_atoms = library_residue->GetAtoms();
        for(LibraryFileResidue::AtomMap::iterator it1 = library_atoms.begin(); it1 != library_atoms.end(); it1++)
        {
            Atom* assembly_atom = new Atom();
            LibraryFileAtom* library_atom = (*it1).second;
            string atom_name = library_atom->GetName();
            assembly_atom->SetName(atom_name);
            stringstream atom_id;
            atom_id << residue_name << ":" << atom_name;
            assembly_atom->SetId(atom_id.str());
            assembly_atom->SetResidue(assembly_residue);
            assembly_atom->SetName(library_atom->GetName());
            assembly_atom->MolecularDynamicAtom::SetCharge(library_atom->GetCharge());
            assembly_atom->MolecularDynamicAtom::SetAtomType(library_atom->GetType());
            Coordinate* coordinate = new Coordinate(library_atom->GetCoordinate());
            assembly_atom->AddCoordinate(coordinate);
            assembly_residue->AddAtom(assembly_atom);
            if(library_atom->GetAtomIndex() == lib_res_head_atom_index)
                assembly_residue->AddHeadAtom(assembly_atom);
            if(library_atom->GetAtomIndex() == lib_res_tail_atom_index)
                assembly_residue->AddTailAtom(assembly_atom);
        }
        residues_.push_back(assembly_residue);
    }
    name_ = ss.str();
}
void Assembly::BuildAssemblyFromPdbFile (std::string pdb_file_path)
Definition at line 362 of file assembly.cc.
References MolecularModeling::Residue::AddAtom(), MolecularModeling::Atom::AddCoordinate(), AddResidue(), ClearAssembly(), PdbFileSpace::PdbFile::GetAllAtomsInOrder(), PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomCardIndexInResidueSet(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomCharge(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomName(), PdbFileSpace::PdbAtom::GetAtomOrthogonalCoordinate(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbModelCard::GetModels(), PdbFileSpace::PdbFile::GetModels(), MolecularModeling::Residue::SetAssembly(), MolecularModeling::Atom::SetDescription(), MolecularModeling::Atom::SetId(), MolecularModeling::Residue::SetId(), MolecularModeling::Residue::SetName(), MolecularModeling::Atom::SetName(), MolecularModeling::Atom::SetResidue(), and gmml::Split().
{
    try
    {
        this->ClearAssembly();
        PdbFile* pdb_file = new PdbFile(pdb_file_path);
        vector<string> key_order = vector<string>();
        PdbFile::PdbResidueAtomsMap residue_atoms_map = pdb_file->GetAllAtomsInOrder(key_order);
        for(vector<string>::iterator it = key_order.begin(); it != key_order.end(); it++)
        {
            string residue_key = *it;
            PdbFile::PdbAtomVector* atoms = residue_atoms_map[residue_key];
            Residue* residue = new Residue();
            residue->SetAssembly(this);
            for(PdbFile::PdbAtomVector::iterator it1 = atoms->begin(); it1 != atoms->end(); it1++)
            {
                PdbAtom* atom = (*it1);
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream ss;
                ss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = ss.str();
                residue->SetId(key);
                Atom* new_atom = new Atom();
                residue->SetName(residue_name);
                string atom_name = atom->GetAtomName();
                new_atom->SetName(atom_name);
                new_atom->MolecularDynamicAtom::SetCharge(gmml::ConvertString<double>(atom->GetAtomCharge()));
                new_atom->SetResidue(residue);
                stringstream atom_key;
                atom_key << atom_name << "_" << atom->GetAtomSerialNumber() << "_" << key;
                new_atom->SetId(atom_key.str());
                PdbModelCard* models = pdb_file->GetModels();
                PdbModelCard::PdbModelMap model_maps = models->GetModels();
                if(model_maps.size() == 1)
                {
                    new_atom->AddCoordinate(new Geometry::Coordinate(atom->GetAtomOrthogonalCoordinate()));
                    vector<string> card_index = gmml::Split(atom->GetAtomCardIndexInResidueSet(), "_");
                    if(card_index.at(0).compare("ATOM") == 0)
                    {
                        new_atom->SetDescription("Atom;");
                    }
                    else if(card_index.at(0).compare("HETATOM") == 0)
                    {
                        new_atom->SetDescription("Het;");
                    }
                }
                else
                {
                    for(PdbModelCard::PdbModelMap::iterator it2 = model_maps.begin(); it2 != model_maps.end(); it2++)
                    {
                        PdbModel* model = (*it2).second;
                        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
                        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
                        vector<string> card_index = gmml::Split(atom->GetAtomCardIndexInResidueSet(), "_");
                        if(card_index.at(0).compare("ATOM") == 0)
{
                            PdbAtomCard* atom_card = atom_cards.at(gmml::ConvertString<int>(card_index.at(1)));
                            PdbAtomCard::PdbAtomMap atom_map = atom_card->GetAtoms();
                            PdbAtom* matching_atom = atom_map[atom->GetAtomSerialNumber()];
                            string matching_residue_name = matching_atom->GetAtomResidueName();
                            char matching_chain_id = matching_atom->GetAtomChainId();
                            int matching_sequence_number = matching_atom->GetAtomResidueSequenceNumber();
                            char matching_insertion_code = matching_atom->GetAtomInsertionCode();
                            char matching_alternate_location = matching_atom->GetAtomAlternateLocation();
                            stringstream sss;
                            sss << matching_residue_name << "_" << matching_chain_id << "_" << matching_sequence_number << "_"
                                << matching_insertion_code << "_" << matching_alternate_location;
                            string matching_key = sss.str();
                            if(key.compare(matching_key) == 0)
{
                                Geometry::Coordinate* coordinate = new Geometry::Coordinate(matching_atom->GetAtomOrthogonalCoordinate());
                                new_atom->AddCoordinate(coordinate);
                                new_atom->SetDescription("Atom;");
                            }
                        }
                        else if(card_index.at(0).compare("HETATOM") == 0)
{
                            PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
                            PdbHeterogenAtomCard* heterogen_atom_card = heterogen_atom_cards.at(gmml::ConvertString<int>(card_index.at(1)));
                            PdbAtomCard::PdbAtomMap heterogen_atom_map = heterogen_atom_card->GetHeterogenAtoms();
                            PdbAtom* matching_heterogen_atom = heterogen_atom_map[atom->GetAtomSerialNumber()];
                            string matching_heterogen_residue_name = matching_heterogen_atom->GetAtomResidueName();
                            char matching_heterogen_chain_id = matching_heterogen_atom->GetAtomChainId();
                            int matching_heterogen_sequence_number = matching_heterogen_atom->GetAtomResidueSequenceNumber();
                            char matching_heterogen_insertion_code = matching_heterogen_atom->GetAtomInsertionCode();
                            char matching_heterogen_alternate_location = matching_heterogen_atom->GetAtomAlternateLocation();
                            stringstream ssss;
                            ssss << matching_heterogen_residue_name << "_" << matching_heterogen_chain_id << "_" << matching_heterogen_sequence_number << "_"
                                 << matching_heterogen_insertion_code << "_" << matching_heterogen_alternate_location;
                            string matching_heterogen_key = ssss.str();
                            if(key.compare(matching_heterogen_key) == 0)
{
                                Geometry::Coordinate* coordinate = new Geometry::Coordinate(matching_heterogen_atom->GetAtomOrthogonalCoordinate());
                                new_atom->AddCoordinate(coordinate);
                                new_atom->SetDescription("Het;");
                            }
                        }
                    }
                }
                residue->AddAtom(new_atom);
            }
            this->AddResidue(residue);
        }
    }
    catch(PdbFileSpace::PdbFileProcessingException &ex)
    {}
}
void Assembly::BuildAssemblyFromPrepFile (std::string prep_file_path)
Definition at line 625 of file assembly.cc.
References MolecularModeling::Residue::AddAtom(), MolecularModeling::Atom::AddCoordinate(), MolecularModeling::Residue::AddHeadAtom(), MolecularModeling::Residue::AddTailAtom(), ClearAssembly(), gmml::ConvertInternalCoordinate2CartesianCoordinate(), PrepFileSpace::PrepFileAtom::GetAngle(), PrepFileSpace::PrepFileAtom::GetAngleIndex(), PrepFileSpace::PrepFileResidue::GetAtoms(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), PrepFileSpace::PrepFileAtom::GetBondIndex(), PrepFileSpace::PrepFileAtom::GetBondLength(), PrepFileSpace::PrepFileAtom::GetCharge(), PrepFileSpace::PrepFileResidue::GetCoordinateType(), PrepFileSpace::PrepFileAtom::GetDihedral(), PrepFileSpace::PrepFileAtom::GetDihedralIndex(), PrepFileSpace::PrepFileResidue::GetDummyAtomType(), PrepFileSpace::PrepFileAtom::GetIndex(), PrepFileSpace::PrepFileAtom::GetName(), PrepFileSpace::PrepFileResidue::GetName(), PrepFileSpace::PrepFile::GetResidues(), PrepFileSpace::PrepFileAtom::GetTopologicalType(), PrepFileSpace::PrepFileAtom::GetType(), PrepFileSpace::kINT, PrepFileSpace::kTopTypeM, PrepFileSpace::kXYZ, MolecularModeling::Residue::SetAssembly(), MolecularModeling::Atom::SetId(), MolecularModeling::Residue::SetId(), MolecularModeling::Residue::SetName(), MolecularModeling::Atom::SetName(), and MolecularModeling::Atom::SetResidue().
{
    this->ClearAssembly();
    PrepFile* prep_file = new PrepFile(prep_file_path);
    sequence_number_ = 1;
    PrepFile::ResidueMap prep_residues = prep_file->GetResidues();
    stringstream ss;
    for(PrepFile::ResidueMap::iterator it = prep_residues.begin(); it != prep_residues.end(); it++)
    {
        int head_atom_index = INFINITY;
        int tail_atom_index = -INFINITY;
        Atom* head_atom = new Atom();
        Atom* tail_atom = new Atom();
        Residue* assembly_residue = new Residue();
        assembly_residue->SetAssembly(this);
        string residue_name = (*it).first;
        assembly_residue->SetName(residue_name);
        assembly_residue->SetId(residue_name);
        PrepFileResidue* prep_residue = (*it).second;
        string prep_residue_name = prep_residue->GetName();
        if(distance(prep_residues.begin(), it) == (int)prep_residues.size()-1)
            ss << prep_residue_name;
        else
            ss << prep_residue_name << "-";
        PrepFileResidue::PrepFileAtomVector prep_atoms = prep_residue->GetAtoms();
        for(PrepFileResidue::PrepFileAtomVector::iterator it1 = prep_atoms.begin(); it1 != prep_atoms.end(); it1++)
        {
            Atom* assembly_atom = new Atom();
            PrepFileAtom* prep_atom = (*it1);
            assembly_atom->SetResidue(assembly_residue);
            string atom_name = prep_atom->GetName();
            assembly_atom->SetName(atom_name);
            stringstream atom_id;
            atom_id << residue_name << ":" << atom_name;
            assembly_atom->SetId(atom_id.str());
            assembly_atom->MolecularDynamicAtom::SetAtomType(prep_atom->GetType());
            assembly_atom->MolecularDynamicAtom::SetCharge(prep_atom->GetCharge());
            if(prep_residue->GetCoordinateType() == PrepFileSpace::kINT)
            {
                vector<Coordinate*> coordinate_list = vector<Coordinate*>();
                int index = distance(prep_atoms.begin(), it1);
                if(index == 0)
                {
                }
                if(index == 1)
                {
                    PrepFileAtom* parent_atom = prep_atoms.at(prep_atom->GetBondIndex() - 1);
                    Coordinate* parent_coordinate = new Coordinate(parent_atom->GetBondLength(), parent_atom->GetAngle(), parent_atom->GetDihedral());
                    coordinate_list.push_back(parent_coordinate);
                }
                if(index == 2)
                {
                    PrepFileAtom* grandparent_atom = prep_atoms.at(prep_atom->GetAngleIndex() - 1);
                    PrepFileAtom* parent_atom = prep_atoms.at(prep_atom->GetBondIndex() - 1);
                    Coordinate* grandparent_coordinate = new Coordinate(grandparent_atom->GetBondLength(), grandparent_atom->GetAngle(), grandparent_atom->GetDihedral());
                    Coordinate* parent_coordinate = new Coordinate(parent_atom->GetBondLength(), parent_atom->GetAngle(), parent_atom->GetDihedral());
                    coordinate_list.push_back(grandparent_coordinate);
                    coordinate_list.push_back(parent_coordinate);
                }
                if(index > 2)
                {
                    PrepFileAtom* great_grandparent_atom = prep_atoms.at(prep_atom->GetDihedralIndex() - 1);
                    PrepFileAtom* grandparent_atom = prep_atoms.at(prep_atom->GetAngleIndex() - 1);
                    PrepFileAtom* parent_atom = prep_atoms.at(prep_atom->GetBondIndex() - 1);
                    Coordinate* great_grandparent_coordinate = new Coordinate(great_grandparent_atom->GetBondLength(), great_grandparent_atom->GetAngle(),
                                                                              great_grandparent_atom->GetDihedral());
                    Coordinate* grandparent_coordinate = new Coordinate(grandparent_atom->GetBondLength(), grandparent_atom->GetAngle(), grandparent_atom->GetDihedral());
                    Coordinate* parent_coordinate = new Coordinate(parent_atom->GetBondLength(), parent_atom->GetAngle(), parent_atom->GetDihedral());
                    coordinate_list.push_back(great_grandparent_coordinate);
                    coordinate_list.push_back(grandparent_coordinate);
                    coordinate_list.push_back(parent_coordinate);
                }
                Coordinate* coordinate = gmml::ConvertInternalCoordinate2CartesianCoordinate(coordinate_list, prep_atom->GetBondLength(),
                                                                                             prep_atom->GetAngle(), prep_atom->GetDihedral());
                assembly_atom->AddCoordinate(coordinate);
            }
            else if(prep_residue->GetCoordinateType() == PrepFileSpace::kXYZ)
            {
                assembly_atom->AddCoordinate(new Coordinate(prep_atom->GetBondLength(), prep_atom->GetAngle(), prep_atom->GetDihedral()));
            }
            if(prep_atom->GetTopologicalType() == kTopTypeM && prep_atom->GetType().compare(prep_residue->GetDummyAtomType()) != 0)
            {
                if(head_atom_index > prep_atom->GetIndex())
                {
                    head_atom_index = prep_atom->GetIndex();
                    head_atom = assembly_atom;
                }
                if(tail_atom_index < prep_atom->GetIndex())
                {
                    tail_atom_index = prep_atom->GetIndex();
                    tail_atom = assembly_atom;
                }
            }
            if(assembly_atom->GetAtomType().compare("DU") != 0)
                assembly_residue->AddAtom(assembly_atom);
        }
        assembly_residue->AddHeadAtom(head_atom);
        assembly_residue->AddTailAtom(tail_atom);
        residues_.push_back(assembly_residue);
    }
    name_ = ss.str();
}
void Assembly::BuildAssemblyFromTopologyCoordinateFile (std::string topology_file_path, std::string coordinate_file_path)
Definition at line 576 of file assembly.cc.
References MolecularModeling::Residue::AddAtom(), MolecularModeling::Atom::AddCoordinate(), ClearAssembly(), gmml::dNotSet, TopologyFileSpace::TopologyFile::GetAssembly(), TopologyFileSpace::TopologyAtom::GetAtomCharge(), TopologyFileSpace::TopologyAtom::GetAtomMass(), TopologyFileSpace::TopologyAtom::GetAtomName(), TopologyFileSpace::TopologyResidue::GetAtoms(), CoordinateFileSpace::CoordinateFile::GetCoordinates(), TopologyFileSpace::TopologyResidue::GetIndex(), TopologyFileSpace::TopologyAtom::GetIndex(), TopologyFileSpace::TopologyAssembly::GetResidues(), TopologyFileSpace::TopologyFile::GetTitle(), TopologyFileSpace::TopologyAtom::GetType(), MolecularModeling::Residue::SetAssembly(), MolecularModeling::Atom::SetId(), MolecularModeling::Residue::SetId(), MolecularModeling::Residue::SetName(), MolecularModeling::Atom::SetName(), and MolecularModeling::Atom::SetResidue().
{
    this->ClearAssembly();
    TopologyFile* topology_file = new TopologyFile(topology_file_path);
    name_ = topology_file->GetTitle();
    sequence_number_ = 1;
    TopologyAssembly::TopologyResidueMap topology_residues = topology_file->GetAssembly()->GetResidues();
    for(TopologyAssembly::TopologyResidueMap::iterator it = topology_residues.begin(); it != topology_residues.end(); it++)
    {
        Residue* assembly_residue = new Residue();
        assembly_residue->SetAssembly(this);
        string residue_name = (*it).first;
        assembly_residue->SetName(residue_name);
        TopologyResidue* topology_residue = (*it).second;
        stringstream id;
        id << residue_name << "(" << topology_residue->GetIndex() << ")" ;
        assembly_residue->SetId(id.str());
        TopologyResidue::TopologyAtomMap topology_atoms = topology_residue->GetAtoms();
        for(TopologyResidue::TopologyAtomMap::iterator it1 = topology_atoms.begin(); it1 != topology_atoms.end(); it1++)
        {
            Atom* assembly_atom = new Atom();
            string atom_name = (*it1).first;
            assembly_atom->SetName(atom_name);
            stringstream atom_id;
            atom_id << id.str() << ":" << atom_name;
            assembly_atom->SetId(atom_id.str());
            TopologyAtom* topology_atom = (*it1).second;
            assembly_atom->MolecularDynamicAtom::SetCharge(topology_atom->GetAtomCharge());
            assembly_atom->MolecularDynamicAtom::SetAtomType(topology_atom->GetType());
            assembly_atom->MolecularDynamicAtom::SetRadius(dNotSet); ////////////////////////
            assembly_atom->MolecularDynamicAtom::SetMass(topology_atom->GetAtomMass());
            int topology_atom_index = topology_atom->GetIndex();
            assembly_atom->SetResidue(assembly_residue);
            assembly_atom->SetName(topology_atom->GetAtomName());
            CoordinateFile* coordinate_file = new CoordinateFile(coordinate_file_path);
            vector<Geometry::Coordinate*> coord_file_coordinates = coordinate_file->GetCoordinates();
            assembly_atom->AddCoordinate(coord_file_coordinates.at(topology_atom_index-1));
            assembly_residue->AddAtom(assembly_atom);
        }
        residues_.push_back(assembly_residue);
    }
}
void Assembly::BuildAssemblyFromTopologyFile (std::string topology_file_path)
Definition at line 478 of file assembly.cc.
References MolecularModeling::Residue::AddAtom(), AddResidue(), ClearAssembly(), gmml::dNotSet, TopologyFileSpace::TopologyFile::GetAssembly(), TopologyFileSpace::TopologyAtom::GetAtomCharge(), TopologyFileSpace::TopologyAtom::GetAtomMass(), TopologyFileSpace::TopologyAtom::GetAtomName(), TopologyFileSpace::TopologyResidue::GetAtoms(), TopologyFileSpace::TopologyResidue::GetIndex(), TopologyFileSpace::TopologyAssembly::GetResidues(), TopologyFileSpace::TopologyFile::GetTitle(), TopologyFileSpace::TopologyAtom::GetType(), MolecularModeling::Residue::SetAssembly(), MolecularModeling::Atom::SetId(), MolecularModeling::Residue::SetId(), MolecularModeling::Residue::SetName(), MolecularModeling::Atom::SetName(), and MolecularModeling::Atom::SetResidue().
{
    this->ClearAssembly();
    TopologyFile* topology_file = new TopologyFile(topology_file_path);
    name_ = topology_file->GetTitle();
    sequence_number_ = 1;
    TopologyAssembly::TopologyResidueMap topology_residues = topology_file->GetAssembly()->GetResidues();
    for(TopologyAssembly::TopologyResidueMap::iterator it = topology_residues.begin(); it != topology_residues.end(); it++)
    {
        Residue* assembly_residue = new Residue();
        assembly_residue->SetAssembly(this);
        string residue_name = (*it).first;
        assembly_residue->SetName(residue_name);
        TopologyResidue* topology_residue = (*it).second;
        stringstream id;
        id << residue_name << "(" << topology_residue->GetIndex() << ")" ;
        assembly_residue->SetId(id.str());
        TopologyResidue::TopologyAtomMap topology_atoms = topology_residue->GetAtoms();
        for(TopologyResidue::TopologyAtomMap::iterator it1 = topology_atoms.begin(); it1 != topology_atoms.end(); it1++)
        {
            Atom* assembly_atom = new Atom();
            string atom_name = (*it1).first;
            assembly_atom->SetName(atom_name);
            stringstream atom_id;
            atom_id << id.str() << ":" << atom_name;
            assembly_atom->SetId(atom_id.str());
            TopologyAtom* topology_atom = (*it1).second;
            assembly_atom->MolecularDynamicAtom::SetCharge(topology_atom->GetAtomCharge());
            assembly_atom->MolecularDynamicAtom::SetMass(topology_atom->GetAtomMass());
            assembly_atom->MolecularDynamicAtom::SetRadius(dNotSet); ///////////////////
            assembly_atom->MolecularDynamicAtom::SetAtomType(topology_atom->GetType());
            assembly_atom->SetResidue(assembly_residue);
            assembly_atom->SetName(topology_atom->GetAtomName());
            assembly_residue->AddAtom(assembly_atom);
        }
        this->AddResidue(assembly_residue);
    }
}
CoordinateFile * Assembly::BuildCoordinateFileStructureFromAssembly ()
Definition at line 1830 of file assembly.cc.
References GetAllCoordinates(), CoordinateFileSpace::CoordinateFile::SetCoordinates(), CoordinateFileSpace::CoordinateFile::SetNumberOfCoordinates(), and CoordinateFileSpace::CoordinateFile::SetTitle().
{
    vector<Coordinate*> coordinates = this->GetAllCoordinates();
    CoordinateFile* coordinate_file = new CoordinateFile();
    coordinate_file->SetCoordinates(coordinates);
    coordinate_file->SetNumberOfCoordinates(coordinates.size());
    string title = "Generated by GMML";
    coordinate_file->SetTitle(title);
    return coordinate_file;
}
LibraryFile * Assembly::BuildLibraryFileStructureFromAssembly ()
Definition at line 1841 of file assembly.cc.
References LibraryFileSpace::LibraryFileResidue::AddAtom(), GetAllResiduesOfAssembly(), MolecularModeling::Residue::GetAssembly(), MolecularModeling::Residue::GetAtoms(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), MolecularModeling::MolecularDynamicAtom::GetCharge(), MolecularModeling::Atom::GetCoordinates(), MolecularModeling::Residue::GetHeadAtoms(), GetModelIndex(), MolecularModeling::Residue::GetName(), MolecularModeling::Atom::GetName(), LibraryFileSpace::LibraryFileResidue::GetName(), MolecularModeling::Atom::GetNode(), MolecularModeling::AtomNode::GetNodeNeighbors(), MolecularModeling::Residue::GetTailAtoms(), gmml::iNotSet, LibraryFileSpace::LibraryFileResidue::SetHeadAtomIndex(), LibraryFileSpace::LibraryFileResidue::SetName(), LibraryFileSpace::LibraryFile::SetResidues(), and LibraryFileSpace::LibraryFileResidue::SetTailAtomIndex().
{
    LibraryFile* library_file = new LibraryFile();
    LibraryFile::ResidueMap residue_map = LibraryFile::ResidueMap();
    ResidueVector residues_of_assembly = this->GetAllResiduesOfAssembly();
    for(ResidueVector::iterator it = residues_of_assembly.begin(); it != residues_of_assembly.end(); it++)
    {
        Residue* assembly_residue = *it;
        int residue_index = distance(residues_of_assembly.begin(), it) + 1;
        AtomVector assembly_residue_atoms = assembly_residue->GetAtoms();
        LibraryFileResidue* library_residue = new LibraryFileResidue();
        library_residue->SetName(assembly_residue->GetName());
        AtomVector head_atoms = assembly_residue->GetHeadAtoms();
        AtomVector tail_atoms = assembly_residue->GetTailAtoms();
        if(!head_atoms.empty())
        {
            int head_atom_index = distance(assembly_residue_atoms.begin(), find(assembly_residue_atoms.begin(), assembly_residue_atoms.end(), head_atoms.at(0))) + 1;
            library_residue->SetHeadAtomIndex(head_atom_index);
        }
        if(!tail_atoms.empty())
        {
            int tail_atom_index = distance(assembly_residue_atoms.begin(), find(assembly_residue_atoms.begin(), assembly_residue_atoms.end(), tail_atoms.at(0))) + 1;
            library_residue->SetTailAtomIndex(tail_atom_index);
        }
        int order = 1;
        for(AtomVector::iterator it1 = assembly_residue_atoms.begin(); it1 != assembly_residue_atoms.end(); it1++)
        {
            Atom* residue_atom = (*it1);
            int atom_index = distance(assembly_residue_atoms.begin(), it1) + 1;
            vector<int> bonded_atom_indices = vector<int>();
            AtomNode* atom_node = residue_atom->GetNode();
            AtomVector atom_neighbours = atom_node->GetNodeNeighbors();
            for(AtomVector::iterator it2 = atom_neighbours.begin(); it2 != atom_neighbours.end(); it2++)
            {
                int bonded_atom_index = distance(assembly_residue_atoms.begin(), it2);
                bonded_atom_indices.push_back(bonded_atom_index);
            }
            LibraryFileAtom* atom = new LibraryFileAtom(residue_atom->GetAtomType(), residue_atom->GetName(), residue_index, atom_index,
                                                        gmml::iNotSet, residue_atom->GetCharge(),
                                                        *(residue_atom->GetCoordinates()[assembly_residue->GetAssembly()->GetModelIndex()]), bonded_atom_indices,
                                                        order);
            order++;
            library_residue->AddAtom(atom);
        }
        residue_map[library_residue->GetName()] = library_residue;
    }
    library_file->SetResidues(residue_map);
    return library_file;
}
PdbFile * Assembly::BuildPdbFileStructureFromAssembly ()
Definition at line 734 of file assembly.cc.
References ExtractPdbModelCardFromAssembly(), PdbFileSpace::PdbModel::SetModelResidueSet(), PdbFileSpace::PdbModelCard::SetModels(), PdbFileSpace::PdbFile::SetModels(), PdbFileSpace::PdbModel::SetModelSerialNumber(), PdbFileSpace::PdbTitleCard::SetTitle(), and PdbFileSpace::PdbFile::SetTitle().
{
    PdbFile* pdb_file = new PdbFile();
    PdbTitleCard* title_card = new PdbTitleCard();
    title_card->SetTitle("Generated by GMML");
    // Set pdb_file title card
    pdb_file->SetTitle(title_card);
    PdbModelCard* model_card = new PdbModelCard();
    PdbModelCard::PdbModelMap models = PdbModelCard::PdbModelMap();
    PdbModel* model = new PdbModel();
    model->SetModelSerialNumber(1);
    PdbModelResidueSet* residue_set = new PdbModelResidueSet();
    int serial_number = 1;
    int sequence_number = 1;
    ExtractPdbModelCardFromAssembly(residue_set, serial_number, sequence_number, model_index_);
    model->SetModelResidueSet(residue_set);
    models[1] = model;
    model_card->SetModels(models);
    pdb_file->SetModels(model_card);
    return pdb_file;
}
PrepFile * Assembly::BuildPrepFileStructureFromAssembly ()
Definition at line 844 of file assembly.cc.
References gmml::DEFUALT_DUMMY_ATOMS, GetAllResiduesOfAssembly(), PrepFileSpace::PrepFileAtom::GetAngle(), MolecularModeling::Residue::GetAtoms(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), PrepFileSpace::PrepFileAtom::GetBondLength(), MolecularModeling::MolecularDynamicAtom::GetCharge(), PrepFileSpace::PrepFileAtom::GetDihedral(), MolecularModeling::Residue::GetName(), MolecularModeling::Atom::GetName(), MolecularModeling::Atom::GetNode(), MolecularModeling::AtomNode::GetNodeNeighbors(), PrepFileSpace::PrepFileAtom::GetTopologicalType(), PrepFileSpace::kFormatted, PrepFileSpace::kGeometryCorrect, PrepFileSpace::kINT, PrepFileSpace::kOmit, PrepFileSpace::kPositionBeg, PrepFileSpace::kTopTypeB, PrepFileSpace::kTopTypeE, PrepFileSpace::kTopTypeM, PrepFileSpace::kTopTypeS, PrepFileSpace::PrepFileAtom::SetAngle(), PrepFileSpace::PrepFileAtom::SetAngleIndex(), PrepFileSpace::PrepFileAtom::SetBondIndex(), PrepFileSpace::PrepFileAtom::SetBondLength(), PrepFileSpace::PrepFileAtom::SetCharge(), PrepFileSpace::PrepFileAtom::SetDihedral(), PrepFileSpace::PrepFileAtom::SetIndex(), PrepFileSpace::PrepFileAtom::SetName(), PrepFileSpace::PrepFile::SetResidues(), PrepFileSpace::PrepFileAtom::SetTopologicalType(), and PrepFileSpace::PrepFileAtom::SetType().
{
    PrepFile* prep_file = new PrepFile();
    ResidueVector assembly_residues = this->GetAllResiduesOfAssembly();
    PrepFile::ResidueMap prep_residues = PrepFile::ResidueMap();
    for(ResidueVector::iterator it = assembly_residues.begin(); it != assembly_residues.end(); it++)
    {
        Residue* assembly_residue = *it;
        vector<TopologicalType> stack = vector<TopologicalType>();
        PrepFileResidue* prep_residue = new PrepFileResidue();
        PrepFileResidue::PrepFileAtomVector prep_atoms = PrepFileResidue::PrepFileAtomVector();
        prep_residue->SetTitle(assembly_residue->GetName());
        prep_residue->SetName(assembly_residue->GetName());
        prep_residue->SetGeometryType(PrepFileSpace::kGeometryCorrect);
        prep_residue->SetCoordinateType(PrepFileSpace::kINT);
        prep_residue->SetDummyAtomOmission(PrepFileSpace::kOmit);
        prep_residue->SetDummyAtomType("DU");
        prep_residue->SetDummyAtomPosition(PrepFileSpace::kPositionBeg);
//        prep_residue->SetImproperDihedrals();
//        prep_residue->SetLoops();
        prep_residue->SetOutputFormat(PrepFileSpace::kFormatted);
        AtomVector assembly_atoms = assembly_residue->GetAtoms();
        CoordinateVector coordinate_list = CoordinateVector();
        int atom_index = 1;
        for(int i = 0; i < DEFUALT_DUMMY_ATOMS; i ++)
        {
            PrepFileAtom* dummy_atom = new PrepFileAtom();
            dummy_atom->SetIndex(atom_index);
            dummy_atom->SetName("DUMM");
            dummy_atom->SetType("DU");
            dummy_atom->SetTopologicalType(PrepFileSpace::kTopTypeM);
            dummy_atom->SetBondIndex(i);
            dummy_atom->SetAngleIndex(i-1);
            dummy_atom->SetDihedral(i-2);
            if(i <= 0)
                dummy_atom->SetBondLength(0.0);
            else
                dummy_atom->SetBondLength(1.0);
            if(i <= 1)
                dummy_atom->SetAngle(0.0);
            else
                dummy_atom->SetAngle(90.0);
            dummy_atom->SetDihedral(0.0);
            dummy_atom->SetCharge(0.0);
            dummy_atom->SetTopologicalType(kTopTypeM);
            stack.push_back(dummy_atom->GetTopologicalType());
            atom_index++;
            coordinate_list.push_back(new Coordinate(dummy_atom->GetBondLength(), dummy_atom->GetAngle(), dummy_atom->GetDihedral()));
            prep_atoms.push_back(dummy_atom);
        }
        for(AtomVector::iterator it1 = assembly_atoms.begin(); it1 != assembly_atoms.end(); it1++)
        {
            Atom* assembly_atom = (*it1);
            PrepFileAtom* prep_atom = new PrepFileAtom();
            prep_atom->SetIndex(atom_index);
            // Set topological type
            // Set bond index, angle index, dihedral index
            // Call function to set parent, grandparent and great_grandparent of the current atom
            // Call coordinate conversion function
            if(assembly_atom->GetNode()->GetNodeNeighbors().size() == 1)
                prep_atom->SetTopologicalType(kTopTypeE);
            else if(assembly_atom->GetNode()->GetNodeNeighbors().size() == 2)
            {
//                TopologicalType type = stack.pop_back();
                prep_atom->SetTopologicalType(kTopTypeB);
            }
            else if(assembly_atom->GetNode()->GetNodeNeighbors().size() == 3)
                prep_atom->SetTopologicalType(kTopTypeS);
            else if(assembly_atom->GetNode()->GetNodeNeighbors().size() == 4)
                prep_atom->SetTopologicalType(kTopTypeM);
            stack.push_back(prep_atom->GetTopologicalType());
//            if(atom_index == 4)
//            {
//                prep_atom->SetTopologicalType(kTopTypeM);
//                coordinate_list.push_back(assembly_atom->GetCoordinates().at(0));
//            }
//            else if(atom_index > 4)
//            {
//                coordinate_list.at(0) = coordinate_list.at(1);
//                coordinate_list.at(1) = coordinate_list.at(2);
//                coordinate_list.at(2) = coordinate_list.at(3);
//                coordinate_list.at(3) = assembly_atom->GetCoordinates().at(0);
//            }
//            Coordinate* internal_coordinate = gmml::ConvertCartesianCoordinate2InternalCoordinate(assembly_atom->GetCoordinates().at(0),
//                                                                                                  coordinate_list);
//            prep_atom->SetAngle();
//            prep_atom->SetAngleIndex();
//            prep_atom->SetBondIndex();
//            prep_atom->SetBondLength();
            prep_atom->SetCharge(assembly_atom->GetCharge());
//            prep_atom->SetDihedral();
//            prep_atom->SetDihedralIndex();
            prep_atom->SetName(assembly_atom->GetName());
//            prep_atom->SetTopologicalType();
            prep_atom->SetType(assembly_atom->GetAtomType());
            atom_index++;
            prep_atoms.push_back(prep_atom);
        }
        prep_residue->SetAtoms(prep_atoms);
        prep_residue->SetCharge(prep_residue->CalculatePrepResidueCharge());
        prep_residues[assembly_residue->GetName()] = prep_residue;
    }
//    prep_file->SetPath();
    prep_file->SetResidues(prep_residues);
    return prep_file;
}
void Assembly::BuildStructure (gmml::BuildingStructureOption building_option, std::vector< std::string > options, std::vector< std::string > file_paths)
Definition at line 1891 of file assembly.cc.
References BuildStructureByDatabaseFilesBondingInformation(), BuildStructureByDistance(), BuildStructureByOriginalFileBondingInformation(), gmml::ConvertAssemblyInputFileType2String(), gmml::ConvertString2AssemblyInputFileType(), gmml::DATABASE, gmml::dCutOff, gmml::DISTANCE, GetSourceFile(), GetSourceFileType(), gmml::ORIGINAL, and gmml::Split().
{
    switch(building_option)
    {
        case gmml::DISTANCE:
            if(options.size() == 1)
            {
                stringstream ss(description_);
                ss << "Building option: Distance;";
                description_ = ss.str();
                vector<string> tokens = gmml::Split(options.at(0), ":");
                if(tokens.at(0).compare("cutoff") == 0)
                {
                    double cutoff = gmml::ConvertString<double>(tokens.at(1));
                    this->BuildStructureByDistance(cutoff);
                }
                if(tokens.at(0).compare("model_index") == 0)
                {
                    double cutoff = gmml::dCutOff;
                    int model_index = gmml::ConvertString<int>(tokens.at(1));
                    this->BuildStructureByDistance(cutoff, model_index);
                }
            }
            if(options.size() == 2)
            {
                stringstream ss(description_);
                ss << "Building option: Distance;";
                description_ = ss.str();
                vector<string> cutoff_tokens = gmml::Split(options.at(0), ":");
                vector<string> model_tokens = gmml::Split(options.at(1), ":");
                double cutoff = gmml::dCutOff;
                int model_index = 0;
                if(cutoff_tokens.at(0).compare("cutoff") == 0)
                {
                    cutoff = gmml::ConvertString<double>(cutoff_tokens.at(1));
                }
                if(model_tokens.at(0).compare("model_index") == 0)
                {
                    model_index = gmml::ConvertString<int>(model_tokens.at(1));
                }
                BuildStructureByDistance(cutoff, model_index);
            }
            else
            {
                BuildStructureByDistance();
            }
            break;
        case gmml::ORIGINAL:
        {
            stringstream ss(description_);
            ss << "Building option: Original;";
            ss << "File type: " << gmml::ConvertAssemblyInputFileType2String(this->GetSourceFileType()) << ";"
               << "File path: " << this->GetSourceFile() << ";";
            description_ = ss.str();
            this->BuildStructureByOriginalFileBondingInformation();
            break;
        }
        case gmml::DATABASE:
            vector<gmml::InputFileType> types = vector<gmml::InputFileType>();
            for(unsigned int i = 0; i < options.size(); i++)
            {
                vector<string> tokens = gmml::Split(options.at(i), ":");
                if(tokens.at(0).compare("type") == 0)
                {
                    gmml::InputFileType type = gmml::ConvertString2AssemblyInputFileType(tokens.at(1));
                    types.push_back(type);
                }
            }
            if(types.size() == file_paths.size())
            {
                stringstream ss(description_);
                ss << "Building option: Distance;";
                for(unsigned int i = 0; i < types.size(); i++)
                {
                    ss << "File type: " << types.at(i) << ";" << "File path: " << file_paths.at(i) << ";";
                }
                description_ = ss.str();
                this->BuildStructureByDatabaseFilesBondingInformation(types, file_paths);
            }
            break;
    }
}
void Assembly::BuildStructureByDatabaseFilesBondingInformation (std::vector< gmml::InputFileType > types, std::vector< std::string > file_paths)
Definition at line 2216 of file assembly.cc.
References MolecularModeling::AtomNode::AddNodeNeighbor(), GetAllAtomsOfAssembly(), LibraryFileSpace::LibraryFileResidue::GetAtomByIndex(), PrepFileSpace::PrepFileResidue::GetAtomIndexByName(), PrepFileSpace::PrepFileResidue::GetAtomNameByIndex(), LibraryFileSpace::LibraryFileAtom::GetBondedAtomsIndices(), PrepFileSpace::PrepFileResidue::GetBondingsOfResidue(), MolecularModeling::Atom::GetId(), LibraryFileSpace::LibraryFileResidue::GetLibraryAtomByAtomName(), LibraryFileSpace::LibraryFile::GetLibraryResidueByResidueName(), MolecularModeling::Residue::GetName(), MolecularModeling::Atom::GetName(), LibraryFileSpace::LibraryFileResidue::GetName(), LibraryFileSpace::LibraryFileAtom::GetName(), PrepFileSpace::PrepFileAtom::GetName(), PrepFileSpace::PrepFileResidue::GetName(), PrepFileSpace::PrepFileResidue::GetPrepAtomByName(), MolecularModeling::Atom::GetResidue(), PrepFileSpace::PrepFile::GetResidues(), gmml::LIB, gmml::PREP, MolecularModeling::AtomNode::SetAtom(), MolecularModeling::AtomNode::SetId(), and MolecularModeling::Atom::SetNode().
Referenced by BuildStructure().
{
    cout << "Building structure ..." << endl;
    AtomVector all_atoms_of_assembly = this->GetAllAtomsOfAssembly();
    int i = 0;
    for(AtomVector::iterator it = all_atoms_of_assembly.begin(); it != all_atoms_of_assembly.end(); it++)
    {
        Atom* atom = (*it);
        AtomNode* atom_node = new AtomNode();
        atom_node->SetAtom(atom);
        atom_node->SetId(i);
        i++;
        Residue* assembly_residue = atom->GetResidue();
        for(unsigned int i = 0; i < types.size(); i++)
        {
            if(types.at(i) == gmml::LIB)
            {
                string lib_path = file_paths.at(i);
                LibraryFile* library_file = new LibraryFile(lib_path);
                LibraryFileResidue* library_residue = library_file->GetLibraryResidueByResidueName(assembly_residue->GetName());
                if(library_residue != NULL)
                {
                    LibraryFileAtom* library_atom = library_residue->GetLibraryAtomByAtomName(atom->GetName());
                    if(library_atom != NULL)
                    {
                        vector<int> library_bonded_atom_indices = library_atom->GetBondedAtomsIndices();
                        for(vector<int>::iterator it1 = library_bonded_atom_indices.begin(); it1 != library_bonded_atom_indices.end(); it1++)
{
                            int library_bonded_atom_index = (*it1);
                            LibraryFileAtom* library_atom = library_residue->GetAtomByIndex(library_bonded_atom_index);
                            for(AtomVector::iterator it2 = all_atoms_of_assembly.begin(); it2 != all_atoms_of_assembly.end(); it2++)
{
                                Atom* assembly_atom = (*it2);
                                string assembly_atom_id = assembly_atom->GetId();
                                stringstream ss;
                                ss << library_residue->GetName() << ":" << library_atom->GetName();
                                string library_atom_id = ss.str();
                                if(assembly_atom_id.compare(library_atom_id) == 0)
{
                                    atom_node->AddNodeNeighbor(assembly_atom);
                                    break;
                                }
                            }
                        }
                    }
                }
            }
            if(types.at(i) == gmml::PREP)
            {
                string prep_path = file_paths.at(i);
                PrepFile* prep_file = new PrepFile(prep_path);
                PrepFileResidue* prep_residue = prep_file->GetResidues()[assembly_residue->GetName()];
                if(prep_residue != NULL)
                {
                    PrepFileAtom* prep_atom = prep_residue->GetPrepAtomByName(atom->GetName());
                    if(prep_atom != NULL)
                    {
                        vector<int> bonded_atoms_index = prep_residue->GetBondingsOfResidue()[prep_residue->GetAtomIndexByName(atom->GetName())];
                        for(vector<int>::iterator it1 = bonded_atoms_index.begin(); it1 != bonded_atoms_index.end(); it1++)
{
                            int bonded_atom_index = (*it1);
                            PrepFileAtom* bonded_atom = prep_residue->GetPrepAtomByName(prep_residue->GetAtomNameByIndex(bonded_atom_index));
                            stringstream ss;
                            ss << prep_residue->GetName() << ":" << bonded_atom->GetName();
                            for(AtomVector::iterator it2 = all_atoms_of_assembly.begin(); it2 != all_atoms_of_assembly.end(); it2++)
{
                                Atom* assembly_atom = (*it2);
                                if(assembly_atom->GetId().compare(ss.str()) == 0)
{
                                    atom_node->AddNodeNeighbor(assembly_atom);
                                    break;
                                }
                            }
                        }
                    }
                }
            }
            atom->SetNode(atom_node);
        }
    }
}
void Assembly::BuildStructureByDistance (double cutoff = gmml::dCutOff, int model_index = 0)
Definition at line 1974 of file assembly.cc.
References MolecularModeling::AtomNode::AddNodeNeighbor(), GetAllAtomsOfAssembly(), MolecularModeling::Atom::GetCoordinates(), MolecularModeling::AtomNode::SetAtom(), MolecularModeling::AtomNode::SetId(), and MolecularModeling::Atom::SetNode().
Referenced by BuildStructure().
{
    cout << "Building structure by distance ..." << endl;
    model_index_ = model_index;
    AtomVector all_atoms_of_assembly = this->GetAllAtomsOfAssembly();
    int i = 0;
    for(AtomVector::iterator it = all_atoms_of_assembly.begin(); it != all_atoms_of_assembly.end(); it++)
    {
        Atom* atom = (*it);
        AtomNode* atom_node = new AtomNode();
        atom_node->SetAtom(atom);
        atom_node->SetId(i);
        i++;
        for(AtomVector::iterator it1 = all_atoms_of_assembly.begin(); it1 != all_atoms_of_assembly.end(); it1++)
        {
            if(it != it1)
            {
                Atom* neighbor_atom = (*it1);
                if((atom->GetCoordinates().at(model_index)->Distance(*(neighbor_atom->GetCoordinates().at(model_index)))) < cutoff)
                {
                    atom_node->AddNodeNeighbor(neighbor_atom);
                }
            }
        }
        atom->SetNode(atom_node);
    }
}
void Assembly::BuildStructureByLIBFileInformation ()
Definition at line 2128 of file assembly.cc.
References MolecularModeling::AtomNode::AddNodeNeighbor(), GetAllAtomsOfAssembly(), LibraryFileSpace::LibraryFileResidue::GetAtomByIndex(), LibraryFileSpace::LibraryFileAtom::GetBondedAtomsIndices(), MolecularModeling::Atom::GetId(), LibraryFileSpace::LibraryFileResidue::GetLibraryAtomByAtomName(), LibraryFileSpace::LibraryFile::GetLibraryResidueByResidueName(), MolecularModeling::Residue::GetName(), MolecularModeling::Atom::GetName(), LibraryFileSpace::LibraryFileResidue::GetName(), LibraryFileSpace::LibraryFileAtom::GetName(), MolecularModeling::Atom::GetResidue(), GetSourceFile(), MolecularModeling::AtomNode::SetAtom(), MolecularModeling::AtomNode::SetId(), and MolecularModeling::Atom::SetNode().
Referenced by BuildStructureByOriginalFileBondingInformation().
{
    cout << "Building structure ..." << endl;
    LibraryFile* library_file = new LibraryFile(this->GetSourceFile());
    AtomVector all_atoms_of_assembly = this->GetAllAtomsOfAssembly();
    int i = 0;
    for(AtomVector::iterator it = all_atoms_of_assembly.begin(); it != all_atoms_of_assembly.end(); it++)
    {
        Atom* atom = (*it);
        AtomNode* atom_node = new AtomNode();
        atom_node->SetAtom(atom);
        atom_node->SetId(i);
        i++;
        Residue* assembly_residue = atom->GetResidue();
        LibraryFileResidue* library_residue = library_file->GetLibraryResidueByResidueName(assembly_residue->GetName());
        if(library_residue != NULL)
        {
            LibraryFileAtom* library_atom = library_residue->GetLibraryAtomByAtomName(atom->GetName());
            if(library_atom != NULL)
            {
                vector<int> library_bonded_atom_indices = library_atom->GetBondedAtomsIndices();
                for(vector<int>::iterator it1 = library_bonded_atom_indices.begin(); it1 != library_bonded_atom_indices.end(); it1++)
                {
                    int library_bonded_atom_index = (*it1);
                    LibraryFileAtom* library_atom = library_residue->GetAtomByIndex(library_bonded_atom_index);
                    for(AtomVector::iterator it2 = all_atoms_of_assembly.begin(); it2 != all_atoms_of_assembly.end(); it2++)
                    {
                        Atom* assembly_atom = (*it2);
                        string assembly_atom_id = assembly_atom->GetId();
                        stringstream ss;
                        ss << library_residue->GetName() << ":" << library_atom->GetName();
                        string library_atom_id = ss.str();
                        if(assembly_atom_id.compare(library_atom_id) == 0)
{
                            atom_node->AddNodeNeighbor(assembly_atom);
                            break;
                        }
                    }
                }
            }
        }
        atom->SetNode(atom_node);
    }
}
void Assembly::BuildStructureByOriginalFileBondingInformation ()
Definition at line 2002 of file assembly.cc.
References BuildStructureByLIBFileInformation(), BuildStructureByPDBFileInformation(), BuildStructureByPrepFileInformation(), BuildStructureByTOPFileInformation(), GetSourceFileType(), gmml::LIB, gmml::MULTIPLE, gmml::PDB, gmml::PREP, gmml::TOP, gmml::TOP_CRD, and gmml::UNKNOWN.
Referenced by BuildStructure().
{
    gmml::InputFileType type = this->GetSourceFileType();
    switch(type)
    {
        case gmml::PDB:
            this->BuildStructureByPDBFileInformation();
            break;
        case gmml::TOP:
            this->BuildStructureByTOPFileInformation();
            break;
        case gmml::LIB:
            this->BuildStructureByLIBFileInformation();
            break;
        case gmml::PREP:
            this->BuildStructureByPrepFileInformation();
            break;
        case gmml::TOP_CRD:
            break;
        case gmml::MULTIPLE:
            break;
        case gmml::UNKNOWN:
            break;
    }
}
void Assembly::BuildStructureByPDBFileInformation ()
Definition at line 2028 of file assembly.cc.
References MolecularModeling::AtomNode::AddNodeNeighbor(), GetAllAtomsOfAssembly(), PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbFile::GetAtomBySerialNumber(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomName(), PdbFileSpace::PdbFile::GetAtomOfResidueByAtomKey(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbAtom::GetAtomSerialNumber(), PdbFileSpace::PdbConnectCard::GetBondedAtomsSerialNumbers(), PdbFileSpace::PdbFile::GetConnectivities(), MolecularModeling::Atom::GetId(), GetSourceFile(), MolecularModeling::AtomNode::SetAtom(), MolecularModeling::AtomNode::SetId(), and MolecularModeling::Atom::SetNode().
Referenced by BuildStructureByOriginalFileBondingInformation().
{
    try{
        cout << "Building structure ..." << endl;
        PdbFile* pdb_file = new PdbFile(this->GetSourceFile());
        AtomVector all_atoms_of_assembly = this->GetAllAtomsOfAssembly();
        int i = 0;
        for(AtomVector::iterator it = all_atoms_of_assembly.begin(); it != all_atoms_of_assembly.end(); it++)
        {
            Atom* atom = (*it);
            AtomNode* atom_node = new AtomNode();
            atom_node->SetAtom(atom);
            atom_node->SetId(i);
            i++;
            PdbAtom* pdb_atom = pdb_file->GetAtomOfResidueByAtomKey(atom->GetId());
            if(pdb_atom != NULL)
            {
                int atom_serial_number = pdb_atom->GetAtomSerialNumber();
                PdbConnectCard* connectivities = pdb_file->GetConnectivities();
                PdbConnectCard::BondedAtomsSerialNumbersMap bonded_atoms_map = connectivities->GetBondedAtomsSerialNumbers();
                vector<int> bonded_atoms_serial_number = bonded_atoms_map[atom_serial_number];
                for(vector<int>::iterator it1 = bonded_atoms_serial_number.begin(); it1 != bonded_atoms_serial_number.end(); it1++)
                {
                    int bonded_atom_serial_number = *it1;
                    PdbAtom* pdb_bonded_atom = pdb_file->GetAtomBySerialNumber(bonded_atom_serial_number);
                    stringstream sss;
                    sss << pdb_bonded_atom->GetAtomName() << "_" << pdb_bonded_atom->GetAtomSerialNumber() << "_" << pdb_bonded_atom->GetAtomResidueName()
                        << "_" << pdb_bonded_atom->GetAtomChainId() << "_" << pdb_bonded_atom->GetAtomResidueSequenceNumber()
                        << "_" << pdb_bonded_atom->GetAtomInsertionCode() << "_" << pdb_bonded_atom->GetAtomAlternateLocation();
                    string pdb_bonded_atom_key = sss.str();
                    for(AtomVector::iterator it2 = all_atoms_of_assembly.begin(); it2 != all_atoms_of_assembly.end(); it2++)
                    {
                        if(it != it2)
{
                            Atom* assembly_atom = (*it2);
                            string assembly_atom_key = assembly_atom->GetId();
                            if(assembly_atom_key.compare(pdb_bonded_atom_key) == 0)
{
                                atom_node->AddNodeNeighbor(assembly_atom);
                                break;
                            }
                        }
                    }
                }
            }
            atom->SetNode(atom_node);
        }
    }
    catch(PdbFileSpace::PdbFileProcessingException &ex)
    {}
}
void Assembly::BuildStructureByPrepFileInformation ()
Definition at line 2173 of file assembly.cc.
References MolecularModeling::AtomNode::AddNodeNeighbor(), GetAllAtomsOfAssembly(), PrepFileSpace::PrepFileResidue::GetAtomIndexByName(), PrepFileSpace::PrepFileResidue::GetAtomNameByIndex(), PrepFileSpace::PrepFileResidue::GetBondingsOfResidue(), MolecularModeling::Atom::GetId(), MolecularModeling::Residue::GetName(), MolecularModeling::Atom::GetName(), PrepFileSpace::PrepFileAtom::GetName(), PrepFileSpace::PrepFileResidue::GetName(), PrepFileSpace::PrepFileResidue::GetPrepAtomByName(), MolecularModeling::Atom::GetResidue(), PrepFileSpace::PrepFile::GetResidues(), GetSourceFile(), MolecularModeling::AtomNode::SetAtom(), MolecularModeling::AtomNode::SetId(), and MolecularModeling::Atom::SetNode().
Referenced by BuildStructureByOriginalFileBondingInformation().
{
    cout << "Building structure ..." << endl;
    PrepFile* prep_file = new PrepFile(this->GetSourceFile());
    AtomVector all_atoms_of_assembly = this->GetAllAtomsOfAssembly();
    int i = 0;
    for(AtomVector::iterator it = all_atoms_of_assembly.begin(); it != all_atoms_of_assembly.end(); it++)
    {
        Atom* atom = (*it);
        AtomNode* atom_node = new AtomNode();
        atom_node->SetAtom(atom);
        atom_node->SetId(i);
        i++;
        Residue* assembly_residue = atom->GetResidue();
        PrepFileResidue* prep_residue = prep_file->GetResidues()[assembly_residue->GetName()];
        if(prep_residue != NULL)
        {
            PrepFileAtom* prep_atom = prep_residue->GetPrepAtomByName(atom->GetName());
            if(prep_atom != NULL)
            {
                vector<int> bonded_atoms_index = prep_residue->GetBondingsOfResidue()[prep_residue->GetAtomIndexByName(atom->GetName())];
                for(vector<int>::iterator it1 = bonded_atoms_index.begin(); it1 != bonded_atoms_index.end(); it1++)
                {
                    int bonded_atom_index = (*it1);
                    PrepFileAtom* bonded_atom = prep_residue->GetPrepAtomByName(prep_residue->GetAtomNameByIndex(bonded_atom_index));
                    stringstream ss;
                    ss << prep_residue->GetName() << ":" << bonded_atom->GetName();
                    for(AtomVector::iterator it2 = all_atoms_of_assembly.begin(); it2 != all_atoms_of_assembly.end(); it2++)
                    {
                        Atom* assembly_atom = (*it2);
                        if(assembly_atom->GetId().compare(ss.str()) == 0)
{
                            atom_node->AddNodeNeighbor(assembly_atom);
                            break;
                        }
                    }
                }
            }
        }
        atom->SetNode(atom_node);
    }
}
void Assembly::BuildStructureByTOPFileInformation ()
Definition at line 2080 of file assembly.cc.
References MolecularModeling::AtomNode::AddNodeNeighbor(), GetAllAtomsOfAssembly(), TopologyFileSpace::TopologyBond::GetBonds(), TopologyFileSpace::TopologyFile::GetBonds(), MolecularModeling::Atom::GetId(), TopologyFileSpace::TopologyBond::GetResidueNames(), GetSourceFile(), MolecularModeling::AtomNode::SetAtom(), MolecularModeling::AtomNode::SetId(), and MolecularModeling::Atom::SetNode().
Referenced by BuildStructureByOriginalFileBondingInformation().
{
    cout << "Building structure ..." << endl;
    TopologyFile* topology_file = new TopologyFile(this->GetSourceFile());
    AtomVector all_atoms_of_assembly = this->GetAllAtomsOfAssembly();
    int i = 0;
    for (AtomVector::iterator it = all_atoms_of_assembly.begin(); it != all_atoms_of_assembly.end(); it++)
    {
        Atom* atom_1 = (*it);
        AtomNode* atom_node = new AtomNode();
        atom_node->SetAtom(atom_1);
        atom_node->SetId(i);
        i++;
        for(AtomVector::iterator it1 = all_atoms_of_assembly.begin(); it1 != all_atoms_of_assembly.end(); it1++)
        {
            if(it != it1)
            {
                Atom* atom_2 = (*it1);
                stringstream ss;
                ss << atom_1->GetId() << "-" << atom_2->GetId();
                string key = ss.str();
                TopologyFile::TopologyBondMap topology_bond = topology_file->GetBonds();
                for(TopologyFile::TopologyBondMap::iterator it2 = topology_bond.begin(); it2 != topology_bond.end(); it2++)
                {
                    TopologyBond* bond = (*it2).second;
                    stringstream sss;
                    sss << bond->GetResidueNames().at(0) << ":" << bond->GetBonds().at(0) << "-" << bond->GetResidueNames().at(1) << ":" << bond->GetBonds().at(1);
                    string topology_bond_key = sss.str();
                    if(key.compare(topology_bond_key) == 0)
                    {
                        atom_node->AddNodeNeighbor(atom_2);
                        break;
                    }
                    stringstream ssss;
                    ssss << bond->GetResidueNames().at(1) << ":" << bond->GetBonds().at(1) << "-" << bond->GetResidueNames().at(0) << ":" << bond->GetBonds().at(0);
                    topology_bond_key = ssss.str();
                    if(key.compare(topology_bond_key) == 0)
                    {
                        atom_node->AddNodeNeighbor(atom_2);
                        break;
                    }
                }
            }
        }
        atom_1->SetNode(atom_node);
    }
}
TopologyFile * Assembly::BuildTopologyFileStructureFromAssembly (std::string parameter_file_path)
Pairs
Bond Types, Bonds
Excluded Atoms
Angle Types, Angle
Excluded Atoms
Excluded Atoms
Definition at line 956 of file assembly.cc.
References TopologyFileSpace::TopologyResidue::AddAtom(), TopologyFileSpace::TopologyAtom::AddExcludedAtom(), TopologyFileSpace::TopologyAssembly::AddResidue(), CountMaxNumberOfAtomsInLargestResidue(), CountNumberOfAnglesExcludingHydrogen(), CountNumberOfAnglesIncludingHydrogen(), CountNumberOfAngleTypes(), CountNumberOfAtoms(), CountNumberOfAtomTypes(), CountNumberOfBondsExcludingHydrogen(), CountNumberOfBondsIncludingHydrogen(), CountNumberOfBondTypes(), CountNumberOfDihedralsExcludingHydrogen(), CountNumberOfDihedralsIncludingHydrogen(), CountNumberOfDihedralTypes(), CountNumberOfExcludedAtoms(), CountNumberOfResidues(), gmml::dNotSet, ExtractTopologyAnglesFromAssembly(), ExtractTopologyAngleTypesFromAssembly(), ExtractTopologyBondsFromAssembly(), ExtractTopologyBondTypesFromAssembly(), ExtractTopologyDihedralsFromAssembly(), ExtractTopologyDihedralTypesFromAssembly(), GetAllResiduesOfAssembly(), ParameterFileSpace::ParameterFile::GetAngles(), MolecularModeling::Residue::GetAtoms(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), ParameterFileSpace::ParameterFile::GetAtomTypes(), ParameterFileSpace::ParameterFile::GetBonds(), MolecularModeling::MolecularDynamicAtom::GetCharge(), ParameterFileSpace::ParameterFile::GetDihedrals(), MolecularModeling::Atom::GetId(), MolecularModeling::MolecularDynamicAtom::GetMass(), MolecularModeling::Residue::GetName(), MolecularModeling::Atom::GetName(), MolecularModeling::Atom::GetNode(), MolecularModeling::AtomNode::GetNodeNeighbors(), ParameterFileSpace::ParameterFileAtom::GetRadius(), ParameterFileSpace::ParameterFileAtom::GetWellDepth(), gmml::iNotSet, TopologyFileSpace::TopologyFile::SetAssembly(), TopologyFileSpace::TopologyAssembly::SetAssemblyName(), TopologyFileSpace::TopologyAtom::SetAtomCharge(), TopologyFileSpace::TopologyAtom::SetAtomicNumber(), TopologyFileSpace::TopologyAtom::SetAtomMass(), TopologyFileSpace::TopologyAtom::SetAtomName(), TopologyFileSpace::TopologyFile::SetAtomPairs(), TopologyFileSpace::TopologyAtomPair::SetCoefficientA(), TopologyFileSpace::TopologyAtomPair::SetCoefficientB(), TopologyFileSpace::TopologyResidue::SetIndex(), TopologyFileSpace::TopologyAtomPair::SetIndex(), TopologyFileSpace::TopologyAtom::SetIndex(), TopologyFileSpace::TopologyFile::SetNumberOfAnglesExcludingHydrogen(), TopologyFileSpace::TopologyFile::SetNumberOfAnglesIncludingHydrogen(), TopologyFileSpace::TopologyFile::SetNumberOfAngleTypes(), TopologyFileSpace::TopologyFile::SetNumberOfAtoms(), TopologyFileSpace::TopologyFile::SetNumberOfAtomsInLargestResidue(), TopologyFileSpace::TopologyFile::SetNumberOfBondsExcludingHydrogen(), TopologyFileSpace::TopologyFile::SetNumberOfBondsIncludingHydrogen(), TopologyFileSpace::TopologyFile::SetNumberOfBondTypes(), TopologyFileSpace::TopologyFile::SetNumberOfDihedralsExcludingHydrogen(), TopologyFileSpace::TopologyFile::SetNumberOfDihedralsIncludingHydrogen(), TopologyFileSpace::TopologyFile::SetNumberOfDihedralTypes(), TopologyFileSpace::TopologyFile::SetNumberOfExcludedAtoms(), TopologyFileSpace::TopologyFile::SetNumberOfResidues(), TopologyFileSpace::TopologyFile::SetNumberOfTypes(), TopologyFileSpace::TopologyAtomPair::SetPairType(), TopologyFileSpace::TopologyAtom::SetRadii(), TopologyFileSpace::TopologyResidue::SetResidueName(), TopologyFileSpace::TopologyAtom::SetResidueName(), TopologyFileSpace::TopologyAtom::SetScreen(), TopologyFileSpace::TopologyResidue::SetStartingAtomIndex(), TopologyFileSpace::TopologyFile::SetTotalNumberOfAngles(), TopologyFileSpace::TopologyFile::SetTotalNumberOfBonds(), TopologyFileSpace::TopologyAtom::SetTreeChainClasification(), and TopologyFileSpace::TopologyAtom::SetType().
{
    TopologyFile* topology_file = new TopologyFile();
    topology_file->SetNumberOfAtoms(this->CountNumberOfAtoms());
    topology_file->SetNumberOfTypes(this->CountNumberOfAtomTypes());
    topology_file->SetNumberOfBondsIncludingHydrogen(this->CountNumberOfBondsIncludingHydrogen());
    topology_file->SetNumberOfBondsExcludingHydrogen(this->CountNumberOfBondsExcludingHydrogen());
    topology_file->SetNumberOfAnglesIncludingHydrogen(this->CountNumberOfAnglesIncludingHydrogen());
    topology_file->SetNumberOfAnglesExcludingHydrogen(this->CountNumberOfAnglesExcludingHydrogen());
    topology_file->SetNumberOfDihedralsIncludingHydrogen(this->CountNumberOfDihedralsIncludingHydrogen(parameter_file_path));
    topology_file->SetNumberOfDihedralsExcludingHydrogen(this->CountNumberOfDihedralsExcludingHydrogen(parameter_file_path));
    //    topology_file->SetNumberOfHydrogenParameters();
    //    topology_file->SetNumberOfParameters();
    topology_file->SetNumberOfExcludedAtoms(this->CountNumberOfExcludedAtoms());   // Does not match
    topology_file->SetNumberOfResidues(this->CountNumberOfResidues());
    topology_file->SetTotalNumberOfBonds(this->CountNumberOfBondsExcludingHydrogen());
    topology_file->SetTotalNumberOfAngles(this->CountNumberOfAnglesExcludingHydrogen());
    topology_file->SetNumberOfBondTypes(this->CountNumberOfBondTypes());
    topology_file->SetNumberOfAngleTypes(this->CountNumberOfAngleTypes());
    topology_file->SetNumberOfDihedralTypes(this->CountNumberOfDihedralTypes(parameter_file_path));
    //    topology_file->SetNumberOfAtomTypesInParameterFile();
    //    topology_file->SetNumberOfDistinctHydrogenBonds();
    //    topology_file->SetPerturbationOption();
    //    topology_file->SetNumberOfBondsPerturbed();
    //    topology_file->SetNumberOfAnglesPerturbed();
    //    topology_file->SetNumberOfDihedralsPerturbed();
    //    topology_file->SetNumberOfBondsGroupPerturbed();
    //    topology_file->SetNumberOfAnglesGroupPerturbed();
    //    topology_file->SetNumberOfDihedralsGroupPerturbed();
    //    topology_file->SetStandardPeriodicBoxOption();
    topology_file->SetNumberOfAtomsInLargestResidue(this->CountMaxNumberOfAtomsInLargestResidue());
    //    topology_file->SetCapOption();
    //    topology_file->SetNumberOfExtraPoints();
    //    topology_file->SetNumberOfBeads();
    TopologyAssembly* topology_assembly = new TopologyAssembly();
    ResidueVector assembly_residues = this->GetAllResiduesOfAssembly();
    int residue_counter = 0;
    int atom_counter = 1;
    stringstream ss;
    int bond_type_counter = 0;
    vector<vector<string> > inserted_bond_types = vector<vector<string> >();
    vector<vector<string> > inserted_bonds = vector<vector<string> >();
    int angle_type_counter = 0;
    vector<vector<string> > inserted_angle_types = vector<vector<string> >();
    vector<vector<string> > inserted_angles = vector<vector<string> >();
    int dihedral_type_counter = 0;
    vector<string>  inserted_dihedral_types = vector<string>();
    vector<vector<string> > inserted_dihedrals = vector<vector<string> >();
    TopologyFile::TopologyAtomPairMap pairs = TopologyFile::TopologyAtomPairMap();
    int pair_count = 1;
    vector<string> inserted_pairs = vector<string>();
    vector<string> excluded_atom_list = vector<string>();
    for(ResidueVector::iterator it = assembly_residues.begin(); it != assembly_residues.end(); it++)
    {
        Residue* assembly_residue = *it;
        TopologyResidue* topology_residue = new TopologyResidue();
        residue_counter++;
        topology_residue->SetIndex(residue_counter);
        topology_residue->SetResidueName(assembly_residue->GetName());
        if(distance(assembly_residues.begin(), it) == (int)assembly_residues.size()-1)
            ss << assembly_residue->GetName();
        else
            ss << assembly_residue->GetName() << "-";
        topology_residue->SetStartingAtomIndex(atom_counter);
        AtomVector assembly_atoms = assembly_residue->GetAtoms();
        ParameterFile* parameter_file = new ParameterFile(parameter_file_path);
        ParameterFileSpace::ParameterFile::BondMap bonds = parameter_file->GetBonds();
        ParameterFileSpace::ParameterFile::AngleMap angles = parameter_file->GetAngles();
        ParameterFileSpace::ParameterFile::DihedralMap dihedrals = parameter_file->GetDihedrals();
        ParameterFileSpace::ParameterFile::AtomTypeMap atom_types_map = parameter_file->GetAtomTypes();
        for(AtomVector::iterator it1 = assembly_atoms.begin(); it1 != assembly_atoms.end(); it1++)
        {
            Atom* assembly_atom = (*it1);
            stringstream key1;
            key1 << assembly_atom->GetId();
            TopologyAtom* topology_atom = new TopologyAtom();
            topology_atom->SetAtomName(assembly_atom->GetName());
            topology_atom->SetAtomCharge(assembly_atom->GetCharge());
            topology_atom->SetAtomicNumber(iNotSet);
            topology_atom->SetAtomMass(assembly_atom->GetMass());
            //            topology_atom->SetNumberOfExcludedAtomsForEachAtom();
            topology_atom->SetResidueName(assembly_residue->GetName());
            topology_atom->SetType(assembly_atom->GetAtomType());
            topology_atom->SetTreeChainClasification("0");
            topology_atom->SetRadii(dNotSet);
            topology_atom->SetScreen(dNotSet);
            topology_atom->SetIndex(atom_counter);
            topology_residue->AddAtom(topology_atom);
            atom_counter++;
            ///Pairs
            for(AtomVector::iterator it2 = assembly_atoms.begin(); it2 != assembly_atoms.end(); it2++)
            {
                Atom* pair_assembly_atom = (*it2);
                string atom_type1 = assembly_atom->GetAtomType();
                string atom_type2 = pair_assembly_atom->GetAtomType();
                vector<string> pair_vector = vector<string>();
                pair_vector.push_back(atom_type1);
                pair_vector.push_back(atom_type2);
                stringstream sss;
                sss << atom_type1 << "-" << atom_type2;
                stringstream reverse_sss;
                reverse_sss << atom_type2 << "-" << atom_type1;
                if(find(inserted_pairs.begin(), inserted_pairs.end(), sss.str()) == inserted_pairs.end() &&
                   find(inserted_pairs.begin(), inserted_pairs.end(), reverse_sss.str()) == inserted_pairs.end()  )
                {
                    TopologyAtomPair* topology_atom_pair = new TopologyAtomPair();
                    ParameterFileAtom* parameter_atom1 = atom_types_map[atom_type1];
                    ParameterFileAtom* parameter_atom2 = atom_types_map[atom_type2];
                    double epsilon = sqrt(parameter_atom1->GetWellDepth() * parameter_atom2->GetWellDepth());
                    double sigma = 0.5 * (parameter_atom1->GetRadius() * pow(2, -(1.0)/(6.0))) + parameter_atom2->GetRadius() * pow(2, -(1.0)/(6.0));
                    double coefficient_a = 4 * epsilon * pow(sigma, 12);
                    double coefficient_b = 4 * epsilon * pow(sigma, 6);
                    topology_atom_pair->SetCoefficientA(coefficient_a);
                    topology_atom_pair->SetCoefficientB(coefficient_b);
                    topology_atom_pair->SetPairType(sss.str());
                    topology_atom_pair->SetIndex(pair_count);
                    pair_count++;
                    inserted_pairs.push_back(sss.str());
                    pairs[sss.str()] = topology_atom_pair;
                }
            }
            ///Bond Types, Bonds
            AtomNode* atom_node = assembly_atom->GetNode();
            AtomVector neighbors = atom_node->GetNodeNeighbors();
            for(AtomVector::iterator it2 = neighbors.begin(); it2 != neighbors.end(); it2++)
            {
                Atom* neighbor = (*it2);
                stringstream key2;
                key2 << neighbor->GetId();
                ExtractTopologyBondTypesFromAssembly(inserted_bond_types, assembly_atom, neighbor, bonds, bond_type_counter, topology_file);
                ExtractTopologyBondsFromAssembly(inserted_bonds, inserted_bond_types, assembly_atom, neighbor, topology_file);
                ///Excluded Atoms
                stringstream first_order_interaction;
                stringstream reverse_first_order_interaction;
                first_order_interaction << key1.str() << "-" << key2.str();
                reverse_first_order_interaction << key2.str() << "-" << key1.str();
                if(find(excluded_atom_list.begin(), excluded_atom_list.end(), first_order_interaction.str()) == excluded_atom_list.end() &&
                        find(excluded_atom_list.begin(), excluded_atom_list.end(), reverse_first_order_interaction.str()) == excluded_atom_list.end())
                {
                    excluded_atom_list.push_back(first_order_interaction.str());
                    topology_atom->AddExcludedAtom(key2.str());
                }
                ///Angle Types, Angle
                AtomNode* neighbor_node = neighbor->GetNode();
                AtomVector neighbors_of_neighbor = neighbor_node->GetNodeNeighbors();
                for(AtomVector::iterator it3 = neighbors_of_neighbor.begin(); it3 != neighbors_of_neighbor.end(); it3++)
                {
                    Atom* neighbor_of_neighbor = (*it3);
                    stringstream key3;
                    key3 << neighbor_of_neighbor->GetId();
                    if(key1.str().compare(key3.str()) != 0)
                    {
                        ExtractTopologyAngleTypesFromAssembly(assembly_atom, neighbor, neighbor_of_neighbor, inserted_angle_types, angle_type_counter,
                                                              topology_file, angles);
                        ExtractTopologyAnglesFromAssembly(assembly_atom, neighbor, neighbor_of_neighbor, inserted_angles, inserted_angle_types, topology_file);
                        ///Excluded Atoms
                        stringstream second_order_interaction;
                        stringstream reverse_second_order_interaction;
                        second_order_interaction << key1.str() << "-" << key3.str();
                        reverse_second_order_interaction << key3.str() << "-" << key1.str();
                        if(find(excluded_atom_list.begin(), excluded_atom_list.end(), second_order_interaction.str()) == excluded_atom_list.end() &&
                                find(excluded_atom_list.begin(), excluded_atom_list.end(), reverse_second_order_interaction.str()) == excluded_atom_list.end())
{
                            excluded_atom_list.push_back(second_order_interaction.str());
                            topology_atom->AddExcludedAtom(key3.str());
                        }
                        //Dihedral Types, Dihedrals
                        AtomNode* neighbor_of_neighbor_node = neighbor_of_neighbor->GetNode();
                        AtomVector neighbors_of_neighbor_neighbor = neighbor_of_neighbor_node->GetNodeNeighbors();
                        for(AtomVector::iterator it4 =  neighbors_of_neighbor_neighbor.begin(); it4 != neighbors_of_neighbor_neighbor.end(); it4++)
{
                            Atom* neighbor_of_neighbor_of_neighbor = (*it4);
                            stringstream key4;
                            key4 << neighbor_of_neighbor_of_neighbor->GetId();
                            if(key2.str().compare(key4.str()) != 0)
{
                                ExtractTopologyDihedralTypesFromAssembly(assembly_atom, neighbor, neighbor_of_neighbor, neighbor_of_neighbor_of_neighbor,
                                                                 inserted_dihedral_types, dihedral_type_counter, topology_file, dihedrals);
                                ExtractTopologyDihedralsFromAssembly(assembly_atom, neighbor, neighbor_of_neighbor, neighbor_of_neighbor_of_neighbor,
                                                                     inserted_dihedrals, inserted_dihedral_types, dihedrals, topology_file);
                                ///Excluded Atoms
                                stringstream third_order_interaction;
                                stringstream reverse_third_order_interaction;
                                third_order_interaction << key1.str() << "-" << key4.str();
                                reverse_third_order_interaction << key4.str() << "-" << key1.str();
                                if(find(excluded_atom_list.begin(), excluded_atom_list.end(), third_order_interaction.str()) == excluded_atom_list.end() &&
                                        find(excluded_atom_list.begin(), excluded_atom_list.end(), reverse_third_order_interaction.str()) == excluded_atom_list.end())
{
                                    excluded_atom_list.push_back(third_order_interaction.str());
                                    topology_atom->AddExcludedAtom(key4.str());
                                }
                            }
                        }
                    }
                }
            }
        }
        topology_assembly->AddResidue(topology_residue);
    }
//    for(ResidueVector::iterator it = assembly_residues.begin(); it != assembly_residues.end(); it++)
//    {
//        Residue* assembly_residue = *it;
//        AtomVector assembly_atoms = assembly_residue->GetAtoms();
//        for(AtomVector::iterator it1 = assembly_atoms.begin(); it1 != assembly_atoms.end(); it1++)
//        {
//            Atom* assembly_atom = (*it1);
//        }
//    }
    topology_assembly->SetAssemblyName(ss.str());
    topology_file->SetAtomPairs(pairs);
    topology_file->SetAssembly(topology_assembly);
    return topology_file;
}
void Assembly::CalculateCenterOfGeometry ()
Definition at line 2299 of file assembly.cc.
References CalculateCenterOfGeometry(), MolecularModeling::Residue::GetAtoms(), GetCenterOfGeometry(), and MolecularModeling::Atom::GetCoordinates().
Referenced by CalculateCenterOfGeometry().
{
    Coordinate center_of_geometry = Coordinate();
    int counter = 0;
    for(AssemblyVector::iterator it = assemblies_.begin(); it != assemblies_.end(); it++)
    {
        Assembly* assembly = (*it);
        assembly->CalculateCenterOfGeometry();
        counter++;
        center_of_geometry.operator +(assembly->GetCenterOfGeometry());
    }
    for(ResidueVector:: iterator it1 = residues_.begin(); it1 != residues_.end(); it1++)
    {
        Residue* residue = (*it1);
        Residue::AtomVector atoms = residue->GetAtoms();
        for(Residue::AtomVector::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
        {
            Atom* atom = (*it2);
            Atom::CoordinateVector coordinates = atom->GetCoordinates();
            Geometry::Coordinate coordinate = *coordinates[this->model_index_];
            center_of_geometry.operator +(coordinate);
            counter++;
        }
    }
    center_of_geometry.operator /(counter);
    center_of_geometry_ = Coordinate(center_of_geometry);
}
void Assembly::ClearAssembly ()
Definition at line 3454 of file assembly.cc.
Referenced by BuildAssemblyFromLibraryFile(), BuildAssemblyFromPdbFile(), BuildAssemblyFromPrepFile(), BuildAssemblyFromTopologyCoordinateFile(), and BuildAssemblyFromTopologyFile().
{
    this->residues_.clear();
    this->assemblies_.clear();
    //    this->source_file_ = "";
    //    this->source_file_type_ = UNKNOWN;
    //    this->chemical_type_ = "";
    //    this->description_ = "";
    //    this->sequence_number_ = 1;
    //    this->total_mass_ = dNotSet;
    //    this->center_of_geometry_ = Coordinate();
    //    this->center_of_mass_ = Coordinate();
    //    this->model_index_ = 0;
}
int Assembly::CountMaxNumberOfAtomsInLargestResidue ()
Definition at line 3435 of file assembly.cc.
References CountNumberOfAtoms(), and MolecularModeling::Residue::GetAtoms().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    int max = 0;
    for(AssemblyVector::iterator it = assemblies_.begin(); it != assemblies_.end(); it++)
    {
        Assembly* assembly = (*it);
        if(max <= assembly->CountNumberOfAtoms())
            max = assembly->CountNumberOfAtoms();
    }
    for(ResidueVector:: iterator it1 = residues_.begin(); it1 != residues_.end(); it1++)
    {
        Residue* residue = (*it1);
        Residue::AtomVector atoms = residue->GetAtoms();
        if(max <= atoms.size())
            max = atoms.size();
    }
    return max;
}
int Assembly::CountNumberOfAngles ()
Definition at line 2562 of file assembly.cc.
References GetAllAtomsOfAssembly(), MolecularModeling::Atom::GetId(), MolecularModeling::Atom::GetNode(), and MolecularModeling::AtomNode::GetNodeNeighbors().
{
    AtomVector atoms = GetAllAtomsOfAssembly();
    int counter = 0;
    for(AtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        Atom* atom = (*it);
        stringstream ss;
        ss << atom->GetId();
        AtomNode* atom_node = atom->GetNode();
        AtomVector neighbors = atom_node->GetNodeNeighbors();
        for(AtomVector::iterator it1 = neighbors.begin(); it1 != neighbors.end(); it1++)
        {
            Atom* neighbor = (*it1);
            AtomNode* neighbor_atom_node = neighbor->GetNode();
            AtomVector neighbors_of_neighbor = neighbor_atom_node->GetNodeNeighbors();
            for(AtomVector::iterator it2 = neighbors_of_neighbor.begin(); it2 != neighbors_of_neighbor.end(); it2++)
            {
                Atom* neighbor_of_neighbor = (*it2);
                stringstream ss1;
                ss1 << neighbor_of_neighbor->GetId();
                if(ss.str().compare(ss1.str()) != 0)
                {
                    counter++;
                }
            }
        }
    }
    return counter/2;
}
int Assembly::CountNumberOfAnglesExcludingHydrogen ()
Definition at line 2523 of file assembly.cc.
References GetAllAtomsOfAssembly(), MolecularModeling::Atom::GetId(), MolecularModeling::Atom::GetName(), MolecularModeling::Atom::GetNode(), and MolecularModeling::AtomNode::GetNodeNeighbors().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    AtomVector atoms = GetAllAtomsOfAssembly();
    int counter = 0;
    for(AtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        Atom* atom = (*it);
        stringstream ss;
        ss << atom->GetId();
        string atom_name = atom->GetName();
        AtomNode* atom_node = atom->GetNode();
        AtomVector neighbors = atom_node->GetNodeNeighbors();
        for(AtomVector::iterator it1 = neighbors.begin(); it1 != neighbors.end(); it1++)
        {
            Atom* neighbor = (*it1);
            string neighbor_name = neighbor->GetName();
            AtomNode* neighbor_atom_node = neighbor->GetNode();
            AtomVector neighbors_of_neighbor = neighbor_atom_node->GetNodeNeighbors();
            for(AtomVector::iterator it2 = neighbors_of_neighbor.begin(); it2 != neighbors_of_neighbor.end(); it2++)
            {
                Atom* neighbor_of_neighbor = (*it2);
                stringstream ss1;
                ss1 << neighbor_of_neighbor->GetId();
                if(ss.str().compare(ss1.str()) != 0)
                {
                    string neighbor_of_neighbor_name = neighbor_of_neighbor->GetName();
                    if((atom_name.substr(0,1).compare("H") == 0 || (atom_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(atom_name.substr(0,1))))) ||
                            (neighbor_name.substr(0,1).compare("H") == 0 || (neighbor_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor_name.substr(0,1))))) ||
                            (neighbor_of_neighbor_name.substr(0,1).compare("H") == 0 || (neighbor_of_neighbor_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor_of_neighbor_name.substr(0,1))))))
                    {}
                    else
                        counter++;
                }
            }
        }
    }
    return counter/2;
}
int Assembly::CountNumberOfAnglesIncludingHydrogen ()
Definition at line 2484 of file assembly.cc.
References GetAllAtomsOfAssembly(), MolecularModeling::Atom::GetId(), MolecularModeling::Atom::GetName(), MolecularModeling::Atom::GetNode(), and MolecularModeling::AtomNode::GetNodeNeighbors().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    AtomVector atoms = GetAllAtomsOfAssembly();
    int counter = 0;
    for(AtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        Atom* atom = (*it);
        stringstream ss;
        ss << atom->GetId();
        string atom_name = atom->GetName();
        AtomNode* atom_node = atom->GetNode();
        AtomVector neighbors = atom_node->GetNodeNeighbors();
        for(AtomVector::iterator it1 = neighbors.begin(); it1 != neighbors.end(); it1++)
        {
            Atom* neighbor = (*it1);
            string neighbor_name = neighbor->GetName();
            AtomNode* neighbor_atom_node = neighbor->GetNode();
            AtomVector neighbors_of_neighbor = neighbor_atom_node->GetNodeNeighbors();
            for(AtomVector::iterator it2 = neighbors_of_neighbor.begin(); it2 != neighbors_of_neighbor.end(); it2++)
            {
                Atom* neighbor_of_neighbor = (*it2);
                stringstream ss1;
                ss1 << neighbor_of_neighbor->GetId();
                if(ss.str().compare(ss1.str()) != 0)
                {
                    string neighbor_of_neighbor_name = neighbor_of_neighbor->GetName();
                    if((atom_name.substr(0,1).compare("H") == 0 || (atom_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(atom_name.substr(0,1))))) ||
                            (neighbor_name.substr(0,1).compare("H") == 0 || (neighbor_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor_name.substr(0,1))))) ||
                            (neighbor_of_neighbor_name.substr(0,1).compare("H") == 0 || (neighbor_of_neighbor_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor_of_neighbor_name.substr(0,1))))))
                    {
                        counter++;
                    }
                }
            }
        }
    }
    return counter/2;
}
int Assembly::CountNumberOfAngleTypes ()
Definition at line 2593 of file assembly.cc.
References GetAllAtomsOfAssembly(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), MolecularModeling::Atom::GetId(), MolecularModeling::Atom::GetNode(), and MolecularModeling::AtomNode::GetNodeNeighbors().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    AtomVector atoms = GetAllAtomsOfAssembly();
    vector<string> type_list = vector<string>();
    for(AtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        Atom* atom = (*it);
        string type1 = atom->GetAtomType();
        stringstream ss;
        ss << atom->GetId();
        AtomNode* atom_node = atom->GetNode();
        AtomVector neighbors = atom_node->GetNodeNeighbors();
        for(AtomVector::iterator it1 = neighbors.begin(); it1 != neighbors.end(); it1++)
        {
            Atom* neighbor = (*it1);
            string type2 = neighbor->GetAtomType();
            AtomNode* neighbor_atom_node = neighbor->GetNode();
            AtomVector neighbors_of_neighbor = neighbor_atom_node->GetNodeNeighbors();
            for(AtomVector::iterator it2 = neighbors_of_neighbor.begin(); it2 != neighbors_of_neighbor.end(); it2++)
            {
                Atom* neighbor_of_neighbor = (*it2);
                string type3 = neighbor_of_neighbor->GetAtomType();
                stringstream ss1;
                ss1 << neighbor_of_neighbor->GetId();
                if(ss.str().compare(ss1.str()) != 0)
                {
                    stringstream ss2;
                    ss2 << type1 << "_" << type2 << "_" << type3;
                    stringstream ss3;
                    ss3 << type3 << "_" << type2 << "_" << type1;
                    if(find(type_list.begin(), type_list.end(), ss2.str()) == type_list.end() &&
                            find(type_list.begin(), type_list.end(), ss3.str()) == type_list.end())
                        type_list.push_back(ss2.str());
                }
            }
        }
    }
    return type_list.size();
}
int Assembly::CountNumberOfAtoms ()
Definition at line 2327 of file assembly.cc.
References CountNumberOfAtoms(), and MolecularModeling::Residue::GetAtoms().
Referenced by BuildTopologyFileStructureFromAssembly(), CountMaxNumberOfAtomsInLargestResidue(), and CountNumberOfAtoms().
{
    int counter = 0;
    for(AssemblyVector::iterator it = assemblies_.begin(); it != assemblies_.end(); it++)
    {
        Assembly* assembly = (*it);
        counter += assembly->CountNumberOfAtoms();
    }
    for(ResidueVector:: iterator it1 = residues_.begin(); it1 != residues_.end(); it1++)
    {
        Residue* residue = (*it1);
        Residue::AtomVector atoms = residue->GetAtoms();
        counter += atoms.size();
    }
    return counter;
}
int Assembly::CountNumberOfAtomTypes ()
Definition at line 2344 of file assembly.cc.
References GetAllAtomsOfAssembly(), and MolecularModeling::MolecularDynamicAtom::GetAtomType().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    vector<string> type_list = vector<string>();
    AtomVector atoms = GetAllAtomsOfAssembly();
    for(AtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        Atom* atom = (*it);
        string atom_type = atom->GetAtomType();
        if(find(type_list.begin(), type_list.end(), atom_type) != type_list.end())
        {}
        else
        {
            type_list.push_back(atom_type);
        }
    }
    return type_list.size();
}
int Assembly::CountNumberOfBonds ()
Definition at line 2438 of file assembly.cc.
References GetAllAtomsOfAssembly(), MolecularModeling::Atom::GetNode(), and MolecularModeling::AtomNode::GetNodeNeighbors().
{
    AtomVector atoms = GetAllAtomsOfAssembly();
    int counter = 0;
    for(AtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        Atom* atom = (*it);
        AtomNode* atom_node = atom->GetNode();
        AtomVector node_neighbors = atom_node->GetNodeNeighbors();
        counter += node_neighbors.size();
    }
    return counter/2;
}
int Assembly::CountNumberOfBondsExcludingHydrogen ()
Definition at line 2406 of file assembly.cc.
References GetAllAtomsOfAssembly(), MolecularModeling::Atom::GetName(), MolecularModeling::Atom::GetNode(), and MolecularModeling::AtomNode::GetNodeNeighbors().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    AtomVector atoms = GetAllAtomsOfAssembly();
    int counter = 0;
    for(AtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        Atom* atom = (*it);
        string atom_name = atom->GetName();
        AtomNode* atom_node = atom->GetNode();
        AtomVector node_neighbors = atom_node->GetNodeNeighbors();
        if((atom_name.substr(0,1).compare("H") == 0 ||
            (atom_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(atom_name.substr(0,1))))))
        {}
        else
        {
            for(AtomVector::iterator it1 = node_neighbors.begin(); it1 != node_neighbors.end(); it1++)
            {
                Atom* node_neighbor = (*it1);
                string node_neighbor_name = node_neighbor->GetName();
                if((node_neighbor_name.substr(0,1).compare("H") == 0 ||
                    (node_neighbor_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(node_neighbor_name.substr(0,1))))))
                {}
                else
                {
                    counter++;
                }
            }
        }
    }
    return counter/2;
}
int Assembly::CountNumberOfBondsIncludingHydrogen ()
Definition at line 2374 of file assembly.cc.
References GetAllAtomsOfAssembly(), MolecularModeling::Atom::GetName(), MolecularModeling::Atom::GetNode(), and MolecularModeling::AtomNode::GetNodeNeighbors().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    AtomVector atoms = GetAllAtomsOfAssembly();
    int counter = 0;
    for(AtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        Atom* atom = (*it);
        string atom_name = atom->GetName();
        AtomNode* atom_node = atom->GetNode();
        AtomVector node_neighbors = atom_node->GetNodeNeighbors();
        if((atom_name.substr(0,1).compare("H") == 0 ||
            (atom_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(atom_name.substr(0,1))))))
        {
            counter += node_neighbors.size();
        }
        else
        {
            for(AtomVector::iterator it1 = node_neighbors.begin(); it1 != node_neighbors.end(); it1++)
            {
                Atom* node_neighbor = (*it1);
                string node_neighbor_name = node_neighbor->GetName();
                if((node_neighbor_name.substr(0,1).compare("H") == 0 ||
                    (node_neighbor_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(node_neighbor_name.substr(0,1))))))
                {
                    counter++;
                }
            }
        }
    }
    return counter/2;
}
int Assembly::CountNumberOfBondTypes ()
Definition at line 2452 of file assembly.cc.
References GetAllAtomsOfAssembly(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), MolecularModeling::Atom::GetNode(), and MolecularModeling::AtomNode::GetNodeNeighbors().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    AtomVector atoms = GetAllAtomsOfAssembly();
    vector<string> type_list = vector<string>();
    for(AtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        Atom* atom = (*it);
        string atom_bond_type = atom->GetAtomType();
        AtomNode* atom_node = atom->GetNode();
        AtomVector node_neighbors = atom_node->GetNodeNeighbors();
        for(AtomVector::iterator it1 = node_neighbors.begin(); it1 != node_neighbors.end(); it1++)
        {
            Atom* node_neighbor = (*it1);
            string node_neighbor_bond_type = node_neighbor->GetAtomType();
            stringstream ss;
            ss << atom_bond_type << "_" << node_neighbor_bond_type;
            string key = ss.str();
            stringstream ss1;
            ss1 << node_neighbor_bond_type << "_" << atom_bond_type;
            string key1 = ss1.str();
            if(find(type_list.begin(), type_list.end(), key ) != type_list.end() ||
                    find(type_list.begin(), type_list.end(), key1 ) != type_list.end())
            {}
            else
            {
                type_list.push_back(key);
            }
        }
    }
    return type_list.size();
}
int Assembly::CountNumberOfDihedrals (std::string parameter_file_path)
Improper Dihedrals
Definition at line 2843 of file assembly.cc.
References CreateAllAtomTypePermutationsforDihedralType(), CreateAllAtomTypePermutationsforImproperDihedralType(), GetAllAtomsOfAssembly(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), ParameterFileSpace::ParameterFile::GetDihedrals(), MolecularModeling::Atom::GetId(), MolecularModeling::Atom::GetNode(), MolecularModeling::AtomNode::GetNodeNeighbors(), and ParameterFileSpace::ParameterFileDihedral::GetTerms().
{
    ParameterFile* parameter_file = new ParameterFile(parameter_file_path);
    AtomVector atoms = GetAllAtomsOfAssembly();
    int counter = 0;
    int improper_counter = 0;
//    int not_found_counter = 0;
    for(AtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        Atom* atom = (*it);
        stringstream ss;
        ss << atom->GetId();
        AtomNode* atom_node = atom->GetNode();
        AtomVector neighbors = atom_node->GetNodeNeighbors();
        for(AtomVector::iterator it1 = neighbors.begin(); it1 != neighbors.end(); it1++)
        {
            Atom* neighbor = (*it1);
            stringstream ss1;
            ss1 << neighbor->GetId();
            AtomNode* neighbor_node = neighbor->GetNode();
            AtomVector neighbors_of_neighbor = neighbor_node->GetNodeNeighbors();
            for(AtomVector::iterator it2 = neighbors_of_neighbor.begin(); it2 != neighbors_of_neighbor.end(); it2++)
            {
                Atom* neighbor_of_neighbor = (*it2);
                stringstream ss2;
                ss2 << neighbor_of_neighbor->GetId();
                if(ss.str().compare(ss2.str()) != 0)
                {
                    AtomNode* neighbor_of_neighbor_node = neighbor_of_neighbor->GetNode();
                    AtomVector neighbors_of_neighbor_of_neighbor = neighbor_of_neighbor_node->GetNodeNeighbors();
                    for(AtomVector::iterator it3 = neighbors_of_neighbor_of_neighbor.begin(); it3 != neighbors_of_neighbor_of_neighbor.end(); it3++)
                    {
                        Atom* neighbor_of_neighbor_of_neighbor = (*it3);
                        stringstream ss3;
                        ss3 << neighbor_of_neighbor_of_neighbor->GetId();
                        if(ss1.str().compare(ss3.str()) != 0)
{
                            vector<vector<string> > all_atom_type_permutations = CreateAllAtomTypePermutationsforDihedralType(atom->GetAtomType(), neighbor->GetAtomType(),
                                                                                                                              neighbor_of_neighbor->GetAtomType(), neighbor_of_neighbor_of_neighbor->GetAtomType());
                            ParameterFile::DihedralMap dihedrals = parameter_file->GetDihedrals();
                            for(vector<vector<string> >::iterator it4 = all_atom_type_permutations.begin(); it4 != all_atom_type_permutations.end(); it4++)
{
                                vector<string> atom_types = (*it4);
//                                cout << atom_types.at(0) << atom_types.at(1) << atom_types.at(2) << atom_types.at(3) << endl;
                                if(dihedrals[atom_types] != NULL)
{
                                    ParameterFileDihedral* parameter_file_dihedrals = dihedrals[atom_types];
                                    int terms_count = parameter_file_dihedrals->GetTerms().size();
                                    counter += terms_count;
                                    break;
                                }
                            }
                        }
                    }
                }
            }
        }
        ///Improper Dihedrals
        if(neighbors.size() == 3)
        {
            Atom* neighbor1 = neighbors.at(0);
            Atom* neighbor2 = neighbors.at(1);
            Atom* neighbor3 = neighbors.at(2);
            vector<vector<string> > all_improper_dihedrals_atom_type_permutations = CreateAllAtomTypePermutationsforImproperDihedralType(neighbor1->GetAtomType(), neighbor2->GetAtomType(),
                                                                                                                                         neighbor3->GetAtomType(), atom->GetAtomType());
            ParameterFile::DihedralMap dihedrals = parameter_file->GetDihedrals();
            for(vector<vector<string> >::iterator it1 = all_improper_dihedrals_atom_type_permutations.begin(); it1 != all_improper_dihedrals_atom_type_permutations.end(); it1++)
            {
                vector<string> improper_dihedral_permutation = (*it1);
                if(dihedrals[improper_dihedral_permutation] != NULL)
                {
                    ParameterFileDihedral* parameter_file_dihedrals = dihedrals[improper_dihedral_permutation];
                    int terms_count = parameter_file_dihedrals->GetTerms().size();
                    improper_counter += terms_count;
                    break;
                }
            }
        }
    }
//    cout << not_found_counter/2 << " dihedrals not found in parameter file" << endl;
    return counter/2 + improper_counter;
}
int Assembly::CountNumberOfDihedralsExcludingHydrogen (std::string parameter_file_path)
Improper Dihedrals
Definition at line 2736 of file assembly.cc.
References CreateAllAtomTypePermutationsforDihedralType(), CreateAllAtomTypePermutationsforImproperDihedralType(), GetAllAtomsOfAssembly(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), ParameterFileSpace::ParameterFile::GetDihedrals(), MolecularModeling::Atom::GetId(), MolecularModeling::Atom::GetName(), MolecularModeling::Atom::GetNode(), MolecularModeling::AtomNode::GetNodeNeighbors(), and ParameterFileSpace::ParameterFileDihedral::GetTerms().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    ParameterFile* parameter_file = new ParameterFile(parameter_file_path);
    AtomVector atoms = GetAllAtomsOfAssembly();
    int counter = 0;
    int improper_counter = 0;
//    int not_found_counter = 0;
    for(AtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        Atom* atom = (*it);
        stringstream ss;
        ss << atom->GetId();
        string atom_name = atom->GetName();
        AtomNode* atom_node = atom->GetNode();
        AtomVector neighbors = atom_node->GetNodeNeighbors();
        for(AtomVector::iterator it1 = neighbors.begin(); it1 != neighbors.end(); it1++)
        {
            Atom* neighbor = (*it1);
            stringstream ss1;
            ss1 << neighbor->GetId();
            string neighbor_name = neighbor->GetName();
            AtomNode* neighbor_node = neighbor->GetNode();
            AtomVector neighbors_of_neighbor = neighbor_node->GetNodeNeighbors();
            for(AtomVector::iterator it2 = neighbors_of_neighbor.begin(); it2 != neighbors_of_neighbor.end(); it2++)
            {
                Atom* neighbor_of_neighbor = (*it2);
                stringstream ss2;
                ss2 << neighbor_of_neighbor->GetId();
                if(ss.str().compare(ss2.str()) != 0)
                {
                    string neighbor_of_neighbor_name = neighbor_of_neighbor->GetName();
                    AtomNode* neighbor_of_neighbor_node = neighbor_of_neighbor->GetNode();
                    AtomVector neighbors_of_neighbor_of_neighbor = neighbor_of_neighbor_node->GetNodeNeighbors();
                    for(AtomVector::iterator it3 = neighbors_of_neighbor_of_neighbor.begin(); it3 != neighbors_of_neighbor_of_neighbor.end(); it3++)
                    {
                        Atom* neighbor_of_neighbor_of_neighbor = (*it3);
                        stringstream ss3;
                        ss3 << neighbor_of_neighbor_of_neighbor->GetId();
                        if(ss1.str().compare(ss3.str()) != 0)
{
                            string neighbor_of_neighbor_of_neighbor_name = neighbor_of_neighbor_of_neighbor->GetName();
                            if((atom_name.substr(0,1).compare("H") == 0 || (atom_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(atom_name.substr(0,1))))) ||
                                    (neighbor_name.substr(0,1).compare("H") == 0 || (neighbor_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor_name.substr(0,1))))) ||
                                    (neighbor_of_neighbor_name.substr(0,1).compare("H") == 0 || (neighbor_of_neighbor_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor_of_neighbor_name.substr(0,1))))) ||
                                    (neighbor_of_neighbor_of_neighbor_name.substr(0,1).compare("H") == 0 || (neighbor_of_neighbor_of_neighbor_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor_of_neighbor_of_neighbor_name.substr(0,1))))))
                            {}
                            else
{
                                vector<vector<string> > all_atom_type_permutations = CreateAllAtomTypePermutationsforDihedralType(atom->GetAtomType(), neighbor->GetAtomType(),
                                                                                                                                  neighbor_of_neighbor->GetAtomType(), neighbor_of_neighbor_of_neighbor->GetAtomType());
                                ParameterFile::DihedralMap dihedrals = parameter_file->GetDihedrals();
                                for(vector<vector<string> >::iterator it4 = all_atom_type_permutations.begin(); it4 != all_atom_type_permutations.end(); it4++)
{
                                    vector<string> atom_types = (*it4);
                                    if(dihedrals[atom_types] != NULL)
{
                                        ParameterFileDihedral* parameter_file_dihedrals = dihedrals[atom_types];
                                        int terms_count = parameter_file_dihedrals->GetTerms().size();
                                        counter += terms_count;
                                        break;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        ///Improper Dihedrals
        if(neighbors.size() == 3)
        {
            Atom* neighbor1 = neighbors.at(0);
            Atom* neighbor2 = neighbors.at(1);
            Atom* neighbor3 = neighbors.at(2);
            string neighbor1_name = neighbor1->GetName();
            string neighbor2_name = neighbor2->GetName();
            string neighbor3_name = neighbor3->GetName();
            vector<vector<string> > all_improper_dihedrals_atom_type_permutations = CreateAllAtomTypePermutationsforImproperDihedralType(neighbor1->GetAtomType(), neighbor2->GetAtomType(),
                                                                                                          neighbor3->GetAtomType(), atom->GetAtomType());
            ParameterFile::DihedralMap dihedrals = parameter_file->GetDihedrals();
            for(vector<vector<string> >::iterator it1 = all_improper_dihedrals_atom_type_permutations.begin(); it1 != all_improper_dihedrals_atom_type_permutations.end(); it1++)
            {
                vector<string> improper_dihedral_permutation = (*it1);
                if((atom_name.substr(0,1).compare("H") == 0 || (atom_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(atom_name.substr(0,1))))) ||
                        (neighbor1_name.substr(0,1).compare("H") == 0 || (neighbor1_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor1_name.substr(0,1))))) ||
                        (neighbor2_name.substr(0,1).compare("H") == 0 || (neighbor2_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor2_name.substr(0,1))))) ||
                        (neighbor3_name.substr(0,1).compare("H") == 0 || (neighbor3_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor3_name.substr(0,1))))))
                {}
                else
                {
                    if(dihedrals[improper_dihedral_permutation] != NULL)
                    {
                        ParameterFileDihedral* parameter_file_dihedrals = dihedrals[improper_dihedral_permutation];
                        int terms_count = parameter_file_dihedrals->GetTerms().size();
                        improper_counter += terms_count;
                        break;
                    }
                }
            }
        }
    }
//    cout << not_found_counter/2 << " dihedrals not found in parameter file" << endl;
    return counter/2 + improper_counter;
}
int Assembly::CountNumberOfDihedralsIncludingHydrogen (std::string parameter_file_path)
Improper Dihedrals
Definition at line 2633 of file assembly.cc.
References CreateAllAtomTypePermutationsforDihedralType(), CreateAllAtomTypePermutationsforImproperDihedralType(), GetAllAtomsOfAssembly(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), ParameterFileSpace::ParameterFile::GetDihedrals(), MolecularModeling::Atom::GetId(), MolecularModeling::Atom::GetName(), MolecularModeling::Atom::GetNode(), MolecularModeling::AtomNode::GetNodeNeighbors(), and ParameterFileSpace::ParameterFileDihedral::GetTerms().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    ParameterFile* parameter_file = new ParameterFile(parameter_file_path);
    AtomVector atoms = GetAllAtomsOfAssembly();
    int counter = 0;
    int improper_counter = 0;
//    int not_found_counter = 0;
    for(AtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        Atom* atom = (*it);
        stringstream ss;
        ss << atom->GetId();
        string atom_name = atom->GetName();
        AtomNode* atom_node = atom->GetNode();
        AtomVector neighbors = atom_node->GetNodeNeighbors();
        for(AtomVector::iterator it1 = neighbors.begin(); it1 != neighbors.end(); it1++)
        {
            Atom* neighbor = (*it1);
            stringstream ss1;
            ss1 << neighbor->GetId();
            string neighbor_name = neighbor->GetName();
            AtomNode* neighbor_node = neighbor->GetNode();
            AtomVector neighbors_of_neighbor = neighbor_node->GetNodeNeighbors();
            for(AtomVector::iterator it2 = neighbors_of_neighbor.begin(); it2 != neighbors_of_neighbor.end(); it2++)
            {
                Atom* neighbor_of_neighbor = (*it2);
                stringstream ss2;
                ss2 << neighbor_of_neighbor->GetId();
                if(ss.str().compare(ss2.str()) != 0)
                {
                    string neighbor_of_neighbor_name = neighbor_of_neighbor->GetName();
                    AtomNode* neighbor_of_neighbor_node = neighbor_of_neighbor->GetNode();
                    AtomVector neighbors_of_neighbor_of_neighbor = neighbor_of_neighbor_node->GetNodeNeighbors();
                    for(AtomVector::iterator it3 = neighbors_of_neighbor_of_neighbor.begin(); it3 != neighbors_of_neighbor_of_neighbor.end(); it3++)
                    {
                        Atom* neighbor_of_neighbor_of_neighbor = (*it3);
                        stringstream ss3;
                        ss3 << neighbor_of_neighbor_of_neighbor->GetId();
                        if(ss1.str().compare(ss3.str()) != 0)
{
                            string neighbor_of_neighbor_of_neighbor_name = neighbor_of_neighbor_of_neighbor->GetName();
                            if((atom_name.substr(0,1).compare("H") == 0 || (atom_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(atom_name.substr(0,1))))) ||
                                    (neighbor_name.substr(0,1).compare("H") == 0 || (neighbor_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor_name.substr(0,1))))) ||
                                    (neighbor_of_neighbor_name.substr(0,1).compare("H") == 0 || (neighbor_of_neighbor_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor_of_neighbor_name.substr(0,1))))) ||
                                    (neighbor_of_neighbor_of_neighbor_name.substr(0,1).compare("H") == 0 || (neighbor_of_neighbor_of_neighbor_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor_of_neighbor_of_neighbor_name.substr(0,1))))))
{
                                vector<vector<string> > all_atom_type_permutations = CreateAllAtomTypePermutationsforDihedralType(atom->GetAtomType(), neighbor->GetAtomType(),
                                                                                                                                  neighbor_of_neighbor->GetAtomType(), neighbor_of_neighbor_of_neighbor->GetAtomType());
                                ParameterFile::DihedralMap dihedrals = parameter_file->GetDihedrals();
                                for(vector<vector<string> >::iterator it4 = all_atom_type_permutations.begin(); it4 != all_atom_type_permutations.end(); it4++)
{
                                    vector<string> atom_types = (*it4);
                                    if(dihedrals[atom_types] != NULL)
{
                                        ParameterFileDihedral* parameter_file_dihedrals = dihedrals[atom_types];
                                        int terms_count = parameter_file_dihedrals->GetTerms().size();
                                        counter += terms_count;
                                        break;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        ///Improper Dihedrals
        if(neighbors.size() == 3)
        {
            Atom* neighbor1 = neighbors.at(0);
            Atom* neighbor2 = neighbors.at(1);
            Atom* neighbor3 = neighbors.at(2);
            string neighbor1_name = neighbor1->GetName();
            string neighbor2_name = neighbor2->GetName();
            string neighbor3_name = neighbor3->GetName();
            vector<vector<string> > all_improper_dihedrals_atom_type_permutations = CreateAllAtomTypePermutationsforImproperDihedralType(neighbor1->GetAtomType(), neighbor2->GetAtomType(),
                                                                                                          neighbor3->GetAtomType(), atom->GetAtomType());
            ParameterFile::DihedralMap dihedrals = parameter_file->GetDihedrals();
            for(vector<vector<string> >::iterator it1 = all_improper_dihedrals_atom_type_permutations.begin(); it1 != all_improper_dihedrals_atom_type_permutations.end(); it1++)
            {
                vector<string> improper_dihedral_permutation = (*it1);
                if((atom_name.substr(0,1).compare("H") == 0 || (atom_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(atom_name.substr(0,1))))) ||
                        (neighbor1_name.substr(0,1).compare("H") == 0 || (neighbor1_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor1_name.substr(0,1))))) ||
                        (neighbor2_name.substr(0,1).compare("H") == 0 || (neighbor2_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor2_name.substr(0,1))))) ||
                        (neighbor3_name.substr(0,1).compare("H") == 0 || (neighbor3_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor3_name.substr(0,1))))))
                {
                    if(dihedrals[improper_dihedral_permutation] != NULL)
                    {
                        ParameterFileDihedral* parameter_file_dihedrals = dihedrals[improper_dihedral_permutation];
                        int terms_count = parameter_file_dihedrals->GetTerms().size();
                        improper_counter += terms_count;
                        break;
                    }
                }
            }
        }
    }
//    cout << not_found_counter/2 << " dihedrals not found in parameter file" << endl;
    return counter/2 + improper_counter;
}
int Assembly::CountNumberOfDihedralTypes (std::string parameter_file_path)
Improper Dihedrals
Definition at line 2929 of file assembly.cc.
References CreateAllAtomTypePermutationsforDihedralType(), CreateAllAtomTypePermutationsforImproperDihedralType(), GetAllAtomsOfAssembly(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), MolecularModeling::Atom::GetId(), MolecularModeling::Atom::GetNode(), MolecularModeling::AtomNode::GetNodeNeighbors(), and ParameterFileSpace::ParameterFileDihedral::GetTerms().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    vector<string> type_list = vector<string>();
    ParameterFile* parameter_file = new ParameterFile(parameter_file_path);
    AtomVector atoms = GetAllAtomsOfAssembly();
    int counter = 0;
//    int not_found_counter = 0;
    for(AtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        Atom* atom = (*it);
        stringstream ss;
        ss << atom->GetId();
        AtomNode* atom_node = atom->GetNode();
        AtomVector neighbors = atom_node->GetNodeNeighbors();
        for(AtomVector::iterator it1 = neighbors.begin(); it1 != neighbors.end(); it1++)
        {
            Atom* neighbor = (*it1);
            stringstream ss1;
            ss1 << neighbor->GetId();
            AtomNode* neighbor_node = neighbor->GetNode();
            AtomVector neighbors_of_neighbor = neighbor_node->GetNodeNeighbors();
            for(AtomVector::iterator it2 = neighbors_of_neighbor.begin(); it2 != neighbors_of_neighbor.end(); it2++)
            {
                Atom* neighbor_of_neighbor = (*it2);
                stringstream ss2;
                ss2 << neighbor_of_neighbor->GetId();
                if(ss.str().compare(ss2.str()) != 0)
                {
                    AtomNode* neighbor_of_neighbor_node = neighbor_of_neighbor->GetNode();
                    AtomVector neighbors_of_neighbor_of_neighbor = neighbor_of_neighbor_node->GetNodeNeighbors();
                    for(AtomVector::iterator it3 = neighbors_of_neighbor_of_neighbor.begin(); it3 != neighbors_of_neighbor_of_neighbor.end(); it3++)
                    {
                        Atom* neighbor_of_neighbor_of_neighbor = (*it3);
                        stringstream ss3;
                        ss3 << neighbor_of_neighbor_of_neighbor->GetId();
                        if(ss1.str().compare(ss3.str()) != 0)
{
                            vector<vector<string> > all_atom_type_permutations = CreateAllAtomTypePermutationsforDihedralType(atom->GetAtomType(), neighbor->GetAtomType(),
                                                                                                                              neighbor_of_neighbor->GetAtomType(), neighbor_of_neighbor_of_neighbor->GetAtomType());
                            ParameterFile::DihedralMap dihedrals = parameter_file->GetDihedrals();
                            for(vector<vector<string> >::iterator it4 = all_atom_type_permutations.begin(); it4 != all_atom_type_permutations.end(); it4++)
{
                                vector<string> atom_types = (*it4);
                                //                            vector<string> atom_types = vector<string>();
                                //                            atom_types.push_back(atom->GetAtomType());
                                //                            atom_types.push_back(neighbor->GetAtomType());
                                //                            atom_types.push_back(neighbor_of_neighbor->GetAtomType());
                                //                            atom_types.push_back(neighbor_of_neighbor_of_neighbor->GetAtomType());
                                if(dihedrals[atom_types] != NULL)
{
                                    stringstream ss4;
                                    ss4 << atom_types.at(0) << "_" << atom_types.at(1) << "_" << atom_types.at(2) << "_" << atom_types.at(3);
                                    stringstream ss5;
                                    ss5 << atom_types.at(3) << "_" << atom_types.at(2) << "_" << atom_types.at(1) << "_" << atom_types.at(0);
                                    if(find(type_list.begin(), type_list.end(), ss4.str()) == type_list.end() &&
                                            find(type_list.begin(), type_list.end(), ss5.str()) == type_list.end())
{
                                        type_list.push_back(ss4.str());
                                        ParameterFileDihedral* parameter_file_dihedrals = dihedrals[atom_types];
                                        int terms_count = parameter_file_dihedrals->GetTerms().size();
                                        counter += terms_count;
                                        break;
                                    }
                                }
//                                else
//                                {
//                                    atom_types[0] = neighbor_of_neighbor_of_neighbor->GetAtomType();
//                                    atom_types[1] = neighbor_of_neighbor->GetAtomType();
//                                    atom_types[2] = neighbor->GetAtomType();
//                                    atom_types[3] = atom->GetAtomType();
//                                    if(dihedrals[atom_types] != NULL)
//                                    {
//                                        stringstream ss6;
//                                        ss6 << atom->GetAtomType() << "_" << neighbor->GetAtomType() << "_" << neighbor_of_neighbor->GetAtomType() << "_" << neighbor_of_neighbor_of_neighbor->GetAtomType();
//                                        stringstream ss7;
//                                        ss7 << neighbor_of_neighbor_of_neighbor->GetAtomType() << "_" << neighbor_of_neighbor->GetAtomType() << "_" << neighbor->GetAtomType() << "_" << atom->GetAtomType();
//                                        if(find(type_list.begin(), type_list.end(), ss6.str()) == type_list.end() &&
//                                                find(type_list.begin(), type_list.end(), ss7.str()) == type_list.end())
//                                        {
//                                            type_list.push_back(ss7.str());
//                                            ParameterFileDihedral* parameter_file_dihedrals = dihedrals[atom_types];
//                                            int terms_count = parameter_file_dihedrals->GetTerms().size();
//                                            counter += terms_count;
//                                        }
//                                    }
//                                    else
//                                    {
//                                        not_found_counter++;
//                                    }
//                                }
                            }
                        }
                    }
                }
            }
        }
        ///Improper Dihedrals
        if(neighbors.size() == 3)
        {
            Atom* neighbor1 = neighbors.at(0);
            Atom* neighbor2 = neighbors.at(1);
            Atom* neighbor3 = neighbors.at(2);
            vector<vector<string> > all_improper_dihedrals_atom_type_permutations = CreateAllAtomTypePermutationsforImproperDihedralType(neighbor1->GetAtomType(), neighbor2->GetAtomType(),
                                                                                                                                         neighbor3->GetAtomType(), atom->GetAtomType());
            for(vector<vector<string> >::iterator it1 = all_improper_dihedrals_atom_type_permutations.begin(); it1 != all_improper_dihedrals_atom_type_permutations.end(); it1++)
            {
                vector<string> improper_dihedral_permutation = (*it1);
                ParameterFile::DihedralMap dihedrals = parameter_file->GetDihedrals();
                if(dihedrals[improper_dihedral_permutation] != NULL)
                {
                    stringstream ss;
                    ss << improper_dihedral_permutation.at(0) << "_" << improper_dihedral_permutation.at(1) << "_" << improper_dihedral_permutation.at(2) << "_" << improper_dihedral_permutation.at(3);
                    stringstream ss1;
                    ss1 << improper_dihedral_permutation.at(3) << "_" << improper_dihedral_permutation.at(2) << "_" << improper_dihedral_permutation.at(1) << "_" << improper_dihedral_permutation.at(0);
                    if(find(type_list.begin(), type_list.end(), ss.str()) == type_list.end() &&
                            find(type_list.begin(), type_list.end(), ss1.str()) == type_list.end())
                    {
                        type_list.push_back(ss.str());
                        ParameterFileDihedral* parameter_file_dihedrals = dihedrals[improper_dihedral_permutation];
                        int terms_count = parameter_file_dihedrals->GetTerms().size();
                        counter += terms_count;
                        break;
                    }
                }
            }
        }
    }
//    cout << not_found_counter << " dihedrals not found in parameter file" << endl;
//    cout << type_list.size() << endl;
    return counter;
}
int Assembly::CountNumberOfExcludedAtoms ()
Definition at line 3371 of file assembly.cc.
References GetAllAtomsOfAssembly(), MolecularModeling::Atom::GetId(), MolecularModeling::Atom::GetNode(), and MolecularModeling::AtomNode::GetNodeNeighbors().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    AtomVector atoms = GetAllAtomsOfAssembly();
    vector<string> excluded_atom_list = vector<string>();
    for(AtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        Atom* atom = (*it);
        stringstream ss;
        ss << atom->GetId();
        AtomNode* node = atom->GetNode();
        AtomVector neighbors = node->GetNodeNeighbors();
        for(AtomVector::iterator it1 = neighbors.begin(); it1 != neighbors.end(); it1++)
        {
            Atom* neighbor = (*it1);
            stringstream ss1;
            ss1 << neighbor->GetId();
            stringstream first_order_interaction;
            stringstream reverse_first_order_interaction;
            first_order_interaction << ss.str() << "-" << ss1.str();
            reverse_first_order_interaction << ss1.str() << "-" << ss.str();
            if(find(excluded_atom_list.begin(), excluded_atom_list.end(), first_order_interaction.str()) == excluded_atom_list.end() &&
                    find(excluded_atom_list.begin(), excluded_atom_list.end(), reverse_first_order_interaction.str()) == excluded_atom_list.end())
                excluded_atom_list.push_back(first_order_interaction.str());
            AtomNode* neighbor_node = neighbor->GetNode();
            AtomVector neighbor_of_neighbors = neighbor_node->GetNodeNeighbors();
            for(AtomVector::iterator it2 = neighbor_of_neighbors.begin(); it2 != neighbor_of_neighbors.end(); it2++)
            {
                Atom* neighbor_of_neighbor = (*it2);
                stringstream ss2;
                ss2 << neighbor_of_neighbor->GetId();
                if(ss.str().compare(ss2.str()) != 0)
                {
                    stringstream second_order_interaction;
                    stringstream reverse_second_order_interaction;
                    second_order_interaction << ss.str() << "-" << ss2.str();
                    reverse_second_order_interaction << ss2.str() << "-" << ss.str();
                    if(find(excluded_atom_list.begin(), excluded_atom_list.end(), second_order_interaction.str()) == excluded_atom_list.end() &&
                            find(excluded_atom_list.begin(), excluded_atom_list.end(), reverse_second_order_interaction.str()) == excluded_atom_list.end())
                        excluded_atom_list.push_back(second_order_interaction.str());
                    AtomNode* neighbor_of_neighbor_node = neighbor_of_neighbor->GetNode();
                    AtomVector neighbor_of_neighbor_of_neighbors = neighbor_of_neighbor_node->GetNodeNeighbors();
                    for(AtomVector::iterator it3 = neighbor_of_neighbor_of_neighbors.begin(); it3 != neighbor_of_neighbor_of_neighbors.end(); it3++)
                    {
                        Atom* neighbor_of_neighbor_of_neighbor = (*it3);
                        stringstream ss3;
                        ss3 << neighbor_of_neighbor_of_neighbor->GetId();
                        if(ss1.str().compare(ss3.str()) != 0)
{
                            stringstream third_order_interaction;
                            stringstream reverse_third_order_interaction;
                            third_order_interaction << ss.str() << "-" << ss3.str();
                            reverse_third_order_interaction << ss3.str() << "-" << ss.str();
                            if(find(excluded_atom_list.begin(), excluded_atom_list.end(), third_order_interaction.str()) == excluded_atom_list.end() &&
                                    find(excluded_atom_list.begin(), excluded_atom_list.end(), reverse_third_order_interaction.str()) == excluded_atom_list.end())
                                excluded_atom_list.push_back(third_order_interaction.str());
                        }
                    }
                }
            }
        }
    }
    return excluded_atom_list.size();
}
int Assembly::CountNumberOfResidues ()
Definition at line 2362 of file assembly.cc.
References CountNumberOfResidues().
Referenced by BuildTopologyFileStructureFromAssembly(), and CountNumberOfResidues().
{
    int counter = 0;
    for(AssemblyVector::iterator it = assemblies_.begin(); it != assemblies_.end(); it++)
    {
        Assembly* assembly = (*it);
        counter += assembly->CountNumberOfResidues();
    }
    counter += residues_.size();
    return counter;
}
vector< vector< string > > Assembly::CreateAllAtomTypePermutationsforDihedralType (std::string atom_type1, std::string atom_type2, std::string atom_type3, std::string atom_type4)
Permutations w/ one X
Permutations w/ two X
Permutations w/ three X
Definition at line 3065 of file assembly.cc.
Referenced by CountNumberOfDihedrals(), CountNumberOfDihedralsExcludingHydrogen(), CountNumberOfDihedralsIncludingHydrogen(), CountNumberOfDihedralTypes(), ExtractTopologyDihedralsFromAssembly(), and ExtractTopologyDihedralTypesFromAssembly().
{
    vector<vector<string> > all_permutations = vector<vector<string> >();
    vector<string> normal_order = vector<string>();
    vector<string> reverse_order = vector<string>();
    normal_order.push_back(atom_type1);
    normal_order.push_back(atom_type2);
    normal_order.push_back(atom_type3);
    normal_order.push_back(atom_type4);
    reverse_order.push_back(atom_type4);
    reverse_order.push_back(atom_type3);
    reverse_order.push_back(atom_type2);
    reverse_order.push_back(atom_type1);
    all_permutations.push_back(normal_order);
    all_permutations.push_back(reverse_order);
    ///Permutations w/ one X
    for(int i = 0; i < 4; i++)
    {
        normal_order.clear();
        normal_order.push_back(atom_type1);
        normal_order.push_back(atom_type2);
        normal_order.push_back(atom_type3);
        normal_order.push_back(atom_type4);
        normal_order.at(i) = "X";
        reverse_order.clear();
        reverse_order.push_back(atom_type4);
        reverse_order.push_back(atom_type3);
        reverse_order.push_back(atom_type2);
        reverse_order.push_back(atom_type1);
        reverse_order.at(i) = "X";
        all_permutations.push_back(normal_order);
        all_permutations.push_back(reverse_order);
    }
    ///Permutations w/ two X
    for(int i = 0; i < 3; i++)
        for(int j = i+1; j < 4; j++)
        {
            normal_order.clear();
            normal_order.push_back(atom_type1);
            normal_order.push_back(atom_type2);
            normal_order.push_back(atom_type3);
            normal_order.push_back(atom_type4);
            normal_order.at(i) = "X";
            normal_order.at(j) = "X";
            reverse_order.clear();
            reverse_order.push_back(atom_type4);
            reverse_order.push_back(atom_type3);
            reverse_order.push_back(atom_type2);
            reverse_order.push_back(atom_type1);
            reverse_order.at(i) = "X";
            reverse_order.at(j) = "X";
            all_permutations.push_back(normal_order);
            all_permutations.push_back(reverse_order);
        }
    ///Permutations w/ three X
    for(int i = 0; i < 2; i++)
        for(int j = i+1; j < 3; j++)
            for(int k = j+1; k < 4; k++)
            {
                normal_order.clear();
                normal_order.push_back(atom_type1);
                normal_order.push_back(atom_type2);
                normal_order.push_back(atom_type3);
                normal_order.push_back(atom_type4);
                normal_order.at(i) = "X";
                normal_order.at(j) = "X";
                normal_order.at(k) = "X";
                reverse_order.clear();
                reverse_order.push_back(atom_type4);
                reverse_order.push_back(atom_type3);
                reverse_order.push_back(atom_type2);
                reverse_order.push_back(atom_type1);
                reverse_order.at(i) = "X";
                reverse_order.at(j) = "X";
                reverse_order.at(k) = "X";
                all_permutations.push_back(normal_order);
                all_permutations.push_back(reverse_order);
            }
    return all_permutations;
}
vector< vector< string > > Assembly::CreateAllAtomTypePermutationsforImproperDihedralType (std::string atom_type1, std::string atom_type2, std::string atom_type3, std::string atom_type4)
Permutations w/ one X
Permutations w/ two X
Permutations w/ three X
Definition at line 3147 of file assembly.cc.
Referenced by CountNumberOfDihedrals(), CountNumberOfDihedralsExcludingHydrogen(), CountNumberOfDihedralsIncludingHydrogen(), CountNumberOfDihedralTypes(), ExtractTopologyDihedralsFromAssembly(), and ExtractTopologyDihedralTypesFromAssembly().
{
    vector<vector<string> > all_permutations = vector<vector<string> >();
    vector<string> order1 = vector<string>();
    vector<string> order2 = vector<string>();
    vector<string> order3 = vector<string>();
    vector<string> reverse_order1 = vector<string>();
    vector<string> reverse_order2 = vector<string>();
    vector<string> reverse_order3 = vector<string>();
    order1.push_back(neighbor1_type);
    order1.push_back(neighbor2_type);
    order1.push_back(atom_type);
    order1.push_back(neighbor3_type);
    reverse_order1.push_back(neighbor3_type);
    reverse_order1.push_back(atom_type);
    reverse_order1.push_back(neighbor2_type);
    reverse_order1.push_back(neighbor1_type);
    order2.push_back(neighbor1_type);
    order2.push_back(atom_type);
    order2.push_back(neighbor3_type);
    order2.push_back(neighbor2_type);
    reverse_order2.push_back(neighbor2_type);
    reverse_order2.push_back(neighbor3_type);
    reverse_order2.push_back(atom_type);
    reverse_order2.push_back(neighbor1_type);
    order3.push_back(neighbor1_type);
    order3.push_back(neighbor3_type);
    order3.push_back(atom_type);
    order3.push_back(neighbor2_type);
    reverse_order3.push_back(neighbor2_type);
    reverse_order3.push_back(atom_type);
    reverse_order3.push_back(neighbor3_type);
    reverse_order3.push_back(neighbor1_type);
    all_permutations.push_back(order1);
    all_permutations.push_back(order2);
    all_permutations.push_back(order3);
    all_permutations.push_back(reverse_order1);
    all_permutations.push_back(reverse_order2);
    all_permutations.push_back(reverse_order3);
    ///Permutations w/ one X
    for(int i = 0; i < 4; i++)
    {
        order1.clear();
        order2.clear();
        order3.clear();
        reverse_order1.clear();
        reverse_order2.clear();
        reverse_order3.clear();
        order1.push_back(neighbor1_type);
        order1.push_back(neighbor2_type);
        order1.push_back(atom_type);
        order1.push_back(neighbor3_type);
        order1.at(i) = "X";
        reverse_order1.push_back(neighbor3_type);
        reverse_order1.push_back(atom_type);
        reverse_order1.push_back(neighbor2_type);
        reverse_order1.push_back(neighbor1_type);
        reverse_order1.at(i) = "X";
        order2.push_back(neighbor1_type);
        order2.push_back(atom_type);
        order2.push_back(neighbor3_type);
        order2.push_back(neighbor2_type);
        order2.at(i) = "X";
        reverse_order2.push_back(neighbor2_type);
        reverse_order2.push_back(neighbor3_type);
        reverse_order2.push_back(atom_type);
        reverse_order2.push_back(neighbor1_type);
        reverse_order2.at(i) = "X";
        order3.push_back(neighbor1_type);
        order3.push_back(neighbor3_type);
        order3.push_back(atom_type);
        order3.push_back(neighbor2_type);
        order3.at(i) = "X";
        reverse_order3.push_back(neighbor2_type);
        reverse_order3.push_back(atom_type);
        reverse_order3.push_back(neighbor3_type);
        reverse_order3.push_back(neighbor1_type);
        reverse_order3.at(i) = "X";
        all_permutations.push_back(order1);
        all_permutations.push_back(reverse_order1);
        all_permutations.push_back(order2);
        all_permutations.push_back(reverse_order2);
        all_permutations.push_back(order3);
        all_permutations.push_back(reverse_order3);
    }
    ///Permutations w/ two X
    for(int i = 0; i < 3; i++)
        for(int j = i+1; j < 4; j++)
        {
            order1.clear();
            order2.clear();
            order3.clear();
            reverse_order1.clear();
            reverse_order2.clear();
            reverse_order3.clear();
            order1.push_back(neighbor1_type);
            order1.push_back(neighbor2_type);
            order1.push_back(atom_type);
            order1.push_back(neighbor3_type);
            order1.at(i) = "X";
            order1.at(j) = "X";
            reverse_order1.push_back(neighbor3_type);
            reverse_order1.push_back(atom_type);
            reverse_order1.push_back(neighbor2_type);
            reverse_order1.push_back(neighbor1_type);
            reverse_order1.at(i) = "X";
            order2.push_back(neighbor1_type);
            order2.push_back(atom_type);
            order2.push_back(neighbor3_type);
            order2.push_back(neighbor2_type);
            order2.at(i) = "X";
            order2.at(j) = "X";
            reverse_order2.push_back(neighbor2_type);
            reverse_order2.push_back(neighbor3_type);
            reverse_order2.push_back(atom_type);
            reverse_order2.push_back(neighbor1_type);
            reverse_order2.at(i) = "X";
            reverse_order2.at(j) = "X";
            order3.push_back(neighbor1_type);
            order3.push_back(neighbor3_type);
            order3.push_back(atom_type);
            order3.push_back(neighbor2_type);
            order3.at(i) = "X";
            order3.at(j) = "X";
            reverse_order3.push_back(neighbor2_type);
            reverse_order3.push_back(atom_type);
            reverse_order3.push_back(neighbor3_type);
            reverse_order3.push_back(neighbor1_type);
            reverse_order3.at(i) = "X";
            reverse_order3.at(j) = "X";
            all_permutations.push_back(order1);
            all_permutations.push_back(reverse_order1);
            all_permutations.push_back(order2);
            all_permutations.push_back(reverse_order2);
            all_permutations.push_back(order3);
            all_permutations.push_back(reverse_order3);;
        }
    ///Permutations w/ three X
    for(int i = 0; i < 2; i++)
        for(int j = i+1; j < 3; j++)
            for(int k = j+1; k < 4; k++)
            {
                order1.clear();
                order2.clear();
                order3.clear();
                reverse_order1.clear();
                reverse_order2.clear();
                reverse_order3.clear();
                order1.push_back(neighbor1_type);
                order1.push_back(neighbor2_type);
                order1.push_back(atom_type);
                order1.push_back(neighbor3_type);
                order1.at(i) = "X";
                order1.at(j) = "X";
                order1.at(k) = "X";
                reverse_order1.push_back(neighbor3_type);
                reverse_order1.push_back(atom_type);
                reverse_order1.push_back(neighbor2_type);
                reverse_order1.push_back(neighbor1_type);
                reverse_order1.at(i) = "X";
                order2.push_back(neighbor1_type);
                order2.push_back(atom_type);
                order2.push_back(neighbor3_type);
                order2.push_back(neighbor2_type);
                order2.at(i) = "X";
                order2.at(j) = "X";
                order2.at(k) = "X";
                reverse_order2.push_back(neighbor2_type);
                reverse_order2.push_back(neighbor3_type);
                reverse_order2.push_back(atom_type);
                reverse_order2.push_back(neighbor1_type);
                reverse_order2.at(i) = "X";
                reverse_order2.at(j) = "X";
                reverse_order2.at(k) = "X";
                order3.push_back(neighbor1_type);
                order3.push_back(neighbor3_type);
                order3.push_back(atom_type);
                order3.push_back(neighbor2_type);
                order3.at(i) = "X";
                order3.at(j) = "X";
                order3.at(k) = "X";
                reverse_order3.push_back(neighbor2_type);
                reverse_order3.push_back(atom_type);
                reverse_order3.push_back(neighbor3_type);
                reverse_order3.push_back(neighbor1_type);
                reverse_order3.at(i) = "X";
                reverse_order3.at(j) = "X";
                reverse_order3.at(k) = "X";
                all_permutations.push_back(order1);
                all_permutations.push_back(reverse_order1);
                all_permutations.push_back(order2);
                all_permutations.push_back(reverse_order2);
                all_permutations.push_back(order3);
                all_permutations.push_back(reverse_order3);;
            }
    return all_permutations;
}
void Assembly::ExtractPdbModelCardFromAssembly (PdbFileSpace::PdbModelResidueSet * residue_set, int & serial_number, int & sequence_number, int model_number)
Definition at line 760 of file assembly.cc.
References PdbFileSpace::PdbModelResidueSet::AddAtom(), PdbFileSpace::PdbModelResidueSet::AddHeterogenAtom(), gmml::dNotSet, GetAssemblies(), MolecularModeling::Residue::GetAtoms(), MolecularModeling::MolecularDynamicAtom::GetCharge(), MolecularModeling::Atom::GetCoordinates(), MolecularModeling::Atom::GetDescription(), MolecularModeling::Atom::GetElementSymbol(), MolecularModeling::Residue::GetName(), MolecularModeling::Atom::GetName(), MolecularModeling::Atom::GetResidue(), GetResidues(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbHeterogenAtomCard::SetHeterogenAtoms(), and gmml::Split().
Referenced by BuildPdbFileStructureFromAssembly().
{
    cout << "Creating PDB file" << endl;
    for(AssemblyVector::iterator it = this->assemblies_.begin(); it != this->assemblies_.end(); it++)
    {
        Assembly* assembly = (*it);
        AssemblyVector assemblies = assembly->GetAssemblies();
        for(AssemblyVector::iterator it1 = assemblies.begin(); it1 != assemblies.end(); it1++)
        {
            ExtractPdbModelCardFromAssembly(residue_set, serial_number, sequence_number, model_number);
        }
        PdbAtomCard* atom_card = new PdbAtomCard();
        PdbHeterogenAtomCard* het_atom_card = new PdbHeterogenAtomCard();
        PdbAtomCard::PdbAtomMap atom_map = PdbAtomCard::PdbAtomMap();
        PdbHeterogenAtomCard::PdbHeterogenAtomMap het_atom_map = PdbHeterogenAtomCard::PdbHeterogenAtomMap();
        ResidueVector residues = assembly->GetResidues();
        for(ResidueVector::iterator it1 = residues.begin(); it1 != residues.end(); it1++)
        {
            Residue* residue = (*it1);
            AtomVector atoms = residue->GetAtoms();
            for(AtomVector::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                Atom* atom = (*it2);
                vector<string> dscr = Split(atom->GetDescription(), ";");
                stringstream ss;
                ss << fixed << setprecision(1) << atom->GetCharge();
                PdbAtom* pdb_atom = new PdbAtom(serial_number, atom->GetName(), ' ', atom->GetResidue()->GetName(), ' ', sequence_number, ' ',
                                                *((atom->GetCoordinates()).at(model_number)), dNotSet, dNotSet, atom->GetElementSymbol(), ss.str());
                if(find(dscr.begin(), dscr.end(), "Atom") != dscr.end())
                {
                    atom_map[serial_number] = pdb_atom;
                    serial_number++;
                }
                else if(find(dscr.begin(), dscr.end(), "Het") != dscr.end())
                {
                    het_atom_map[serial_number] = pdb_atom;
                    serial_number++;
                }
            }
            sequence_number++;
        }
        atom_card->SetAtoms(atom_map);
        het_atom_card->SetHeterogenAtoms(het_atom_map);
        residue_set->AddAtom(atom_card);
        residue_set->AddHeterogenAtom(het_atom_card);
    }
    PdbAtomCard* atom_card = new PdbAtomCard();
    PdbHeterogenAtomCard* het_atom_card = new PdbHeterogenAtomCard();
    PdbAtomCard::PdbAtomMap atom_map = PdbAtomCard::PdbAtomMap();
    PdbHeterogenAtomCard::PdbHeterogenAtomMap het_atom_map = PdbHeterogenAtomCard::PdbHeterogenAtomMap();
    for(ResidueVector::iterator it1 = residues_.begin(); it1 != residues_.end(); it1++)
    {
        Residue* residue = (*it1);
        AtomVector atoms = residue->GetAtoms();
        for(AtomVector::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
        {
            Atom* atom = (*it2);
            vector<string> dscr = Split(atom->GetDescription(), ";");
            stringstream ss;
            ss << fixed << setprecision(1) << atom->GetCharge();
            PdbAtom* pdb_atom = new PdbAtom(serial_number, atom->GetName(), ' ', atom->GetResidue()->GetName(), ' ', sequence_number, ' ',
                                            *((atom->GetCoordinates()).at(model_number)), dNotSet, dNotSet, atom->GetElementSymbol(), ss.str());
            if(find(dscr.begin(), dscr.end(), "Atom") != dscr.end())
            {
                atom_map[serial_number] = pdb_atom;
                serial_number++;
            }
            else if(find(dscr.begin(), dscr.end(), "Het") != dscr.end())
            {
                het_atom_map[serial_number] = pdb_atom;
                serial_number++;
            }
        }
        sequence_number++;
    }
    atom_card->SetAtoms(atom_map);
    het_atom_card->SetHeterogenAtoms(het_atom_map);
    residue_set->AddAtom(atom_card);
    residue_set->AddHeterogenAtom(het_atom_card);
}
void Assembly::ExtractTopologyAnglesFromAssembly (Atom * assembly_atom, Atom * neighbor, Atom * neighbor_of_neighbor, std::vector< std::vector< std::string > > & inserted_angles, std::vector< std::vector< std::string > > & inserted_angle_types, TopologyFileSpace::TopologyFile * topology_file)
Definition at line 1340 of file assembly.cc.
References TopologyFileSpace::TopologyFile::AddAngle(), TopologyFileSpace::TopologyFile::GetAngleTypeByIndex(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), MolecularModeling::Residue::GetName(), MolecularModeling::Atom::GetName(), MolecularModeling::Atom::GetResidue(), TopologyFileSpace::TopologyAngle::SetAnlgeType(), and TopologyFileSpace::TopologyAngle::SetIncludingHydrogen().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    vector<string> angle_type = vector<string>();
    vector<string> reverse_angle_type = vector<string>();
    angle_type.push_back(assembly_atom->GetAtomType());
    angle_type.push_back(neighbor->GetAtomType());
    angle_type.push_back(neighbor_of_neighbor->GetAtomType());
    reverse_angle_type.push_back(neighbor_of_neighbor->GetAtomType());
    reverse_angle_type.push_back(neighbor->GetAtomType());
    reverse_angle_type.push_back(assembly_atom->GetAtomType());
    vector<string> angle_atom_names = vector<string>();
    vector<string> reverse_angle_atom_names = vector<string>();
    angle_atom_names.push_back(assembly_atom->GetName());
    angle_atom_names.push_back(neighbor->GetName());
    angle_atom_names.push_back(neighbor_of_neighbor->GetName());
    reverse_angle_atom_names.push_back(neighbor_of_neighbor->GetName());
    reverse_angle_atom_names.push_back(neighbor->GetName());
    reverse_angle_atom_names.push_back(assembly_atom->GetName());
    vector<string> residue_names = vector<string>();
    vector<string> reverse_residue_names = vector<string>();
    residue_names.push_back(assembly_atom->GetResidue()->GetName());
    residue_names.push_back(neighbor->GetResidue()->GetName());
    residue_names.push_back(neighbor_of_neighbor->GetResidue()->GetName());
    reverse_residue_names.push_back(neighbor_of_neighbor->GetResidue()->GetName());
    reverse_residue_names.push_back(neighbor->GetResidue()->GetName());
    reverse_residue_names.push_back(assembly_atom->GetResidue()->GetName());
    vector<string> angle = vector<string>();
    vector<string> reverse_angle = vector<string>();
    stringstream ss;
    ss << residue_names.at(0) << ":" << angle_atom_names.at(0);
    stringstream ss1;
    ss1 << residue_names.at(1) << ":" << angle_atom_names.at(1);
    stringstream ss2;
    ss2 << residue_names.at(2) << ":" << angle_atom_names.at(2);
    angle.push_back(ss.str());
    angle.push_back(ss1.str());
    angle.push_back(ss2.str());
    reverse_angle.push_back(ss2.str());
    reverse_angle.push_back(ss1.str());
    reverse_angle.push_back(ss.str());
    if(find(inserted_angles.begin(), inserted_angles.end(), angle) == inserted_angles.end() &&
            find(inserted_angles.begin(), inserted_angles.end(), reverse_angle) == inserted_angles.end())
    {
        TopologyAngle* topology_angle;
        if(find(inserted_angles.begin(), inserted_angles.end(), angle) == inserted_angles.end())
        {
            topology_angle = new TopologyAngle(angle_atom_names, residue_names);
            inserted_angles.push_back(angle);
        }
        else if (find(inserted_angles.begin(), inserted_angles.end(), reverse_angle) == inserted_angles.end())
        {
            topology_angle = new TopologyAngle(reverse_angle_atom_names, reverse_residue_names);
            inserted_angles.push_back(reverse_angle);
        }
        if((assembly_atom->GetName().substr(0,1).compare("H") == 0 ||
            (assembly_atom->GetName().substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(assembly_atom->GetName().substr(0,1)))))
                || (neighbor->GetName().substr(0,1).compare("H") == 0 ||
                    (neighbor->GetName().substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor->GetName().substr(0,1)))))
                ||(neighbor_of_neighbor->GetName().substr(0,1).compare("H") == 0 ||
                   (neighbor_of_neighbor->GetName().substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor_of_neighbor->GetName().substr(0,1))))))
            topology_angle->SetIncludingHydrogen(true);
        else
            topology_angle->SetIncludingHydrogen(false);
        int index = 0;
        if(find(inserted_angle_types.begin(), inserted_angle_types.end(), angle_type) != inserted_angle_types.end())
            index = distance(inserted_angle_types.begin(), find(inserted_angle_types.begin(), inserted_angle_types.end(), angle_type));
        else if(find(inserted_angle_types.begin(), inserted_angle_types.end(), reverse_angle_type) != inserted_angle_types.end())
            index = distance(inserted_angle_types.begin(), find(inserted_angle_types.begin(), inserted_angle_types.end(), reverse_angle_type));
        else
        {
            cout << angle_type.at(0) << "-" << angle_type.at(1) << "-" << angle_type.at(2) << " angle type does not exist in the parameter files" << endl;
            return;
        }
        topology_angle->SetAnlgeType(topology_file->GetAngleTypeByIndex(index));
        topology_file->AddAngle(topology_angle);
    }
}
void Assembly::ExtractTopologyAngleTypesFromAssembly (Atom * assembly_atom, Atom * neighbor, Atom * neighbor_of_neighbor, std::vector< std::vector< std::string > > & inserted_angle_types, int & angle_type_counter, TopologyFileSpace::TopologyFile * topology_file, ParameterFileSpace::ParameterFile::AngleMap & angles)
Definition at line 1300 of file assembly.cc.
References TopologyFileSpace::TopologyFile::AddAngleType(), ParameterFileSpace::ParameterFileAngle::GetAngle(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), ParameterFileSpace::ParameterFileAngle::GetForceConstant(), TopologyFileSpace::TopologyAngleType::SetEquilibriumValue(), TopologyFileSpace::TopologyAngleType::SetForceConstant(), and TopologyFileSpace::TopologyAngleType::SetIndex().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    vector<string> angle_type = vector<string>();
    vector<string> reverse_angle_type = vector<string>();
    angle_type.push_back(assembly_atom->GetAtomType());
    angle_type.push_back(neighbor->GetAtomType());
    angle_type.push_back(neighbor_of_neighbor->GetAtomType());
    reverse_angle_type.push_back(neighbor_of_neighbor->GetAtomType());
    reverse_angle_type.push_back(neighbor->GetAtomType());
    reverse_angle_type.push_back(assembly_atom->GetAtomType());
    if(find(inserted_angle_types.begin(), inserted_angle_types.end(), angle_type) == inserted_angle_types.end() &&
            find(inserted_angle_types.begin(), inserted_angle_types.end(), reverse_angle_type) == inserted_angle_types.end())
    {
        ParameterFileAngle* parameter_file_angle;
        if(angles.find(angle_type) != angles.end())
        {
            parameter_file_angle = angles[angle_type];
            inserted_angle_types.push_back(angle_type);
        }
        else if(angles.find(reverse_angle_type) != angles.end())
        {
            parameter_file_angle = angles[reverse_angle_type];
            inserted_angle_types.push_back(reverse_angle_type);
        }
        else
        {
            cout << angle_type.at(0) << "-" << angle_type.at(1) << "-" << angle_type.at(2) << " angle type does not exist in the parameter files" << endl;
            return;
        }
        TopologyAngleType* topology_angle_type = new TopologyAngleType();
        topology_angle_type->SetForceConstant(parameter_file_angle->GetForceConstant());
        topology_angle_type->SetEquilibriumValue(parameter_file_angle->GetAngle());
        topology_angle_type->SetIndex(angle_type_counter);
        angle_type_counter++;
        topology_file->AddAngleType(topology_angle_type);
    }
}
void Assembly::ExtractTopologyBondsFromAssembly (std::vector< std::vector< std::string > > & inserted_bonds, std::vector< std::vector< std::string > > & inserted_bond_tyoes, Atom * assembly_atom, Atom * neighbor, TopologyFileSpace::TopologyFile * topology_file)
Definition at line 1227 of file assembly.cc.
References TopologyFileSpace::TopologyFile::AddBond(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), TopologyFileSpace::TopologyFile::GetBondTypeByIndex(), MolecularModeling::Atom::GetId(), MolecularModeling::Residue::GetName(), MolecularModeling::Atom::GetName(), MolecularModeling::Atom::GetResidue(), TopologyFileSpace::TopologyBond::SetBondType(), and TopologyFileSpace::TopologyBond::SetIncludingHydrogen().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    vector<string> atom_pair_type = vector<string>();
    vector<string> reverse_atom_pair_type = vector<string>();
    stringstream key2;
    key2 << neighbor->GetId();
    atom_pair_type.push_back(assembly_atom->GetAtomType());
    atom_pair_type.push_back(neighbor->GetAtomType());
    reverse_atom_pair_type.push_back(neighbor->GetAtomType());
    reverse_atom_pair_type.push_back(assembly_atom->GetAtomType());
    vector<string> atom_pair_name = vector<string>();;
    vector<string> reverse_atom_pair_name = vector<string>();;
    atom_pair_name.push_back(assembly_atom->GetName());
    atom_pair_name.push_back(neighbor->GetName());
    reverse_atom_pair_name.push_back(neighbor->GetName());
    reverse_atom_pair_name.push_back(assembly_atom->GetName());
    vector<string> residue_names = vector<string>();;
    vector<string> reverse_residue_names = vector<string>();;
    residue_names.push_back(assembly_atom->GetResidue()->GetName());
    residue_names.push_back(neighbor->GetResidue()->GetName());
    reverse_residue_names.push_back(neighbor->GetResidue()->GetName());
    reverse_residue_names.push_back(assembly_atom->GetResidue()->GetName());
    vector<string> bond = vector<string>();;
    vector<string> reverse_bond = vector<string>();;
    stringstream ss;
    ss << residue_names.at(0) << ":" << atom_pair_name.at(0);
    stringstream ss1;
    ss1 << residue_names.at(1) << ":" << atom_pair_name.at(1);
    bond.push_back(ss.str());
    bond.push_back(ss1.str());
    reverse_bond.push_back(ss1.str());
    reverse_bond.push_back(ss.str());
    if(find(inserted_bonds.begin(), inserted_bonds.end(), bond) == inserted_bonds.end() &&
            find(inserted_bonds.begin(), inserted_bonds.end(), reverse_bond) == inserted_bonds.end())
    {
        TopologyBond* topology_bond;
        if(find(inserted_bonds.begin(), inserted_bonds.end(), bond) == inserted_bonds.end())
        {
            topology_bond = new TopologyBond(atom_pair_name, residue_names);
            inserted_bonds.push_back(bond);
        }
        else if (find(inserted_bonds.begin(), inserted_bonds.end(), reverse_bond) == inserted_bonds.end())
        {
            topology_bond = new TopologyBond(reverse_atom_pair_name, reverse_residue_names);
            inserted_bonds.push_back(reverse_bond);
        }
        if((assembly_atom->GetName().substr(0,1).compare("H") == 0 ||
            (assembly_atom->GetName().substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(assembly_atom->GetName().substr(0,1)))))
                || (neighbor->GetName().substr(0,1).compare("H") == 0 ||
                    (neighbor->GetName().substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor->GetName().substr(0,1))))))
            topology_bond->SetIncludingHydrogen(true);
        else
            topology_bond->SetIncludingHydrogen(false);
        int index = 0;
        if(find(inserted_bond_types.begin(), inserted_bond_types.end(), atom_pair_type) != inserted_bond_types.end())
            index = distance(inserted_bond_types.begin(), find(inserted_bond_types.begin(), inserted_bond_types.end(), atom_pair_type));
        else if(find(inserted_bond_types.begin(), inserted_bond_types.end(), reverse_atom_pair_type) != inserted_bond_types.end())
            index = distance(inserted_bond_types.begin(), find(inserted_bond_types.begin(), inserted_bond_types.end(), reverse_atom_pair_type));
        else
        {
            cout << atom_pair_type.at(0) << "-" << atom_pair_type.at(1) << " bond type does not exist in the parameter files" << endl;
            return;
        }
        topology_bond->SetBondType(topology_file->GetBondTypeByIndex(index));
        topology_file->AddBond(topology_bond);
    }
}
void Assembly::ExtractTopologyBondTypesFromAssembly (std::vector< std::vector< std::string > > & inserted_bond_types, Atom * assembly_atom, Atom * neighbor, ParameterFileSpace::ParameterFile::BondMap & bonds, int & bond_type_counter, TopologyFileSpace::TopologyFile * topology_file)
Definition at line 1187 of file assembly.cc.
References TopologyFileSpace::TopologyFile::AddBondType(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), ParameterFileSpace::ParameterFileBond::GetForceConstant(), MolecularModeling::Atom::GetId(), ParameterFileSpace::ParameterFileBond::GetLength(), TopologyFileSpace::TopologyBondType::SetEquilibriumValue(), TopologyFileSpace::TopologyBondType::SetForceConstant(), and TopologyFileSpace::TopologyBondType::SetIndex().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    vector<string> atom_pair_type = vector<string>();
    vector<string> reverse_atom_pair_type = vector<string>();
    stringstream key2;
    key2 << neighbor->GetId();
    atom_pair_type.push_back(assembly_atom->GetAtomType());
    atom_pair_type.push_back(neighbor->GetAtomType());
    reverse_atom_pair_type.push_back(neighbor->GetAtomType());
    reverse_atom_pair_type.push_back(assembly_atom->GetAtomType());
    if(find(inserted_bond_types.begin(), inserted_bond_types.end(), atom_pair_type) == inserted_bond_types.end() &&
            find(inserted_bond_types.begin(), inserted_bond_types.end(), reverse_atom_pair_type) == inserted_bond_types.end())
    {
        ParameterFileBond* parameter_file_bond;
        if(bonds.find(atom_pair_type) != bonds.end())
        {
            parameter_file_bond = bonds[atom_pair_type];
            inserted_bond_types.push_back(atom_pair_type);
        }
        else if(bonds.find(reverse_atom_pair_type) != bonds.end())
        {
            parameter_file_bond = bonds[reverse_atom_pair_type];
            inserted_bond_types.push_back(reverse_atom_pair_type);
        }
        else
        {
            cout << atom_pair_type.at(0) << "-" << atom_pair_type.at(1) << " bond type does not exist in the parameter files" << endl;
            return;
        }
        TopologyBondType* topology_bond_type = new TopologyBondType();
        topology_bond_type->SetForceConstant(parameter_file_bond->GetForceConstant());
        topology_bond_type->SetEquilibriumValue(parameter_file_bond->GetLength());
        topology_bond_type->SetIndex(bond_type_counter);
        bond_type_counter++;
        topology_file->AddBondType(topology_bond_type);
    }
}
void Assembly::ExtractTopologyDihedralsFromAssembly (Atom * assembly_atom, Atom * neighbor, Atom * neighbor_of_neighbor, Atom * neighbor_of_neighbor_neighbor, std::vector< std::vector< std::string > > & inserted_dihedrals, std::vector< std::string > & inserted_dihedral_types, ParameterFileSpace::ParameterFile::DihedralMap & dihedrals, TopologyFileSpace::TopologyFile * topology_file)
not sure
Improper Dihedrals
not sure
Definition at line 1499 of file assembly.cc.
References TopologyFileSpace::TopologyFile::AddDihedral(), CreateAllAtomTypePermutationsforDihedralType(), CreateAllAtomTypePermutationsforImproperDihedralType(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), TopologyFileSpace::TopologyFile::GetDihedralTypeByIndex(), MolecularModeling::Residue::GetName(), MolecularModeling::Atom::GetName(), MolecularModeling::Atom::GetNode(), MolecularModeling::AtomNode::GetNodeNeighbors(), MolecularModeling::Atom::GetResidue(), ParameterFileSpace::ParameterFileDihedral::GetTerms(), TopologyFileSpace::TopologyDihedral::SetDihedrals(), TopologyFileSpace::TopologyDihedral::SetDihedralType(), TopologyFileSpace::TopologyDihedral::SetIgnoredGroupInteraction(), TopologyFileSpace::TopologyDihedral::SetIncludingHydrogen(), TopologyFileSpace::TopologyDihedral::SetIsImproper(), and TopologyFileSpace::TopologyDihedral::SetResidueNames().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    vector<vector<string> > all_atom_type_permutations = CreateAllAtomTypePermutationsforDihedralType(assembly_atom->GetAtomType(), neighbor->GetAtomType(),
                                                                                                      neighbor_of_neighbor->GetAtomType(), neighbor_of_neighbor_of_neighbor->GetAtomType());
    for(vector<vector<string> >::iterator it = all_atom_type_permutations.begin(); it != all_atom_type_permutations.end(); it++)
    {
        vector<string> atom_types = (*it);
        stringstream sss;
        sss << atom_types.at(0) << "_" << atom_types.at(1) << "_" << atom_types.at(2) << "_" << atom_types.at(3);
        if(find(inserted_dihedral_types.begin(), inserted_dihedral_types.end(), sss.str()) != inserted_dihedral_types.end())
        {
            vector<string> dihedral_atom_names = vector<string>();
            vector<string> reverse_dihedral_atom_names = vector<string>();
            dihedral_atom_names.push_back(assembly_atom->GetName());
            dihedral_atom_names.push_back(neighbor->GetName());
            dihedral_atom_names.push_back(neighbor_of_neighbor->GetName());
            dihedral_atom_names.push_back(neighbor_of_neighbor_of_neighbor->GetName());
            reverse_dihedral_atom_names.push_back(neighbor_of_neighbor_of_neighbor->GetName());
            reverse_dihedral_atom_names.push_back(neighbor_of_neighbor->GetName());
            reverse_dihedral_atom_names.push_back(neighbor->GetName());
            reverse_dihedral_atom_names.push_back(assembly_atom->GetName());
            vector<string> residue_names = vector<string>();
            vector<string> reverse_residue_names = vector<string>();
            residue_names.push_back(assembly_atom->GetResidue()->GetName());
            residue_names.push_back(neighbor->GetResidue()->GetName());
            residue_names.push_back(neighbor_of_neighbor->GetResidue()->GetName());
            residue_names.push_back(neighbor_of_neighbor_of_neighbor->GetResidue()->GetName());
            reverse_residue_names.push_back(neighbor_of_neighbor_of_neighbor->GetResidue()->GetName());
            reverse_residue_names.push_back(neighbor_of_neighbor->GetResidue()->GetName());
            reverse_residue_names.push_back(neighbor->GetResidue()->GetName());
            reverse_residue_names.push_back(assembly_atom->GetResidue()->GetName());
            vector<string> dihedral = vector<string>();
            vector<string> reverse_dihedral = vector<string>();
            stringstream ss;
            ss << residue_names.at(0) << ":" << dihedral_atom_names.at(0);
            stringstream ss1;
            ss1 << residue_names.at(1) << ":" << dihedral_atom_names.at(1);
            stringstream ss2;
            ss2 << residue_names.at(2) << ":" << dihedral_atom_names.at(2);
            stringstream ss3;
            ss3 << residue_names.at(3) << ":" << dihedral_atom_names.at(3);
            dihedral.push_back(ss.str());
            dihedral.push_back(ss1.str());
            dihedral.push_back(ss2.str());
            dihedral.push_back(ss3.str());
            reverse_dihedral.push_back(ss3.str());
            reverse_dihedral.push_back(ss2.str());
            reverse_dihedral.push_back(ss1.str());
            reverse_dihedral.push_back(ss.str());
            if(find(inserted_dihedrals.begin(), inserted_dihedrals.end(), dihedral) == inserted_dihedrals.end() &&
                    find(inserted_dihedrals.begin(), inserted_dihedrals.end(), reverse_dihedral) == inserted_dihedrals.end())
            {
                ParameterFileDihedral* parameter_file_dihedral = dihedrals[atom_types];
                vector<ParameterFileDihedralTerm> dihedral_terms = parameter_file_dihedral->GetTerms();
                for(vector<ParameterFileDihedralTerm>::iterator it1 = dihedral_terms.begin(); it1 != dihedral_terms.end(); it1++)
                {
                    TopologyDihedral* topology_dihedral = new TopologyDihedral();
                    topology_dihedral->SetIsImproper(false);
                    topology_dihedral->SetIgnoredGroupInteraction(false);///not sure
                    if((assembly_atom->GetName().substr(0,1).compare("H") == 0 ||
                        (assembly_atom->GetName().substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(assembly_atom->GetName().substr(0,1)))))
                            || (neighbor->GetName().substr(0,1).compare("H") == 0 ||
                                (neighbor->GetName().substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor->GetName().substr(0,1)))))
                            ||(neighbor_of_neighbor->GetName().substr(0,1).compare("H") == 0 ||
                               (neighbor_of_neighbor->GetName().substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor_of_neighbor->GetName().substr(0,1)))))
                            ||(neighbor_of_neighbor_of_neighbor->GetName().substr(0,1).compare("H") == 0 ||
                               (neighbor_of_neighbor_of_neighbor->GetName().substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor_of_neighbor_of_neighbor->GetName().substr(0,1))))))
                        topology_dihedral->SetIncludingHydrogen(true);
                    else
                        topology_dihedral->SetIncludingHydrogen(false);
                    if(atom_types.at(0).compare(assembly_atom->GetAtomType()) == 0 ||
                            atom_types.at(0).compare("X") == 0 && atom_types.at(3).compare(neighbor_of_neighbor_of_neighbor->GetAtomType()) == 0 ||
                            atom_types.at(0).compare("X") == 0 && atom_types.at(3).compare("X") == 0 && atom_types.at(1).compare(neighbor->GetAtomType()) == 0 ||
                            atom_types.at(0).compare("X") == 0 && atom_types.at(3).compare("X") == 0 && atom_types.at(2).compare(neighbor_of_neighbor->GetAtomType()) == 0 )
                    {
                        topology_dihedral->SetResidueNames(residue_names);
                        topology_dihedral->SetDihedrals(dihedral_atom_names);
                    }
                    else
                    {
                        topology_dihedral->SetResidueNames(reverse_residue_names);
                        topology_dihedral->SetDihedrals(reverse_dihedral_atom_names);
                    }
                    int index = 0;
                    if(find(inserted_dihedral_types.begin(), inserted_dihedral_types.end(), sss.str()) != inserted_dihedral_types.end())
                        index = distance(inserted_dihedral_types.begin(), find(inserted_dihedral_types.begin(), inserted_dihedral_types.end(), sss.str())) +
                                distance(dihedral_terms.begin(), it1);
                    topology_dihedral->SetDihedralType(topology_file->GetDihedralTypeByIndex(index));
                    topology_file->AddDihedral(topology_dihedral);
                }
                if(atom_types.at(0).compare(assembly_atom->GetAtomType()) == 0 ||
                        (atom_types.at(0).compare("X") == 0 && atom_types.at(3).compare(neighbor_of_neighbor_of_neighbor->GetAtomType()) == 0) ||
                        (atom_types.at(0).compare("X") == 0 && atom_types.at(3).compare("X") == 0 && atom_types.at(1).compare(neighbor->GetAtomType()) == 0) ||
                        (atom_types.at(0).compare("X") == 0 && atom_types.at(3).compare("X") == 0 && atom_types.at(2).compare(neighbor_of_neighbor->GetAtomType()) == 0) )
                    inserted_dihedrals.push_back(dihedral);
                else
                    inserted_dihedrals.push_back(reverse_dihedral);
                break;
            }
        }
    }
    /**/
    ///Improper Dihedrals
    AtomNode* atom_node = assembly_atom->GetNode();
    AtomVector neighbors = atom_node->GetNodeNeighbors();
    if(neighbors.size() == 3)
    {
        Atom* neighbor1 = neighbors.at(0);
        Atom* neighbor2 = neighbors.at(1);
        Atom* neighbor3 = neighbors.at(2);
        vector<vector<string> > all_improper_dihedrals_atom_type_permutations = CreateAllAtomTypePermutationsforImproperDihedralType(neighbor1->GetAtomType(), neighbor2->GetAtomType(),
                                                                                                                                     neighbor3->GetAtomType(), assembly_atom->GetAtomType());
        for(vector<vector<string> >::iterator it = all_improper_dihedrals_atom_type_permutations.begin(); it != all_improper_dihedrals_atom_type_permutations.end(); it++)
        {
            vector<string> improper_dihedral_permutation = (*it);
            stringstream sss;
            sss << improper_dihedral_permutation.at(0) << "_" << improper_dihedral_permutation.at(1) << "_" << improper_dihedral_permutation.at(2) << "_" << improper_dihedral_permutation.at(3);
            if(find(inserted_dihedral_types.begin(), inserted_dihedral_types.end(), sss.str()) != inserted_dihedral_types.end())
            {
                vector<string> dihedral_atom_names1 = vector<string>();
                dihedral_atom_names1.push_back(neighbor1->GetName());
                dihedral_atom_names1.push_back(neighbor2->GetName());
                dihedral_atom_names1.push_back(assembly_atom->GetName());
                dihedral_atom_names1.push_back(neighbor3->GetName());
                vector<string> dihedral_atom_names2 = vector<string>();
                dihedral_atom_names2.push_back(neighbor1->GetName());
                dihedral_atom_names2.push_back(assembly_atom->GetName());
                dihedral_atom_names2.push_back(neighbor3->GetName());
                dihedral_atom_names2.push_back(neighbor2->GetName());
                vector<string> dihedral_atom_names3 = vector<string>();
                dihedral_atom_names3.push_back(neighbor1->GetName());
                dihedral_atom_names3.push_back(neighbor3->GetName());
                dihedral_atom_names3.push_back(assembly_atom->GetName());
                dihedral_atom_names3.push_back(neighbor2->GetName());
                vector<string> reverse_dihedral_atom_names1 = vector<string>();
                reverse_dihedral_atom_names1.push_back(neighbor3->GetName());
                reverse_dihedral_atom_names1.push_back(assembly_atom->GetName());
                reverse_dihedral_atom_names1.push_back(neighbor2->GetName());
                reverse_dihedral_atom_names1.push_back(neighbor1->GetName());
                vector<string> reverse_dihedral_atom_names2 = vector<string>();
                reverse_dihedral_atom_names2.push_back(neighbor2->GetName());
                reverse_dihedral_atom_names2.push_back(neighbor3->GetName());
                reverse_dihedral_atom_names2.push_back(assembly_atom->GetName());
                reverse_dihedral_atom_names2.push_back(neighbor1->GetName());
                vector<string> reverse_dihedral_atom_names3 = vector<string>();
                reverse_dihedral_atom_names3.push_back(neighbor2->GetName());
                reverse_dihedral_atom_names3.push_back(assembly_atom->GetName());
                reverse_dihedral_atom_names3.push_back(neighbor3->GetName());
                reverse_dihedral_atom_names3.push_back(neighbor1->GetName());
                vector<string> residue_names1 = vector<string>();
                residue_names1.push_back(neighbor1->GetResidue()->GetName());
                residue_names1.push_back(neighbor2->GetResidue()->GetName());
                residue_names1.push_back(assembly_atom->GetResidue()->GetName());
                residue_names1.push_back(neighbor3->GetResidue()->GetName());
                vector<string> residue_names2 = vector<string>();
                residue_names2.push_back(neighbor1->GetName());
                residue_names2.push_back(assembly_atom->GetResidue()->GetName());
                residue_names2.push_back(neighbor3->GetResidue()->GetName());
                residue_names2.push_back(neighbor2->GetResidue()->GetName());
                vector<string> residue_names3 = vector<string>();
                residue_names3.push_back(neighbor1->GetResidue()->GetName());
                residue_names3.push_back(neighbor3->GetResidue()->GetName());
                residue_names3.push_back(assembly_atom->GetResidue()->GetName());
                residue_names3.push_back(neighbor2->GetResidue()->GetName());
                vector<string> reverse_residue_names1 = vector<string>();
                reverse_residue_names1.push_back(neighbor3->GetResidue()->GetName());
                reverse_residue_names1.push_back(assembly_atom->GetResidue()->GetName());
                reverse_residue_names1.push_back(neighbor2->GetResidue()->GetName());
                reverse_residue_names1.push_back(neighbor1->GetResidue()->GetName());
                vector<string> reverse_residue_names2 = vector<string>();
                reverse_residue_names2.push_back(neighbor2->GetResidue()->GetName());
                reverse_residue_names2.push_back(neighbor3->GetResidue()->GetName());
                reverse_residue_names2.push_back(assembly_atom->GetResidue()->GetName());
                reverse_residue_names2.push_back(neighbor1->GetName());
                vector<string> reverse_residue_names3 = vector<string>();
                reverse_residue_names3.push_back(neighbor2->GetResidue()->GetName());
                reverse_residue_names3.push_back(assembly_atom->GetResidue()->GetName());
                reverse_residue_names3.push_back(neighbor3->GetResidue()->GetName());
                reverse_residue_names3.push_back(neighbor1->GetResidue()->GetName());
                vector<string> dihedral1 = vector<string>();
                vector<string> dihedral2 = vector<string>();
                vector<string> dihedral3 = vector<string>();
                vector<string> reverse_dihedral1 = vector<string>();
                vector<string> reverse_dihedral2 = vector<string>();
                vector<string> reverse_dihedral3 = vector<string>();
                stringstream ss;
                ss << residue_names1.at(2) << ":" << dihedral_atom_names1.at(2);
                stringstream ss1;
                ss1 << residue_names1.at(0) << ":" << dihedral_atom_names1.at(0);
                stringstream ss2;
                ss2 << residue_names1.at(1) << ":" << dihedral_atom_names1.at(1);
                stringstream ss3;
                ss3 << residue_names1.at(3) << ":" << dihedral_atom_names1.at(3);
                dihedral1.push_back(ss1.str());
                dihedral1.push_back(ss2.str());
                dihedral1.push_back(ss.str());
                dihedral1.push_back(ss3.str());
                reverse_dihedral1.push_back(ss3.str());
                reverse_dihedral1.push_back(ss.str());
                reverse_dihedral1.push_back(ss2.str());
                reverse_dihedral1.push_back(ss1.str());
                dihedral2.push_back(ss1.str());
                dihedral2.push_back(ss.str());
                dihedral2.push_back(ss3.str());
                dihedral2.push_back(ss2.str());
                reverse_dihedral2.push_back(ss2.str());
                reverse_dihedral2.push_back(ss3.str());
                reverse_dihedral2.push_back(ss.str());
                reverse_dihedral2.push_back(ss1.str());
                dihedral3.push_back(ss1.str());
                dihedral3.push_back(ss3.str());
                dihedral3.push_back(ss.str());
                dihedral3.push_back(ss2.str());
                reverse_dihedral3.push_back(ss2.str());
                reverse_dihedral3.push_back(ss.str());
                reverse_dihedral3.push_back(ss3.str());
                reverse_dihedral3.push_back(ss1.str());
                if(find(inserted_dihedrals.begin(), inserted_dihedrals.end(), dihedral1) == inserted_dihedrals.end() &&
                        find(inserted_dihedrals.begin(), inserted_dihedrals.end(), dihedral2) == inserted_dihedrals.end() &&
                        find(inserted_dihedrals.begin(), inserted_dihedrals.end(), dihedral3) == inserted_dihedrals.end() &&
                        find(inserted_dihedrals.begin(), inserted_dihedrals.end(), reverse_dihedral1) == inserted_dihedrals.end() &&
                        find(inserted_dihedrals.begin(), inserted_dihedrals.end(), reverse_dihedral2) == inserted_dihedrals.end() &&
                        find(inserted_dihedrals.begin(), inserted_dihedrals.end(), reverse_dihedral3) == inserted_dihedrals.end())
                {
                    int permutation_index = distance(all_improper_dihedrals_atom_type_permutations.begin(), it);
                    ParameterFileDihedral* parameter_file_dihedral = dihedrals[improper_dihedral_permutation];
                    vector<ParameterFileDihedralTerm> dihedral_terms = parameter_file_dihedral->GetTerms();
                    for(vector<ParameterFileDihedralTerm>::iterator it1 = dihedral_terms.begin(); it1 != dihedral_terms.end(); it1++)
                    {
                        TopologyDihedral* topology_dihedral = new TopologyDihedral();
                        topology_dihedral->SetIsImproper(true);
                        topology_dihedral->SetIgnoredGroupInteraction(false);///not sure
                        if((assembly_atom->GetName().substr(0,1).compare("H") == 0 ||
                            (assembly_atom->GetName().substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(assembly_atom->GetName().substr(0,1)))))
                                || (neighbor->GetName().substr(0,1).compare("H") == 0 ||
                                    (neighbor->GetName().substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor->GetName().substr(0,1)))))
                                ||(neighbor_of_neighbor->GetName().substr(0,1).compare("H") == 0 ||
                                   (neighbor_of_neighbor->GetName().substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor_of_neighbor->GetName().substr(0,1)))))
                                ||(neighbor_of_neighbor_of_neighbor->GetName().substr(0,1).compare("H") == 0 ||
                                   (neighbor_of_neighbor_of_neighbor->GetName().substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(neighbor_of_neighbor_of_neighbor->GetName().substr(0,1))))))
                            topology_dihedral->SetIncludingHydrogen(true);
                        else
                            topology_dihedral->SetIncludingHydrogen(false);
                        if(permutation_index == 0 || (permutation_index >= 6 && permutation_index <= 9) || (permutation_index >= 30 && permutation_index <= 35) || (permutation_index >= 66 && permutation_index <= 69))
{
                            topology_dihedral->SetResidueNames(residue_names1);
                            topology_dihedral->SetDihedrals(dihedral_atom_names1);
                        }
                        if(permutation_index == 2 || (permutation_index >= 14 && permutation_index <= 17) || (permutation_index >= 42 && permutation_index <= 47) || (permutation_index >= 74 && permutation_index <= 77))
{
                            topology_dihedral->SetResidueNames(residue_names2);
                            topology_dihedral->SetDihedrals(dihedral_atom_names2);
                        }
                        if(permutation_index == 4 || (permutation_index >= 22 && permutation_index <= 25) || (permutation_index >= 54 && permutation_index <= 59) || (permutation_index >= 82 && permutation_index <= 85))
{
                            topology_dihedral->SetResidueNames(residue_names3);
                            topology_dihedral->SetDihedrals(dihedral_atom_names3);
                        }
                        if(permutation_index == 1 || (permutation_index >= 10 && permutation_index <= 13) || (permutation_index >= 36 && permutation_index <= 41) || (permutation_index >= 70 && permutation_index <= 73))
{
                            topology_dihedral->SetResidueNames(reverse_residue_names1);
                            topology_dihedral->SetDihedrals(reverse_dihedral_atom_names1);
                        }
                        if(permutation_index == 3 || (permutation_index >= 18 && permutation_index <= 21) || (permutation_index >= 48 && permutation_index <= 53) || (permutation_index >= 78 && permutation_index <= 81))
{
                            topology_dihedral->SetResidueNames(reverse_residue_names2);
                            topology_dihedral->SetDihedrals(reverse_dihedral_atom_names2);
                        }
                        if(permutation_index == 5 || (permutation_index >= 26 && permutation_index <= 29) || (permutation_index >= 60 && permutation_index <= 65) || (permutation_index >= 86 && permutation_index <= 89))
{
                            topology_dihedral->SetResidueNames(reverse_residue_names3);
                            topology_dihedral->SetDihedrals(reverse_dihedral_atom_names3);
                        }
                        int index = 0;
                        if(find(inserted_dihedral_types.begin(), inserted_dihedral_types.end(), sss.str()) != inserted_dihedral_types.end())
                            index = distance(inserted_dihedral_types.begin(), find(inserted_dihedral_types.begin(), inserted_dihedral_types.end(), sss.str())) +
                                    distance(dihedral_terms.begin(), it1);
                        topology_dihedral->SetDihedralType(topology_file->GetDihedralTypeByIndex(index));
                        topology_file->AddDihedral(topology_dihedral);
                    }
                    if(permutation_index == 0 || (permutation_index >= 6 && permutation_index <= 9) || (permutation_index >= 30 && permutation_index <= 35) || (permutation_index >= 66 && permutation_index <= 69))
                    {
                        inserted_dihedrals.push_back(dihedral1);
                    }
                    if(permutation_index == 2 || (permutation_index >= 14 && permutation_index <= 17) || (permutation_index >= 42 && permutation_index <= 47) || (permutation_index >= 74 && permutation_index <= 77))
                    {
                        inserted_dihedrals.push_back(dihedral2);
                    }
                    if(permutation_index == 4 || (permutation_index >= 22 && permutation_index <= 25) || (permutation_index >= 54 && permutation_index <= 59) || (permutation_index >= 82 && permutation_index <= 85))
                    {
                        inserted_dihedrals.push_back(dihedral3);
                    }
                    if(permutation_index == 1 || (permutation_index >= 10 && permutation_index <= 13) || (permutation_index >= 36 && permutation_index <= 41) || (permutation_index >= 70 && permutation_index <= 73))
                    {
                        inserted_dihedrals.push_back(reverse_dihedral1);
                    }
                    if(permutation_index == 3 || (permutation_index >= 18 && permutation_index <= 21) || (permutation_index >= 48 && permutation_index <= 53) || (permutation_index >= 78 && permutation_index <= 81))
                    {
                        inserted_dihedrals.push_back(reverse_dihedral2);
                    }
                    if(permutation_index == 5 || (permutation_index >= 26 && permutation_index <= 29) || (permutation_index >= 60 && permutation_index <= 65) || (permutation_index >= 86 && permutation_index <= 89))
                    {
                        inserted_dihedrals.push_back(reverse_dihedral3);
                    }
                    break;
                }
            }
        }
    }
    /**/
}
void Assembly::ExtractTopologyDihedralTypesFromAssembly (Atom * assembly_atom, Atom * neighbor, Atom * neighbor_of_neighbor, Atom * neighbor_of_neighbor_neighbor, std::vector< std::string > & inserted_dihedral_types, int & dihedral_type_counter, TopologyFileSpace::TopologyFile * topology_file, ParameterFileSpace::ParameterFile::DihedralMap & dihedrals)
Improper Dihedrals
Definition at line 1423 of file assembly.cc.
References TopologyFileSpace::TopologyFile::AddDihedralType(), CreateAllAtomTypePermutationsforDihedralType(), CreateAllAtomTypePermutationsforImproperDihedralType(), MolecularModeling::MolecularDynamicAtom::GetAtomType(), ParameterFileSpace::ParameterFileDihedralTerm::GetForceConstant(), MolecularModeling::Atom::GetNode(), MolecularModeling::AtomNode::GetNodeNeighbors(), ParameterFileSpace::ParameterFileDihedralTerm::GetPeriodicity(), ParameterFileSpace::ParameterFileDihedralTerm::GetPhase(), ParameterFileSpace::ParameterFileDihedral::GetScee(), ParameterFileSpace::ParameterFileDihedral::GetScnb(), ParameterFileSpace::ParameterFileDihedral::GetTerms(), TopologyFileSpace::TopologyDihedralType::SetForceConstant(), TopologyFileSpace::TopologyDihedralType::SetIndex(), TopologyFileSpace::TopologyDihedralType::SetPeriodicity(), TopologyFileSpace::TopologyDihedralType::SetPhase(), TopologyFileSpace::TopologyDihedralType::SetScee(), and TopologyFileSpace::TopologyDihedralType::SetScnb().
Referenced by BuildTopologyFileStructureFromAssembly().
{
    vector<vector<string> > all_atom_type_permutations = CreateAllAtomTypePermutationsforDihedralType(assembly_atom->GetAtomType(), neighbor->GetAtomType(),
                                                                                                      neighbor_of_neighbor->GetAtomType(), neighbor_of_neighbor_of_neighbor->GetAtomType());
    for(vector<vector<string> >::iterator it = all_atom_type_permutations.begin(); it != all_atom_type_permutations.end(); it++)
    {
        vector<string> atom_types = (*it);
        if(dihedrals[atom_types] != NULL)
        {
            stringstream ss;
            ss << atom_types.at(0) << "_" << atom_types.at(1) << "_" << atom_types.at(2) << "_" << atom_types.at(3);
            if(find(inserted_dihedral_types.begin(), inserted_dihedral_types.end(), ss.str()) == inserted_dihedral_types.end())
            {
                ParameterFileDihedral* parameter_file_dihedral = dihedrals[atom_types];
                vector<ParameterFileDihedralTerm> dihedral_terms = parameter_file_dihedral->GetTerms();
                for(vector<ParameterFileDihedralTerm>::iterator it1 = dihedral_terms.begin(); it1 != dihedral_terms.end(); it1++)
                {
                    inserted_dihedral_types.push_back(ss.str());
                    ParameterFileDihedralTerm parameter_file_dihedral_term = (*it1);
                    TopologyDihedralType* topology_dihedral_type = new TopologyDihedralType();
                    topology_dihedral_type->SetIndex(dihedral_type_counter);
                    dihedral_type_counter++;
                    topology_dihedral_type->SetForceConstant(parameter_file_dihedral_term.GetForceConstant());
                    topology_dihedral_type->SetPeriodicity(fabs(parameter_file_dihedral_term.GetPeriodicity()));
                    topology_dihedral_type->SetPhase(parameter_file_dihedral_term.GetPhase());
                    topology_dihedral_type->SetScee(parameter_file_dihedral->GetScee());
                    topology_dihedral_type->SetScnb(parameter_file_dihedral->GetScnb());
                    topology_file->AddDihedralType(topology_dihedral_type);
                }
                break;
            }
        }
    }
    ///Improper Dihedrals
    AtomNode* atom_node = assembly_atom->GetNode();
    AtomVector neighbors = atom_node->GetNodeNeighbors();
    if(neighbors.size() == 3)
    {
        Atom* neighbor1 = neighbors.at(0);
        Atom* neighbor2 = neighbors.at(1);
        Atom* neighbor3 = neighbors.at(2);
        vector<vector<string> > all_improper_dihedrals_atom_type_permutations = CreateAllAtomTypePermutationsforImproperDihedralType(neighbor1->GetAtomType(), neighbor2->GetAtomType(),
                                                                                                                                     neighbor3->GetAtomType(), assembly_atom->GetAtomType());
        for(vector<vector<string> >::iterator it = all_improper_dihedrals_atom_type_permutations.begin(); it != all_improper_dihedrals_atom_type_permutations.end(); it++)
        {
            vector<string> improper_dihedral_permutation = (*it);
            if(dihedrals[improper_dihedral_permutation] != NULL)
            {
                stringstream ss;
                ss << improper_dihedral_permutation.at(0) << "_" << improper_dihedral_permutation.at(1) << "_" << improper_dihedral_permutation.at(2) << "_" << improper_dihedral_permutation.at(3);
                if(find(inserted_dihedral_types.begin(), inserted_dihedral_types.end(), ss.str()) == inserted_dihedral_types.end())
                {
                    ParameterFileDihedral* parameter_file_dihedral = dihedrals[improper_dihedral_permutation];
                    vector<ParameterFileDihedralTerm> dihedral_terms = parameter_file_dihedral->GetTerms();
                    for(vector<ParameterFileDihedralTerm>::iterator it1 = dihedral_terms.begin(); it1 != dihedral_terms.end(); it1++)
                    {
                        inserted_dihedral_types.push_back(ss.str());
                        ParameterFileDihedralTerm parameter_file_dihedral_term = (*it1);
                        TopologyDihedralType* topology_dihedral_type = new TopologyDihedralType();
                        topology_dihedral_type->SetIndex(dihedral_type_counter);
                        dihedral_type_counter++;
                        topology_dihedral_type->SetForceConstant(parameter_file_dihedral_term.GetForceConstant());
                        topology_dihedral_type->SetPeriodicity(fabs(parameter_file_dihedral_term.GetPeriodicity()));
                        topology_dihedral_type->SetPhase(parameter_file_dihedral_term.GetPhase());
                        topology_dihedral_type->SetScee(parameter_file_dihedral->GetScee());
                        topology_dihedral_type->SetScnb(parameter_file_dihedral->GetScnb());
                        topology_file->AddDihedralType(topology_dihedral_type);
                    }
                    break;
                }
            }
        }
    }
}
Assembly::AtomVector Assembly::GetAllAtomsOfAssembly ()
Definition at line 218 of file assembly.cc.
References GetAllAtomsOfAssembly(), GetAssemblies(), MolecularModeling::Residue::GetAtoms(), and GetResidues().
Referenced by BuildStructureByDatabaseFilesBondingInformation(), BuildStructureByDistance(), BuildStructureByLIBFileInformation(), BuildStructureByPDBFileInformation(), BuildStructureByPrepFileInformation(), BuildStructureByTOPFileInformation(), CountNumberOfAngles(), CountNumberOfAnglesExcludingHydrogen(), CountNumberOfAnglesIncludingHydrogen(), CountNumberOfAngleTypes(), CountNumberOfAtomTypes(), CountNumberOfBonds(), CountNumberOfBondsExcludingHydrogen(), CountNumberOfBondsIncludingHydrogen(), CountNumberOfBondTypes(), CountNumberOfDihedrals(), CountNumberOfDihedralsExcludingHydrogen(), CountNumberOfDihedralsIncludingHydrogen(), CountNumberOfDihedralTypes(), CountNumberOfExcludedAtoms(), GetAllAtomsOfAssembly(), and GetAllAtomsOfAssemblyWithAtLeastThreeNeighbors().
{
    AtomVector all_atoms_of_assembly = AtomVector();
    AssemblyVector assemblies = this->GetAssemblies();
    for(AssemblyVector::iterator it = assemblies.begin(); it != assemblies.end(); it++)
    {
        Assembly* assembly = (*it);
        AtomVector atoms_of_assembly = assembly->GetAllAtomsOfAssembly();
        for(AtomVector::iterator it1 = atoms_of_assembly.begin(); it1 != atoms_of_assembly.end(); it1++)
        {
            Atom* atom = (*it1);
            all_atoms_of_assembly.push_back(atom);
        }
    }
    ResidueVector residues = this->GetResidues();
    for(ResidueVector::iterator it = residues.begin(); it != residues.end(); it++)
    {
        Residue* residue = (*it);
        AtomVector atoms = residue->GetAtoms();
        for(AtomVector::iterator it1 = atoms.begin(); it1 != atoms.end(); it1++)
        {
            Atom* atom = (*it1);
            all_atoms_of_assembly.push_back(atom);
        }
    }
    return all_atoms_of_assembly;
}
Assembly::AtomVector Assembly::GetAllAtomsOfAssemblyWithAtLeastThreeNeighbors ()
Definition at line 3356 of file assembly.cc.
References GetAllAtomsOfAssembly(), MolecularModeling::Atom::GetNode(), and MolecularModeling::AtomNode::GetNodeNeighbors().
{
    AtomVector all_atoms = GetAllAtomsOfAssembly();
    AtomVector atoms_with_at_least_three_neighbors = AtomVector();
    for(AtomVector::iterator it = all_atoms.begin(); it != all_atoms.end(); it++)
    {
        Atom* atom = (*it);
        AtomNode* node = atom->GetNode();
        AtomVector neighbors = node->GetNodeNeighbors();
        if(neighbors.size() > 2)
            atoms_with_at_least_three_neighbors.push_back(atom);
    }
    return atoms_with_at_least_three_neighbors;
}
Assembly::CoordinateVector Assembly::GetAllCoordinates ()
Definition at line 180 of file assembly.cc.
References GetAllCoordinates(), MolecularModeling::Residue::GetAtoms(), and MolecularModeling::Atom::GetCoordinates().
Referenced by BuildCoordinateFileStructureFromAssembly(), and GetAllCoordinates().
{
    CoordinateVector coordinates = CoordinateVector();
    for(AssemblyVector::iterator it = this->assemblies_.begin(); it != this->assemblies_.end(); it++)
    {
        Assembly* assembly = (*it);
        CoordinateVector assembly_coordinate = assembly->GetAllCoordinates();
        if(assembly_coordinate.size() == 0)
        {
            cout << "Central data structure is not complete in order for generating this type of file: Missing coordinate(s)" << endl;
            return CoordinateVector();
        }
        for(CoordinateVector::iterator it1 = assembly_coordinate.begin(); it1 != assembly_coordinate.end(); it1++)
        {
            coordinates.push_back(*it1);
        }
    }
    for(ResidueVector::iterator it = this->residues_.begin(); it != this->residues_.end(); it++)
    {
        Residue* residue = (*it);
        AtomVector residue_atoms = residue->GetAtoms();
        for(AtomVector::iterator it1 = residue_atoms.begin(); it1 != residue_atoms.end(); it1++)
        {
            Atom* atom = (*it1);
            if(atom->GetCoordinates().size() == 0)
            {
                cout << "Central data structure is not complete in order for generating this type of file: Missing coordinate(s)" << endl;
                return CoordinateVector();
            }
            else
            {
                coordinates.push_back(atom->GetCoordinates()[model_index_]);
            }
        }
    }
    return coordinates;
}
Assembly::ResidueVector Assembly::GetAllResiduesOfAssembly ()
Definition at line 245 of file assembly.cc.
References GetAllResiduesOfAssembly(), GetAssemblies(), and GetResidues().
Referenced by BuildLibraryFileStructureFromAssembly(), BuildPrepFileStructureFromAssembly(), BuildTopologyFileStructureFromAssembly(), and GetAllResiduesOfAssembly().
{
    ResidueVector all_residues_of_assembly = ResidueVector();
    AssemblyVector assemblies = this->GetAssemblies();
    for(AssemblyVector::iterator it = assemblies.begin(); it != assemblies.end(); it++)
    {
        Assembly* assembly = (*it);
        ResidueVector residues_of_assembly = assembly->GetAllResiduesOfAssembly();
        for(ResidueVector::iterator it1 = residues_of_assembly.begin(); it1 != residues_of_assembly.end(); it1++)
        {
            all_residues_of_assembly.push_back(*it1);
        }
    }
    ResidueVector residues = this->GetResidues();
    for(ResidueVector::iterator it = residues.begin(); it != residues.end(); it++)
    {
        all_residues_of_assembly.push_back(*it);
    }
    return all_residues_of_assembly;
}
Assembly::AssemblyVector Assembly::GetAssemblies ()
Definition at line 136 of file assembly.cc.
Referenced by ExtractPdbModelCardFromAssembly(), GetAllAtomsOfAssembly(), and GetAllResiduesOfAssembly().
{
    return assemblies_;
}
Geometry::Coordinate Assembly::GetCenterOfGeometry ()
Definition at line 160 of file assembly.cc.
Referenced by CalculateCenterOfGeometry().
{
    return center_of_geometry_;
}
Geometry::Coordinate Assembly::GetCenterOfMass ()
Definition at line 156 of file assembly.cc.
{
    return center_of_mass_;
}
string Assembly::GetChemicalType ()
Definition at line 144 of file assembly.cc.
{
    return chemical_type_;
}
string Assembly::GetDescription ()
Definition at line 164 of file assembly.cc.
{
    return description_;
}
int Assembly::GetModelIndex ()
Definition at line 176 of file assembly.cc.
Referenced by BuildLibraryFileStructureFromAssembly().
{
    return model_index_;
}
string Assembly::GetName ()
Definition at line 132 of file assembly.cc.
Referenced by AddAssembly().
{
    return name_;
}
Assembly::ResidueVector Assembly::GetResidues ()
Definition at line 140 of file assembly.cc.
Referenced by ExtractPdbModelCardFromAssembly(), GetAllAtomsOfAssembly(), and GetAllResiduesOfAssembly().
{
    return residues_;
}
int Assembly::GetSequenceNumber ()
Definition at line 148 of file assembly.cc.
{
    return sequence_number_;
}
string Assembly::GetSourceFile ()
Definition at line 168 of file assembly.cc.
Referenced by AddAssembly(), BuildStructure(), BuildStructureByLIBFileInformation(), BuildStructureByPDBFileInformation(), BuildStructureByPrepFileInformation(), and BuildStructureByTOPFileInformation().
{
    return source_file_;
}
gmml::InputFileType Assembly::GetSourceFileType ()
Definition at line 172 of file assembly.cc.
Referenced by BuildStructure(), and BuildStructureByOriginalFileBondingInformation().
{
    return source_file_type_;
}
double Assembly::GetTotalMass ()
Definition at line 152 of file assembly.cc.
{
    return total_mass_;
}
void Assembly::Print (std::ostream & out = std::cout)
Definition at line 3472 of file assembly.cc.
References MolecularModeling::Residue::Print(), and Print().
Referenced by Print().
{
    out << "===================== " << name_ << " ============================" << endl;
    out << "Source file: " << source_file_ << endl;
    if(assemblies_.size() != 0)
    {
        for(AssemblyVector::iterator it = assemblies_.begin(); it != assemblies_.end(); it++)
        {
            Assembly* assembly = (*it);
            assembly->Print(out);
        }
    }
    else
    {
        for(ResidueVector::iterator it = residues_.begin(); it != residues_.end(); it++)
        {
            Residue* residue = (*it);
            residue->Print(out);
        }
    }
}
void Assembly::SetAssemblies (AssemblyVector assemblies)
Definition at line 272 of file assembly.cc.
{
    assemblies_.clear();
    for(AssemblyVector::iterator it = assemblies.begin(); it != assemblies.end(); it++)
    {
        assemblies_.push_back(*it);
    }
}
void Assembly::SetCenterOfGeometry (Geometry::Coordinate center_of_geometry)
Definition at line 338 of file assembly.cc.
{
    center_of_geometry_ = center_of_geometry;
}
void Assembly::SetCenterOfMass (Geometry::Coordinate center_of_mass)
Definition at line 334 of file assembly.cc.
{
    center_of_mass_ = center_of_mass;
}
void Assembly::SetChemicalType (std::string chemical_type)
Definition at line 322 of file assembly.cc.
{
    chemical_type_ = chemical_type;
}
void Assembly::SetDescription (std::string description)
Definition at line 342 of file assembly.cc.
{
    description_ = description;
}
void Assembly::SetModelIndex (int model_index)
Definition at line 354 of file assembly.cc.
{
    model_index_ = model_index;
}
void Assembly::SetName (std::string name)
Definition at line 268 of file assembly.cc.
{
    name_ = name;
}
void Assembly::SetResidues (ResidueVector residues)
Definition at line 310 of file assembly.cc.
{
    residues_.clear();
    for(ResidueVector::iterator it = residues.begin(); it != residues.end(); it++)
    {
        residues_.push_back(*it);
    }
}
void Assembly::SetSequenceNumber (int sequence_number)
Definition at line 326 of file assembly.cc.
Referenced by AddAssembly().
{
    sequence_number_ = sequence_number;
}
void Assembly::SetSourceFile (std::string source_file)
Definition at line 346 of file assembly.cc.
{
    source_file_ = source_file;
}
void Assembly::SetSourceFileType (gmml::InputFileType source_file_type)
Definition at line 350 of file assembly.cc.
{
    source_file_type_ = source_file_type;
}
void Assembly::SetTtoalMass (double total_mass)
Definition at line 330 of file assembly.cc.
{
    total_mass_ = total_mass;
}
The documentation for this class was generated from the following files:
includes/MolecularModeling/assembly.hpp
src/MolecularModeling/assembly.cc