gmmlNew: PdbFileSpace::PdbSite Class Reference
PdbFileSpace::PdbSite Class Reference
#include <pdbsite.hpp>
Public Types
typedef std::vector
< PdbSiteResidue * > SiteResidueVector
Public Member Functions
PdbSite ()
PdbSite (std::stringstream &site_block)
std::string GetSiteId ()
SiteResidueVector GetResidues ()
int GetNumberOfResidues ()
void SetSiteId (const std::string site_id)
void SetResidues (SiteResidueVector residues)
void AddResidue (PdbSiteResidue *residue)
void SetNumberOfResidues (int number_of_residues)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 16 of file pdbsite.hpp.
Member Typedef Documentation
typedef std::vector< PdbSiteResidue* > PdbFileSpace::PdbSite::SiteResidueVector
Definition at line 25 of file pdbsite.hpp.
Constructor & Destructor Documentation
PdbSite::PdbSite ()
Definition at line 13 of file pdbsite.cc.
{}
PdbFileSpace::PdbSite::PdbSite (std::stringstream & site_block)
Member Function Documentation
void PdbSite::AddResidue (PdbSiteResidue * residue)
Definition at line 80 of file pdbsite.cc.
{
    residues_.push_back(residue);
}
int PdbSite::GetNumberOfResidues ()
Definition at line 60 of file pdbsite.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSiteCard().
{
    return number_of_residues_;
}
PdbSite::SiteResidueVector PdbSite::GetResidues ()
Definition at line 56 of file pdbsite.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSiteCard().
{
    return residues_;
}
string PdbSite::GetSiteId ()
Definition at line 52 of file pdbsite.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSiteCard().
{
    return site_id_;
}
void PdbSite::Print (std::ostream & out = std::cout)
Definition at line 96 of file pdbsite.cc.
References gmml::iNotSet.
Referenced by PdbFileSpace::PdbSiteCard::Print().
{
    out << "Site ID: " << site_id_
        << ", Number of Residues: ";
    if(number_of_residues_ != iNotSet)
        out << number_of_residues_;
    else
        out << " ";
    out << endl << "---------------- Residues ----------------" << endl;
    for(PdbSite::SiteResidueVector::iterator it = residues_.begin(); it != residues_.end(); it++)
    {
        (*it)->Print(out);
        out << endl;
    }
    out << endl;
}
void PdbSite::SetNumberOfResidues (int number_of_residues)
Definition at line 85 of file pdbsite.cc.
{
    number_of_residues_ = number_of_residues;
}
void PdbSite::SetResidues (SiteResidueVector residues)
Definition at line 72 of file pdbsite.cc.
{
    residues_.clear();
    for(SiteResidueVector::iterator it = residues.begin(); it != residues.end(); it++)
    {
        residues_.push_back(*it);
    }
}
void PdbSite::SetSiteId (const std::string site_id)
Definition at line 68 of file pdbsite.cc.
{
    site_id_ = site_id;
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbsite.hpp
src/FileSet/PdbFileSpace/pdbsite.cc