gmmlNew: PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom Class Reference
PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom Class Reference
#include <pdbpreprocessorunrecognizedheavyatom.hpp>
Public Member Functions
PdbPreprocessorUnrecognizedHeavyAtom ()
PdbPreprocessorUnrecognizedHeavyAtom (char residue_chain_id, int atom_serial_number, std::string atom_name, std::string residue_name, int residue_sequence_number, char residue_insertion_code, char residue_alternate_location)
char GetResidueChainId ()
int GetAtomSerialNumber ()
std::string GetAtomName ()
std::string GetResidueName ()
int GetResidueSequenceNumber ()
char GetResidueInsertionCode ()
char GetResidueAlternateLocation ()
void SetResidueChainId (char residue_chain_id)
void SetAtomSerialNumber (int atom_serial_number)
void SetAtomName (std::string atom_name)
void SetResidueName (std::string residue_name)
void SetResidueSequenceNumber (int residue_sequence_number)
void SetResidueInsertionCode (char residue_insertion_code)
void SetResidueAlternateLocation (char residue_alternate_location)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 9 of file pdbpreprocessorunrecognizedheavyatom.hpp.
Constructor & Destructor Documentation
PdbPreprocessorUnrecognizedHeavyAtom::PdbPreprocessorUnrecognizedHeavyAtom ()
Definition at line 10 of file pdbpreprocessorunrecognizedheavyatom.cc.
{}
PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::PdbPreprocessorUnrecognizedHeavyAtom (char residue_chain_id, int atom_serial_number, std::string atom_name, std::string residue_name, int residue_sequence_number, char residue_insertion_code, char residue_alternate_location)
Member Function Documentation
string PdbPreprocessorUnrecognizedHeavyAtom::GetAtomName ()
Definition at line 28 of file pdbpreprocessorunrecognizedheavyatom.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveUnknownHeavyAtoms().
{
    return atom_name_;
}
int PdbPreprocessorUnrecognizedHeavyAtom::GetAtomSerialNumber ()
Definition at line 24 of file pdbpreprocessorunrecognizedheavyatom.cc.
{
    return atom_serial_number_;
}
char PdbPreprocessorUnrecognizedHeavyAtom::GetResidueAlternateLocation ()
Definition at line 44 of file pdbpreprocessorunrecognizedheavyatom.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveResiduesOfUnknownHeavyAtoms(), and PdbPreprocessorSpace::PdbPreprocessor::RemoveUnknownHeavyAtoms().
{
    return residue_alternate_location_;
}
char PdbPreprocessorUnrecognizedHeavyAtom::GetResidueChainId ()
Definition at line 20 of file pdbpreprocessorunrecognizedheavyatom.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveResiduesOfUnknownHeavyAtoms(), and PdbPreprocessorSpace::PdbPreprocessor::RemoveUnknownHeavyAtoms().
{
    return residue_chain_id_;
}
char PdbPreprocessorUnrecognizedHeavyAtom::GetResidueInsertionCode ()
Definition at line 40 of file pdbpreprocessorunrecognizedheavyatom.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveResiduesOfUnknownHeavyAtoms(), and PdbPreprocessorSpace::PdbPreprocessor::RemoveUnknownHeavyAtoms().
{
    return residue_insertion_code_;
}
string PdbPreprocessorUnrecognizedHeavyAtom::GetResidueName ()
Definition at line 32 of file pdbpreprocessorunrecognizedheavyatom.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveResiduesOfUnknownHeavyAtoms(), and PdbPreprocessorSpace::PdbPreprocessor::RemoveUnknownHeavyAtoms().
{
    return residue_name_;
}
int PdbPreprocessorUnrecognizedHeavyAtom::GetResidueSequenceNumber ()
Definition at line 36 of file pdbpreprocessorunrecognizedheavyatom.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveResiduesOfUnknownHeavyAtoms(), and PdbPreprocessorSpace::PdbPreprocessor::RemoveUnknownHeavyAtoms().
{
    return residue_sequence_number_;
}
void PdbPreprocessorUnrecognizedHeavyAtom::Print (std::ostream & out = std::cout)
Definition at line 84 of file pdbpreprocessorunrecognizedheavyatom.cc.
{
    out << "Atom name: " << atom_name_
         << ", Serial number: " << atom_serial_number_
         << ", Chain id: " << residue_chain_id_
         << ", Residue name: " << residue_name_
         << ", Sequence number: " << residue_sequence_number_
         << ", Insertion code: " << residue_insertion_code_
         << ", Alternate location: " << residue_alternate_location_
         << endl;
}
void PdbPreprocessorUnrecognizedHeavyAtom::SetAtomName (std::string atom_name)
Definition at line 60 of file pdbpreprocessorunrecognizedheavyatom.cc.
{
    atom_name_ = atom_name;
}
void PdbPreprocessorUnrecognizedHeavyAtom::SetAtomSerialNumber (int atom_serial_number)
Definition at line 56 of file pdbpreprocessorunrecognizedheavyatom.cc.
{
    atom_serial_number_ = atom_serial_number;
}
void PdbPreprocessorUnrecognizedHeavyAtom::SetResidueAlternateLocation (char residue_alternate_location)
Definition at line 76 of file pdbpreprocessorunrecognizedheavyatom.cc.
{
    residue_alternate_location_ = residue_alternate_location;
}
void PdbPreprocessorUnrecognizedHeavyAtom::SetResidueChainId (char residue_chain_id)
Definition at line 52 of file pdbpreprocessorunrecognizedheavyatom.cc.
{
    residue_chain_id_ = residue_chain_id;
}
void PdbPreprocessorUnrecognizedHeavyAtom::SetResidueInsertionCode (char residue_insertion_code)
Definition at line 72 of file pdbpreprocessorunrecognizedheavyatom.cc.
{
    residue_insertion_code_ = residue_insertion_code;
}
void PdbPreprocessorUnrecognizedHeavyAtom::SetResidueName (std::string residue_name)
Definition at line 64 of file pdbpreprocessorunrecognizedheavyatom.cc.
{
    residue_name_ = residue_name;
}
void PdbPreprocessorUnrecognizedHeavyAtom::SetResidueSequenceNumber (int residue_sequence_number)
Definition at line 68 of file pdbpreprocessorunrecognizedheavyatom.cc.
{
    residue_sequence_number_ = residue_sequence_number;
}
The documentation for this class was generated from the following files:
includes/Resolver/PdbPreprocessor/pdbpreprocessorunrecognizedheavyatom.hpp
src/Resolver/PdbPreprocessor/pdbpreprocessorunrecognizedheavyatom.cc