gmmlNew: PdbFileSpace::PdbAtom Class Reference
PdbFileSpace::PdbAtom Class Reference
#include <pdbatom.hpp>
Public Member Functions
PdbAtom ()
PdbAtom (std::string &line)
PdbAtom (int atom_serial_number, std::string atom_name, char atom_alternate_location, std::string residue_name, char chain_id, int residue_sequence_number, char insertion_code, Geometry::Coordinate coordinate, double occupancy, double tempreture_factor, std::string element_symbol, std::string charge)
PdbAtom (char chain_id, std::string atom_name, std::string residue_name, int residue_sequence_number, char residue_insertion_code, char atom_alternate_location)
int GetAtomSerialNumber ()
std::string GetAtomName ()
char GetAtomAlternateLocation ()
std::string GetAtomResidueName ()
char GetAtomChainId ()
int GetAtomResidueSequenceNumber ()
char GetAtomInsertionCode ()
Geometry::Coordinate GetAtomOrthogonalCoordinate ()
double GetAtomOccupancy ()
double GetAtomTempretureFactor ()
std::string GetAtomElementSymbol ()
std::string GetAtomCharge ()
std::string GetAtomCardIndexInResidueSet ()
void SetAtomSerialNumber (int atom_serial_number)
void SetAtomName (const std::string atom_name)
void SetAtomAlternateLocation (char atom_alternate_location)
void SetAtomResidueName (const std::string atom_residue_name)
void SetAtomChainId (char atom_chain_id)
void SetAtomResidueSequenceNumber (int atom_residue_sequence_number)
void SetAtomInsertionCode (char atom_insertion_code)
void SetAtomOrthogonalCoordinate (Geometry::Coordinate atom_orthogonal_coordinate)
void SetAtomOccupancy (double atom_occupancy)
void SetAtomTempretureFactor (double atom_temperature_factor)
void SetAtomElementSymbol (const std::string atom_element_symbol)
void SetAtomCharge (const std::string atom_charge)
void SetAtomCardIndexInResidueSet (std::string atom_card_index_in_residue_sequence)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 14 of file pdbatom.hpp.
Constructor & Destructor Documentation
PdbAtom::PdbAtom ()
Definition at line 13 of file pdbatom.cc.
:atom_orthogonal_coordinate_() {}
PdbFileSpace::PdbAtom::PdbAtom (std::string & line)
PdbFileSpace::PdbAtom::PdbAtom (int atom_serial_number, std::string atom_name, char atom_alternate_location, std::string residue_name, char chain_id, int residue_sequence_number, char insertion_code, Geometry::Coordinate coordinate, double occupancy, double tempreture_factor, std::string element_symbol, std::string charge)
PdbFileSpace::PdbAtom::PdbAtom (char chain_id, std::string atom_name, std::string residue_name, int residue_sequence_number, char residue_insertion_code, char atom_alternate_location)
Member Function Documentation
char PdbAtom::GetAtomAlternateLocation ()
Definition at line 148 of file pdbatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildStructureByPDBFileInformation(), PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbFileSpace::PdbFile::GetAllAtomsInOrder(), PdbFileSpace::PdbFile::GetAllAtomsOfResidue(), PdbFileSpace::PdbFile::GetAllAtomsOfResidues(), PdbFileSpace::PdbFile::GetAllResidues(), PdbFileSpace::PdbFile::GetAllResiduesFromAtomCard(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return atom_alternate_location_;
}
string PdbAtom::GetAtomCardIndexInResidueSet ()
Definition at line 187 of file pdbatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile().
{
    return atom_card_index_in_residue_sequence_;
}
char PdbAtom::GetAtomChainId ()
Definition at line 156 of file pdbatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildStructureByPDBFileInformation(), PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbFileSpace::PdbFile::GetAllAtomsInOrder(), PdbFileSpace::PdbFile::GetAllAtomsOfResidue(), PdbFileSpace::PdbFile::GetAllAtomsOfResidues(), PdbFileSpace::PdbFile::GetAllResidues(), PdbFileSpace::PdbFile::GetAllResiduesFromAtomCard(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return atom_chain_id_;
}
string PdbAtom::GetAtomCharge ()
Definition at line 184 of file pdbatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), and PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber().
{
    return atom_charge_;
}
string PdbAtom::GetAtomElementSymbol ()
Definition at line 180 of file pdbatom.cc.
Referenced by PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), and PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber().
{
    return atom_element_symbol_;
}
char PdbAtom::GetAtomInsertionCode ()
Definition at line 164 of file pdbatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildStructureByPDBFileInformation(), PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbFileSpace::PdbFile::GetAllAtomsInOrder(), PdbFileSpace::PdbFile::GetAllAtomsOfResidue(), PdbFileSpace::PdbFile::GetAllAtomsOfResidues(), PdbFileSpace::PdbFile::GetAllResidues(), PdbFileSpace::PdbFile::GetAllResiduesFromAtomCard(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return atom_insertion_code_;
}
string PdbAtom::GetAtomName ()
Definition at line 144 of file pdbatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildStructureByPDBFileInformation(), PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::GetAllAtomNamesOfResidue(), PdbPreprocessorSpace::PdbPreprocessor::GetRemovedHydrogensOfResidue(), PdbPreprocessorSpace::PdbPreprocessor::GetUnknownHeavyAtomsOfResidue(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), and PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber().
{
    return atom_name_;
}
double PdbAtom::GetAtomOccupancy ()
Definition at line 172 of file pdbatom.cc.
Referenced by PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), and PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber().
{
    return atom_occupancy_;
}
Geometry::Coordinate PdbAtom::GetAtomOrthogonalCoordinate ()
Definition at line 168 of file pdbatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), PdbPreprocessorSpace::PdbPreprocessor::GetDistanceofCYS(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), and PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber().
{
    return atom_orthogonal_coordinate_;
}
string PdbAtom::GetAtomResidueName ()
Definition at line 152 of file pdbatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildStructureByPDBFileInformation(), PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbFileSpace::PdbFile::GetAllAtomsInOrder(), PdbFileSpace::PdbFile::GetAllAtomsOfResidue(), PdbFileSpace::PdbFile::GetAllAtomsOfResidues(), PdbFileSpace::PdbFile::GetAllResidueNames(), PdbFileSpace::PdbFile::GetAllResidueNamesFromAtomCard(), PdbFileSpace::PdbFile::GetAllResidues(), PdbFileSpace::PdbFile::GetAllResiduesFromAtomCard(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return atom_residue_name_;
}
int PdbAtom::GetAtomResidueSequenceNumber ()
Definition at line 160 of file pdbatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildStructureByPDBFileInformation(), PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbFileSpace::PdbFile::GetAllAtomsInOrder(), PdbFileSpace::PdbFile::GetAllAtomsOfResidue(), PdbFileSpace::PdbFile::GetAllAtomsOfResidues(), PdbFileSpace::PdbFile::GetAllResidues(), PdbFileSpace::PdbFile::GetAllResiduesFromAtomCard(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return atom_residue_sequence_number_;
}
int PdbAtom::GetAtomSerialNumber ()
Definition at line 140 of file pdbatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildStructureByPDBFileInformation(), PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return atom_serial_number_;
}
double PdbAtom::GetAtomTempretureFactor ()
Definition at line 176 of file pdbatom.cc.
Referenced by PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), and PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber().
{
    return atom_temperature_factor_;
}
void PdbAtom::Print (std::ostream & out = std::cout)
Definition at line 250 of file pdbatom.cc.
References gmml::dNotSet, gmml::iNotSet, and Geometry::Coordinate::Print().
{
    out << "Atom Serial Number: ";
    if(atom_serial_number_ == iNotSet)
        out << " ";
    else
        out << atom_serial_number_;
    out << ", Atom Name: " << atom_name_
        << ", Atom Alternate Location: " << atom_alternate_location_
        << ", Atom Residue Name: " << atom_residue_name_
        << ", Atom Chain ID: " << atom_chain_id_
        << ", Atom Residue Sequence Number: ";
    if(atom_residue_sequence_number_ == iNotSet)
        out << " ";
    else
        out << atom_residue_sequence_number_;
    out << ", Atom Inserion Code: " << atom_insertion_code_
        << ", Atom Orthogonal Coordinate: ";
    atom_orthogonal_coordinate_.Print(out);
    out << ", Atom Occupancy: ";
    if(atom_occupancy_ == dNotSet)
        out << " ";
    else
        out << atom_occupancy_;
    out << ", Atom Tempreture Factor: ";
    if(atom_temperature_factor_ == dNotSet)
        out << " ";
    else
        out << atom_temperature_factor_;
    out << ", Atom Element Symbol: " << atom_element_symbol_
        << ", Atom Charge: " << atom_charge_ << endl;
}
void PdbAtom::SetAtomAlternateLocation (char atom_alternate_location)
Definition at line 203 of file pdbatom.cc.
{
    atom_alternate_location_ = atom_alternate_location;
}
void PdbAtom::SetAtomCardIndexInResidueSet (std::string atom_card_index_in_residue_sequence)
Definition at line 242 of file pdbatom.cc.
{
    atom_card_index_in_residue_sequence_ = atom_card_index_in_residue_sequence;
}
void PdbAtom::SetAtomChainId (char atom_chain_id)
Definition at line 211 of file pdbatom.cc.
{
    atom_chain_id_ = atom_chain_id;
}
void PdbAtom::SetAtomCharge (const std::string atom_charge)
Definition at line 239 of file pdbatom.cc.
{
    atom_charge_ = atom_charge;
}
void PdbAtom::SetAtomElementSymbol (const std::string atom_element_symbol)
Definition at line 235 of file pdbatom.cc.
{
    atom_element_symbol_ = atom_element_symbol;
}
void PdbAtom::SetAtomInsertionCode (char atom_insertion_code)
Definition at line 219 of file pdbatom.cc.
{
    atom_insertion_code_ = atom_insertion_code;
}
void PdbAtom::SetAtomName (const std::string atom_name)
Definition at line 199 of file pdbatom.cc.
{
    atom_name_ = atom_name;
}
void PdbAtom::SetAtomOccupancy (double atom_occupancy)
Definition at line 227 of file pdbatom.cc.
{
    atom_occupancy_ = atom_occupancy;
}
void PdbAtom::SetAtomOrthogonalCoordinate (Geometry::Coordinate atom_orthogonal_coordinate)
Definition at line 223 of file pdbatom.cc.
{
    atom_orthogonal_coordinate_ = atom_orthogonal_coordinate;
}
void PdbAtom::SetAtomResidueName (const std::string atom_residue_name)
Definition at line 207 of file pdbatom.cc.
Referenced by PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    atom_residue_name_ = atom_residue_name;
}
void PdbAtom::SetAtomResidueSequenceNumber (int atom_residue_sequence_number)
Definition at line 215 of file pdbatom.cc.
{
    atom_residue_sequence_number_ = atom_residue_sequence_number;
}
void PdbAtom::SetAtomSerialNumber (int atom_serial_number)
Definition at line 195 of file pdbatom.cc.
Referenced by PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), and PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber().
{
    atom_serial_number_ = atom_serial_number;
}
void PdbAtom::SetAtomTempretureFactor (double atom_temperature_factor)
Definition at line 231 of file pdbatom.cc.
{
    atom_temperature_factor_ = atom_temperature_factor;
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbatom.hpp
src/FileSet/PdbFileSpace/pdbatom.cc