gmmlNew: PrepFileSpace::PrepFileResidue Class Reference
PrepFileSpace::PrepFileResidue Class Reference
#include <prepfileresidue.hpp>
Public Types
typedef std::map< int, int > Loop
typedef std::vector< std::string > Dihedral
typedef std::vector
< PrepFileAtom * > PrepFileAtomVector
typedef std::vector< Dihedral > DihedralVector
typedef std::map< int,
std::vector< int > > BondedAtomIndexMap
Public Member Functions
PrepFileResidue ()
PrepFileResidue * LoadFromStream (std::ifstream &in_file)
std::string ExtractResidueName (std::istream &ss)
Return residue name from a stream line which is the first column of the 3rd line in each residue section.
CoordinateType ExtractResidueCoordinateType (std::istream &ss)
Return coordinate type from a stream line which is the 2nd column of the 3rd line in each residue section.
OutputFormat ExtractResidueOutputFormat (std::istream &ss)
Return output format from a stream line which is the 3rd column of the 3rd line in each residue section.
GeometryType ExtractResidueGeometryType (std::istream &ss)
Return geometry type from a stream line which is the first column of the 4th line in each residue section.
DummyAtomOmission ExtractResidueDummyAtomOmission (std::istream &ss)
Return dummy atom omission from a stream line which is the 2nd column of the 4th line in each residue section.
DummyAtomPosition ExtractResidueDummyAtomPosition (std::istream &ss)
Return dummy atom position from a stream line which is the 4th column of the 4th line in each residue section.
SectionType ExtractSectionType (std::string &line)
Return a corresponding title from a stream line which may appear in each residue section.
Loop ExtractLoops (std::ifstream &in_file)
Parse the loop section of each residue section and return a loop map.
DihedralVector ExtractImproperDihedral (std::ifstream &in_file)
Parse the improper dihedral section of each residue section and return a vector of improper dihedrals.
int GetAtomIndexByName (const std::string &name)
std::string GetTitle ()
std::string GetName ()
CoordinateType GetCoordinateType ()
OutputFormat GetOutputFormat ()
GeometryType GetGeometryType ()
DummyAtomOmission GetDummyAtomOmission ()
std::string GetDummyAtomType ()
DummyAtomPosition GetDummyAtomPosition ()
double GetCharge ()
PrepFileAtomVector GetAtoms ()
DihedralVector GetImproperDihedrals ()
Loop GetLoops ()
PrepFileAtom * GetPrepAtomByName (std::string atom_name)
std::string GetAtomNameByIndex (int atom_index)
std::string GetStringFormatOfCoordinateType (CoordinateType coordinate_type)
std::string GetStringFormatOfCoordinateType ()
std::string GetStringFromatOfOutputFormat (OutputFormat output_format)
std::string GetStringFromatOfOutputFormat ()
std::string GetStringFormatOfGeometryType (GeometryType geometry_type)
std::string GetStringFormatOfGeometryType ()
std::string GetStringFormatOfDummyAtomPosition (DummyAtomPosition dummy_atom_position)
std::string GetStringFormatOfDummyAtomPosition ()
std::string GetStringFormatOfDummyAtomOmission (DummyAtomOmission dummy_atom_omission)
std::string GetStringFormatOfDummyAtomOmission ()
std::string GetStringFormatOfSectionType (SectionType section_type)
CoordinateType GetCoordinateTypeFromString (std::string coordinate_type)
OutputFormat GetOutputFormatFromString (std::string output_format)
GeometryType GetGeometryTypeFromString (std::string geometry_type)
DummyAtomPosition GetDummyAtomPositionFromString (std::string dummy_atom_position)
DummyAtomOmission GetDummyAtomOmissionFromString (std::string dummy_atom_omission)
SectionType GetSectionTypeFromString (std::string section_type)
BondedAtomIndexMap GetBondingsOfResidue ()
void SetTitle (std::string title)
void SetName (std::string name)
void SetCoordinateType (CoordinateType coordinate_type)
void SetOutputFormat (OutputFormat output_format)
void SetBondIndex (GeometryType geometry_type)
void GetDummyAtomOmission (DummyAtomOmission dummy_atom_omission)
void SetDummyAtomType (std::string dummy_atom_type)
void SetDummyAtomPosition (DummyAtomPosition dummy_atom_position)
void SetCharge (double charge)
void SetAtoms (PrepFileAtomVector atoms)
void AddAtom (PrepFileAtom *atom)
void SetImproperDihedrals (DihedralVector improper_dihedrals)
void AddImproperDihedral (Dihedral improper_dihedral)
void SetLoops (Loop loops)
void Print (std::ostream &out=std::cout)
Public Attributes
std::string title_
std::string name_
CoordinateType coordinate_type_
OutputFormat output_format_
GeometryType geometry_type_
DummyAtomOmission dummy_atom_omission_
std::string dummy_atom_type_
DummyAtomPosition dummy_atom_position_
double charge_
PrepFileAtomVector atoms_
DihedralVector improper_dihedrals_
Loop loops_
Detailed Description
Definition at line 37 of file prepfileresidue.hpp.
Member Typedef Documentation
typedef std::map<int, std::vector<int> > PrepFileSpace::PrepFileResidue::BondedAtomIndexMap
Definition at line 62 of file prepfileresidue.hpp.
typedef std::vector<std::string> PrepFileSpace::PrepFileResidue::Dihedral
Definition at line 50 of file prepfileresidue.hpp.
typedef std::vector<Dihedral> PrepFileSpace::PrepFileResidue::DihedralVector
Definition at line 58 of file prepfileresidue.hpp.
typedef std::map<int, int> PrepFileSpace::PrepFileResidue::Loop
Definition at line 46 of file prepfileresidue.hpp.
typedef std::vector<PrepFileAtom*> PrepFileSpace::PrepFileResidue::PrepFileAtomVector
Definition at line 54 of file prepfileresidue.hpp.
Constructor & Destructor Documentation
PrepFileResidue::PrepFileResidue ()
Definition at line 18 of file prepfileresidue.cc.
{}
Member Function Documentation
void PrepFileResidue::AddAtom (PrepFileAtom * atom)
Definition at line 479 of file prepfileresidue.cc.
{
    atoms_.push_back(atom);
}
void PrepFileResidue::AddImproperDihedral (Dihedral improper_dihedral)
Definition at line 491 of file prepfileresidue.cc.
{
    improper_dihedrals_.push_back(improper_dihedral);
}
vector< PrepFileResidue::Dihedral > PrepFileResidue::ExtractImproperDihedral (std::ifstream & in_file)
Parse the improper dihedral section of each residue section and return a vector of improper dihedrals.
Read file until blank line which determines the end of the section
Extract improper atom types involving in a dihedral from each line
Push all atoms into a vector of atom types
Create a new dihedral into the vector of dihedrals
Read the next line
Definition at line 706 of file prepfileresidue.cc.
References gmml::Trim().
Referenced by LoadFromStream().
{
    string line;
    std::stringstream ss;
    vector<Dihedral> dihedrals;
    getline(in_file, line);
    while (!Trim(line).empty())                         /// Read file until blank line which determines the end of the section
    {
        string atom_names[4];
        Dihedral dihedral;
        ss.clear();
        ss.str(line);
        /// Extract improper atom types involving in a dihedral from each line
        ss >> atom_names[0]
           >> atom_names[1]
           >> atom_names[2]
           >> atom_names[3];
        /// Push all atoms into a vector of atom types
        for(int i = 0; i < 4; i++)
        {
            dihedral.push_back(atom_names[i]);
        }
        dihedrals.push_back(dihedral);                  /// Create a new dihedral into the vector of dihedrals
        getline(in_file, line);                         /// Read the next line
    }
    return dihedrals;
}
PrepFileResidue::Loop PrepFileResidue::ExtractLoops (std::ifstream & in_file)
Parse the loop section of each residue section and return a loop map.
Read file until blank line which determines the end of the section
Create a stream from the read line
Extract atom names from the stream
Extract index of the first atom in the loop
Extract index of the second atom in the loop
throw error here, unknown atom names
Add a new entry into the loop map of the residue
Definition at line 678 of file prepfileresidue.cc.
References gmml::Trim().
Referenced by LoadFromStream().
{
    Loop loops;
    string line;
    std::stringstream ss;
    getline(in_file, line);
    while (!Trim(line).empty())                         /// Read file until blank line which determines the end of the section
    {
        ss.clear();
        ss.str(line);                                   /// Create a stream from the read line
        string atom_names[2];
        ss >> atom_names[0] >> atom_names[1];           /// Extract atom names from the stream
        int from = GetAtomIndexByName(atom_names[0]);   /// Extract index of the first atom in the loop
        int to = GetAtomIndexByName(atom_names[1]);     /// Extract index of the second atom in the loop
        if (from == -1 || to == -1)
        {
            /// throw error here, unknown atom names
        }
        loops[from] = to;                               /// Add a new entry into the loop map of the residue
        getline(in_file, line);
    }
    return loops;
}
CoordinateType PrepFileResidue::ExtractResidueCoordinateType (std::istream & ss)
Return coordinate type from a stream line which is the 2nd column of the 3rd line in each residue section.
Definition at line 611 of file prepfileresidue.cc.
References PrepFileSpace::kINT, and PrepFileSpace::kXYZ.
{
    string s;
    ss >> s;
    if (s == "XYZ")
        return kXYZ;
    else
        return kINT;
}
DummyAtomOmission PrepFileResidue::ExtractResidueDummyAtomOmission (std::istream & ss)
Return dummy atom omission from a stream line which is the 2nd column of the 4th line in each residue section.
Definition at line 644 of file prepfileresidue.cc.
References PrepFileSpace::kNomit, and PrepFileSpace::kOmit.
{
    string s;
    ss >> s;
    if (s == "NOMIT")
        return kNomit;
    else
        return kOmit;
}
DummyAtomPosition PrepFileResidue::ExtractResidueDummyAtomPosition (std::istream & ss)
Return dummy atom position from a stream line which is the 4th column of the 4th line in each residue section.
Definition at line 655 of file prepfileresidue.cc.
References PrepFileSpace::kPositionAll, and PrepFileSpace::kPositionBeg.
{
    string s;
    ss >> s;
    if (s == "ALL")
        return kPositionAll;
    else
        return kPositionBeg;
}
GeometryType PrepFileResidue::ExtractResidueGeometryType (std::istream & ss)
Return geometry type from a stream line which is the first column of the 4th line in each residue section.
Definition at line 633 of file prepfileresidue.cc.
References PrepFileSpace::kGeometryChange, and PrepFileSpace::kGeometryCorrect.
{
    string s;
    ss >> s;
    if (s == "CHANGE")
        return kGeometryChange;
    else
        return kGeometryCorrect;
}
std::string PrepFileResidue::ExtractResidueName (std::istream & ss)
Return residue name from a stream line which is the first column of the 3rd line in each residue section.
Definition at line 603 of file prepfileresidue.cc.
{
    string name;
    ss >> name;
    return name;
}
OutputFormat PrepFileResidue::ExtractResidueOutputFormat (std::istream & ss)
Return output format from a stream line which is the 3rd column of the 3rd line in each residue section.
Definition at line 622 of file prepfileresidue.cc.
References PrepFileSpace::kBinary, and PrepFileSpace::kFormatted.
{
    int val;
    ss >> val;
    if (val == 1)
        return kBinary;
    else
        return kFormatted;
}
SectionType PrepFileResidue::ExtractSectionType (std::string & line)
Return a corresponding title from a stream line which may appear in each residue section.
Definition at line 666 of file prepfileresidue.cc.
References PrepFileSpace::kSectionDone, PrepFileSpace::kSectionImproper, PrepFileSpace::kSectionLoop, and PrepFileSpace::kSectionOther.
{
    if (line == "LOOP")
        return kSectionLoop;
    else if (line == "IMPROPER")
        return kSectionImproper;
    else if (line == "DONE")
        return kSectionDone;
    return kSectionOther;
}
int PrepFileResidue::GetAtomIndexByName (const std::string & name)
Return the index of an atom in a specific residue by a given name
Definition at line 24 of file prepfileresidue.cc.
Referenced by MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), and MolecularModeling::Assembly::BuildStructureByPrepFileInformation().
{
    for (unsigned int i = 0; i < atoms_.size(); i++)
        if (name.compare(atoms_[i]->GetName()) == 0)
            return atoms_[i]->GetIndex();
    return -1;
}
string PrepFileResidue::GetAtomNameByIndex (int atom_index)
Definition at line 226 of file prepfileresidue.cc.
References PrepFileSpace::PrepFileAtom::GetIndex(), and PrepFileSpace::PrepFileAtom::GetName().
Referenced by PrepFileSpace::PrepFile::BuildPrepFile(), MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), and MolecularModeling::Assembly::BuildStructureByPrepFileInformation().
{
    for(PrepFileAtomVector::iterator it = atoms_.begin(); it != atoms_.end(); it++)
    {
        PrepFileAtom* prep_file_atom = (*it);
        if(prep_file_atom->GetIndex() == atom_index)
            return prep_file_atom->GetName();
    }
    return NULL;
}
PrepFileResidue::PrepFileAtomVector PrepFileResidue::GetAtoms ()
Definition at line 68 of file prepfileresidue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), PrepFileSpace::PrepFile::BuildPrepFile(), and PrepFileSpace::PrepFile::GetAllAtomNamesOfResidue().
{
    return atoms_;
}
PrepFileResidue::BondedAtomIndexMap PrepFileResidue::GetBondingsOfResidue ()
Definition at line 90 of file prepfileresidue.cc.
References PrepFileSpace::PrepFileAtom::GetIndex(), PrepFileSpace::PrepFileAtom::GetTopologicalType(), PrepFileSpace::PrepFileAtom::GetType(), PrepFileSpace::kTopType3, PrepFileSpace::kTopTypeB, PrepFileSpace::kTopTypeE, PrepFileSpace::kTopTypeM, and PrepFileSpace::kTopTypeS.
Referenced by MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), and MolecularModeling::Assembly::BuildStructureByPrepFileInformation().
{
    BondedAtomIndexMap bonded_atoms_map = BondedAtomIndexMap();
    vector<PrepFileAtom*> stack = vector<PrepFileAtom*>();
    vector<int> number_of_bonds = vector<int>();
    for(PrepFileAtomVector::iterator it = atoms_.begin(); it != atoms_.end(); it++)
    {
        PrepFileAtom* atom = (*it);
        if(stack.empty())
        {
            if(atom->GetTopologicalType() == kTopTypeM || atom->GetTopologicalType() == kTopTypeS
                    || atom->GetTopologicalType() == kTopTypeB || atom->GetTopologicalType() == kTopType3)
            {
                stack.push_back(atom);
                if(atom->GetTopologicalType() == kTopTypeM)
                    number_of_bonds.push_back(4);
                if(atom->GetTopologicalType() == kTopTypeS)
                    number_of_bonds.push_back(2);
                if(atom->GetTopologicalType() == kTopTypeB)
                    number_of_bonds.push_back(3);
                if(atom->GetTopologicalType() == kTopType3)
                    number_of_bonds.push_back(4);
            }
        }
        if(!stack.empty())
        {
            if(atom->GetTopologicalType() == kTopTypeE)
            {
                PrepFileAtom* top_of_stack_atom = stack.at(stack.size()-1);
                bonded_atoms_map[top_of_stack_atom->GetIndex()].push_back(atom->GetIndex());
                bonded_atoms_map[atom->GetIndex()].push_back(top_of_stack_atom->GetIndex());
                number_of_bonds.at(number_of_bonds.size()-1)--;
                if(number_of_bonds.at(number_of_bonds.size()-1) == 0)
                {
                    number_of_bonds.pop_back();
                    stack.pop_back();
                }
            }
            if(atom->GetTopologicalType() == kTopTypeM)
            {
                PrepFileAtom* top_of_stack_atom = stack.at(stack.size()-1);
                if(top_of_stack_atom->GetTopologicalType() == kTopTypeM)
                {
                    if(top_of_stack_atom->GetType().compare(this->GetDummyAtomType()) == 0)
                    {
                        bonded_atoms_map[top_of_stack_atom->GetIndex()].push_back(atom->GetIndex());
                        bonded_atoms_map[atom->GetIndex()].push_back(top_of_stack_atom->GetIndex());
                        stack.pop_back();
                        number_of_bonds.pop_back();
                        stack.push_back(atom);
                        number_of_bonds.push_back(4);
                    }
                    else
                    {
                        bonded_atoms_map[top_of_stack_atom->GetIndex()].push_back(atom->GetIndex());
                        bonded_atoms_map[atom->GetIndex()].push_back(top_of_stack_atom->GetIndex());
                        number_of_bonds.at(number_of_bonds.size()-1)--;
                        if(number_of_bonds.at(number_of_bonds.size()-1) == 0)
{
                            number_of_bonds.pop_back();
                            stack.pop_back();
                        }
                        stack.push_back(atom);
                        number_of_bonds.push_back(3);
                    }
                }
                if(top_of_stack_atom->GetTopologicalType() == kTopTypeS || top_of_stack_atom->GetTopologicalType() == kTopTypeB
                        || top_of_stack_atom->GetTopologicalType() == kTopType3)
                {
                    bonded_atoms_map[top_of_stack_atom->GetIndex()].push_back(atom->GetIndex());
                    bonded_atoms_map[atom->GetIndex()].push_back(top_of_stack_atom->GetIndex());
                    number_of_bonds.at(number_of_bonds.size()-1)--;
                    if(number_of_bonds.at(number_of_bonds.size()-1) == 0)
                    {
                        number_of_bonds.pop_back();
                        stack.pop_back();
                    }
                    stack.push_back(atom);
                    number_of_bonds.push_back(3);
                }
            }
            if(atom->GetTopologicalType() == kTopTypeS)
            {
                PrepFileAtom* top_of_stack_atom = stack.at(stack.size()-1);
                bonded_atoms_map[top_of_stack_atom->GetIndex()].push_back(atom->GetIndex());
                bonded_atoms_map[atom->GetIndex()].push_back(top_of_stack_atom->GetIndex());
                number_of_bonds.at(number_of_bonds.size()-1)--;
                if(number_of_bonds.at(number_of_bonds.size()-1) == 0)
                {
                    number_of_bonds.pop_back();
                    stack.pop_back();
                }
                stack.push_back(atom);
                number_of_bonds.push_back(1);
            }
            if(atom->GetTopologicalType() == kTopTypeB)
            {
                PrepFileAtom* top_of_stack_atom = stack.at(stack.size()-1);
                bonded_atoms_map[top_of_stack_atom->GetIndex()].push_back(atom->GetIndex());
                bonded_atoms_map[atom->GetIndex()].push_back(top_of_stack_atom->GetIndex());
                number_of_bonds.at(number_of_bonds.size()-1)--;
                if(number_of_bonds.at(number_of_bonds.size()-1) == 0)
                {
                    number_of_bonds.pop_back();
                    stack.pop_back();
                }
                stack.push_back(atom);
                number_of_bonds.push_back(2);
            }
            if(atom->GetTopologicalType() == kTopType3)
            {
                PrepFileAtom* top_of_stack_atom = stack.at(stack.size()-1);
                bonded_atoms_map[top_of_stack_atom->GetIndex()].push_back(atom->GetIndex());
                bonded_atoms_map[atom->GetIndex()].push_back(top_of_stack_atom->GetIndex());
                number_of_bonds.at(number_of_bonds.size()-1)--;
                if(number_of_bonds.at(number_of_bonds.size()-1) == 0)
                {
                    number_of_bonds.pop_back();
                    stack.pop_back();
                }
                stack.push_back(atom);
                number_of_bonds.push_back(3);
            }
        }
    }
    for(Loop::iterator it = loops_.begin(); it != loops_.end(); it++)
    {
        int from = (*it).first;
        int to = (*it).second;
        bonded_atoms_map[from].push_back(to);
        bonded_atoms_map[to].push_back(from);
    }
    return bonded_atoms_map;
}
double PrepFileResidue::GetCharge ()
Definition at line 64 of file prepfileresidue.cc.
Referenced by PrepFileSpace::PrepFile::BuildPrepFile().
{
    return charge_;
}
CoordinateType PrepFileResidue::GetCoordinateType ()
Definition at line 40 of file prepfileresidue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPrepFile().
{
    return coordinate_type_;
}
CoordinateType PrepFileResidue::GetCoordinateTypeFromString (std::string coordinate_type)
Definition at line 372 of file prepfileresidue.cc.
References PrepFileSpace::kINT, and PrepFileSpace::kXYZ.
{
    if(coordinate_type.compare("INT") == 0)
        return kINT;
    if(coordinate_type.compare("XYZ") == 0)
        return kXYZ;
    else
        return kINT;
}
DummyAtomOmission PrepFileResidue::GetDummyAtomOmission ()
Definition at line 52 of file prepfileresidue.cc.
{
    return dummy_atom_omission_;
}
void PrepFileResidue::GetDummyAtomOmission (DummyAtomOmission dummy_atom_omission)
Definition at line 455 of file prepfileresidue.cc.
{
    dummy_atom_omission_ = dummy_atom_omission;
}
DummyAtomOmission PrepFileResidue::GetDummyAtomOmissionFromString (std::string dummy_atom_omission)
Definition at line 408 of file prepfileresidue.cc.
References PrepFileSpace::kNomit, and PrepFileSpace::kOmit.
{
    if(dummy_atom_omission.compare("Omit") == 0)
        return kOmit;
    if(dummy_atom_omission.compare("Nomit") == 0)
        return kNomit;
    else
        return kOmit;
}
DummyAtomPosition PrepFileResidue::GetDummyAtomPosition ()
Definition at line 60 of file prepfileresidue.cc.
{
    return dummy_atom_position_;
}
DummyAtomPosition PrepFileResidue::GetDummyAtomPositionFromString (std::string dummy_atom_position)
Definition at line 399 of file prepfileresidue.cc.
References PrepFileSpace::kPositionAll, and PrepFileSpace::kPositionBeg.
{
    if(dummy_atom_position.compare("PositionAll") == 0)
        return kPositionAll;
    if(dummy_atom_position.compare("PositionBeg") == 0)
        return kPositionBeg;
    else
        return kPositionBeg;
}
string PrepFileResidue::GetDummyAtomType ()
Definition at line 56 of file prepfileresidue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), and PrepFileSpace::PrepFile::BuildPrepFile().
{
    return dummy_atom_type_;
}
GeometryType PrepFileResidue::GetGeometryType ()
Definition at line 48 of file prepfileresidue.cc.
{
    return geometry_type_;
}
GeometryType PrepFileResidue::GetGeometryTypeFromString (std::string geometry_type)
Definition at line 390 of file prepfileresidue.cc.
References PrepFileSpace::kGeometryChange, and PrepFileSpace::kGeometryCorrect.
{
    if(geometry_type.compare("GeometryCorrect") == 0)
        return kGeometryCorrect;
    if(geometry_type.compare("GeometryChange") == 0)
        return kGeometryChange;
    else
        return kGeometryCorrect;
}
PrepFileResidue::DihedralVector PrepFileResidue::GetImproperDihedrals ()
Definition at line 72 of file prepfileresidue.cc.
Referenced by PrepFileSpace::PrepFile::BuildPrepFile().
{
    return improper_dihedrals_;
}
PrepFileResidue::Loop PrepFileResidue::GetLoops ()
Definition at line 76 of file prepfileresidue.cc.
Referenced by PrepFileSpace::PrepFile::BuildPrepFile().
{
    return loops_;
}
string PrepFileResidue::GetName ()
Definition at line 36 of file prepfileresidue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), PrepFileSpace::PrepFile::BuildPrepFile(), MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), and MolecularModeling::Assembly::BuildStructureByPrepFileInformation().
{
    return name_;
}
OutputFormat PrepFileResidue::GetOutputFormat ()
Definition at line 44 of file prepfileresidue.cc.
Referenced by PrepFileSpace::PrepFile::BuildPrepFile().
{
    return output_format_;
}
OutputFormat PrepFileResidue::GetOutputFormatFromString (std::string output_format)
Definition at line 381 of file prepfileresidue.cc.
References PrepFileSpace::kBinary, and PrepFileSpace::kFormatted.
{
    if(output_format.compare("Formatted") == 0)
        return kFormatted;
    if(output_format.compare("Binary") == 0)
        return kBinary;
    else
        return kBinary;
}
PrepFileAtom * PrepFileResidue::GetPrepAtomByName (std::string atom_name)
Definition at line 79 of file prepfileresidue.cc.
References PrepFileSpace::PrepFileAtom::GetName().
Referenced by MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), and MolecularModeling::Assembly::BuildStructureByPrepFileInformation().
{
    for(PrepFileAtomVector::iterator it = atoms_.begin(); it != atoms_.end(); it++)
    {
        PrepFileAtom* prep_file_atom = (*it);
        string prep_file_atom_name = prep_file_atom->GetName();
        if(prep_file_atom_name.compare(atom_name) == 0)
            return prep_file_atom;
    }
    return NULL;
}
SectionType PrepFileResidue::GetSectionTypeFromString (std::string section_type)
Definition at line 417 of file prepfileresidue.cc.
References PrepFileSpace::kSectionDone, PrepFileSpace::kSectionImproper, PrepFileSpace::kSectionLoop, and PrepFileSpace::kSectionOther.
{
    if(section_type.compare("SectionLoop") == 0)
        return kSectionLoop;
    if(section_type.compare("SectionImproper") == 0)
        return kSectionImproper;
    if(section_type.compare("SectionDone") == 0)
        return kSectionDone;
    if(section_type.compare("SectionOther") == 0)
        return kSectionOther;
    else
        return kSectionOther;
}
string PrepFileResidue::GetStringFormatOfCoordinateType (CoordinateType coordinate_type)
Definition at line 236 of file prepfileresidue.cc.
References PrepFileSpace::kINT, and PrepFileSpace::kXYZ.
Referenced by PrepFileSpace::PrepFile::BuildPrepFile().
{
    switch(coordinate_type)
    {
        case kINT:
            return "INT";
        case kXYZ:
            return "XYZ";
        default:
            return "";
    }
}
string PrepFileResidue::GetStringFormatOfCoordinateType ()
Definition at line 248 of file prepfileresidue.cc.
References PrepFileSpace::kINT, and PrepFileSpace::kXYZ.
{
    switch(coordinate_type_)
    {
        case kINT:
            return "INT";
        case kXYZ:
            return "XYZ";
        default:
            return "";
    }
}
string PrepFileResidue::GetStringFormatOfDummyAtomOmission (DummyAtomOmission dummy_atom_omission)
Definition at line 332 of file prepfileresidue.cc.
References PrepFileSpace::kNomit, and PrepFileSpace::kOmit.
Referenced by PrepFileSpace::PrepFile::BuildPrepFile().
{
    switch(dummy_atom_omission)
    {
        case kOmit:
            return "OMIT";
        case kNomit:
            return "NOMIT";
        default:
            return "";
    }
}
string PrepFileResidue::GetStringFormatOfDummyAtomOmission ()
Definition at line 344 of file prepfileresidue.cc.
References PrepFileSpace::kNomit, and PrepFileSpace::kOmit.
{
    switch(dummy_atom_omission_)
    {
        case kOmit:
            return "OMIT";
        case kNomit:
            return "NOMIT";
        default:
            return "";
    }
}
string PrepFileResidue::GetStringFormatOfDummyAtomPosition (DummyAtomPosition dummy_atom_position)
Definition at line 308 of file prepfileresidue.cc.
References PrepFileSpace::kPositionAll, and PrepFileSpace::kPositionBeg.
Referenced by PrepFileSpace::PrepFile::BuildPrepFile().
{
    switch(dummy_atom_position)
    {
        case kPositionAll:
            return "ALL";
        case kPositionBeg:
            return "BEG";
        default:
            return "";
    }
}
string PrepFileResidue::GetStringFormatOfDummyAtomPosition ()
Definition at line 320 of file prepfileresidue.cc.
References PrepFileSpace::kPositionAll, and PrepFileSpace::kPositionBeg.
{
    switch(dummy_atom_position_)
    {
        case kPositionAll:
            return "ALL";
        case kPositionBeg:
            return "BEG";
        default:
            return "";
    }
}
string PrepFileResidue::GetStringFormatOfGeometryType (GeometryType geometry_type)
Definition at line 284 of file prepfileresidue.cc.
References PrepFileSpace::kGeometryChange, and PrepFileSpace::kGeometryCorrect.
Referenced by PrepFileSpace::PrepFile::BuildPrepFile().
{
    switch(geometry_type)
    {
        case kGeometryCorrect:
            return "CORRECT";
        case kGeometryChange:
            return "CHANGE";
        default:
            return "";
    }
}
string PrepFileResidue::GetStringFormatOfGeometryType ()
Definition at line 296 of file prepfileresidue.cc.
References PrepFileSpace::kGeometryChange, and PrepFileSpace::kGeometryCorrect.
{
    switch(geometry_type_)
    {
        case kGeometryCorrect:
            return "CORRECT";
        case kGeometryChange:
            return "CHANGE";
        default:
            return "";
    }
}
string PrepFileResidue::GetStringFormatOfSectionType (SectionType section_type)
Definition at line 356 of file prepfileresidue.cc.
References PrepFileSpace::kSectionDone, PrepFileSpace::kSectionImproper, PrepFileSpace::kSectionLoop, and PrepFileSpace::kSectionOther.
{
    switch(section_type)
    {
        case kSectionLoop:
            return "SectionLoop";
        case kSectionImproper:
            return "SectionImproper";
        case kSectionDone:
            return "kSectionDone";
        case kSectionOther:
            return "SectionOther";
        default:
            return "";
    }
}
string PrepFileResidue::GetStringFromatOfOutputFormat (OutputFormat output_format)
Definition at line 260 of file prepfileresidue.cc.
References PrepFileSpace::kBinary, and PrepFileSpace::kFormatted.
{
    switch(output_format)
    {
        case kFormatted:
            return "FRM";
        case kBinary:
            return "BIN";
        default:
            return "";
    }
}
string PrepFileResidue::GetStringFromatOfOutputFormat ()
Definition at line 272 of file prepfileresidue.cc.
References PrepFileSpace::kBinary, and PrepFileSpace::kFormatted.
{
    switch(output_format_)
    {
        case kFormatted:
            return "FRM";
        case kBinary:
            return "BIN";
        default:
            return "";
    }
}
string PrepFileResidue::GetTitle ()
Definition at line 32 of file prepfileresidue.cc.
Referenced by PrepFileSpace::PrepFile::BuildPrepFile().
{
    return title_;
}
PrepFileResidue * PrepFileResidue::LoadFromStream (std::ifstream & in_file)
Create a new residue from a given stream
Read the first line of a residue section
End of file
Set title of the residue
Blank line, skip
Read the next line
Create an stream from the read line
Residue name extraction from the stream of the read line
Coordinate type extraction from the stream of the read line
Output format extraction from the stream of the read line
Read the next line
Create an stream from the read line
Geometry type extraction from the stream of the read line
Dummy atom omission extraction from the stream of the read line
Dummy atom type extraction from the stream of the read line
Dummy atom position extraction from the stream of the read line
Read the next line
Residue charge extraction from the read line
Process atoms of the residue
Process the extra sections: IMPROPER, LOOP, DONE
Skip blank lines until to reach to a known section title
Does a corresponding action based on the section title
Definition at line 504 of file prepfileresidue.cc.
References atoms_, charge_, coordinate_type_, dummy_atom_omission_, dummy_atom_position_, dummy_atom_type_, ExtractImproperDihedral(), ExtractLoops(), geometry_type_, improper_dihedrals_, PrepFileSpace::kSectionDone, PrepFileSpace::kSectionImproper, PrepFileSpace::kSectionLoop, PrepFileSpace::kSectionOther, loops_, name_, output_format_, title_, and gmml::Trim().
Referenced by PrepFileSpace::PrepFile::ProcessResidueSection().
{
    string line, name, dummy_atom_type;
    istringstream ss;
    CoordinateType coordinate_type;
    OutputFormat output_format;
    GeometryType geometry_type;
    DummyAtomOmission dummy_atom_omission;
    DummyAtomPosition dummy_atom_position;
    PrepFileResidue *residue = new PrepFileResidue();
    getline(in_file, line);             /// Read the first line of a residue section
    if (Trim(line) == "STOP")           /// End of file
        return NULL;
    residue->title_ = line;             /// Set title of the residue
    getline(in_file, line);             /// Blank line, skip
    getline(in_file, line);             /// Read the next line
    ss.str(line);                       /// Create an stream from the read line
    /// Residue name extraction from the stream of the read line
    name = ExtractResidueName(ss);
    residue->name_ = name;
    /// Coordinate type extraction from the stream of the read line
    coordinate_type = ExtractResidueCoordinateType(ss);
    residue->coordinate_type_ = coordinate_type;
    /// Output format extraction from the stream of the read line
    output_format = ExtractResidueOutputFormat(ss);
    residue->output_format_ = output_format;
    ss.clear();
    getline(in_file, line);             /// Read the next line
    ss.str(line);                       /// Create an stream from the read line
    /// Geometry type extraction from the stream of the read line
    geometry_type = ExtractResidueGeometryType(ss);
    residue->geometry_type_ = geometry_type;
    /// Dummy atom omission extraction from the stream of the read line
    dummy_atom_omission = ExtractResidueDummyAtomOmission(ss);
    residue->dummy_atom_omission_ = dummy_atom_omission;
    /// Dummy atom type extraction from the stream of the read line
    ss >> dummy_atom_type;
    residue->dummy_atom_type_ = dummy_atom_type;
    /// Dummy atom position extraction from the stream of the read line
    dummy_atom_position = ExtractResidueDummyAtomPosition(ss);
    residue->dummy_atom_position_ = dummy_atom_position;
    getline(in_file, line);             /// Read the next line
    /// Residue charge extraction from the read line
    residue->charge_ = ConvertString<double>(line);
    /// Process atoms of the residue
    while (getline(in_file, line) && !Trim(line).empty())
    {
        PrepFileAtom *atom = new PrepFileAtom(line);
        residue->atoms_.push_back(atom);
    }
    /// Process the extra sections: IMPROPER, LOOP, DONE
    bool done = false;
    while (!done)
    {
        /// Skip blank lines until to reach to a known section title
        getline(in_file, line);
        while (Trim(line).empty())
        {
            getline(in_file, line);
        }
        /// Does a corresponding action based on the section title
        switch (ExtractSectionType(line))
        {
            case kSectionLoop:
                residue->loops_ = residue->ExtractLoops(in_file);
                break;
            case kSectionImproper:
                residue->improper_dihedrals_ = residue->ExtractImproperDihedral(in_file);
                break;
            case kSectionDone:
                done = true;
                break;
            case kSectionOther:
                cout << "Unrecognized section in prep file";
                break;
        }
    }
    return residue;
}
void PrepFileResidue::Print (std::ostream & out = std::cout)
Definition at line 737 of file prepfileresidue.cc.
References PrepFileSpace::kBinary, PrepFileSpace::kFormatted, PrepFileSpace::kGeometryChange, PrepFileSpace::kGeometryCorrect, PrepFileSpace::kINT, PrepFileSpace::kNomit, PrepFileSpace::kOmit, PrepFileSpace::kPositionAll, PrepFileSpace::kPositionBeg, and PrepFileSpace::kXYZ.
{
    BondedAtomIndexMap bonded_atoms_map = this->GetBondingsOfResidue();
    out << "Title: " << title_ << endl;
    out << setw(10) << "ResName"
        << setw(10) << "CrdType"
        << setw(10) << "Output"
        << setw(10) << "GeoType"
        << setw(15) << "DummyOmission"
        << setw(12) << "DummyType"
        << setw(12) << "DummyPos"
        << setw(10) << "Charge" << endl;
    out << setw(10) << name_;
    if(coordinate_type_ == kINT)
        out << setw(10) << "INT";
    else if(coordinate_type_ == kXYZ)
        out << setw(10) << "XYZ";
    else
        out << setw(10) << "--";
    if(output_format_ == kBinary)
        out << setw(10) << "Binary";
    else if(output_format_ == kFormatted)
        out << setw(10) << "NBinary";
    else
        out << setw(10) << "--";
    if(geometry_type_ == kGeometryCorrect)
        out << setw(10) << "Correct";
    else if(geometry_type_ == kGeometryChange)
        out << setw(10) << "Change";
    else
        out << setw(10) << "--";
    if(dummy_atom_omission_ == kOmit)
        out << setw(15) << "YES";
    else if(dummy_atom_omission_ == kNomit)
        out << setw(15) << "NO";
    else
        out << setw(15) << "--";
    out << setw(12) << dummy_atom_type_;
    if(dummy_atom_position_ == kPositionAll)
        out << setw(12) << "ALL";
    else if (dummy_atom_position_ == kPositionBeg)
        out << setw(12) << "BEG";
    else
        out << setw(12) << "--";
    out << setw(10) << charge_ << endl << endl;
    out << setw(3) << "#"
        << setw(6) << "Name"
        << setw(6) << "Type"
        << setw(3) << "TT"
        << setw(4) << "B#"
        << setw(4) << "A#"
        << setw(4) << "D#"
        << setw(10) << "Bond"
        << setw(10) << "Angle"
        << setw(10) << "Dihedral"
        << setw(10) << "Charge"
        << setw(10) << "Bonded"
        << endl;
    for(vector<PrepFileAtom*>::iterator it = atoms_.begin(); it != atoms_.end(); it++)
    {
        (*it)->Print(out);
        vector<int> bonded_atoms = bonded_atoms_map[(*it)->GetIndex()];
        out << "\t";
        for(unsigned int i = 0; i < bonded_atoms.size(); i++)
        {
            if(i != bonded_atoms.size() - 1)
                out << this->GetAtomNameByIndex(bonded_atoms.at(i)) << ", ";
            else
                out << this->GetAtomNameByIndex(bonded_atoms.at(i));
        }
        out << endl;
    }
    out << endl << "Improper dihedrals" << endl;
    for(vector<Dihedral>::iterator it = improper_dihedrals_.begin(); it != improper_dihedrals_.end(); it++)
    {
        for(Dihedral::iterator it1 = it->begin(); it1 != it->end(); it1++)
        {
            out << setw(6) << (*it1);
        }
        out << endl;
    }
    out << endl << "Loops" << endl;
    for(Loop::iterator it = loops_.begin(); it != loops_.end(); it++)
    {
        out << setw(6) << this->GetAtomNameByIndex(it->first) << setw(6) << this->GetAtomNameByIndex(it->second) << endl;
    }
    out << endl;
}
void PrepFileResidue::SetAtoms (PrepFileAtomVector atoms)
Definition at line 471 of file prepfileresidue.cc.
{
    atoms_.clear();
    for(PrepFileAtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        atoms_.push_back(*it);
    }
}
void PrepFileResidue::SetBondIndex (GeometryType geometry_type)
Definition at line 451 of file prepfileresidue.cc.
{
    geometry_type_ = geometry_type;
}
void PrepFileResidue::SetCharge (double charge)
Definition at line 467 of file prepfileresidue.cc.
{
    charge_ = charge;
}
void PrepFileResidue::SetCoordinateType (CoordinateType coordinate_type)
Definition at line 443 of file prepfileresidue.cc.
{
    coordinate_type_ = coordinate_type;
}
void PrepFileResidue::SetDummyAtomPosition (DummyAtomPosition dummy_atom_position)
Definition at line 463 of file prepfileresidue.cc.
{
    dummy_atom_position_ = dummy_atom_position;
}
void PrepFileResidue::SetDummyAtomType (std::string dummy_atom_type)
Definition at line 459 of file prepfileresidue.cc.
{
    dummy_atom_type_ = dummy_atom_type;
}
void PrepFileResidue::SetImproperDihedrals (DihedralVector improper_dihedrals)
Definition at line 483 of file prepfileresidue.cc.
{
    improper_dihedrals_.clear();
    for(DihedralVector::iterator it = improper_dihedrals.begin(); it != improper_dihedrals.end(); it++)
    {
        improper_dihedrals_.push_back(*it);
    }
}
void PrepFileResidue::SetLoops (Loop loops)
Definition at line 495 of file prepfileresidue.cc.
{
    loops_ = loops;
}
void PrepFileResidue::SetName (std::string name)
Definition at line 439 of file prepfileresidue.cc.
{
    name_ = name;
}
void PrepFileResidue::SetOutputFormat (OutputFormat output_format)
Definition at line 447 of file prepfileresidue.cc.
{
    output_format_ = output_format;
}
void PrepFileResidue::SetTitle (std::string title)
Definition at line 435 of file prepfileresidue.cc.
{
    title_ = title;
}
Member Data Documentation
PrepFileAtomVector PrepFileSpace::PrepFileResidue::atoms_
Atoms in the resisue; fill by all lines between 6th line of each residue section of the file and a blank line in that section
Definition at line 445 of file prepfileresidue.hpp.
Referenced by LoadFromStream().
double PrepFileSpace::PrepFileResidue::charge_
Total charge of the residue; fill by the 5th line of each residue section of the file
Definition at line 444 of file prepfileresidue.hpp.
Referenced by LoadFromStream().
CoordinateType PrepFileSpace::PrepFileResidue::coordinate_type_
Coordinate type(INT, XYZ); fill by the 2nd column of the third line of each residue section of the file
Definition at line 438 of file prepfileresidue.hpp.
Referenced by LoadFromStream().
DummyAtomOmission PrepFileSpace::PrepFileResidue::dummy_atom_omission_
Dummy atom omission(OMIT, NOMIT); fill by the 3rd column of the 4th line of each residue section of the file
Definition at line 441 of file prepfileresidue.hpp.
Referenced by LoadFromStream().
DummyAtomPosition PrepFileSpace::PrepFileResidue::dummy_atom_position_
Dummy atom position(ALL, BEG); fill by the 5th column of the 4th line of each residue section of the file
Definition at line 443 of file prepfileresidue.hpp.
Referenced by LoadFromStream().
std::string PrepFileSpace::PrepFileResidue::dummy_atom_type_
Dummy atom type; fill by the 4th column of the 4th line of each residue section of the file
Definition at line 442 of file prepfileresidue.hpp.
Referenced by LoadFromStream().
GeometryType PrepFileSpace::PrepFileResidue::geometry_type_
Geometry type(CORRECT, CHANGE); fill by the first column of the 4th line of each residue section of the file
Definition at line 440 of file prepfileresidue.hpp.
Referenced by LoadFromStream().
DihedralVector PrepFileSpace::PrepFileResidue::improper_dihedrals_
Improper dihedrals; fill by all lines between IMPROPER title in each residue section of the file and a blank line in that section
Definition at line 446 of file prepfileresidue.hpp.
Referenced by LoadFromStream().
Loop PrepFileSpace::PrepFileResidue::loops_
Loops; fill by all lines between LOOP title in each residue section of the file and a blank line in that section End of each residue section gets marked by DONE
Definition at line 447 of file prepfileresidue.hpp.
Referenced by LoadFromStream().
std::string PrepFileSpace::PrepFileResidue::name_
Residue name; fill by the first column of the 3rd line of each residue section of the file
Definition at line 437 of file prepfileresidue.hpp.
Referenced by LoadFromStream(), and PrepFileSpace::PrepFile::Read().
OutputFormat PrepFileSpace::PrepFileResidue::output_format_
Output format(Binary=1,Formatted=1); fill by the third column of the 3rd line of each residue section of the file
Definition at line 439 of file prepfileresidue.hpp.
Referenced by LoadFromStream().
std::string PrepFileSpace::PrepFileResidue::title_
Residue title; fill by the first line of each residue section of the file
Definition at line 436 of file prepfileresidue.hpp.
Referenced by LoadFromStream().
The documentation for this class was generated from the following files:
includes/ParameterSet/PrepFileSpace/prepfileresidue.hpp
src/ParameterSet/PrepFileSpace/prepfileresidue.cc