gmmlNew: PdbPreprocessorSpace::PdbPreprocessorAlternateResidue Class Reference
PdbPreprocessorSpace::PdbPreprocessorAlternateResidue Class Reference
#include <pdbpreprocessoralternateresidue.hpp>
Public Member Functions
PdbPreprocessorAlternateResidue ()
PdbPreprocessorAlternateResidue (std::string residue_name, char chain_id, int sequence_number, char residue_insertion_code, std::vector< char > residue_alternate_location, std::vector< bool > selected_alternate_location)
char GetResidueChainId ()
int GetResidueSequenceNumber ()
std::string GetResidueName ()
char GetResidueInsertionCode ()
std::vector< char > GetResidueAlternateLocation ()
std::vector< bool > GetSelectedAlternateLocation ()
void SetResidueChainId (char residue_chain_id)
void SetResidueSequenceNumber (int residue_sequence_number)
void SetResidueName (std::string residue_name)
void SetResidueInsertionCode (char residue_insertion_code)
void SetResidueAlternateLocation (std::vector< char > residue_alternate_location)
void SetSelectedAlternateLocation (std::vector< bool > selected_alternate_location)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 10 of file pdbpreprocessoralternateresidue.hpp.
Constructor & Destructor Documentation
PdbPreprocessorAlternateResidue::PdbPreprocessorAlternateResidue ()
Definition at line 10 of file pdbpreprocessoralternateresidue.cc.
{}
PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::PdbPreprocessorAlternateResidue (std::string residue_name, char chain_id, int sequence_number, char residue_insertion_code, std::vector< char > residue_alternate_location, std::vector< bool > selected_alternate_location)
Member Function Documentation
vector< char > PdbPreprocessorAlternateResidue::GetResidueAlternateLocation ()
Definition at line 47 of file pdbpreprocessoralternateresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::ExtractAlternateResidue(), and PdbPreprocessorSpace::PdbPreprocessor::RemoveUnselectedAlternateResidues().
{
    return residue_alternate_location_;
}
char PdbPreprocessorAlternateResidue::GetResidueChainId ()
Definition at line 31 of file pdbpreprocessoralternateresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveUnselectedAlternateResidues().
{
    return residue_chain_id_;
}
char PdbPreprocessorAlternateResidue::GetResidueInsertionCode ()
Definition at line 43 of file pdbpreprocessoralternateresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveUnselectedAlternateResidues().
{
    return residue_insertion_code_;
}
string PdbPreprocessorAlternateResidue::GetResidueName ()
Definition at line 39 of file pdbpreprocessoralternateresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveUnselectedAlternateResidues().
{
    return residue_name_;
}
int PdbPreprocessorAlternateResidue::GetResidueSequenceNumber ()
Definition at line 35 of file pdbpreprocessoralternateresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveUnselectedAlternateResidues().
{
    return residue_sequence_number_;
}
vector< bool > PdbPreprocessorAlternateResidue::GetSelectedAlternateLocation ()
Definition at line 51 of file pdbpreprocessoralternateresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::ExtractAlternateResidue(), and PdbPreprocessorSpace::PdbPreprocessor::RemoveUnselectedAlternateResidues().
{
    return selected_alternate_location_;
}
void PdbPreprocessorAlternateResidue::Print (std::ostream & out = std::cout)
Definition at line 95 of file pdbpreprocessoralternateresidue.cc.
{
    out << "Residue name: " << residue_name_
         << ", Chain id: " << residue_chain_id_
         << ", Sequence number: " << residue_sequence_number_
         << ", Insertion code: " << residue_insertion_code_ << endl;
         for(unsigned int i = 0; i < residue_alternate_location_.size(); i++)
         {
             out << "\t Alternate Location: " << residue_alternate_location_[i] << " " << selected_alternate_location_[i] << endl;
         }
         out << endl;
}
void PdbPreprocessorAlternateResidue::SetResidueAlternateLocation (std::vector< char > residue_alternate_location)
Definition at line 75 of file pdbpreprocessoralternateresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::ExtractAlternateResidue().
{
    residue_alternate_location_.clear();
    for(vector<char>::iterator it = residue_alternate_location.begin(); it != residue_alternate_location.end(); it++)
    {
        residue_alternate_location_.push_back(*it);
    }
}
void PdbPreprocessorAlternateResidue::SetResidueChainId (char residue_chain_id)
Definition at line 59 of file pdbpreprocessoralternateresidue.cc.
{
    residue_chain_id_ = residue_chain_id;
}
void PdbPreprocessorAlternateResidue::SetResidueInsertionCode (char residue_insertion_code)
Definition at line 71 of file pdbpreprocessoralternateresidue.cc.
{
    residue_insertion_code_ = residue_insertion_code;
}
void PdbPreprocessorAlternateResidue::SetResidueName (std::string residue_name)
Definition at line 67 of file pdbpreprocessoralternateresidue.cc.
{
    residue_name_ = residue_name;
}
void PdbPreprocessorAlternateResidue::SetResidueSequenceNumber (int residue_sequence_number)
Definition at line 63 of file pdbpreprocessoralternateresidue.cc.
{
    residue_sequence_number_ = residue_sequence_number;
}
void PdbPreprocessorAlternateResidue::SetSelectedAlternateLocation (std::vector< bool > selected_alternate_location)
Definition at line 83 of file pdbpreprocessoralternateresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::ExtractAlternateResidue().
{
    selected_alternate_location_.clear();
    for(vector<bool>::iterator it = selected_alternate_location.begin(); it != selected_alternate_location.end(); it++)
    {
        selected_alternate_location_.push_back(*it);
    }
}
The documentation for this class was generated from the following files:
includes/Resolver/PdbPreprocessor/pdbpreprocessoralternateresidue.hpp
src/Resolver/PdbPreprocessor/pdbpreprocessoralternateresidue.cc