gmmlNew: PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen Class Reference
PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen Class Reference
#include <pdbpreprocessorreplacedhydrogen.hpp>
Public Member Functions
PdbPreprocessorReplacedHydrogen ()
PdbPreprocessorReplacedHydrogen (char residue_chain_id, int atom_serial_number, std::string atom_name, std::string residue_name, int residue_sequence_number, char residue_insertion_code, char residue_alternate_location)
int GetAtomSerialNumber ()
std::string GetAtomName ()
std::string GetResidueName ()
int GetResidueSequenceNumber ()
char GetResidueChainId ()
char GetResidueInsertionCode ()
char GetResidueAlternateLocation ()
void SetAtomSerialNumber (int atom_serial_number)
void SetAtomName (std::string atom_name)
void SetResidueName (std::string residue_name)
void SetResidueSequenceNumber (int residue_sequence_number)
void SetResidueChainId (char residue_chain_id)
void SetResidueInsertionCode (char residue_insertion_code)
void SetResidueAlternateLocation (char residue_alternate_location)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 9 of file pdbpreprocessorreplacedhydrogen.hpp.
Constructor & Destructor Documentation
PdbPreprocessorReplacedHydrogen::PdbPreprocessorReplacedHydrogen ()
Definition at line 10 of file pdbpreprocessorreplacedhydrogen.cc.
{}
PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen::PdbPreprocessorReplacedHydrogen (char residue_chain_id, int atom_serial_number, std::string atom_name, std::string residue_name, int residue_sequence_number, char residue_insertion_code, char residue_alternate_location)
Member Function Documentation
string PdbPreprocessorReplacedHydrogen::GetAtomName ()
Definition at line 24 of file pdbpreprocessorreplacedhydrogen.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveRemovedHydrogens().
{
    return atom_name_;
}
int PdbPreprocessorReplacedHydrogen::GetAtomSerialNumber ()
Definition at line 20 of file pdbpreprocessorreplacedhydrogen.cc.
{
    return atom_serial_number_;
}
char PdbPreprocessorReplacedHydrogen::GetResidueAlternateLocation ()
Definition at line 44 of file pdbpreprocessorreplacedhydrogen.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveRemovedHydrogens().
{
    return residue_alternate_location_;
}
char PdbPreprocessorReplacedHydrogen::GetResidueChainId ()
Definition at line 36 of file pdbpreprocessorreplacedhydrogen.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveRemovedHydrogens().
{
    return residue_chain_id_;
}
char PdbPreprocessorReplacedHydrogen::GetResidueInsertionCode ()
Definition at line 40 of file pdbpreprocessorreplacedhydrogen.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveRemovedHydrogens().
{
    return residue_insertion_code_;
}
string PdbPreprocessorReplacedHydrogen::GetResidueName ()
Definition at line 28 of file pdbpreprocessorreplacedhydrogen.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveRemovedHydrogens().
{
    return residue_name_;
}
int PdbPreprocessorReplacedHydrogen::GetResidueSequenceNumber ()
Definition at line 32 of file pdbpreprocessorreplacedhydrogen.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveRemovedHydrogens().
{
    return residue_sequence_number_;
}
void PdbPreprocessorReplacedHydrogen::Print (std::ostream & out = std::cout)
Definition at line 84 of file pdbpreprocessorreplacedhydrogen.cc.
{
    out << "Atom name: " << atom_name_
         << ", Serial number: " << atom_serial_number_
         << ", Residue name: " << residue_name_
         << ", Sequence number: " << residue_sequence_number_
         << ", chain id: " << residue_chain_id_
         << ", insertion code: " << residue_insertion_code_
         << ", Alternate location: " << residue_alternate_location_
         << endl;
}
void PdbPreprocessorReplacedHydrogen::SetAtomName (std::string atom_name)
Definition at line 56 of file pdbpreprocessorreplacedhydrogen.cc.
{
    atom_name_ = atom_name;
}
void PdbPreprocessorReplacedHydrogen::SetAtomSerialNumber (int atom_serial_number)
Definition at line 52 of file pdbpreprocessorreplacedhydrogen.cc.
{
    atom_serial_number_ = atom_serial_number;
}
void PdbPreprocessorReplacedHydrogen::SetResidueAlternateLocation (char residue_alternate_location)
Definition at line 76 of file pdbpreprocessorreplacedhydrogen.cc.
{
    residue_alternate_location_ = residue_alternate_location;
}
void PdbPreprocessorReplacedHydrogen::SetResidueChainId (char residue_chain_id)
Definition at line 68 of file pdbpreprocessorreplacedhydrogen.cc.
{
    residue_chain_id_ = residue_chain_id;
}
void PdbPreprocessorReplacedHydrogen::SetResidueInsertionCode (char residue_insertion_code)
Definition at line 72 of file pdbpreprocessorreplacedhydrogen.cc.
{
    residue_insertion_code_ = residue_insertion_code;
}
void PdbPreprocessorReplacedHydrogen::SetResidueName (std::string residue_name)
Definition at line 60 of file pdbpreprocessorreplacedhydrogen.cc.
{
    residue_name_ = residue_name;
}
void PdbPreprocessorReplacedHydrogen::SetResidueSequenceNumber (int residue_sequence_number)
Definition at line 64 of file pdbpreprocessorreplacedhydrogen.cc.
{
    residue_sequence_number_ = residue_sequence_number;
}
The documentation for this class was generated from the following files:
includes/Resolver/PdbPreprocessor/pdbpreprocessorreplacedhydrogen.hpp
src/Resolver/PdbPreprocessor/pdbpreprocessorreplacedhydrogen.cc