gmmlNew: PdbFileSpace::PdbCompoundSpecification Class Reference
PdbFileSpace::PdbCompoundSpecification Class Reference
#include <pdbcompoundspecification.hpp>
Public Member Functions
PdbCompoundSpecification ()
PdbCompoundSpecification (const std::string &molecule_id, const std::string &molecule_name)
PdbCompoundSpecification (const std::string &molecule_id, const std::string &molecule_name, const std::vector< std::string > &chain_ids, const std::string &fragment, const std::vector< std::string > &molecule_synonyms, std::vector< std::string > &enzyme_commission_numbers, bool is_engineered, bool has_mutation, const std::string &comments)
PdbCompoundSpecification (std::stringstream &specification_block)
std::string GetMoleculeId ()
std::string GetMoleculeName ()
std::vector< std::string > GetChainIds ()
std::string GetFragment ()
std::vector< std::string > GetMoleculeSynonyms ()
std::vector< std::string > GetEnzymeCommissionNumbers ()
bool GetIsEngineered ()
bool GetHasMutation ()
std::string GetComments ()
void SetMoleculeId (const std::string molecule_id)
void SetMoleculeName (const std::string molecule_name)
void SetChainIds (const std::vector< std::string > chain_ids)
void AddChainId (const std::string chain_id)
void SetFragment (const std::string fragment)
void SetMoleculeSynonyms (std::vector< std::string > molecule_synonyms)
void AddMoleculeSynonym (const std::string molecule_synonym)
void SetEnzymeCommissionNumbers (std::vector< std::string > enzyme_commission_numbers)
void AddEnzymeCommissionNumber (std::string enzyme_commission_number)
void SetIsEngineered (bool is_engineered)
void SetHasMutation (bool has_mutation)
void setComments (const std::string comments)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 13 of file pdbcompoundspecification.hpp.
Constructor & Destructor Documentation
PdbCompoundSpecification::PdbCompoundSpecification ()
Definition at line 13 of file pdbcompoundspecification.cc.
                                                   : molecule_id_(""), molecule_name_(""), chain_ids_(), fragment_(""),
    molecule_synonyms_(), enzyme_commission_numbers_(), is_engineered_(false), has_mutation_(false), comments_(""){}
PdbFileSpace::PdbCompoundSpecification::PdbCompoundSpecification (const std::string & molecule_id, const std::string & molecule_name)
PdbFileSpace::PdbCompoundSpecification::PdbCompoundSpecification (const std::string & molecule_id, const std::string & molecule_name, const std::vector< std::string > & chain_ids, const std::string & fragment, const std::vector< std::string > & molecule_synonyms, std::vector< std::string > & enzyme_commission_numbers, bool is_engineered, bool has_mutation, const std::string & comments)
PdbFileSpace::PdbCompoundSpecification::PdbCompoundSpecification (std::stringstream & specification_block)
Member Function Documentation
void PdbCompoundSpecification::AddChainId (const std::string chain_id)
Definition at line 245 of file pdbcompoundspecification.cc.
{
    chain_ids_.push_back(chain_id);
}
void PdbCompoundSpecification::AddEnzymeCommissionNumber (std::string enzyme_commission_number)
Definition at line 278 of file pdbcompoundspecification.cc.
{
    enzyme_commission_numbers_.push_back(enzyme_commission_number);
}
void PdbCompoundSpecification::AddMoleculeSynonym (const std::string molecule_synonym)
Definition at line 264 of file pdbcompoundspecification.cc.
{
    molecule_synonyms_.push_back(molecule_synonym);
}
vector< string > PdbCompoundSpecification::GetChainIds ()
Definition at line 188 of file pdbcompoundspecification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveCompoundCard().
{
    return chain_ids_;
}
string PdbCompoundSpecification::GetComments ()
Definition at line 218 of file pdbcompoundspecification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveCompoundCard().
{
    return comments_;
}
vector< string > PdbCompoundSpecification::GetEnzymeCommissionNumbers ()
Definition at line 203 of file pdbcompoundspecification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveCompoundCard().
{
    return enzyme_commission_numbers_;
}
string PdbCompoundSpecification::GetFragment ()
Definition at line 193 of file pdbcompoundspecification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveCompoundCard().
{
    return fragment_;
}
bool PdbCompoundSpecification::GetHasMutation ()
Definition at line 213 of file pdbcompoundspecification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveCompoundCard().
{
    return has_mutation_;
}
bool PdbCompoundSpecification::GetIsEngineered ()
Definition at line 208 of file pdbcompoundspecification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveCompoundCard().
{
    return is_engineered_;
}
string PdbCompoundSpecification::GetMoleculeId ()
Definition at line 178 of file pdbcompoundspecification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveCompoundCard().
{
    return molecule_id_;
}
string PdbCompoundSpecification::GetMoleculeName ()
Definition at line 183 of file pdbcompoundspecification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveCompoundCard().
{
    return molecule_name_;
}
vector< string > PdbCompoundSpecification::GetMoleculeSynonyms ()
Definition at line 198 of file pdbcompoundspecification.cc.
Referenced by PdbFileSpace::PdbFile::ResolveCompoundCard().
{
    return molecule_synonyms_;
}
void PdbCompoundSpecification::Print (std::ostream & out = std::cout)
Definition at line 305 of file pdbcompoundspecification.cc.
{
    out << "Molecule ID: " << molecule_id_ << ", Molecule Name: " << molecule_name_ << endl;
    out << "Chain IDs: ";
    for(vector<string>::iterator it = chain_ids_.begin(); it != chain_ids_.end(); it++)
    {
        out << (*it) << ", ";
    }
    out << endl << "Fragment: " << fragment_ << endl << "Molecule Synonyms: ";
    for(vector<string>::iterator it = molecule_synonyms_.begin(); it != molecule_synonyms_.end(); it++)
    {
        out << (*it) << ", ";
    }
    out << endl << "Enzyme Commission Numbers: ";
    for(vector<string>::iterator it = enzyme_commission_numbers_.begin(); it != enzyme_commission_numbers_.end(); it++)
    {
        out << (*it) << ", ";
    }
    out << endl << "Engineered: ";
    if(is_engineered_)
        out << "YES" << endl;
    else
        out << "NO" << endl;
    out << "Mutation: ";
    if(has_mutation_)
        out << "YES" << endl;
    else
        out << "NO" << endl;
    out << "Comments: " << comments_ << endl;
}
void PdbCompoundSpecification::SetChainIds (const std::vector< std::string > chain_ids)
Definition at line 236 of file pdbcompoundspecification.cc.
{
    chain_ids_.clear();
    for(vector<string>::const_iterator it = chain_ids.begin(); it != chain_ids.end(); it++)
    {
        chain_ids_.push_back(*it);
    }
}
void PdbCompoundSpecification::setComments (const std::string comments)
Definition at line 293 of file pdbcompoundspecification.cc.
{
    comments_ = comments;
}
void PdbCompoundSpecification::SetEnzymeCommissionNumbers (std::vector< std::string > enzyme_commission_numbers)
Definition at line 269 of file pdbcompoundspecification.cc.
{
    enzyme_commission_numbers_.clear();
    for(vector<string>::const_iterator it = enzyme_commission_numbers.begin(); it != enzyme_commission_numbers.end(); it++)
    {
        enzyme_commission_numbers_.push_back(*it);
    }
}
void PdbCompoundSpecification::SetFragment (const std::string fragment)
Definition at line 250 of file pdbcompoundspecification.cc.
{
    fragment_ = fragment;
}
void PdbCompoundSpecification::SetHasMutation (bool has_mutation)
Definition at line 288 of file pdbcompoundspecification.cc.
{
    has_mutation_ = has_mutation;
}
void PdbCompoundSpecification::SetIsEngineered (bool is_engineered)
Definition at line 283 of file pdbcompoundspecification.cc.
{
    is_engineered_ = is_engineered;
}
void PdbCompoundSpecification::SetMoleculeId (const std::string molecule_id)
Definition at line 226 of file pdbcompoundspecification.cc.
{
    molecule_id_ = molecule_id;
}
void PdbCompoundSpecification::SetMoleculeName (const std::string molecule_name)
Definition at line 231 of file pdbcompoundspecification.cc.
{
    molecule_name_ = molecule_name;
}
void PdbCompoundSpecification::SetMoleculeSynonyms (std::vector< std::string > molecule_synonyms)
Definition at line 255 of file pdbcompoundspecification.cc.
{
    molecule_synonyms_.clear();
    for(vector<string>::const_iterator it = molecule_synonyms.begin(); it != molecule_synonyms.end(); it++)
    {
        molecule_synonyms_.push_back(*it);
    }
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbcompoundspecification.hpp
src/FileSet/PdbFileSpace/pdbcompoundspecification.cc