gmmlNew: PdbFileSpace::PdbOriginXn Class Reference
PdbFileSpace::PdbOriginXn Class Reference
#include <pdboriginxn.hpp>
Public Member Functions
PdbOriginXn ()
PdbOriginXn (std::stringstream &stream_block)
std::string GetRecordName ()
int GetN ()
Geometry::Coordinate GetOrigin ()
double GetT ()
void SetRecordName (const std::string record_name)
void SetN (int n)
void SetOrigin (Geometry::Coordinate origin)
void SetT (double t)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 15 of file pdboriginxn.hpp.
Constructor & Destructor Documentation
PdbOriginXn::PdbOriginXn ()
Definition at line 13 of file pdboriginxn.cc.
:origin_() {}
PdbFileSpace::PdbOriginXn::PdbOriginXn (std::stringstream & stream_block)
Member Function Documentation
int PdbOriginXn::GetN ()
Definition at line 60 of file pdboriginxn.cc.
Referenced by PdbFileSpace::PdbFile::ResolveOriginCard().
                     {
    return n_;
}
Geometry::Coordinate PdbOriginXn::GetOrigin ()
Definition at line 64 of file pdboriginxn.cc.
Referenced by PdbFileSpace::PdbFile::ResolveOriginCard().
{
    return origin_;
}
string PdbOriginXn::GetRecordName ()
Definition at line 56 of file pdboriginxn.cc.
Referenced by PdbFileSpace::PdbFile::ResolveOriginCard().
{
    return record_name_;
}
double PdbOriginXn::GetT ()
Definition at line 68 of file pdboriginxn.cc.
Referenced by PdbFileSpace::PdbFile::ResolveOriginCard().
{
    return t_;
}
void PdbOriginXn::Print (std::ostream & out = std::cout)
Definition at line 95 of file pdboriginxn.cc.
References gmml::dNotSet, gmml::iNotSet, and Geometry::Coordinate::Print().
{
    out << "Record Name: " << record_name_;
    if(n_ != iNotSet)
        out << n_;
    else
        out << " ";
    out << ", Origin: ";
    origin_.Print(out);
    out << ", T: ";
    if(t_ != dNotSet)
        out << t_;
    else
        out << " ";
    out << endl;
}
void PdbOriginXn::SetN (int n)
Definition at line 80 of file pdboriginxn.cc.
{
    n_ = n;
}
void PdbOriginXn::SetOrigin (Geometry::Coordinate origin)
Definition at line 84 of file pdboriginxn.cc.
{
    origin_ = origin;
}
void PdbOriginXn::SetRecordName (const std::string record_name)
Definition at line 76 of file pdboriginxn.cc.
{
    record_name_ = record_name;
}
void PdbOriginXn::SetT (double t)
Definition at line 88 of file pdboriginxn.cc.
{
    t_ = t;
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdboriginxn.hpp
src/FileSet/PdbFileSpace/pdboriginxn.cc