gmmlNew: Geometry::Coordinate Class Reference
Geometry::Coordinate Class Reference
#include <coordinate.hpp>
Public Member Functions
Coordinate ()
Coordinate (double x, double y, double z)
Coordinate (const Coordinate &coordinate)
double GetX ()
double GetY ()
double GetZ ()
void SetX (double x)
void SetY (double y)
void SetZ (double z)
void Translate (double x, double y, double z)
bool CompareTo (Coordinate coordinate)
double Distance (Coordinate coordinate)
double length ()
void Normalize ()
double DotProduct (Coordinate coordinate)
void CrossProduct (Coordinate coordinate)
void operator+ (Coordinate coordinate)
void operator- (Coordinate coordinate)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 10 of file coordinate.hpp.
Constructor & Destructor Documentation
Coordinate::Coordinate ()
Definition at line 12 of file coordinate.cc.
Referenced by Print().
: x_(0.0), y_(0.0), z_(0.0) {}
Coordinate::Coordinate (double x, double y, double z)
Definition at line 14 of file coordinate.cc.
: x_(x), y_(y), z_(z) {}
Coordinate::Coordinate (const Coordinate & coordinate)
Definition at line 16 of file coordinate.cc.
: x_(coordinate.x_), y_(coordinate.y_), z_(coordinate.z_) {}
Member Function Documentation
bool Coordinate::CompareTo (Coordinate coordinate)
Definition at line 64 of file coordinate.cc.
Referenced by Print(), PdbFileSpace::PdbFile::ResolveMatrixCard(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveOriginCard(), and PdbFileSpace::PdbFile::ResolveScaleCard().
{
    if(x_ == coordinate.x_ && y_ == coordinate.y_ && z_ == coordinate.z_)
        return true;
    else
        return false;
}
void Coordinate::CrossProduct (Coordinate coordinate)
Definition at line 96 of file coordinate.cc.
Referenced by gmml::ConvertInternalCoordinate2CartesianCoordinate().
{
    x_ = (y_ * coordinate.z_) - (coordinate.y_ * z_);
    y_ = (z_ * coordinate.x_) - (coordinate.z_ * x_);
    z_ = (x_ * coordinate.y_) - (coordinate.x_ * y_);
}
double Coordinate::Distance (Coordinate coordinate)
Definition at line 72 of file coordinate.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::GetDistanceofCYS().
{
    double dist = (x_ - coordinate.x_) * (x_ - coordinate.x_) + (y_ - coordinate.y_) * (y_ - coordinate.y_) + (z_ - coordinate.z_) * (z_ - coordinate.z_);
    return sqrt(dist);
}
double Coordinate::DotProduct (Coordinate coordinate)
Definition at line 92 of file coordinate.cc.
{
    return ((x_ * coordinate.x_) + (y_ * coordinate.y_) + (z_ * coordinate.z_));
}
double Coordinate::GetX ()
Definition at line 21 of file coordinate.cc.
Referenced by gmml::ConvertInternalCoordinate2CartesianCoordinate(), LibraryFileSpace::LibraryFileAtom::Print(), PdbFileSpace::PdbFile::ResolveMatrixCard(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveOriginCard(), LibraryFileSpace::LibraryFile::ResolvePositionSection(), PdbFileSpace::PdbFile::ResolveScaleCard(), and LibraryFileSpace::LibraryFileAtom::SetCoordinate().
{
    return x_;
}
double Coordinate::GetY ()
Definition at line 26 of file coordinate.cc.
Referenced by gmml::ConvertInternalCoordinate2CartesianCoordinate(), LibraryFileSpace::LibraryFileAtom::Print(), PdbFileSpace::PdbFile::ResolveMatrixCard(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveOriginCard(), LibraryFileSpace::LibraryFile::ResolvePositionSection(), PdbFileSpace::PdbFile::ResolveScaleCard(), and LibraryFileSpace::LibraryFileAtom::SetCoordinate().
{
    return y_;
}
double Coordinate::GetZ ()
Definition at line 31 of file coordinate.cc.
Referenced by gmml::ConvertInternalCoordinate2CartesianCoordinate(), LibraryFileSpace::LibraryFileAtom::Print(), PdbFileSpace::PdbFile::ResolveMatrixCard(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveOriginCard(), LibraryFileSpace::LibraryFile::ResolvePositionSection(), PdbFileSpace::PdbFile::ResolveScaleCard(), and LibraryFileSpace::LibraryFileAtom::SetCoordinate().
{
    return z_;
}
double Coordinate::length ()
Definition at line 78 of file coordinate.cc.
Referenced by Normalize().
{
    double length = (x_ * x_) + (y_ * y_) + (z_ * z_);
    return sqrt(length);
}
void Coordinate::Normalize ()
Definition at line 83 of file coordinate.cc.
References length().
Referenced by gmml::ConvertInternalCoordinate2CartesianCoordinate().
{
    if(length() != 0.0)
    {
        x_ = x_ / length();
        y_ = y_ / length();
        z_ = z_ / length();
    }
}
void Coordinate::operator+ (Coordinate coordinate)
Definition at line 102 of file coordinate.cc.
{
    x_ += coordinate.x_;
    y_ += coordinate.y_;
    z_ += coordinate.z_;
}
void Coordinate::operator- (Coordinate coordinate)
Definition at line 108 of file coordinate.cc.
{
    x_ -= coordinate.x_;
    y_ -= coordinate.y_;
    z_ -= coordinate.z_;
}
void Coordinate::Print (std::ostream & out = std::cout)
Definition at line 118 of file coordinate.cc.
References CompareTo(), Coordinate(), and gmml::dNotSet.
Referenced by PdbFileSpace::PdbOriginXn::Print(), PdbFileSpace::PdbScaleN::Print(), PdbFileSpace::PdbMatrixN::Print(), MolecularModeling::Atom::Print(), and PdbFileSpace::PdbAtom::Print().
{
    if(this->CompareTo(Coordinate(dNotSet, dNotSet, dNotSet)) == true)
        out << std::setw(10) << " " << ", " << std::setw(10) << " " << ", " << std::setw(10) << " ";
    else
        out << std::setw(10) << x_ << ", " << std::setw(10) << y_ << ", " << std::setw(10) << z_;
}
void Coordinate::SetX (double x)
Definition at line 39 of file coordinate.cc.
Referenced by LibraryFileSpace::LibraryFileAtom::SetCoordinate().
{
    x_ = x;
}
void Coordinate::SetY (double y)
Definition at line 44 of file coordinate.cc.
Referenced by LibraryFileSpace::LibraryFileAtom::SetCoordinate().
{
    y_ = y;
}
void Coordinate::SetZ (double z)
Definition at line 49 of file coordinate.cc.
Referenced by LibraryFileSpace::LibraryFileAtom::SetCoordinate().
{
    z_ = z;
}
void Coordinate::Translate (double x, double y, double z)
Definition at line 57 of file coordinate.cc.
Referenced by gmml::ConvertInternalCoordinate2CartesianCoordinate().
{
    x_ += x;
    y_ += y;
    z_ += z;
}
The documentation for this class was generated from the following files:
includes/Geometry/coordinate.hpp
src/Geometry/coordinate.cc