gmmlNew: PdbFileSpace::PdbMatrixN Class Reference
PdbFileSpace::PdbMatrixN Class Reference
#include <pdbmatrixn.hpp>
Public Member Functions
PdbMatrixN ()
PdbMatrixN (std::string &line)
std::string GetRecordName ()
int GetN ()
int GetSerialNumber ()
Geometry::Coordinate GetTransformationVector ()
double GetV ()
int GetIGiven ()
void SetRecordName (const std::string record_name)
void SetN (int n)
void SetSerialNumber (int serial_number)
void SetTransformationVector (Geometry::Coordinate transfomration_vector)
void SetV (double v)
void SetIGiven (int i_given)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 14 of file pdbmatrixn.hpp.
Constructor & Destructor Documentation
PdbMatrixN::PdbMatrixN ()
Definition at line 13 of file pdbmatrixn.cc.
{}
PdbFileSpace::PdbMatrixN::PdbMatrixN (std::string & line)
Member Function Documentation
int PdbMatrixN::GetIGiven ()
Definition at line 72 of file pdbmatrixn.cc.
Referenced by PdbFileSpace::PdbFile::ResolveMatrixCard().
{
    return i_given_;
}
int PdbMatrixN::GetN ()
Definition at line 56 of file pdbmatrixn.cc.
Referenced by PdbFileSpace::PdbFile::ResolveMatrixCard().
                    {
    return n_;
}
string PdbMatrixN::GetRecordName ()
Definition at line 52 of file pdbmatrixn.cc.
Referenced by PdbFileSpace::PdbFile::ResolveMatrixCard().
{
    return record_name_;
}
int PdbMatrixN::GetSerialNumber ()
Definition at line 60 of file pdbmatrixn.cc.
Referenced by PdbFileSpace::PdbFile::ResolveMatrixCard().
{
    return serial_number_;
}
Geometry::Coordinate PdbMatrixN::GetTransformationVector ()
Definition at line 64 of file pdbmatrixn.cc.
Referenced by PdbFileSpace::PdbFile::ResolveMatrixCard().
{
    return transfomration_vector_;
}
double PdbMatrixN::GetV ()
Definition at line 68 of file pdbmatrixn.cc.
Referenced by PdbFileSpace::PdbFile::ResolveMatrixCard().
                       {
    return v_;
}
void PdbMatrixN::Print (std::ostream & out = std::cout)
Definition at line 107 of file pdbmatrixn.cc.
References gmml::dNotSet, gmml::iNotSet, and Geometry::Coordinate::Print().
{
    out << "Record Name: " << record_name_;
    if(n_ != iNotSet)
        out << n_;
    else
        out << " ";
    out << ", Serial Number: ";
    if(serial_number_ != iNotSet)
        out << serial_number_;
    else
        out << " ";
    out << ", Transformation Vector: ";
    transfomration_vector_.Print(out);
    out << ", V: ";
    if(v_ != dNotSet)
        out << v_;
    else
        out << " ";
    out << ", I Given: ";
    if(i_given_ != iNotSet)
        out << i_given_;
    else
        out << " ";
    out << endl;
}
void PdbMatrixN::SetIGiven (int i_given)
Definition at line 100 of file pdbmatrixn.cc.
{
    i_given_ = i_given;
}
void PdbMatrixN::SetN (int n)
Definition at line 84 of file pdbmatrixn.cc.
{
    n_ = n;
}
void PdbMatrixN::SetRecordName (const std::string record_name)
Definition at line 80 of file pdbmatrixn.cc.
{
    record_name_ = record_name;
}
void PdbMatrixN::SetSerialNumber (int serial_number)
Definition at line 88 of file pdbmatrixn.cc.
{
    serial_number_ = serial_number;
}
void PdbMatrixN::SetTransformationVector (Geometry::Coordinate transfomration_vector)
Definition at line 92 of file pdbmatrixn.cc.
{
    transfomration_vector_ = transfomration_vector;
}
void PdbMatrixN::SetV (double v)
Definition at line 96 of file pdbmatrixn.cc.
{
    v_ = v;
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbmatrixn.hpp
src/FileSet/PdbFileSpace/pdbmatrixn.cc