gmmlNew: MolecularModeling::AtomNode Class Reference
MolecularModeling::AtomNode Class Reference
#include <atomnode.hpp>
Public Types
typedef std::vector< Atom * > AtomVector
Public Member Functions
AtomNode ()
Atom * GetAtom ()
AtomVector GetNodeNeighbors ()
int GetId ()
void SetAtom (Atom *atom)
void SetNodeNeighbors (AtomVector node_neighbors)
void AddNodeNeighbor (Atom *node_neighbor)
void SetId (int id)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 12 of file atomnode.hpp.
Member Typedef Documentation
typedef std::vector<Atom*> MolecularModeling::AtomNode::AtomVector
Definition at line 18 of file atomnode.hpp.
Constructor & Destructor Documentation
AtomNode::AtomNode ()
Definition at line 11 of file atomnode.cc.
{}
Member Function Documentation
void AtomNode::AddNodeNeighbor (Atom * node_neighbor)
Definition at line 44 of file atomnode.cc.
Referenced by MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), MolecularModeling::Assembly::BuildStructureByDistance(), MolecularModeling::Assembly::BuildStructureByLIBFileInformation(), MolecularModeling::Assembly::BuildStructureByPDBFileInformation(), MolecularModeling::Assembly::BuildStructureByPrepFileInformation(), and MolecularModeling::Assembly::BuildStructureByTOPFileInformation().
{
    node_neighbors_.push_back(node_neighbor);
}
Atom * AtomNode::GetAtom ()
Definition at line 16 of file atomnode.cc.
{
    return atom_;
}
int AtomNode::GetId ()
Definition at line 24 of file atomnode.cc.
{
    return id_;
}
AtomNode::AtomVector AtomNode::GetNodeNeighbors ()
Definition at line 20 of file atomnode.cc.
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly(), MolecularModeling::Assembly::BuildPrepFileStructureFromAssembly(), MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly(), MolecularModeling::Assembly::CountNumberOfAngles(), MolecularModeling::Assembly::CountNumberOfAnglesExcludingHydrogen(), MolecularModeling::Assembly::CountNumberOfAnglesIncludingHydrogen(), MolecularModeling::Assembly::CountNumberOfAngleTypes(), MolecularModeling::Assembly::CountNumberOfBonds(), MolecularModeling::Assembly::CountNumberOfBondsExcludingHydrogen(), MolecularModeling::Assembly::CountNumberOfBondsIncludingHydrogen(), MolecularModeling::Assembly::CountNumberOfBondTypes(), MolecularModeling::Assembly::CountNumberOfDihedrals(), MolecularModeling::Assembly::CountNumberOfDihedralsExcludingHydrogen(), MolecularModeling::Assembly::CountNumberOfDihedralsIncludingHydrogen(), MolecularModeling::Assembly::CountNumberOfDihedralTypes(), MolecularModeling::Assembly::CountNumberOfExcludedAtoms(), MolecularModeling::Assembly::ExtractTopologyDihedralsFromAssembly(), MolecularModeling::Assembly::ExtractTopologyDihedralTypesFromAssembly(), and MolecularModeling::Assembly::GetAllAtomsOfAssemblyWithAtLeastThreeNeighbors().
{
    return node_neighbors_;
}
void AtomNode::Print (std::ostream & out = std::cout)
Definition at line 56 of file atomnode.cc.
References MolecularModeling::Residue::GetId(), and MolecularModeling::Atom::GetResidue().
{
    int number_of_bonds = node_neighbors_.size();
    switch(number_of_bonds)
    {
        case 0:
            out << atom_->GetResidue()->GetId() << ":" << atom_->GetName() << endl;
            break;
        case 1:
            out << node_neighbors_.at(0)->GetResidue()->GetId() << ":" << node_neighbors_.at(0)->GetName() << " -- "
                << atom_->GetResidue()->GetId() << ":" << atom_->GetName() << endl;
            break;
        case 2:
            out << node_neighbors_.at(0)->GetResidue()->GetId() << ":" << node_neighbors_.at(0)->GetName() << " -- "
                << atom_->GetResidue()->GetId() << ":" << atom_->GetName() << " -- "
                << node_neighbors_.at(1)->GetResidue()->GetId() << ":" << node_neighbors_.at(1)->GetName() << endl;
            break;
        case 3:
            out << "\t\t" << node_neighbors_.at(0)->GetResidue()->GetId() << ":" << node_neighbors_.at(0)->GetName() << endl
                << "\t\t" << "  |  " << endl
                << "\t" << node_neighbors_.at(1)->GetResidue()->GetId() << ":" << node_neighbors_.at(1)->GetName() << " -- "
                << atom_->GetResidue()->GetId() << ":" << atom_->GetName() << endl
                << "\t\t" << "  |  " << endl
                << "\t\t" <<  node_neighbors_.at(2)->GetResidue()->GetId() << ":" << node_neighbors_.at(2)->GetName() << endl;
            break;
        case 4:
            out << "\t\t\t" << node_neighbors_.at(0)->GetResidue()->GetId() << ":" << node_neighbors_.at(0)->GetName() << endl
                << "\t\t\t" << "  |  " << endl
                << "\t" << node_neighbors_.at(1)->GetResidue()->GetId() << ":" << node_neighbors_.at(1)->GetName() << " -- "
                << atom_->GetResidue()->GetId() << ":" << atom_->GetName() << " -- "
                << node_neighbors_.at(2)->GetResidue()->GetId() << ":" << node_neighbors_.at(2)->GetName() << endl
                << "\t\t\t" << "  |  " << endl
                << "\t\t\t" << node_neighbors_.at(3)->GetResidue()->GetId() << ":" << node_neighbors_.at(3)->GetName() << endl;
            break;
        case 5:
            break;
    }
}
void AtomNode::SetAtom (Atom * atom)
Definition at line 32 of file atomnode.cc.
Referenced by MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), MolecularModeling::Assembly::BuildStructureByDistance(), MolecularModeling::Assembly::BuildStructureByLIBFileInformation(), MolecularModeling::Assembly::BuildStructureByPDBFileInformation(), MolecularModeling::Assembly::BuildStructureByPrepFileInformation(), and MolecularModeling::Assembly::BuildStructureByTOPFileInformation().
{
    atom_ = atom;
}
void AtomNode::SetId (int id)
Definition at line 48 of file atomnode.cc.
Referenced by MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), MolecularModeling::Assembly::BuildStructureByDistance(), MolecularModeling::Assembly::BuildStructureByLIBFileInformation(), MolecularModeling::Assembly::BuildStructureByPDBFileInformation(), MolecularModeling::Assembly::BuildStructureByPrepFileInformation(), and MolecularModeling::Assembly::BuildStructureByTOPFileInformation().
{
    id_ = id;
}
void AtomNode::SetNodeNeighbors (AtomVector node_neighbors)
Definition at line 36 of file atomnode.cc.
{
    node_neighbors_.clear();
    for(AtomVector::iterator it = node_neighbors.begin(); it != node_neighbors.end(); it++)
    {
        node_neighbors_.push_back(*it);
    }
}
The documentation for this class was generated from the following files:
includes/MolecularModeling/atomnode.hpp
src/MolecularModeling/atomnode.cc