gmmlNew: PdbFileSpace::PdbResidue Class Reference
PdbFileSpace::PdbResidue Class Reference
#include <pdbresidue.hpp>
Public Member Functions
PdbResidue ()
PdbResidue (std::string residue_name, char chain_id, int sequence_number, char insertion_code= ' ', char residue_alternate_location= ' ')
char GetResidueChainId ()
std::string GetResidueName ()
int GetResidueSequenceNumber ()
char GetResidueInsertionCode ()
char GetResidueAlternateLocation ()
void SetResidueChainId (char residue_chain_id)
void SetResidueName (std::string residue_name)
void SetResidueSequenceNumber (int residue_sequence_number)
void SetResidueInsertionCode (char residue_insertion_code)
void SetResidueAlternateLocation (char residue_alternate_location)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 9 of file pdbresidue.hpp.
Constructor & Destructor Documentation
PdbResidue::PdbResidue ()
Definition at line 9 of file pdbresidue.cc.
{}
PdbFileSpace::PdbResidue::PdbResidue (std::string residue_name, char chain_id, int sequence_number, char insertion_code = ' ', char residue_alternate_location = ' ')
Member Function Documentation
char PdbResidue::GetResidueAlternateLocation ()
Definition at line 33 of file pdbresidue.cc.
Referenced by PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::ExtractAlternateResidue(), PdbPreprocessorSpace::PdbPreprocessor::ExtractCYSResidues(), PdbPreprocessorSpace::PdbPreprocessor::ExtractHISResidues(), PdbFileSpace::PdbFile::GetAllAtomNamesOfResidue(), PdbFileSpace::PdbFile::GetAllAtomsOfResidue(), PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMapping(), PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMappingWithTheGivenNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return residue_alternate_location_;
}
char PdbResidue::GetResidueChainId ()
Definition at line 17 of file pdbresidue.cc.
Referenced by PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::ExtractAlternateResidue(), PdbPreprocessorSpace::PdbPreprocessor::ExtractAminoAcidChains(), PdbPreprocessorSpace::PdbPreprocessor::ExtractCYSResidues(), PdbPreprocessorSpace::PdbPreprocessor::ExtractGapsInAminoAcidChains(), PdbPreprocessorSpace::PdbPreprocessor::ExtractHISResidues(), PdbFileSpace::PdbFile::GetAllAtomNamesOfResidue(), PdbFileSpace::PdbFile::GetAllAtomsOfResidue(), PdbFileSpace::PdbFile::GetAllTerCardPositions(), PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMapping(), PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMappingWithTheGivenNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return residue_chain_id_;
}
char PdbResidue::GetResidueInsertionCode ()
Definition at line 29 of file pdbresidue.cc.
Referenced by PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::ExtractAlternateResidue(), PdbPreprocessorSpace::PdbPreprocessor::ExtractAminoAcidChains(), PdbPreprocessorSpace::PdbPreprocessor::ExtractCYSResidues(), PdbPreprocessorSpace::PdbPreprocessor::ExtractGapsInAminoAcidChains(), PdbPreprocessorSpace::PdbPreprocessor::ExtractHISResidues(), PdbFileSpace::PdbFile::GetAllAtomNamesOfResidue(), PdbFileSpace::PdbFile::GetAllAtomsOfResidue(), PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMapping(), PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMappingWithTheGivenNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return residue_insertion_code_;
}
string PdbResidue::GetResidueName ()
Definition at line 21 of file pdbresidue.cc.
Referenced by PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::ExtractAlternateResidue(), PdbFileSpace::PdbFile::GetAllAtomNamesOfResidue(), PdbFileSpace::PdbFile::GetAllAtomsOfResidue(), PdbPreprocessorSpace::PdbPreprocessor::GetAllCYSResidues(), PdbPreprocessorSpace::PdbPreprocessor::GetAllHISResidues(), PdbFileSpace::PdbFile::GetAllTerCardPositions(), PdbPreprocessorSpace::PdbPreprocessor::GetRecognizedResidues(), PdbPreprocessorSpace::PdbPreprocessor::GetUnrecognizedResidues(), PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMapping(), PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMappingWithTheGivenNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return residue_name_;
}
int PdbResidue::GetResidueSequenceNumber ()
Definition at line 25 of file pdbresidue.cc.
Referenced by PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::ExtractAlternateResidue(), PdbPreprocessorSpace::PdbPreprocessor::ExtractAminoAcidChains(), PdbPreprocessorSpace::PdbPreprocessor::ExtractCYSResidues(), PdbPreprocessorSpace::PdbPreprocessor::ExtractGapsInAminoAcidChains(), PdbPreprocessorSpace::PdbPreprocessor::ExtractHISResidues(), PdbFileSpace::PdbFile::GetAllAtomNamesOfResidue(), PdbFileSpace::PdbFile::GetAllAtomsOfResidue(), PdbFileSpace::PdbFile::GetAllTerCardPositions(), PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMapping(), PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMappingWithTheGivenNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return residue_sequence_number_;
}
void PdbResidue::Print (std::ostream & out = std::cout)
Definition at line 65 of file pdbresidue.cc.
{
    out << "Residue name: " << residue_name_
         << ", Chain id: " << residue_chain_id_
         << ", Sequence number: " << residue_sequence_number_
         << ", Insertion code: " << residue_insertion_code_
         << ", Alternate location: " << residue_alternate_location_ << endl;
}
void PdbResidue::SetResidueAlternateLocation (char residue_alternate_location)
Definition at line 57 of file pdbresidue.cc.
{
    residue_alternate_location_ = residue_alternate_location;
}
void PdbResidue::SetResidueChainId (char residue_chain_id)
Definition at line 41 of file pdbresidue.cc.
{
    residue_chain_id_ = residue_chain_id;
}
void PdbResidue::SetResidueInsertionCode (char residue_insertion_code)
Definition at line 53 of file pdbresidue.cc.
{
    residue_insertion_code_ = residue_insertion_code;
}
void PdbResidue::SetResidueName (std::string residue_name)
Definition at line 45 of file pdbresidue.cc.
{
    residue_name_ = residue_name;
}
void PdbResidue::SetResidueSequenceNumber (int residue_sequence_number)
Definition at line 49 of file pdbresidue.cc.
{
    residue_sequence_number_ = residue_sequence_number;
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbresidue.hpp
src/FileSet/PdbFileSpace/pdbresidue.cc