gmmlNew: ParameterFileSpace::ParameterFileAngle Class Reference
ParameterFileSpace::ParameterFileAngle Class Reference
#include <parameterfileangle.hpp>
Public Member Functions
ParameterFileAngle ()
ParameterFileAngle (const std::vector< std::string > &types, double force_constant, double angle, const std::string &dscr="")
std::vector< std::string > GetTypes ()
double GetForceConstant ()
Return force constant.
double GetAngle ()
Return angle.
std::string GetDscr ()
Return dscr.
void SetTypes (const std::vector< std::string > types)
void SetForceConstant (double force_constant)
Set force constant.
void SetAngle (double angle)
Set angle.
void SetDscr (const std::string dscr)
Set dscr.
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 10 of file parameterfileangle.hpp.
Constructor & Destructor Documentation
ParameterFileAngle::ParameterFileAngle ()
Definition at line 12 of file parameterfileangle.cc.
    : types_(), force_constant_(dNotSet), angle_(dNotSet), dscr_("") {}
ParameterFileAngle::ParameterFileAngle (const std::vector< std::string > & types, double force_constant, double angle, const std::string & dscr = "")
Definition at line 15 of file parameterfileangle.cc.
    : types_(types), force_constant_(force_constant), angle_(angle), dscr_(dscr) {}
Member Function Documentation
double ParameterFileAngle::GetAngle ()
Return angle.
Definition at line 34 of file parameterfileangle.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveAngleSection().
{
    return angle_;
}
std::string ParameterFileAngle::GetDscr ()
Return dscr.
Definition at line 40 of file parameterfileangle.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveAngleSection().
{
    return dscr_;
}
double ParameterFileAngle::GetForceConstant ()
Return force constant.
Definition at line 28 of file parameterfileangle.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveAngleSection().
{
    return force_constant_;
}
std::vector< std::string > ParameterFileAngle::GetTypes ()
Return the list of atom types involved in the current angle object
Definition at line 22 of file parameterfileangle.cc.
{
    return types_;
}
void ParameterFileAngle::Print (std::ostream & out = std::cout)
Definition at line 77 of file parameterfileangle.cc.
References gmml::dNotSet.
{
    for(std::vector<std::string>::iterator it = types_.begin(); it != types_.end(); it++)
    {
        if(it != types_.end() - 1)
        {
            out << std::setw(4) << (*it)
                << std::setw(2) << "-";
        }
        else
            out << std::setw(4) << (*it);
    }
    if (force_constant_ == dNotSet)
        out << std::setw(15) << "--";
    else
        out << std::setw(15) << force_constant_;
    if(angle_ == dNotSet)
        out << std::setw(10) << "--";
    else
        out << std::setw(10) << angle_;
    out << std::setw(60) << dscr_
        << std::endl;
}
void ParameterFileAngle::SetAngle (double angle)
Set angle.
Definition at line 65 of file parameterfileangle.cc.
{
    angle_ = angle;
}
void ParameterFileAngle::SetDscr (const std::string dscr)
Set dscr.
Definition at line 70 of file parameterfileangle.cc.
{
    dscr_ = dscr;
}
void ParameterFileAngle::SetForceConstant (double force_constant)
Set force constant.
Definition at line 59 of file parameterfileangle.cc.
{
    force_constant_ = force_constant;
}
void ParameterFileAngle::SetTypes (const std::vector< std::string > types)
Set the list of atom types involved in the current angle object
Definition at line 49 of file parameterfileangle.cc.
{
    types_.clear();
    for(std::vector<std::string>::iterator it = types.begin(); it != types.end(); it++)
    {
        types_.push_back(*it);
    }
}
The documentation for this class was generated from the following files:
includes/ParameterSet/ParameterFileSpace/parameterfileangle.hpp
src/ParameterSet/ParameterFileSpace/parameterfileangle.cc