gmmlNew: PdbFileSpace::PdbSiteResidue Class Reference
PdbFileSpace::PdbSiteResidue Class Reference
#include <pdbsiteresidue.hpp>
Public Member Functions
PdbSiteResidue ()
PdbSiteResidue (const std::string &residue_name, char residue_chain_id, int residue_sequence_number, char residue_insertion_code)
PdbSiteResidue (const std::string &section)
std::string GetResidueName ()
char GetResidueChainId ()
int GetResidueSequenceNumber ()
char GetResidueInsertionCode ()
void SetResidueName (const std::string residue_name)
void SetResidueChainId (char residue_chain_id)
void SetResidueSequenceNumber (int residue_sequence_number)
void SetResidueInsertionCode (char residue_insertion_code)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 12 of file pdbsiteresidue.hpp.
Constructor & Destructor Documentation
PdbSiteResidue::PdbSiteResidue ()
Definition at line 12 of file pdbsiteresidue.cc.
{}
PdbFileSpace::PdbSiteResidue::PdbSiteResidue (const std::string & residue_name, char residue_chain_id, int residue_sequence_number, char residue_insertion_code)
PdbFileSpace::PdbSiteResidue::PdbSiteResidue (const std::string & section)
Member Function Documentation
char PdbSiteResidue::GetResidueChainId ()
Definition at line 42 of file pdbsiteresidue.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSiteCard().
{
    return residue_chain_id_;
}
char PdbSiteResidue::GetResidueInsertionCode ()
Definition at line 50 of file pdbsiteresidue.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSiteCard().
{
    return residue_insertion_code_;
}
string PdbSiteResidue::GetResidueName ()
Definition at line 38 of file pdbsiteresidue.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSiteCard().
{
    return residue_name_;
}
int PdbSiteResidue::GetResidueSequenceNumber ()
Definition at line 46 of file pdbsiteresidue.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSiteCard().
{
    return residue_sequence_number_;
}
void PdbSiteResidue::Print (std::ostream & out = std::cout)
Definition at line 77 of file pdbsiteresidue.cc.
References gmml::iNotSet.
{
    out << "Residue Name: " << residue_name_
        << ", Residue Chain ID: " << residue_chain_id_
        << ", Residue Sequence Number: ";
    if(residue_sequence_number_ != iNotSet)
        out << residue_sequence_number_;
    else
        out << " ";
    out << ", Residue Insertion Code: " << residue_insertion_code_
        << endl << endl;
}
void PdbSiteResidue::SetResidueChainId (char residue_chain_id)
Definition at line 62 of file pdbsiteresidue.cc.
{
    residue_chain_id_ = residue_chain_id;
}
void PdbSiteResidue::SetResidueInsertionCode (char residue_insertion_code)
Definition at line 70 of file pdbsiteresidue.cc.
{
    residue_insertion_code_ = residue_insertion_code;
}
void PdbSiteResidue::SetResidueName (const std::string residue_name)
Definition at line 58 of file pdbsiteresidue.cc.
{
    residue_name_ = residue_name;
}
void PdbSiteResidue::SetResidueSequenceNumber (int residue_sequence_number)
Definition at line 66 of file pdbsiteresidue.cc.
{
    residue_sequence_number_ = residue_sequence_number;
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbsiteresidue.hpp
src/FileSet/PdbFileSpace/pdbsiteresidue.cc