gmmlNew: MolecularModeling::Residue Class Reference
MolecularModeling::Residue Class Reference
#include <residue.hpp>
Public Types
typedef std::vector< Atom * > AtomVector
Public Member Functions
Residue ()
Assembly * GetAssembly ()
std::string GetName ()
AtomVector GetAtoms ()
AtomVector GetHeadAtoms ()
AtomVector GetTailAtoms ()
std::string GetChemicalType ()
std::string GetDescription ()
std::string GetId ()
void SetAssembly (Assembly *assembly)
void SetName (std::string name)
void SetAtoms (AtomVector atoms)
void AddAtom (Atom *atom)
void SetHeadAtoms (AtomVector head_atoms)
void AddHeadAtom (Atom *head_atom)
void SetTailAtoms (AtomVector tail_atoms)
void AddTailAtom (Atom *tail_atom)
void SetChemicalType (std::string chemical_type)
void SetDescription (std::string description)
void SetId (std::string id)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 13 of file residue.hpp.
Member Typedef Documentation
typedef std::vector<Atom*> MolecularModeling::Residue::AtomVector
Definition at line 19 of file residue.hpp.
Constructor & Destructor Documentation
Residue::Residue ()
Definition at line 10 of file residue.cc.
{}
Member Function Documentation
void Residue::AddAtom (Atom * atom)
Definition at line 67 of file residue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), MolecularModeling::Assembly::BuildAssemblyFromTopologyCoordinateFile(), and MolecularModeling::Assembly::BuildAssemblyFromTopologyFile().
{
    atoms_.push_back(atom);
}
void Residue::AddHeadAtom (Atom * head_atom)
Definition at line 79 of file residue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), and MolecularModeling::Assembly::BuildAssemblyFromPrepFile().
{
    head_atoms_.push_back(head_atom);
}
void Residue::AddTailAtom (Atom * tail_atom)
Definition at line 91 of file residue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), and MolecularModeling::Assembly::BuildAssemblyFromPrepFile().
{
    tail_atoms_.push_back(tail_atom);
}
Assembly * Residue::GetAssembly ()
Definition at line 15 of file residue.cc.
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly().
{
    return assembly_;
}
Residue::AtomVector Residue::GetAtoms ()
Definition at line 23 of file residue.cc.
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly(), MolecularModeling::Assembly::BuildPrepFileStructureFromAssembly(), MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly(), MolecularModeling::Assembly::CalculateCenterOfGeometry(), MolecularModeling::Assembly::CountMaxNumberOfAtomsInLargestResidue(), MolecularModeling::Assembly::CountNumberOfAtoms(), MolecularModeling::Assembly::ExtractPdbModelCardFromAssembly(), MolecularModeling::Assembly::GetAllAtomsOfAssembly(), and MolecularModeling::Assembly::GetAllCoordinates().
{
    return atoms_;
}
string Residue::GetChemicalType ()
Definition at line 35 of file residue.cc.
{
    return chemical_type_;
}
string Residue::GetDescription ()
Definition at line 39 of file residue.cc.
{
    return description_;
}
Residue::AtomVector Residue::GetHeadAtoms ()
Definition at line 27 of file residue.cc.
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly().
{
    return head_atoms_;
}
string Residue::GetId ()
Definition at line 43 of file residue.cc.
Referenced by MolecularModeling::AtomNode::Print().
{
    return id_;
}
string Residue::GetName ()
Definition at line 19 of file residue.cc.
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly(), MolecularModeling::Assembly::BuildPrepFileStructureFromAssembly(), MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), MolecularModeling::Assembly::BuildStructureByLIBFileInformation(), MolecularModeling::Assembly::BuildStructureByPrepFileInformation(), MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly(), MolecularModeling::Assembly::ExtractPdbModelCardFromAssembly(), MolecularModeling::Assembly::ExtractTopologyAnglesFromAssembly(), MolecularModeling::Assembly::ExtractTopologyBondsFromAssembly(), MolecularModeling::Assembly::ExtractTopologyDihedralsFromAssembly(), and Print().
{
    return name_;
}
Residue::AtomVector Residue::GetTailAtoms ()
Definition at line 31 of file residue.cc.
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly().
{
    return tail_atoms_;
}
void Residue::Print (std::ostream & out = std::cout)
Definition at line 111 of file residue.cc.
References GetName(), MolecularModeling::Atom::GetName(), MolecularModeling::Atom::GetResidue(), and MolecularModeling::Atom::Print().
Referenced by MolecularModeling::Assembly::Print().
{
    out << "------------------------ " << name_ << " --------------------------" << endl;
    out << "Head atoms: ";
    for(AtomVector::iterator it = head_atoms_.begin(); it != head_atoms_.end(); it++)
    {
        Atom* atom = *it;
        out << atom->GetResidue()->GetName() << ":" << atom->GetName() << "; ";
    }
    out << endl;
    out << "Tail atoms: ";
    for(AtomVector::iterator it = tail_atoms_.begin(); it != tail_atoms_.end(); it++)
    {
        Atom* atom = *it;
        out << atom->GetResidue()->GetName() << ":" << atom->GetName() << "; ";
    }
    out << endl;
    for(AtomVector::iterator it = atoms_.begin(); it != atoms_.end(); it++)
    {
        Atom* atom = *it;
        atom->Print(out);
    }
}
void Residue::SetAssembly (Assembly * assembly)
Definition at line 51 of file residue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), MolecularModeling::Assembly::BuildAssemblyFromTopologyCoordinateFile(), and MolecularModeling::Assembly::BuildAssemblyFromTopologyFile().
{
    assembly_ = assembly;
}
void Residue::SetAtoms (AtomVector atoms)
Definition at line 59 of file residue.cc.
{
    atoms_.clear();
    for(AtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        atoms_.push_back(*it);
    }
}
void Residue::SetChemicalType (std::string chemical_type)
Definition at line 95 of file residue.cc.
{
    chemical_type_ = chemical_type;
}
void Residue::SetDescription (std::string description)
Definition at line 99 of file residue.cc.
{
    description_ = description;
}
void Residue::SetHeadAtoms (AtomVector head_atoms)
Definition at line 71 of file residue.cc.
{
    head_atoms_.clear();
    for(AtomVector::iterator it = head_atoms.begin(); it != head_atoms.end(); it++)
    {
        head_atoms_.push_back(*it);
    }
}
void Residue::SetId (std::string id)
Definition at line 103 of file residue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), MolecularModeling::Assembly::BuildAssemblyFromTopologyCoordinateFile(), and MolecularModeling::Assembly::BuildAssemblyFromTopologyFile().
{
    id_ = id;
}
void Residue::SetName (std::string name)
Definition at line 55 of file residue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildAssemblyFromPrepFile(), MolecularModeling::Assembly::BuildAssemblyFromTopologyCoordinateFile(), and MolecularModeling::Assembly::BuildAssemblyFromTopologyFile().
{
    name_ = name;
}
void Residue::SetTailAtoms (AtomVector tail_atoms)
Definition at line 83 of file residue.cc.
{
    tail_atoms_.clear();
    for(AtomVector::iterator it = tail_atoms.begin(); it != tail_atoms.end(); it++)
    {
        tail_atoms_.push_back(*it);
    }
}
The documentation for this class was generated from the following files:
includes/MolecularModeling/residue.hpp
src/MolecularModeling/residue.cc