gmmlNew: PdbFileSpace::PdbDisulfideResidueBond Class Reference
PdbFileSpace::PdbDisulfideResidueBond Class Reference
#include <pdbdisulfideresiduebond.hpp>
Public Types
typedef std::vector
< PdbDisulfideResidue * > DisulfideResidueVector
Public Member Functions
PdbDisulfideResidueBond ()
PdbDisulfideResidueBond (int serial_number, const DisulfideResidueVector residues, double bond_length)
PdbDisulfideResidueBond (std::string &line)
int GetSerialNumber ()
DisulfideResidueVector GetResidues ()
double GetBondLength ()
void SetSerialNumber (int serial_number)
void SetResidues (const DisulfideResidueVector residues)
void AddResidue (PdbDisulfideResidue *residue)
void SetBondLength (double bond_length)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 14 of file pdbdisulfideresiduebond.hpp.
Member Typedef Documentation
typedef std::vector<PdbDisulfideResidue*> PdbFileSpace::PdbDisulfideResidueBond::DisulfideResidueVector
Definition at line 23 of file pdbdisulfideresiduebond.hpp.
Constructor & Destructor Documentation
PdbDisulfideResidueBond::PdbDisulfideResidueBond ()
Definition at line 14 of file pdbdisulfideresiduebond.cc.
: serial_number_(dNotSet), bond_length_(dNotSet) {}
PdbDisulfideResidueBond::PdbDisulfideResidueBond (int serial_number, const DisulfideResidueVector residues, double bond_length)
Definition at line 16 of file pdbdisulfideresiduebond.cc.
    : serial_number_(serial_number), bond_length_(bond_length)
{
    residues_.clear();
    for(DisulfideResidueVector::const_iterator it = residues.begin(); it != residues.end(); it++)
    {
        residues_.push_back(*it);
    }
}
PdbFileSpace::PdbDisulfideResidueBond::PdbDisulfideResidueBond (std::string & line)
Member Function Documentation
void PdbDisulfideResidueBond::AddResidue (PdbDisulfideResidue * residue)
Definition at line 121 of file pdbdisulfideresiduebond.cc.
{
    residues_.push_back(residue);
}
double PdbDisulfideResidueBond::GetBondLength ()
Definition at line 99 of file pdbdisulfideresiduebond.cc.
Referenced by PdbFileSpace::PdbFile::ResolveDisulfideBondCard().
{
    return bond_length_;
}
PdbDisulfideResidueBond::DisulfideResidueVector PdbDisulfideResidueBond::GetResidues ()
Definition at line 94 of file pdbdisulfideresiduebond.cc.
Referenced by PdbFileSpace::PdbFile::ResolveDisulfideBondCard().
{
    return residues_;
}
int PdbDisulfideResidueBond::GetSerialNumber ()
Definition at line 89 of file pdbdisulfideresiduebond.cc.
Referenced by PdbFileSpace::PdbFile::ResolveDisulfideBondCard().
{
    return serial_number_;
}
void PdbDisulfideResidueBond::Print (std::ostream & out = std::cout)
Definition at line 138 of file pdbdisulfideresiduebond.cc.
References gmml::dNotSet, and gmml::iNotSet.
{
    out << "Serial Number: ";
    if(serial_number_ != iNotSet)
        out << serial_number_ << endl;
    else
        out << " " << endl;
    out << "----------------- Residues -----------------" << endl;
    for(PdbDisulfideResidueBond::DisulfideResidueVector::iterator it = residues_.begin(); it != residues_.end(); it++)
    {
        (*it)->Print(out);
        out << endl;
    }
    out << "Bond Length: ";
    if(bond_length_ != dNotSet)
        out << bond_length_ << endl << endl;
    else
        out << " " << endl << endl;
}
void PdbDisulfideResidueBond::SetBondLength (double bond_length)
Definition at line 126 of file pdbdisulfideresiduebond.cc.
{
    bond_length_ = bond_length;
}
void PdbDisulfideResidueBond::SetResidues (const DisulfideResidueVector residues)
Definition at line 112 of file pdbdisulfideresiduebond.cc.
{
    residues_.clear();
    for(DisulfideResidueVector::const_iterator it = residues.begin(); it != residues.end(); it++)
    {
        residues_.push_back(*it);
    }
}
void PdbDisulfideResidueBond::SetSerialNumber (int serial_number)
Definition at line 107 of file pdbdisulfideresiduebond.cc.
{
    serial_number_ = serial_number;
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbdisulfideresiduebond.hpp
src/FileSet/PdbFileSpace/pdbdisulfideresiduebond.cc