gmmlNew: PdbFileSpace::PdbSheet Class Reference
PdbFileSpace::PdbSheet Class Reference
#include <pdbsheet.hpp>
Public Types
typedef std::vector
< PdbSheetStrand * > SheetStrandVector
Public Member Functions
PdbSheet ()
PdbSheet (const std::string &sheet_id, int number_of_strands, const SheetStrandVector strands)
PdbSheet (std::stringstream &sheet_block)
std::string GetSheetId ()
int GetNumberOfStrands ()
SheetStrandVector GetStrands ()
void SetSheetId (const std::string sheet_id)
void SetNumberOfStrands (int number_of_strands)
void SetStrands (const SheetStrandVector strands)
void AddStrand (PdbSheetStrand *strand)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 15 of file pdbsheet.hpp.
Member Typedef Documentation
typedef std::vector<PdbSheetStrand*> PdbFileSpace::PdbSheet::SheetStrandVector
Definition at line 24 of file pdbsheet.hpp.
Constructor & Destructor Documentation
PdbSheet::PdbSheet ()
Definition at line 18 of file pdbsheet.cc.
:  sheet_id_(""), number_of_strands_(dNotSet) {}
PdbFileSpace::PdbSheet::PdbSheet (const std::string & sheet_id, int number_of_strands, const SheetStrandVector strands)
PdbFileSpace::PdbSheet::PdbSheet (std::stringstream & sheet_block)
Member Function Documentation
void PdbSheet::AddStrand (PdbSheetStrand * strand)
Definition at line 103 of file pdbsheet.cc.
{
    strands_.push_back(strand);
}
int PdbSheet::GetNumberOfStrands ()
Definition at line 71 of file pdbsheet.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSheetCard().
{
    return number_of_strands_;
}
string PdbSheet::GetSheetId ()
Definition at line 66 of file pdbsheet.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSheetCard().
{
    return sheet_id_;
}
PdbSheet::SheetStrandVector PdbSheet::GetStrands ()
Definition at line 76 of file pdbsheet.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSheetCard().
{
    return strands_;
}
void PdbSheet::Print (std::ostream & out = std::cout)
Definition at line 115 of file pdbsheet.cc.
References gmml::iNotSet.
{
    out << "Sheet ID: " << sheet_id_
        << ", Number of Strands: ";
    if(number_of_strands_ != iNotSet)
        out << number_of_strands_;
    else
        out << " ";
    out << endl << "------------------- Strands ------------------" << endl;
    for(PdbSheet::SheetStrandVector::iterator it = strands_.begin(); it != strands_.end(); it++)
    {
        (*it)->Print(out);
        out << endl;
    }
    out << endl;
}
void PdbSheet::SetNumberOfStrands (int number_of_strands)
Definition at line 89 of file pdbsheet.cc.
{
    number_of_strands_ = number_of_strands;
}
void PdbSheet::SetSheetId (const std::string sheet_id)
Definition at line 84 of file pdbsheet.cc.
{
    sheet_id_ = sheet_id;
}
void PdbSheet::SetStrands (const SheetStrandVector strands)
Definition at line 94 of file pdbsheet.cc.
{
    strands_.clear();
    for(SheetStrandVector::const_iterator it = strands.begin(); it != strands.end(); it++)
    {
        strands_.push_back(*it);
    }
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbsheet.hpp
src/FileSet/PdbFileSpace/pdbsheet.cc