gmmlNew: PdbPreprocessorSpace::PdbPreprocessorHistidineMapping Class Reference
PdbPreprocessorSpace::PdbPreprocessorHistidineMapping Class Reference
#include <pdbpreprocessorhistidinemapping.hpp>
Public Member Functions
PdbPreprocessorHistidineMapping ()
PdbPreprocessorHistidineMapping (char chain_id, int residue_sequence_number, gmml::PdbPreprocessorHISMapping selected_mapping, char residue_insertion_code, char residue_alternate_location)
char GetResidueChainId ()
int GetResidueSequenceNumber ()
gmml::PdbPreprocessorHISMapping GetSelectedMapping ()
char GetResidueInsertionCode ()
char GetResidueAlternateLocation ()
std::string GetStringFormatOfSelectedMapping ()
std::string GetStringFormatOfMapping (gmml::PdbPreprocessorHISMapping mapping)
std::vector< std::string > GetAllHISMappingAsString ()
void SetResidueChainId (char residue_chain_id)
void SetResidueSequenceNumber (int residue_sequence_number)
void SetSelectedMapping (gmml::PdbPreprocessorHISMapping selected_mapping)
void SetResidueInsertionCode (char residue_insertion_code)
void SetResidueAlternateLocation (char residue_alternate_location)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 12 of file pdbpreprocessorhistidinemapping.hpp.
Constructor & Destructor Documentation
PdbPreprocessorHistidineMapping::PdbPreprocessorHistidineMapping ()
Definition at line 11 of file pdbpreprocessorhistidinemapping.cc.
{}
PdbPreprocessorHistidineMapping::PdbPreprocessorHistidineMapping (char chain_id, int residue_sequence_number, gmml::PdbPreprocessorHISMapping selected_mapping, char residue_insertion_code, char residue_alternate_location)
Definition at line 13 of file pdbpreprocessorhistidinemapping.cc.
                                                                                                                               :
    residue_chain_id_(residue_chain_id), residue_sequence_number_(residue_sequence_number), selected_mapping_(selected_mapping),
    residue_insertion_code_(residue_insertion_code), residue_alternate_location_(residue_alternate_location) {}
Member Function Documentation
vector< string > PdbPreprocessorHistidineMapping::GetAllHISMappingAsString ()
Definition at line 69 of file pdbpreprocessorhistidinemapping.cc.
References GetStringFormatOfMapping(), gmml::HID, and gmml::HIE.
{
    vector<string> all_his_mapping_as_string;
    for(int his_mapping = HIE; his_mapping != HID; his_mapping++)
        all_his_mapping_as_string.push_back(GetStringFormatOfMapping((PdbPreprocessorHISMapping)his_mapping));
    return all_his_mapping_as_string;
}
char PdbPreprocessorHistidineMapping::GetResidueAlternateLocation ()
Definition at line 37 of file pdbpreprocessorhistidinemapping.cc.
Referenced by Print(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMapping().
{
    return residue_alternate_location_;
}
char PdbPreprocessorHistidineMapping::GetResidueChainId ()
Definition at line 21 of file pdbpreprocessorhistidinemapping.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMapping().
{
    return residue_chain_id_;
}
char PdbPreprocessorHistidineMapping::GetResidueInsertionCode ()
Definition at line 33 of file pdbpreprocessorhistidinemapping.cc.
Referenced by Print(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMapping().
{
    return residue_insertion_code_;
}
int PdbPreprocessorHistidineMapping::GetResidueSequenceNumber ()
Definition at line 25 of file pdbpreprocessorhistidinemapping.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMapping().
{
    return residue_sequence_number_;
}
PdbPreprocessorHISMapping PdbPreprocessorHistidineMapping::GetSelectedMapping ()
Definition at line 29 of file pdbpreprocessorhistidinemapping.cc.
{
    return selected_mapping_;
}
string PdbPreprocessorHistidineMapping::GetStringFormatOfMapping (gmml::PdbPreprocessorHISMapping mapping)
Definition at line 55 of file pdbpreprocessorhistidinemapping.cc.
Referenced by GetAllHISMappingAsString().
{
    switch(his_mapping)
    {
        case 1:
            return "HIE";
        case 2:
            return "HIP";
        case 3:
            return "HID";
        default:
            return "";
    }
}
string PdbPreprocessorHistidineMapping::GetStringFormatOfSelectedMapping ()
Definition at line 41 of file pdbpreprocessorhistidinemapping.cc.
Referenced by Print(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMapping().
{
    switch(selected_mapping_)
    {
        case 1:
            return "HIE";
        case 2:
            return "HIP";
        case 3:
            return "HID";
        default:
            return "";
    }
}
void PdbPreprocessorHistidineMapping::Print (std::ostream & out = std::cout)
Definition at line 104 of file pdbpreprocessorhistidinemapping.cc.
References GetResidueAlternateLocation(), GetResidueInsertionCode(), and GetStringFormatOfSelectedMapping().
{
    out << "Chain id: " << residue_chain_id_
         << ", Sequence_number: " << residue_sequence_number_
         << ", Selected mapping: " << GetStringFormatOfSelectedMapping()
         << ", Insertion code: " << GetResidueInsertionCode()
         << ", Alternate location: " << GetResidueAlternateLocation()
         << endl;
}
void PdbPreprocessorHistidineMapping::SetResidueAlternateLocation (char residue_alternate_location)
Definition at line 96 of file pdbpreprocessorhistidinemapping.cc.
{
    residue_alternate_location_ = residue_alternate_location;
}
void PdbPreprocessorHistidineMapping::SetResidueChainId (char residue_chain_id)
Definition at line 80 of file pdbpreprocessorhistidinemapping.cc.
{
    residue_chain_id_ = residue_chain_id;
}
void PdbPreprocessorHistidineMapping::SetResidueInsertionCode (char residue_insertion_code)
Definition at line 92 of file pdbpreprocessorhistidinemapping.cc.
{
    residue_insertion_code_ = residue_insertion_code;
}
void PdbPreprocessorHistidineMapping::SetResidueSequenceNumber (int residue_sequence_number)
Definition at line 84 of file pdbpreprocessorhistidinemapping.cc.
{
    residue_sequence_number_ = residue_sequence_number;
}
void PdbPreprocessorHistidineMapping::SetSelectedMapping (gmml::PdbPreprocessorHISMapping selected_mapping)
Definition at line 88 of file pdbpreprocessorhistidinemapping.cc.
{
    selected_mapping_ = selected_mapping;
}
The documentation for this class was generated from the following files:
includes/Resolver/PdbPreprocessor/pdbpreprocessorhistidinemapping.hpp
src/Resolver/PdbPreprocessor/pdbpreprocessorhistidinemapping.cc