gmmlNew: ParameterFileSpace::ParameterFileAtom Class Reference
ParameterFileSpace::ParameterFileAtom Class Reference
#include <parameterfileatom.hpp>
Public Member Functions
ParameterFileAtom ()
ParameterFileAtom (const std::string &type, double mass, double polarizability, const std::string &dscr="")
ParameterFileAtom (const std::string &type, double mass, double polarizability, double radius, double well_depth, const std::string &dscr="", const std::string &mod4_dscr="")
ParameterFileAtom (const std::string &type, double mass, double polarizability, double radius, double well_depth, const std::vector< std::string > &equivalent_list, const std::string &dscr="", const std::string &mod4_dscr="", bool is_hydrophilic=false)
std::string GetType ()
double GetMass ()
Returns mass.
double GetPolarizability ()
Returns polarizability.
std::string GetDscr ()
Return dscr.
double GetRadius ()
Returns Radius.
double GetWellDepth ()
Retunrs well debpth.
std::string GetMod4Dscr ()
Returns mod4 dscr.
bool GetIsHydrophilic ()
Returns is_hydrophilic.
std::vector< std::string > GetEquivalentList ()
Returns equivalent_list.
void SetType (std::string type)
void SetMass (double mass)
void SetPolarizability (double polarizability)
void SetDscr (std::string dscr)
void SetRadius (double radius)
void SetWellDepth (double well_depth)
void SetMod4Dscr (std::string mod4_dscr)
void SetIsHydrophilic (bool is_hydrophilic)
void SetEquivalentList (std::vector< std::string > equivalent_list)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 10 of file parameterfileatom.hpp.
Constructor & Destructor Documentation
ParameterFileAtom::ParameterFileAtom ()
Definition at line 13 of file parameterfileatom.cc.
    : type_(""), mass_(dNotSet), polarizability_(dNotSet), dscr_(""), radius_(dNotSet), well_depth_(dNotSet), mod4_dscr_("") {}
ParameterFileAtom::ParameterFileAtom (const std::string & type, double mass, double polarizability, const std::string & dscr = "")
Definition at line 16 of file parameterfileatom.cc.
    : type_(type), mass_(mass), polarizability_(polarizability),dscr_(dscr), radius_(dNotSet), well_depth_(dNotSet), is_hydrophilic_(false) {}
ParameterFileAtom::ParameterFileAtom (const std::string & type, double mass, double polarizability, double radius, double well_depth, const std::string & dscr = "", const std::string & mod4_dscr = "")
Definition at line 19 of file parameterfileatom.cc.
    : type_(type), mass_(mass), polarizability_(polarizability), dscr_(dscr), radius_(radius), well_depth_(well_depth), mod4_dscr_(mod4_dscr) {}
ParameterFileAtom::ParameterFileAtom (const std::string & type, double mass, double polarizability, double radius, double well_depth, const std::vector< std::string > & equivalent_list, const std::string & dscr = "", const std::string & mod4_dscr = "", bool is_hydrophilic = false)
Definition at line 23 of file parameterfileatom.cc.
    : type_(type), mass_(mass), polarizability_(polarizability), dscr_(dscr), radius_(radius), well_depth_(well_depth), mod4_dscr_(mod4_dscr),
      is_hydrophilic_(is_hydrophilic), equivalent_list_(equivalent_list) {}
Member Function Documentation
std::string ParameterFileAtom::GetDscr ()
Return dscr.
Definition at line 51 of file parameterfileatom.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveAtomTypeSection().
{
    return dscr_;
}
std::vector< std::string > ParameterFileAtom::GetEquivalentList ()
Returns equivalent_list.
Definition at line 81 of file parameterfileatom.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveEquivalentSymbolsSection().
{
    return equivalent_list_;
}
bool ParameterFileAtom::GetIsHydrophilic ()
Returns is_hydrophilic.
Definition at line 75 of file parameterfileatom.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveHydrophilicAtomTypeSection().
{
    return is_hydrophilic_;
}
double ParameterFileAtom::GetMass ()
Returns mass.
Definition at line 38 of file parameterfileatom.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveAtomTypeSection().
{
    return mass_;
}
std::string ParameterFileAtom::GetMod4Dscr ()
Returns mod4 dscr.
Definition at line 69 of file parameterfileatom.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolvePotentialParameterSection().
{
    return mod4_dscr_;
}
double ParameterFileAtom::GetPolarizability ()
Returns polarizability.
Definition at line 45 of file parameterfileatom.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveAtomTypeSection().
{
    return polarizability_;
}
double ParameterFileAtom::GetRadius ()
Returns Radius.
Definition at line 57 of file parameterfileatom.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolvePotentialParameterSection().
{
    return radius_;
}
std::string ParameterFileAtom::GetType ()
Retuns type
Definition at line 32 of file parameterfileatom.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveAtomTypeSection(), ParameterFileSpace::ParameterFile::ResolveEquivalentSymbolsSection(), ParameterFileSpace::ParameterFile::ResolveHydrophilicAtomTypeSection(), and ParameterFileSpace::ParameterFile::ResolvePotentialParameterSection().
{
    return type_;
}
double ParameterFileAtom::GetWellDepth ()
Retunrs well debpth.
Definition at line 63 of file parameterfileatom.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolvePotentialParameterSection().
{
    return well_depth_;
}
void ParameterFileAtom::Print (std::ostream & out = std::cout)
Definition at line 134 of file parameterfileatom.cc.
References gmml::dNotSet.
{
    out << std::setw(6) << type_;
    if(mass_ == dNotSet)
        out << std::setw(6) << "--";
    else
        out << std::setw(6) << mass_;
    if(polarizability_ == dNotSet)
        out << std::setw(16) << "--";
    else
        out << std::setw(16) << polarizability_;
    if(radius_ == dNotSet)
        out << std::setw(8) << "--";
    else
        out << std::setw(8) << radius_;
    if(well_depth_ == dNotSet)
        out << std::setw(12) << "--";
    else
        out << std::setw(12) << well_depth_;
    if(is_hydrophilic_ == true)
        out << std::setw(13) << "YES";
    else
        out << std::setw(13) << "NO";
    out << std::setw(60) << dscr_
        << std::setw(60) << mod4_dscr_
        << std::endl;
    if(!equivalent_list_.empty())
    {
        out << std::setw(20) << "" << "Equivalent symbols: ";
        for(std::vector<std::string>::iterator it = equivalent_list_.begin(); it != equivalent_list_.end(); it++)
        {
            out << (*it) << "   ";
        }
        out << std::endl;
    }
}
void ParameterFileAtom::SetDscr (std::string dscr)
Definition at line 102 of file parameterfileatom.cc.
{
    dscr_ = dscr;
}
void ParameterFileAtom::SetEquivalentList (std::vector< std::string > equivalent_list)
Definition at line 123 of file parameterfileatom.cc.
{
    equivalent_list_.clear();
    for(std::vector<std::string>::iterator it = equivalent_list.begin(); it != equivalent_list.end(); it++)
    {
        equivalent_list_.push_back(*it);
    }
}
void ParameterFileAtom::SetIsHydrophilic (bool is_hydrophilic)
Definition at line 119 of file parameterfileatom.cc.
{
    is_hydrophilic_ = is_hydrophilic;
}
void ParameterFileAtom::SetMass (double mass)
Definition at line 94 of file parameterfileatom.cc.
{
    mass_ = mass;
}
void ParameterFileAtom::SetMod4Dscr (std::string mod4_dscr)
Definition at line 114 of file parameterfileatom.cc.
{
    mod4_dscr_ = mod4_dscr;
}
void ParameterFileAtom::SetPolarizability (double polarizability)
Definition at line 98 of file parameterfileatom.cc.
{
    polarizability_ = polarizability;
}
void ParameterFileAtom::SetRadius (double radius)
Definition at line 106 of file parameterfileatom.cc.
{
    radius_ = radius;
}
void ParameterFileAtom::SetType (std::string type)
Definition at line 90 of file parameterfileatom.cc.
{
    type_ = type;
}
void ParameterFileAtom::SetWellDepth (double well_depth)
Definition at line 110 of file parameterfileatom.cc.
{
    well_depth_ = well_depth;
}
The documentation for this class was generated from the following files:
includes/ParameterSet/ParameterFileSpace/parameterfileatom.hpp
src/ParameterSet/ParameterFileSpace/parameterfileatom.cc