gmmlNew: PdbPreprocessorSpace::PdbPreprocessorUnrecognizedResidue Class Reference
PdbPreprocessorSpace::PdbPreprocessorUnrecognizedResidue Class Reference
#include <pdbpreprocessorunrecognizedresidue.hpp>
Public Member Functions
PdbPreprocessorUnrecognizedResidue ()
PdbPreprocessorUnrecognizedResidue (std::string residue_name, char chain_id, int sequence_number, char residue_insertion_code, char residue_alternate_location, bool middle_of_chain)
char GetResidueChainId ()
int GetResidueSequenceNumber ()
std::string GetResidueName ()
char GetResidueInsertionCode ()
char GetResidueAlternateLocation ()
bool GetMiddleOfChain ()
void SetResidueChainId (char residue_chain_id)
void SetResidueSequenceNumber (int residue_sequence_number)
void SetResidueName (std::string residue_name)
void SetResidueInsertionCode (char residue_insertion_code)
void SetResidueAlternateLocation (char residue_alternate_location)
void SetMiddleOfChain (bool middle_of_chain)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 9 of file pdbpreprocessorunrecognizedresidue.hpp.
Constructor & Destructor Documentation
PdbPreprocessorUnrecognizedResidue::PdbPreprocessorUnrecognizedResidue ()
Definition at line 10 of file pdbpreprocessorunrecognizedresidue.cc.
{}
PdbPreprocessorSpace::PdbPreprocessorUnrecognizedResidue::PdbPreprocessorUnrecognizedResidue (std::string residue_name, char chain_id, int sequence_number, char residue_insertion_code, char residue_alternate_location, bool middle_of_chain)
Member Function Documentation
bool PdbPreprocessorUnrecognizedResidue::GetMiddleOfChain ()
Definition at line 40 of file pdbpreprocessorunrecognizedresidue.cc.
{
    return middle_of_chain_;
}
char PdbPreprocessorUnrecognizedResidue::GetResidueAlternateLocation ()
Definition at line 36 of file pdbpreprocessorunrecognizedresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveUnrecognizedResidues(), and PdbPreprocessorSpace::PdbPreprocessor::RemoveUnrecognizedResiduesWithTheGivenModelNumber().
{
    return residue_alternate_location_;
}
char PdbPreprocessorUnrecognizedResidue::GetResidueChainId ()
Definition at line 20 of file pdbpreprocessorunrecognizedresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveUnrecognizedResidues(), and PdbPreprocessorSpace::PdbPreprocessor::RemoveUnrecognizedResiduesWithTheGivenModelNumber().
{
    return residue_chain_id_;
}
char PdbPreprocessorUnrecognizedResidue::GetResidueInsertionCode ()
Definition at line 32 of file pdbpreprocessorunrecognizedresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveUnrecognizedResidues(), and PdbPreprocessorSpace::PdbPreprocessor::RemoveUnrecognizedResiduesWithTheGivenModelNumber().
{
    return residue_insertion_code_;
}
string PdbPreprocessorUnrecognizedResidue::GetResidueName ()
Definition at line 28 of file pdbpreprocessorunrecognizedresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveUnrecognizedResidues(), and PdbPreprocessorSpace::PdbPreprocessor::RemoveUnrecognizedResiduesWithTheGivenModelNumber().
{
    return residue_name_;
}
int PdbPreprocessorUnrecognizedResidue::GetResidueSequenceNumber ()
Definition at line 24 of file pdbpreprocessorunrecognizedresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::RemoveUnrecognizedResidues(), and PdbPreprocessorSpace::PdbPreprocessor::RemoveUnrecognizedResiduesWithTheGivenModelNumber().
{
    return residue_sequence_number_;
}
void PdbPreprocessorUnrecognizedResidue::Print (std::ostream & out = std::cout)
Definition at line 76 of file pdbpreprocessorunrecognizedresidue.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::Print().
{
    out << "Residue name: " << residue_name_
         << ", Chain id: " << residue_chain_id_
         << ", Sequence number: " << residue_sequence_number_
         << ", Insertion code: " << residue_insertion_code_
         << ", Alternate location: " << residue_alternate_location_
         << ", In the middle of chain: " << middle_of_chain_
         << endl;
}
void PdbPreprocessorUnrecognizedResidue::SetMiddleOfChain (bool middle_of_chain)
Definition at line 68 of file pdbpreprocessorunrecognizedresidue.cc.
{
    middle_of_chain_ = middle_of_chain;
}
void PdbPreprocessorUnrecognizedResidue::SetResidueAlternateLocation (char residue_alternate_location)
Definition at line 64 of file pdbpreprocessorunrecognizedresidue.cc.
{
    residue_alternate_location_ = residue_alternate_location;
}
void PdbPreprocessorUnrecognizedResidue::SetResidueChainId (char residue_chain_id)
Definition at line 48 of file pdbpreprocessorunrecognizedresidue.cc.
{
    residue_chain_id_ = residue_chain_id;
}
void PdbPreprocessorUnrecognizedResidue::SetResidueInsertionCode (char residue_insertion_code)
Definition at line 60 of file pdbpreprocessorunrecognizedresidue.cc.
{
    residue_insertion_code_ = residue_insertion_code;
}
void PdbPreprocessorUnrecognizedResidue::SetResidueName (std::string residue_name)
Definition at line 56 of file pdbpreprocessorunrecognizedresidue.cc.
{
    residue_name_ = residue_name;
}
void PdbPreprocessorUnrecognizedResidue::SetResidueSequenceNumber (int residue_sequence_number)
Definition at line 52 of file pdbpreprocessorunrecognizedresidue.cc.
{
    residue_sequence_number_ = residue_sequence_number;
}
The documentation for this class was generated from the following files:
includes/Resolver/PdbPreprocessor/pdbpreprocessorunrecognizedresidue.hpp
src/Resolver/PdbPreprocessor/pdbpreprocessorunrecognizedresidue.cc