gmmlNew: PdbPreprocessorSpace::PdbPreprocessorDisulfideBond Class Reference
PdbPreprocessorSpace::PdbPreprocessorDisulfideBond Class Reference
#include <pdbpreprocessordisulfidebond.hpp>
Public Member Functions
PdbPreprocessorDisulfideBond ()
PdbPreprocessorDisulfideBond (char chain_id_1, char chain_id_2, int residue_sequence_number_1, int residue_sequence_number_2, double distance, bool is_bonded, char residue_insertion_code_1, char residue_insertion_code_2, char residue_alternate_location_1, char residue_alternate_location_2)
char GetResidueChainId1 ()
char GetResidueChainId2 ()
int GetResidueSequenceNumber1 ()
int GetResidueSequenceNumber2 ()
double GetDistance ()
bool GetIsBonded ()
char GetResidueInsertionCode1 ()
char GetResidueInsertionCode2 ()
char GetResidueAlternateLocation1 ()
char GetResidueAlternateLocation2 ()
void SetResidueChainId1 (char residue_chain_id_1)
void SetResidueChainId2 (char residue_chain_id_2)
void SetResidueSequenceNumber1 (int residue_sequence_number_1)
void SetResidueSequenceNumber2 (int residue_sequence_number_2)
void SetDistance (double distance)
void SetIsBonded (bool is_bonded)
void SetResidueInsertionCode1 (char residue_insertion_code_1)
void SetResidueInsertionCode2 (char residue_insertion_code_2)
void SetResidueAlternateLocation1 (char residue_alternate_location_1)
void SetResidueAlternateLocation2 (char residue_alternate_location_2)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 9 of file pdbpreprocessordisulfidebond.hpp.
Constructor & Destructor Documentation
PdbPreprocessorDisulfideBond::PdbPreprocessorDisulfideBond ()
Definition at line 10 of file pdbpreprocessordisulfidebond.cc.
{}
PdbPreprocessorDisulfideBond::PdbPreprocessorDisulfideBond (char chain_id_1, char chain_id_2, int residue_sequence_number_1, int residue_sequence_number_2, double distance, bool is_bonded, char residue_insertion_code_1, char residue_insertion_code_2, char residue_alternate_location_1, char residue_alternate_location_2)
Definition at line 12 of file pdbpreprocessordisulfidebond.cc.
                                                                                                                                                                                                               :
    residue_chain_id_1_(residue_chain_id_1), residue_chain_id_2_(residue_chain_id_2), residue_sequence_number_1_(residue_sequence_number_1),
    residue_sequence_number_2_(residue_sequence_number_2), distance_(distance), is_bonded_(is_bonded), residue_insertion_code_1_(residue_insertion_code_1),
    residue_insertion_code_2_(residue_insertion_code_2), residue_alternate_location_1_(residue_alternate_location_1), residue_alternate_location_2_(residue_alternate_location_2) {}
Member Function Documentation
double PdbPreprocessorDisulfideBond::GetDistance ()
Definition at line 37 of file pdbpreprocessordisulfidebond.cc.
{
    return distance_;
}
bool PdbPreprocessorDisulfideBond::GetIsBonded ()
Definition at line 41 of file pdbpreprocessordisulfidebond.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber().
{
    return is_bonded_;
}
char PdbPreprocessorDisulfideBond::GetResidueAlternateLocation1 ()
Definition at line 53 of file pdbpreprocessordisulfidebond.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber().
{
    return residue_alternate_location_1_;
}
char PdbPreprocessorDisulfideBond::GetResidueAlternateLocation2 ()
Definition at line 57 of file pdbpreprocessordisulfidebond.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber().
{
    return residue_alternate_location_2_;
}
char PdbPreprocessorDisulfideBond::GetResidueChainId1 ()
Definition at line 21 of file pdbpreprocessordisulfidebond.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber().
{
    return residue_chain_id_1_;
}
char PdbPreprocessorDisulfideBond::GetResidueChainId2 ()
Definition at line 25 of file pdbpreprocessordisulfidebond.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber().
{
    return residue_chain_id_2_;
}
char PdbPreprocessorDisulfideBond::GetResidueInsertionCode1 ()
Definition at line 45 of file pdbpreprocessordisulfidebond.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber().
{
    return residue_insertion_code_1_;
}
char PdbPreprocessorDisulfideBond::GetResidueInsertionCode2 ()
Definition at line 49 of file pdbpreprocessordisulfidebond.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber().
{
    return residue_insertion_code_2_;
}
int PdbPreprocessorDisulfideBond::GetResidueSequenceNumber1 ()
Definition at line 29 of file pdbpreprocessordisulfidebond.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber().
{
    return residue_sequence_number_1_;
}
int PdbPreprocessorDisulfideBond::GetResidueSequenceNumber2 ()
Definition at line 33 of file pdbpreprocessordisulfidebond.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber().
{
    return residue_sequence_number_2_;
}
void PdbPreprocessorDisulfideBond::Print (std::ostream & out = std::cout)
Definition at line 109 of file pdbpreprocessordisulfidebond.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::Print().
{
    out << "[Chain id: " << residue_chain_id_1_
         << ", Sequence number: " << residue_sequence_number_1_
         << ", Insertion code: " << residue_insertion_code_1_
         << ", Alternate location: " << residue_alternate_location_1_
         << "]--[Chain id: " << residue_chain_id_2_
         << ", Sequence number: " << residue_sequence_number_2_
         << ", Insertion code: " << residue_insertion_code_2_
         << ", Alternate location: " << residue_alternate_location_2_
         << "] => Distance: " << distance_
         << endl;
}
void PdbPreprocessorDisulfideBond::SetDistance (double distance)
Definition at line 81 of file pdbpreprocessordisulfidebond.cc.
{
    distance_ = distance;
}
void PdbPreprocessorDisulfideBond::SetIsBonded (bool is_bonded)
Definition at line 85 of file pdbpreprocessordisulfidebond.cc.
{
    is_bonded_ = is_bonded;
}
void PdbPreprocessorDisulfideBond::SetResidueAlternateLocation1 (char residue_alternate_location_1)
Definition at line 97 of file pdbpreprocessordisulfidebond.cc.
{
    residue_alternate_location_1_ = residue_alternate_location_1;
}
void PdbPreprocessorDisulfideBond::SetResidueAlternateLocation2 (char residue_alternate_location_2)
Definition at line 101 of file pdbpreprocessordisulfidebond.cc.
{
    residue_alternate_location_2_ = residue_alternate_location_2;
}
void PdbPreprocessorDisulfideBond::SetResidueChainId1 (char residue_chain_id_1)
Definition at line 65 of file pdbpreprocessordisulfidebond.cc.
{
    residue_chain_id_1_ = residue_chain_id_1;
}
void PdbPreprocessorDisulfideBond::SetResidueChainId2 (char residue_chain_id_2)
Definition at line 69 of file pdbpreprocessordisulfidebond.cc.
{
    residue_chain_id_2_ = residue_chain_id_2;
}
void PdbPreprocessorDisulfideBond::SetResidueInsertionCode1 (char residue_insertion_code_1)
Definition at line 89 of file pdbpreprocessordisulfidebond.cc.
{
    residue_insertion_code_1_ = residue_insertion_code_1;
}
void PdbPreprocessorDisulfideBond::SetResidueInsertionCode2 (char residue_insertion_code_2)
Definition at line 93 of file pdbpreprocessordisulfidebond.cc.
{
    residue_insertion_code_2_ = residue_insertion_code_2;
}
void PdbPreprocessorDisulfideBond::SetResidueSequenceNumber1 (int residue_sequence_number_1)
Definition at line 73 of file pdbpreprocessordisulfidebond.cc.
{
    residue_sequence_number_1_ = residue_sequence_number_1;
}
void PdbPreprocessorDisulfideBond::SetResidueSequenceNumber2 (int residue_sequence_number_2)
Definition at line 77 of file pdbpreprocessordisulfidebond.cc.
{
    residue_sequence_number_2_ = residue_sequence_number_2;
}
The documentation for this class was generated from the following files:
includes/Resolver/PdbPreprocessor/pdbpreprocessordisulfidebond.hpp
src/Resolver/PdbPreprocessor/pdbpreprocessordisulfidebond.cc