gmmlNew: LibraryFileSpace::LibraryFileResidue Class Reference
LibraryFileSpace::LibraryFileResidue Class Reference
#include <libraryfileresidue.hpp>
Public Types
typedef std::map< int,
LibraryFileAtom * > AtomMap
Public Member Functions
LibraryFileResidue ()
LibraryFileResidue (std::string &name)
LibraryFileResidue (std::string &name, std::vector< LibraryFileAtom * > &atoms, int head_atom_index, int tail_atom_index, double box_angle=0, double box_length=0, double box_width=0, double box_height=0)
std::string GetName ()
AtomMap GetAtoms ()
Return a map of all atoms belonging to the residue mapped to their order of insertion into the residue.
LibraryFileAtom * GetAtomByIndex (int index)
Return an atom belonging to the residue by a given index number.
LibraryFileAtom * GetAtomByOrder (int order)
Return an atom belonging to the residue by a given order number.
double GetBoxAngle ()
Return the box angle of the residue.
double GetBoxLength ()
Return the box length of the residue.
double GetBoxWidth ()
Return the box width of the residue.
double GetBoxHeight ()
Return the box hight of the residue.
int GetHeadAtomIndex ()
Return the head atom index of the residue.
int GetTailAtomIndex ()
Return the tail atom index of the residue.
LibraryFileAtom * GetLibraryAtomByAtomName (std::string atom_name)
void SetName (std::string name)
void SetAtoms (AtomMap &atoms)
Set the atom map belonging to the residue mapped to their insertion order.
void AddAtom (LibraryFileAtom *atom)
Add a new atom to map of the residue.
void SetBoxAngle (double box_angle)
Set the box angle of the residue.
void SetBoxLength (double box_length)
Set the box length of the residue.
void SetBoxWidth (double box_width)
Set the box width of the residue.
void SetBoxHeight (double box_height)
Set the box height of the residue.
void SetHeadAtomIndex (int head_atom_index)
Set the head atom index of the residue.
void SetTailAtomIndex (int tail_atom_index)
Set the tail atom index of the residue.
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 12 of file libraryfileresidue.hpp.
Member Typedef Documentation
typedef std::map<int, LibraryFileAtom*> LibraryFileSpace::LibraryFileResidue::AtomMap
Definition at line 21 of file libraryfileresidue.hpp.
Constructor & Destructor Documentation
LibraryFileResidue::LibraryFileResidue ()
Definition at line 14 of file libraryfileresidue.cc.
                                       : name_(""), atoms_(), box_angle_(0.0), box_length_(0.0), box_width_(0.0), box_height_(0.0),
    head_atom_index_(-1), tail_atom_index_(-1) {}
LibraryFileSpace::LibraryFileResidue::LibraryFileResidue (std::string & name)
LibraryFileSpace::LibraryFileResidue::LibraryFileResidue (std::string & name, std::vector< LibraryFileAtom * > & atoms, int head_atom_index, int tail_atom_index, double box_angle = 0, double box_length = 0, double box_width = 0, double box_height = 0)
Member Function Documentation
void LibraryFileResidue::AddAtom (LibraryFileAtom * atom)
Add a new atom to map of the residue.
Definition at line 130 of file libraryfileresidue.cc.
References LibraryFileSpace::LibraryFileAtom::GetAtomOrder().
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly().
{
    atoms_[atom->GetAtomOrder()] = atom;
}
LibraryFileAtom * LibraryFileResidue::GetAtomByIndex (int index)
Return an atom belonging to the residue by a given index number.
Definition at line 48 of file libraryfileresidue.cc.
Referenced by MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), and MolecularModeling::Assembly::BuildStructureByLIBFileInformation().
{
    return atoms_[index];
}
LibraryFileAtom * LibraryFileResidue::GetAtomByOrder (int order)
Return an atom belonging to the residue by a given order number.
Definition at line 54 of file libraryfileresidue.cc.
Referenced by LibraryFileSpace::LibraryFile::ResolveAtomSection(), LibraryFileSpace::LibraryFile::ResolveConnectivitySection(), and LibraryFileSpace::LibraryFile::ResolvePositionSection().
{
    for(LibraryFileResidue::AtomMap::iterator it = atoms_.begin(); it != atoms_.end(); it++)
    {
        if(it->second->GetAtomOrder() == order)
            return it->second;
    }
    return NULL;
}
LibraryFileResidue::AtomMap LibraryFileResidue::GetAtoms ()
Return a map of all atoms belonging to the residue mapped to their order of insertion into the residue.
Definition at line 42 of file libraryfileresidue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), LibraryFileSpace::LibraryFile::GetAllAtomNamesOfResidue(), PdbPreprocessorSpace::PdbPreprocessor::GetAllAtomNamesOfResidueNamesFromMultipleLibFiles(), LibraryFileSpace::LibraryFile::ResolveAtomSection(), LibraryFileSpace::LibraryFile::ResolveConnectivitySection(), LibraryFileSpace::LibraryFile::ResolvePositionSection(), PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains(), PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChainsWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    return atoms_;
}
double LibraryFileResidue::GetBoxAngle ()
Return the box angle of the residue.
Definition at line 65 of file libraryfileresidue.cc.
Referenced by LibraryFileSpace::LibraryFile::ResolveBoundBoxSection().
{
    return box_angle_;
}
double LibraryFileResidue::GetBoxHeight ()
Return the box hight of the residue.
Definition at line 83 of file libraryfileresidue.cc.
Referenced by LibraryFileSpace::LibraryFile::ResolveBoundBoxSection().
{
    return box_height_;
}
double LibraryFileResidue::GetBoxLength ()
Return the box length of the residue.
Definition at line 71 of file libraryfileresidue.cc.
Referenced by LibraryFileSpace::LibraryFile::ResolveBoundBoxSection().
{
    return box_length_;
}
double LibraryFileResidue::GetBoxWidth ()
Return the box width of the residue.
Definition at line 77 of file libraryfileresidue.cc.
Referenced by LibraryFileSpace::LibraryFile::ResolveBoundBoxSection().
{
    return box_width_;
}
int LibraryFileResidue::GetHeadAtomIndex ()
Return the head atom index of the residue.
Definition at line 89 of file libraryfileresidue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), and LibraryFileSpace::LibraryFile::ResolveConnectSection().
{
    return head_atom_index_;
}
LibraryFileAtom * LibraryFileResidue::GetLibraryAtomByAtomName (std::string atom_name)
Definition at line 99 of file libraryfileresidue.cc.
References LibraryFileSpace::LibraryFileAtom::GetName().
Referenced by MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), and MolecularModeling::Assembly::BuildStructureByLIBFileInformation().
{
    for(LibraryFileResidue::AtomMap::iterator it = atoms_.begin(); it != atoms_.end(); it++)
    {
        LibraryFileAtom* atom = (*it).second;
        if(atom->GetName().compare(atom_name) == 0)
            return atom;
    }
    return NULL;
}
std::string LibraryFileResidue::GetName ()
Return the residue name
Definition at line 36 of file libraryfileresidue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), LibraryFileSpace::LibraryFile::BuildLibraryFile(), MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly(), MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), MolecularModeling::Assembly::BuildStructureByLIBFileInformation(), LibraryFileSpace::LibraryFile::ResolveAtomPertInfoSection(), LibraryFileSpace::LibraryFile::ResolveAtomSection(), LibraryFileSpace::LibraryFile::ResolveBoundBoxSection(), LibraryFileSpace::LibraryFile::ResolveChildSequenceSection(), LibraryFileSpace::LibraryFile::ResolveConnectivitySection(), LibraryFileSpace::LibraryFile::ResolveConnectSection(), LibraryFileSpace::LibraryFile::ResolveHierarchySection(), LibraryFileSpace::LibraryFile::ResolveNameSection(), LibraryFileSpace::LibraryFile::ResolvePositionSection(), LibraryFileSpace::LibraryFile::ResolveResidueConnectSection(), LibraryFileSpace::LibraryFile::ResolveResiduePdbSequenceNumberSection(), LibraryFileSpace::LibraryFile::ResolveResiduesSection(), LibraryFileSpace::LibraryFile::ResolveSolventCapSection(), and LibraryFileSpace::LibraryFile::ResolveVelocitiesSection().
{
    return name_;
}
int LibraryFileResidue::GetTailAtomIndex ()
Return the tail atom index of the residue.
Definition at line 95 of file libraryfileresidue.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), and LibraryFileSpace::LibraryFile::ResolveConnectSection().
{
    return tail_atom_index_;
}
void LibraryFileResidue::Print (std::ostream & out = std::cout)
Definition at line 174 of file libraryfileresidue.cc.
References gmml::dNotSet.
{
    out << setw(80) << "***************************** " + name_ + " *****************************" << endl;
    out << setw(60) << "======================== ATOMS ========================" << endl;
    out << setw(2) << "#"
        << setw(6) << "NAME"
        << setw(6) << "TYPE"
        << setw(6) << "RES_I"
        << setw(6) << "ATM_I"
        << setw(10) << "CHG"
        << setw(45) << "CRD"
        << setw(20) << "BND_ATMS"
        << endl;
    for(LibraryFileResidue::AtomMap::iterator it = atoms_.begin(); it != atoms_.end(); it++)
    {
        it->second->Print(out);
        for(unsigned int j = 0; j < it->second->GetBondedAtomsIndices().size(); j++)
            out << setw(4) << it -> second -> GetBondedAtomsIndices()[j] << ", ";
        out << endl;
    }
    out << endl << setw(60) << "======================= Bound Box =======================" << endl;
    out << setw(6) << "ANGL"
        << setw(6) << "LEN"
        << setw(6) << "WDTH"
        << setw(6) << "HGHT"
        << endl;
    if(box_angle_ == dNotSet)
        out << setw(6) << "--";
    else
        out << setw(6) << box_angle_;
    if(box_length_ == dNotSet)
        out << setw(6) << "--";
    else
        out << setw(6) << box_length_;
    if(box_width_ == dNotSet)
        out << setw(6) << "--";
    else
        out << setw(6) << box_width_;
    if(box_height_ == dNotSet)
        out << setw(6) << "--";
    else
        out << setw(6) << box_height_;
    out << endl;
    out << "HEAD ATOM INDEX: " << head_atom_index_ << endl;
    out << "TAIL ATOM INDEX: " << tail_atom_index_ << endl;
}
void LibraryFileResidue::SetAtoms (LibraryFileResidue::AtomMap & atoms)
Set the atom map belonging to the residue mapped to their insertion order.
Definition at line 120 of file libraryfileresidue.cc.
{
    atoms_.clear();
    for(LibraryFileResidue::AtomMap::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        atoms_[it->second->GetAtomOrder()] = it->second;
    }
}
void LibraryFileResidue::SetBoxAngle (double box_angle)
Set the box angle of the residue.
Definition at line 136 of file libraryfileresidue.cc.
{
    box_angle_ = box_angle;
}
void LibraryFileResidue::SetBoxHeight (double box_height)
Set the box height of the residue.
Definition at line 154 of file libraryfileresidue.cc.
{
    box_height_ = box_height;
}
void LibraryFileResidue::SetBoxLength (double box_length)
Set the box length of the residue.
Definition at line 142 of file libraryfileresidue.cc.
{
    box_length_ = box_length;
}
void LibraryFileResidue::SetBoxWidth (double box_width)
Set the box width of the residue.
Definition at line 148 of file libraryfileresidue.cc.
{
    box_width_ = box_width;
}
void LibraryFileResidue::SetHeadAtomIndex (int head_atom_index)
Set the head atom index of the residue.
Definition at line 160 of file libraryfileresidue.cc.
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly().
{
    head_atom_index_ = head_atom_index;
}
void LibraryFileResidue::SetName (std::string name)
Set the residue name
Definition at line 114 of file libraryfileresidue.cc.
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly().
{
    name_ = name;
}
void LibraryFileResidue::SetTailAtomIndex (int tail_atom_index)
Set the tail atom index of the residue.
Definition at line 166 of file libraryfileresidue.cc.
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly().
{
    tail_atom_index_ = tail_atom_index;
}
The documentation for this class was generated from the following files:
includes/ParameterSet/LibraryFileSpace/libraryfileresidue.hpp
src/ParameterSet/LibraryFileSpace/libraryfileresidue.cc