gmmlNew: PdbFileSpace::PdbResidueSequence Class Reference
PdbFileSpace::PdbResidueSequence Class Reference
#include <pdbresiduesequence.hpp>
Public Member Functions
PdbResidueSequence ()
PdbResidueSequence (char chain_id, int number_of_residues, const std::vector< std::string > &residue_names)
PdbResidueSequence (std::stringstream &specification_block)
char GetChainId ()
int GetNumberOfResidues ()
std::vector< std::string > GetResidueNames ()
void SetChainId (char chain_id)
void SetNumberOfResidues (int number_of_residues)
void SetResidueNames (const std::vector< std::string > residue_names)
void AddResidueName (const std::string residue_name)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 13 of file pdbresiduesequence.hpp.
Constructor & Destructor Documentation
PdbResidueSequence::PdbResidueSequence ()
Definition at line 14 of file pdbresiduesequence.cc.
: chain_id_(' '), number_of_residues_(dNotSet) {}
PdbFileSpace::PdbResidueSequence::PdbResidueSequence (char chain_id, int number_of_residues, const std::vector< std::string > & residue_names)
PdbFileSpace::PdbResidueSequence::PdbResidueSequence (std::stringstream & specification_block)
Member Function Documentation
void PdbResidueSequence::AddResidueName (const std::string residue_name)
Definition at line 101 of file pdbresiduesequence.cc.
{
    residue_names_.push_back(residue_name);
}
char PdbResidueSequence::GetChainId ()
Definition at line 64 of file pdbresiduesequence.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSequenceResidueCard().
{
    return chain_id_;
}
int PdbResidueSequence::GetNumberOfResidues ()
Definition at line 69 of file pdbresiduesequence.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSequenceResidueCard().
{
    return number_of_residues_;
}
vector< string > PdbResidueSequence::GetResidueNames ()
Definition at line 74 of file pdbresiduesequence.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSequenceResidueCard().
{
    return residue_names_;
}
void PdbResidueSequence::Print (std::ostream & out = std::cout)
Definition at line 113 of file pdbresiduesequence.cc.
References gmml::iNotSet.
{
    out << "Chain ID: " << chain_id_
        << ", " << "Number of Residues: ";
    if(number_of_residues_ != iNotSet)
        out << number_of_residues_;
    else
        out << " ";
    out << "Residue Names: ";
    for(vector<string>::iterator it = residue_names_.begin(); it != residue_names_.end(); it++)
    {
        out << (*it) << ", ";
    }
    out << endl;
}
void PdbResidueSequence::SetChainId (char chain_id)
Definition at line 82 of file pdbresiduesequence.cc.
{
    chain_id_ = chain_id;
}
void PdbResidueSequence::SetNumberOfResidues (int number_of_residues)
Definition at line 87 of file pdbresiduesequence.cc.
{
    number_of_residues_ = number_of_residues;
}
void PdbResidueSequence::SetResidueNames (const std::vector< std::string > residue_names)
Definition at line 92 of file pdbresiduesequence.cc.
{
    residue_names_.clear();
    for(vector<string>::const_iterator it = residue_names.begin(); it != residue_names.end(); it++)
    {
        residue_names_.push_back(*it);
    }
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbresiduesequence.hpp
src/FileSet/PdbFileSpace/pdbresiduesequence.cc