gmmlNew: ParameterFileSpace::ParameterFileBond Class Reference
ParameterFileSpace::ParameterFileBond Class Reference
#include <parameterfilebond.hpp>
Public Member Functions
ParameterFileBond ()
ParameterFileBond (const std::vector< std::string > &types, double force_constant, double length, const std::string &dscr="")
ParameterFileBond (const std::vector< std::string > &types, double force_constant, double length, const std::vector< double > &hbond_coefficients, const std::string &dscr="")
std::vector< std::string > GetTypes ()
double GetForceConstant ()
Return force constant.
double GetLength ()
Return angle.
std::string GetDscr ()
Return dscr.
std::vector< double > GetHbondCoefficients ()
Return hbonded_coefficients.
void SetTypes (const std::vector< std::string > types)
void SetForceConstant (double force_constant)
Set force constant.
void SetLength (double length)
Set angle.
void SetDscr (const std::string dscr)
Set dscr.
void SetHbondCoefficients (std::vector< double > hbond_coefficients)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 10 of file parameterfilebond.hpp.
Constructor & Destructor Documentation
ParameterFileBond::ParameterFileBond ()
Definition at line 13 of file parameterfilebond.cc.
    : types_(), force_constant_(dNotSet), length_(dNotSet), dscr_("") {}
ParameterFileBond::ParameterFileBond (const std::vector< std::string > & types, double force_constant, double length, const std::string & dscr = "")
Definition at line 16 of file parameterfilebond.cc.
    : types_(types), force_constant_(force_constant), length_(length), dscr_(dscr) {}
ParameterFileBond::ParameterFileBond (const std::vector< std::string > & types, double force_constant, double length, const std::vector< double > & hbond_coefficients, const std::string & dscr = "")
Definition at line 19 of file parameterfilebond.cc.
    : types_(types), force_constant_(force_constant), length_(length), dscr_(dscr), hbond_coefficients_(hbond_coefficients) {}
Member Function Documentation
std::string ParameterFileBond::GetDscr ()
Return dscr.
Definition at line 45 of file parameterfilebond.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveBondSection().
{
    return dscr_;
}
double ParameterFileBond::GetForceConstant ()
Return force constant.
Definition at line 33 of file parameterfilebond.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveBondSection().
{
    return force_constant_;
}
std::vector< double > ParameterFileBond::GetHbondCoefficients ()
Return hbonded_coefficients.
Definition at line 51 of file parameterfilebond.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveHydrogenBondSection().
{
    return hbond_coefficients_;
}
double ParameterFileBond::GetLength ()
Return angle.
Definition at line 39 of file parameterfilebond.cc.
Referenced by ParameterFileSpace::ParameterFile::ResolveBondSection().
{
    return length_;
}
std::vector< std::string > ParameterFileBond::GetTypes ()
Return the list of atom types involved in the current bond object
Definition at line 27 of file parameterfilebond.cc.
{
    return types_;
}
void ParameterFileBond::Print (std::ostream & out = std::cout)
Definition at line 96 of file parameterfilebond.cc.
References gmml::dNotSet.
{
    for(std::vector<std::string>::iterator it = types_.begin(); it != types_.end(); it++)
    {
        if(it != types_.end() - 1)
        {
            out << std::setw(4) << (*it)
                << std::setw(2) << "-";
        }
        else
            out << std::setw(4) << (*it);
    }
    if(force_constant_ == dNotSet)
        out << std::setw(15) << "--";
    else
        out << std::setw(15) << force_constant_;
    if(length_ == dNotSet)
        out << std::setw(10) << "--";
    else
        out << std::setw(10) << length_;
    out << std::setw(60) << dscr_
        << std::endl;
}
void ParameterFileBond::SetDscr (const std::string dscr)
Set dscr.
Definition at line 81 of file parameterfilebond.cc.
{
    dscr_ = dscr;
}
void ParameterFileBond::SetForceConstant (double force_constant)
Set force constant.
Definition at line 70 of file parameterfilebond.cc.
{
    force_constant_ = force_constant;
}
void ParameterFileBond::SetHbondCoefficients (std::vector< double > hbond_coefficients)
Definition at line 85 of file parameterfilebond.cc.
{
    hbond_coefficients_.clear();
    for(std::vector<double>::iterator it = hbond_coefficients.begin(); it != hbond_coefficients.end(); it++)
    {
        hbond_coefficients_.push_back(*it);
    }
}
void ParameterFileBond::SetLength (double length)
Set angle.
Definition at line 76 of file parameterfilebond.cc.
{
    length_ = length;
}
void ParameterFileBond::SetTypes (const std::vector< std::string > types)
Set the list of atom types involved in the current bond object
Definition at line 60 of file parameterfilebond.cc.
{
    types_.clear();
    for(std::vector<std::string>::iterator it = types.begin(); it != types.end(); it++)
    {
        types_.push_back(*it);
    }
}
The documentation for this class was generated from the following files:
includes/ParameterSet/ParameterFileSpace/parameterfilebond.hpp
src/ParameterSet/ParameterFileSpace/parameterfilebond.cc