gmmlNew: PdbFileSpace::PdbModel Class Reference
PdbFileSpace::PdbModel Class Reference
#include <pdbmodel.hpp>
Public Member Functions
PdbModel ()
PdbModel (std::stringstream &model_block)
int GetModelSerialNumber ()
PdbModelResidueSet * GetModelResidueSet ()
void SetModelSerialNumber (int model_serial_number)
void SetModelResidueSet (PdbModelResidueSet *model_residue_set)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 15 of file pdbmodel.hpp.
Constructor & Destructor Documentation
PdbModel::PdbModel ()
Definition at line 13 of file pdbmodel.cc.
{}
PdbFileSpace::PdbModel::PdbModel (std::stringstream & model_block)
Member Function Documentation
PdbModelResidueSet * PdbModel::GetModelResidueSet ()
Definition at line 61 of file pdbmodel.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbFileSpace::PdbFile::GetAllAtomsInOrder(), PdbFileSpace::PdbFile::GetAllAtomsOfResidue(), PdbFileSpace::PdbFile::GetAllAtomsOfResidues(), PdbFileSpace::PdbFile::GetAllResidueNames(), PdbFileSpace::PdbFile::GetAllResidueNamesFromAtomCard(), PdbFileSpace::PdbFile::GetAllResidues(), PdbFileSpace::PdbFile::GetAllResiduesFromAtomCard(), PdbFileSpace::PdbFile::GetAtomBySerialNumber(), PdbFileSpace::PdbFile::GetAtomOfResidueByAtomKey(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return model_residue_set_;
}
int PdbModel::GetModelSerialNumber ()
Definition at line 57 of file pdbmodel.cc.
Referenced by PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), and PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber().
{
    return model_serial_number_;
}
void PdbModel::Print (std::ostream & out = std::cout)
Definition at line 84 of file pdbmodel.cc.
References gmml::iNotSet, and PdbFileSpace::PdbModelResidueSet::Print().
{
    out << "Model Serial Number: ";
    if(model_serial_number_ != iNotSet)
        out << model_serial_number_;
    else
        out << " ";
    out << endl
        << "====================== Residue Set =====================" << endl;
    model_residue_set_->Print(out);
    out << endl;
}
void PdbModel::SetModelResidueSet (PdbModelResidueSet * model_residue_set)
Definition at line 73 of file pdbmodel.cc.
Referenced by MolecularModeling::Assembly::BuildPdbFileStructureFromAssembly(), PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    model_residue_set_ = model_residue_set;
}
void PdbModel::SetModelSerialNumber (int model_serial_number)
Definition at line 69 of file pdbmodel.cc.
Referenced by MolecularModeling::Assembly::BuildPdbFileStructureFromAssembly(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), and PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber().
{
    model_serial_number_ = model_serial_number;
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbmodel.hpp
src/FileSet/PdbFileSpace/pdbmodel.cc