gmmlNew: PdbFileSpace::PdbHeterogen Class Reference
PdbFileSpace::PdbHeterogen Class Reference
#include <pdbheterogen.hpp>
Public Member Functions
PdbHeterogen ()
PdbHeterogen (const std::string &heterogen_id, char chain_identifier, int sequence_number, char insertion_code, int number_of_heterogen_atoms, const std::string &dscr)
PdbHeterogen (std::stringstream &stream_block)
std::string GetHeterogenId ()
char GetChainId ()
int GetSequenceNumber ()
char GetInsertionCode ()
int GetNumberOfHeterogenAtoms ()
std::string GetDscr ()
void SetHeterogenId (const std::string heterogen_id)
void SetChainId (char chain_identifier)
void SetSequenceNumber (int sequence_number)
void SetInsertionCode (char insertion_code)
void SetNumberOfHeterogenAtoms (int number_of_heterogen_atoms)
void SetDscr (const std::string dscr)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 12 of file pdbheterogen.hpp.
Constructor & Destructor Documentation
PdbHeterogen::PdbHeterogen ()
Definition at line 15 of file pdbheterogen.cc.
                           : heterogen_id_(""), chain_identifier_(' '), sequence_number_(dNotSet), insertion_code_(' '),
    number_of_heterogen_atoms_(dNotSet), dscr_("") {}
PdbFileSpace::PdbHeterogen::PdbHeterogen (const std::string & heterogen_id, char chain_identifier, int sequence_number, char insertion_code, int number_of_heterogen_atoms, const std::string & dscr)
PdbFileSpace::PdbHeterogen::PdbHeterogen (std::stringstream & stream_block)
Member Function Documentation
char PdbHeterogen::GetChainId ()
Definition at line 70 of file pdbheterogen.cc.
Referenced by PdbFileSpace::PdbFile::ResolveHeterogenCard().
{
    return chain_identifier_;
}
string PdbHeterogen::GetDscr ()
Definition at line 90 of file pdbheterogen.cc.
Referenced by PdbFileSpace::PdbFile::ResolveHeterogenCard().
{
    return dscr_;
}
string PdbHeterogen::GetHeterogenId ()
Definition at line 65 of file pdbheterogen.cc.
Referenced by PdbFileSpace::PdbFile::ResolveHeterogenCard().
{
    return heterogen_id_;
}
char PdbHeterogen::GetInsertionCode ()
Definition at line 80 of file pdbheterogen.cc.
Referenced by PdbFileSpace::PdbFile::ResolveHeterogenCard().
{
    return insertion_code_;
}
int PdbHeterogen::GetNumberOfHeterogenAtoms ()
Definition at line 85 of file pdbheterogen.cc.
Referenced by PdbFileSpace::PdbFile::ResolveHeterogenCard().
{
    return number_of_heterogen_atoms_;
}
int PdbHeterogen::GetSequenceNumber ()
Definition at line 75 of file pdbheterogen.cc.
Referenced by PdbFileSpace::PdbFile::ResolveHeterogenCard().
{
    return sequence_number_;
}
void PdbHeterogen::Print (std::ostream & out = std::cout)
Definition at line 135 of file pdbheterogen.cc.
References gmml::iNotSet.
{
    out << "Heterogen ID: " << heterogen_id_
        << ", Chain Identifier: " << chain_identifier_
        << ", Sequence Number: ";
    if(sequence_number_ != iNotSet)
        out << sequence_number_;
    else
        out << " ";
    out << ", Insertion Code: " << insertion_code_
        << ", Number of Heterogen Atoms: ";
    if(number_of_heterogen_atoms_ != iNotSet)
        out << number_of_heterogen_atoms_;
    else
        out << " ";
    out << ", Description: " << dscr_ << endl;
}
void PdbHeterogen::SetChainId (char chain_identifier)
Definition at line 103 of file pdbheterogen.cc.
{
    chain_identifier_ = chain_identifier;
}
void PdbHeterogen::SetDscr (const std::string dscr)
Definition at line 123 of file pdbheterogen.cc.
{
    dscr_ = dscr;
}
void PdbHeterogen::SetHeterogenId (const std::string heterogen_id)
Definition at line 98 of file pdbheterogen.cc.
{
    heterogen_id_ = heterogen_id;
}
void PdbHeterogen::SetInsertionCode (char insertion_code)
Definition at line 113 of file pdbheterogen.cc.
{
    insertion_code_ = insertion_code;
}
void PdbHeterogen::SetNumberOfHeterogenAtoms (int number_of_heterogen_atoms)
Definition at line 118 of file pdbheterogen.cc.
{
    number_of_heterogen_atoms_ = number_of_heterogen_atoms;
}
void PdbHeterogen::SetSequenceNumber (int sequence_number)
Definition at line 108 of file pdbheterogen.cc.
{
    sequence_number_ = sequence_number;
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbheterogen.hpp
src/FileSet/PdbFileSpace/pdbheterogen.cc