gmmlNew: PdbFileSpace::PdbSheetStrand Class Reference
PdbFileSpace::PdbSheetStrand Class Reference
#include <pdbsheetstrand.hpp>
Public Types
typedef std::vector
< PdbSheetStrandResidue * > SheetStrandResidueVector
Public Member Functions
PdbSheetStrand ()
PdbSheetStrand (const SheetStrandResidueVector strand_residues, PdbSheetStrandSense sense, const std::string &current_atom, const std::string &previous_atom)
PdbSheetStrand (std::string &line)
SheetStrandResidueVector GetStrandResidues ()
PdbSheetStrandSense GetSense ()
std::string GetCurrentAtom ()
std::string GetPreviousAtom ()
void SetStrandResidues (const SheetStrandResidueVector strand_residues)
void AddStrandResidue (PdbSheetStrandResidue *strand_residue)
void SetSense (PdbSheetStrandSense sense)
void SetCurrentAtom (const std::string current_atom)
void SetPreviousAtom (const std::string previous_atom)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 25 of file pdbsheetstrand.hpp.
Member Typedef Documentation
typedef std::vector<PdbSheetStrandResidue*> PdbFileSpace::PdbSheetStrand::SheetStrandResidueVector
Definition at line 31 of file pdbsheetstrand.hpp.
Constructor & Destructor Documentation
PdbSheetStrand::PdbSheetStrand ()
Definition at line 15 of file pdbsheetstrand.cc.
: sense_(FIRST_STRAND), current_atom_(""), previous_atom_("") {}
PdbFileSpace::PdbSheetStrand::PdbSheetStrand (const SheetStrandResidueVector strand_residues, PdbSheetStrandSense sense, const std::string & current_atom, const std::string & previous_atom)
PdbFileSpace::PdbSheetStrand::PdbSheetStrand (std::string & line)
Member Function Documentation
void PdbSheetStrand::AddStrandResidue (PdbSheetStrandResidue * strand_residue)
Definition at line 165 of file pdbsheetstrand.cc.
{
    strand_residues_.push_back(strand_residue);
}
string PdbSheetStrand::GetCurrentAtom ()
Definition at line 143 of file pdbsheetstrand.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSheetCard().
{
    return current_atom_;
}
string PdbSheetStrand::GetPreviousAtom ()
Definition at line 148 of file pdbsheetstrand.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSheetCard().
{
    return previous_atom_;
}
PdbSheetStrandSense PdbSheetStrand::GetSense ()
Definition at line 138 of file pdbsheetstrand.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSheetCard().
{
    return sense_;
}
PdbSheetStrand::SheetStrandResidueVector PdbSheetStrand::GetStrandResidues ()
Definition at line 133 of file pdbsheetstrand.cc.
Referenced by PdbFileSpace::PdbFile::ResolveSheetCard().
{
    return strand_residues_;
}
void PdbSheetStrand::Print (std::ostream & out = std::cout)
Definition at line 192 of file pdbsheetstrand.cc.
References PdbFileSpace::UnknownStrand.
{
    out << "Strand Residues: " << endl;
    for(PdbSheetStrand::SheetStrandResidueVector::iterator it = strand_residues_.begin(); it != strand_residues_.end(); it++)
    {
        (*it)->Print(out);
        out << endl;
    }
    out << "Sense: ";
    if(sense_ != UnknownStrand)
        out << sense_;
    else
        out << " ";
    out << ", Current Atom: " << current_atom_
        << ", Previous Atom: " << previous_atom_
        << endl << endl;
}
void PdbSheetStrand::SetCurrentAtom (const std::string current_atom)
Definition at line 175 of file pdbsheetstrand.cc.
{
    current_atom_ = current_atom;
}
void PdbSheetStrand::SetPreviousAtom (const std::string previous_atom)
Definition at line 180 of file pdbsheetstrand.cc.
{
    previous_atom_ = previous_atom;
}
void PdbSheetStrand::SetSense (PdbSheetStrandSense sense)
Definition at line 170 of file pdbsheetstrand.cc.
{
    sense_ = sense;
}
void PdbSheetStrand::SetStrandResidues (const SheetStrandResidueVector strand_residues)
Definition at line 156 of file pdbsheetstrand.cc.
{
    strand_residues_.clear();
    for(PdbSheetStrand::SheetStrandResidueVector::const_iterator it = strand_residues.begin(); it != strand_residues.end(); it++)
    {
        strand_residues_.push_back(*it);
    }
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbsheetstrand.hpp
src/FileSet/PdbFileSpace/pdbsheetstrand.cc