gmmlNew: TopologyFileSpace::TopologyAtomPair Class Reference
TopologyFileSpace::TopologyAtomPair Class Reference
#include <topologyatompair.hpp>
Public Types
typedef std::map< std::string,
double > TopologyCoefficientMap
Public Member Functions
TopologyAtomPair ()
TopologyAtomPair (std::string pair_type, double coefficient_a, double coefficient_b, int index)
std::string GetPairType ()
double GetCoefficientA ()
double GetCoefficientB ()
int GetIndex ()
void SetPairType (std::string pair_type)
void SetCoefficientA (double coefficient_a)
void SetCoefficientB (double coefficient_b)
void SetIndex (int index)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 10 of file topologyatompair.hpp.
Member Typedef Documentation
typedef std::map<std::string, double> TopologyFileSpace::TopologyAtomPair::TopologyCoefficientMap
Definition at line 19 of file topologyatompair.hpp.
Constructor & Destructor Documentation
TopologyAtomPair::TopologyAtomPair ()
Definition at line 10 of file topologyatompair.cc.
{}
TopologyFileSpace::TopologyAtomPair::TopologyAtomPair (std::string pair_type, double coefficient_a, double coefficient_b, int index)
Member Function Documentation
double TopologyAtomPair::GetCoefficientA ()
Definition at line 22 of file topologyatompair.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveLennardJonesACoefSection().
{
    return coefficient_a_;
}
double TopologyAtomPair::GetCoefficientB ()
Definition at line 26 of file topologyatompair.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveLennardJonesBCoefSection().
{
    return coefficient_b_;
}
int TopologyAtomPair::GetIndex ()
Definition at line 30 of file topologyatompair.cc.
Referenced by TopologyFileSpace::TopologyFile::GetAtomPairByIndex().
{
    return index_;
}
string TopologyAtomPair::GetPairType ()
Definition at line 18 of file topologyatompair.cc.
Referenced by TopologyFileSpace::TopologyFile::AddAtomPair().
{
    return pair_type_;
}
void TopologyAtomPair::Print (std::ostream & out = std::cout)
Definition at line 62 of file topologyatompair.cc.
Referenced by TopologyFileSpace::TopologyFile::Print().
{
    out << pair_type_ << ": a = " << coefficient_a_ << "; b = " << coefficient_b_ << endl;
}
void TopologyAtomPair::SetCoefficientA (double coefficient_a)
Definition at line 42 of file topologyatompair.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    coefficient_a_ = coefficient_a;
}
void TopologyAtomPair::SetCoefficientB (double coefficient_b)
Definition at line 46 of file topologyatompair.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    coefficient_b_ = coefficient_b;
}
void TopologyAtomPair::SetIndex (int index)
Definition at line 50 of file topologyatompair.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    index_ = index;
}
void TopologyAtomPair::SetPairType (std::string pair_type)
Definition at line 38 of file topologyatompair.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    pair_type_ = pair_type;
}
The documentation for this class was generated from the following files:
includes/FileSet/TopologyFileSpace/topologyatompair.hpp
src/FileSet/TopologyFileSpace/topologyatompair.cc