gmmlNew: PdbFileSpace::PdbFile Class Reference
PdbFileSpace::PdbFile Class Reference
#include <pdbfile.hpp>
Public Types
typedef std::vector< PdbResidue * > PdbResidueVector
typedef std::vector< PdbAtom * > PdbAtomVector
typedef std::map< std::string,
PdbAtomVector * > PdbResidueAtomsMap
typedef std::map< int, int > PdbSerialNumberMapping
typedef std::map< int, int > PdbSequenceNumberMapping
typedef std::vector< std::pair
< char, int > > PdbPairVectorTerCardPositions
typedef std::vector< std::pair
< std::string, std::string > > PdbPairVectorAtomNamePositionFlag
Public Member Functions
PdbFile ()
PdbFile (const std::string &pdb_file)
std::string GetPath ()
PdbHeaderCard * GetHeader ()
PdbTitleCard * GetTitle ()
PdbCompoundCard * GetCompound ()
PdbNumModelCard * GetNumberOfModels ()
PdbModelTypeCard * GetModelType ()
PdbResidueSequenceCard * GetResiduesSequence ()
PdbResidueModificationCard * GetResidueModification ()
PdbHeterogenCard * GetHeterogens ()
PdbHeterogenNameCard * GetHeterogensName ()
PdbHeterogenSynonymCard * GetHeterogenSynonyms ()
PdbFormulaCard * GetFormulas ()
PdbHelixCard * GetHelixes ()
PdbSheetCard * GetSheets ()
PdbDisulfideBondCard * GetDisulfideBonds ()
PdbLinkCard * GetLinks ()
PdbSiteCard * GetSites ()
PdbCrystallographicCard * GetCrystallography ()
PdbOriginXnCard * GetOrigins ()
PdbScaleNCard * GetScales ()
PdbMatrixNCard * GetMatrices ()
PdbModelCard * GetModels ()
PdbConnectCard * GetConnectivities ()
PdbSerialNumberMapping GetSerialNumberMapping ()
PdbSequenceNumberMapping GetSequenceNumberMapping ()
PdbPairVectorAtomNamePositionFlag GetAllResidueNames ()
PdbPairVectorAtomNamePositionFlag GetAllResidueNamesFromAtomCard ()
PdbResidueVector GetAllResidues ()
PdbResidueVector GetAllResiduesFromAtomCard ()
PdbAtomVector GetAllAtomsOfResidue (PdbResidue *residue)
PdbResidueAtomsMap GetAllAtomsOfResidues ()
PdbResidueAtomsMap GetAllAtomsInOrder (std::vector< std::string > &key_order)
PdbAtom * GetAtomOfResidueByName (PdbResidue *residue, std::string atom_name, PdbResidueAtomsMap residue_atom_map)
PdbAtom * GetAtomOfResidueByName (PdbResidue *residue, std::string atom_name)
PdbAtom * GetAtomOfResidueByAtomKey (std::string atom_key)
PdbAtom * GetAtomBySerialNumber (int serial_number)
std::vector< std::string > GetAllAtomNamesOfResidue (PdbResidue *residue, PdbResidueAtomsMap residue_atom_map)
std::vector< std::string > GetAllAtomNamesOfResidue (PdbResidue *residue)
PdbPairVectorTerCardPositions GetAllTerCardPositions (std::vector< std::string > glycam_residue_names)
void SetPath (std::string pdb_path)
void SetHeader (PdbHeaderCard *header)
void SetTitle (PdbTitleCard *title)
void SetCompound (PdbCompoundCard *compound)
void SetNumberOfModels (PdbNumModelCard *number_of_models)
void SetModelType (PdbModelTypeCard *model_type)
void SetResiduesSequence (PdbResidueSequenceCard *residues_sequence)
void SetResidueModification (PdbResidueModificationCard *residue_modification)
void SetHeterogens (PdbHeterogenCard *heterogens)
void SetHeterogensName (PdbHeterogenNameCard *heterogens_name)
void SetHeterogenSynonyms (PdbHeterogenSynonymCard *heterogen_synonyms)
void SetFormulas (PdbFormulaCard *formulas)
void SetHelixes (PdbHelixCard *helixes)
void SetSheets (PdbSheetCard *sheets)
void SetDisulfideBonds (PdbDisulfideBondCard *disulfide_bonds)
void SetLinks (PdbLinkCard *links)
void SetSites (PdbSiteCard *sites)
void SetCrystallography (PdbCrystallographicCard *crystallography)
void SetOrigins (PdbOriginXnCard *origins)
void SetScales (PdbScaleNCard *scales)
void SetMatrices (PdbMatrixNCard *matrices)
void SetModels (PdbModelCard *models)
void SetConnectivities (PdbConnectCard *connectivities)
void SetSerialNumberMapping (PdbSerialNumberMapping serial_number_mapping)
void SetSequenceNumberMapping (PdbSequenceNumberMapping sequence_number_mapping)
void DeleteResidue (PdbResidue *residue)
void DeleteResidues (PdbResidueVector residues)
void DeleteResidueWithTheGivenModelNumber (PdbResidue *residue, int model_number=1)
void DeleteResiduesWithTheGivenModelNumber (PdbResidueVector residues, int model_number=1)
void DeleteAtom (PdbAtom *atom)
void DeleteAtoms (PdbAtomVector atoms)
void DeleteAtomWithTheGivenModelNumber (PdbAtom *atom, int model_number=1)
void DeleteAtomsWithTheGivenModelNumber (PdbAtomVector atoms, int model_number=1)
void UpdateResidueName (PdbResidue *residue, std::string residue_name)
void UpdateResidueNameWithTheGivenModelNumber (PdbResidue *residue, std::string residue_name, int model_number=1)
void InsertResidueBefore (PdbAtomCard *residue)
void InsertResidueBeforeWithTheGivenModelNumber (PdbAtomCard *residue, int model_number=1)
void InsertResidueAfter (PdbAtomCard *residue)
void InsertResidueAfterWithTheGivenModelNumber (PdbAtomCard *residue, int model_number=1)
void SplitAtomCardOfModelCard (char split_point_chain_id, int split_point_sequence_number)
void SplitAtomCardOfModelCardWithTheGivenModelNumber (char split_point_chain_id, int split_point_sequence_number, int model_number=1)
void UpdateConnectCard ()
bool Read (std::ifstream &in_file)
bool ParseCards (std::ifstream &in_stream)
bool ParseHeaderCard (std::ifstream &stream, std::string &line)
bool ParseObsoleteCard (std::ifstream &stream, std::string &line)
bool ParseTitleCard (std::ifstream &stream, std::string &line)
bool ParseSplitCard (std::ifstream &stream, std::string &line)
bool ParseCaveatCard (std::ifstream &stream, std::string &line)
bool ParseCompoundCard (std::ifstream &stream, std::string &line)
bool ParseSourceCard (std::ifstream &stream, std::string &line)
bool ParseKeywordCard (std::ifstream &stream, std::string &line)
bool ParseExpirationDateCard (std::ifstream &stream, std::string &line)
bool ParseNumModelCard (std::ifstream &stream, std::string &line)
bool ParseModelTypeCard (std::ifstream &stream, std::string &line)
bool ParseAuthorCard (std::ifstream &stream, std::string &line)
bool ParseRevisionDateCard (std::ifstream &stream, std::string &line)
bool ParseSupersededEntriesCard (std::ifstream &stream, std::string &line)
bool ParseJournalCard (std::ifstream &stream, std::string &line)
bool ParseRemarkCard (std::ifstream &stream, std::string &line)
bool ParseDatabaseReferenceCard (std::ifstream &stream, std::string &line)
bool ParseSequenceAdvancedCard (std::ifstream &stream, std::string &line)
bool ParseSequenceResidueCard (std::ifstream &stream, std::string &line)
bool ParseModificationResidueCard (std::ifstream &stream, std::string &line)
bool ParseHeterogenCard (std::ifstream &stream, std::string &line)
bool ParseHeterogenNameCard (std::ifstream &stream, std::string &line)
bool ParseHeterogenSynonymCard (std::ifstream &stream, std::string &line)
bool ParseFormulaCard (std::ifstream &stream, std::string &line)
bool ParseHelixCard (std::ifstream &stream, std::string &line)
bool ParseSheetCard (std::ifstream &stream, std::string &line)
bool ParseDisulfideBondCard (std::ifstream &stream, std::string &line)
bool ParseLinkCard (std::ifstream &stream, std::string &line)
bool ParseCISPeptideCard (std::ifstream &stream, std::string &line)
bool ParseSiteCard (std::ifstream &stream, std::string &line)
bool ParseCrystallographyCard (std::ifstream &stream, std::string &line)
bool ParseOriginCard (std::ifstream &stream, std::string &line)
bool ParseScaleCard (std::ifstream &stream, std::string &line)
bool ParseMatrixCard (std::ifstream &stream, std::string &line)
bool ParseModelCard (std::ifstream &stream, std::string &line)
bool ParseConnectivityCard (std::ifstream &stream, std::string &line)
bool ParseMasterCard (std::ifstream &stream, std::string &line)
bool ParseEndCard (std::ifstream &stream, std::string &line)
void Write (const std::string &pdb_file)
void WriteWithTheGivenModelNumber (const std::string &pdb_file, int model_number=1)
void ResolveCards (std::ofstream &out_stream)
void ResolveCardsWithTheGivenModelNumber (std::ofstream &out_stream, int model_number=1)
void ResolveHeaderCard (std::ofstream &stream)
void ResolveObsoleteCard (std::ofstream &stream)
void ResolveTitleCard (std::ofstream &stream)
void ResolveSplitCard (std::ofstream &stream)
void ResolveCaveatCard (std::ofstream &stream)
void ResolveCompoundCard (std::ofstream &stream)
void ResolveSourceCard (std::ofstream &stream)
void ResolveKeywordCard (std::ofstream &stream)
void ResolveExpirationDateCard (std::ofstream &stream)
void ResolveNumModelCard (std::ofstream &stream)
void ResolveModelTypeCard (std::ofstream &stream)
void ResolveAuthorCard (std::ofstream &stream)
void ResolveRevisionDateCard (std::ofstream &stream)
void ResolveSupersededEntriesCard (std::ofstream &stream)
void ResolveJournalCard (std::ofstream &stream)
void ResolveRemarkCard (std::ofstream &stream)
void ResolveDatabaseReferenceCard (std::ofstream &stream)
void ResolveSequenceAdvancedCard (std::ofstream &stream)
void ResolveSequenceResidueCard (std::ofstream &stream)
void ResolveModificationResidueCard (std::ofstream &stream)
void ResolveHeterogenCard (std::ofstream &stream)
void ResolveHeterogenNameCard (std::ofstream &stream)
void ResolveHeterogenSynonymCard (std::ofstream &stream)
void ResolveFormulaCard (std::ofstream &stream)
void ResolveHelixCard (std::ofstream &stream)
void ResolveSheetCard (std::ofstream &stream)
void ResolveDisulfideBondCard (std::ofstream &stream)
void ResolveLinkCard (std::ofstream &stream)
void ResolveCISPeptideCard (std::ofstream &stream)
void ResolveSiteCard (std::ofstream &stream)
void ResolveCrystallographyCard (std::ofstream &stream)
void ResolveOriginCard (std::ofstream &stream)
void ResolveScaleCard (std::ofstream &stream)
void ResolveMatrixCard (std::ofstream &stream)
void ResolveModelCard (std::ofstream &stream)
void ResolveModelCardWithTheGivenModelNumber (std::ofstream &stream, int model_number=1)
void ResolveConnectivityCard (std::ofstream &stream)
void ResolveMasterCard (std::ofstream &stream)
void ResolveEndCard (std::ofstream &stream)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 38 of file pdbfile.hpp.
Member Typedef Documentation
typedef std::vector<PdbAtom*> PdbFileSpace::PdbFile::PdbAtomVector
Definition at line 51 of file pdbfile.hpp.
typedef std::vector<std::pair<std::string, std::string> > PdbFileSpace::PdbFile::PdbPairVectorAtomNamePositionFlag
Definition at line 66 of file pdbfile.hpp.
typedef std::vector<std::pair<char, int> > PdbFileSpace::PdbFile::PdbPairVectorTerCardPositions
Definition at line 65 of file pdbfile.hpp.
typedef std::map<std::string, PdbAtomVector* > PdbFileSpace::PdbFile::PdbResidueAtomsMap
Definition at line 55 of file pdbfile.hpp.
typedef std::vector<PdbResidue*> PdbFileSpace::PdbFile::PdbResidueVector
Definition at line 47 of file pdbfile.hpp.
typedef std::map<int, int> PdbFileSpace::PdbFile::PdbSequenceNumberMapping
Definition at line 63 of file pdbfile.hpp.
typedef std::map<int, int> PdbFileSpace::PdbFile::PdbSerialNumberMapping
Definition at line 59 of file pdbfile.hpp.
Constructor & Destructor Documentation
PdbFile::PdbFile ()
Definition at line 72 of file pdbfile.cc.
{
    path_ = "GMML-Generated";
    header_ = NULL;
    title_ = NULL;
    compound_ = NULL;
    number_of_models_ = NULL;
    model_type_ = NULL;
    residues_sequence_ = NULL;
    residue_modification_ = NULL;
    heterogens_ = NULL;
    heterogens_name_ = NULL;
    heterogen_synonyms_ = NULL;
    formulas_ = NULL;
    helixes_ = NULL;
    sheets_ = NULL;
    disulfide_bonds_ = NULL;
    links_ = NULL;
    sites_ = NULL;
    crystallography_ = NULL;
    origins_ = NULL;
    scales_ = NULL;
    matrices_ = NULL;
    models_ = NULL;
    connectivities_ = NULL;
    serial_number_mapping_ = PdbFile::PdbSerialNumberMapping();
    sequence_number_mapping_ = PdbFile::PdbSequenceNumberMapping();
}
PdbFile::PdbFile (const std::string & pdb_file)
Close the parameter files
Definition at line 101 of file pdbfile.cc.
References gmml::Trim().
{
    path_ = pdb_file;
    header_ = NULL;
    title_ = NULL;
    compound_ = NULL;
    number_of_models_ = NULL;
    model_type_ = NULL;
    residues_sequence_ = NULL;
    residue_modification_ = NULL;
    heterogens_ = NULL;
    heterogens_name_ = NULL;
    heterogen_synonyms_ = NULL;
    formulas_ = NULL;
    helixes_ = NULL;
    sheets_ = NULL;
    disulfide_bonds_ = NULL;
    links_ = NULL;
    sites_ = NULL;
    crystallography_ = NULL;
    origins_ = NULL;
    scales_ = NULL;
    matrices_ = NULL;
    models_ = NULL;
    connectivities_ = NULL;
    serial_number_mapping_ = PdbFile::PdbSerialNumberMapping();
    sequence_number_mapping_ = PdbFile::PdbSequenceNumberMapping();
    std::ifstream in_file;
    if(std::ifstream(pdb_file.c_str()))
    {
        cout << "Opening PDB file ..." << endl;
        in_file.open(pdb_file.c_str());
    }
    else
    {
        throw PdbFileProcessingException(__LINE__, "PDB file not found");
    }
    string line = "";
    string temp = "";
    stringstream ss;
    while(!in_file.eof())
    {
        if(!getline(in_file, line))
            break;
        else
        {
            temp = line.substr(0,6);
            temp = Trim(temp);
            if(temp.find("END") != string::npos || temp.compare("END") == 0)
                break;
            else if(!line.empty())
                ss << line << endl;
        }
    }
    in_file.close();
    if(temp.find("END") == string::npos || temp.compare("END") != 0)
    {
        std::ofstream out_file;
        out_file.open(pdb_file.c_str());
        out_file << ss.str() << "END";
        out_file.close();
    }
    else
    {
        std::ofstream out_file;
        out_file.open(pdb_file.c_str());
        out_file << ss.str() << temp;
        out_file.close();
    }
    in_file.open(pdb_file.c_str());
    if(!Read(in_file))
    {
        throw PdbFileProcessingException(__LINE__, "Reading PDB file exception");
    }
    in_file.close();            /// Close the parameter files
}
Member Function Documentation
void PdbFile::DeleteAtom (PdbAtom * atom)
Definition at line 1371 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomName(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbAtom::SetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::SetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), and PdbFileSpace::PdbModel::SetModelResidueSet().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMapping().
{
    string target_residue_name = target_atom->GetAtomResidueName();
    char target_residue_chain_id = target_atom->GetAtomChainId();
    int target_residue_sequence_number = target_atom->GetAtomResidueSequenceNumber();
    char target_residue_insertion_code = target_atom->GetAtomInsertionCode();
    char target_residue_alternate_location = target_atom->GetAtomAlternateLocation();
    stringstream ss;
    ss << target_residue_name << "_" << target_residue_chain_id << "_" << target_residue_sequence_number << "_" << target_residue_insertion_code << "_" << target_residue_alternate_location;
    string target_key = ss.str();
    PdbModelCard::PdbModelMap models = models_->GetModels();
    for(PdbModelCard::PdbModelMap::iterator it = models.begin();it != models.end(); it++)
    {
        PdbModel* model = (*it).second;
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards;
        int serial_number = 1;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap updated_atoms;
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(target_key.compare(key) != 0)
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    string atom_name = atom->GetAtomName();
                    if(atom_name.compare(target_atom->GetAtomName()) != 0)
                    {
                        serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                        atom->SetAtomSerialNumber(serial_number);
                        updated_atoms[serial_number] = atom;
                        serial_number++;
                    }
                    else
                    {
                        if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
{
                            serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                        }
                    }
                }
            }
            atom_card->SetAtoms(updated_atoms);
            updated_atom_cards.push_back(atom_card);
            serial_number++;
        }
        residue_set->SetAtoms(updated_atom_cards);
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        PdbModelResidueSet::HeterogenAtomCardVector updated_heterogen_atom_cards;
        for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
        {
            PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
            PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
            PdbHeterogenAtomCard::PdbHeterogenAtomMap updated_heterogen_atoms;
            for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(target_key.compare(key) != 0)
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_heterogen_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    string atom_name = atom->GetAtomName();
                    if(atom_name.compare(target_atom->GetAtomName()) != 0)
                    {
                        serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                        atom->SetAtomSerialNumber(serial_number);
                        updated_heterogen_atoms[serial_number] = atom;
                        serial_number++;
                    }
                    else
                    {
                        if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
{
                            serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                        }
                    }
                }
            }
            heterogen_atom_card->SetHeterogenAtoms(updated_heterogen_atoms);
            updated_heterogen_atom_cards.push_back(heterogen_atom_card);
        }
        residue_set->SetHeterogenAtoms(updated_heterogen_atom_cards);
        model->SetModelResidueSet(residue_set);
        (*it).second = model;
    }
    models_->SetModels(models);
    this->UpdateConnectCard();
}
void PdbFile::DeleteAtoms (PdbAtomVector atoms)
Definition at line 1495 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomName(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbAtom::SetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::SetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), and PdbFileSpace::PdbModel::SetModelResidueSet().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::DeleteAllToBeDeletedEntities().
{
    map<string, PdbAtom* > pdb_atom_map = map<string, PdbAtom* >();
    for(PdbAtomVector::iterator it = target_atoms.begin(); it != target_atoms.end(); it++)
    {
        PdbAtom* target_atom = (*it);
        string target_residue_name = target_atom->GetAtomResidueName();
        char target_residue_chain_id = target_atom->GetAtomChainId();
        int target_residue_sequence_number = target_atom->GetAtomResidueSequenceNumber();
        char target_residue_insertion_code = target_atom->GetAtomInsertionCode();
        char target_residue_alternate_location = target_atom->GetAtomAlternateLocation();
        stringstream ss;
        ss << target_residue_name << "_" << target_residue_chain_id << "_" << target_residue_sequence_number << "_" << target_residue_insertion_code << "_" << target_residue_alternate_location;
        string target_key = ss.str();
        pdb_atom_map[target_key] = target_atom;
    }
    PdbModelCard::PdbModelMap models = models_->GetModels();
    for(PdbModelCard::PdbModelMap::iterator it = models.begin();it != models.end(); it++)
    {
        PdbModel* model = (*it).second;
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards;
        int serial_number = 1;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap updated_atoms;
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(pdb_atom_map.find(key) == pdb_atom_map.end())
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    PdbAtom* target_atom = pdb_atom_map[key];
                    string atom_name = atom->GetAtomName();
                    if(atom_name.compare(target_atom->GetAtomName()) != 0)
                    {
                        serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                        atom->SetAtomSerialNumber(serial_number);
                        updated_atoms[serial_number] = atom;
                        serial_number++;
                    }
                    else
                    {
                        if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
{
                            serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                        }
                    }
                }
            }
            atom_card->SetAtoms(updated_atoms);
            updated_atom_cards.push_back(atom_card);
            serial_number++;
        }
        residue_set->SetAtoms(updated_atom_cards);
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        PdbModelResidueSet::HeterogenAtomCardVector updated_heterogen_atom_cards;
        for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
        {
            PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
            PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
            PdbHeterogenAtomCard::PdbHeterogenAtomMap updated_heterogen_atoms;
            for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(pdb_atom_map.find(key) == pdb_atom_map.end())
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_heterogen_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    PdbAtom* target_atom = pdb_atom_map[key];
                    string atom_name = atom->GetAtomName();
                    if(atom_name.compare(target_atom->GetAtomName()) != 0)
                    {
                        serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                        atom->SetAtomSerialNumber(serial_number);
                        updated_heterogen_atoms[serial_number] = atom;
                        serial_number++;
                    }
                    else
                    {
                        if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
{
                            serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                        }
                    }
                }
            }
            heterogen_atom_card->SetHeterogenAtoms(updated_heterogen_atoms);
            updated_heterogen_atom_cards.push_back(heterogen_atom_card);
        }
        residue_set->SetHeterogenAtoms(updated_heterogen_atom_cards);
        model->SetModelResidueSet(residue_set);
        (*it).second = model;
    }
    models_->SetModels(models);
    this->UpdateConnectCard();
}
void PdbFile::DeleteAtomsWithTheGivenModelNumber (PdbAtomVector atoms, int model_number = 1)
Definition at line 1751 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomName(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbAtom::SetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::SetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), and PdbFileSpace::PdbModel::SetModelResidueSet().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::DeleteAllToBeDeletedEntitiesWithTheGivenModelNumber().
{
    map<string, PdbAtom* > pdb_atom_map = map<string, PdbAtom* >();
    for(PdbAtomVector::iterator it = target_atoms.begin(); it != target_atoms.end(); it++)
    {
        PdbAtom* target_atom = (*it);
        string target_residue_name = target_atom->GetAtomResidueName();
        char target_residue_chain_id = target_atom->GetAtomChainId();
        int target_residue_sequence_number = target_atom->GetAtomResidueSequenceNumber();
        char target_residue_insertion_code = target_atom->GetAtomInsertionCode();
        char target_residue_alternate_location = target_atom->GetAtomAlternateLocation();
        stringstream ss;
        ss << target_residue_name << "_" << target_residue_chain_id << "_" << target_residue_sequence_number << "_" << target_residue_insertion_code << "_" << target_residue_alternate_location;
        string target_key = ss.str();
        pdb_atom_map[target_key] = target_atom;
    }
    PdbModelCard::PdbModelMap models = models_->GetModels();
    if(models.size() != 0)
    {
        PdbModel* model = models[model_number];
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards;
        int serial_number = 1;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap updated_atoms;
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(pdb_atom_map.find(key) == pdb_atom_map.end())
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    PdbAtom* target_atom = pdb_atom_map[key];
                    string atom_name = atom->GetAtomName();
                    if(atom_name.compare(target_atom->GetAtomName()) != 0)
                    {
                        serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                        atom->SetAtomSerialNumber(serial_number);
                        updated_atoms[serial_number] = atom;
                        serial_number++;
                    }
                    else
                    {
                        if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
{
                            serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                        }
                    }
                }
            }
            atom_card->SetAtoms(updated_atoms);
            updated_atom_cards.push_back(atom_card);
            serial_number++;
        }
        residue_set->SetAtoms(updated_atom_cards);
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        PdbModelResidueSet::HeterogenAtomCardVector updated_heterogen_atom_cards;
        for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
        {
            PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
            PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
            PdbHeterogenAtomCard::PdbHeterogenAtomMap updated_heterogen_atoms;
            for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(pdb_atom_map.find(key) == pdb_atom_map.end())
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_heterogen_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    PdbAtom* target_atom = pdb_atom_map[key];
                    string atom_name = atom->GetAtomName();
                    if(atom_name.compare(target_atom->GetAtomName()) != 0)
                    {
                        serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                        atom->SetAtomSerialNumber(serial_number);
                        updated_heterogen_atoms[serial_number] = atom;
                        serial_number++;
                    }
                    else
                    {
                        if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
{
                            serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                        }
                    }
                }
            }
            heterogen_atom_card->SetHeterogenAtoms(updated_heterogen_atoms);
            updated_heterogen_atom_cards.push_back(heterogen_atom_card);
        }
        residue_set->SetHeterogenAtoms(updated_heterogen_atom_cards);
        model->SetModelResidueSet(residue_set);
        models[model_number] = model;
        models_->SetModels(models);
        this->UpdateConnectCard();
    }
}
void PdbFile::DeleteAtomWithTheGivenModelNumber (PdbAtom * atom, int model_number = 1)
Definition at line 1627 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomName(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbAtom::SetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::SetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), and PdbFileSpace::PdbModel::SetModelResidueSet().
{
    string target_residue_name = target_atom->GetAtomResidueName();
    char target_residue_chain_id = target_atom->GetAtomChainId();
    int target_residue_sequence_number = target_atom->GetAtomResidueSequenceNumber();
    char target_residue_insertion_code = target_atom->GetAtomInsertionCode();
    char target_residue_alternate_location = target_atom->GetAtomAlternateLocation();
    stringstream ss;
    ss << target_residue_name << "_" << target_residue_chain_id << "_" << target_residue_sequence_number << "_" << target_residue_insertion_code << "_" << target_residue_alternate_location;
    string target_key = ss.str();
    PdbModelCard::PdbModelMap models = models_->GetModels();
    if(models.size() != 0)
    {
        PdbModel* model = models[model_number];
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards;
        int serial_number = 1;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap updated_atoms;
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(target_key.compare(key) != 0)
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    string atom_name = atom->GetAtomName();
                    if(atom_name.compare(target_atom->GetAtomName()) != 0)
                    {
                        serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                        atom->SetAtomSerialNumber(serial_number);
                        updated_atoms[serial_number] = atom;
                        serial_number++;
                    }
                    else
                    {
                        if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
{
                            serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                        }
                    }
                }
            }
            atom_card->SetAtoms(updated_atoms);
            updated_atom_cards.push_back(atom_card);
            serial_number++;
        }
        residue_set->SetAtoms(updated_atom_cards);
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        PdbModelResidueSet::HeterogenAtomCardVector updated_heterogen_atom_cards;
        for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
        {
            PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
            PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
            PdbHeterogenAtomCard::PdbHeterogenAtomMap updated_heterogen_atoms;
            for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(target_key.compare(key) != 0)
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_heterogen_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    string atom_name = atom->GetAtomName();
                    if(atom_name.compare(target_atom->GetAtomName()) != 0)
                    {
                        serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                        atom->SetAtomSerialNumber(serial_number);
                        updated_heterogen_atoms[serial_number] = atom;
                        serial_number++;
                    }
                    else
                    {
                        if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
{
                            serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                        }
                    }
                }
            }
            heterogen_atom_card->SetHeterogenAtoms(updated_heterogen_atoms);
            updated_heterogen_atom_cards.push_back(heterogen_atom_card);
        }
        residue_set->SetHeterogenAtoms(updated_heterogen_atom_cards);
        model->SetModelResidueSet(residue_set);
        models[model_number] = model;
        models_->SetModels(models);
        this->UpdateConnectCard();
    }
}
void PdbFile::DeleteResidue (PdbResidue * residue)
Definition at line 953 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbResidue::GetResidueAlternateLocation(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), PdbFileSpace::PdbResidue::GetResidueName(), PdbFileSpace::PdbResidue::GetResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbAtom::SetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::SetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), and PdbFileSpace::PdbModel::SetModelResidueSet().
{
    string target_residue_name = residue->GetResidueName();
    char target_residue_chain_id = residue->GetResidueChainId();
    int target_residue_sequence_number = residue->GetResidueSequenceNumber();
    char target_residue_insertion_code = residue->GetResidueInsertionCode();
    char target_residue_alternate_location = residue->GetResidueAlternateLocation();
    stringstream ss;
    ss << target_residue_name << "_" << target_residue_chain_id << "_" << target_residue_sequence_number << "_" << target_residue_insertion_code << "_" << target_residue_alternate_location;
    string target_key = ss.str();
    PdbModelCard::PdbModelMap models = models_->GetModels();
    for(PdbModelCard::PdbModelMap::iterator it = models.begin();it != models.end(); it++)
    {
        PdbModel* model = (*it).second;
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards = PdbModelResidueSet::AtomCardVector();
        int serial_number = 1;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap updated_atoms = PdbAtomCard::PdbAtomMap();
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int atom_sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << atom_sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(target_key.compare(key) != 0)
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
                    {
                        serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                    }
                }
            }
            atom_card->SetAtoms(updated_atoms);
            updated_atom_cards.push_back(atom_card);
            serial_number++;
        }
        residue_set->SetAtoms(updated_atom_cards);
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        PdbModelResidueSet::HeterogenAtomCardVector updated_heterogen_atom_cards = PdbModelResidueSet::HeterogenAtomCardVector();
        for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
        {
            PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
            PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
            PdbHeterogenAtomCard::PdbHeterogenAtomMap updated_heterogen_atoms;
            for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int heterogen_atom_sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << heterogen_atom_sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(target_key.compare(key) != 0)
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_heterogen_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
                    {
                        serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                    }
                }
            }
            heterogen_atom_card->SetHeterogenAtoms(updated_heterogen_atoms);
            updated_heterogen_atom_cards.push_back(heterogen_atom_card);
        }
        residue_set->SetHeterogenAtoms(updated_heterogen_atom_cards);
        model->SetModelResidueSet(residue_set);
        (*it).second = model;
    }
    models_->SetModels(models);
    this->UpdateConnectCard();
}
void PdbFile::DeleteResidues (PdbResidueVector residues)
Definition at line 1054 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbResidue::GetResidueAlternateLocation(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), PdbFileSpace::PdbResidue::GetResidueName(), PdbFileSpace::PdbResidue::GetResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbAtom::SetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::SetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), and PdbFileSpace::PdbModel::SetModelResidueSet().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::DeleteAllToBeDeletedEntities().
{
    map<string, PdbResidue* > pdb_residue_map = map<string, PdbResidue* >();
    for(PdbResidueVector::iterator it = target_residues.begin(); it != target_residues.end(); it++)
    {
        PdbResidue* residue = (*it);
        string target_residue_name = residue->GetResidueName();
        char target_residue_chain_id = residue->GetResidueChainId();
        int target_residue_sequence_number = residue->GetResidueSequenceNumber();
        char target_residue_insertion_code = residue->GetResidueInsertionCode();
        char target_residue_alternate_location = residue->GetResidueAlternateLocation();
        stringstream ss;
        ss << target_residue_name << "_" << target_residue_chain_id << "_" << target_residue_sequence_number << "_" << target_residue_insertion_code << "_" << target_residue_alternate_location;
        string target_key = ss.str();
        pdb_residue_map[target_key] = residue;
    }
    PdbModelCard::PdbModelMap models = models_->GetModels();
    for(PdbModelCard::PdbModelMap::iterator it = models.begin();it != models.end(); it++)
    {
        PdbModel* model = (*it).second;
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards = PdbModelResidueSet::AtomCardVector();
        int serial_number = 1;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap updated_atoms = PdbAtomCard::PdbAtomMap();
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int atom_sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << atom_sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(pdb_residue_map.find(key) == pdb_residue_map.end())
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
                    {
                        serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                    }
                }
            }
            atom_card->SetAtoms(updated_atoms);
            updated_atom_cards.push_back(atom_card);
            serial_number++;
        }
        residue_set->SetAtoms(updated_atom_cards);
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        PdbModelResidueSet::HeterogenAtomCardVector updated_heterogen_atom_cards = PdbModelResidueSet::HeterogenAtomCardVector();
        for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
        {
            PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
            PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
            PdbHeterogenAtomCard::PdbHeterogenAtomMap updated_heterogen_atoms;
            for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int heterogen_atom_sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << heterogen_atom_sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(pdb_residue_map.find(key) == pdb_residue_map.end())
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_heterogen_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
                    {
                        serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                    }
                }
            }
            heterogen_atom_card->SetHeterogenAtoms(updated_heterogen_atoms);
            updated_heterogen_atom_cards.push_back(heterogen_atom_card);
        }
        residue_set->SetHeterogenAtoms(updated_heterogen_atom_cards);
        model->SetModelResidueSet(residue_set);
        (*it).second = model;
    }
    models_->SetModels(models);
    this->UpdateConnectCard();
}
void PdbFile::DeleteResiduesWithTheGivenModelNumber (PdbResidueVector residues, int model_number = 1)
Definition at line 1263 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbResidue::GetResidueAlternateLocation(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), PdbFileSpace::PdbResidue::GetResidueName(), PdbFileSpace::PdbResidue::GetResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbAtom::SetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::SetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), and PdbFileSpace::PdbModel::SetModelResidueSet().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::DeleteAllToBeDeletedEntitiesWithTheGivenModelNumber().
{
    map<string, PdbResidue* > pdb_residue_map = map<string, PdbResidue* >();
    for(PdbResidueVector::iterator it = target_residues.begin(); it != target_residues.end(); it++)
    {
        PdbResidue* residue = (*it);
        string target_residue_name = residue->GetResidueName();
        char target_residue_chain_id = residue->GetResidueChainId();
        int target_residue_sequence_number = residue->GetResidueSequenceNumber();
        char target_residue_insertion_code = residue->GetResidueInsertionCode();
        char target_residue_alternate_location = residue->GetResidueAlternateLocation();
        stringstream ss;
        ss << target_residue_name << "_" << target_residue_chain_id << "_" << target_residue_sequence_number << "_" << target_residue_insertion_code << "_" << target_residue_alternate_location;
        string target_key = ss.str();
        pdb_residue_map[target_key] = residue;
    }
    PdbModelCard::PdbModelMap models = models_->GetModels();
    if(models.size() != 0)
    {
        PdbModel* model = models[model_number];
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards = PdbModelResidueSet::AtomCardVector();
        int serial_number = 1;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap updated_atoms = PdbAtomCard::PdbAtomMap();
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int atom_sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << atom_sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(pdb_residue_map.find(key) == pdb_residue_map.end())
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
                    {
                        serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                    }
                }
            }
            atom_card->SetAtoms(updated_atoms);
            updated_atom_cards.push_back(atom_card);
            serial_number++;
        }
        residue_set->SetAtoms(updated_atom_cards);
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        PdbModelResidueSet::HeterogenAtomCardVector updated_heterogen_atom_cards = PdbModelResidueSet::HeterogenAtomCardVector();
        for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
        {
            PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
            PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
            PdbHeterogenAtomCard::PdbHeterogenAtomMap updated_heterogen_atoms;
            for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int heterogen_atom_sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << heterogen_atom_sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(pdb_residue_map.find(key) == pdb_residue_map.end())
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_heterogen_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
                    {
                        serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                    }
                }
            }
            heterogen_atom_card->SetHeterogenAtoms(updated_heterogen_atoms);
            updated_heterogen_atom_cards.push_back(heterogen_atom_card);
        }
        residue_set->SetHeterogenAtoms(updated_heterogen_atom_cards);
        model->SetModelResidueSet(residue_set);
        models[model_number] = model;
        models_->SetModels(models);
        this->UpdateConnectCard();
    }
}
void PdbFile::DeleteResidueWithTheGivenModelNumber (PdbResidue * residue, int model_number = 1)
Definition at line 1161 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbResidue::GetResidueAlternateLocation(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), PdbFileSpace::PdbResidue::GetResidueName(), PdbFileSpace::PdbResidue::GetResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbAtom::SetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::SetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), and PdbFileSpace::PdbModel::SetModelResidueSet().
{
    string target_residue_name = residue->GetResidueName();
    char target_residue_chain_id = residue->GetResidueChainId();
    int target_residue_sequence_number = residue->GetResidueSequenceNumber();
    char target_residue_insertion_code = residue->GetResidueInsertionCode();
    char target_residue_alternate_location = residue->GetResidueAlternateLocation();
    stringstream ss;
    ss << target_residue_name << "_" << target_residue_chain_id << "_" << target_residue_sequence_number << "_" << target_residue_insertion_code << "_" << target_residue_alternate_location;
    string target_key = ss.str();
    PdbModelCard::PdbModelMap models = models_->GetModels();
    if(models.size() != 0)
    {
        PdbModel* model = models[model_number];
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards = PdbModelResidueSet::AtomCardVector();
        int serial_number = 1;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap updated_atoms = PdbAtomCard::PdbAtomMap();
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int atom_sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << atom_sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(target_key.compare(key) != 0)
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
                    {
                        serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                    }
                }
            }
            atom_card->SetAtoms(updated_atoms);
            updated_atom_cards.push_back(atom_card);
            serial_number++;
        }
        residue_set->SetAtoms(updated_atom_cards);
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        PdbModelResidueSet::HeterogenAtomCardVector updated_heterogen_atom_cards = PdbModelResidueSet::HeterogenAtomCardVector();
        for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
        {
            PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
            PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
            PdbHeterogenAtomCard::PdbHeterogenAtomMap updated_heterogen_atoms;
            for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int heterogen_atom_sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << heterogen_atom_sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(target_key.compare(key) != 0)
                {
                    serial_number_mapping_[atom->GetAtomSerialNumber()] = serial_number;
                    atom->SetAtomSerialNumber(serial_number);
                    updated_heterogen_atoms[serial_number] = atom;
                    serial_number++;
                }
                else
                {
                    if(serial_number_mapping_.find(atom->GetAtomSerialNumber()) != serial_number_mapping_.end())
                    {
                        serial_number_mapping_.erase(atom->GetAtomSerialNumber());
                    }
                }
            }
            heterogen_atom_card->SetHeterogenAtoms(updated_heterogen_atoms);
            updated_heterogen_atom_cards.push_back(heterogen_atom_card);
        }
        residue_set->SetHeterogenAtoms(updated_heterogen_atom_cards);
        model->SetModelResidueSet(residue_set);
        models[model_number] = model;
        models_->SetModels(models);
        this->UpdateConnectCard();
    }
}
vector< string > PdbFile::GetAllAtomNamesOfResidue (PdbResidue * residue, PdbFile::PdbResidueAtomsMap residue_atom_map)
Definition at line 756 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomName(), PdbFileSpace::PdbResidue::GetResidueAlternateLocation(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), PdbFileSpace::PdbResidue::GetResidueName(), and PdbFileSpace::PdbResidue::GetResidueSequenceNumber().
{
    string target_residue_name = residue->GetResidueName();
    char target_residue_chain_id = residue->GetResidueChainId();
    int target_residue_sequence_number = residue->GetResidueSequenceNumber();
    char target_residue_insertion_code = residue->GetResidueInsertionCode();
    char target_residue_alternate_location = residue->GetResidueAlternateLocation();
    stringstream ss;
    ss << target_residue_name << "_" << target_residue_chain_id << "_" << target_residue_sequence_number << "_" << target_residue_insertion_code << "_" << target_residue_alternate_location;
    string target_key = ss.str();
    PdbAtomVector* atoms = residue_atom_map[target_key];
    vector<string> atom_names;
    for(PdbAtomVector::iterator it = atoms->begin(); it != atoms->end(); it++)
    {
        PdbAtom* atom = (*it);
        atom_names.push_back(atom->GetAtomName());
    }
    return atom_names;
}
vector< string > PdbFile::GetAllAtomNamesOfResidue (PdbResidue * residue)
Definition at line 777 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomName().
{
    PdbAtomVector atoms = GetAllAtomsOfResidue(residue);
    vector<string> atom_names;
    for(PdbAtomVector::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        PdbAtom* atom = (*it);
        atom_names.push_back(atom->GetAtomName());
    }
    return atom_names;
}
PdbFile::PdbResidueAtomsMap PdbFile::GetAllAtomsInOrder (std::vector< std::string > & key_order)
Definition at line 611 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), and PdbFileSpace::PdbModel::GetModelResidueSet().
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile().
{
    PdbFile::PdbResidueAtomsMap residue_atom_map;
    map<string, bool> inserted_residues;
    PdbModelCard::PdbModelMap models = models_->GetModels();
    PdbModel* model = (*models.begin()).second;
    PdbModelResidueSet* residue_set = model->GetModelResidueSet();
    PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
    for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
    {
        PdbAtomCard* atom_card = (*it1);
        PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
        for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
        {
            PdbAtom* atom = (*it2).second;
            string residue_name = atom->GetAtomResidueName();
            char chain_id = atom->GetAtomChainId();
            int sequence_number = atom->GetAtomResidueSequenceNumber();
            char insertion_code = atom->GetAtomInsertionCode();
            char alternate_location = atom->GetAtomAlternateLocation();
            stringstream ss;
            ss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
            string key = ss.str();
            if(!inserted_residues[key])
            {
                residue_atom_map[key] = new vector<PdbAtom*>();
                inserted_residues[key] = true;
                key_order.push_back(key);
            }
            residue_atom_map[key]->push_back(atom);
        }
    }
    PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
    for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
    {
        PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
        PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
        for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
        {
            PdbAtom* atom = (*it2).second;
            string residue_name = atom->GetAtomResidueName();
            char chain_id = atom->GetAtomChainId();
            int sequence_number = atom->GetAtomResidueSequenceNumber();
            char insertion_code = atom->GetAtomInsertionCode();
            char alternate_location = atom->GetAtomAlternateLocation();
            stringstream ss;
            ss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
            string key = ss.str();
            if(!inserted_residues[key])
            {
                residue_atom_map[key] = new vector<PdbAtom*>();
                inserted_residues[key] = true;
                key_order.push_back(key);
            }
            residue_atom_map[key]->push_back(atom);
        }
    }
    return residue_atom_map;
}
PdbFile::PdbAtomVector PdbFile::GetAllAtomsOfResidue (PdbResidue * residue)
Definition at line 490 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbResidue::GetResidueAlternateLocation(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), PdbFileSpace::PdbResidue::GetResidueName(), and PdbFileSpace::PdbResidue::GetResidueSequenceNumber().
{
    string target_residue_name = residue->GetResidueName();
    char target_residue_chain_id = residue->GetResidueChainId();
    int target_residue_sequence_number = residue->GetResidueSequenceNumber();
    char target_residue_insertion_code = residue->GetResidueInsertionCode();
    char target_residue_alternate_location = residue->GetResidueAlternateLocation();
    stringstream ss;
    ss << target_residue_name << "_" << target_residue_chain_id << "_" << target_residue_sequence_number << "_" << target_residue_insertion_code << "_" << target_residue_alternate_location;
    string target_key = ss.str();
    PdbAtomVector atoms_of_residue;
    PdbModelCard::PdbModelMap models = models_->GetModels();
    PdbModel* model = (*models.begin()).second;
    PdbModelResidueSet* residue_set = model->GetModelResidueSet();
    PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
    for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
    {
        PdbAtomCard* atom_card = (*it1);
        PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
        for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
        {
            PdbAtom* atom = (*it2).second;
            string residue_name = atom->GetAtomResidueName();
            char chain_id = atom->GetAtomChainId();
            int sequence_number = atom->GetAtomResidueSequenceNumber();
            char insertion_code = atom->GetAtomInsertionCode();
            char alternate_location = atom->GetAtomAlternateLocation();
            stringstream sss;
            sss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
            string key = sss.str();
            if(target_key.compare(key) == 0)
            {
                atoms_of_residue.push_back(atom);
            }
        }
    }
    PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
    for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
    {
        PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
        PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
        for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
        {
            PdbAtom* atom = (*it2).second;
            string residue_name = atom->GetAtomResidueName();
            char chain_id = atom->GetAtomChainId();
            int sequence_number = atom->GetAtomResidueSequenceNumber();
            char insertion_code = atom->GetAtomInsertionCode();
            char alternate_location = atom->GetAtomAlternateLocation();
            stringstream sss;
            sss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
            string key = sss.str();
            if(target_key.compare(key) == 0)
            {
                atoms_of_residue.push_back(atom);
            }
        }
    }
    return atoms_of_residue;
}
PdbFile::PdbResidueAtomsMap PdbFile::GetAllAtomsOfResidues ()
Definition at line 552 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), and PdbFileSpace::PdbModel::GetModelResidueSet().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::ExtractCYSResidues().
{
    PdbFile::PdbResidueAtomsMap residue_atom_map;
    map<string, bool> inserted_residues;
    PdbModelCard::PdbModelMap models = models_->GetModels();
    PdbModel* model = (*models.begin()).second;
    PdbModelResidueSet* residue_set = model->GetModelResidueSet();
    PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
    for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
    {
        PdbAtomCard* atom_card = (*it1);
        PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
        for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
        {
            PdbAtom* atom = (*it2).second;
            string residue_name = atom->GetAtomResidueName();
            char chain_id = atom->GetAtomChainId();
            int sequence_number = atom->GetAtomResidueSequenceNumber();
            char insertion_code = atom->GetAtomInsertionCode();
            char alternate_location = atom->GetAtomAlternateLocation();
            stringstream ss;
            ss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
            string key = ss.str();
            if(!inserted_residues[key])
            {
                residue_atom_map[key] = new vector<PdbAtom*>();
                inserted_residues[key] = true;
            }
            residue_atom_map[key]->push_back(atom);
        }
    }
    PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
    for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
    {
        PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
        PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
        for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
        {
            PdbAtom* atom = (*it2).second;
            string residue_name = atom->GetAtomResidueName();
            char chain_id = atom->GetAtomChainId();
            int sequence_number = atom->GetAtomResidueSequenceNumber();
            char insertion_code = atom->GetAtomInsertionCode();
            char alternate_location = atom->GetAtomAlternateLocation();
            stringstream ss;
            ss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
            string key = ss.str();
            if(!inserted_residues[key])
            {
                residue_atom_map[key] = new vector<PdbAtom*>();
                inserted_residues[key] = true;
            }
            residue_atom_map[key]->push_back(atom);
        }
    }
    return residue_atom_map;
}
PdbFile::PdbPairVectorAtomNamePositionFlag PdbFile::GetAllResidueNames ()
Definition at line 306 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), and PdbFileSpace::PdbModel::GetModelResidueSet().
{
    PdbPairVectorAtomNamePositionFlag residue_names;
    PdbModelCard::PdbModelMap models = models_->GetModels();
    PdbModel* model = (*models.begin()).second;
    PdbModelResidueSet* residue_set = model->GetModelResidueSet();
    PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
    for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
    {
        PdbAtomCard* atom_card = (*it1);
        PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
        for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
        {
            PdbAtom* atom = (*it2).second;
            int dist = distance(atoms.begin(), it2);
            string atom_residue_name = atom->GetAtomResidueName();
            if(dist == 0)
            {
                pair<string, string> pair_residue_position = make_pair(atom_residue_name, "S");
                if(find(residue_names.begin(), residue_names.end(), pair_residue_position) == residue_names.end())
                        residue_names.push_back(pair_residue_position);
            }
            else if(dist == atoms.size() - 1)
            {
                pair<string, string> pair_residue_position = make_pair(atom_residue_name, "E");
                if(find(residue_names.begin(), residue_names.end(), pair_residue_position) == residue_names.end())
                    residue_names.push_back(pair_residue_position);
            }
            pair<string, string> pair_residue_position = make_pair(atom_residue_name, " ");
            if(find(residue_names.begin(), residue_names.end(), pair_residue_position) == residue_names.end())
                residue_names.push_back(pair_residue_position);
        }
    }
    PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
    for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
    {
        PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
        PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
        for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
        {
            PdbAtom* atom = (*it2).second;
            string atom_residue_name = atom->GetAtomResidueName();
            pair<string, string> pair_residue_position = make_pair(atom_residue_name, " ");
            if(find(residue_names.begin(), residue_names.end(), pair_residue_position) == residue_names.end())
            {
                residue_names.push_back(pair_residue_position);
            }
        }
    }
    return residue_names;
}
PdbFile::PdbPairVectorAtomNamePositionFlag PdbFile::GetAllResidueNamesFromAtomCard ()
Definition at line 358 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), and PdbFileSpace::PdbModel::GetModelResidueSet().
{
    PdbPairVectorAtomNamePositionFlag residue_names;
    PdbModelCard::PdbModelMap models = models_->GetModels();
    PdbModel* model = (*models.begin()).second;
    PdbModelResidueSet* residue_set = model->GetModelResidueSet();
    PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
    for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
    {
        PdbAtomCard* atom_card = (*it1);
        PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
        for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
        {
            PdbAtom* atom = (*it2).second;
            int dist = distance(atoms.begin(), it2);
            string atom_residue_name = atom->GetAtomResidueName();
            if(dist == 0)
            {
                pair<string, string> pair_residue_position = make_pair(atom_residue_name, "S");
                if(find(residue_names.begin(), residue_names.end(), pair_residue_position) == residue_names.end())
                        residue_names.push_back(pair_residue_position);
            }
            else if(dist == atoms.size() - 1)
            {
                pair<string, string> pair_residue_position = make_pair(atom_residue_name, "E");
                if(find(residue_names.begin(), residue_names.end(), pair_residue_position) == residue_names.end())
                    residue_names.push_back(pair_residue_position);
            }
            else
            {
                pair<string, string> pair_residue_position = make_pair(atom_residue_name, " ");
                if(find(residue_names.begin(), residue_names.end(), pair_residue_position) == residue_names.end())
                    residue_names.push_back(pair_residue_position);
            }
        }
    }
    return residue_names;
}
PdbFile::PdbResidueVector PdbFile::GetAllResidues ()
Definition at line 398 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), and PdbFileSpace::PdbModel::GetModelResidueSet().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::ExtractAlternateResidue(), PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMapping(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMappingWithTheGivenNumber().
{
    PdbFile::PdbResidueVector residues;
    map<string, bool> inserted_residues;
    PdbModelCard::PdbModelMap models = models_->GetModels();
    PdbModel* model = (*models.begin()).second;
    PdbModelResidueSet* residue_set = model->GetModelResidueSet();
    PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
    for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
    {
        PdbAtomCard* atom_card = (*it1);
        PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
        for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
        {
            PdbAtom* atom = (*it2).second;
            string residue_name = atom->GetAtomResidueName();
            char chain_id = atom->GetAtomChainId();
            int sequence_number = atom->GetAtomResidueSequenceNumber();
            char insertion_code = atom->GetAtomInsertionCode();
            char alternate_location = atom->GetAtomAlternateLocation();
            stringstream ss;
            ss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
            string key = ss.str();
            if(!inserted_residues[key])
            {
                PdbResidue* res = new PdbResidue(residue_name, chain_id, sequence_number, insertion_code, alternate_location);
                residues.push_back(res);
                inserted_residues[key] = true;
            }
        }
    }
    PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
    for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
    {
        PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
        PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
        for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
        {
            PdbAtom* atom = (*it2).second;
            string residue_name = atom->GetAtomResidueName();
            char chain_id = atom->GetAtomChainId();
            int sequence_number = atom->GetAtomResidueSequenceNumber();
            char insertion_code = atom->GetAtomInsertionCode();
            char alternate_location = atom->GetAtomAlternateLocation();
            stringstream ss;
            ss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
            string key = ss.str();
            if(!inserted_residues[key])
            {
                PdbResidue* res = new PdbResidue(residue_name, chain_id, sequence_number, insertion_code, alternate_location);
                residues.push_back(res);
                inserted_residues[key] = true;
            }
        }
    }
    return residues;
}
PdbFile::PdbResidueVector PdbFile::GetAllResiduesFromAtomCard ()
Definition at line 456 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), and PdbFileSpace::PdbModel::GetModelResidueSet().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::ExtractAminoAcidChains(), PdbPreprocessorSpace::PdbPreprocessor::ExtractCYSResidues(), PdbPreprocessorSpace::PdbPreprocessor::ExtractGapsInAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::ExtractHISResidues().
{
    PdbFile::PdbResidueVector residues = PdbFile::PdbResidueVector();
    map<string, bool> inserted_residues = map<string, bool>();
    PdbModelCard::PdbModelMap models = models_->GetModels();
    PdbModel* model = (*models.begin()).second;
    PdbModelResidueSet* residue_set = model->GetModelResidueSet();
    PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
    for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
    {
        PdbAtomCard* atom_card = (*it1);
        PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
        for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
        {
            PdbAtom* atom = (*it2).second;
            string residue_name = atom->GetAtomResidueName();
            char chain_id = atom->GetAtomChainId();
            int sequence_number = atom->GetAtomResidueSequenceNumber();
            char insertion_code = atom->GetAtomInsertionCode();
            char alternate_location = atom->GetAtomAlternateLocation();
            stringstream ss;
            ss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code << "_" << alternate_location;
            string key = ss.str();
            if(!inserted_residues[key])
            {
                PdbResidue* res = new PdbResidue(residue_name, chain_id, sequence_number, insertion_code, alternate_location);
                residues.push_back(res);
                inserted_residues[key] = true;
            }
        }
    }
    return residues;
}
PdbFile::PdbPairVectorTerCardPositions PdbFile::GetAllTerCardPositions (std::vector< std::string > glycam_residue_names)
Definition at line 789 of file pdbfile.cc.
References PdbFileSpace::PdbResidue::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueName(), and PdbFileSpace::PdbResidue::GetResidueSequenceNumber().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChainsWithTheGivenModelNumber().
{
    vector<pair<char, int> > ter_card_positions = vector<pair<char, int> >();
    // After residues that has no tails or has more than or equal two tails
    PdbFile::PdbResidueVector residues = this->GetAllResiduesFromAtomCard();
    for(PdbFile::PdbResidueVector::iterator it = residues.begin(); it != residues.end(); it++)
    {
        int dist = distance(residues.begin(), it);
        if(dist != residues.size() - 1)
        {
            PdbResidue* residue = (*it);
            string residue_name = residue->GetResidueName();
            if(find(glycam_residue_names.begin(), glycam_residue_names.end(), residue_name) != glycam_residue_names.end())
            {
                // No tail || has more than or equal two tails
                if(residue_name[0] == '0' || isalpha(residue_name[0]))
                {
                    ter_card_positions.push_back(make_pair(residue->GetResidueChainId(), residue->GetResidueSequenceNumber() + 1));
                }
            }
        }
    }
    return ter_card_positions;
}
PdbAtom * PdbFile::GetAtomBySerialNumber (int serial_number)
Definition at line 732 of file pdbfile.cc.
References PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), and PdbFileSpace::PdbModel::GetModelResidueSet().
Referenced by MolecularModeling::Assembly::BuildStructureByPDBFileInformation().
{
    PdbModelCard::PdbModelMap models = models_->GetModels();
    PdbModel* model = (*models.begin()).second;
    PdbModelResidueSet* residue_set = model->GetModelResidueSet();
    PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
    for(PdbModelResidueSet::AtomCardVector::iterator it = atom_cards.begin(); it != atom_cards.end(); it++)
    {
        PdbAtomCard* atom_card = (*it);
        PdbAtomCard::PdbAtomMap atom_map = atom_card->GetAtoms();
        if(atom_map[serial_number] != NULL)
            return atom_map[serial_number];
    }
    PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
    for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it = heterogen_atom_cards.begin(); it != heterogen_atom_cards.end(); it++)
    {
        PdbHeterogenAtomCard* heterogen_atom_card = (*it);
        PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atom_map = heterogen_atom_card->GetHeterogenAtoms();
        if(heterogen_atom_map[serial_number] != NULL)
            return heterogen_atom_map[serial_number];
    }
    return NULL;
}
PdbAtom * PdbFile::GetAtomOfResidueByAtomKey (std::string atom_key)
Definition at line 706 of file pdbfile.cc.
References PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), and gmml::Split().
Referenced by MolecularModeling::Assembly::BuildStructureByPDBFileInformation().
{
    vector<string> key_tokens = Split(atom_key, "_");
    int serial_number = gmml::ConvertString<int>(key_tokens.at(1));
    PdbModelCard::PdbModelMap models = models_->GetModels();
    PdbModel* model = (*models.begin()).second;
    PdbModelResidueSet* residue_set = model->GetModelResidueSet();
    PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
    for(PdbModelResidueSet::AtomCardVector::iterator it = atom_cards.begin(); it != atom_cards.end(); it++)
    {
        PdbAtomCard* atom_card = (*it);
        PdbAtomCard::PdbAtomMap atom_map = atom_card->GetAtoms();
        if(atom_map[serial_number] != NULL)
            return atom_map[serial_number];
    }
    PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
    for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it = heterogen_atom_cards.begin(); it != heterogen_atom_cards.end(); it++)
    {
        PdbHeterogenAtomCard* heterogen_atom_card = (*it);
        PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atom_map = heterogen_atom_card->GetHeterogenAtoms();
        if(heterogen_atom_map[serial_number] != NULL)
            return heterogen_atom_map[serial_number];
    }
    return NULL;
}
PdbAtom* PdbFileSpace::PdbFile::GetAtomOfResidueByName (PdbResidue * residue, std::string atom_name, PdbResidueAtomsMap residue_atom_map)
Referenced by PdbPreprocessorSpace::PdbPreprocessor::ExtractHISResidues(), PdbPreprocessorSpace::PdbPreprocessor::GetDistanceofCYS(), PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMapping(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMappingWithTheGivenNumber().
PdbAtom* PdbFileSpace::PdbFile::GetAtomOfResidueByName (PdbResidue * residue, std::string atom_name)
PdbCompoundCard * PdbFile::GetCompound ()
Definition at line 198 of file pdbfile.cc.
{
    return compound_;
}
PdbConnectCard * PdbFile::GetConnectivities ()
Definition at line 293 of file pdbfile.cc.
Referenced by MolecularModeling::Assembly::BuildStructureByPDBFileInformation().
{
    return connectivities_;
}
PdbCrystallographicCard * PdbFile::GetCrystallography ()
Definition at line 268 of file pdbfile.cc.
{
    return crystallography_;
}
PdbDisulfideBondCard * PdbFile::GetDisulfideBonds ()
Definition at line 253 of file pdbfile.cc.
{
    return disulfide_bonds_;
}
PdbFormulaCard * PdbFile::GetFormulas ()
Definition at line 238 of file pdbfile.cc.
{
    return formulas_;
}
PdbHeaderCard * PdbFile::GetHeader ()
Definition at line 188 of file pdbfile.cc.
{
    return header_;
}
PdbHelixCard * PdbFile::GetHelixes ()
Definition at line 243 of file pdbfile.cc.
{
    return helixes_;
}
PdbHeterogenCard * PdbFile::GetHeterogens ()
Definition at line 223 of file pdbfile.cc.
{
    return heterogens_;
}
PdbHeterogenNameCard * PdbFile::GetHeterogensName ()
Definition at line 228 of file pdbfile.cc.
{
    return heterogens_name_;
}
PdbHeterogenSynonymCard * PdbFile::GetHeterogenSynonyms ()
Definition at line 233 of file pdbfile.cc.
{
    return heterogen_synonyms_;
}
PdbLinkCard * PdbFile::GetLinks ()
Definition at line 258 of file pdbfile.cc.
{
    return links_;
}
PdbMatrixNCard * PdbFile::GetMatrices ()
Definition at line 283 of file pdbfile.cc.
{
    return matrices_;
}
PdbModelCard * PdbFile::GetModels ()
Definition at line 288 of file pdbfile.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile().
{
    return models_;
}
PdbModelTypeCard * PdbFile::GetModelType ()
Definition at line 208 of file pdbfile.cc.
{
    return model_type_;
}
PdbNumModelCard * PdbFile::GetNumberOfModels ()
Definition at line 203 of file pdbfile.cc.
{
    return number_of_models_;
}
PdbOriginXnCard * PdbFile::GetOrigins ()
Definition at line 273 of file pdbfile.cc.
{
    return origins_;
}
string PdbFile::GetPath ()
Definition at line 183 of file pdbfile.cc.
{
    return path_;
}
PdbResidueModificationCard * PdbFile::GetResidueModification ()
Definition at line 218 of file pdbfile.cc.
{
    return residue_modification_;
}
PdbResidueSequenceCard * PdbFile::GetResiduesSequence ()
Definition at line 213 of file pdbfile.cc.
{
    return residues_sequence_;
}
PdbScaleNCard * PdbFile::GetScales ()
Definition at line 278 of file pdbfile.cc.
{
    return scales_;
}
PdbFile::PdbSerialNumberMapping PdbFile::GetSequenceNumberMapping ()
Definition at line 301 of file pdbfile.cc.
{
    return sequence_number_mapping_;
}
PdbFile::PdbSerialNumberMapping PdbFile::GetSerialNumberMapping ()
Definition at line 297 of file pdbfile.cc.
{
    return serial_number_mapping_;
}
PdbSheetCard * PdbFile::GetSheets ()
Definition at line 248 of file pdbfile.cc.
{
    return sheets_;
}
PdbSiteCard * PdbFile::GetSites ()
Definition at line 263 of file pdbfile.cc.
{
    return sites_;
}
PdbTitleCard * PdbFile::GetTitle ()
Definition at line 193 of file pdbfile.cc.
{
    return title_;
}
void PdbFile::InsertResidueAfter (PdbAtomCard * residue)
Definition at line 2341 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomCharge(), PdbFileSpace::PdbAtom::GetAtomElementSymbol(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomName(), PdbFileSpace::PdbAtom::GetAtomOccupancy(), PdbFileSpace::PdbAtom::GetAtomOrthogonalCoordinate(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomTempretureFactor(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbModel::GetModelSerialNumber(), PdbFileSpace::PdbAtomCard::GetRecordName(), PdbFileSpace::PdbHeterogenAtomCard::GetRecordName(), gmml::iNotSet, PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbHeterogenAtomCard::SetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), PdbFileSpace::PdbModel::SetModelResidueSet(), PdbFileSpace::PdbModel::SetModelSerialNumber(), PdbFileSpace::PdbAtomCard::SetRecordName(), and PdbFileSpace::PdbHeterogenAtomCard::SetRecordName().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains().
{
    PdbModelCard::PdbModelMap models = models_->GetModels();
    PdbModelCard::PdbModelMap updated_models;
    for(PdbModelCard::PdbModelMap::iterator it = models.begin(); it != models.end(); it++)
    {
        PdbModel* model = (*it).second;
        PdbModel* updated_model = new PdbModel();
        updated_model->SetModelSerialNumber(model->GetModelSerialNumber());
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet* updated_residue_set = new PdbModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards;
        int serial_number = 1;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard* updated_atom_card = new PdbAtomCard();
            updated_atom_card->SetRecordName(atom_card->GetRecordName());
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap updated_atoms;
            int sequence_number = 1;
            bool located = false;
            PdbAtomCard::PdbAtomMap atoms_of_residue = residue->GetAtoms();
            PdbAtom* first_atom_in_residue = (*(atoms_of_residue.begin())).second;
            char residue_chain_id = first_atom_in_residue->GetAtomChainId();
            int residue_sequence_number = first_atom_in_residue->GetAtomResidueSequenceNumber();
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                if(residue_chain_id == atom->GetAtomChainId() && residue_sequence_number == atom->GetAtomResidueSequenceNumber())
                {
                    if(it2 != atoms.begin())
                    {
                        PdbAtom* previous_atom = (*(--it2)).second;
                        it2++;
                        if(previous_atom->GetAtomResidueSequenceNumber() != atom->GetAtomResidueSequenceNumber())
{
                            int diff = atom->GetAtomResidueSequenceNumber() - previous_atom->GetAtomResidueSequenceNumber();
                            if(diff == 1)
                                sequence_number++;
                            else
                                sequence_number += diff;
                        }
                    }
                    else
                    {
                        sequence_number = atom->GetAtomResidueSequenceNumber();
                    }
                    PdbAtom* updated_atom = new PdbAtom(serial_number, atom->GetAtomName(),atom->GetAtomAlternateLocation(), atom->GetAtomResidueName(),
                                                        atom->GetAtomChainId(), sequence_number, atom->GetAtomInsertionCode(), atom->GetAtomOrthogonalCoordinate(),
                                                        atom->GetAtomOccupancy(), atom->GetAtomTempretureFactor(), atom->GetAtomElementSymbol(), atom->GetAtomCharge());
                    updated_atoms[serial_number] = updated_atom;
                    serial_number++;
                    if(sequence_number != atom->GetAtomResidueSequenceNumber())
                        sequence_number_mapping_[sequence_number] = atom->GetAtomResidueSequenceNumber();
                    located = true;
                }
                else
                {
                    if(located)
                    {
                        sequence_number++;
                        for(PdbAtomCard::PdbAtomMap::iterator it3 = atoms_of_residue.begin(); it3 != atoms_of_residue.end(); it3++)
{
                            PdbAtom* atom_of_residue = (*it3).second;
                            PdbAtom* new_atom = new PdbAtom(serial_number, atom_of_residue->GetAtomName(),atom_of_residue->GetAtomAlternateLocation(),
                                                            atom_of_residue->GetAtomResidueName(),atom_of_residue->GetAtomChainId(), sequence_number,
                                                            atom_of_residue->GetAtomInsertionCode(), atom_of_residue->GetAtomOrthogonalCoordinate(),
                                                            atom_of_residue->GetAtomOccupancy(), atom_of_residue->GetAtomTempretureFactor(),
                                                            atom_of_residue->GetAtomElementSymbol(), atom_of_residue->GetAtomCharge());
                            updated_atoms[serial_number] = new_atom;
                            serial_number++;
                        }
                        sequence_number_mapping_[sequence_number] = iNotSet;
                        located = false;
                    }
                    if(!located)
                    {
                        if(it2 != atoms.begin())
{
                            PdbAtom* previous_atom = (*(--it2)).second;
                            it2++;
                            if(previous_atom->GetAtomResidueSequenceNumber() != atom->GetAtomResidueSequenceNumber())
{
                                int diff = atom->GetAtomResidueSequenceNumber() - previous_atom->GetAtomResidueSequenceNumber();
                                if(diff == 1)
                                    sequence_number++;
                                else
                                    sequence_number += diff;
                            }
                        }
                        else
{
                            sequence_number = atom->GetAtomResidueSequenceNumber();
                        }
                        PdbAtom* updated_atom = new PdbAtom(serial_number, atom->GetAtomName(),atom->GetAtomAlternateLocation(), atom->GetAtomResidueName(),
                                                            atom->GetAtomChainId(), sequence_number, atom->GetAtomInsertionCode(), atom->GetAtomOrthogonalCoordinate(),
                                                            atom->GetAtomOccupancy(), atom->GetAtomTempretureFactor(), atom->GetAtomElementSymbol(), atom->GetAtomCharge());
                        updated_atoms[serial_number] = updated_atom;
                        serial_number++;
                        if(sequence_number != atom->GetAtomResidueSequenceNumber())
                            sequence_number_mapping_[sequence_number] = atom->GetAtomResidueSequenceNumber();
                    }
                }
                if(it2 == --atoms.end() && located)
                {
                    sequence_number++;
                    for(PdbAtomCard::PdbAtomMap::iterator it3 = atoms_of_residue.begin(); it3 != atoms_of_residue.end(); it3++)
                    {
                        PdbAtom* atom_of_residue = (*it3).second;
                        PdbAtom* new_atom = new PdbAtom(serial_number, atom_of_residue->GetAtomName(),atom_of_residue->GetAtomAlternateLocation(),
                                                        atom_of_residue->GetAtomResidueName(),atom_of_residue->GetAtomChainId(), sequence_number,
                                                        atom_of_residue->GetAtomInsertionCode(), atom_of_residue->GetAtomOrthogonalCoordinate(),
                                                        atom_of_residue->GetAtomOccupancy(), atom_of_residue->GetAtomTempretureFactor(),
                                                        atom_of_residue->GetAtomElementSymbol(), atom_of_residue->GetAtomCharge());
                        updated_atoms[serial_number] = new_atom;
                        serial_number++;
                    }
                    sequence_number_mapping_[sequence_number] = iNotSet;
                    located = false;
                    sequence_number++;
                }
            }
            updated_atom_card->SetAtoms(updated_atoms);
            updated_atom_cards.push_back(updated_atom_card);
            serial_number++;
        }
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        PdbModelResidueSet::HeterogenAtomCardVector updated_heterogen_atom_cards;
        for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
        {
            PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
            PdbHeterogenAtomCard* updated_heterogen_atom_card = new PdbHeterogenAtomCard();
            updated_heterogen_atom_card->SetRecordName(heterogen_atom_card->GetRecordName());
            PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
            PdbHeterogenAtomCard::PdbHeterogenAtomMap updated_heterogen_atoms;
            for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
            {
                PdbAtom* heterogen_atom = (*it2).second;
                PdbAtom* updated_heterogen_atom = new PdbAtom(serial_number, heterogen_atom->GetAtomName(),heterogen_atom->GetAtomAlternateLocation(),
                                                              heterogen_atom->GetAtomResidueName(), heterogen_atom->GetAtomChainId(), heterogen_atom->GetAtomResidueSequenceNumber(),
                                                              heterogen_atom->GetAtomInsertionCode(), heterogen_atom->GetAtomOrthogonalCoordinate(),
                                                              heterogen_atom->GetAtomOccupancy(), heterogen_atom->GetAtomTempretureFactor(),
                                                              heterogen_atom->GetAtomElementSymbol(), heterogen_atom->GetAtomCharge());
                updated_heterogen_atoms[serial_number] = updated_heterogen_atom;
                serial_number++;
            }
            updated_heterogen_atom_card->SetHeterogenAtoms(updated_heterogen_atoms);
            updated_heterogen_atom_cards.push_back(updated_heterogen_atom_card);
        }
        updated_residue_set->SetAtoms(updated_atom_cards);
        updated_residue_set->SetHeterogenAtoms(updated_heterogen_atom_cards);
        updated_model->SetModelResidueSet(updated_residue_set);
        updated_models[updated_model->GetModelSerialNumber()] = updated_model;
    }
    models_->SetModels(updated_models);
}
void PdbFile::InsertResidueAfterWithTheGivenModelNumber (PdbAtomCard * residue, int model_number = 1)
Definition at line 2503 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomCharge(), PdbFileSpace::PdbAtom::GetAtomElementSymbol(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomName(), PdbFileSpace::PdbAtom::GetAtomOccupancy(), PdbFileSpace::PdbAtom::GetAtomOrthogonalCoordinate(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomTempretureFactor(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbModel::GetModelSerialNumber(), PdbFileSpace::PdbAtomCard::GetRecordName(), PdbFileSpace::PdbHeterogenAtomCard::GetRecordName(), gmml::iNotSet, PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbHeterogenAtomCard::SetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), PdbFileSpace::PdbModel::SetModelResidueSet(), PdbFileSpace::PdbModel::SetModelSerialNumber(), PdbFileSpace::PdbAtomCard::SetRecordName(), and PdbFileSpace::PdbHeterogenAtomCard::SetRecordName().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChainsWithTheGivenModelNumber(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    PdbModelCard::PdbModelMap models = models_->GetModels();
    if(models.size() != 0)
    {
        PdbModel* model = models[model_number];
        PdbModelCard::PdbModelMap updated_models;
        PdbModel* updated_model = new PdbModel();
        updated_model->SetModelSerialNumber(model->GetModelSerialNumber());
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet* updated_residue_set = new PdbModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards;
        int serial_number = 1;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard* updated_atom_card = new PdbAtomCard();
            updated_atom_card->SetRecordName(atom_card->GetRecordName());
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap updated_atoms;
            int sequence_number = 1;
            bool located = false;
            PdbAtomCard::PdbAtomMap atoms_of_residue = residue->GetAtoms();
            PdbAtom* first_atom_in_residue = (*(atoms_of_residue.begin())).second;
            char residue_chain_id = first_atom_in_residue->GetAtomChainId();
            int residue_sequence_number = first_atom_in_residue->GetAtomResidueSequenceNumber();
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                if(residue_chain_id == atom->GetAtomChainId() && residue_sequence_number == atom->GetAtomResidueSequenceNumber())
                {
                    if(it2 != atoms.begin())
                    {
                        PdbAtom* previous_atom = (*(--it2)).second;
                        it2++;
                        if(previous_atom->GetAtomResidueSequenceNumber() != atom->GetAtomResidueSequenceNumber())
{
                            int diff = atom->GetAtomResidueSequenceNumber() - previous_atom->GetAtomResidueSequenceNumber();
                            if(diff == 1)
                                sequence_number++;
                            else
                                sequence_number += diff;
                        }
                    }
                    else
                    {
                        sequence_number = atom->GetAtomResidueSequenceNumber();
                    }
                    PdbAtom* updated_atom = new PdbAtom(serial_number, atom->GetAtomName(),atom->GetAtomAlternateLocation(), atom->GetAtomResidueName(),
                                                        atom->GetAtomChainId(), sequence_number, atom->GetAtomInsertionCode(), atom->GetAtomOrthogonalCoordinate(),
                                                        atom->GetAtomOccupancy(), atom->GetAtomTempretureFactor(), atom->GetAtomElementSymbol(), atom->GetAtomCharge());
                    updated_atoms[serial_number] = updated_atom;
                    serial_number++;
                    if(sequence_number != atom->GetAtomResidueSequenceNumber())
                        sequence_number_mapping_[sequence_number] = atom->GetAtomResidueSequenceNumber();
                    located = true;
                }
                else
                {
                    if(located)
                    {
                        sequence_number++;
                        for(PdbAtomCard::PdbAtomMap::iterator it3 = atoms_of_residue.begin(); it3 != atoms_of_residue.end(); it3++)
{
                            PdbAtom* atom_of_residue = (*it3).second;
                            PdbAtom* new_atom = new PdbAtom(serial_number, atom_of_residue->GetAtomName(),atom_of_residue->GetAtomAlternateLocation(),
                                                            atom_of_residue->GetAtomResidueName(),atom_of_residue->GetAtomChainId(), sequence_number,
                                                            atom_of_residue->GetAtomInsertionCode(), atom_of_residue->GetAtomOrthogonalCoordinate(),
                                                            atom_of_residue->GetAtomOccupancy(), atom_of_residue->GetAtomTempretureFactor(),
                                                            atom_of_residue->GetAtomElementSymbol(), atom_of_residue->GetAtomCharge());
                            updated_atoms[serial_number] = new_atom;
                            serial_number++;
                        }
                        located = false;
                    }
                    if(!located)
                    {
                        if(it2 != atoms.begin())
{
                            PdbAtom* previous_atom = (*(--it2)).second;
                            it2++;
                            if(previous_atom->GetAtomResidueSequenceNumber() != atom->GetAtomResidueSequenceNumber())
{
                                int diff = atom->GetAtomResidueSequenceNumber() - previous_atom->GetAtomResidueSequenceNumber();
                                if(diff == 1)
                                    sequence_number++;
                                else
                                    sequence_number += diff;
                            }
                        }
                        else
{
                            sequence_number = atom->GetAtomResidueSequenceNumber();
                        }
                        PdbAtom* updated_atom = new PdbAtom(serial_number, atom->GetAtomName(),atom->GetAtomAlternateLocation(), atom->GetAtomResidueName(),
                                                            atom->GetAtomChainId(), sequence_number, atom->GetAtomInsertionCode(), atom->GetAtomOrthogonalCoordinate(),
                                                            atom->GetAtomOccupancy(), atom->GetAtomTempretureFactor(), atom->GetAtomElementSymbol(), atom->GetAtomCharge());
                        updated_atoms[serial_number] = updated_atom;
                        serial_number++;
                        if(sequence_number != atom->GetAtomResidueSequenceNumber())
                            sequence_number_mapping_[sequence_number] = atom->GetAtomResidueSequenceNumber();
                    }
                }
                if(it2 == --atoms.end() && located)
                {
                    sequence_number++;
                    for(PdbAtomCard::PdbAtomMap::iterator it3 = atoms_of_residue.begin(); it3 != atoms_of_residue.end(); it3++)
                    {
                        PdbAtom* atom_of_residue = (*it3).second;
                        PdbAtom* new_atom = new PdbAtom(serial_number, atom_of_residue->GetAtomName(),atom_of_residue->GetAtomAlternateLocation(),
                                                        atom_of_residue->GetAtomResidueName(),atom_of_residue->GetAtomChainId(), sequence_number,
                                                        atom_of_residue->GetAtomInsertionCode(), atom_of_residue->GetAtomOrthogonalCoordinate(),
                                                        atom_of_residue->GetAtomOccupancy(), atom_of_residue->GetAtomTempretureFactor(),
                                                        atom_of_residue->GetAtomElementSymbol(), atom_of_residue->GetAtomCharge());
                        updated_atoms[serial_number] = new_atom;
                        serial_number++;
                    }
                    sequence_number_mapping_[sequence_number] = iNotSet;
                    located = false;
                    sequence_number++;
                }
            }
            updated_atom_card->SetAtoms(updated_atoms);
            updated_atom_cards.push_back(updated_atom_card);
            serial_number++;
        }
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        PdbModelResidueSet::HeterogenAtomCardVector updated_heterogen_atom_cards;
        for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
        {
            PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
            PdbHeterogenAtomCard* updated_heterogen_atom_card = new PdbHeterogenAtomCard();
            updated_heterogen_atom_card->SetRecordName(heterogen_atom_card->GetRecordName());
            PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
            PdbHeterogenAtomCard::PdbHeterogenAtomMap updated_heterogen_atoms;
            for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
            {
                PdbAtom* heterogen_atom = (*it2).second;
                PdbAtom* updated_heterogen_atom = new PdbAtom(serial_number, heterogen_atom->GetAtomName(),heterogen_atom->GetAtomAlternateLocation(),
                                                              heterogen_atom->GetAtomResidueName(), heterogen_atom->GetAtomChainId(), heterogen_atom->GetAtomResidueSequenceNumber(),
                                                              heterogen_atom->GetAtomInsertionCode(), heterogen_atom->GetAtomOrthogonalCoordinate(),
                                                              heterogen_atom->GetAtomOccupancy(), heterogen_atom->GetAtomTempretureFactor(),
                                                              heterogen_atom->GetAtomElementSymbol(), heterogen_atom->GetAtomCharge());
                updated_heterogen_atoms[serial_number] = updated_heterogen_atom;
                serial_number++;
            }
            updated_heterogen_atom_card->SetHeterogenAtoms(updated_heterogen_atoms);
            updated_heterogen_atom_cards.push_back(updated_heterogen_atom_card);
        }
        updated_residue_set->SetAtoms(updated_atom_cards);
        updated_residue_set->SetHeterogenAtoms(updated_heterogen_atom_cards);
        updated_model->SetModelResidueSet(updated_residue_set);
        updated_models[updated_model->GetModelSerialNumber()] = updated_model;
        models_->SetModels(updated_models);
    }
}
void PdbFile::InsertResidueBefore (PdbAtomCard * residue)
Definition at line 2060 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomCharge(), PdbFileSpace::PdbAtom::GetAtomElementSymbol(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomName(), PdbFileSpace::PdbAtom::GetAtomOccupancy(), PdbFileSpace::PdbAtom::GetAtomOrthogonalCoordinate(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomTempretureFactor(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbModel::GetModelSerialNumber(), PdbFileSpace::PdbAtomCard::GetRecordName(), PdbFileSpace::PdbHeterogenAtomCard::GetRecordName(), gmml::iNotSet, PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbHeterogenAtomCard::SetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), PdbFileSpace::PdbModel::SetModelResidueSet(), PdbFileSpace::PdbModel::SetModelSerialNumber(), PdbFileSpace::PdbAtomCard::SetRecordName(), and PdbFileSpace::PdbHeterogenAtomCard::SetRecordName().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains().
{
    PdbModelCard::PdbModelMap models = models_->GetModels();
    PdbModelCard::PdbModelMap updated_models;
    for(PdbModelCard::PdbModelMap::iterator it = models.begin(); it != models.end(); it++)
    {
        PdbModel* model = (*it).second;
        PdbModel* updated_model = new PdbModel();
        updated_model->SetModelSerialNumber(model->GetModelSerialNumber());
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet* updated_residue_set = new PdbModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards;
        int serial_number = 1;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard* updated_atom_card = new PdbAtomCard();
            updated_atom_card->SetRecordName(atom_card->GetRecordName());
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap updated_atoms;
            int sequence_number = 1;
            bool located = true;
            PdbAtomCard::PdbAtomMap atoms_of_residue = residue->GetAtoms();
            PdbAtom* first_atom_in_residue = (*(atoms_of_residue.begin())).second;
            char residue_chain_id = first_atom_in_residue->GetAtomChainId();
            int residue_sequence_number = first_atom_in_residue->GetAtomResidueSequenceNumber();
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                if(residue_chain_id == atom->GetAtomChainId() && residue_sequence_number == atom->GetAtomResidueSequenceNumber())
                {
                    if(it2 != atoms.begin())
                    {
                        PdbAtom* previous_atom = (*(--it2)).second;
                        it2++;
                        if(previous_atom->GetAtomResidueSequenceNumber() != atom->GetAtomResidueSequenceNumber())
{
                            int diff = atom->GetAtomResidueSequenceNumber() - previous_atom->GetAtomResidueSequenceNumber();
                            if(diff == 1)
                                sequence_number++;
                            else
                                sequence_number += diff;
                        }
                    }
                    else
                        sequence_number = atom->GetAtomResidueSequenceNumber();
                    if(located)
                    {
                        for(PdbAtomCard::PdbAtomMap::iterator it3 = atoms_of_residue.begin(); it3 != atoms_of_residue.end(); it3++)
{
                            PdbAtom* atom_of_residue = (*it3).second;
                            PdbAtom* new_atom = new PdbAtom(serial_number, atom_of_residue->GetAtomName(),atom_of_residue->GetAtomAlternateLocation(),
                                                            atom_of_residue->GetAtomResidueName(),atom_of_residue->GetAtomChainId(), sequence_number,
                                                            atom_of_residue->GetAtomInsertionCode(), atom_of_residue->GetAtomOrthogonalCoordinate(),
                                                            atom_of_residue->GetAtomOccupancy(), atom_of_residue->GetAtomTempretureFactor(),
                                                            atom_of_residue->GetAtomElementSymbol(), atom_of_residue->GetAtomCharge());
                            updated_atoms[serial_number] = new_atom;
                            serial_number++;
                        }
                        sequence_number_mapping_[sequence_number] = iNotSet;
                        sequence_number++;
                        located = false;
                    }
                    if(!located)
                    {
                        PdbAtom* updated_atom = new PdbAtom(serial_number, atom->GetAtomName(),atom->GetAtomAlternateLocation(), atom->GetAtomResidueName(),
                                                            atom->GetAtomChainId(), sequence_number, atom->GetAtomInsertionCode(), atom->GetAtomOrthogonalCoordinate(),
                                                            atom->GetAtomOccupancy(), atom->GetAtomTempretureFactor(), atom->GetAtomElementSymbol(), atom->GetAtomCharge());
                        updated_atoms[serial_number] = updated_atom;
                        serial_number++;
                        if(sequence_number != atom->GetAtomResidueSequenceNumber())
                            sequence_number_mapping_[sequence_number] = atom->GetAtomResidueSequenceNumber();
                    }
                }
                else
                {
                    if(it2 != atoms.begin())
                    {
                        PdbAtom* previous_atom = (*(--it2)).second;
                        it2++;
                        if(previous_atom->GetAtomResidueSequenceNumber() != atom->GetAtomResidueSequenceNumber())
{
                            int diff = atom->GetAtomResidueSequenceNumber() - previous_atom->GetAtomResidueSequenceNumber();
                            if(diff == 1)
                                sequence_number++;
                            else
                                sequence_number += diff;
                        }
                    }
                    else
                        sequence_number = atom->GetAtomResidueSequenceNumber();
                    PdbAtom* updated_atom = new PdbAtom(serial_number, atom->GetAtomName(),atom->GetAtomAlternateLocation(), atom->GetAtomResidueName(),
                                                        atom->GetAtomChainId(), sequence_number, atom->GetAtomInsertionCode(), atom->GetAtomOrthogonalCoordinate(),
                                                        atom->GetAtomOccupancy(), atom->GetAtomTempretureFactor(), atom->GetAtomElementSymbol(), atom->GetAtomCharge());
                    updated_atoms[serial_number] = updated_atom;
                    serial_number++;
                    if(sequence_number != atom->GetAtomResidueSequenceNumber())
                        sequence_number_mapping_[sequence_number] = atom->GetAtomResidueSequenceNumber();
                }
            }
            updated_atom_card->SetAtoms(updated_atoms);
            updated_atom_cards.push_back(updated_atom_card);
            serial_number++;
        }
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        PdbModelResidueSet::HeterogenAtomCardVector updated_heterogen_atom_cards;
        for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
        {
            PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
            PdbHeterogenAtomCard* updated_heterogen_atom_card = new PdbHeterogenAtomCard();
            updated_heterogen_atom_card->SetRecordName(heterogen_atom_card->GetRecordName());
            PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
            PdbHeterogenAtomCard::PdbHeterogenAtomMap updated_heterogen_atoms;
            for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
            {
                PdbAtom* heterogen_atom = (*it2).second;
                PdbAtom* updated_heterogen_atom = new PdbAtom(serial_number, heterogen_atom->GetAtomName(),heterogen_atom->GetAtomAlternateLocation(),
                                                              heterogen_atom->GetAtomResidueName(), heterogen_atom->GetAtomChainId(), heterogen_atom->GetAtomResidueSequenceNumber(),
                                                              heterogen_atom->GetAtomInsertionCode(), heterogen_atom->GetAtomOrthogonalCoordinate(),
                                                              heterogen_atom->GetAtomOccupancy(), heterogen_atom->GetAtomTempretureFactor(),
                                                              heterogen_atom->GetAtomElementSymbol(), heterogen_atom->GetAtomCharge());
                updated_heterogen_atoms[serial_number] = updated_heterogen_atom;
                serial_number++;
            }
            updated_heterogen_atom_card->SetHeterogenAtoms(updated_heterogen_atoms);
            updated_heterogen_atom_cards.push_back(updated_heterogen_atom_card);
        }
        updated_residue_set->SetAtoms(updated_atom_cards);
        updated_residue_set->SetHeterogenAtoms(updated_heterogen_atom_cards);
        updated_model->SetModelResidueSet(updated_residue_set);
        updated_models[updated_model->GetModelSerialNumber()] = updated_model;
    }
    models_->SetModels(updated_models);
}
void PdbFile::InsertResidueBeforeWithTheGivenModelNumber (PdbAtomCard * residue, int model_number = 1)
Definition at line 2200 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomCharge(), PdbFileSpace::PdbAtom::GetAtomElementSymbol(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomName(), PdbFileSpace::PdbAtom::GetAtomOccupancy(), PdbFileSpace::PdbAtom::GetAtomOrthogonalCoordinate(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomTempretureFactor(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbModel::GetModelSerialNumber(), PdbFileSpace::PdbAtomCard::GetRecordName(), PdbFileSpace::PdbHeterogenAtomCard::GetRecordName(), gmml::iNotSet, PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbHeterogenAtomCard::SetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), PdbFileSpace::PdbModel::SetModelResidueSet(), PdbFileSpace::PdbModel::SetModelSerialNumber(), PdbFileSpace::PdbAtomCard::SetRecordName(), and PdbFileSpace::PdbHeterogenAtomCard::SetRecordName().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChainsWithTheGivenModelNumber(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    PdbModelCard::PdbModelMap models = models_->GetModels();
    if(models.size() != 0)
    {
        PdbModel* model = models[model_number];
        PdbModelCard::PdbModelMap updated_models;
        PdbModel* updated_model = new PdbModel();
        updated_model->SetModelSerialNumber(model->GetModelSerialNumber());
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet* updated_residue_set = new PdbModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards;
        int serial_number = 1;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard* updated_atom_card = new PdbAtomCard();
            updated_atom_card->SetRecordName(atom_card->GetRecordName());
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap updated_atoms;
            int sequence_number = 1;
            bool located = true;
            PdbAtomCard::PdbAtomMap atoms_of_residue = residue->GetAtoms();
            PdbAtom* first_atom_in_residue = (*(atoms_of_residue.begin())).second;
            char residue_chain_id = first_atom_in_residue->GetAtomChainId();
            int residue_sequence_number = first_atom_in_residue->GetAtomResidueSequenceNumber();
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                if(residue_chain_id == atom->GetAtomChainId() && residue_sequence_number == atom->GetAtomResidueSequenceNumber())
                {
                    if(it2 != atoms.begin())
                    {
                        PdbAtom* previous_atom = (*(--it2)).second;
                        it2++;
                        if(previous_atom->GetAtomResidueSequenceNumber() != atom->GetAtomResidueSequenceNumber())
{
                            int diff = atom->GetAtomResidueSequenceNumber() - previous_atom->GetAtomResidueSequenceNumber();
                            if(diff == 1)
                                sequence_number++;
                            else
                                sequence_number += diff;
                        }
                    }
                    else
                        sequence_number = atom->GetAtomResidueSequenceNumber();
                    if(located)
                    {
                        for(PdbAtomCard::PdbAtomMap::iterator it3 = atoms_of_residue.begin(); it3 != atoms_of_residue.end(); it3++)
{
                            PdbAtom* atom_of_residue = (*it3).second;
                            PdbAtom* new_atom = new PdbAtom(serial_number, atom_of_residue->GetAtomName(),atom_of_residue->GetAtomAlternateLocation(),
                                                            atom_of_residue->GetAtomResidueName(),atom_of_residue->GetAtomChainId(), sequence_number,
                                                            atom_of_residue->GetAtomInsertionCode(), atom_of_residue->GetAtomOrthogonalCoordinate(),
                                                            atom_of_residue->GetAtomOccupancy(), atom_of_residue->GetAtomTempretureFactor(),
                                                            atom_of_residue->GetAtomElementSymbol(), atom_of_residue->GetAtomCharge());
                            updated_atoms[serial_number] = new_atom;
                            serial_number++;
                        }
                        sequence_number_mapping_[sequence_number] = iNotSet;
                        sequence_number++;
                        located = false;
                    }
                    if(!located)
                    {
                        PdbAtom* updated_atom = new PdbAtom(serial_number, atom->GetAtomName(),atom->GetAtomAlternateLocation(), atom->GetAtomResidueName(),
                                                            atom->GetAtomChainId(), sequence_number, atom->GetAtomInsertionCode(), atom->GetAtomOrthogonalCoordinate(),
                                                            atom->GetAtomOccupancy(), atom->GetAtomTempretureFactor(), atom->GetAtomElementSymbol(), atom->GetAtomCharge());
                        updated_atoms[serial_number] = updated_atom;
                        serial_number++;
                        if(sequence_number != atom->GetAtomResidueSequenceNumber())
                            sequence_number_mapping_[sequence_number] = atom->GetAtomResidueSequenceNumber();
                    }
                }
                else
                {
                    if(it2 != atoms.begin())
                    {
                        PdbAtom* previous_atom = (*(--it2)).second;
                        it2++;
                        if(previous_atom->GetAtomResidueSequenceNumber() != atom->GetAtomResidueSequenceNumber())
{
                            int diff = atom->GetAtomResidueSequenceNumber() - previous_atom->GetAtomResidueSequenceNumber();
                            if(diff == 1)
                                sequence_number++;
                            else
                                sequence_number += diff;
                        }
                    }
                    else
                        sequence_number = atom->GetAtomResidueSequenceNumber();
                    PdbAtom* updated_atom = new PdbAtom(serial_number, atom->GetAtomName(),atom->GetAtomAlternateLocation(), atom->GetAtomResidueName(),
                                                        atom->GetAtomChainId(), sequence_number, atom->GetAtomInsertionCode(), atom->GetAtomOrthogonalCoordinate(),
                                                        atom->GetAtomOccupancy(), atom->GetAtomTempretureFactor(), atom->GetAtomElementSymbol(), atom->GetAtomCharge());
                    updated_atoms[serial_number] = updated_atom;
                    serial_number++;
                    if(sequence_number != atom->GetAtomResidueSequenceNumber())
                        sequence_number_mapping_[sequence_number] = atom->GetAtomResidueSequenceNumber();
                }
            }
            updated_atom_card->SetAtoms(updated_atoms);
            updated_atom_cards.push_back(updated_atom_card);
            serial_number++;
        }
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        PdbModelResidueSet::HeterogenAtomCardVector updated_heterogen_atom_cards;
        for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
        {
            PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
            PdbHeterogenAtomCard* updated_heterogen_atom_card = new PdbHeterogenAtomCard();
            updated_heterogen_atom_card->SetRecordName(heterogen_atom_card->GetRecordName());
            PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
            PdbHeterogenAtomCard::PdbHeterogenAtomMap updated_heterogen_atoms;
            for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
            {
                PdbAtom* heterogen_atom = (*it2).second;
                PdbAtom* updated_heterogen_atom = new PdbAtom(serial_number, heterogen_atom->GetAtomName(),heterogen_atom->GetAtomAlternateLocation(),
                                                              heterogen_atom->GetAtomResidueName(), heterogen_atom->GetAtomChainId(), heterogen_atom->GetAtomResidueSequenceNumber(),
                                                              heterogen_atom->GetAtomInsertionCode(), heterogen_atom->GetAtomOrthogonalCoordinate(),
                                                              heterogen_atom->GetAtomOccupancy(), heterogen_atom->GetAtomTempretureFactor(),
                                                              heterogen_atom->GetAtomElementSymbol(), heterogen_atom->GetAtomCharge());
                updated_heterogen_atoms[serial_number] = updated_heterogen_atom;
                serial_number++;
            }
            updated_heterogen_atom_card->SetHeterogenAtoms(updated_heterogen_atoms);
            updated_heterogen_atom_cards.push_back(updated_heterogen_atom_card);
        }
        updated_residue_set->SetAtoms(updated_atom_cards);
        updated_residue_set->SetHeterogenAtoms(updated_heterogen_atom_cards);
        updated_model->SetModelResidueSet(updated_residue_set);
        updated_models[updated_model->GetModelSerialNumber()] = updated_model;
        models_->SetModels(updated_models);
    }
}
bool PdbFile::ParseAuthorCard (std::ifstream & stream, std::string & line)
Definition at line 3519 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Author card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("AUTHOR") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Author card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    return true;
}
bool PdbFile::ParseCards (std::ifstream & in_stream)
Unable to read file
Definition at line 2853 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    string line;
    /// Unable to read file
    if (!getline(in_stream, line))
    {
        cout << "Wrong input file format" << endl;
        throw PdbFileProcessingException("Error reading file");
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("HEADER") == 0)
    {
        if(!ParseHeaderCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("OBSLTE") == 0)
    {
        if(!ParseObsoleteCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("TITLE") == 0)
    {
        if(!ParseTitleCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("SPLIT") == 0)
    {
        if(!ParseSplitCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("CAVEAT") == 0)
    {
        if(!ParseCaveatCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("COMPND") == 0)
    {
        if(!ParseCompoundCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("SOURCE") == 0)
    {
        if(!ParseSourceCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("KEYWDS") == 0)
    {
        if(!ParseKeywordCard(in_stream, line))
                return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("EXPDTA") == 0)
    {
        if(!ParseExpirationDateCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("NUMMDL") == 0)
    {
        if(!ParseNumModelCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("MDLTYP") == 0)
    {
        if(!ParseModelTypeCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("AUTHOR") == 0)
    {
        if(!ParseAuthorCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("REVDAT") == 0)
    {
        if(!ParseRevisionDateCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("SPRSDE") == 0)
    {
        if(!ParseSupersededEntriesCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("JRNL") == 0)
    {
        if(!ParseJournalCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("REMARK") == 0)
    {
        if(!ParseRemarkCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.find("DBREF") != string::npos)
    {
        if(!ParseDatabaseReferenceCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("SEQADV") == 0)
    {
        if(!ParseSequenceAdvancedCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("SEQRES") == 0)
    {
        if(!ParseSequenceResidueCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("MODRES") == 0)
    {
        if(!ParseModificationResidueCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("HET") == 0)
    {
        if(!ParseHeterogenCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("HETNAM") == 0)
    {
        if(!ParseHeterogenNameCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("HETSYN") == 0)
    {
        if(!ParseHeterogenSynonymCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("FORMUL") == 0)
    {
        if(!ParseFormulaCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("HELIX") == 0)
    {
        if(!ParseHelixCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("SHEET") == 0)
    {
        if(!ParseSheetCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("SSBOND") == 0)
    {
        if(!ParseDisulfideBondCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("LINK") == 0)
    {
        if(!ParseLinkCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("CISPEP") == 0)
    {
        if(!ParseCISPeptideCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("SITE") == 0)
    {
        if(!ParseSiteCard(in_stream, line))
           return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("CRYST1") == 0)
    {
        if(!ParseCrystallographyCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.find("ORIGX") != string::npos)
    {
        if(!ParseOriginCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.find("SCALE") != string::npos)
    {
        if(!ParseScaleCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.find("MTRIX") != string::npos)
    {
        if(!ParseMatrixCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("MODEL") == 0 || record_name.compare("ATOM") == 0 || record_name.compare("HETATM") == 0)
    {
        if(!ParseModelCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("CONECT") == 0)
    {
        if(!ParseConnectivityCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.compare("MODEL") == 0)
    {
        cout << "Multiple connect card between model cards --> Unexpected entry"  << endl;
        return false;
    }
    if(record_name.compare("MASTER") == 0)
    {
        if(!ParseMasterCard(in_stream, line))
            return false;
    }
    record_name = line.substr(0,6);
    record_name = Trim(record_name);
    if(record_name.find("END") != string::npos || record_name.compare("END") == 0)
    {
        if(!ParseEndCard(in_stream, line))
            return false;
        return true;
    }
    else
    {
        cout << "Wrong input file format" << endl;
        return false;
    }
    return true;
}
bool PdbFile::ParseCaveatCard (std::ifstream & stream, std::string & line)
Definition at line 3282 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Caveat card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("CAVEAT") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Caveat card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    return true;
}
bool PdbFile::ParseCISPeptideCard (std::ifstream & stream, std::string & line)
Definition at line 4100 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "CIS peptide card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("CISPEP") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "CIS peptide card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    return true;
}
bool PdbFile::ParseCompoundCard (std::ifstream & stream, std::string & line)
Definition at line 3315 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Compound card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("COMPND") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Compound card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    compound_ = new PdbCompoundCard(stream_block);
    return true;
}
bool PdbFile::ParseConnectivityCard (std::ifstream & stream, std::string & line)
Definition at line 4346 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Connectivity card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("CONECT") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Connectivity card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    connectivities_ = new PdbConnectCard(stream_block);
    return true;
}
bool PdbFile::ParseCrystallographyCard (std::ifstream & stream, std::string & line)
Definition at line 4168 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Crystallography card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("CRYST1") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Crystallography card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    crystallography_ = new PdbCrystallographicCard(stream_block);
    return true;
}
bool PdbFile::ParseDatabaseReferenceCard (std::ifstream & stream, std::string & line)
Definition at line 3684 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "database reference card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("DBREF") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "database reference card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    return true;
}
bool PdbFile::ParseDisulfideBondCard (std::ifstream & stream, std::string & line)
Definition at line 4030 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Disulfide bond card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("SSBOND") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Disulfide bond card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    disulfide_bonds_ = new PdbDisulfideBondCard(stream_block);
    return true;
}
bool PdbFile::ParseEndCard (std::ifstream & stream, std::string & line)
Definition at line 4414 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "End of file" << endl;
        return true;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.find("END") != string::npos || record_name.compare("END") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "End of file" << endl;
            return true;
        }
    }
    return true;
}
bool PdbFile::ParseExpirationDateCard (std::ifstream & stream, std::string & line)
Definition at line 3416 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Expiration date card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("EXPDTA") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Expiration date card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    return true;
}
bool PdbFile::ParseFormulaCard (std::ifstream & stream, std::string & line)
Definition at line 3925 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Formula card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("FORMUL") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Formula card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    formulas_ = new PdbFormulaCard(stream_block);
    return true;
}
bool PdbFile::ParseHeaderCard (std::ifstream & stream, std::string & line)
Definition at line 3146 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Header card corupption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("HEADER") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Header card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    header_ = new PdbHeaderCard(stream_block);
    return true;
}
bool PdbFile::ParseHelixCard (std::ifstream & stream, std::string & line)
Definition at line 3960 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Helix card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("HELIX") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Helix card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    helixes_ = new PdbHelixCard(stream_block);
    return true;
}
bool PdbFile::ParseHeterogenCard (std::ifstream & stream, std::string & line)
Definition at line 3820 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Heterogen card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("HET") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Heterogen card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    heterogens_ = new PdbHeterogenCard(stream_block);
    return true;
}
bool PdbFile::ParseHeterogenNameCard (std::ifstream & stream, std::string & line)
Definition at line 3855 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Heterogen name card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("HETNAM") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Heterogen name card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    heterogens_name_ = new PdbHeterogenNameCard(stream_block);
    return true;
}
bool PdbFile::ParseHeterogenSynonymCard (std::ifstream & stream, std::string & line)
Definition at line 3890 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Heterogen synonym card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("HETSYN") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Heterogen synonym card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    heterogen_synonyms_ = new PdbHeterogenSynonymCard(stream_block);
    return true;
}
bool PdbFile::ParseJournalCard (std::ifstream & stream, std::string & line)
Definition at line 3618 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Journal card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("JRNL") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Journal card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    return true;
}
bool PdbFile::ParseKeywordCard (std::ifstream & stream, std::string & line)
Definition at line 3383 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Keyword card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("KEYWDS") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Keyword card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    return true;
}
bool PdbFile::ParseLinkCard (std::ifstream & stream, std::string & line)
Definition at line 4065 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Link card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("LINK") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Link card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    links_ = new PdbLinkCard(stream_block);
    return true;
}
bool PdbFile::ParseMasterCard (std::ifstream & stream, std::string & line)
Definition at line 4381 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Master card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("MASTER") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Master card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    return true;
}
bool PdbFile::ParseMatrixCard (std::ifstream & stream, std::string & line)
Definition at line 4273 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Matrix card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,5);
    record_name = Trim(record_name);
    while(record_name.compare("MTRIX") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,5);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Matrix card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    matrices_ = new PdbMatrixNCard(stream_block);
    return true;
}
bool PdbFile::ParseModelCard (std::ifstream & stream, std::string & line)
Definition at line 4308 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Model card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("MODEL") == 0 || record_name.compare("ATOM") == 0 || record_name.compare("ANISOU") == 0
          || record_name.compare("TER") == 0 || record_name.compare("HETATM") == 0 || record_name.compare("ENDMDL") == 0)
//          || record_name.find("TER") != string::npos || record_name.find("ENDMDL") != string::npos)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Model card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    // Model card
    models_ = new PdbModelCard(stream_block);
    return true;
}
bool PdbFile::ParseModelTypeCard (std::ifstream & stream, std::string & line)
Definition at line 3484 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Model type card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("MDLTYP") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Model type card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    model_type_ = new PdbModelTypeCard(stream_block);
    return true;
}
bool PdbFile::ParseModificationResidueCard (std::ifstream & stream, std::string & line)
Definition at line 3785 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Modification residue card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("MODRES") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Modification residue card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    residue_modification_ = new PdbResidueModificationCard(stream_block);
    return true;
}
bool PdbFile::ParseNumModelCard (std::ifstream & stream, std::string & line)
Definition at line 3449 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Number of model card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("NUMMDL") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Number of model card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    number_of_models_ = new PdbNumModelCard(stream_block);
    return true;
}
bool PdbFile::ParseObsoleteCard (std::ifstream & stream, std::string & line)
Definition at line 3181 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Obsolete card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("OBSLTE") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
        line = ExpandLine(line, iPdbLineLength);
        record_name = line.substr(0,6);
        record_name = Trim(record_name);
        }
        else
        {
            cout << "Obsolete card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    return true;
}
bool PdbFile::ParseOriginCard (std::ifstream & stream, std::string & line)
Definition at line 4203 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Origin card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,5);
    record_name = Trim(record_name);
    while(record_name.compare("ORIGX") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,5);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Origin card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    origins_ = new PdbOriginXnCard(stream_block);
    return true;
}
bool PdbFile::ParseRemarkCard (std::ifstream & stream, std::string & line)
Definition at line 3651 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Remark card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("REMARK") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Remark card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    return true;
}
bool PdbFile::ParseRevisionDateCard (std::ifstream & stream, std::string & line)
Definition at line 3552 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Revision date card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("REVDAT") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Revision date card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    return true;
}
bool PdbFile::ParseScaleCard (std::ifstream & stream, std::string & line)
Definition at line 4238 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Scale card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,5);
    record_name = Trim(record_name);
    while(record_name.compare("SCALE") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,5);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Scale card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    scales_ = new PdbScaleNCard(stream_block);
    return true;
}
bool PdbFile::ParseSequenceAdvancedCard (std::ifstream & stream, std::string & line)
Definition at line 3717 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Sequence advanced card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("SEQADV") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Sequence advanced card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    return true;
}
bool PdbFile::ParseSequenceResidueCard (std::ifstream & stream, std::string & line)
Definition at line 3750 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Sequence residue card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("SEQRES") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Sequence residue card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    residues_sequence_ = new PdbResidueSequenceCard(stream_block);
    return true;
}
bool PdbFile::ParseSheetCard (std::ifstream & stream, std::string & line)
Definition at line 3995 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Sheet card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("SHEET") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Sheet card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    sheets_ = new PdbSheetCard(stream_block);
    return true;
}
bool PdbFile::ParseSiteCard (std::ifstream & stream, std::string & line)
Definition at line 4133 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Site card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("SITE") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Site card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    sites_ = new PdbSiteCard(stream_block);
    return true;
}
bool PdbFile::ParseSourceCard (std::ifstream & stream, std::string & line)
Definition at line 3350 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Source card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("SOURCE") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Source card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    return true;
}
bool PdbFile::ParseSplitCard (std::ifstream & stream, std::string & line)
Definition at line 3249 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Split card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("SPLIT") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Split card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    return true;
}
bool PdbFile::ParseSupersededEntriesCard (std::ifstream & stream, std::string & line)
Definition at line 3585 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Superseded entries card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("SPRSDE") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Superseded entries card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    return true;
}
bool PdbFile::ParseTitleCard (std::ifstream & stream, std::string & line)
Definition at line 3214 of file pdbfile.cc.
References gmml::ExpandLine(), gmml::iPdbLineLength, and gmml::Trim().
{
    stringstream stream_block;
    stream_block << line << endl;
    if(!getline(stream, line))
    {
        cout << "Title card corruption" << endl;
        cout << "Wrong input file format" << endl;
        return false;
    }
    line = ExpandLine(line, iPdbLineLength);
    string record_name = line.substr(0,6);
    record_name = Trim(record_name);
    while(record_name.compare("TITLE") == 0)
    {
        stream_block << line << endl;
        if(getline(stream, line))
        {
            line = ExpandLine(line, iPdbLineLength);
            record_name = line.substr(0,6);
            record_name = Trim(record_name);
        }
        else
        {
            cout << "Title card corruption" << endl;
            cout << "Wrong input file format" << endl;
            return false;
        }
    }
    title_ = new PdbTitleCard(stream_block);
    return true;
}
void PdbFile::Print (std::ostream & out = std::cout)
Definition at line 6670 of file pdbfile.cc.
{
    if(header_ != NULL)
    {
        out << "******************************* HEADER *******************************" << endl;
        header_->Print(out);
    }
    if(title_ != NULL)
    {
        out << "******************************** TITLE *******************************" << endl;
        title_->Print(out);
    }
    if(compound_ != NULL)
    {
        out << "****************************** COMPOUND ******************************" << endl;
        compound_->Print(out);
    }
    if(number_of_models_ != NULL)
    {
        out << "************************** NUMBER OF MODELS **************************" << endl;
        number_of_models_->Print(out);
    }
    if(model_type_ != NULL)
    {
        out << "***************************** MODEL TYPE *****************************" << endl;
        model_type_->Print(out);
    }
    if(residues_sequence_ != NULL)
    {
        out << "************************** RESIDUE SEQUENCE **************************" << endl;
        residues_sequence_->Print(out);
    }
    if(residue_modification_ != NULL)
    {
        out << "************************ RESIDUE MODIFICATION ************************" << endl;
        residue_modification_->Print(out);
    }
    if(heterogens_ != NULL)
    {
        out << "***************************** HETEROGEN ******************************" << endl;
        heterogens_->Print(out);
    }
    if(heterogens_name_ != NULL)
    {
        out << "*************************** HETEROGEN NAME ***************************" << endl;
        heterogens_name_->Print(out);
    }
    if(heterogen_synonyms_ != NULL)
    {
        out << "************************** HETEROGEN SYNONYM *************************" << endl;
        heterogen_synonyms_->Print(out);
    }
    if(formulas_ != NULL)
    {
        out << "******************************* FORMULA ******************************" << endl;
        formulas_->Print(out);
    }
    if(helixes_ != NULL)
    {
        out << "******************************** HELIX *******************************" << endl;
        helixes_->Print(out);
    }
    if(sheets_ != NULL)
    {
        out << "******************************** SHEET *******************************" << endl;
        sheets_->Print(out);
    }
    if(disulfide_bonds_ != NULL)
    {
        out << "*************************** DISULFIDE BOND ***************************" << endl;
        disulfide_bonds_->Print(out);
    }
    if(links_ != NULL)
    {
        out << "******************************** LINK ********************************" << endl;
        links_->Print(out);
    }
    if(sites_ != NULL)
    {
        out << "******************************** SITE ********************************" << endl;
        sites_->Print(out);
    }
    if(crystallography_ != NULL)
    {
        out << "************************** CRYSTALLOGRAPHIC **************************" << endl;
        crystallography_->Print(out);
    }
    if(origins_ != NULL)
    {
        out << "******************************* ORIGIN *******************************" << endl;
        origins_->Print(out);
    }
    if(scales_ != NULL)
    {
        out << "******************************** SCALE *******************************" << endl;
        scales_->Print(out);
    }
    if(matrices_ != NULL)
    {
        out << "******************************* MATRIX *******************************" << endl;
        matrices_->Print(out);
    }
    if(models_ != NULL)
    {
        out << "******************************* MODEL ********************************" << endl;
        models_->Print(out);
    }
    if(connectivities_ != NULL)
    {
        out << "******************************* CONNECT ******************************" << endl;
        connectivities_->Print(out);
    }
}
bool PdbFile::Read (std::ifstream & in_file)
Definition at line 2847 of file pdbfile.cc.
{
    if(!this->ParseCards(in_file))
        return false;
}
void PdbFile::ResolveAuthorCard (std::ofstream & stream)
Definition at line 5198 of file pdbfile.cc.
{
}
void PdbFile::ResolveCards (std::ofstream & out_stream)
Definition at line 4487 of file pdbfile.cc.
{
    if(this->header_ != NULL)
    {
        this->ResolveHeaderCard(out_stream);
    }
    if(this->title_ != NULL)
    {
        this->ResolveTitleCard(out_stream);
    }
    if(this->compound_ != NULL)
    {
        this->ResolveCompoundCard(out_stream);
    }
    if(this->number_of_models_ != NULL)
    {
        this->ResolveCompoundCard(out_stream);
    }
    if(this->model_type_ != NULL)
    {
        this->ResolveNumModelCard(out_stream);
    }
    if(this->residues_sequence_ != NULL)
    {
        this->ResolveSequenceResidueCard(out_stream);
    }
    if(this->residue_modification_ != NULL)
    {
        this->ResolveModificationResidueCard(out_stream);
    }
    if(this->heterogens_ != NULL)
    {
        this->ResolveHeterogenCard(out_stream);
    }
    if(this->heterogens_name_ != NULL)
    {
        this->ResolveHeterogenNameCard(out_stream);
    }
    if(this->heterogen_synonyms_ != NULL)
    {
        this->ResolveHeterogenSynonymCard(out_stream);
    }
    if(this->formulas_ != NULL)
    {
        this->ResolveFormulaCard(out_stream);
    }
    if(this->helixes_ != NULL)
    {
        this->ResolveHelixCard(out_stream);
    }
    if(this->sheets_ != NULL)
    {
        this->ResolveSheetCard(out_stream);
    }
    if(this->disulfide_bonds_ != NULL)
    {
        this->ResolveDisulfideBondCard(out_stream);
    }
    if(this->links_ != NULL)
    {
        this->ResolveLinkCard(out_stream);
    }
    if(this->sites_ != NULL)
    {
        this->ResolveSiteCard(out_stream);
    }
    if(this->crystallography_ != NULL)
    {
        this->ResolveCrystallographyCard(out_stream);
    }
    if(this->origins_ != NULL)
    {
        this->ResolveOriginCard(out_stream);
    }
    if(this->scales_ != NULL)
    {
        this->ResolveScaleCard(out_stream);
    }
    if(this->matrices_ != NULL)
    {
        this->ResolveMatrixCard(out_stream);
    }
    if(this->models_ != NULL)
    {
        this->ResolveModelCard(out_stream);
    }
    if(this->connectivities_ != NULL)
    {
        this->ResolveConnectivityCard(out_stream);
    }
    this->ResolveEndCard(out_stream);
}
void PdbFile::ResolveCardsWithTheGivenModelNumber (std::ofstream & out_stream, int model_number = 1)
Definition at line 4580 of file pdbfile.cc.
{
    if(this->header_ != NULL)
    {
        this->ResolveHeaderCard(out_stream);
    }
    if(this->title_ != NULL)
    {
        this->ResolveTitleCard(out_stream);
    }
    if(this->compound_ != NULL)
    {
        this->ResolveCompoundCard(out_stream);
    }
    if(this->number_of_models_ != NULL)
    {
        this->ResolveCompoundCard(out_stream);
    }
    if(this->model_type_ != NULL)
    {
        this->ResolveNumModelCard(out_stream);
    }
    if(this->residues_sequence_ != NULL)
    {
        this->ResolveSequenceResidueCard(out_stream);
    }
    if(this->residue_modification_ != NULL)
    {
        this->ResolveModificationResidueCard(out_stream);
    }
    if(this->heterogens_ != NULL)
    {
        this->ResolveHeterogenCard(out_stream);
    }
    if(this->heterogens_name_ != NULL)
    {
        this->ResolveHeterogenNameCard(out_stream);
    }
    if(this->heterogen_synonyms_ != NULL)
    {
        this->ResolveHeterogenSynonymCard(out_stream);
    }
    if(this->formulas_ != NULL)
    {
        this->ResolveFormulaCard(out_stream);
    }
    if(this->helixes_ != NULL)
    {
        this->ResolveHelixCard(out_stream);
    }
    if(this->sheets_ != NULL)
    {
        this->ResolveSheetCard(out_stream);
    }
    if(this->disulfide_bonds_ != NULL)
    {
        this->ResolveDisulfideBondCard(out_stream);
    }
    if(this->links_ != NULL)
    {
        this->ResolveLinkCard(out_stream);
    }
    if(this->sites_ != NULL)
    {
        this->ResolveSiteCard(out_stream);
    }
    if(this->crystallography_ != NULL)
    {
        this->ResolveCrystallographyCard(out_stream);
    }
    if(this->origins_ != NULL)
    {
        this->ResolveOriginCard(out_stream);
    }
    if(this->scales_ != NULL)
    {
        this->ResolveScaleCard(out_stream);
    }
    if(this->matrices_ != NULL)
    {
        this->ResolveMatrixCard(out_stream);
    }
    if(this->models_ != NULL)
    {
        this->ResolveModelCardWithTheGivenModelNumber(out_stream, model_number);
    }
    if(this->connectivities_ != NULL)
    {
        this->ResolveConnectivityCard(out_stream);
    }
    this->ResolveEndCard(out_stream);
}
void PdbFile::ResolveCaveatCard (std::ofstream & stream)
Definition at line 4734 of file pdbfile.cc.
{
}
void PdbFile::ResolveCISPeptideCard (std::ofstream & stream)
Definition at line 5871 of file pdbfile.cc.
{
}
void PdbFile::ResolveCompoundCard (std::ofstream & stream)
Molecule name specification
Molecule chain ids specification
Fragment specification
Molecule synonyms specification
Enzyme commission numbers specification
Engineered specification
Mutation specification
Other comments specification
Definition at line 4739 of file pdbfile.cc.
References PdbFileSpace::PdbCompoundSpecification::GetChainIds(), PdbFileSpace::PdbCompoundSpecification::GetComments(), PdbFileSpace::PdbCompoundSpecification::GetEnzymeCommissionNumbers(), PdbFileSpace::PdbCompoundSpecification::GetFragment(), PdbFileSpace::PdbCompoundSpecification::GetHasMutation(), PdbFileSpace::PdbCompoundSpecification::GetIsEngineered(), PdbFileSpace::PdbCompoundSpecification::GetMoleculeId(), PdbFileSpace::PdbCompoundSpecification::GetMoleculeName(), and PdbFileSpace::PdbCompoundSpecification::GetMoleculeSynonyms().
{
    const int MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE = 70;
    stream << left << setw(6) << compound_->GetRecordName()
           << left << setw(1) << " "
           << right << setw(3) << " ";
    PdbCompoundCard::PdbCompoundSpecificationMap compound_specification_map = compound_->GetCompoundSpecifications();
    if((*(compound_specification_map.begin())).second->GetMoleculeId() != "")
    {
        stringstream ss;
        ss << "MOL_ID: " << (*(compound_specification_map.begin())).second->GetMoleculeId() << ";";
        stream << left << setw(70) << ss.str() << endl;
    }
    else
    {
        stringstream ss;
        ss << " UNKNOWN;";
        stream << left << setw(70) << ss.str() << endl;
    }
    bool first = true;
    int counter = 2;
    for(PdbCompoundCard::PdbCompoundSpecificationMap::iterator it = compound_specification_map.begin(); it != compound_specification_map.end(); it++)
    {
        PdbCompoundSpecification* compound_specification = (*it).second;
        if(!first)
        {
            if(compound_specification->GetMoleculeId() != "")
            {
                stringstream ss;
                ss << " MOL_ID: " << compound_specification->GetMoleculeId() << ";";
                stream << left << setw(6) << compound_->GetRecordName()
                       << left << setw(1) << " "
                       << right << setw(3) << counter
                       << left << setw(70) << ss.str() << endl;
                counter++;
            }
            else
            {
                stringstream ss;
                ss << " UNKNOWN;";
                stream << left << setw(6) << compound_->GetRecordName()
                       << left << setw(1) << " "
                       << right << setw(3) << counter
                       << left << setw(70) << ss.str() << endl;
                counter++;
            }
        }
        /// Molecule name specification
        if(compound_specification->GetMoleculeName() != "")
        {
            stringstream molecule_name;
            molecule_name << " MOLECULE: " << compound_specification->GetMoleculeName() << ";";
            int length = molecule_name.str().length();
            if(length <= MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE)
            {
                stringstream ss;
                ss << molecule_name.str();
                stream << left << setw(6) << compound_->GetRecordName()
                       << left << setw(1) << " "
                       << right << setw(3) << counter
                       << left << setw(70) << ss.str() << endl;
                counter++;
            }
            else
            {
                int number_of_lines = ceil((double)(length) / MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                for(int i = 1; i <= number_of_lines; i++)
                {
                    if(i != number_of_lines)
                    {
                        stringstream ss;
                        ss << molecule_name.str().substr((i-1)*(MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE), MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                        stream << left << setw(6) << compound_->GetRecordName()
                               << left << setw(1) << " "
                               << right << setw(3) << counter
                               << left << setw(70) << ss.str()
                               << endl;
                        counter++;
                    }
                    else
                    {
                        stringstream ss;
                        ss << molecule_name.str().substr((i-1)*(MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE), length - (i-1)*(MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE));
                        stream << left << setw(6) << compound_->GetRecordName()
                               << left << setw(1) << " "
                               << right << setw(3) << counter
                               << left << setw(70) << ss.str()
                               << endl;
                        counter++;
                    }
                }
            }
        }
        /// Molecule chain ids specification
        if(compound_specification->GetChainIds().size() > 0)
        {
            vector<string> chain_ids = compound_specification->GetChainIds();
            stringstream chain_id;
            chain_id << " CHAIN: ";
            for(vector<string>::iterator it1 = chain_ids.begin(); it1 != chain_ids.end(); it1++)
            {
                if(it1 < chain_ids.end()-1)
                    chain_id << (*it1) << ",";
                else
                    chain_id << (*it1);
            }
            chain_id << ";";
            int length = chain_id.str().length();
            if(length <= MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE)
            {
                stringstream ss;
                ss << chain_id.str();
                stream << left << setw(6) << compound_->GetRecordName()
                       << left << setw(1) << " "
                       << right << setw(3) << counter
                       << left << setw(70) << ss.str() << endl;
                counter++;
            }
            else
            {
                int number_of_lines = ceil((double)(length) / MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                for(int i = 1; i <= number_of_lines; i++)
                {
                    if(i != number_of_lines)
                    {
                        stringstream ss;
                        ss << chain_id.str().substr((i-1)*MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE, MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                        stream << left << setw(6) << compound_->GetRecordName()
                               << left << setw(1) << " "
                               << right << setw(3) << counter
                               << left << setw(70) << ss.str() << endl;
                        counter++;
                    }
                    else
                    {
                        stringstream ss;
                        ss << chain_id.str().substr((i-1)*MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE, length - (i-1)*MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                        stream << left << setw(6) << compound_->GetRecordName()
                               << left << setw(1) << " "
                               << right << setw(3) << counter
                               << left << setw(70) << ss.str() << endl;
                        counter++;
                    }
                }
            }
        }
        /// Fragment specification
        if(compound_specification->GetFragment() != "")
        {
            stringstream fragment;
            fragment << " FRAGMENT: " << compound_specification->GetFragment() << ";";
            int length = fragment.str().length();
            if(length <= MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE)
            {
                stringstream ss;
                ss << ss.str();
                stream << left << setw(6) << compound_->GetRecordName()
                       << left << setw(1) << " "
                       << right << setw(3) << counter
                       << left << setw(70) << ss.str() << endl;
                counter++;
            }
            else
            {
                int number_of_lines = ceil((double)(length) / MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                for(int i = 1; i <= number_of_lines; i++)
                {
                    if(i != number_of_lines)
                    {
                        stringstream ss;
                        ss << ss.str().substr((i-1)*MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE, MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                        stream << left << setw(6) << compound_->GetRecordName()
                               << left << setw(1) << " "
                               << right << setw(3) << counter
                               << left << setw(70) << ss.str() << endl;
                        counter++;
                    }
                    else
                    {
                        stringstream ss;
                        ss << ss.str().substr((i-1)*MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE, length - (i-1)*MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                        stream << left << setw(6) << compound_->GetRecordName()
                               << left << setw(1) << " "
                               << right << setw(3) << counter
                               << left << setw(70) << ss.str() << endl;
                        counter++;
                    }
                }
            }
        }
        /// Molecule synonyms specification
        if(compound_specification->GetMoleculeSynonyms().size() > 0)
        {
            vector<string> molecule_synonyms = compound_specification->GetMoleculeSynonyms();
            stringstream synonyms;
            synonyms << " SYNONYM: ";
            for(vector<string>::iterator it1 = molecule_synonyms.begin(); it1 != molecule_synonyms.end(); it1++)
            {
                if(it1 < molecule_synonyms.end()-1)
                    synonyms << (*it1) << ",";
                else
                    synonyms << (*it1);
            }
            synonyms << ";";
            int length = synonyms.str().length();
            if(length <= MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE)
            {
                stringstream ss;
                ss << synonyms.str();
                stream << left << setw(6) << compound_->GetRecordName()
                       << left << setw(1) << " "
                       << right << setw(3) << counter
                       << left << setw(70) << ss.str() << endl;
                counter++;
            }
            else
            {
                int number_of_lines = ceil((double)(length) / MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                for(int i = 1; i <= number_of_lines; i++)
                {
                    if(i != number_of_lines)
                    {
                        stringstream ss;
                        ss << synonyms.str().substr((i-1)*MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE, MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                        stream << left << setw(6) << compound_->GetRecordName()
                               << left << setw(1) << " "
                               << right << setw(3) << counter
                               << left << setw(70) << ss.str() << endl;
                        counter++;
                    }
                    else
                    {
                        stringstream ss;
                        ss << synonyms.str().substr((i-1)*MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE, length - (i-1)*MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                        stream << left << setw(6) << compound_->GetRecordName()
                               << left << setw(1) << " "
                               << right << setw(3) << counter
                               << left << setw(70) << ss.str() << endl;
                        counter++;
                    }
                }
            }
        }
        /// Enzyme commission numbers specification
        if(compound_specification->GetEnzymeCommissionNumbers().size() > 0)
        {
            vector<string> enzyme_commission_numbers = compound_specification->GetEnzymeCommissionNumbers();
            stringstream commission_numbers;
            commission_numbers << " EC: ";
            for(vector<string>::iterator it1 = enzyme_commission_numbers.begin(); it1 != enzyme_commission_numbers.end(); it1++)
            {
                if(it1 < enzyme_commission_numbers.end()-1)
                    commission_numbers << (*it1) << ",";
                else
                    commission_numbers << (*it1);
            }
            commission_numbers << ";";
            int length = commission_numbers.str().length();
            if(length <= MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE)
            {
                stringstream ss;
                ss << commission_numbers.str();
                stream << left << setw(6) << compound_->GetRecordName()
                       << left << setw(1) << " "
                       << right << setw(3) << counter
                       << left << setw(70) << ss.str() << endl;
                counter++;
            }
            else
            {
                int number_of_lines = ceil((double)(length) / MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                for(int i = 1; i <= number_of_lines; i++)
                {
                    if(i != number_of_lines)
                    {
                        stringstream ss;
                        ss << commission_numbers.str().substr((i-1)*MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE, MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                        stream << left << setw(6) << compound_->GetRecordName()
                               << left << setw(1) << " "
                               << right << setw(3) << counter
                               << left << setw(70) << ss.str() << endl;
                        counter++;
                    }
                    else
                    {
                        stringstream ss;
                        ss << commission_numbers.str().substr((i-1)*MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE, length - (i-1)*MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                        stream << left << setw(6) << compound_->GetRecordName()
                               << left << setw(1) << " "
                               << right << setw(3) << counter
                               << left << setw(70) << ss.str() << endl;
                        counter++;
                    }
                }
            }
        }
        /// Engineered specification
        if(compound_specification->GetIsEngineered())
        {
            stringstream ss;
            ss << " ENGINEERED: YES;";
            stream << left << setw(6) << compound_->GetRecordName()
                   << left << setw(1) << " "
                   << right << setw(3) << counter
                   << left << setw(70) << ss.str() << endl;
            counter++;
        }
        /// Mutation specification
        if(compound_specification->GetHasMutation())
        {
            stringstream ss;
            ss << " MUTATION: YES;";
            stream << left << setw(6) << compound_->GetRecordName()
                   << left << setw(1) << " "
                   << right << setw(3) << counter
                   << left << setw(70) << ss.str() << endl;
            counter++;
        }
        /// Other comments specification
        if(compound_specification->GetComments() != "")
        {
            stringstream comments;
            comments << " OTHER_DETAILS: " << compound_specification->GetComments() << ";";
            int length = comments.str().length();
            if(length <= MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE)
            {
                stringstream ss;
                ss << comments.str();
                stream << left << setw(6) << compound_->GetRecordName()
                       << left << setw(1) << " "
                       << right << setw(3) << counter
                       << left << setw(70) << ss.str() << endl;
                counter++;
            }
            else
            {
                int number_of_lines = ceil((double)(length) / MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                for(int i = 1; i <= number_of_lines; i++)
                {
                    if(i != number_of_lines)
                    {
                        stringstream ss;
                        ss << comments.str().substr((i-1)*MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE, MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                        stream << left << setw(6) << compound_->GetRecordName()
                               << left << setw(1) << " "
                               << right << setw(3) << counter
                               << left << setw(70) << ss.str() << endl;
                        counter++;
                    }
                    else
                    {
                        stringstream ss;
                        ss << comments.str().substr((i-1)*MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE, length - (i-1)*MAX_LENGTH_OF_COMPOUND_SPEC_IN_LINE);
                        stream << left << setw(6) << compound_->GetRecordName()
                               << left << setw(1) << " "
                               << right << setw(3) << counter
                               << left << setw(70) << ss.str() << endl;
                        counter++;
                    }
                }
            }
        }
        first = false;
    }
}
void PdbFile::ResolveConnectivityCard (std::ofstream & stream)
Definition at line 6575 of file pdbfile.cc.
References gmml::iNotSet.
{
    PdbConnectCard::BondedAtomsSerialNumbersMap bonded_atoms = connectivities_->GetBondedAtomsSerialNumbers();
    for(PdbConnectCard::BondedAtomsSerialNumbersMap::iterator it = bonded_atoms.begin(); it != bonded_atoms.end(); it++)
    {
        vector<int> bonded_atoms_serial_number = (*it).second;
        int source_atom_serial_number = (*it).first;
        int number_of_bonded_atoms = bonded_atoms_serial_number.size();
        const int MAX_SERIAL_NUMBER_IN_LINE = 4;
        const int SERIAL_NUMBER_LENGTH = 5;
        if(number_of_bonded_atoms <= MAX_SERIAL_NUMBER_IN_LINE)
        {
            stream << left << setw(6) << connectivities_->GetRecordName();
            if(source_atom_serial_number != iNotSet)
                stream << right << setw(5) << source_atom_serial_number;
            else
                stream << right << setw(5) << " ";
            for(vector<int>::iterator it1 = bonded_atoms_serial_number.begin(); it1 != bonded_atoms_serial_number.end(); it1++)
            {
                int serial_number = (*it1);
                if(serial_number != iNotSet)
                    stream << right << setw(5) << serial_number;
                else
                    stream << right << setw(5) << " ";
            }
            if((MAX_SERIAL_NUMBER_IN_LINE-number_of_bonded_atoms)*SERIAL_NUMBER_LENGTH != 0)
                stream << left << setw((MAX_SERIAL_NUMBER_IN_LINE-number_of_bonded_atoms)*SERIAL_NUMBER_LENGTH) << " "
                       << left << setw(49) << " "
                       << endl;
            else
                stream << left << setw(49) << " "
                       << endl;
        }
        else
        {
            int number_of_lines = ceil((double)(number_of_bonded_atoms) / MAX_SERIAL_NUMBER_IN_LINE);
            for(int i = 1; i <= number_of_lines; i++)
            {
                stream << left << setw(6) << connectivities_->GetRecordName();
                if(source_atom_serial_number != iNotSet)
                    stream << right << setw(5) << source_atom_serial_number;
                else
                    stream << right << setw(5) << " ";
                if(i != number_of_lines)
                {
                    for(vector<int>::iterator it1 = bonded_atoms_serial_number.begin() + (i-1) * MAX_SERIAL_NUMBER_IN_LINE;
                        it1 != bonded_atoms_serial_number.begin() + i * MAX_SERIAL_NUMBER_IN_LINE; it1++)
                    {
                        int serial_number = (*it1);
                        if(serial_number != iNotSet)
                            stream << right << setw(5) << serial_number;
                        else
                            stream << right << setw(5) << " ";
                    }
                    stream << left << setw(49) << " "
                           << endl;
                }
                else
                {
                    for(vector<int>::iterator it1 = bonded_atoms_serial_number.begin() + (i-1) * MAX_SERIAL_NUMBER_IN_LINE;
                        it1 != bonded_atoms_serial_number.end(); it1++)
                    {
                        int serial_number = (*it1);
                        if(serial_number != iNotSet)
                            stream << right << setw(5) << serial_number;
                        else
                            stream << right << setw(5) << " ";
                    }
                    if((MAX_SERIAL_NUMBER_IN_LINE-(number_of_bonded_atoms-(i-1)*MAX_SERIAL_NUMBER_IN_LINE))*SERIAL_NUMBER_LENGTH != 0)
                        stream << left << setw((MAX_SERIAL_NUMBER_IN_LINE-number_of_bonded_atoms)*SERIAL_NUMBER_LENGTH) << " "
                               << left << setw(49) << " "
                               << endl;
                    else
                        stream << left << setw(49) << " "
                               << endl;
                }
            }
        }
    }
}
void PdbFile::ResolveCrystallographyCard (std::ofstream & stream)
Definition at line 5998 of file pdbfile.cc.
References gmml::dNotSet, and gmml::iNotSet.
{
    stream << left << setw(6) << crystallography_->GetRecordName();
    if(crystallography_->GetA() != dNotSet)
        stream << right << setw(9) << fixed << setprecision(3) << crystallography_->GetA();
    else
        stream << right << setw(9) << " ";
    if(crystallography_->GetB() != dNotSet)
        stream << right << setw(9) << fixed << setprecision(3) << crystallography_->GetB();
    else
        stream << right << setw(9) << " ";
    if(crystallography_->GetC() != dNotSet)
        stream << right << setw(9) << fixed << setprecision(3) << crystallography_->GetC();
    else
        stream << right << setw(9) << " ";
    if(crystallography_->GetAlpha() != dNotSet)
        stream << right << setw(7) << fixed << setprecision(2) << crystallography_->GetAlpha();
    else
        stream << right << setw(7) << " ";
    if(crystallography_->GetBeta() != dNotSet)
        stream << right << setw(7) << fixed << setprecision(2) << crystallography_->GetBeta();
    else
        stream << right << setw(7) << " ";
    if(crystallography_->GetGamma() != dNotSet)
        stream << right << setw(7) << fixed << setprecision(2) << crystallography_->GetGamma();
    else
        stream << right << setw(7) << " ";
    stream << left << setw(1) << " "
           << left << setw(11) << crystallography_->GetSpaceGroup();
    if(crystallography_->GetZValue() != iNotSet)
        stream << right << setw(4) << crystallography_->GetZValue();
    else
        stream << right << setw(4) << " ";
    stream << left << setw(10) << " "
           << endl;
}
void PdbFile::ResolveDatabaseReferenceCard (std::ofstream & stream)
Definition at line 5223 of file pdbfile.cc.
{
}
void PdbFile::ResolveDisulfideBondCard (std::ofstream & stream)
Definition at line 5768 of file pdbfile.cc.
References gmml::dNotSet, PdbFileSpace::PdbDisulfideResidueBond::GetBondLength(), PdbFileSpace::PdbDisulfideResidueBond::GetResidues(), PdbFileSpace::PdbDisulfideResidueBond::GetSerialNumber(), and gmml::iNotSet.
{
    PdbDisulfideBondCard::DisulfideResidueBondMap disulfide_bond_map = disulfide_bonds_->GetDisulfideResidueBonds();
    for(PdbDisulfideBondCard::DisulfideResidueBondMap::iterator it = disulfide_bond_map.begin(); it != disulfide_bond_map.end(); it++)
    {
        PdbDisulfideResidueBond* disulfide_bonds = (*it).second;
        PdbDisulfideResidueBond::DisulfideResidueVector disulfide_bonds_residues = disulfide_bonds->GetResidues();
        stream << left << setw(6) << disulfide_bonds_->GetRecordName()
               << left << setw(1) << " ";
        if(disulfide_bonds->GetSerialNumber() != iNotSet)
            stream << right << setw(3) << disulfide_bonds->GetSerialNumber();
        else
            stream << right << setw(3) << " ";
        stream << left << setw(1) << " "
               << right << setw(3) << disulfide_bonds_residues.at(0)->GetResidueName()
               << left << setw(1) << " "
               << right << setw(1) << disulfide_bonds_residues.at(0)->GetResidueChainId()
               << left << setw(1) << " ";
        if(disulfide_bonds_residues.at(0)->GetResidueSequenceNumber() != iNotSet)
            stream << right << setw(4) << disulfide_bonds_residues.at(0)->GetResidueSequenceNumber();
        else
            stream << right << setw(4) << " ";
        stream << right << setw(1) << disulfide_bonds_residues.at(0)->GetResidueInsertionCode()
               << left << setw(3) << " "
               << right << setw(3) << disulfide_bonds_residues.at(1)->GetResidueName()
               << left << setw(1) << " "
               << right << setw(1) << disulfide_bonds_residues.at(1)->GetResidueChainId()
               << left << setw(1) << " ";
        if(disulfide_bonds_residues.at(1)->GetResidueSequenceNumber() != iNotSet)
            stream << right << setw(4) << disulfide_bonds_residues.at(1)->GetResidueSequenceNumber();
        else
            stream << right << setw(4) << " ";
        stream << right << setw(1) << disulfide_bonds_residues.at(1)->GetResidueInsertionCode()
               << left << setw(23) << " ";
        if(disulfide_bonds_residues.at(0)->GetSymmetryOperator() != iNotSet)
            stream << right << setw(6) << disulfide_bonds_residues.at(0)->GetSymmetryOperator();
        else
            stream << right << setw(6) << " ";
        stream << left << setw(1) << " ";
        if(disulfide_bonds_residues.at(1)->GetSymmetryOperator() != iNotSet)
            stream << right << setw(6) << disulfide_bonds_residues.at(1)->GetSymmetryOperator();
        else
            stream << right << setw(6) << " ";
        stream << left << setw(1) << " ";
        if(disulfide_bonds->GetBondLength() != dNotSet)
            stream << right << setw(5) << fixed << setprecision(2) << disulfide_bonds->GetBondLength();
        else
            stream << right << setw(5) << " ";
        stream << left << setw(2) << " "
               << endl;
    }
}
void PdbFile::ResolveEndCard (std::ofstream & stream)
Definition at line 6661 of file pdbfile.cc.
{
    stream << left << setw(6) << "END" << left << setw(74) << " " << endl;
}
void PdbFile::ResolveExpirationDateCard (std::ofstream & stream)
Definition at line 5130 of file pdbfile.cc.
{
}
void PdbFile::ResolveFormulaCard (std::ofstream & stream)
Definition at line 5515 of file pdbfile.cc.
References PdbFileSpace::PdbFormula::GetChemicalFormula(), PdbFileSpace::PdbFormula::GetComponentNumber(), PdbFileSpace::PdbFormula::GetHeterogenIdentifier(), and gmml::iNotSet.
{
    PdbFormulaCard::FormulaMap formula_map = formulas_->GetFormulas();
    for(PdbFormulaCard::FormulaMap::iterator it = formula_map.begin(); it != formula_map.end(); it++)
    {
        PdbFormula* formula = (*it).second;
        const int MAX_NAME_LENGTH_IN_LINE = 51;
        if((int)formula->GetChemicalFormula().length() > MAX_NAME_LENGTH_IN_LINE)
        {
            stream << left << setw(6) << formulas_->GetRecordName()
                   << left << setw(2) << " ";
            if(formula->GetComponentNumber() != iNotSet)
                stream << right << setw(2) << formula->GetComponentNumber();
            else
                stream << right << setw(2) << " ";
            stream << left << setw(2) << " "
                   << right << setw(3) << formula->GetHeterogenIdentifier()
                   << left << setw(1) << " "
                   << right << setw(2) << " "
                   << left << setw(1) << " "
                   << left << setw(51) << formula->GetChemicalFormula().substr(0,MAX_NAME_LENGTH_IN_LINE)
                   << left << setw(10) << " "
                   << endl;
            int counter = ceil((double)(formula->GetChemicalFormula().length()) / MAX_NAME_LENGTH_IN_LINE);
            for(int i = 2; i <= counter; i++)
            {
                if(i != counter)
                {
                    stream << left << setw(6) << formulas_->GetRecordName()
                           << left << setw(2) << " ";
                    if(formula->GetComponentNumber() != iNotSet)
                        stream << right << setw(2) << formula->GetComponentNumber();
                    else
                        stream << right << setw(2) << " ";
                    stream << left << setw(2) << " "
                           << right << setw(3) << formula->GetHeterogenIdentifier()
                           << left << setw(1) << " "
                           << right << setw(2) << i
                           << left << setw(1) << " "
                           << left << setw(51) << formula->GetChemicalFormula().substr(MAX_NAME_LENGTH_IN_LINE*(i-1),MAX_NAME_LENGTH_IN_LINE)
                           << left << setw(10) << " "
                           << endl;
                }
                else
                {
                    stream << left << setw(6) << formulas_->GetRecordName()
                           << left << setw(2) << " ";
                    if(formula->GetComponentNumber()!= iNotSet)
                        stream << right << setw(2) << formula->GetComponentNumber();
                    else
                        stream << right << setw(2) << " ";
                    stream << left << setw(2) << " "
                           << right << setw(3) << formula->GetHeterogenIdentifier()
                           << left << setw(1) << " "
                           << right << setw(2) << i
                           << left << setw(1) << " "
                           << left << setw(51) << formula->GetChemicalFormula().substr(MAX_NAME_LENGTH_IN_LINE*(i-1),formula->GetChemicalFormula().length()-MAX_NAME_LENGTH_IN_LINE*(i-1))
                           << left << setw(10) << " "
                           << endl;
                }
            }
        }
        else
        {
            stream << left << setw(6) << formulas_->GetRecordName()
                   << left << setw(2) << " ";
            if(formula->GetComponentNumber() != iNotSet)
                stream << right << setw(2) << formula->GetComponentNumber();
            else
                stream << right << setw(2) << " ";
            stream << left << setw(2) << " "
                   << right << setw(3) << formula->GetHeterogenIdentifier()
                   << left << setw(1) << " "
                   << right << setw(2) << " "
                   << left << setw(1) << " "
                   << left << setw(51) << formula->GetChemicalFormula().substr(0,MAX_NAME_LENGTH_IN_LINE)
                   << left << setw(10) << " "
                   << endl;
        }
    }
}
void PdbFile::ResolveHeaderCard (std::ofstream & stream)
Definition at line 4673 of file pdbfile.cc.
{
    stream << left << setw(6) << header_->GetRecordName()
           << left << setw(4) << " "
           << left << setw(40) << header_->GetClassification()
           << left << setw(9) << header_->GetDepositionDate()
           << left << setw(3) << " "
           << right << setw(4) << header_->GetIdentifierCode()
           << left << setw(14) << " "
           << endl;
}
void PdbFile::ResolveHelixCard (std::ofstream & stream)
Definition at line 5597 of file pdbfile.cc.
References gmml::dNotSet, PdbFileSpace::PdbHelix::GetComment(), PdbFileSpace::PdbHelix::GetHelixClass(), PdbFileSpace::PdbHelix::GetHelixId(), PdbFileSpace::PdbHelix::GetHelixLength(), PdbFileSpace::PdbHelix::GetHelixResidues(), PdbFileSpace::PdbHelix::GetHelixSerialNumber(), gmml::iNotSet, and PdbFileSpace::UnknownHelix.
{
    PdbHelixCard::HelixMap helix_map = helixes_->GetHelixes();
    int counter = helix_map.size();
    int serial_number = 1;
    while(serial_number <= counter)
    {
        for(PdbHelixCard::HelixMap::iterator it = helix_map.begin(); it != helix_map.end(); it++)
        {
            PdbHelix* helix = (*it).second;
            PdbHelix::HelixResidueVector helix_residues = helix->GetHelixResidues();
            if(helix->GetHelixSerialNumber() == serial_number)
            {
                stream << left << setw(6) << helixes_->GetRecordName()
                       << left << setw(1) << " ";
                if(helix->GetHelixSerialNumber() != iNotSet)
                    stream << right << setw(3) << helix->GetHelixSerialNumber();
                else
                    stream << right << setw(3) << " ";
                stream << left << setw(1) << " "
                       << right << setw(3) << helix->GetHelixId()
                       << left << setw(1) << " "
                       << right << setw(3) << helix_residues.at(0)->GetResidueName()
                       << left << setw(1) << " "
                       << right << setw(1) << helix_residues.at(0)->GetResidueChainId()
                       << left << setw(1) << " ";
                if(helix_residues.at(0)->GetResidueSequenceNumber() != iNotSet)
                    stream << right << setw(4) << helix_residues.at(0)->GetResidueSequenceNumber();
                else
                    stream << right << setw(4) << " ";
                stream << right << setw(1) << helix_residues.at(0)->GetResidueInsertionCode()
                       << left << setw(1) << " "
                       << right << setw(3) << helix_residues.at(1)->GetResidueName()
                       << left << setw(1) << " "
                       << right << setw(1) << helix_residues.at(1)->GetResidueChainId()
                       << left << setw(1) << " ";
                if(helix_residues.at(1)->GetResidueSequenceNumber() != iNotSet)
                    stream << right << setw(4) << helix_residues.at(1)->GetResidueSequenceNumber();
                else
                    stream << right << setw(4) << " ";
                stream << right << setw(1) << helix_residues.at(1)->GetResidueInsertionCode();
                if(helix->GetHelixClass() != UnknownHelix)
                    stream << right << setw(2) << helix->GetHelixClass();
                else
                    stream << right << setw(2) << " ";
                stream << left << setw(30) << helix->GetComment()
                       << left << setw(1) << " ";
                if(helix->GetHelixLength() != dNotSet)
                    stream << right << setw(5) << helix->GetHelixLength();
                else
                    stream << right << setw(5) << " ";
                stream << left << setw(4) << " "
                       << endl;
                break;
            }
        }
        serial_number++;
    }
}
void PdbFile::ResolveHeterogenCard (std::ofstream & stream)
Definition at line 5349 of file pdbfile.cc.
References PdbFileSpace::PdbHeterogen::GetChainId(), PdbFileSpace::PdbHeterogen::GetDscr(), PdbFileSpace::PdbHeterogen::GetHeterogenId(), PdbFileSpace::PdbHeterogen::GetInsertionCode(), PdbFileSpace::PdbHeterogen::GetNumberOfHeterogenAtoms(), PdbFileSpace::PdbHeterogen::GetSequenceNumber(), and gmml::iNotSet.
{
    PdbHeterogenCard::HeterogenMap heterogen_map = heterogens_->GetHeterogens();
    for(PdbHeterogenCard::HeterogenMap::iterator it = heterogen_map.begin(); it != heterogen_map.end(); it++)
    {
        PdbHeterogen* heterogen = (*it).second;
        stream << left << setw(6) << heterogens_->GetRecordName()
               << left << setw(1) << " "
               << right << setw(3) << heterogen->GetHeterogenId()
               << left << setw(2) << " "
               << right << setw(1) << heterogen->GetChainId();
        if(heterogen->GetSequenceNumber() != iNotSet)
            stream << right << setw(4) << heterogen->GetSequenceNumber();
        else
            stream << right << setw(4) << " ";
        stream << right << setw(1) << heterogen->GetInsertionCode()
               << left << setw(2) << " ";
        if(heterogen->GetNumberOfHeterogenAtoms() != iNotSet)
            stream << right << setw(5) << heterogen->GetNumberOfHeterogenAtoms();
        else
            stream << right << setw(5) << " ";
        stream << left << setw(5) << " "
               << left << setw(40) << heterogen->GetDscr()
               << left << setw(10) << " "
               << endl;
    }
}
void PdbFile::ResolveHeterogenNameCard (std::ofstream & stream)
Definition at line 5378 of file pdbfile.cc.
References PdbFileSpace::PdbHeterogenName::GetHeterogenIdentifier(), and PdbFileSpace::PdbHeterogenName::GetHeterogenName().
{
    PdbHeterogenNameCard::HeterogenNameMap heterogen_name_map = heterogens_name_->GetHeterogenNames();
    for(PdbHeterogenNameCard::HeterogenNameMap::iterator it = heterogen_name_map.begin(); it != heterogen_name_map.end(); it++)
    {
        PdbHeterogenName* heterogen_name = (*it).second;
        const int MAX_NAME_LENGTH_IN_LINE = 55;
        if((int)heterogen_name->GetHeterogenName().length() > MAX_NAME_LENGTH_IN_LINE)
        {
            stream << left << setw(6) << heterogens_name_->GetRecordName()
                   << left << setw(2) << " "
                   << right << setw(2) << " "
                   << left << setw(1) << " "
                   << right << setw(3) << heterogen_name->GetHeterogenIdentifier()
                   << left << setw(1) << " "
                   << left << setw(55) << heterogen_name->GetHeterogenName().substr(0,MAX_NAME_LENGTH_IN_LINE)
                   << left << setw(10) << " "
                   << endl;
            int counter = ceil((double)(heterogen_name->GetHeterogenName().length()) / MAX_NAME_LENGTH_IN_LINE);
            for(int i = 2; i <= counter; i++)
            {
                if(i != counter)
                {
                    stream << left << setw(6) << heterogens_name_->GetRecordName()
                           << left << setw(2) << " "
                           << right << setw(2) << i
                           << left << setw(1) << " "
                           << right << setw(3) << heterogen_name->GetHeterogenIdentifier()
                           << left << setw(1) << " "
                           << left << setw(55) << heterogen_name->GetHeterogenName().substr(MAX_NAME_LENGTH_IN_LINE*(i-1),MAX_NAME_LENGTH_IN_LINE)
                           << left << setw(10) << " "
                           << endl;
                }
                else
                {
                    stream << left << setw(6) << heterogens_name_->GetRecordName()
                           << left << setw(2) << " "
                           << right << setw(2) << i
                           << left << setw(1) << " "
                           << right << setw(3) << heterogen_name->GetHeterogenIdentifier()
                           << left << setw(1) << " "
                           << left << setw(55) << heterogen_name->GetHeterogenName().substr(MAX_NAME_LENGTH_IN_LINE*(i-1),heterogen_name->GetHeterogenName().length()-MAX_NAME_LENGTH_IN_LINE*(i-1))
                           << left << setw(10) << " "
                           << endl;
                }
            }
        }
        else
        {
            stream << left << setw(6) << heterogens_name_->GetRecordName()
                   << left << setw(2) << " "
                   << right << setw(2) << " "
                   << left << setw(1) << " "
                   << right << setw(3) << heterogen_name->GetHeterogenIdentifier()
                   << left << setw(1) << " "
                   << left << setw(55) << heterogen_name->GetHeterogenName()
                   << left << setw(10) << " "
                   << endl;
        }
    }
}
void PdbFile::ResolveHeterogenSynonymCard (std::ofstream & stream)
Definition at line 5440 of file pdbfile.cc.
References PdbFileSpace::PdbHeterogenSynonym::GetHeterogenIdentifier(), and PdbFileSpace::PdbHeterogenSynonym::GetHeterogenSynonyms().
{
    PdbHeterogenSynonymCard::HeterogenSynonymMap heterogen_synonym_map = heterogen_synonyms_->GetHeterogensSynonyms();
    for(PdbHeterogenSynonymCard::HeterogenSynonymMap::iterator it = heterogen_synonym_map.begin(); it != heterogen_synonym_map.end(); it++)
    {
        PdbHeterogenSynonym* heterogen_synonym = (*it).second;
        stringstream ss;
        vector<string> synonyms = heterogen_synonym->GetHeterogenSynonyms();
        for(vector<string>::iterator it = synonyms.begin(); it != synonyms.end(); it++)
        {
            if(it != synonyms.end() - 1)
            {
                ss << (*it) << "; ";
            }
            else
            {
                ss << (*it) << ";";
            }
        }
        const int MAX_SYNONYM_LENGTH_IN_LINE = 55;
        if((int)ss.str().length() > MAX_SYNONYM_LENGTH_IN_LINE)
        {
            stream << left << setw(6) << heterogen_synonyms_->GetRecordName()
                   << left << setw(2) << " "
                   << right << setw(2) << " "
                   << left << setw(1) << " "
                   << right << setw(3) << heterogen_synonym->GetHeterogenIdentifier()
                   << left << setw(1) << " "
                   << left << setw(55) << ss.str().substr(0,MAX_SYNONYM_LENGTH_IN_LINE)
                   << left << setw(10) << " "
                   << endl;
            int counter = ceil((double)(ss.str().length()) / MAX_SYNONYM_LENGTH_IN_LINE);
            for(int i = 2; i <= counter; i++)
            {
                if(i != counter)
                {
                    stream << left << setw(6) << heterogen_synonyms_->GetRecordName()
                           << left << setw(2) << " "
                           << right << setw(2) << i
                           << left << setw(1) << " "
                           << right << setw(3) << heterogen_synonym->GetHeterogenIdentifier()
                           << left << setw(1) << " "
                           << left << setw(55) << ss.str().substr(MAX_SYNONYM_LENGTH_IN_LINE*(i-1),MAX_SYNONYM_LENGTH_IN_LINE)
                           << left << setw(10) << " "
                           << endl;
                }
                else
                {
                    stream << left << setw(6) << heterogen_synonyms_->GetRecordName()
                           << left << setw(2) << " "
                           << right << setw(2) << i
                           << left << setw(1) << " "
                           << right << setw(3) << heterogen_synonym->GetHeterogenIdentifier()
                           << left << setw(1) << " "
                           << left << setw(55) << ss.str().substr(MAX_SYNONYM_LENGTH_IN_LINE*(i-1),ss.str().length()-MAX_SYNONYM_LENGTH_IN_LINE*(i-1))
                           << left << setw(10) << " "
                           << endl;
                }
            }
        }
        else
        {
            stream << left << setw(6) << heterogen_synonyms_->GetRecordName()
                   << left << setw(2) << " "
                   << right << setw(2) << " "
                   << left << setw(1) << " "
                   << right << setw(3) << heterogen_synonym->GetHeterogenIdentifier()
                   << left << setw(1) << " "
                   << left << setw(55) << ss.str()
                   << left << setw(10) << " "
                   << endl;
        }
    }
}
void PdbFile::ResolveJournalCard (std::ofstream & stream)
Definition at line 5213 of file pdbfile.cc.
{
}
void PdbFile::ResolveKeywordCard (std::ofstream & stream)
Definition at line 5125 of file pdbfile.cc.
{
}
void PdbFile::ResolveLinkCard (std::ofstream & stream)
Definition at line 5821 of file pdbfile.cc.
References gmml::dNotSet, PdbFileSpace::PdbLink::GetLinkLength(), PdbFileSpace::PdbLink::GetResidues(), and gmml::iNotSet.
{
    PdbLinkCard::LinkVector links = links_->GetResidueLinks();
    for(PdbLinkCard::LinkVector::iterator it = links.begin(); it != links.end(); it++)
    {
        PdbLink* link = (*it);
        PdbLink::LinkResidueVector link_residues = link->GetResidues();
        stream << left << setw(6) << links_->GetRecordName()
               << left << setw(6) << " "
               << left << setw(4) << link_residues.at(0)->GetAtomName()
               << right << setw(1) << link_residues.at(0)->GetAlternateLocationIndicator()
               << right << setw(3) << link_residues.at(0)->GetResidueName()
               << left << setw(1) << " "
               << right << setw(1) << link_residues.at(0)->GetResidueChainId();
        if(link_residues.at(0)->GetResidueSequenceNumber() != iNotSet)
            stream << right << setw(4) << link_residues.at(0)->GetResidueSequenceNumber();
        else
            stream << right << setw(4) << " ";
        stream << right << setw(1) << link_residues.at(0)->GetResidueInsertionCode()
               << left << setw(15) << " "
               << left << setw(4) << link_residues.at(1)->GetAtomName()
               << right << setw(1) << link_residues.at(1)->GetAlternateLocationIndicator()
               << right << setw(3) << link_residues.at(1)->GetResidueName()
               << left << setw(1) << " "
               << right << setw(1) << link_residues.at(1)->GetResidueChainId();
        if(link_residues.at(1)->GetResidueSequenceNumber() != iNotSet)
            stream << right << setw(4) << link_residues.at(1)->GetResidueSequenceNumber();
        else
            stream << right << setw(4) << " ";
        stream << right << setw(1) << link_residues.at(1)->GetResidueInsertionCode()
               << left << setw(2) << " ";
        if(link_residues.at(0)->GetSymmetryOperator() != iNotSet)
            stream << right << setw(6) << link_residues.at(0)->GetSymmetryOperator();
        else
            stream << right << setw(6) << " ";
        stream << left << setw(1) << " ";
        if(link_residues.at(1)->GetSymmetryOperator() != iNotSet)
            stream << right << setw(6) << link_residues.at(1)->GetSymmetryOperator();
        else
            stream << right << setw(6) << " ";
        stream << left << setw(1) << " ";
        if(link->GetLinkLength() != dNotSet)
            stream << right << setw(5) << fixed << setprecision(2) << link->GetLinkLength();
        else
            stream << right << setw(5) << " ";
        stream << left << setw(2) << " "
               << endl;
    }
}
void PdbFile::ResolveMasterCard (std::ofstream & stream)
Definition at line 6656 of file pdbfile.cc.
{
}
void PdbFile::ResolveMatrixCard (std::ofstream & stream)
Definition at line 6100 of file pdbfile.cc.
References Geometry::Coordinate::CompareTo(), gmml::dNotSet, PdbFileSpace::PdbMatrixN::GetIGiven(), PdbFileSpace::PdbMatrixN::GetN(), PdbFileSpace::PdbMatrixN::GetRecordName(), PdbFileSpace::PdbMatrixN::GetSerialNumber(), PdbFileSpace::PdbMatrixN::GetTransformationVector(), PdbFileSpace::PdbMatrixN::GetV(), Geometry::Coordinate::GetX(), Geometry::Coordinate::GetY(), Geometry::Coordinate::GetZ(), and gmml::iNotSet.
{
    PdbMatrixNCard::MatrixNVectorVector matrices = matrices_->GetMatrixN();
    int number_of_matrix_entries = matrices.at(0).size();
    for(int i = 0; i < number_of_matrix_entries; i++)
    {
        for(unsigned int j = 0; j < 3; j++)
        {
            PdbMatrixNCard::MatrixNVector matrix_vector = matrices.at(j);
            PdbMatrixN* matrix = matrix_vector.at(i);
            stringstream ss;
            ss << matrix->GetRecordName() << matrix->GetN();
            stream << left << setw(6) << ss.str()
                   << left << setw(1) << " ";
            if(matrix->GetSerialNumber() != iNotSet)
                stream << right << setw(3) << matrix->GetSerialNumber();
            else
                stream << right << setw(3) << " ";
            if(matrix->GetTransformationVector().CompareTo(Geometry::Coordinate(dNotSet, dNotSet, dNotSet)) == false)
            {
                stream << right << setw(10) << fixed << setprecision(6) << matrix->GetTransformationVector().GetX()
                       << right << setw(10) << fixed << setprecision(6) << matrix->GetTransformationVector().GetY()
                       << right << setw(10) << fixed << setprecision(6) << matrix->GetTransformationVector().GetZ();
            }
            else
            {
                stream << right << setw(10) << " "
                       << right << setw(10) << " "
                       << right << setw(10) << " ";
            }
            stream << left << setw(5) << " ";
            if(matrix->GetV() != dNotSet)
                stream << right << setw(10) << fixed << setprecision(5) << matrix->GetV();
            else
                stream << right << setw(10) << " ";
            stream << left << setw(4) << " ";
            if(matrix->GetIGiven() != iNotSet)
                stream << right << setw(1) << matrix->GetIGiven();
            else
                stream << right << setw(1) << " ";
            stream << left << setw(20) << " "
                   << endl;
        }
    }
}
void PdbFile::ResolveModelCard (std::ofstream & stream)
Definition at line 6147 of file pdbfile.cc.
References Geometry::Coordinate::CompareTo(), gmml::dNotSet, PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomCharge(), PdbFileSpace::PdbAtom::GetAtomElementSymbol(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomName(), PdbFileSpace::PdbAtom::GetAtomOccupancy(), PdbFileSpace::PdbAtom::GetAtomOrthogonalCoordinate(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomSerialNumber(), PdbFileSpace::PdbAtom::GetAtomTempretureFactor(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbModel::GetModelSerialNumber(), PdbFileSpace::PdbAtomCard::GetRecordName(), PdbFileSpace::PdbHeterogenAtomCard::GetRecordName(), Geometry::Coordinate::GetX(), Geometry::Coordinate::GetY(), Geometry::Coordinate::GetZ(), and gmml::iNotSet.
{
    PdbModelCard::PdbModelMap models = models_->GetModels();
    int number_of_models = models.size();
    if(number_of_models == 1)
    {
        for(PdbModelCard::PdbModelMap::iterator it = models.begin(); it != models.end(); it++)
        {
            PdbModel* model = (*it).second;
            PdbModelResidueSet* residue_set = model->GetModelResidueSet();
            PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
            for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
            {
                PdbAtomCard* atom_card = (*it1);
                int serial_number = 0;
                string residue_name = "";
                char chain_id = ' ';
                int residue_sequence_number = 0;
                char insertion_code = ' ';
                PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
                int atoms_size = atoms.size();
                for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
                {
                    PdbAtom* atom = (*it2).second;
                    stream << left << setw(6) << atom_card->GetRecordName();
                    if(atom->GetAtomSerialNumber() != iNotSet)
                        stream << right << setw(5) << atom->GetAtomSerialNumber();
                    else
                        stream << right << setw(5) << " ";
                    stream << left << setw(1) << " "
                           << left << setw(4) << atom->GetAtomName()
                           << left << setw(1) << atom->GetAtomAlternateLocation()
                           << right << setw(3) << atom->GetAtomResidueName()
                           << left << setw(1) << " "
                           << left << setw(1) << atom->GetAtomChainId();
                    if(atom->GetAtomResidueSequenceNumber() != iNotSet)
                        stream << right << setw(4) << atom->GetAtomResidueSequenceNumber();
                    else
                        stream << right << setw(4) << " ";
                    stream << left << setw(1) << atom->GetAtomInsertionCode()
                           << left << setw(3) << " ";
                    if(atom->GetAtomOrthogonalCoordinate().CompareTo(Geometry::Coordinate(dNotSet, dNotSet, dNotSet)) == false)
                    {
                        stream << right << setw(8) << fixed << setprecision(3) << atom->GetAtomOrthogonalCoordinate().GetX()
                               << right << setw(8) << fixed << setprecision(3) << atom->GetAtomOrthogonalCoordinate().GetY()
                               << right << setw(8) << fixed << setprecision(3) << atom->GetAtomOrthogonalCoordinate().GetZ();
                    }
                    else
                    {
                        stream << right << setw(8) << " "
                               << right << setw(8) << " "
                               << right << setw(8) << " ";
                    }
                    if(atom->GetAtomOccupancy() != dNotSet)
                        stream << right << setw(6) << fixed << setprecision(2) << atom->GetAtomOccupancy();
                    else
                        stream << right << setw(6) << " ";
                    if(atom->GetAtomTempretureFactor() != dNotSet)
                        stream << right << setw(6) << fixed << setprecision(2) << atom->GetAtomTempretureFactor();
                    else
                        stream << right << setw(6) << " ";
                    stream << left << setw(10) << " "
                           << right << setw(2) << atom->GetAtomElementSymbol()
                           << left << setw(2) << atom->GetAtomCharge()
                           << endl;
                    serial_number = atom->GetAtomSerialNumber();
                    residue_name = atom->GetAtomResidueName();
                    chain_id = atom->GetAtomChainId();
                    residue_sequence_number = atom->GetAtomResidueSequenceNumber();
                }
                if(atoms_size != 0)
                {
                    stream << left << setw(6) << "TER";
                    if(serial_number != iNotSet)
                        stream << right << setw(5) << (serial_number+1);
                    else
                        stream << right << setw(5) << " ";
                    stream << left << setw(6) << " "
                           << right << setw(3) << residue_name
                           << left << setw(1) << " "
                           << left << setw(1) << chain_id;
                    if(residue_sequence_number != iNotSet)
                        stream << right << setw(4) << residue_sequence_number;
                    else
                        stream << right << setw(4) << " ";
                    stream << left << setw(1) << insertion_code
                           << left << setw(53) << " "
                           << endl;
                }
            }
            PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
            for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
            {
                PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
                PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
                for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
                {
                    PdbAtom* heterogen_atom = (*it2).second;
                    stream << left << setw(6) << heterogen_atom_card->GetRecordName();
                    if(heterogen_atom->GetAtomSerialNumber() != iNotSet)
                        stream << right << setw(5) << heterogen_atom->GetAtomSerialNumber();
                    else
                        stream << right << setw(5) << " ";
                    stream << left << setw(1) << " "
                           << left << setw(4) << heterogen_atom->GetAtomName()
                           << left << setw(1) << heterogen_atom->GetAtomAlternateLocation()
                           << right << setw(3) << heterogen_atom->GetAtomResidueName()
                           << left << setw(1) << " "
                           << left << setw(1) << heterogen_atom->GetAtomChainId();
                    if(heterogen_atom->GetAtomResidueSequenceNumber() != iNotSet)
                        stream << right << setw(4) << heterogen_atom->GetAtomResidueSequenceNumber();
                    else
                        stream << right << setw(4) << " ";
                    stream << left << setw(1) << heterogen_atom->GetAtomInsertionCode()
                           << left << setw(3) << " ";
                    if(heterogen_atom->GetAtomOrthogonalCoordinate().CompareTo(Geometry::Coordinate(dNotSet, dNotSet, dNotSet)) == false)
                    {
                        stream << right << setw(8) << fixed << setprecision(3) << heterogen_atom->GetAtomOrthogonalCoordinate().GetX()
                               << right << setw(8) << fixed << setprecision(3) << heterogen_atom->GetAtomOrthogonalCoordinate().GetY()
                               << right << setw(8) << fixed << setprecision(3) << heterogen_atom->GetAtomOrthogonalCoordinate().GetZ();
                    }
                    else
                    {
                        stream << right << setw(8) << " "
                               << right << setw(8) << " "
                               << right << setw(8) << " ";
                    }
                    if(heterogen_atom->GetAtomOccupancy() != dNotSet)
                        stream << right << setw(6) << fixed << setprecision(2) << heterogen_atom->GetAtomOccupancy();
                    else
                        stream << right << setw(6) << " ";
                    if(heterogen_atom->GetAtomTempretureFactor() != dNotSet)
                        stream << right << setw(6) << fixed << setprecision(2) << heterogen_atom->GetAtomTempretureFactor();
                    else
                        stream << right << setw(6) << " ";
                    stream << left << setw(10) << " "
                           << right << setw(2) << heterogen_atom->GetAtomElementSymbol()
                           << left << setw(2) << heterogen_atom->GetAtomCharge()
                           << endl;
                }
            }
        }
    }
    else
    {
        for(PdbModelCard::PdbModelMap::iterator it = models.begin(); it != models.end(); it++)
        {
            PdbModel* model = (*it).second;
            stream << left << setw(6) << models_->GetRecordName()
                   << left << setw(4) << " ";
            if(model->GetModelSerialNumber() != iNotSet)
                stream << right << setw(4) << model->GetModelSerialNumber();
            else
                stream << right << setw(4) << " ";
            stream << left << setw(66) << " "
                   << endl;
            PdbModelResidueSet* residue_set = model->GetModelResidueSet();
            PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
            for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
            {
                PdbAtomCard* atom_card = (*it1);
                int serial_number = 0;
                string residue_name = "";
                char chain_id = ' ';
                int residue_sequence_number = 0;
                char insertion_code = ' ';
                PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
                int atoms_size = atoms.size();
                for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
                {
                    PdbAtom* atom = (*it2).second;
                    stream << left << setw(6) << atom_card->GetRecordName();
                    if(atom->GetAtomSerialNumber() != iNotSet)
                        stream << right << setw(5) << atom->GetAtomSerialNumber();
                    else
                        stream << right << setw(5) << " ";
                    stream << left << setw(1) << " "
                           << left << setw(4) << atom->GetAtomName()
                           << left << setw(1) << atom->GetAtomAlternateLocation()
                           << right << setw(3) << atom->GetAtomResidueName()
                           << left << setw(1) << " "
                           << left << setw(1) << atom->GetAtomChainId();
                    if(atom->GetAtomResidueSequenceNumber() != iNotSet)
                        stream << right << setw(4) << atom->GetAtomResidueSequenceNumber();
                    else
                        stream << right << setw(4) << " ";
                    stream << left << setw(1) << atom->GetAtomInsertionCode()
                           << left << setw(3) << " ";
                    if(atom->GetAtomOrthogonalCoordinate().CompareTo(Geometry::Coordinate(dNotSet, dNotSet, dNotSet)) == false)
                        stream << right << setw(8) << fixed << setprecision(3) << atom->GetAtomOrthogonalCoordinate().GetX()
                               << right << setw(8) << fixed << setprecision(3) << atom->GetAtomOrthogonalCoordinate().GetY()
                               << right << setw(8) << fixed << setprecision(3) << atom->GetAtomOrthogonalCoordinate().GetZ();
                    else
                        stream << right << setw(8) << " "
                               << right << setw(8) << " "
                               << right << setw(8) << " ";
                    if(atom->GetAtomOccupancy() != dNotSet)
                        stream << right << setw(6) << fixed << setprecision(2) << atom->GetAtomOccupancy();
                    else
                        stream << right << setw(6) << " ";
                    if(atom->GetAtomTempretureFactor() != dNotSet)
                        stream << right << setw(6) << fixed << setprecision(2) << atom->GetAtomTempretureFactor();
                    else
                        stream << right << setw(6) << " ";
                    stream << left << setw(10) << " "
                           << right << setw(2) << atom->GetAtomElementSymbol()
                           << left << setw(2) << atom->GetAtomCharge()
                           << endl;
                    serial_number = atom->GetAtomSerialNumber();
                    residue_name = atom->GetAtomResidueName();
                    chain_id = atom->GetAtomChainId();
                    residue_sequence_number = atom->GetAtomResidueSequenceNumber();
                }
                if(atoms_size != 0)
                {
                    stream << left << setw(6) << "TER";
                    if(serial_number != iNotSet)
                        stream << right << setw(5) << (serial_number+1);
                    else
                        stream << right << setw(5) << " ";
                    stream << left << setw(6) << " "
                           << right << setw(3) << residue_name
                           << left << setw(1) << " "
                           << left << setw(1) << chain_id;
                    if(residue_sequence_number != iNotSet)
                        stream << right << setw(4) << residue_sequence_number;
                    else
                        stream << right << setw(4) << " ";
                    stream << left << setw(1) << insertion_code
                           << left << setw(53) << " "
                           << endl;
                }
            }
            PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
            for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
            {
                PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
                PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
                for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
                {
                    PdbAtom* heterogen_atom = (*it2).second;
                    stream << left << setw(6) << heterogen_atom_card->GetRecordName();
                    if(heterogen_atom->GetAtomSerialNumber() != iNotSet)
                        stream << right << setw(5) << heterogen_atom->GetAtomSerialNumber();
                    else
                        stream << right << setw(5) << " ";
                    stream << left << setw(1) << " "
                           << left << setw(4) << heterogen_atom->GetAtomName()
                           << left << setw(1) << heterogen_atom->GetAtomAlternateLocation()
                           << right << setw(3) << heterogen_atom->GetAtomResidueName()
                           << left << setw(1) << " "
                           << left << setw(1) << heterogen_atom->GetAtomChainId();
                    if(heterogen_atom->GetAtomResidueSequenceNumber() != iNotSet)
                        stream << right << setw(4) << heterogen_atom->GetAtomResidueSequenceNumber();
                    else
                        stream << right << setw(4) << " ";
                    stream << left << setw(1) << heterogen_atom->GetAtomInsertionCode()
                           << left << setw(3) << " ";
                    if(heterogen_atom->GetAtomOrthogonalCoordinate().CompareTo(Geometry::Coordinate(dNotSet, dNotSet, dNotSet)) == false)
                        stream << right << setw(8) << fixed << setprecision(3) << heterogen_atom->GetAtomOrthogonalCoordinate().GetX()
                               << right << setw(8) << fixed << setprecision(3) << heterogen_atom->GetAtomOrthogonalCoordinate().GetY()
                               << right << setw(8) << fixed << setprecision(3) << heterogen_atom->GetAtomOrthogonalCoordinate().GetZ();
                    else
                        stream << right << setw(8) << " "
                               << right << setw(8) << " "
                               << right << setw(8) << " ";
                    if(heterogen_atom->GetAtomOccupancy() != dNotSet)
                        stream << right << setw(6) << fixed << setprecision(2) << heterogen_atom->GetAtomOccupancy();
                    else
                        stream << right << setw(6) << " ";
                    if(heterogen_atom->GetAtomTempretureFactor() != dNotSet)
                        stream << right << setw(6) << fixed << setprecision(2) << heterogen_atom->GetAtomTempretureFactor();
                    else
                        stream << right << setw(6) << " ";
                    stream << left << setw(10) << " "
                           << right << setw(2) << heterogen_atom->GetAtomElementSymbol()
                           << left << setw(2) << heterogen_atom->GetAtomCharge()
                           << endl;
                }
            }
            stream << left << setw(6) << "ENDMDL"
                   << left << setw(74) << " "
                   << endl;
        }
    }
}
void PdbFile::ResolveModelCardWithTheGivenModelNumber (std::ofstream & stream, int model_number = 1)
Definition at line 6434 of file pdbfile.cc.
References Geometry::Coordinate::CompareTo(), gmml::dNotSet, PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomCharge(), PdbFileSpace::PdbAtom::GetAtomElementSymbol(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomName(), PdbFileSpace::PdbAtom::GetAtomOccupancy(), PdbFileSpace::PdbAtom::GetAtomOrthogonalCoordinate(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomSerialNumber(), PdbFileSpace::PdbAtom::GetAtomTempretureFactor(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbAtomCard::GetRecordName(), PdbFileSpace::PdbHeterogenAtomCard::GetRecordName(), Geometry::Coordinate::GetX(), Geometry::Coordinate::GetY(), Geometry::Coordinate::GetZ(), and gmml::iNotSet.
{
    PdbModelCard::PdbModelMap models = models_->GetModels();
    if(models.size() != 0)
    {
        PdbModel* model = models[model_number];
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            int serial_number = 0;
            string residue_name = "";
            char chain_id = ' ';
            int residue_sequence_number = 0;
            char insertion_code = ' ';
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            int atoms_size = atoms.size();
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                stream << left << setw(6) << atom_card->GetRecordName();
                if(atom->GetAtomSerialNumber() != iNotSet)
                    stream << right << setw(5) << atom->GetAtomSerialNumber();
                else
                    stream << right << setw(5) << " ";
                stream << left << setw(1) << " "
                       << left << setw(4) << atom->GetAtomName()
                       << left << setw(1) << atom->GetAtomAlternateLocation()
                       << right << setw(3) << atom->GetAtomResidueName()
                       << left << setw(1) << " "
                       << left << setw(1) << atom->GetAtomChainId();
                if(atom->GetAtomResidueSequenceNumber() != iNotSet)
                    stream << right << setw(4) << atom->GetAtomResidueSequenceNumber();
                else
                    stream << right << setw(4) << " ";
                stream << left << setw(1) << atom->GetAtomInsertionCode()
                       << left << setw(3) << " ";
                if(atom->GetAtomOrthogonalCoordinate().CompareTo(Geometry::Coordinate(dNotSet, dNotSet, dNotSet)) == false)
                {
                    stream << right << setw(8) << fixed << setprecision(3) << atom->GetAtomOrthogonalCoordinate().GetX()
                           << right << setw(8) << fixed << setprecision(3) << atom->GetAtomOrthogonalCoordinate().GetY()
                           << right << setw(8) << fixed << setprecision(3) << atom->GetAtomOrthogonalCoordinate().GetZ();
                }
                else
                {
                    stream << right << setw(8) << " "
                           << right << setw(8) << " "
                           << right << setw(8) << " ";
                }
                if(atom->GetAtomOccupancy() != dNotSet)
                    stream << right << setw(6) << fixed << setprecision(2) << atom->GetAtomOccupancy();
                else
                    stream << right << setw(6) << " ";
                if(atom->GetAtomTempretureFactor() != dNotSet)
                    stream << right << setw(6) << fixed << setprecision(2) << atom->GetAtomTempretureFactor();
                else
                    stream << right << setw(6) << " ";
                stream << left << setw(10) << " "
                       << right << setw(2) << atom->GetAtomElementSymbol()
                       << left << setw(2) << atom->GetAtomCharge()
                       << endl;
                serial_number = atom->GetAtomSerialNumber();
                residue_name = atom->GetAtomResidueName();
                chain_id = atom->GetAtomChainId();
                residue_sequence_number = atom->GetAtomResidueSequenceNumber();
            }
            if(atoms_size != 0)
            {
                stream << left << setw(6) << "TER";
                if(serial_number != iNotSet)
                    stream << right << setw(5) << (serial_number+1);
                else
                    stream << right << setw(5) << " ";
                stream << left << setw(6) << " "
                       << right << setw(3) << residue_name
                       << left << setw(1) << " "
                       << left << setw(1) << chain_id;
                if(residue_sequence_number != iNotSet)
                    stream << right << setw(4) << residue_sequence_number;
                else
                    stream << right << setw(4) << " ";
                stream << left << setw(1) << insertion_code
                       << left << setw(53) << " "
                       << endl;
            }
        }
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
        {
            PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
            PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
            for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
            {
                PdbAtom* heterogen_atom = (*it2).second;
                stream << left << setw(6) << heterogen_atom_card->GetRecordName();
                if(heterogen_atom->GetAtomSerialNumber() != iNotSet)
                    stream << right << setw(5) << heterogen_atom->GetAtomSerialNumber();
                else
                    stream << right << setw(5) << " ";
                stream << left << setw(1) << " "
                       << left << setw(4) << heterogen_atom->GetAtomName()
                       << left << setw(1) << heterogen_atom->GetAtomAlternateLocation()
                       << right << setw(3) << heterogen_atom->GetAtomResidueName()
                       << left << setw(1) << " "
                       << left << setw(1) << heterogen_atom->GetAtomChainId();
                if(heterogen_atom->GetAtomResidueSequenceNumber() != iNotSet)
                    stream << right << setw(4) << heterogen_atom->GetAtomResidueSequenceNumber();
                else
                    stream << right << setw(4) << " ";
                stream << left << setw(1) << heterogen_atom->GetAtomInsertionCode()
                       << left << setw(3) << " ";
                if(heterogen_atom->GetAtomOrthogonalCoordinate().CompareTo(Geometry::Coordinate(dNotSet, dNotSet, dNotSet)) == false)
                {
                    stream << right << setw(8) << fixed << setprecision(3) << heterogen_atom->GetAtomOrthogonalCoordinate().GetX()
                           << right << setw(8) << fixed << setprecision(3) << heterogen_atom->GetAtomOrthogonalCoordinate().GetY()
                           << right << setw(8) << fixed << setprecision(3) << heterogen_atom->GetAtomOrthogonalCoordinate().GetZ();
                }
                else
                {
                    stream << right << setw(8) << " "
                           << right << setw(8) << " "
                           << right << setw(8) << " ";
                }
                if(heterogen_atom->GetAtomOccupancy() != dNotSet)
                    stream << right << setw(6) << fixed << setprecision(2) << heterogen_atom->GetAtomOccupancy();
                else
                    stream << right << setw(6) << " ";
                if(heterogen_atom->GetAtomTempretureFactor() != dNotSet)
                    stream << right << setw(6) << fixed << setprecision(2) << heterogen_atom->GetAtomTempretureFactor();
                else
                    stream << right << setw(6) << " ";
                stream << left << setw(10) << " "
                       << right << setw(2) << heterogen_atom->GetAtomElementSymbol()
                       << left << setw(2) << heterogen_atom->GetAtomCharge()
                       << endl;
            }
        }
    }
}
void PdbFile::ResolveModelTypeCard (std::ofstream & stream)
Definition at line 5147 of file pdbfile.cc.
{
    stream << left << setw(6) << model_type_->GetRecordName()
           << left << setw(2) << " ";
    stringstream ss;
    for(vector<string>::iterator it = model_type_->GetComments().begin(); it != model_type_->GetComments().end(); it++)
    {
        if(it != model_type_->GetComments().end() - 1)
        {
            ss << (*it) << "; ";
        }
        else
        {
            ss << (*it);
        }
    }
    if(ss.str().length() > 70)
    {
        stream << right << setw(2) << " "
               << left << setw(70) << ss.str().substr(0,70)
               << endl;
        int counter = ceil((double)(ss.str().length()) / 70);
        for(int i = 2; i <= counter; i++)
        {
            if(i != counter)
            {
                stream << left << setw(6) << model_type_->GetRecordName()
                       << left << setw(2) << " "
                       << right << setw(2) << i
                       << left << setw(70) << ss.str().substr(70*(i-1), 70)
                       << endl;
            }
            else
            {
                stream << left << setw(6) << model_type_->GetRecordName()
                       << left << setw(2) << " "
                       << right << setw(2) << i
                       << left << setw(70) << ss.str().substr(70*(i-1), ss.str().length() - (i-1)*70)
                       << endl;
            }
        }
    }
    else
    {
        stream << right << setw(2) << " "
               << left << setw(70) << ss.str()
               << endl;
    }
}
void PdbFile::ResolveModificationResidueCard (std::ofstream & stream)
Definition at line 5321 of file pdbfile.cc.
References PdbFileSpace::PdbResidueModification::GetChainId(), PdbFileSpace::PdbResidueModification::GetDscr(), PdbFileSpace::PdbResidueModification::GetIdCode(), PdbFileSpace::PdbResidueModification::GetInsertionCode(), PdbFileSpace::PdbResidueModification::GetResidueName(), PdbFileSpace::PdbResidueModification::GetSequenceNumber(), PdbFileSpace::PdbResidueModification::GetStandardResidueName(), and gmml::iNotSet.
{
    PdbResidueModificationCard::ResidueModificationMap residue_modification_map = residue_modification_->GetResidueModifications();
    for(PdbResidueModificationCard::ResidueModificationMap::iterator it = residue_modification_map.begin(); it != residue_modification_map.end(); it++)
    {
        PdbResidueModification* residue_modification = (*it).second;
        stream << left << setw(6) << residue_modification_->GetRecordName()
               << left << setw(1) << " "
               << right << setw(4) << residue_modification->GetIdCode()
               << left << setw(1) << " "
               << right << setw(3) << residue_modification->GetResidueName()
               << left << setw(1) << " "
               << right << setw(1) << residue_modification->GetChainId()
               << left << setw(1) << " ";
        if(residue_modification->GetSequenceNumber() != iNotSet)
            stream << right << setw(4) << residue_modification->GetSequenceNumber();
        else
            stream << right << setw(4) << " ";
        stream << right << setw(1) << residue_modification->GetInsertionCode()
               << left << setw(1) << " "
               << right << setw(3) << residue_modification->GetStandardResidueName()
               << left << setw(2) << " "
               << left << setw(41) << residue_modification->GetDscr()
               << left << setw(10) << " "
               << endl;
    }
}
void PdbFile::ResolveNumModelCard (std::ofstream & stream)
Definition at line 5135 of file pdbfile.cc.
References gmml::iNotSet.
{
    stream << left << setw(6) << number_of_models_->GetRecordName()
           << left << setw(4) << " ";
    if(number_of_models_->GetNumberOfModels() != iNotSet)
        stream << right << setw(4) << number_of_models_->GetNumberOfModels();
    else
        stream << right << setw(4) << " ";
    stream << left << setw(66) << " "
           << endl;
}
void PdbFile::ResolveObsoleteCard (std::ofstream & stream)
Definition at line 4685 of file pdbfile.cc.
{
}
void PdbFile::ResolveOriginCard (std::ofstream & stream)
Definition at line 6035 of file pdbfile.cc.
References Geometry::Coordinate::CompareTo(), gmml::dNotSet, PdbFileSpace::PdbOriginXn::GetN(), PdbFileSpace::PdbOriginXn::GetOrigin(), PdbFileSpace::PdbOriginXn::GetRecordName(), PdbFileSpace::PdbOriginXn::GetT(), Geometry::Coordinate::GetX(), Geometry::Coordinate::GetY(), and Geometry::Coordinate::GetZ().
{
    PdbOriginXnCard::OriginXnVector origins = origins_->GetOriginXN();
    for(PdbOriginXnCard::OriginXnVector::iterator it = origins.begin(); it != origins.end(); it++)
    {
        PdbOriginXn* origin = (*it);
        stringstream ss;
        ss << origin->GetRecordName() << origin->GetN();
        stream << left << setw(6) << ss.str()
               << left << setw(4) << " ";
        if(origin->GetOrigin().CompareTo(Geometry::Coordinate(dNotSet, dNotSet, dNotSet)) == false)
        {
            stream << right << setw(10) << fixed << setprecision(6) << origin->GetOrigin().GetX()
                   << right << setw(10) << fixed << setprecision(6) << origin->GetOrigin().GetY()
                   << right << setw(10) << fixed << setprecision(6) << origin->GetOrigin().GetZ();
        }
        else
        {
            stream << right << setw(10) << " "
                   << right << setw(10) << " "
                   << right << setw(10) << " ";
        }
        stream << left << setw(5) << " ";
        if(origin->GetT() != dNotSet)
            stream << right << setw(10) << fixed << setprecision(5) << origin->GetT();
        else
            stream << right << setw(10) << " ";
        stream << left << setw(25) << " "
               << endl;
    }
}
void PdbFile::ResolveRemarkCard (std::ofstream & stream)
Definition at line 5218 of file pdbfile.cc.
{
}
void PdbFile::ResolveRevisionDateCard (std::ofstream & stream)
Definition at line 5203 of file pdbfile.cc.
{
}
void PdbFile::ResolveScaleCard (std::ofstream & stream)
Definition at line 6068 of file pdbfile.cc.
References Geometry::Coordinate::CompareTo(), gmml::dNotSet, PdbFileSpace::PdbScaleN::GetN(), PdbFileSpace::PdbScaleN::GetRecordName(), PdbFileSpace::PdbScaleN::GetScaleVector(), PdbFileSpace::PdbScaleN::GetU(), Geometry::Coordinate::GetX(), Geometry::Coordinate::GetY(), and Geometry::Coordinate::GetZ().
{
    PdbScaleNCard::ScaleNVector scales = scales_->GetScaleN();
    for(PdbScaleNCard::ScaleNVector::iterator it = scales.begin(); it != scales.end(); it++)
    {
        PdbScaleN* scale = (*it);
        stringstream ss;
        ss << scale->GetRecordName() << scale->GetN();
        stream << left << setw(6) << ss.str()
               << left << setw(4) << " ";
        if(scale->GetScaleVector().CompareTo(Geometry::Coordinate(dNotSet, dNotSet, dNotSet)) == false)
        {
            stream << right << setw(10) << fixed << setprecision(6) << scale->GetScaleVector().GetX()
                   << right << setw(10) << fixed << setprecision(6) << scale->GetScaleVector().GetY()
                   << right << setw(10) << fixed << setprecision(6) << scale->GetScaleVector().GetZ();
        }
        else
        {
            stream << right << setw(10) << " "
                   << right << setw(10) << " "
                   << right << setw(10) << " ";
        }
        stream << left << setw(5) << " ";
        if(scale->GetU() != dNotSet)
            stream << right << setw(10) << fixed << setprecision(5) << scale->GetU();
        else
            stream << right << setw(10) << " ";
        stream << left << setw(25) << " "
               << endl;
    }
}
void PdbFile::ResolveSequenceAdvancedCard (std::ofstream & stream)
Definition at line 5228 of file pdbfile.cc.
{
}
void PdbFile::ResolveSequenceResidueCard (std::ofstream & stream)
Definition at line 5233 of file pdbfile.cc.
References PdbFileSpace::PdbResidueSequence::GetChainId(), PdbFileSpace::PdbResidueSequence::GetNumberOfResidues(), PdbFileSpace::PdbResidueSequence::GetResidueNames(), and gmml::iNotSet.
{
    PdbResidueSequenceCard::ResidueSequenceMap residue_sequence_map = residues_sequence_->GetResidueSequenceChain();
    for(PdbResidueSequenceCard::ResidueSequenceMap::iterator it = residue_sequence_map.begin(); it != residue_sequence_map.end(); it++)
    {
        PdbResidueSequence* residue_sequence = (*it).second;
        int serial_number = 1;
        const int MAX_RESIDUE_IN_SINGLE_LINE = 13;
        vector<string> residue_names = residue_sequence->GetResidueNames();
        if(residue_sequence->GetNumberOfResidues() <= MAX_RESIDUE_IN_SINGLE_LINE)
        {
            stringstream ss;
            for(vector<string>::iterator it1 = residue_names.begin(); it1 != residue_names.end(); it1++)
            {
                ss << right << setw(1) << " "
                   << right << setw(3) << (*it1);
            }
            for(int i = 0; i < MAX_RESIDUE_IN_SINGLE_LINE - residue_sequence->GetNumberOfResidues(); i++)
            {
                ss << right << setw(1) << " "
                   << right << setw(3) << " ";
            }
            stream << left << setw(6) << residues_sequence_->GetRecordName()
                   << left << setw(1) << " "
                   << right << setw(3) << serial_number
                   << right << setw(1) << " "
                   << right << setw(1) << residue_sequence->GetChainId()
                   << right << setw(1) << " ";
            if(residue_sequence->GetNumberOfResidues() != iNotSet)
                stream << right << setw(4) << residue_sequence->GetNumberOfResidues();
            else
                stream << right << setw(4) << " ";
            stream << right << setw(1) << " "
                   << right << setw(52) << ss.str()
                   << right << setw(10) << " "
                   << endl;
        }
        else
        {
            int number_of_lines = ceil((double)(residue_sequence->GetNumberOfResidues()) / MAX_RESIDUE_IN_SINGLE_LINE);
            for(int i = 0; i < number_of_lines; i++)
            {
                stringstream ss;
                if(i != number_of_lines - 1)
                {
                    for(vector<string>::iterator it1 = residue_names.begin() + i * MAX_RESIDUE_IN_SINGLE_LINE;
                        it1 != residue_names.begin() + (i+1) * MAX_RESIDUE_IN_SINGLE_LINE; it1++)
                    {
                        ss << right << setw(1) << " "
                           << right << setw(3) << (*it1);
                    }
                }
                else
                {
                    for(vector<string>::iterator it1 = residue_names.begin() + i * MAX_RESIDUE_IN_SINGLE_LINE;
                        it1 != residue_names.end(); it1++)
                    {
                        ss << right << setw(1) << " "
                           << right << setw(3) << (*it1);
                    }
                    for(int i = 0; i < MAX_RESIDUE_IN_SINGLE_LINE - residue_sequence->GetNumberOfResidues() % MAX_RESIDUE_IN_SINGLE_LINE; i++)
                    {
                        ss << right << setw(1) << " "
                           << right << setw(3) << " ";
                    }
                }
                stream << left << setw(6) << residues_sequence_->GetRecordName()
                       << left << setw(1) << " "
                       << right << setw(3) << serial_number
                       << right << setw(1) << " "
                       << right << setw(1) << residue_sequence->GetChainId()
                       << right << setw(1) << " ";
                if(residue_sequence->GetNumberOfResidues() != iNotSet)
                    stream << right << setw(4) << residue_sequence->GetNumberOfResidues();
                else
                    stream << right << setw(4) << " ";
                stream << right << setw(1) << " "
                       << right << setw(52) << ss.str()
                       << right << setw(10) << " "
                       << endl;
                serial_number++;
            }
        }
    }
}
void PdbFile::ResolveSheetCard (std::ofstream & stream)
Definition at line 5658 of file pdbfile.cc.
References PdbFileSpace::PdbSheetStrand::GetCurrentAtom(), PdbFileSpace::PdbSheet::GetNumberOfStrands(), PdbFileSpace::PdbSheetStrand::GetPreviousAtom(), PdbFileSpace::PdbSheetStrand::GetSense(), PdbFileSpace::PdbSheet::GetSheetId(), PdbFileSpace::PdbSheetStrand::GetStrandResidues(), PdbFileSpace::PdbSheet::GetStrands(), gmml::iNotSet, and PdbFileSpace::UnknownStrand.
{
    PdbSheetCard::SheetMap sheet_map = sheets_->GetSheets();
    for(PdbSheetCard::SheetMap::iterator it = sheet_map.begin(); it != sheet_map.end(); it++)
    {
        PdbSheet* sheet = (*it).second;
        PdbSheet::SheetStrandVector strands = sheet->GetStrands();
        int serial_number = 1;
        for(PdbSheet::SheetStrandVector::iterator it1 = strands.begin(); it1 != strands.end(); it1++)
        {
            PdbSheetStrand* strand = (*it1);
            PdbSheetStrand::SheetStrandResidueVector strand_residues = strand->GetStrandResidues();
            if(strand->GetSense() != 0)
            {
                stream << left << setw(6) << sheets_->GetRecordName()
                       << left << setw(1) << " "
                       << right << setw(3) << serial_number
                       << left << setw(1) << " "
                       << right << setw(3) << sheet->GetSheetId();
                if(sheet->GetNumberOfStrands() != iNotSet)
                    stream << right << setw(2) << sheet->GetNumberOfStrands();
                else
                    stream << right << setw(2) << " ";
                stream << left << setw(1) << " "
                       << right << setw(3) << strand_residues.at(0)->GetResidueName()
                       << left << setw(1) << " "
                       << right << setw(1) << strand_residues.at(0)->GetResidueChainId();
                if(strand_residues.at(0)->GetResidueSequenceNumber() != iNotSet)
                    stream << right << setw(4) << strand_residues.at(0)->GetResidueSequenceNumber();
                else
                    stream << right << setw(4) << " ";
                stream << right << setw(1) << strand_residues.at(0)->GetResidueInsertionCode()
                       << left << setw(1) << " "
                       << right << setw(3) << strand_residues.at(1)->GetResidueName()
                       << left << setw(1) << " "
                       << right << setw(1) << strand_residues.at(1)->GetResidueChainId();
                if(strand_residues.at(1)->GetResidueSequenceNumber() != iNotSet)
                    stream << right << setw(4) << strand_residues.at(1)->GetResidueSequenceNumber();
                else
                    stream << right << setw(4) << " ";
                stream << right << setw(1) << strand_residues.at(1)->GetResidueInsertionCode();
                if(strand->GetSense() != UnknownStrand)
                    stream << right << setw(2) << strand->GetSense();
                else
                    stream << right << setw(2) << " ";
                stream << left << setw(1) << " "
                       << left << setw(4) << strand->GetCurrentAtom()
                       << right << setw(3) << strand_residues.at(2)->GetResidueName()
                       << left << setw(1) << " "
                       << right << setw(1) << strand_residues.at(2)->GetResidueChainId();
                if(strand_residues.at(2)->GetResidueSequenceNumber() != iNotSet)
                    stream << right << setw(4) << strand_residues.at(2)->GetResidueSequenceNumber();
                else
                    stream << right << setw(4) << " ";
                stream << right << setw(1) << strand_residues.at(2)->GetResidueInsertionCode()
                       << left << setw(1) << " "
                       << left << setw(4) << strand->GetPreviousAtom()
                       << right << setw(3) << strand_residues.at(3)->GetResidueName()
                       << left << setw(1) << " "
                       << right << setw(1) << strand_residues.at(3)->GetResidueChainId();
                if(strand_residues.at(3)->GetResidueSequenceNumber() != iNotSet)
                    stream << right << setw(4) << strand_residues.at(3)->GetResidueSequenceNumber();
                else
                    stream << right << setw(4) << " ";
                stream << right << setw(1) << strand_residues.at(3)->GetResidueInsertionCode()
                       << left << setw(10) << " "
                       << endl;
            }
            else
            {
                stream << left << setw(6) << sheets_->GetRecordName()
                       << left << setw(1) << " "
                       << right << setw(3) << serial_number
                       << left << setw(1) << " "
                       << right << setw(3) << sheet->GetSheetId();
                if(sheet->GetNumberOfStrands() != iNotSet)
                    stream << right << setw(2) << sheet->GetNumberOfStrands();
                else
                    stream << right << setw(2) << " ";
                stream << left << setw(1) << " "
                       << right << setw(3) << strand_residues.at(0)->GetResidueName()
                       << left << setw(1) << " "
                       << right << setw(1) << strand_residues.at(0)->GetResidueChainId();
                if(strand_residues.at(0)->GetResidueSequenceNumber() != iNotSet)
                    stream << right << setw(4) << strand_residues.at(0)->GetResidueSequenceNumber();
                else
                    stream << right << setw(4) << " ";
                stream << right << setw(1) << strand_residues.at(0)->GetResidueInsertionCode()
                       << left << setw(1) << " "
                       << right << setw(3) << strand_residues.at(1)->GetResidueName()
                       << left << setw(1) << " "
                       << right << setw(1) << strand_residues.at(1)->GetResidueChainId();
                if(strand_residues.at(1)->GetResidueSequenceNumber() != iNotSet)
                    stream << right << setw(4) << strand_residues.at(1)->GetResidueSequenceNumber();
                else
                    stream << right << setw(4) << " ";
                stream << right << setw(1) << strand_residues.at(1)->GetResidueInsertionCode();
                if(strand->GetSense() != UnknownStrand)
                    stream << right << setw(2) << strand->GetSense();
                else
                    stream << right << setw(2) << " ";
                stream << left << setw(40) << " "
                       << endl;
            }
            serial_number++;
        }
    }
}
void PdbFile::ResolveSiteCard (std::ofstream & stream)
Definition at line 5876 of file pdbfile.cc.
References PdbFileSpace::PdbSite::GetNumberOfResidues(), PdbFileSpace::PdbSiteResidue::GetResidueChainId(), PdbFileSpace::PdbSiteResidue::GetResidueInsertionCode(), PdbFileSpace::PdbSiteResidue::GetResidueName(), PdbFileSpace::PdbSite::GetResidues(), PdbFileSpace::PdbSiteResidue::GetResidueSequenceNumber(), PdbFileSpace::PdbSite::GetSiteId(), and gmml::iNotSet.
{
    PdbSiteCard::PdbSiteMap site_map = sites_->GetResidueSites();
    for(PdbSiteCard::PdbSiteMap::iterator it = site_map.begin(); it != site_map.end(); it++)
    {
        PdbSite* site = (*it).second;
        PdbSite::SiteResidueVector site_residues = site->GetResidues();
        const int MAX_RESIDUE_IN_LINE = 4;
        const int RESIDUE_LENGHT_IN_LINE = 11;
        int number_of_residues = site_residues.size();
        int sequence_number = 1;
        if(number_of_residues > MAX_RESIDUE_IN_LINE)
        {
            int number_of_lines = ceil((double)(number_of_residues) / MAX_RESIDUE_IN_LINE);
            while(sequence_number <= number_of_lines)
            {
                if(sequence_number != number_of_lines)
                {
                    stringstream ss;
                    for(PdbSite::SiteResidueVector::iterator it1 = site_residues.begin()+(sequence_number - 1)*MAX_RESIDUE_IN_LINE;
                        it1 != site_residues.begin()+(sequence_number)*MAX_RESIDUE_IN_LINE; it1++)
                    {
                        PdbSiteResidue* residue = (*it1);
                        ss << left << setw(1) << " "
                           << right << setw(3) << residue->GetResidueName()
                           << left << setw(1) << " "
                           << right << setw(1) << residue->GetResidueChainId();
                        if(residue->GetResidueSequenceNumber() != iNotSet)
                            ss << right << setw(4) << residue->GetResidueSequenceNumber();
                        else
                            ss << right << setw(4) << " ";
                        ss << right << setw(1) << residue->GetResidueInsertionCode();
                    }
                    ss << left << setw(19) << " ";
                    stream << left << setw(6) << sites_->GetRecordName()
                           << left << setw(1) << " "
                           << right << setw(3) << sequence_number
                           << left << setw(1) << " "
                           << right << setw(3) << site->GetSiteId()
                           << left << setw(1) << " ";
                    if(site->GetNumberOfResidues() != iNotSet)
                        stream << right << setw(2) << site->GetNumberOfResidues();
                    else
                        stream << right << setw(2) << " ";
                    stream << left << setw(63) << ss.str()
                           << endl;
                }
                else
                {
                    stringstream ss;
                    for(PdbSite::SiteResidueVector::iterator it1 = site_residues.begin()+(sequence_number - 1)*MAX_RESIDUE_IN_LINE;
                        it1 != site_residues.end(); it1++)
                    {
                        PdbSiteResidue* residue = (*it1);
                        ss << left << setw(1) << " "
                           << right << setw(3) << residue->GetResidueName()
                           << left << setw(1) << " "
                           << right << setw(1) << residue->GetResidueChainId();
                        if(residue->GetResidueSequenceNumber() != iNotSet)
                            ss << right << setw(4) << residue->GetResidueSequenceNumber();
                        else
                            ss << right << setw(4) << " ";
                        ss << right << setw(1) << residue->GetResidueInsertionCode();
                    }
                    if((sequence_number*MAX_RESIDUE_IN_LINE-number_of_residues)*RESIDUE_LENGHT_IN_LINE != 0)
                        ss << left << setw((sequence_number*MAX_RESIDUE_IN_LINE-number_of_residues)*RESIDUE_LENGHT_IN_LINE) << " ";
                    ss << left << setw(19) << " ";
                    stream << left << setw(6) << sites_->GetRecordName()
                           << left << setw(1) << " "
                           << right << setw(3) << sequence_number
                           << left << setw(1) << " "
                           << right << setw(3) << site->GetSiteId()
                           << left << setw(1) << " ";
                    if(site->GetNumberOfResidues() != iNotSet)
                        stream << right << setw(2) << site->GetNumberOfResidues();
                    else
                        stream << right << setw(2) << " ";
                    stream << left << setw(63) << ss.str()
                           << endl;
                }
                sequence_number++;
            }
        }
        else
        {
            stringstream ss;
            for(PdbSite::SiteResidueVector::iterator it1 = site_residues.begin(); it1 != site_residues.end(); it1++)
            {
                PdbSiteResidue* residue = (*it1);
                ss << left << setw(1) << " "
                   << right << setw(3) << residue->GetResidueName()
                   << left << setw(1) << " "
                   << right << setw(1) << residue->GetResidueChainId();
                if(residue->GetResidueSequenceNumber() != iNotSet)
                    ss << right << setw(4) << residue->GetResidueSequenceNumber();
                else
                    ss << right << setw(4) << " ";
                ss << right << setw(1) << residue->GetResidueInsertionCode();
            }
            if((MAX_RESIDUE_IN_LINE-number_of_residues)*RESIDUE_LENGHT_IN_LINE != 0)
                ss << left << setw((MAX_RESIDUE_IN_LINE-number_of_residues)*RESIDUE_LENGHT_IN_LINE) << " ";
            ss << left << setw(19) << " ";
            stream << left << setw(6) << sites_->GetRecordName()
                   << left << setw(1) << " "
                   << right << setw(3) << sequence_number
                   << left << setw(1) << " "
                   << right << setw(3) << site->GetSiteId()
                   << left << setw(1) << " ";
            if(site->GetNumberOfResidues() != iNotSet)
                stream << right << setw(2) << site->GetNumberOfResidues();
            else
                stream << right << setw(2) << " ";
            stream << left << setw(63) << ss.str()
                   << endl;
            sequence_number++;
        }
    }
}
void PdbFile::ResolveSourceCard (std::ofstream & stream)
Definition at line 5120 of file pdbfile.cc.
{
}
void PdbFile::ResolveSplitCard (std::ofstream & stream)
Definition at line 4729 of file pdbfile.cc.
{
}
void PdbFile::ResolveSupersededEntriesCard (std::ofstream & stream)
Definition at line 5208 of file pdbfile.cc.
{
}
void PdbFile::ResolveTitleCard (std::ofstream & stream)
Definition at line 4689 of file pdbfile.cc.
{
    const int MAX_TITLE_LENGTH_IN_LINE = 70;
    stream << left << setw(6) << title_->GetRecordName()
           << left << setw(2) << " ";
    if((int)title_->GetTitle().length() > MAX_TITLE_LENGTH_IN_LINE)
    {
        stream << right << setw(2) << " "
               << left << setw(70) << title_->GetTitle().substr(0,MAX_TITLE_LENGTH_IN_LINE)
               << endl;
        int counter = ceil((double)(title_->GetTitle().length()) / MAX_TITLE_LENGTH_IN_LINE);
        for(int i = 2; i <= counter; i++)
        {
            if(i != counter)
            {
                stream << left << setw(6) << title_->GetRecordName()
                       << left << setw(2) << " "
                       << right << setw(2) << i
                       << left << setw(70) << title_->GetTitle().substr(MAX_TITLE_LENGTH_IN_LINE*(i-1), MAX_TITLE_LENGTH_IN_LINE)
                       << endl;
            }
            else
            {
                stream << left << setw(6) << title_->GetRecordName()
                       << left << setw(2) << " "
                       << right << setw(2) << i
                       << left << setw(70) << title_->GetTitle().substr(MAX_TITLE_LENGTH_IN_LINE*(i-1), title_->GetTitle().length()-MAX_TITLE_LENGTH_IN_LINE*(i-1))
                       << endl;
            }
        }
    }
    else
    {
        stream << right << setw(2) << " "
               << left << setw(70) << title_->GetTitle()
               << endl;
    }
}
void PdbFile::SetCompound (PdbCompoundCard * compound)
Definition at line 832 of file pdbfile.cc.
{
    compound_ = new PdbCompoundCard();
    compound_ = compound;
}
void PdbFile::SetConnectivities (PdbConnectCard * connectivities)
Definition at line 927 of file pdbfile.cc.
{
    connectivities_ = new PdbConnectCard();
    connectivities_ = connectivities;
}
void PdbFile::SetCrystallography (PdbCrystallographicCard * crystallography)
Definition at line 902 of file pdbfile.cc.
{
    crystallography_ = new PdbCrystallographicCard();
    crystallography_ = crystallography;
}
void PdbFile::SetDisulfideBonds (PdbDisulfideBondCard * disulfide_bonds)
Definition at line 887 of file pdbfile.cc.
{
    disulfide_bonds_ = new PdbDisulfideBondCard();\
    disulfide_bonds_ = disulfide_bonds;
}
void PdbFile::SetFormulas (PdbFormulaCard * formulas)
Definition at line 872 of file pdbfile.cc.
{
    formulas_ = new PdbFormulaCard();
    formulas_ = formulas;
}
void PdbFile::SetHeader (PdbHeaderCard * header)
Definition at line 821 of file pdbfile.cc.
{
    header_ = new PdbHeaderCard();
    header_ = header;
}
void PdbFile::SetHelixes (PdbHelixCard * helixes)
Definition at line 877 of file pdbfile.cc.
{
    helixes_ = new PdbHelixCard();
    helixes_ = helixes;
}
void PdbFile::SetHeterogens (PdbHeterogenCard * heterogens)
Definition at line 857 of file pdbfile.cc.
{
    heterogens_ = new PdbHeterogenCard();
    heterogens_ = heterogens;
}
void PdbFile::SetHeterogensName (PdbHeterogenNameCard * heterogens_name)
Definition at line 862 of file pdbfile.cc.
{
    heterogens_name_ = new PdbHeterogenNameCard();
    heterogens_name_ = heterogens_name;
}
void PdbFile::SetHeterogenSynonyms (PdbHeterogenSynonymCard * heterogen_synonyms)
Definition at line 867 of file pdbfile.cc.
{
    heterogen_synonyms_ = new PdbHeterogenSynonymCard();
    heterogen_synonyms_ = heterogen_synonyms;
}
void PdbFile::SetLinks (PdbLinkCard * links)
Definition at line 892 of file pdbfile.cc.
{
    links_ = new PdbLinkCard();
    links_ = links;
}
void PdbFile::SetMatrices (PdbMatrixNCard * matrices)
Definition at line 917 of file pdbfile.cc.
{
    matrices_ = new PdbMatrixNCard();
    matrices_ = matrices;
}
void PdbFile::SetModels (PdbModelCard * models)
Definition at line 922 of file pdbfile.cc.
Referenced by MolecularModeling::Assembly::BuildPdbFileStructureFromAssembly().
{
    models_ = new PdbModelCard();
    models_ = models;
}
void PdbFile::SetModelType (PdbModelTypeCard * model_type)
Definition at line 842 of file pdbfile.cc.
{
    model_type_ = new PdbModelTypeCard();
    model_type_ = model_type;
}
void PdbFile::SetNumberOfModels (PdbNumModelCard * number_of_models)
Definition at line 837 of file pdbfile.cc.
{
    number_of_models_ = new PdbNumModelCard();
    number_of_models_ = number_of_models;
}
void PdbFile::SetOrigins (PdbOriginXnCard * origins)
Definition at line 907 of file pdbfile.cc.
{
    origins_ = new PdbOriginXnCard();
    origins_ = origins;
}
void PdbFile::SetPath (std::string pdb_path)
Definition at line 817 of file pdbfile.cc.
{
    path_ = pdb_path;
}
void PdbFile::SetResidueModification (PdbResidueModificationCard * residue_modification)
Definition at line 852 of file pdbfile.cc.
{
    residue_modification_ = new PdbResidueModificationCard();
    residue_modification_ = residue_modification;
}
void PdbFile::SetResiduesSequence (PdbResidueSequenceCard * residues_sequence)
Definition at line 847 of file pdbfile.cc.
{
    residues_sequence_ = new PdbResidueSequenceCard();
    residues_sequence_ = residues_sequence;
}
void PdbFile::SetScales (PdbScaleNCard * scales)
Definition at line 912 of file pdbfile.cc.
{
    scales_ = new PdbScaleNCard();
    scales_ = scales;
}
void PdbFile::SetSequenceNumberMapping (PdbSequenceNumberMapping sequence_number_mapping)
Definition at line 942 of file pdbfile.cc.
{
    sequence_number_mapping_.clear();
    for(PdbSequenceNumberMapping::iterator it = sequence_number_mapping.begin(); it != sequence_number_mapping.end(); it++)
    {
        int mapped_sequence = (*it).first;
        int source_sequence = (*it).second;
        sequence_number_mapping_[mapped_sequence] = source_sequence;
    }
}
void PdbFile::SetSerialNumberMapping (PdbSerialNumberMapping serial_number_mapping)
Definition at line 932 of file pdbfile.cc.
{
    serial_number_mapping_.clear();
    for(PdbSerialNumberMapping::iterator it = serial_number_mapping.begin(); it != serial_number_mapping.end(); it++)
    {
        int source_serial = (*it).first;
        int mapped_serial = (*it).second;
        serial_number_mapping_[source_serial] = mapped_serial;
    }
}
void PdbFile::SetSheets (PdbSheetCard * sheets)
Definition at line 882 of file pdbfile.cc.
{
    sheets_ = new PdbSheetCard();
    sheets_ = sheets;
}
void PdbFile::SetSites (PdbSiteCard * sites)
Definition at line 897 of file pdbfile.cc.
{
    sites_ = new PdbSiteCard();
    sites_ = sites;
}
void PdbFile::SetTitle (PdbTitleCard * title)
Definition at line 827 of file pdbfile.cc.
Referenced by MolecularModeling::Assembly::BuildPdbFileStructureFromAssembly().
{
    title_ = new PdbTitleCard();
    title_ = title;
}
void PdbFile::SplitAtomCardOfModelCard (char split_point_chain_id, int split_point_sequence_number)
Definition at line 2663 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomCharge(), PdbFileSpace::PdbAtom::GetAtomElementSymbol(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomName(), PdbFileSpace::PdbAtom::GetAtomOccupancy(), PdbFileSpace::PdbAtom::GetAtomOrthogonalCoordinate(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomTempretureFactor(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbModel::GetModelSerialNumber(), PdbFileSpace::PdbAtomCard::GetRecordName(), PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), PdbFileSpace::PdbModel::SetModelResidueSet(), PdbFileSpace::PdbModel::SetModelSerialNumber(), and PdbFileSpace::PdbAtomCard::SetRecordName().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains(), PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChainsWithTheGivenModelNumber(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains().
{
    PdbModelCard::PdbModelMap models = models_->GetModels();
    PdbModelCard::PdbModelMap updated_models;
    for(PdbModelCard::PdbModelMap::iterator it = models.begin(); it != models.end(); it++)
    {
        PdbModel* model = (*it).second;
        PdbModel* updated_model = new PdbModel();
        updated_model->SetModelSerialNumber(model->GetModelSerialNumber());
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet* updated_residue_set = new PdbModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards;
        int serial_number = 1;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard* updated_atom_card_first_part = new PdbAtomCard();
            PdbAtomCard* updated_atom_card_second_part = new PdbAtomCard();
            updated_atom_card_first_part->SetRecordName(atom_card->GetRecordName());
            updated_atom_card_second_part->SetRecordName(atom_card->GetRecordName());
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap atoms_first_part;
            PdbAtomCard::PdbAtomMap atoms_second_part;
            bool located = false;
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                char residue_chain_id = atom->GetAtomChainId();
                int residue_sequence_number = atom->GetAtomResidueSequenceNumber();
                if(residue_chain_id == split_point_chain_id && residue_sequence_number == split_point_sequence_number)
                {
                    located = true;
                }
                if(located)
                {
                    serial_number++;
                    PdbAtom* updated_atom = new PdbAtom(serial_number, atom->GetAtomName(),atom->GetAtomAlternateLocation(), atom->GetAtomResidueName(),
                                                        atom->GetAtomChainId(), atom->GetAtomResidueSequenceNumber(), atom->GetAtomInsertionCode(), atom->GetAtomOrthogonalCoordinate(),
                                                        atom->GetAtomOccupancy(), atom->GetAtomTempretureFactor(), atom->GetAtomElementSymbol(), atom->GetAtomCharge());
                    atoms_second_part[serial_number] = updated_atom;
                }
                if(!located)
                {
                    PdbAtom* updated_atom = new PdbAtom(serial_number, atom->GetAtomName(),atom->GetAtomAlternateLocation(), atom->GetAtomResidueName(),
                                                        atom->GetAtomChainId(), atom->GetAtomResidueSequenceNumber(), atom->GetAtomInsertionCode(), atom->GetAtomOrthogonalCoordinate(),
                                                        atom->GetAtomOccupancy(), atom->GetAtomTempretureFactor(), atom->GetAtomElementSymbol(), atom->GetAtomCharge());
                    atoms_first_part[serial_number] = updated_atom;
                    serial_number++;
                }
            }
            updated_atom_card_first_part->SetAtoms(atoms_first_part);
            updated_atom_card_second_part->SetAtoms(atoms_second_part);
            if(atoms_first_part.size() > 0)
            {
                updated_atom_cards.push_back(updated_atom_card_first_part);
                serial_number++;
            }
            if(atoms_second_part.size() > 0)
            {
                updated_atom_cards.push_back(updated_atom_card_second_part);
                serial_number++;
            }
        }
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        updated_residue_set->SetAtoms(updated_atom_cards);
        updated_residue_set->SetHeterogenAtoms(heterogen_atom_cards);
        updated_model->SetModelResidueSet(updated_residue_set);
        updated_models[updated_model->GetModelSerialNumber()] = updated_model;
    }
    models_->SetModels(updated_models);
}
void PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber (char split_point_chain_id, int split_point_sequence_number, int model_number = 1)
Definition at line 2739 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomCharge(), PdbFileSpace::PdbAtom::GetAtomElementSymbol(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomName(), PdbFileSpace::PdbAtom::GetAtomOccupancy(), PdbFileSpace::PdbAtom::GetAtomOrthogonalCoordinate(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomTempretureFactor(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbModel::GetModelSerialNumber(), PdbFileSpace::PdbAtomCard::GetRecordName(), PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), PdbFileSpace::PdbModel::SetModelResidueSet(), PdbFileSpace::PdbModel::SetModelSerialNumber(), and PdbFileSpace::PdbAtomCard::SetRecordName().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    PdbModelCard::PdbModelMap models = models_->GetModels();
    if(models.size() != 0)
    {
        PdbModelCard::PdbModelMap updated_models;
        PdbModel* model = models[model_number];
        PdbModel* updated_model = new PdbModel();
        updated_model->SetModelSerialNumber(model->GetModelSerialNumber());
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet* updated_residue_set = new PdbModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards;
        int serial_number = 1;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard* updated_atom_card_first_part = new PdbAtomCard();
            PdbAtomCard* updated_atom_card_second_part = new PdbAtomCard();
            updated_atom_card_first_part->SetRecordName(atom_card->GetRecordName());
            updated_atom_card_second_part->SetRecordName(atom_card->GetRecordName());
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap atoms_first_part;
            PdbAtomCard::PdbAtomMap atoms_second_part;
            bool located = false;
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                char residue_chain_id = atom->GetAtomChainId();
                int residue_sequence_number = atom->GetAtomResidueSequenceNumber();
                if(residue_chain_id == split_point_chain_id && residue_sequence_number == split_point_sequence_number)
                {
                    located = true;
                }
                if(located)
                {
                    serial_number++;
                    PdbAtom* updated_atom = new PdbAtom(serial_number, atom->GetAtomName(),atom->GetAtomAlternateLocation(), atom->GetAtomResidueName(),
                                                        atom->GetAtomChainId(), atom->GetAtomResidueSequenceNumber(), atom->GetAtomInsertionCode(), atom->GetAtomOrthogonalCoordinate(),
                                                        atom->GetAtomOccupancy(), atom->GetAtomTempretureFactor(), atom->GetAtomElementSymbol(), atom->GetAtomCharge());
                    atoms_second_part[serial_number] = updated_atom;
                }
                if(!located)
                {
                    PdbAtom* updated_atom = new PdbAtom(serial_number, atom->GetAtomName(),atom->GetAtomAlternateLocation(), atom->GetAtomResidueName(),
                                                        atom->GetAtomChainId(), atom->GetAtomResidueSequenceNumber(), atom->GetAtomInsertionCode(), atom->GetAtomOrthogonalCoordinate(),
                                                        atom->GetAtomOccupancy(), atom->GetAtomTempretureFactor(), atom->GetAtomElementSymbol(), atom->GetAtomCharge());
                    atoms_first_part[serial_number] = updated_atom;
                    serial_number++;
                }
            }
            updated_atom_card_first_part->SetAtoms(atoms_first_part);
            updated_atom_card_second_part->SetAtoms(atoms_second_part);
            if(atoms_first_part.size() > 0)
            {
                updated_atom_cards.push_back(updated_atom_card_first_part);
                serial_number++;
            }
            if(atoms_second_part.size() > 0)
            {
                updated_atom_cards.push_back(updated_atom_card_second_part);
                serial_number++;
            }
        }
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        updated_residue_set->SetAtoms(updated_atom_cards);
        updated_residue_set->SetHeterogenAtoms(heterogen_atom_cards);
        updated_model->SetModelResidueSet(updated_residue_set);
        updated_models[updated_model->GetModelSerialNumber()] = updated_model;
        models_->SetModels(updated_models);
    }
}
void PdbFile::UpdateConnectCard ()
Definition at line 2815 of file pdbfile.cc.
{
    if(connectivities_ != NULL)
    {
        PdbConnectCard::BondedAtomsSerialNumbersMap bondedAtomsSerialNumbersMap = connectivities_->GetBondedAtomsSerialNumbers();
        PdbConnectCard::BondedAtomsSerialNumbersMap new_bonded_atoms_serial_numbers_map = PdbConnectCard::BondedAtomsSerialNumbersMap();
        for(PdbConnectCard::BondedAtomsSerialNumbersMap::iterator it = bondedAtomsSerialNumbersMap.begin(); it != bondedAtomsSerialNumbersMap.end(); it++)
        {
            int source_serial_number = (*it).first;
            vector<int> bonded_serial_numbers = (*it).second;
            if(serial_number_mapping_.find(source_serial_number) != serial_number_mapping_.end())
            {
                int new_source_serial_number = serial_number_mapping_[source_serial_number];
                new_bonded_atoms_serial_numbers_map[new_source_serial_number] = vector<int>();
                for(vector<int>::iterator it1 = bonded_serial_numbers.begin(); it1 != bonded_serial_numbers.end(); it1++)
                {
                    int bonded_serial_number = (*it1);
                    if(serial_number_mapping_.find(bonded_serial_number) != serial_number_mapping_.end())
                    {
                        int new_bonded_serial_number = serial_number_mapping_[bonded_serial_number];
                        new_bonded_atoms_serial_numbers_map[new_source_serial_number].push_back(new_bonded_serial_number);
                    }
                }
            }
        }
        connectivities_->SetBondedAtomsSerialNumbers(new_bonded_atoms_serial_numbers_map);
    }
}
void PdbFile::UpdateResidueName (PdbResidue * residue, std::string residue_name)
Definition at line 1883 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbResidue::GetResidueAlternateLocation(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), PdbFileSpace::PdbResidue::GetResidueName(), PdbFileSpace::PdbResidue::GetResidueSequenceNumber(), PdbFileSpace::PdbAtom::SetAtomResidueName(), PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbHeterogenAtomCard::SetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), and PdbFileSpace::PdbModel::SetModelResidueSet().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResidues(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMapping().
{
    string target_residue_name = residue->GetResidueName();
    char target_residue_chain_id = residue->GetResidueChainId();
    int target_residue_sequence_number = residue->GetResidueSequenceNumber();
    char target_residue_insertion_code = residue->GetResidueInsertionCode();
    char target_residue_alternate_location = residue->GetResidueAlternateLocation();
    stringstream ss;
    ss << target_residue_name << "_" << target_residue_chain_id << "_" << target_residue_sequence_number << "_" << target_residue_insertion_code << "_" << target_residue_alternate_location;
    string target_key = ss.str();
    PdbModelCard::PdbModelMap models = models_->GetModels();
    for(PdbModelCard::PdbModelMap::iterator it = models.begin();it != models.end(); it++)
    {
        PdbModel* model = (*it).second;
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap updated_atoms;
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int atom_sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << atom_sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(target_key.compare(key) == 0)
                {
                    atom->SetAtomResidueName(updated_residue_name);
                    updated_atoms[atom->GetAtomSerialNumber()] = atom;
                }
                else
                {
                    updated_atoms[atom->GetAtomSerialNumber()] = atom;
                }
            }
            atom_card->SetAtoms(updated_atoms);
            updated_atom_cards.push_back(atom_card);
        }
        residue_set->SetAtoms(updated_atom_cards);
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        PdbModelResidueSet::HeterogenAtomCardVector updated_heterogen_atom_cards;
        for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
        {
            PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
            PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
            PdbHeterogenAtomCard::PdbHeterogenAtomMap updated_heterogen_atoms;
            for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int heterogen_atom_sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << heterogen_atom_sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(target_key.compare(key) == 0)
                {
                    atom->SetAtomResidueName(updated_residue_name);
                    updated_heterogen_atoms[atom->GetAtomSerialNumber()] = atom;
                }
                else
                {
                    updated_heterogen_atoms[atom->GetAtomSerialNumber()] = atom;
                }
            }
            heterogen_atom_card->SetHeterogenAtoms(updated_heterogen_atoms);
            updated_heterogen_atom_cards.push_back(heterogen_atom_card);
        }
        residue_set->SetHeterogenAtoms(updated_heterogen_atom_cards);
        model->SetModelResidueSet(residue_set);
        (*it).second = model;
    }
    models_->SetModels(models);
}
void PdbFile::UpdateResidueNameWithTheGivenModelNumber (PdbResidue * residue, std::string residue_name, int model_number = 1)
Definition at line 1971 of file pdbfile.cc.
References PdbFileSpace::PdbAtom::GetAtomAlternateLocation(), PdbFileSpace::PdbAtom::GetAtomChainId(), PdbFileSpace::PdbAtom::GetAtomInsertionCode(), PdbFileSpace::PdbAtom::GetAtomResidueName(), PdbFileSpace::PdbAtom::GetAtomResidueSequenceNumber(), PdbFileSpace::PdbAtomCard::GetAtoms(), PdbFileSpace::PdbModelResidueSet::GetAtoms(), PdbFileSpace::PdbAtom::GetAtomSerialNumber(), PdbFileSpace::PdbHeterogenAtomCard::GetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::GetHeterogenAtoms(), PdbFileSpace::PdbModel::GetModelResidueSet(), PdbFileSpace::PdbResidue::GetResidueAlternateLocation(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), PdbFileSpace::PdbResidue::GetResidueName(), PdbFileSpace::PdbResidue::GetResidueSequenceNumber(), PdbFileSpace::PdbAtom::SetAtomResidueName(), PdbFileSpace::PdbModelResidueSet::SetAtoms(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbHeterogenAtomCard::SetHeterogenAtoms(), PdbFileSpace::PdbModelResidueSet::SetHeterogenAtoms(), and PdbFileSpace::PdbModel::SetModelResidueSet().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateHISMappingWithTheGivenNumber().
{
    string target_residue_name = residue->GetResidueName();
    char target_residue_chain_id = residue->GetResidueChainId();
    int target_residue_sequence_number = residue->GetResidueSequenceNumber();
    char target_residue_insertion_code = residue->GetResidueInsertionCode();
    char target_residue_alternate_location = residue->GetResidueAlternateLocation();
    stringstream ss;
    ss << target_residue_name << "_" << target_residue_chain_id << "_" << target_residue_sequence_number << "_" << target_residue_insertion_code << "_" << target_residue_alternate_location;
    string target_key = ss.str();
    PdbModelCard::PdbModelMap models = models_->GetModels();
    if(models.size() != 0)
    {
        PdbModel* model = models[model_number];
        PdbModelResidueSet* residue_set = model->GetModelResidueSet();
        PdbModelResidueSet::AtomCardVector atom_cards = residue_set->GetAtoms();
        PdbModelResidueSet::AtomCardVector updated_atom_cards;
        for(PdbModelResidueSet::AtomCardVector::iterator it1 = atom_cards.begin(); it1 != atom_cards.end(); it1++)
        {
            PdbAtomCard* atom_card = (*it1);
            PdbAtomCard::PdbAtomMap atoms = atom_card->GetAtoms();
            PdbAtomCard::PdbAtomMap updated_atoms;
            for(PdbAtomCard::PdbAtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int atom_sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << atom_sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(target_key.compare(key) == 0)
                {
                    atom->SetAtomResidueName(updated_residue_name);
                    updated_atoms[atom->GetAtomSerialNumber()] = atom;
                }
                else
                {
                    updated_atoms[atom->GetAtomSerialNumber()] = atom;
                }
            }
            atom_card->SetAtoms(updated_atoms);
            updated_atom_cards.push_back(atom_card);
        }
        residue_set->SetAtoms(updated_atom_cards);
        PdbModelResidueSet::HeterogenAtomCardVector heterogen_atom_cards = residue_set->GetHeterogenAtoms();
        PdbModelResidueSet::HeterogenAtomCardVector updated_heterogen_atom_cards;
        for(PdbModelResidueSet::HeterogenAtomCardVector::iterator it1 = heterogen_atom_cards.begin(); it1 != heterogen_atom_cards.end(); it1++)
        {
            PdbHeterogenAtomCard* heterogen_atom_card = (*it1);
            PdbHeterogenAtomCard::PdbHeterogenAtomMap heterogen_atoms = heterogen_atom_card->GetHeterogenAtoms();
            PdbHeterogenAtomCard::PdbHeterogenAtomMap updated_heterogen_atoms;
            for(PdbHeterogenAtomCard::PdbHeterogenAtomMap::iterator it2 = heterogen_atoms.begin(); it2 != heterogen_atoms.end(); it2++)
            {
                PdbAtom* atom = (*it2).second;
                string residue_name = atom->GetAtomResidueName();
                char chain_id = atom->GetAtomChainId();
                int heterogen_atom_sequence_number = atom->GetAtomResidueSequenceNumber();
                char insertion_code = atom->GetAtomInsertionCode();
                char alternate_location = atom->GetAtomAlternateLocation();
                stringstream sss;
                sss << residue_name << "_" << chain_id << "_" << heterogen_atom_sequence_number << "_" << insertion_code << "_" << alternate_location;
                string key = sss.str();
                if(target_key.compare(key) == 0)
                {
                    atom->SetAtomResidueName(updated_residue_name);
                    updated_heterogen_atoms[atom->GetAtomSerialNumber()] = atom;
                }
                else
                {
                    updated_heterogen_atoms[atom->GetAtomSerialNumber()] = atom;
                }
            }
            heterogen_atom_card->SetHeterogenAtoms(updated_heterogen_atoms);
            updated_heterogen_atom_cards.push_back(heterogen_atom_card);
        }
        residue_set->SetHeterogenAtoms(updated_heterogen_atom_cards);
        model->SetModelResidueSet(residue_set);
        models[model_number] = model;
        models_->SetModels(models);
    }
}
void PdbFile::Write (const std::string & pdb_file)
Close the parameter files
Definition at line 4445 of file pdbfile.cc.
{
    std::ofstream out_file;
    try
    {
        out_file.open(pdb_file.c_str());
    }
    catch(...)
    {
        throw PdbFileProcessingException(__LINE__,"File could not be created");
    }
    try
    {
        this->ResolveCards(out_file);
    }
    catch(...)
    {
        out_file.close();            /// Close the parameter files
    }
}
void PdbFile::WriteWithTheGivenModelNumber (const std::string & pdb_file, int model_number = 1)
Close the parameter files
Definition at line 4466 of file pdbfile.cc.
{
    std::ofstream out_file;
    try
    {
        out_file.open(pdb_file.c_str());
    }
    catch(...)
    {
        throw PdbFileProcessingException(__LINE__,"File could not be created");
    }
    try
    {
        this->ResolveCardsWithTheGivenModelNumber(out_file, model_number);
    }
    catch(...)
    {
        out_file.close();            /// Close the parameter files
    }
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbfile.hpp
src/FileSet/PdbFileSpace/pdbfile.cc