gmmlNew: PdbPreprocessorSpace::PdbPreprocessor Class Reference
PdbPreprocessorSpace::PdbPreprocessor Class Reference
#include <pdbpreprocessor.hpp>
Public Types
typedef std::vector
< PdbPreprocessorDisulfideBond * > PdbPreprocessorDisulfideBondVector
typedef std::vector
< PdbPreprocessorChainTermination * > PdbPreprocessorChainTerminationVector
typedef std::vector
< PdbPreprocessorHistidineMapping * > PdbPreprocessorHistidineMappingVector
typedef std::vector
< PdbPreprocessorMissingResidue * > PdbPreprocessorMissingResidueVector
typedef std::vector
< PdbPreprocessorUnrecognizedResidue * > PdbPreprocessorUnrecognizedResidueVector
typedef std::vector
< PdbPreprocessorUnrecognizedResidue * > PdbPreprocessorRecognizedResidueVector
typedef std::vector
< PdbPreprocessorUnrecognizedHeavyAtom * > PdbPreprocessorUnrecognizedHeavyAtomVector
typedef std::vector
< PdbPreprocessorReplacedHydrogen * > PdbPreprocessorReplacedHydrogenVector
typedef std::map< char,
std::vector< int > > PdbPreprocessorChainIdSequenceNumbersMap
typedef std::map< char,
std::vector< char > > PdbPreprocessorChainIdInsertionCodeMap
typedef std::map< std::string,
PdbPreprocessorAlternateResidue * > PdbPreprocessorAlternateResidueMap
typedef std::vector
< PdbFileSpace::PdbAtom * > PdbPreprocessorToBeDeletedAtomVector
typedef std::vector
< PdbFileSpace::PdbResidue * > PdbPreprocessorToBeDeletedResidueVector
typedef std::map< std::string,
PdbFileSpace::PdbFile::PdbResidueVector > PdbPreprocessorChainIdResidueMap
typedef std::map< std::string,
PdbPreprocessorResidueInfo * > PdbPreprocessorResidueInfoMap
Public Member Functions
PdbPreprocessor ()
PdbPreprocessorDisulfideBondVector GetDisulfideBonds ()
PdbPreprocessorChainTerminationVector GetChainTerminations ()
PdbPreprocessorHistidineMappingVector GetHistidineMappings ()
PdbPreprocessorMissingResidueVector GetMissingResidues ()
PdbPreprocessorUnrecognizedResidueVector GetUnrecognizedResidues ()
PdbPreprocessorRecognizedResidueVector GetRecognizedResidues ()
PdbPreprocessorUnrecognizedHeavyAtomVector GetUnrecognizedHeavyAtoms ()
PdbPreprocessorReplacedHydrogenVector GetReplacedHydrogens ()
PdbPreprocessorAlternateResidueMap GetAlternateResidueMap ()
PdbPreprocessorToBeDeletedAtomVector GetToBeDeletedAtoms ()
PdbPreprocessorToBeDeletedResidueVector GetToBeDeletedResidues ()
PdbPreprocessorResidueInfoMap GetResidueInfoMap ()
void SetDisulfideBonds (PdbPreprocessorDisulfideBondVector disulfide_bonds)
void AddDisulfideBond (PdbPreprocessorDisulfideBond *disulfide_bond)
void SetChainTerminations (PdbPreprocessorChainTerminationVector chain_terminations)
void AddChainTermination (PdbPreprocessorChainTermination *chain_termination)
void SetHistidineMappings (PdbPreprocessorHistidineMappingVector histidine_mappings)
void AddHistidineMapping (PdbPreprocessorHistidineMapping *histidnine_mapping)
void SetMissingResidues (PdbPreprocessorMissingResidueVector missing_residues)
void AddMissingResidue (PdbPreprocessorMissingResidue *missing_residue)
void SetUnrecognizedResidues (PdbPreprocessorUnrecognizedResidueVector unrecognized_residues)
void AddUnrecognizedResidue (PdbPreprocessorUnrecognizedResidue *unrecognized_residue)
void SetRecognizedResidues (PdbPreprocessorRecognizedResidueVector recognized_residues)
void AddRecognizedResidue (PdbPreprocessorUnrecognizedResidue *recognized_residue)
void SetUnrecognizedHeavyAtoms (PdbPreprocessorUnrecognizedHeavyAtomVector unrecognized_heavy_atoms)
void AddUnrecognizedHeavyAtom (PdbPreprocessorUnrecognizedHeavyAtom *unrecognized_heavy_atom)
void SetReplacedHydrogens (PdbPreprocessorReplacedHydrogenVector replaced_hydrogens)
void AddReplacedHydrogen (PdbPreprocessorReplacedHydrogen *replaced_hydrogen)
void SetToBeDeletedAtoms (PdbPreprocessorToBeDeletedAtomVector to_be_deleted_atoms)
void SetToBeDeletedResidues (PdbPreprocessorToBeDeletedResidueVector to_be_deleted_residues)
std::vector< std::string > GetUnrecognizedResidueNames (PdbFileSpace::PdbFile::PdbPairVectorAtomNamePositionFlag pdb_residue_names, std::vector< std::string > dataset_residue_names)
gmml::ResidueNameMap GetUnrecognizedResidueNamesMap (PdbFileSpace::PdbFile::PdbPairVectorAtomNamePositionFlag pdb_residue_names, gmml::ResidueNameMap dataset_residue_names)
std::vector< std::string > GetRecognizedResidueNames (PdbFileSpace::PdbFile::PdbPairVectorAtomNamePositionFlag pdb_residue_names, std::vector< std::string > dataset_residue_names)
gmml::ResidueNameMap GetRecognizedResidueNamesMap (PdbFileSpace::PdbFile::PdbPairVectorAtomNamePositionFlag pdb_residue_names, gmml::ResidueNameMap dataset_residue_names)
PdbFileSpace::PdbFile::PdbResidueVector GetUnrecognizedResidues (PdbFileSpace::PdbFile::PdbResidueVector pdb_residues, std::vector< std::string > unrecognized_residue_names)
PdbFileSpace::PdbFile::PdbResidueVector GetUnrecognizedResidues (PdbFileSpace::PdbFile::PdbResidueVector pdb_residues, gmml::ResidueNameMap unrecognized_residue_names)
PdbFileSpace::PdbFile::PdbResidueVector GetRecognizedResidues (PdbFileSpace::PdbFile::PdbResidueVector pdb_residues, std::vector< std::string > recognized_residue_names)
PdbFileSpace::PdbFile::PdbResidueVector GetRecognizedResidues (PdbFileSpace::PdbFile::PdbResidueVector pdb_residues, gmml::ResidueNameMap recognized_residue_names)
std::vector< std::string > GetAllResidueNamesFromMultipleLibFiles (std::vector< std::string > lib_files)
gmml::ResidueNameMap GetAllResidueNamesFromMultipleLibFilesMap (std::vector< std::string > lib_files)
LibraryFileSpace::LibraryFile::ResidueMap GetAllResiduesFromMultipleLibFilesMap (std::vector< std::string > lib_files)
PrepFileSpace::PrepFile::ResidueMap GetAllResiduesFromMultiplePrepFilesMap (std::vector< std::string > prep_files)
std::vector< std::string > GetAllResidueNamesFromMultiplePrepFiles (std::vector< std::string > prep_files)
gmml::ResidueNameMap GetAllResidueNamesFromMultiplePrepFilesMap (std::vector< std::string > prep_files)
std::vector< std::string > GetAllResidueNamesFromDatasetFiles (std::vector< std::string > lib_files, std::vector< std::string > prep_files)
gmml::ResidueNameMap GetAllResidueNamesFromDatasetFilesMap (std::vector< std::string > lib_files, std::vector< std::string > prep_files)
bool ExtractUnrecognizedResidues (std::string pdb_file_path, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
bool ExtractUnrecognizedResidues (PdbFileSpace::PdbFile *pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
void RemoveUnrecognizedResidues (PdbFileSpace::PdbFile *pdb_file, PdbPreprocessorUnrecognizedResidueVector unrecognized_residues)
void RemoveUnrecognizedResiduesWithTheGivenModelNumber (PdbFileSpace::PdbFile *pdb_file, PdbPreprocessorUnrecognizedResidueVector unrecognized_residues, int model_number=1)
bool ExtractRecognizedResidues (std::string pdb_file_path, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
bool ExtractRecognizedResidues (PdbFileSpace::PdbFile *pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
PdbFileSpace::PdbFile::PdbResidueVector GetAllCYSResidues (PdbFileSpace::PdbFile::PdbResidueVector pdb_residues)
double GetDistanceofCYS (PdbFileSpace::PdbResidue *first_residue, PdbFileSpace::PdbResidue *second_residue, PdbFileSpace::PdbFile *pdb_file, PdbFileSpace::PdbFile::PdbResidueAtomsMap residue_atom_map)
bool ExtractCYSResidues (std::string pdb_file_path)
bool ExtractCYSResidues (PdbFileSpace::PdbFile *pdb_file)
void UpdateCYSResidues (PdbFileSpace::PdbFile *pdb_file, PdbPreprocessorDisulfideBondVector disulfide_bonds)
void UpdateCYSResiduesWithTheGivenModelNumber (PdbFileSpace::PdbFile *pdb_file, PdbPreprocessorDisulfideBondVector disulfide_bonds, int model_number=1)
PdbFileSpace::PdbFile::PdbResidueVector GetAllHISResidues (PdbFileSpace::PdbFile::PdbResidueVector pdb_residues)
bool ExtractHISResidues (std::string pdb_file_path)
bool ExtractHISResidues (PdbFileSpace::PdbFile *pdb_file)
void UpdateHISMapping (PdbFileSpace::PdbFile *pdb_file, PdbPreprocessorHistidineMappingVector histidine_mappings)
void UpdateHISMappingWithTheGivenNumber (PdbFileSpace::PdbFile *pdb_file, PdbPreprocessorHistidineMappingVector histidine_mappings, int model_number=1)
std::vector< std::string > GetUnknownHeavyAtomNamesOfResidue (std::vector< std::string > pdb_atom_names_of_residue, std::vector< std::string > dataset_atom_names_of_residue)
std::vector< std::string > GetAllAtomNamesOfResidueFromMultipleLibFiles (std::string residue_name, std::vector< std::string > lib_files)
gmml::ResidueNameAtomNamesMap GetAllAtomNamesOfResidueNamesFromMultipleLibFiles (std::vector< std::string > lib_files)
std::vector< std::string > GetAllAtomNamesOfResidueFromMultiplePrepFiles (std::string residue_name, std::vector< std::string > prep_files)
gmml::ResidueNameAtomNamesMap GetAllAtomNamesOfResidueNamesFromMultiplePrepFiles (std::vector< std::string > prep_files)
std::vector< std::string > GetAllAtomNamesOfResidueFromDatasetFiles (std::string residue_name, std::vector< std::string > lib_files, std::vector< std::string > prep_files)
gmml::ResidueNameAtomNamesMap GetAllAtomNamesOfResidueNamesFromDatasetFiles (std::vector< std::string > lib_files, std::vector< std::string > prep_files)
PdbFileSpace::PdbFile::PdbAtomVector GetUnknownHeavyAtomsOfResidue (PdbFileSpace::PdbFile::PdbAtomVector pdb_atoms, std::vector< std::string > dataset_atom_names_of_residue)
bool ExtractUnknownHeavyAtoms (std::string pdb_file_path, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
bool ExtractUnknownHeavyAtoms (PdbFileSpace::PdbFile *pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
void RemoveUnknownHeavyAtoms (PdbFileSpace::PdbFile *pdb_file, PdbPreprocessorUnrecognizedHeavyAtomVector unknown_heavy_atoms)
void RemoveUnknownHeavyAtomsWithTheGivenModelNumber (PdbFileSpace::PdbFile *pdb_file, PdbPreprocessorUnrecognizedHeavyAtomVector unknown_heavy_atoms, int model_number=1)
void RemoveResiduesOfUnknownHeavyAtoms (PdbFileSpace::PdbFile *pdb_file, PdbPreprocessorUnrecognizedHeavyAtomVector unknown_heavy_atoms)
void RemoveResiduesOfUnknownHeavyAtomsWithTheGivenModelNumber (PdbFileSpace::PdbFile *pdb_file, PdbPreprocessorUnrecognizedHeavyAtomVector unknown_heavy_atoms, int model_number=1)
std::vector< std::string > GetRemovedHydrogenNamesOfResidue (std::vector< std::string > pdb_atom_names_of_residue, std::vector< std::string > dataset_atom_names_of_residue)
PdbFileSpace::PdbFile::PdbAtomVector GetRemovedHydrogensOfResidue (PdbFileSpace::PdbFile::PdbAtomVector pdb_atoms, std::vector< std::string > dataset_atom_names_of_residue)
bool ExtractRemovedHydrogens (std::string pdb_file_path, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
bool ExtractRemovedHydrogens (PdbFileSpace::PdbFile *pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
void RemoveRemovedHydrogens (PdbFileSpace::PdbFile *pdb_file, PdbPreprocessorReplacedHydrogenVector replaced_hydrogens)
void RemoveRemovedHydrogensWithTheGivenModelNumber (PdbFileSpace::PdbFile *pdb_file, PdbPreprocessorReplacedHydrogenVector replaced_hydrogens, int model_number=1)
bool ExtractAminoAcidChains (std::string pdb_file_path)
bool ExtractAminoAcidChains (std::string pdb_file_path, std::vector< std::string > amino_lib_files)
bool ExtractAminoAcidChains (PdbFileSpace::PdbFile *pdb_file)
bool ExtractAminoAcidChains (PdbFileSpace::PdbFile *pdb_file, std::vector< std::string > amino_lib_files)
void UpdateAminoAcidChains (PdbFileSpace::PdbFile *pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > prep_files, PdbPreprocessorChainTerminationVector chain_terminations)
void UpdateAminoAcidChainsWithTheGivenModelNumber (PdbFileSpace::PdbFile *pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > prep_files, PdbPreprocessorChainTerminationVector chain_terminations, int model_number=1)
bool ExtractGapsInAminoAcidChains (std::string pdb_file_path)
bool ExtractGapsInAminoAcidChains (std::string pdb_file_path, std::vector< std::string > amino_lib_files)
bool ExtractGapsInAminoAcidChains (PdbFileSpace::PdbFile *pdb_file)
bool ExtractGapsInAminoAcidChains (PdbFileSpace::PdbFile *pdb_file, std::vector< std::string > amino_lib_files)
void UpdateGapsInAminoAcidChains (PdbFileSpace::PdbFile *pdb_file, std::vector< std::string > amino_lib_files, PdbPreprocessorMissingResidueVector gaps)
void UpdateGapsInAminoAcidChainsWithTheGivenModelNumber (PdbFileSpace::PdbFile *pdb_file, std::vector< std::string > amino_lib_files, PdbPreprocessorMissingResidueVector gaps, int model_number=1)
LibraryFileSpace::LibraryFileResidue * GetLibraryResidueByNameFromMultipleLibraryFiles (std::string residue_name, std::vector< std::string > lib_files)
bool ExtractAlternateResidue (std::string pdb_file_path)
bool ExtractAlternateResidue (PdbFileSpace::PdbFile *pdb_file)
void RemoveUnselectedAlternateResidues (PdbFileSpace::PdbFile *pdb_file, PdbPreprocessorAlternateResidueMap alternate_residue_map)
void RemoveUnselectedAlternateResiduesWithTheGivenModelNumber (PdbFileSpace::PdbFile *pdb_file, PdbPreprocessorAlternateResidueMap alternate_residue_map, int model_number=1)
void Preprocess (PdbFileSpace::PdbFile *pdb_file, std::vector< std::string > amino_lib_files_path, std::vector< std::string > glycam_lib_files_path, std::vector< std::string > other_lib_files_path, std::vector< std::string > prep_files_path)
void ApplyPreprocessing (PdbFileSpace::PdbFile *pdb_file, std::vector< std::string > amino_lib_files_path, std::vector< std::string > glycam_lib_files_path, std::vector< std::string > prep_files_path)
void ApplyPreprocessingWithTheGivenModelNumber (PdbFileSpace::PdbFile *pdb_file, std::vector< std::string > amino_lib_files_path, std::vector< std::string > glycam_lib_files_path, std::vector< std::string > prep_files_path, int model_number=1)
void DeleteAllToBeDeletedEntities (PdbFileSpace::PdbFile *pdb_file)
void DeleteAllToBeDeletedEntitiesWithTheGivenModelNumber (PdbFileSpace::PdbFile *pdb_file, int model_number=1)
bool ExtractResidueInfo (std::string pdb_file_path, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_filess, std::vector< std::string > prep_files)
bool ExtractResidueInfo (PdbFileSpace::PdbFile *pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
double CalculateModelCharge (std::string pdb_file_path, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
double CalculateModelCharge (PdbFileSpace::PdbFile *pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 26 of file pdbpreprocessor.hpp.
Member Typedef Documentation
typedef std::map<std::string, PdbPreprocessorAlternateResidue*> PdbPreprocessorSpace::PdbPreprocessor::PdbPreprocessorAlternateResidueMap
Definition at line 75 of file pdbpreprocessor.hpp.
typedef std::map<char, std::vector<char> > PdbPreprocessorSpace::PdbPreprocessor::PdbPreprocessorChainIdInsertionCodeMap
Definition at line 71 of file pdbpreprocessor.hpp.
typedef std::map<std::string, PdbFileSpace::PdbFile::PdbResidueVector > PdbPreprocessorSpace::PdbPreprocessor::PdbPreprocessorChainIdResidueMap
Definition at line 87 of file pdbpreprocessor.hpp.
typedef std::map<char, std::vector<int> > PdbPreprocessorSpace::PdbPreprocessor::PdbPreprocessorChainIdSequenceNumbersMap
Definition at line 67 of file pdbpreprocessor.hpp.
typedef std::vector<PdbPreprocessorChainTermination*> PdbPreprocessorSpace::PdbPreprocessor::PdbPreprocessorChainTerminationVector
Definition at line 39 of file pdbpreprocessor.hpp.
typedef std::vector<PdbPreprocessorDisulfideBond*> PdbPreprocessorSpace::PdbPreprocessor::PdbPreprocessorDisulfideBondVector
Definition at line 35 of file pdbpreprocessor.hpp.
typedef std::vector<PdbPreprocessorHistidineMapping*> PdbPreprocessorSpace::PdbPreprocessor::PdbPreprocessorHistidineMappingVector
Definition at line 43 of file pdbpreprocessor.hpp.
typedef std::vector<PdbPreprocessorMissingResidue*> PdbPreprocessorSpace::PdbPreprocessor::PdbPreprocessorMissingResidueVector
Definition at line 47 of file pdbpreprocessor.hpp.
typedef std::vector<PdbPreprocessorUnrecognizedResidue*> PdbPreprocessorSpace::PdbPreprocessor::PdbPreprocessorRecognizedResidueVector
Definition at line 55 of file pdbpreprocessor.hpp.
typedef std::vector<PdbPreprocessorReplacedHydrogen*> PdbPreprocessorSpace::PdbPreprocessor::PdbPreprocessorReplacedHydrogenVector
Definition at line 63 of file pdbpreprocessor.hpp.
typedef std::map<std::string, PdbPreprocessorResidueInfo*> PdbPreprocessorSpace::PdbPreprocessor::PdbPreprocessorResidueInfoMap
Definition at line 91 of file pdbpreprocessor.hpp.
typedef std::vector<PdbFileSpace::PdbAtom*> PdbPreprocessorSpace::PdbPreprocessor::PdbPreprocessorToBeDeletedAtomVector
Definition at line 79 of file pdbpreprocessor.hpp.
typedef std::vector<PdbFileSpace::PdbResidue*> PdbPreprocessorSpace::PdbPreprocessor::PdbPreprocessorToBeDeletedResidueVector
Definition at line 83 of file pdbpreprocessor.hpp.
typedef std::vector<PdbPreprocessorUnrecognizedHeavyAtom*> PdbPreprocessorSpace::PdbPreprocessor::PdbPreprocessorUnrecognizedHeavyAtomVector
Definition at line 59 of file pdbpreprocessor.hpp.
typedef std::vector<PdbPreprocessorUnrecognizedResidue*> PdbPreprocessorSpace::PdbPreprocessor::PdbPreprocessorUnrecognizedResidueVector
Definition at line 51 of file pdbpreprocessor.hpp.
Constructor & Destructor Documentation
PdbPreprocessor::PdbPreprocessor ()
Definition at line 34 of file pdbpreprocessor.cc.
{}
Member Function Documentation
void PdbPreprocessor::AddChainTermination (PdbPreprocessorChainTermination * chain_termination)
Definition at line 98 of file pdbpreprocessor.cc.
{
    chain_terminations_.push_back(chain_termination);
}
void PdbPreprocessor::AddDisulfideBond (PdbPreprocessorDisulfideBond * disulfide_bond)
Definition at line 87 of file pdbpreprocessor.cc.
{
    disulfide_bonds_.push_back(disulfide_bond);
}
void PdbPreprocessor::AddHistidineMapping (PdbPreprocessorHistidineMapping * histidnine_mapping)
Definition at line 109 of file pdbpreprocessor.cc.
{
    histidine_mappings_.push_back(histidine_mapping);
}
void PdbPreprocessor::AddMissingResidue (PdbPreprocessorMissingResidue * missing_residue)
Definition at line 120 of file pdbpreprocessor.cc.
{
    missing_residues_.push_back(missing_residue);
}
void PdbPreprocessor::AddRecognizedResidue (PdbPreprocessorUnrecognizedResidue * recognized_residue)
Definition at line 142 of file pdbpreprocessor.cc.
{
    recognized_residues_.push_back(recognized_residue);
}
void PdbPreprocessor::AddReplacedHydrogen (PdbPreprocessorReplacedHydrogen * replaced_hydrogen)
Definition at line 164 of file pdbpreprocessor.cc.
{
    replaced_hydrogens_.push_back(replaced_hydrogen);
}
void PdbPreprocessor::AddUnrecognizedHeavyAtom (PdbPreprocessorUnrecognizedHeavyAtom * unrecognized_heavy_atom)
Definition at line 153 of file pdbpreprocessor.cc.
{
    unrecognized_heavy_atoms_.push_back(unrecognized_heavy_atom);
}
void PdbPreprocessor::AddUnrecognizedResidue (PdbPreprocessorUnrecognizedResidue * unrecognized_residue)
Definition at line 131 of file pdbpreprocessor.cc.
{
    unrecognized_residues_.push_back(unrecognized_residue);
}
void PdbPreprocessor::ApplyPreprocessing (PdbFileSpace::PdbFile * pdb_file, std::vector< std::string > amino_lib_files_path, std::vector< std::string > glycam_lib_files_path, std::vector< std::string > prep_files_path)
Definition at line 3603 of file pdbpreprocessor.cc.
{
    time_t t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Start to apply changes ..." << endl;
    UpdateHISMapping(pdb_file,this->GetHistidineMappings());
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "HIS residues update: done" << endl;
    UpdateCYSResidues(pdb_file, this->GetDisulfideBonds());
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "CYS residues update: done" << endl;
    RemoveUnselectedAlternateResidues(pdb_file,this->GetAlternateResidueMap());
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Unselected alternate residues removed: done" << endl;
    RemoveUnrecognizedResidues(pdb_file, this->GetUnrecognizedResidues());
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Remove unrecognized residues: done" << endl;
    RemoveResiduesOfUnknownHeavyAtoms(pdb_file, this->GetUnrecognizedHeavyAtoms());
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Unknown heavy atoms removed: done" << endl;
    RemoveRemovedHydrogens(pdb_file, this->GetReplacedHydrogens());
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Removed hydrogens removed: done" << endl;
    UpdateAminoAcidChains(pdb_file, amino_lib_files_path, glycam_lib_files_path, prep_files_path, this->GetChainTerminations());
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Amino acid chains update: done" << endl;
    UpdateGapsInAminoAcidChains(pdb_file, amino_lib_files_path, this->GetMissingResidues());
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Gaps in amino acid chains update: done" << endl;
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Applying changes done" << endl;
}
void PdbPreprocessor::ApplyPreprocessingWithTheGivenModelNumber (PdbFileSpace::PdbFile * pdb_file, std::vector< std::string > amino_lib_files_path, std::vector< std::string > glycam_lib_files_path, std::vector< std::string > prep_files_path, int model_number = 1)
Definition at line 3635 of file pdbpreprocessor.cc.
{
    time_t t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Start to apply changes ..." << endl;
    UpdateHISMappingWithTheGivenNumber(pdb_file,this->GetHistidineMappings(), model_number);
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "HIS residues update: done" << endl;
    UpdateCYSResiduesWithTheGivenModelNumber(pdb_file, this->GetDisulfideBonds());
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "CYS residues update: done" << endl;
    RemoveUnselectedAlternateResiduesWithTheGivenModelNumber(pdb_file,this->GetAlternateResidueMap(), model_number);
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Unselected alternate residues removed: done" << endl;
    RemoveUnrecognizedResiduesWithTheGivenModelNumber(pdb_file, this->GetUnrecognizedResidues(), model_number);
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Remove unrecognized residues: done" << endl;
    RemoveResiduesOfUnknownHeavyAtomsWithTheGivenModelNumber(pdb_file, this->GetUnrecognizedHeavyAtoms(), model_number);
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Unknown heavy atoms removed: done" << endl;
    RemoveRemovedHydrogensWithTheGivenModelNumber(pdb_file, this->GetReplacedHydrogens(), model_number);
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Removed hydrogens removed: done" << endl;
    UpdateAminoAcidChainsWithTheGivenModelNumber(pdb_file, amino_lib_files_path, glycam_lib_files_path, prep_files_path, this->GetChainTerminations(), model_number);
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Amino acid chains update: done" << endl;
    UpdateGapsInAminoAcidChainsWithTheGivenModelNumber(pdb_file, amino_lib_files_path, this->GetMissingResidues(), model_number);
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Gaps in amino acid chains update: done" << endl;
    t = time(0);
    cout << std::asctime(std::localtime(&t)) << "Applying changes done" << endl;
}
double PdbPreprocessorSpace::PdbPreprocessor::CalculateModelCharge (std::string pdb_file_path, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
double PdbPreprocessorSpace::PdbPreprocessor::CalculateModelCharge (PdbFileSpace::PdbFile * pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
void PdbPreprocessor::DeleteAllToBeDeletedEntities (PdbFileSpace::PdbFile * pdb_file)
Definition at line 3278 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbFile::DeleteAtoms(), and PdbFileSpace::PdbFile::DeleteResidues().
{
    if(to_be_deleted_atoms_.size() != 0)
        pdb_file->DeleteAtoms(to_be_deleted_atoms_);
    if(to_be_deleted_residues_.size() != 0)
        pdb_file->DeleteResidues(to_be_deleted_residues_);
}
void PdbPreprocessor::DeleteAllToBeDeletedEntitiesWithTheGivenModelNumber (PdbFileSpace::PdbFile * pdb_file, int model_number = 1)
Definition at line 3286 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), and PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber().
{
    if(to_be_deleted_atoms_.size() != 0)
        pdb_file->DeleteAtomsWithTheGivenModelNumber(to_be_deleted_atoms_, model_number);
    if(to_be_deleted_residues_.size() != 0)
        pdb_file->DeleteResiduesWithTheGivenModelNumber(to_be_deleted_residues_, model_number);
}
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractAlternateResidue (std::string pdb_file_path)
bool PdbPreprocessor::ExtractAlternateResidue (PdbFileSpace::PdbFile * pdb_file)
Definition at line 3169 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbFile::GetAllResidues(), PdbFileSpace::PdbResidue::GetResidueAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::GetResidueAlternateLocation(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), PdbFileSpace::PdbResidue::GetResidueName(), PdbFileSpace::PdbResidue::GetResidueSequenceNumber(), PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::GetSelectedAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::SetResidueAlternateLocation(), and PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::SetSelectedAlternateLocation().
{
    PdbFileSpace::PdbFile::PdbResidueVector pdb_residues = pdb_file->GetAllResidues();
    for(PdbFileSpace::PdbFile::PdbResidueVector::iterator it = pdb_residues.begin(); it != pdb_residues.end(); it++)
    {
        PdbFileSpace::PdbResidue* target_residue = *it;
        string target_residue_name = target_residue->GetResidueName();
        char target_chain_id = target_residue->GetResidueChainId();
        int target_sequence_number = target_residue->GetResidueSequenceNumber();
        char target_insertion_code = target_residue->GetResidueInsertionCode();
        char target_alternate_location = target_residue->GetResidueAlternateLocation();
        stringstream ss;
        ss << target_residue_name << "_" << target_chain_id << "_" << target_sequence_number << "_" << target_insertion_code;
        string target_key = ss.str();
        for(PdbFileSpace::PdbFile::PdbResidueVector::iterator it1 =it+1 ; it1 != pdb_residues.end(); it1++)
        {
            PdbFileSpace::PdbResidue* residue = *it1;
            string residue_name = residue->GetResidueName();
            char chain_id = residue->GetResidueChainId();
            int sequence_number = residue->GetResidueSequenceNumber();
            char insertion_code = residue->GetResidueInsertionCode();
            char alternate_location = residue->GetResidueAlternateLocation();
            stringstream sss;
            sss << residue_name << "_" << chain_id << "_" << sequence_number << "_" << insertion_code;
            string key = sss.str();
            if(key.compare(target_key) == 0)
            {
                if(target_alternate_location != alternate_location)
                {
                    if (alternate_residue_map_.empty() || distance(alternate_residue_map_.begin() ,alternate_residue_map_.find(key)) < 0 ||
                            distance(alternate_residue_map_.begin() ,alternate_residue_map_.find(key)) >= (int)alternate_residue_map_.size())
                    {
                        vector<bool> selected = vector<bool>();
                        selected.push_back(true);
                        selected.push_back(false);
                        vector<char> alternate_locations = vector<char>();
                        alternate_locations.push_back(target_alternate_location);
                        alternate_locations.push_back(alternate_location);
                        alternate_residue_map_[target_key] = new PdbPreprocessorAlternateResidue(residue_name, chain_id, sequence_number, insertion_code, alternate_locations, selected);
                    }
                    else
                    {
                        PdbPreprocessorAlternateResidue* alternate_residue = alternate_residue_map_[target_key];
                        vector<char> alternate_locations = alternate_residue->GetResidueAlternateLocation();
                        if(distance(alternate_locations.begin(), find(alternate_locations.begin(),alternate_locations.end(),alternate_location)) < 0 ||
                                distance(alternate_locations.begin(), find(alternate_locations.begin(),alternate_locations.end(),alternate_location)) >= (int)alternate_locations.size())
{
                            alternate_locations.push_back(alternate_location);
                            alternate_residue->SetResidueAlternateLocation(alternate_locations);
                            vector<bool> selected_alternate_locations = alternate_residue->GetSelectedAlternateLocation();
                            selected_alternate_locations.push_back(false);
                            alternate_residue->SetSelectedAlternateLocation(selected_alternate_locations);
                        }
                    }
                }
            }
        }
    }
    return true;
}
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractAminoAcidChains (std::string pdb_file_path)
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractAminoAcidChains (std::string pdb_file_path, std::vector< std::string > amino_lib_files)
bool PdbPreprocessor::ExtractAminoAcidChains (PdbFileSpace::PdbFile * pdb_file)
Definition at line 2089 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbFile::GetAllResiduesFromAtomCard(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), and PdbFileSpace::PdbResidue::GetResidueSequenceNumber().
{
    PdbFileSpace::PdbFile::PdbResidueVector pdb_residues = pdb_file->GetAllResiduesFromAtomCard();
    PdbPreprocessor::PdbPreprocessorChainIdSequenceNumbersMap chain_map_sequence_number;
    PdbPreprocessor::PdbPreprocessorChainIdInsertionCodeMap chain_map_insertion_code;
    for(PdbFileSpace::PdbFile::PdbResidueVector::iterator it = pdb_residues.begin(); it != pdb_residues.end(); it++)
    {
        PdbFileSpace::PdbResidue* residue = *it;
        char chain_id = residue->GetResidueChainId();
        int sequence_number = residue->GetResidueSequenceNumber();
        char insertion_code = residue->GetResidueInsertionCode();
        chain_map_sequence_number[chain_id].push_back(sequence_number);
        chain_map_insertion_code[chain_id].push_back(insertion_code);
    }
    for(PdbPreprocessorChainIdSequenceNumbersMap::iterator it = chain_map_sequence_number.begin(); it != chain_map_sequence_number.end(); it++)
    {
        char chain_id = (*it).first;
        vector<int> sequence_numbers = (*it).second;
        vector<char> insertion_codes = chain_map_insertion_code[chain_id];
        vector<int>::iterator starting_sequence_number_iterator = min_element(sequence_numbers.begin(), sequence_numbers.end());
        vector<int>::iterator ending_sequence_number_iterator = max_element(sequence_numbers.begin(), sequence_numbers.end());
        int starting_index = distance(sequence_numbers.begin(), starting_sequence_number_iterator);
        int ending_index = distance(sequence_numbers.begin(), ending_sequence_number_iterator);
        PdbPreprocessorChainTermination* chain = new PdbPreprocessorChainTermination(chain_id, *starting_sequence_number_iterator, *ending_sequence_number_iterator,
                                                                                     insertion_codes.at(starting_index), insertion_codes.at(ending_index) );
        chain_terminations_.push_back(chain);
    }
    return true;
}
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractAminoAcidChains (PdbFileSpace::PdbFile * pdb_file, std::vector< std::string > amino_lib_files)
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractCYSResidues (std::string pdb_file_path)
bool PdbPreprocessor::ExtractCYSResidues (PdbFileSpace::PdbFile * pdb_file)
Definition at line 953 of file pdbpreprocessor.cc.
References gmml::dSulfurCutoff, PdbFileSpace::PdbFile::GetAllAtomsOfResidues(), PdbFileSpace::PdbFile::GetAllResiduesFromAtomCard(), PdbFileSpace::PdbResidue::GetResidueAlternateLocation(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), and PdbFileSpace::PdbResidue::GetResidueSequenceNumber().
{
    PdbFileSpace::PdbFile::PdbResidueVector pdb_residues = pdb_file->GetAllResiduesFromAtomCard();
    PdbFileSpace::PdbFile::PdbResidueVector cys_residues = GetAllCYSResidues(pdb_residues);
    PdbFile::PdbResidueAtomsMap residue_atom_map = pdb_file->GetAllAtomsOfResidues();
    for(PdbFileSpace::PdbFile::PdbResidueVector::iterator it = cys_residues.begin(); it != cys_residues.end(); it++)
    {
        PdbResidue* first_residue = (*it);
        for(PdbFileSpace::PdbFile::PdbResidueVector::iterator it1 = it+1 ; it1 != cys_residues.end(); it1++)
        {
            PdbResidue* second_residue = (*it1);
            double distance = GetDistanceofCYS(first_residue, second_residue, pdb_file, residue_atom_map);
            if (distance < dSulfurCutoff)
            {
                PdbPreprocessorDisulfideBond* disulfide_bond =
                        new PdbPreprocessorDisulfideBond(first_residue->GetResidueChainId(), second_residue->GetResidueChainId(),
                                                         first_residue->GetResidueSequenceNumber(), second_residue->GetResidueSequenceNumber(),
                                                         distance, true, first_residue->GetResidueInsertionCode(), second_residue->GetResidueInsertionCode(),
                                                         first_residue->GetResidueAlternateLocation(), second_residue->GetResidueAlternateLocation() );
                disulfide_bonds_.push_back(disulfide_bond);
            }
        }
    }
    return true;
}
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractGapsInAminoAcidChains (std::string pdb_file_path)
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractGapsInAminoAcidChains (std::string pdb_file_path, std::vector< std::string > amino_lib_files)
bool PdbPreprocessor::ExtractGapsInAminoAcidChains (PdbFileSpace::PdbFile * pdb_file)
Definition at line 2655 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbFile::GetAllResiduesFromAtomCard(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), and PdbFileSpace::PdbResidue::GetResidueSequenceNumber().
{
    PdbFileSpace::PdbFile::PdbResidueVector pdb_residues = pdb_file->GetAllResiduesFromAtomCard();
    PdbPreprocessor::PdbPreprocessorChainIdSequenceNumbersMap chain_map_sequence_number;
    PdbPreprocessor::PdbPreprocessorChainIdInsertionCodeMap chain_map_insertion_code;
    for(PdbFileSpace::PdbFile::PdbResidueVector::iterator it = pdb_residues.begin(); it != pdb_residues.end(); it++)
    {
        PdbFileSpace::PdbResidue* residue = *it;
        char chain_id = residue->GetResidueChainId();
        int sequence_number = residue->GetResidueSequenceNumber();
        char insertion_code = residue->GetResidueInsertionCode();
        chain_map_sequence_number[chain_id].push_back(sequence_number);
        chain_map_insertion_code[chain_id].push_back(insertion_code);
    }
    for(PdbPreprocessorChainIdSequenceNumbersMap::iterator it = chain_map_sequence_number.begin(); it != chain_map_sequence_number.end(); it++)
    {
        char chain_id = (*it).first;
        vector<int> sequence_numbers = (*it).second;
        vector<char> insertion_codes = chain_map_insertion_code[chain_id];
        int starting_sequence_number = *min_element(sequence_numbers.begin(), sequence_numbers.end());
        int ending_sequence_number = *max_element(sequence_numbers.begin(), sequence_numbers.end());
        for(unsigned int i = 0; i < sequence_numbers.size() - 1; i++)
        {
            if(sequence_numbers.at(i) == sequence_numbers.at(i+1) || (sequence_numbers.at(i) + 1) == sequence_numbers.at(i+1))
            {
            }
            else
            {
                PdbPreprocessorMissingResidue* missing_residues = new PdbPreprocessorMissingResidue(chain_id, starting_sequence_number,
                                                                                                    ending_sequence_number, sequence_numbers.at(i),
                                                                                                    sequence_numbers.at(i+1), insertion_codes.at(i), insertion_codes.at(i+1));
                missing_residues_.push_back(missing_residues);
            }
        }
    }
    return true;
}
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractGapsInAminoAcidChains (PdbFileSpace::PdbFile * pdb_file, std::vector< std::string > amino_lib_files)
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractHISResidues (std::string pdb_file_path)
bool PdbPreprocessor::ExtractHISResidues (PdbFileSpace::PdbFile * pdb_file)
Definition at line 1148 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbFile::GetAllResiduesFromAtomCard(), PdbFileSpace::PdbFile::GetAtomOfResidueByName(), PdbFileSpace::PdbResidue::GetResidueAlternateLocation(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), PdbFileSpace::PdbResidue::GetResidueSequenceNumber(), gmml::HID, gmml::HIE, and gmml::HIP.
{
    PdbFileSpace::PdbFile::PdbResidueVector pdb_residues = pdb_file->GetAllResiduesFromAtomCard();
    PdbFileSpace::PdbFile::PdbResidueVector his_residues = GetAllHISResidues(pdb_residues);
    for(PdbFileSpace::PdbFile::PdbResidueVector::iterator it = his_residues.begin(); it != his_residues.end(); it++)
    {
        PdbResidue* his_residue = (*it);
        // HIE residue
        if(pdb_file->GetAtomOfResidueByName(his_residue, "HE2") != NULL && pdb_file->GetAtomOfResidueByName(his_residue, "HD1") == NULL)
        {
            PdbPreprocessorHistidineMapping* histidine_mapping =
                    new PdbPreprocessorHistidineMapping(his_residue->GetResidueChainId(), his_residue->GetResidueSequenceNumber(), HIE,
                                                        his_residue->GetResidueInsertionCode(), his_residue->GetResidueAlternateLocation());
            histidine_mappings_.push_back(histidine_mapping);
        }
        // HID residue
        else if(pdb_file->GetAtomOfResidueByName(his_residue, "HE2") == NULL && pdb_file->GetAtomOfResidueByName(his_residue, "HD1") != NULL)
        {
            PdbPreprocessorHistidineMapping* histidine_mapping =
                    new PdbPreprocessorHistidineMapping(his_residue->GetResidueChainId(), his_residue->GetResidueSequenceNumber(), HID,
                                                        his_residue->GetResidueInsertionCode(), his_residue->GetResidueAlternateLocation());
            histidine_mappings_.push_back(histidine_mapping);
        }
        // HIP residue
        else if(pdb_file->GetAtomOfResidueByName(his_residue, "HE2") != NULL && pdb_file->GetAtomOfResidueByName(his_residue, "HD1") != NULL)
        {
            PdbPreprocessorHistidineMapping* histidine_mapping =
                    new PdbPreprocessorHistidineMapping(his_residue->GetResidueChainId(), his_residue->GetResidueSequenceNumber(), HIP,
                                                        his_residue->GetResidueInsertionCode(), his_residue->GetResidueAlternateLocation());
            histidine_mappings_.push_back(histidine_mapping);
        }
        else if(pdb_file->GetAtomOfResidueByName(his_residue, "HE2") == NULL && pdb_file->GetAtomOfResidueByName(his_residue, "HD1") == NULL)
        {
            PdbPreprocessorHistidineMapping* histidine_mapping =
                    new PdbPreprocessorHistidineMapping(his_residue->GetResidueChainId(), his_residue->GetResidueSequenceNumber(), HIE,
                                                        his_residue->GetResidueInsertionCode(), his_residue->GetResidueAlternateLocation());
            histidine_mappings_.push_back(histidine_mapping);
        }
    }
    return true;
}
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractRecognizedResidues (std::string pdb_file_path, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractRecognizedResidues (PdbFileSpace::PdbFile * pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractRemovedHydrogens (std::string pdb_file_path, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractRemovedHydrogens (PdbFileSpace::PdbFile * pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractResidueInfo (std::string pdb_file_path, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_filess, std::vector< std::string > prep_files)
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractResidueInfo (PdbFileSpace::PdbFile * pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractUnknownHeavyAtoms (std::string pdb_file_path, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractUnknownHeavyAtoms (PdbFileSpace::PdbFile * pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractUnrecognizedResidues (std::string pdb_file_path, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
bool PdbPreprocessorSpace::PdbPreprocessor::ExtractUnrecognizedResidues (PdbFileSpace::PdbFile * pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > other_lib_files, std::vector< std::string > prep_files)
vector< string > PdbPreprocessor::GetAllAtomNamesOfResidueFromDatasetFiles (std::string residue_name, std::vector< std::string > lib_files, std::vector< std::string > prep_files)
Definition at line 1436 of file pdbpreprocessor.cc.
{
    vector<string> all_atom_names_of_residue_from_lib = GetAllAtomNamesOfResidueFromMultipleLibFiles(residue_name, lib_files);
    vector<string> all_atom_names_of_residue_from_prep = GetAllAtomNamesOfResidueFromMultiplePrepFiles(residue_name, prep_files);
    vector<string> all_atom_names;
    for(vector<string>::iterator it1 = all_atom_names_of_residue_from_lib.begin(); it1 != all_atom_names_of_residue_from_lib.end(); it1++)
    {
        all_atom_names.push_back(*it1);
    }
    for(vector<string>::iterator it1 = all_atom_names_of_residue_from_prep.begin(); it1 != all_atom_names_of_residue_from_prep.end(); it1++)
    {
        all_atom_names.push_back(*it1);
    }
    return all_atom_names;
}
vector< string > PdbPreprocessor::GetAllAtomNamesOfResidueFromMultipleLibFiles (std::string residue_name, std::vector< std::string > lib_files)
Definition at line 1354 of file pdbpreprocessor.cc.
References LibraryFileSpace::LibraryFile::GetAllAtomNamesOfResidue(), and LibraryFileSpace::LibraryFile::GetAllResidueNames().
{
    vector<string> all_atom_names_of_residue;
    vector<string> residue_names;
    for(vector<string>::iterator it = lib_files.begin(); it != lib_files.end(); it++)
    {
        LibraryFileSpace::LibraryFile* lib_file = new LibraryFileSpace::LibraryFile(*it);
        residue_names = lib_file->GetAllResidueNames();
        if(find(residue_names.begin(), residue_names.end(), residue_name) != residue_names.end())
        {
            all_atom_names_of_residue = lib_file->GetAllAtomNamesOfResidue(residue_name);
            break;
        }
    }
    return all_atom_names_of_residue;
}
vector< string > PdbPreprocessor::GetAllAtomNamesOfResidueFromMultiplePrepFiles (std::string residue_name, std::vector< std::string > prep_files)
Definition at line 1396 of file pdbpreprocessor.cc.
References PrepFileSpace::PrepFile::GetAllAtomNamesOfResidue(), and PrepFileSpace::PrepFile::GetAllResidueNames().
{
    vector<string> all_atom_names_of_residue;
    vector<string> residue_names;
    for(vector<string>::iterator it = prep_files.begin(); it != prep_files.end(); it++)
    {
        PrepFileSpace::PrepFile* prep_file = new PrepFileSpace::PrepFile(*it);
        residue_names = prep_file->GetAllResidueNames();
        if(find(residue_names.begin(), residue_names.end(), residue_name) != residue_names.end())
        {
            all_atom_names_of_residue = prep_file->GetAllAtomNamesOfResidue(residue_name);
            break;
        }
    }
    return all_atom_names_of_residue;
}
ResidueNameAtomNamesMap PdbPreprocessor::GetAllAtomNamesOfResidueNamesFromDatasetFiles (std::vector< std::string > lib_files, std::vector< std::string > prep_files)
Definition at line 1452 of file pdbpreprocessor.cc.
{
    ResidueNameAtomNamesMap all_residue_atom_map = ResidueNameAtomNamesMap();
    ResidueNameAtomNamesMap all_residue_atom_map_from_lib = GetAllAtomNamesOfResidueNamesFromMultipleLibFiles(lib_files);
    ResidueNameAtomNamesMap all_residue_atom_map_from_prep = GetAllAtomNamesOfResidueNamesFromMultiplePrepFiles(prep_files);
    for(ResidueNameAtomNamesMap::iterator it = all_residue_atom_map_from_lib.begin(); it != all_residue_atom_map_from_lib.end(); it++)
    {
        string residue_name = (*it).first;
        vector<string> atom_names = (*it).second;
        all_residue_atom_map[residue_name] = atom_names;
    }
    for(ResidueNameAtomNamesMap::iterator it = all_residue_atom_map_from_prep.begin(); it != all_residue_atom_map_from_prep.end(); it++)
    {
        string residue_name = (*it).first;
        vector<string> atom_names = (*it).second;
        all_residue_atom_map[residue_name] = atom_names;
    }
    return all_residue_atom_map;
}
ResidueNameAtomNamesMap PdbPreprocessor::GetAllAtomNamesOfResidueNamesFromMultipleLibFiles (std::vector< std::string > lib_files)
Definition at line 1372 of file pdbpreprocessor.cc.
References LibraryFileSpace::LibraryFileResidue::GetAtoms(), LibraryFileSpace::LibraryFileAtom::GetName(), and LibraryFileSpace::LibraryFile::GetResidues().
{
    ResidueNameAtomNamesMap residue_atom_map = ResidueNameAtomNamesMap();
    LibraryFileSpace::LibraryFile::ResidueMap residues;
    for(vector<string>::iterator it = lib_files.begin(); it != lib_files.end(); it++)
    {
        LibraryFileSpace::LibraryFile* lib_file = new LibraryFileSpace::LibraryFile(*it);
        residues = lib_file->GetResidues();
        for(LibraryFileSpace::LibraryFile::ResidueMap::iterator it1 = residues.begin(); it1 != residues.end(); it1++)
        {
            string residue_name = (*it1).first;
            LibraryFileSpace::LibraryFileResidue* residue = (*it1).second;
            LibraryFileSpace::LibraryFileResidue::AtomMap atoms = residue->GetAtoms();
            for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                LibraryFileSpace::LibraryFileAtom* atom = (*it2).second;
                string atom_name = atom->GetName();
                residue_atom_map[residue_name].push_back(atom_name);
            }
        }
    }
    return residue_atom_map;
}
ResidueNameAtomNamesMap PdbPreprocessor::GetAllAtomNamesOfResidueNamesFromMultiplePrepFiles (std::vector< std::string > prep_files)
Definition at line 1413 of file pdbpreprocessor.cc.
References PrepFileSpace::PrepFileResidue::GetAtoms(), PrepFileSpace::PrepFileAtom::GetName(), and PrepFileSpace::PrepFile::GetResidues().
{
    ResidueNameAtomNamesMap residue_atom_map = ResidueNameAtomNamesMap();
    for(vector<string>::iterator it = prep_files.begin(); it != prep_files.end(); it++)
    {
        PrepFileSpace::PrepFile* prep_file = new PrepFileSpace::PrepFile(*it);
        PrepFileSpace::PrepFile::ResidueMap residues = prep_file->GetResidues();
        for(PrepFileSpace::PrepFile::ResidueMap::iterator it1 = residues.begin(); it1 != residues.end(); it1++)
        {
            string residue_name = (*it1).first;
            PrepFileSpace::PrepFileResidue* residue = (*it1).second;
            PrepFileSpace::PrepFileResidue::PrepFileAtomVector atoms = residue->GetAtoms();
            for(PrepFileSpace::PrepFileResidue::PrepFileAtomVector::iterator it2 = atoms.begin(); it2 != atoms.end(); it2++)
            {
                PrepFileSpace::PrepFileAtom* atom = (*it2);
                string atom_name = atom->GetName();
                residue_atom_map[residue_name].push_back(atom_name);
            }
        }
    }
    return residue_atom_map;
}
PdbFileSpace::PdbFile::PdbResidueVector PdbPreprocessor::GetAllCYSResidues (PdbFileSpace::PdbFile::PdbResidueVector pdb_residues)
Definition at line 897 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbResidue::GetResidueName().
{
    PdbFileSpace::PdbFile::PdbResidueVector all_cys_residues;
    for(PdbFileSpace::PdbFile::PdbResidueVector::iterator it = pdb_residues.begin(); it != pdb_residues.end(); it++)
    {
        PdbResidue* pdb_residue = (*it);
        string pdb_residue_name = pdb_residue->GetResidueName();
        if((pdb_residue_name).compare("CYS") == 0)
        {
            all_cys_residues.push_back(pdb_residue);
        }
    }
    return all_cys_residues;
}
PdbFileSpace::PdbFile::PdbResidueVector PdbPreprocessor::GetAllHISResidues (PdbFileSpace::PdbFile::PdbResidueVector pdb_residues)
Definition at line 1089 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbResidue::GetResidueName().
{
    PdbFileSpace::PdbFile::PdbResidueVector all_his_residues;
    for(PdbFileSpace::PdbFile::PdbResidueVector::iterator it = pdb_residues.begin(); it != pdb_residues.end(); it++)
    {
        PdbResidue* pdb_residue = (*it);
        string pdb_residue_name = pdb_residue->GetResidueName();
        if((pdb_residue_name).compare("HIS") == 0)
        {
            all_his_residues.push_back(pdb_residue);
        }
    }
    return all_his_residues;
}
vector< string > PdbPreprocessor::GetAllResidueNamesFromDatasetFiles (std::vector< std::string > lib_files, std::vector< std::string > prep_files)
Definition at line 522 of file pdbpreprocessor.cc.
{
    vector<string> all_lib_residue_names = GetAllResidueNamesFromMultipleLibFiles(lib_files);
    vector<string> all_prep_residue_names = GetAllResidueNamesFromMultiplePrepFiles(prep_files);
    vector<string> all_residue_names;
    for(vector<string>::iterator it1 = all_lib_residue_names.begin(); it1 != all_lib_residue_names.end(); it1++)
    {
        all_residue_names.push_back(*it1);
    }
    for(vector<string>::iterator it1 = all_prep_residue_names.begin(); it1 != all_prep_residue_names.end(); it1++)
    {
        all_residue_names.push_back(*it1);
    }
    return all_residue_names;
}
ResidueNameMap PdbPreprocessor::GetAllResidueNamesFromDatasetFilesMap (std::vector< std::string > lib_files, std::vector< std::string > prep_files)
Definition at line 538 of file pdbpreprocessor.cc.
{
    ResidueNameMap all_lib_residue_names = GetAllResidueNamesFromMultipleLibFilesMap(lib_files);
    ResidueNameMap all_prep_residue_names = GetAllResidueNamesFromMultiplePrepFilesMap(prep_files);
    ResidueNameMap all_residue_names = ResidueNameMap();
    for(ResidueNameMap::iterator it1 = all_lib_residue_names.begin(); it1 != all_lib_residue_names.end(); it1++)
    {
        string key = (*it1).first;
        string val = (*it1).second;
        all_residue_names[key] = val;
    }
    for(ResidueNameMap::iterator it1 = all_prep_residue_names.begin(); it1 != all_prep_residue_names.end(); it1++)
    {
        string key = (*it1).first;
        string val = (*it1).second;
        all_residue_names[key] = val;
    }
    return all_residue_names;
}
vector< string > PdbPreprocessor::GetAllResidueNamesFromMultipleLibFiles (std::vector< std::string > lib_files)
Definition at line 424 of file pdbpreprocessor.cc.
References LibraryFileSpace::LibraryFile::GetAllResidueNames().
{
    vector<string> all_residue_names;
    for(vector<string>::iterator it = lib_files.begin(); it != lib_files.end(); it++)
    {
        LibraryFileSpace::LibraryFile* lib_file = new LibraryFileSpace::LibraryFile(*it);
        vector<string> residue_names = lib_file->GetAllResidueNames();
        for(vector<string>::iterator it1 = residue_names.begin(); it1 != residue_names.end(); it1++)
        {
            all_residue_names.push_back(*it1);
        }
    }
    return all_residue_names;
}
ResidueNameMap PdbPreprocessor::GetAllResidueNamesFromMultipleLibFilesMap (std::vector< std::string > lib_files)
Definition at line 439 of file pdbpreprocessor.cc.
References LibraryFileSpace::LibraryFile::GetAllResidueNames().
{
    ResidueNameMap all_residue_names;
    vector<string> residue_names;
    for(vector<string>::iterator it = lib_files.begin(); it != lib_files.end(); it++)
    {
        LibraryFileSpace::LibraryFile* lib_file = new LibraryFileSpace::LibraryFile(*it);
        residue_names = lib_file->GetAllResidueNames();
        for(vector<string>::iterator it1 = residue_names.begin(); it1 != residue_names.end(); it1++)
        {
            string residue_name = (*it1);
            all_residue_names[residue_name] = (residue_name);
        }
    }
    return all_residue_names;
}
vector< string > PdbPreprocessor::GetAllResidueNamesFromMultiplePrepFiles (std::vector< std::string > prep_files)
Definition at line 489 of file pdbpreprocessor.cc.
References PrepFileSpace::PrepFile::GetAllResidueNames().
{
    vector<string> all_residue_names;
    vector<string> residue_names;
    for(vector<string>::iterator it = prep_files.begin(); it != prep_files.end(); it++)
    {
        PrepFileSpace::PrepFile* prep_file = new PrepFileSpace::PrepFile(*it);
        residue_names = prep_file->GetAllResidueNames();
        for(vector<string>::iterator it1 = residue_names.begin(); it1 != residue_names.end(); it1++)
        {
            all_residue_names.push_back(*it1);
        }
    }
    return all_residue_names;
}
ResidueNameMap PdbPreprocessor::GetAllResidueNamesFromMultiplePrepFilesMap (std::vector< std::string > prep_files)
Definition at line 505 of file pdbpreprocessor.cc.
References PrepFileSpace::PrepFile::GetAllResidueNames().
{
    ResidueNameMap all_residue_names;
    vector<string> residue_names;
    for(vector<string>::iterator it = prep_files.begin(); it != prep_files.end(); it++)
    {
        PrepFileSpace::PrepFile* prep_file = new PrepFileSpace::PrepFile(*it);
        residue_names = prep_file->GetAllResidueNames();
        for(vector<string>::iterator it1 = residue_names.begin(); it1 != residue_names.end(); it1++)
        {
            string residue_name = (*it1);
            all_residue_names[residue_name] = residue_name;
        }
    }
    return all_residue_names;
}
LibraryFileSpace::LibraryFile::ResidueMap PdbPreprocessor::GetAllResiduesFromMultipleLibFilesMap (std::vector< std::string > lib_files)
Definition at line 456 of file pdbpreprocessor.cc.
References LibraryFileSpace::LibraryFile::GetResidues().
{
    LibraryFileSpace::LibraryFile::ResidueMap all_residues;
    LibraryFileSpace::LibraryFile::ResidueMap residues;
    for(vector<string>::iterator it = lib_files.begin(); it != lib_files.end(); it++)
    {
        LibraryFileSpace::LibraryFile* lib_file = new LibraryFileSpace::LibraryFile(*it);
        residues = lib_file->GetResidues();
        for(LibraryFileSpace::LibraryFile::ResidueMap::iterator it1 = residues.begin(); it1 != residues.end(); it1++)
        {
            string lib_residue_name = (*it1).first;
            all_residues[lib_residue_name] = (*it1).second;
        }
    }
    return all_residues;
}
PrepFileSpace::PrepFile::ResidueMap PdbPreprocessor::GetAllResiduesFromMultiplePrepFilesMap (std::vector< std::string > prep_files)
Definition at line 472 of file pdbpreprocessor.cc.
References PrepFileSpace::PrepFile::GetResidues().
{
    PrepFileSpace::PrepFile::ResidueMap all_residues;
    PrepFileSpace::PrepFile::ResidueMap residues;
    for(vector<string>::iterator it = prep_files.begin(); it != prep_files.end(); it++)
    {
        PrepFileSpace::PrepFile* prep_file = new PrepFileSpace::PrepFile(*it);
        residues = prep_file->GetResidues();
        for(PrepFileSpace::PrepFile::ResidueMap::iterator it1 = residues.begin(); it1 != residues.end(); it1++)
        {
            string prep_residue_name = (*it1).first;
            all_residues[prep_residue_name] = (*it1).second;
        }
    }
    return all_residues;
}
PdbPreprocessor::PdbPreprocessorAlternateResidueMap PdbPreprocessor::GetAlternateResidueMap ()
Definition at line 64 of file pdbpreprocessor.cc.
{
    return alternate_residue_map_;
}
PdbPreprocessor::PdbPreprocessorChainTerminationVector PdbPreprocessor::GetChainTerminations ()
Definition at line 43 of file pdbpreprocessor.cc.
{
    return chain_terminations_;
}
double PdbPreprocessor::GetDistanceofCYS (PdbFileSpace::PdbResidue * first_residue, PdbFileSpace::PdbResidue * second_residue, PdbFileSpace::PdbFile * pdb_file, PdbFileSpace::PdbFile::PdbResidueAtomsMap residue_atom_map)
Definition at line 912 of file pdbpreprocessor.cc.
References Geometry::Coordinate::Distance(), PdbFileSpace::PdbFile::GetAtomOfResidueByName(), and PdbFileSpace::PdbAtom::GetAtomOrthogonalCoordinate().
{
    double distance = 0.0;
    PdbAtom* first_residue_sulfur_atom = pdb_file->GetAtomOfResidueByName(first_residue, "SG", residue_atom_map);
    PdbAtom* second_residue_sulfur_atom = pdb_file->GetAtomOfResidueByName(second_residue, "SG", residue_atom_map);
    if(first_residue_sulfur_atom != NULL && second_residue_sulfur_atom != NULL)
        distance = first_residue_sulfur_atom->GetAtomOrthogonalCoordinate().Distance(second_residue_sulfur_atom->GetAtomOrthogonalCoordinate());
    return distance;
}
PdbPreprocessor::PdbPreprocessorDisulfideBondVector PdbPreprocessor::GetDisulfideBonds ()
Definition at line 40 of file pdbpreprocessor.cc.
{
    return disulfide_bonds_;
}
PdbPreprocessor::PdbPreprocessorHistidineMappingVector PdbPreprocessor::GetHistidineMappings ()
Definition at line 46 of file pdbpreprocessor.cc.
{
    return histidine_mappings_;
}
LibraryFileSpace::LibraryFileResidue * PdbPreprocessor::GetLibraryResidueByNameFromMultipleLibraryFiles (std::string residue_name, std::vector< std::string > lib_files)
Definition at line 3089 of file pdbpreprocessor.cc.
References LibraryFileSpace::LibraryFile::GetLibraryResidueByResidueName().
{
    LibraryFileSpace::LibraryFileResidue* library_residue = new LibraryFileSpace::LibraryFileResidue();
    for(vector<string>::iterator it = lib_files.begin(); it != lib_files.end(); it++)
    {
        LibraryFileSpace::LibraryFile* lib_file = new LibraryFileSpace::LibraryFile(*it);
        library_residue = lib_file->GetLibraryResidueByResidueName(residue_name);
        if(library_residue != NULL)
            break;
    }
    return library_residue;
}
PdbPreprocessor::PdbPreprocessorMissingResidueVector PdbPreprocessor::GetMissingResidues ()
Definition at line 49 of file pdbpreprocessor.cc.
{
    return missing_residues_;
}
vector< string > PdbPreprocessor::GetRecognizedResidueNames (PdbFileSpace::PdbFile::PdbPairVectorAtomNamePositionFlag pdb_residue_names, std::vector< std::string > dataset_residue_names)
Definition at line 278 of file pdbpreprocessor.cc.
{
    vector<string> recognized_residue_names;
    pair<string, string> residue_name_flag;
    string pdb_residue_name;
    string pdb_residue_position_flag;
    for(PdbFile::PdbPairVectorAtomNamePositionFlag::iterator it = pdb_residue_names.begin(); it != pdb_residue_names.end(); it++)
    {
        residue_name_flag = *it;
        pdb_residue_name = residue_name_flag.first;
        pdb_residue_position_flag = residue_name_flag.second;
        if(pdb_residue_name.compare("HIS") != 0)
        {
            if(find(dataset_residue_names.begin(), dataset_residue_names.end(), pdb_residue_name) != dataset_residue_names.end())
            {
                recognized_residue_names.push_back(pdb_residue_name);
            }
            else
            {
                if(pdb_residue_position_flag.compare("S") == 0)
                {
                    stringstream ss;
                    ss << "N" << pdb_residue_name;
                    string n_terminal_pdb_residue_name = ss.str();
                    if(find(dataset_residue_names.begin(), dataset_residue_names.end(), n_terminal_pdb_residue_name) != dataset_residue_names.end())
                        recognized_residue_names.push_back(pdb_residue_name);
                }
                else if(pdb_residue_position_flag.compare("E") == 0)
                {
                    stringstream ss;
                    ss << "C" << pdb_residue_name;
                    string c_terminal_pdb_residue_name = ss.str();
                    if(find(dataset_residue_names.begin(), dataset_residue_names.end(), c_terminal_pdb_residue_name) != dataset_residue_names.end())
                        recognized_residue_names.push_back(pdb_residue_name);
                }
            }
        }
        else
        {
            recognized_residue_names.push_back(pdb_residue_name);
        }
    }
    cout << "HIS residue(s) found" << endl;
    return recognized_residue_names;
}
ResidueNameMap PdbPreprocessor::GetRecognizedResidueNamesMap (PdbFileSpace::PdbFile::PdbPairVectorAtomNamePositionFlag pdb_residue_names, gmml::ResidueNameMap dataset_residue_names)
Definition at line 324 of file pdbpreprocessor.cc.
{
    ResidueNameMap recognized_residue_names = ResidueNameMap();
    pair<string, string> residue_name_flag;
    string pdb_residue_name;
    string pdb_residue_position_flag;
    for(PdbFile::PdbPairVectorAtomNamePositionFlag::iterator it = pdb_residue_names.begin(); it != pdb_residue_names.end(); it++)
    {
        residue_name_flag = *it;
        pdb_residue_name = residue_name_flag.first;
        pdb_residue_position_flag = residue_name_flag.second;
        if(pdb_residue_name.compare("HIS") != 0)
        {
            if(dataset_residue_names.find(pdb_residue_name) != dataset_residue_names.end())
            {
                recognized_residue_names[pdb_residue_name] = pdb_residue_name;
            }
            else
            {
                if(pdb_residue_position_flag.compare("S") == 0)
                {
                    stringstream ss;
                    ss << "N" << pdb_residue_name;
                    string n_terminal_pdb_residue_name = ss.str();
                    if(dataset_residue_names.find(n_terminal_pdb_residue_name) != dataset_residue_names.end())
                        recognized_residue_names[pdb_residue_name] = pdb_residue_name;
                }
                else if(pdb_residue_position_flag.compare("E") == 0)
                {
                    stringstream ss;
                    ss << "C" << pdb_residue_name;
                    string c_terminal_pdb_residue_name = ss.str();
                    if(dataset_residue_names.find(c_terminal_pdb_residue_name) != dataset_residue_names.end())
                        recognized_residue_names[pdb_residue_name] = pdb_residue_name;
                }
            }
        }
        else
        {
            recognized_residue_names[pdb_residue_name] = pdb_residue_name;
        }
    }
    cout << "HIS residue(s) found" << endl;
    return recognized_residue_names;
}
PdbPreprocessor::PdbPreprocessorRecognizedResidueVector PdbPreprocessor::GetRecognizedResidues ()
Definition at line 55 of file pdbpreprocessor.cc.
{
    return recognized_residues_;
}
PdbFileSpace::PdbFile::PdbResidueVector PdbPreprocessorSpace::PdbPreprocessor::GetRecognizedResidues (PdbFileSpace::PdbFile::PdbResidueVector pdb_residues, std::vector< std::string > recognized_residue_names)
PdbFileSpace::PdbFile::PdbResidueVector PdbPreprocessor::GetRecognizedResidues (PdbFileSpace::PdbFile::PdbResidueVector pdb_residues, gmml::ResidueNameMap recognized_residue_names)
Definition at line 411 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbResidue::GetResidueName().
{
    PdbFileSpace::PdbFile::PdbResidueVector recognized_residues;
    for(PdbFileSpace::PdbFile::PdbResidueVector::iterator it = pdb_residues.begin(); it != pdb_residues.end(); it++)
    {
        PdbResidue* pdb_residue = *it;
        string pdb_residue_name = pdb_residue->GetResidueName();
        if(recognized_residue_names.find(pdb_residue_name) != recognized_residue_names.end())
            recognized_residues.push_back(pdb_residue);
    }
    return recognized_residues;
}
vector< string > PdbPreprocessor::GetRemovedHydrogenNamesOfResidue (std::vector< std::string > pdb_atom_names_of_residue, std::vector< std::string > dataset_atom_names_of_residue)
Definition at line 1768 of file pdbpreprocessor.cc.
{
    vector<string> removed_hydrogen_names_of_residue;
    for(vector<string>::iterator it = pdb_atom_names_of_residue.begin(); it != pdb_atom_names_of_residue.end(); it++)
    {
        string pdb_atom_name = (*it);
        if((pdb_atom_name.substr(0,1).compare("H") == 0 ||
            (pdb_atom_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(pdb_atom_name.substr(0,1))))))
        {
            if(find(dataset_atom_names_of_residue.begin(), dataset_atom_names_of_residue.end(), pdb_atom_name) == dataset_atom_names_of_residue.end())
            {
                removed_hydrogen_names_of_residue.push_back(pdb_atom_name);
            }
        }
    }
    return removed_hydrogen_names_of_residue;
}
PdbFileSpace::PdbFile::PdbAtomVector PdbPreprocessor::GetRemovedHydrogensOfResidue (PdbFileSpace::PdbFile::PdbAtomVector pdb_atoms, std::vector< std::string > dataset_atom_names_of_residue)
Definition at line 1786 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbAtom::GetAtomName().
{
    PdbFile::PdbAtomVector removed_hydrogens_of_residue;
    for(PdbFile::PdbAtomVector::iterator it = pdb_atoms.begin(); it != pdb_atoms.end(); it++)
    {
        PdbAtom* pdb_atom = *it;
        string pdb_atom_name = pdb_atom->GetAtomName();
        if((pdb_atom_name.substr(0,1).compare("H") == 0 ||
            (pdb_atom_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(pdb_atom_name.substr(0,1))))))
        {
            if(find(dataset_atom_names_of_residue.begin(), dataset_atom_names_of_residue.end(), pdb_atom_name) == dataset_atom_names_of_residue.end())
                removed_hydrogens_of_residue.push_back(pdb_atom);
        }
    }
    return removed_hydrogens_of_residue;
}
PdbPreprocessor::PdbPreprocessorReplacedHydrogenVector PdbPreprocessor::GetReplacedHydrogens ()
Definition at line 61 of file pdbpreprocessor.cc.
{
    return replaced_hydrogens_;
}
PdbPreprocessor::PdbPreprocessorResidueInfoMap PdbPreprocessor::GetResidueInfoMap ()
Definition at line 73 of file pdbpreprocessor.cc.
{
    return residue_info_map_;
}
PdbPreprocessor::PdbPreprocessorToBeDeletedAtomVector PdbPreprocessor::GetToBeDeletedAtoms ()
Definition at line 67 of file pdbpreprocessor.cc.
{
    return to_be_deleted_atoms_;
}
PdbPreprocessor::PdbPreprocessorToBeDeletedResidueVector PdbPreprocessor::GetToBeDeletedResidues ()
Definition at line 70 of file pdbpreprocessor.cc.
{
    return to_be_deleted_residues_;
}
vector< string > PdbPreprocessor::GetUnknownHeavyAtomNamesOfResidue (std::vector< std::string > pdb_atom_names_of_residue, std::vector< std::string > dataset_atom_names_of_residue)
Definition at line 1338 of file pdbpreprocessor.cc.
{
    vector<string> unknown_heavy_atom_names_of_residue;
    for(vector<string>::iterator it = pdb_atom_names_of_residue.begin(); it != pdb_atom_names_of_residue.end(); it++)
    {
        string pdb_atom_name = (*it);
        if(!(pdb_atom_name.substr(0,1).compare("H") == 0 ||
             (pdb_atom_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(pdb_atom_name.substr(0,1))))))
        {
            if(find(dataset_atom_names_of_residue.begin(), dataset_atom_names_of_residue.end(), pdb_atom_name) == dataset_atom_names_of_residue.end())
                unknown_heavy_atom_names_of_residue.push_back(pdb_atom_name);
        }
    }
    return unknown_heavy_atom_names_of_residue;
}
PdbFileSpace::PdbFile::PdbAtomVector PdbPreprocessor::GetUnknownHeavyAtomsOfResidue (PdbFileSpace::PdbFile::PdbAtomVector pdb_atoms, std::vector< std::string > dataset_atom_names_of_residue)
Definition at line 1472 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbAtom::GetAtomName().
{
    PdbFile::PdbAtomVector unknown_heavy_atoms_of_residue;
    for(PdbFile::PdbAtomVector::iterator it = pdb_atoms.begin(); it != pdb_atoms.end(); it++)
    {
        PdbAtom* pdb_atom = *it;
        string pdb_atom_name = pdb_atom->GetAtomName();
        if(!(pdb_atom_name.substr(0,1).compare("H") == 0 ||
             (pdb_atom_name.substr(1,1).compare("H") == 0 && isdigit(ConvertString<char>(pdb_atom_name.substr(0,1))))))
        {
            if(!(find(dataset_atom_names_of_residue.begin(), dataset_atom_names_of_residue.end(), pdb_atom_name) != dataset_atom_names_of_residue.end()))
            {
                unknown_heavy_atoms_of_residue.push_back(pdb_atom);
            }
        }
    }
    return unknown_heavy_atoms_of_residue;
}
PdbPreprocessor::PdbPreprocessorUnrecognizedHeavyAtomVector PdbPreprocessor::GetUnrecognizedHeavyAtoms ()
Definition at line 58 of file pdbpreprocessor.cc.
{
    return unrecognized_heavy_atoms_;
}
vector< string > PdbPreprocessor::GetUnrecognizedResidueNames (PdbFileSpace::PdbFile::PdbPairVectorAtomNamePositionFlag pdb_residue_names, std::vector< std::string > dataset_residue_names)
Definition at line 188 of file pdbpreprocessor.cc.
{
    vector<string> unrecognized_residue_names;
    pair<string, string> residue_name_flag;
    string pdb_residue_name;
    string pdb_residue_position_flag;
    for(PdbFile::PdbPairVectorAtomNamePositionFlag::iterator it = pdb_residue_names.begin(); it != pdb_residue_names.end(); it++)
    {
        residue_name_flag = *it;
        pdb_residue_name = residue_name_flag.first;
        pdb_residue_position_flag = residue_name_flag.second;
        if(pdb_residue_name.compare("HIS") != 0 )
        {
            if(find(dataset_residue_names.begin(), dataset_residue_names.end(), pdb_residue_name) != dataset_residue_names.end())
            {
            }
            else
            {
                if(pdb_residue_position_flag.compare("S") == 0)
                {
                    stringstream ss;
                    ss << "N" << pdb_residue_name;
                    string n_terminal_pdb_residue_name = ss.str();
                    if(find(dataset_residue_names.begin(), dataset_residue_names.end(), n_terminal_pdb_residue_name) == dataset_residue_names.end())
                        unrecognized_residue_names.push_back(pdb_residue_name);
                }
                else if(pdb_residue_position_flag.compare("E") == 0)
                {
                    stringstream ss;
                    ss << "C" << pdb_residue_name;
                    string c_terminal_pdb_residue_name = ss.str();
                    if(find(dataset_residue_names.begin(), dataset_residue_names.end(), c_terminal_pdb_residue_name) == dataset_residue_names.end())
                        unrecognized_residue_names.push_back(pdb_residue_name);
                }
                else
                {
                    unrecognized_residue_names.push_back(pdb_residue_name);
                }
            }
        }
    }
    cout << "HIS residue(s) found" << endl;
    return unrecognized_residue_names;
}
ResidueNameMap PdbPreprocessor::GetUnrecognizedResidueNamesMap (PdbFileSpace::PdbFile::PdbPairVectorAtomNamePositionFlag pdb_residue_names, gmml::ResidueNameMap dataset_residue_names)
Definition at line 233 of file pdbpreprocessor.cc.
{
    ResidueNameMap unrecognized_residue_names = ResidueNameMap();
    pair<string, string> residue_name_flag;
    string pdb_residue_name;
    string pdb_residue_position_flag;
    for(PdbFile::PdbPairVectorAtomNamePositionFlag::iterator it = pdb_residue_names.begin(); it != pdb_residue_names.end(); it++)
    {
        residue_name_flag = *it;
        pdb_residue_name = residue_name_flag.first;
        pdb_residue_position_flag = residue_name_flag.second;
        if(pdb_residue_name.compare("HIS") != 0 )
        {
            if(dataset_residue_names.find(pdb_residue_name) != dataset_residue_names.end())
            {
            }
            else
            {
                if(pdb_residue_position_flag.compare("S") == 0)
                {
                    stringstream ss;
                    ss << "N" << pdb_residue_name;
                    string n_terminal_pdb_residue_name = ss.str();
                    if(dataset_residue_names.find(n_terminal_pdb_residue_name) == dataset_residue_names.end())
                        unrecognized_residue_names[pdb_residue_name] = pdb_residue_name;
                }
                else if(pdb_residue_position_flag.compare("E") == 0)
                {
                    stringstream ss;
                    ss << "C" << pdb_residue_name;
                    string c_terminal_pdb_residue_name = ss.str();
                    if(dataset_residue_names.find(c_terminal_pdb_residue_name) == dataset_residue_names.end())
                        unrecognized_residue_names[pdb_residue_name] = pdb_residue_name;
                }
                else
                {
                    unrecognized_residue_names[pdb_residue_name] = pdb_residue_name;
                }
            }
        }
    }
    cout << "HIS residue(s) found" << endl;
    return unrecognized_residue_names;
}
PdbPreprocessor::PdbPreprocessorUnrecognizedResidueVector PdbPreprocessor::GetUnrecognizedResidues ()
Definition at line 52 of file pdbpreprocessor.cc.
{
    return unrecognized_residues_;
}
PdbFileSpace::PdbFile::PdbResidueVector PdbPreprocessorSpace::PdbPreprocessor::GetUnrecognizedResidues (PdbFileSpace::PdbFile::PdbResidueVector pdb_residues, std::vector< std::string > unrecognized_residue_names)
PdbFileSpace::PdbFile::PdbResidueVector PdbPreprocessor::GetUnrecognizedResidues (PdbFileSpace::PdbFile::PdbResidueVector pdb_residues, gmml::ResidueNameMap unrecognized_residue_names)
Definition at line 385 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbResidue::GetResidueName().
{
    PdbFileSpace::PdbFile::PdbResidueVector unrecognized_residues;
    for(PdbFileSpace::PdbFile::PdbResidueVector::iterator it = pdb_residues.begin(); it != pdb_residues.end(); it++)
    {
        PdbResidue* pdb_residue = *it;
        string pdb_residue_name = pdb_residue->GetResidueName();
        if(unrecognized_residue_names.find(pdb_residue_name) != unrecognized_residue_names.end())
            unrecognized_residues.push_back(pdb_residue);
    }
    return unrecognized_residues;
}
void PdbPreprocessor::Preprocess (PdbFileSpace::PdbFile * pdb_file, std::vector< std::string > amino_lib_files_path, std::vector< std::string > glycam_lib_files_path, std::vector< std::string > other_lib_files_path, std::vector< std::string > prep_files_path)
Definition at line 3560 of file pdbpreprocessor.cc.
{
    try
    {
        time_t t = time(0);
        cout << std::asctime(std::localtime(&t)) << "Start preprocessing ..." << endl;
        ExtractHISResidues(pdb_file);
        t = time(0);
        cout << std::asctime(std::localtime(&t)) << "HIS residues extraction: done" << endl;
        ExtractCYSResidues(pdb_file);
        t = time(0);
        cout << std::asctime(std::localtime(&t)) << "CYS residues extraction: done" << endl;
        ExtractAlternateResidue(pdb_file);
        t = time(0);
        cout << std::asctime(std::localtime(&t)) << "Alternate residues extraction: done" << endl;
        ExtractUnrecognizedResidues(pdb_file, amino_lib_files_path, glycam_lib_files_path, other_lib_files_path, prep_files_path);
        t = time(0);
        cout << std::asctime(std::localtime(&t)) << "Unrecognized residues extraction: done" << endl;
        ExtractUnknownHeavyAtoms(pdb_file, amino_lib_files_path, glycam_lib_files_path, other_lib_files_path, prep_files_path);
        t = time(0);
        cout << std::asctime(std::localtime(&t)) << "Unknown heavy atoms extraction: done" << endl;
        ExtractRemovedHydrogens(pdb_file, amino_lib_files_path, glycam_lib_files_path, other_lib_files_path, prep_files_path);
        t = time(0);
        cout << std::asctime(std::localtime(&t)) << "Removed hydrogens extraction: done" << endl;
        ExtractAminoAcidChains(pdb_file, amino_lib_files_path);
        t = time(0);
        cout << std::asctime(std::localtime(&t)) << "Amino acid chains extraction: done" << endl;
        ExtractGapsInAminoAcidChains(pdb_file, amino_lib_files_path);
        t = time(0);
        cout << std::asctime(std::localtime(&t)) << "Gaps in amino acid chains extraction: done" << endl;
        ExtractResidueInfo(pdb_file, amino_lib_files_path, glycam_lib_files_path, other_lib_files_path, prep_files_path);
        t = time(0);
        cout << std::asctime(std::localtime(&t)) << "Residue info extraction: done" << endl;
        t = time(0);
        cout << "Model charge is " << CalculateModelCharge(pdb_file, amino_lib_files_path, glycam_lib_files_path, other_lib_files_path, prep_files_path) << endl;
        cout << std::asctime(std::localtime(&t)) << "Model charge calculation: done" << endl;
        t = time(0);
        cout << std::asctime(std::localtime(&t)) << "Preprocessing done" << endl;
    }
    catch(PdbFileSpace::PdbFileProcessingException &ex)
    {}
}
void PdbPreprocessor::Print (std::ostream & out = std::cout)
Definition at line 3672 of file pdbpreprocessor.cc.
References PdbPreprocessorSpace::PdbPreprocessorUnrecognizedResidue::Print(), PdbPreprocessorSpace::PdbPreprocessorResidueInfo::Print(), PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::Print(), PdbPreprocessorSpace::PdbPreprocessorHistidineMapping::Print(), PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen::Print(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::Print(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::Print(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::Print(), and PdbPreprocessorSpace::PdbPreprocessorMissingResidue::Print().
{
    out << "================================== Disulfide Bonds =====================================" << endl;
    for(PdbPreprocessorDisulfideBondVector::iterator it = disulfide_bonds_.begin(); it != disulfide_bonds_.end(); it++)
    {
        PdbPreprocessorDisulfideBond* disulfide_bond = (*it);
        disulfide_bond->Print(out);
    }
    out << "======================================= Chains =========================================" << endl;
    for(PdbPreprocessorChainTerminationVector::iterator it = chain_terminations_.begin(); it != chain_terminations_.end(); it++)
    {
        PdbPreprocessorChainTermination* chain = (*it);
        chain->Print(out);
    }
    out << "===================================== HIS Residues =====================================" << endl;
    for(PdbPreprocessorHistidineMappingVector::iterator it = histidine_mappings_.begin(); it != histidine_mappings_.end(); it++)
    {
        PdbPreprocessorHistidineMapping* his_residue = (*it);
        his_residue->Print(out);
    }
    out << "======================================== Gaps ==========================================" << endl;
    for(PdbPreprocessorMissingResidueVector::iterator it = missing_residues_.begin(); it != missing_residues_.end(); it++)
    {
        PdbPreprocessorMissingResidue* gap = (*it);
        gap->Print(out);
    }
    out << "============================== Unrecognized Residues ===================================" << endl;
    for(PdbPreprocessorUnrecognizedResidueVector::iterator it = unrecognized_residues_.begin(); it != unrecognized_residues_.end(); it++)
    {
        PdbPreprocessorUnrecognizedResidue* unrecognized_residue = (*it);
        unrecognized_residue->Print(out);
    }
    out << "=============================== Unknown Heavy Atoms ====================================" << endl;
    for(PdbPreprocessorUnrecognizedHeavyAtomVector::iterator it = unrecognized_heavy_atoms_.begin(); it != unrecognized_heavy_atoms_.end(); it++)
    {
        PdbPreprocessorUnrecognizedHeavyAtom* unknown_heavy_atom = (*it);
        unknown_heavy_atom->Print(out);
    }
    out << "================================ Removed Hydrogens =====================================" << endl;
    for(PdbPreprocessorReplacedHydrogenVector::iterator it = replaced_hydrogens_.begin(); it != replaced_hydrogens_.end(); it++)
    {
        PdbPreprocessorReplacedHydrogen* removed_hydrogen = (*it);
        removed_hydrogen->Print(out);
    }
    out << "================================ Alternate Residues ====================================" << endl;
    for(PdbPreprocessorAlternateResidueMap::iterator it = alternate_residue_map_.begin(); it != alternate_residue_map_.end(); it++)
    {
        PdbPreprocessorAlternateResidue* alternate_residue = (*it).second;
        alternate_residue->Print(out);
    }
    out << "================================ Residues Info ====================================" << endl;
    for(PdbPreprocessorResidueInfoMap::iterator it = residue_info_map_.begin(); it != residue_info_map_.end(); it++)
    {
        PdbPreprocessorResidueInfo* residue_info = (*it).second;
        residue_info->Print(out);
    }
}
void PdbPreprocessor::RemoveRemovedHydrogens (PdbFileSpace::PdbFile * pdb_file, PdbPreprocessorReplacedHydrogenVector replaced_hydrogens)
Definition at line 1934 of file pdbpreprocessor.cc.
References PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen::GetAtomName(), PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen::GetResidueAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen::GetResidueInsertionCode(), PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen::GetResidueName(), and PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen::GetResidueSequenceNumber().
{
    to_be_deleted_atoms_.clear();
    to_be_deleted_residues_.clear();
    for(PdbPreprocessorReplacedHydrogenVector::iterator it = replaced_hydrogens.begin(); it != replaced_hydrogens.end(); it++)
    {
        PdbPreprocessorReplacedHydrogen* replaced_hydrogen = (*it);
        PdbAtom* pdb_atom =
                new PdbAtom(replaced_hydrogen->GetResidueChainId(),replaced_hydrogen->GetAtomName(),
                            replaced_hydrogen->GetResidueName(), replaced_hydrogen->GetResidueSequenceNumber(), replaced_hydrogen->GetResidueInsertionCode(), replaced_hydrogen->GetResidueAlternateLocation());
//        pdb_file->DeleteAtom(pdb_atom);
        to_be_deleted_atoms_.push_back(pdb_atom);
    }
    DeleteAllToBeDeletedEntities(pdb_file);
}
void PdbPreprocessor::RemoveRemovedHydrogensWithTheGivenModelNumber (PdbFileSpace::PdbFile * pdb_file, PdbPreprocessorReplacedHydrogenVector replaced_hydrogens, int model_number = 1)
Definition at line 1949 of file pdbpreprocessor.cc.
References PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen::GetAtomName(), PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen::GetResidueAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen::GetResidueInsertionCode(), PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen::GetResidueName(), and PdbPreprocessorSpace::PdbPreprocessorReplacedHydrogen::GetResidueSequenceNumber().
{
    to_be_deleted_atoms_.clear();
    to_be_deleted_residues_.clear();
    for(PdbPreprocessorReplacedHydrogenVector::iterator it = replaced_hydrogens.begin(); it != replaced_hydrogens.end(); it++)
    {
        PdbPreprocessorReplacedHydrogen* replaced_hydrogen = (*it);
        PdbAtom* pdb_atom =
                new PdbAtom(replaced_hydrogen->GetResidueChainId(),replaced_hydrogen->GetAtomName(),
                            replaced_hydrogen->GetResidueName(), replaced_hydrogen->GetResidueSequenceNumber(), replaced_hydrogen->GetResidueInsertionCode(), replaced_hydrogen->GetResidueAlternateLocation());
//        pdb_file->DeleteAtomWithTheGivenModelNumber(pdb_atom, model_number);
        to_be_deleted_atoms_.push_back(pdb_atom);
    }
    DeleteAllToBeDeletedEntitiesWithTheGivenModelNumber(pdb_file, model_number);
}
void PdbPreprocessor::RemoveResiduesOfUnknownHeavyAtoms (PdbFileSpace::PdbFile * pdb_file, PdbPreprocessorUnrecognizedHeavyAtomVector unknown_heavy_atoms)
Definition at line 1718 of file pdbpreprocessor.cc.
References PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueInsertionCode(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueName(), and PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueSequenceNumber().
{
    to_be_deleted_atoms_.clear();
    to_be_deleted_residues_.clear();
    vector<string> removed_keys = vector<string>();
    for(PdbPreprocessorUnrecognizedHeavyAtomVector::iterator it = unknown_heavy_atoms.begin(); it != unknown_heavy_atoms.end(); it++)
    {
        PdbPreprocessorUnrecognizedHeavyAtom* unknown_heavy_atom = (*it);
        stringstream ss;
        ss << unknown_heavy_atom->GetResidueInsertionCode() << "_" << unknown_heavy_atom->GetResidueChainId() << "_" << unknown_heavy_atom->GetResidueSequenceNumber()
           << "_" << unknown_heavy_atom->GetResidueInsertionCode() << "_" << unknown_heavy_atom->GetResidueAlternateLocation();
        string residue_key = ss.str();
        if(distance(removed_keys.begin(), find(removed_keys.begin(), removed_keys.end(), residue_key)) < 0 ||
                distance(removed_keys.begin(), find(removed_keys.begin(), removed_keys.end(), residue_key)) >= (int)removed_keys.size())
        {
            PdbResidue* pdb_residue = new PdbResidue(unknown_heavy_atom->GetResidueName(),unknown_heavy_atom->GetResidueChainId(), unknown_heavy_atom->GetResidueSequenceNumber(),
                                                     unknown_heavy_atom->GetResidueInsertionCode(), unknown_heavy_atom->GetResidueAlternateLocation());
//            pdb_file->DeleteResidue(pdb_residue);
            to_be_deleted_residues_.push_back(pdb_residue);
            removed_keys.push_back(residue_key);
        }
    }
    DeleteAllToBeDeletedEntities(pdb_file);
}
void PdbPreprocessor::RemoveResiduesOfUnknownHeavyAtomsWithTheGivenModelNumber (PdbFileSpace::PdbFile * pdb_file, PdbPreprocessorUnrecognizedHeavyAtomVector unknown_heavy_atoms, int model_number = 1)
Definition at line 1743 of file pdbpreprocessor.cc.
References PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueInsertionCode(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueName(), and PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueSequenceNumber().
{
    to_be_deleted_atoms_.clear();
    to_be_deleted_residues_.clear();
    vector<string> removed_keys = vector<string>();
    for(PdbPreprocessorUnrecognizedHeavyAtomVector::iterator it = unknown_heavy_atoms.begin(); it != unknown_heavy_atoms.end(); it++)
    {
        PdbPreprocessorUnrecognizedHeavyAtom* unknown_heavy_atom = (*it);
        stringstream ss;
        ss << unknown_heavy_atom->GetResidueInsertionCode() << "_" << unknown_heavy_atom->GetResidueChainId() << "_" << unknown_heavy_atom->GetResidueSequenceNumber()
           << "_" << unknown_heavy_atom->GetResidueInsertionCode() << "_" << unknown_heavy_atom->GetResidueAlternateLocation();
        string residue_key = ss.str();
        if(distance(removed_keys.begin(), find(removed_keys.begin(), removed_keys.end(), residue_key)) < 0 ||
                distance(removed_keys.begin(), find(removed_keys.begin(), removed_keys.end(), residue_key)) >= (int)removed_keys.size())
        {
            PdbResidue* pdb_residue = new PdbResidue(unknown_heavy_atom->GetResidueName(),unknown_heavy_atom->GetResidueChainId(), unknown_heavy_atom->GetResidueSequenceNumber(),
                                                     unknown_heavy_atom->GetResidueInsertionCode(), unknown_heavy_atom->GetResidueAlternateLocation());
//            pdb_file->DeleteResidueWithTheGivenModelNumber(pdb_residue , model_number);
            to_be_deleted_residues_.push_back(pdb_residue);
            removed_keys.push_back(residue_key);
        }
    }
    DeleteAllToBeDeletedEntitiesWithTheGivenModelNumber(pdb_file, model_number);
}
void PdbPreprocessor::RemoveUnknownHeavyAtoms (PdbFileSpace::PdbFile * pdb_file, PdbPreprocessorUnrecognizedHeavyAtomVector unknown_heavy_atoms)
Definition at line 1687 of file pdbpreprocessor.cc.
References PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetAtomName(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueInsertionCode(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueName(), and PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueSequenceNumber().
{
    to_be_deleted_atoms_.clear();
    to_be_deleted_residues_.clear();
    for(PdbPreprocessorUnrecognizedHeavyAtomVector::iterator it = unknown_heavy_atoms.begin(); it != unknown_heavy_atoms.end(); it++)
    {
        PdbPreprocessorUnrecognizedHeavyAtom* unknown_heavy_atom = (*it);
        PdbAtom* pdb_atom =
                new PdbAtom(unknown_heavy_atom->GetResidueChainId(),unknown_heavy_atom->GetAtomName(),
                            unknown_heavy_atom->GetResidueName(), unknown_heavy_atom->GetResidueSequenceNumber(), unknown_heavy_atom->GetResidueInsertionCode(), unknown_heavy_atom->GetResidueAlternateLocation());
//        pdb_file->DeleteAtom(pdb_atom);
        to_be_deleted_atoms_.push_back(pdb_atom);
    }
    DeleteAllToBeDeletedEntities(pdb_file);
}
void PdbPreprocessor::RemoveUnknownHeavyAtomsWithTheGivenModelNumber (PdbFileSpace::PdbFile * pdb_file, PdbPreprocessorUnrecognizedHeavyAtomVector unknown_heavy_atoms, int model_number = 1)
Definition at line 1702 of file pdbpreprocessor.cc.
References PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetAtomName(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueInsertionCode(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueName(), and PdbPreprocessorSpace::PdbPreprocessorUnrecognizedHeavyAtom::GetResidueSequenceNumber().
{
    to_be_deleted_atoms_.clear();
    to_be_deleted_residues_.clear();
    for(PdbPreprocessorUnrecognizedHeavyAtomVector::iterator it = unknown_heavy_atoms.begin(); it != unknown_heavy_atoms.end(); it++)
    {
        PdbPreprocessorUnrecognizedHeavyAtom* unknown_heavy_atom = (*it);
        PdbAtom* pdb_atom =
                new PdbAtom(unknown_heavy_atom->GetResidueChainId(),unknown_heavy_atom->GetAtomName(),
                            unknown_heavy_atom->GetResidueName(), unknown_heavy_atom->GetResidueSequenceNumber(), unknown_heavy_atom->GetResidueInsertionCode(), unknown_heavy_atom->GetResidueAlternateLocation());
//        pdb_file->DeleteAtomWithTheGivenModelNumber(pdb_atom, model_number);
        to_be_deleted_atoms_.push_back(pdb_atom);
    }
    DeleteAllToBeDeletedEntitiesWithTheGivenModelNumber(pdb_file, model_number);
}
void PdbPreprocessor::RemoveUnrecognizedResidues (PdbFileSpace::PdbFile * pdb_file, PdbPreprocessorUnrecognizedResidueVector unrecognized_residues)
Definition at line 786 of file pdbpreprocessor.cc.
References PdbPreprocessorSpace::PdbPreprocessorUnrecognizedResidue::GetResidueAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedResidue::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedResidue::GetResidueInsertionCode(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedResidue::GetResidueName(), and PdbPreprocessorSpace::PdbPreprocessorUnrecognizedResidue::GetResidueSequenceNumber().
{
    to_be_deleted_atoms_.clear();
    to_be_deleted_residues_.clear();
    for(PdbPreprocessorUnrecognizedResidueVector::iterator it = unrecognized_residues.begin(); it != unrecognized_residues.end(); it++)
    {
        PdbPreprocessorUnrecognizedResidue* unrecognized_residue = (*it);
        PdbResidue* pdb_residue =
                new PdbResidue(unrecognized_residue->GetResidueName(), unrecognized_residue->GetResidueChainId(),
                               unrecognized_residue->GetResidueSequenceNumber(), unrecognized_residue->GetResidueInsertionCode(), unrecognized_residue->GetResidueAlternateLocation());
//        pdb_file->DeleteResidue(pdb_residue);
        to_be_deleted_residues_.push_back(pdb_residue);
    }
    DeleteAllToBeDeletedEntities(pdb_file);
}
void PdbPreprocessor::RemoveUnrecognizedResiduesWithTheGivenModelNumber (PdbFileSpace::PdbFile * pdb_file, PdbPreprocessorUnrecognizedResidueVector unrecognized_residues, int model_number = 1)
Definition at line 801 of file pdbpreprocessor.cc.
References PdbPreprocessorSpace::PdbPreprocessorUnrecognizedResidue::GetResidueAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedResidue::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedResidue::GetResidueInsertionCode(), PdbPreprocessorSpace::PdbPreprocessorUnrecognizedResidue::GetResidueName(), and PdbPreprocessorSpace::PdbPreprocessorUnrecognizedResidue::GetResidueSequenceNumber().
{
    to_be_deleted_atoms_.clear();
    to_be_deleted_residues_.clear();
    for(PdbPreprocessorUnrecognizedResidueVector::iterator it = unrecognized_residues.begin(); it != unrecognized_residues.end(); it++)
    {
        PdbPreprocessorUnrecognizedResidue* unrecognized_residue = (*it);
        PdbResidue* pdb_residue =
                new PdbResidue(unrecognized_residue->GetResidueName(), unrecognized_residue->GetResidueChainId(),
                               unrecognized_residue->GetResidueSequenceNumber(), unrecognized_residue->GetResidueInsertionCode(), unrecognized_residue->GetResidueAlternateLocation());
//        pdb_file->DeleteResidueWithTheGivenModelNumber(pdb_residue, model_number);
        to_be_deleted_residues_.push_back(pdb_residue);
    }
    DeleteAllToBeDeletedEntitiesWithTheGivenModelNumber(pdb_file, model_number);
}
void PdbPreprocessor::RemoveUnselectedAlternateResidues (PdbFileSpace::PdbFile * pdb_file, PdbPreprocessorAlternateResidueMap alternate_residue_map)
Definition at line 3231 of file pdbpreprocessor.cc.
References PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::GetResidueAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::GetResidueInsertionCode(), PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::GetResidueName(), PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::GetResidueSequenceNumber(), and PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::GetSelectedAlternateLocation().
{
    to_be_deleted_atoms_.clear();
    to_be_deleted_residues_.clear();
    for(PdbPreprocessorAlternateResidueMap::iterator it = alternate_residue_map.begin(); it != alternate_residue_map.end(); it++)
    {
        PdbPreprocessorAlternateResidue* alternate_residue = (*it).second;
        vector<bool> selected_alternate_locations = alternate_residue->GetSelectedAlternateLocation();
        for(vector<bool>::iterator it1 = selected_alternate_locations.begin(); it1 != selected_alternate_locations.end(); it1++)
        {
            bool selected_alternate_location = (*it1);
            char alternate_location = alternate_residue->GetResidueAlternateLocation().at(distance(selected_alternate_locations.begin(), it1));
            if(!selected_alternate_location)
            {
                PdbResidue* pdb_residue = new PdbResidue(alternate_residue->GetResidueName() ,alternate_residue->GetResidueChainId(), alternate_residue->GetResidueSequenceNumber(),
                                                         alternate_residue->GetResidueInsertionCode(), alternate_location);
//                pdb_file->DeleteResidue(pdb_residue);
                to_be_deleted_residues_.push_back(pdb_residue);
            }
        }
    }
    DeleteAllToBeDeletedEntities(pdb_file);
}
void PdbPreprocessor::RemoveUnselectedAlternateResiduesWithTheGivenModelNumber (PdbFileSpace::PdbFile * pdb_file, PdbPreprocessorAlternateResidueMap alternate_residue_map, int model_number = 1)
Definition at line 3254 of file pdbpreprocessor.cc.
References PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::GetResidueAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::GetResidueInsertionCode(), PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::GetResidueName(), PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::GetResidueSequenceNumber(), and PdbPreprocessorSpace::PdbPreprocessorAlternateResidue::GetSelectedAlternateLocation().
{
    to_be_deleted_atoms_.clear();
    to_be_deleted_residues_.clear();
    for(PdbPreprocessorAlternateResidueMap::iterator it = alternate_residue_map.begin(); it != alternate_residue_map.end(); it++)
    {
        PdbPreprocessorAlternateResidue* alternate_residue = (*it).second;
        vector<bool> selected_alternate_locations = alternate_residue->GetSelectedAlternateLocation();
        for(vector<bool>::iterator it1 = selected_alternate_locations.begin(); it1 != selected_alternate_locations.end(); it1++)
        {
            bool selected_alternate_location = (*it1);
            char alternate_location = alternate_residue->GetResidueAlternateLocation().at(distance(selected_alternate_locations.begin(), it1));
            if(!selected_alternate_location)
            {
                PdbResidue* pdb_residue = new PdbResidue(alternate_residue->GetResidueName() ,alternate_residue->GetResidueChainId(), alternate_residue->GetResidueSequenceNumber(),
                                                         alternate_residue->GetResidueInsertionCode(), alternate_location);
//                pdb_file->DeleteResidueWithTheGivenModelNumber(pdb_residue, model_number);
                to_be_deleted_residues_.push_back(pdb_residue);
            }
        }
    }
    DeleteAllToBeDeletedEntitiesWithTheGivenModelNumber(pdb_file);
}
void PdbPreprocessor::SetChainTerminations (PdbPreprocessor::PdbPreprocessorChainTerminationVector chain_terminations)
Definition at line 91 of file pdbpreprocessor.cc.
{
    chain_terminations_.clear();
    for(PdbPreprocessorChainTerminationVector::iterator it = chain_terminations.begin(); it != chain_terminations.end(); it++)
    {
        chain_terminations_.push_back(*it);
    }
}
void PdbPreprocessor::SetDisulfideBonds (PdbPreprocessor::PdbPreprocessorDisulfideBondVector disulfide_bonds)
Definition at line 80 of file pdbpreprocessor.cc.
{
    disulfide_bonds_.clear();
    for(PdbPreprocessorDisulfideBondVector::iterator it = disulfide_bonds.begin(); it != disulfide_bonds.end(); it++)
    {
        disulfide_bonds_.push_back(*it);
    }
}
void PdbPreprocessor::SetHistidineMappings (PdbPreprocessor::PdbPreprocessorHistidineMappingVector histidine_mappings)
Definition at line 102 of file pdbpreprocessor.cc.
{
    histidine_mappings_.clear();
    for(PdbPreprocessorHistidineMappingVector::iterator it = histidine_mappings.begin(); it != histidine_mappings.end(); it++)
    {
        histidine_mappings_.push_back(*it);
    }
}
void PdbPreprocessor::SetMissingResidues (PdbPreprocessor::PdbPreprocessorMissingResidueVector missing_residues)
Definition at line 113 of file pdbpreprocessor.cc.
{
    missing_residues_.clear();
    for(PdbPreprocessorMissingResidueVector::iterator it = missing_residues.begin(); it != missing_residues.end(); it++)
    {
        missing_residues_.push_back(*it);
    }
}
void PdbPreprocessor::SetRecognizedResidues (PdbPreprocessor::PdbPreprocessorRecognizedResidueVector recognized_residues)
Definition at line 135 of file pdbpreprocessor.cc.
{
    recognized_residues_.clear();
    for(PdbPreprocessorRecognizedResidueVector::iterator it = recognized_residues.begin(); it != recognized_residues.end(); it++)
    {
        recognized_residues_.push_back(*it);
    }
}
void PdbPreprocessor::SetReplacedHydrogens (PdbPreprocessor::PdbPreprocessorReplacedHydrogenVector replaced_hydrogens)
Definition at line 157 of file pdbpreprocessor.cc.
{
    replaced_hydrogens.clear();
    for(PdbPreprocessorReplacedHydrogenVector::iterator it = replaced_hydrogens.begin(); it != replaced_hydrogens.end(); it++)
    {
        replaced_hydrogens_.push_back(*it);
    }
}
void PdbPreprocessor::SetToBeDeletedAtoms (PdbPreprocessorToBeDeletedAtomVector to_be_deleted_atoms)
Definition at line 168 of file pdbpreprocessor.cc.
{
    to_be_deleted_atoms_.clear();
    for(PdbPreprocessorToBeDeletedAtomVector::iterator it = to_be_deleted_atoms.begin(); it != to_be_deleted_atoms.end(); it++)
    {
        to_be_deleted_atoms_.push_back(*it);
    }
}
void PdbPreprocessor::SetToBeDeletedResidues (PdbPreprocessorToBeDeletedResidueVector to_be_deleted_residues)
Definition at line 176 of file pdbpreprocessor.cc.
{
    to_be_deleted_residues_.clear();
    for(PdbPreprocessorToBeDeletedResidueVector::iterator it = to_be_deleted_residues.begin(); it != to_be_deleted_residues.end(); it++)
    {
        to_be_deleted_residues_.push_back(*it);
    }
}
void PdbPreprocessor::SetUnrecognizedHeavyAtoms (PdbPreprocessor::PdbPreprocessorUnrecognizedHeavyAtomVector unrecognized_heavy_atoms)
Definition at line 146 of file pdbpreprocessor.cc.
{
    unrecognized_heavy_atoms_.clear();
    for(PdbPreprocessorUnrecognizedHeavyAtomVector::iterator it = unrecognized_heavy_atoms.begin(); it != unrecognized_heavy_atoms.end(); it++)
    {
        unrecognized_heavy_atoms_.push_back(*it);
    }
}
void PdbPreprocessor::SetUnrecognizedResidues (PdbPreprocessor::PdbPreprocessorUnrecognizedResidueVector unrecognized_residues)
Definition at line 124 of file pdbpreprocessor.cc.
{
    unrecognized_residues_.clear();
    for(PdbPreprocessorUnrecognizedResidueVector::iterator it = unrecognized_residues.begin(); it != unrecognized_residues.end(); it++)
    {
        unrecognized_residues_.push_back(*it);
    }
}
void PdbPreprocessor::UpdateAminoAcidChains (PdbFileSpace::PdbFile * pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > prep_files, PdbPreprocessorChainTerminationVector chain_terminations)
Definition at line 2206 of file pdbpreprocessor.cc.
References gmml::dNotSet, PdbFileSpace::PdbFile::GetAllTerCardPositions(), LibraryFileSpace::LibraryFileResidue::GetAtoms(), LibraryFileSpace::LibraryFileAtom::GetCoordinate(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetEndingResidueSequenceNumber(), LibraryFileSpace::LibraryFileAtom::GetName(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetSelectedCTermination(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetSelectedNTermination(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetStartingResidueSequenceNumber(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetStringFormatOfCTermination(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetStringFormatOfNTermination(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetStringFormatOfSelectedCTermination(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetStringFormatOfSelectedNTermination(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbAtomCard::SetRecordName(), and PdbFileSpace::PdbFile::SplitAtomCardOfModelCard().
{
    // Before non-amino-acid residue
    for(PdbPreprocessor::PdbPreprocessorChainTerminationVector::iterator it1 = chain_terminations.begin(); it1 != chain_terminations.end(); it1++)
    {
        PdbPreprocessorChainTermination* chain = (*it1);
        pdb_file->SplitAtomCardOfModelCard(chain->GetResidueChainId(), chain->GetEndingResidueSequenceNumber() + 1);
    }
    cout << "Putting TER card after non-amino acid residues: Done" << endl;
    vector<string> glycam_residue_names = this->GetAllResidueNamesFromDatasetFiles(glycam_lib_files, prep_files);
    // Get all TER card positions and split
    vector<pair<char, int> > ter_card_positions = pdb_file->GetAllTerCardPositions(glycam_residue_names);
    for(vector<pair<char, int> >::iterator it1 = ter_card_positions.begin(); it1 != ter_card_positions.end(); it1++)
    {
        pair<char, int> ter_position = *it1;
        char chain_id = ter_position.first;
        int sequence_number = ter_position.second;
        pdb_file->SplitAtomCardOfModelCard(chain_id, sequence_number);
    }
    cout << "Putting TER card after residues with no tail or with at least 2 tails: Done" << endl;
    // Add Terminals
    LibraryFileSpace::LibraryFileResidue::AtomMap lib_atoms;
    for(PdbPreprocessor::PdbPreprocessorChainTerminationVector::iterator it1 = chain_terminations.begin(); it1 != chain_terminations.end(); it1++)
    {
        PdbPreprocessorChainTermination* chain = (*it1);
        // Zwitterionic in n terminal
        if(chain->GetStringFormatOfSelectedNTermination().find("+") != string::npos || chain->GetStringFormatOfSelectedNTermination().find("-") != string::npos)
        {
            // Zwitterionic in c terminal
            if(chain->GetStringFormatOfSelectedCTermination().find("+") != string::npos || chain->GetStringFormatOfSelectedCTermination().find("-") != string::npos)
            {
                // End of chain
                // Do nothing
            }
            else
            {
                // Add c terminal at the end of the chain
                PossibleCChainTermination c_termination = chain->GetSelectedCTermination();
                string string_c_termination = chain->GetStringFormatOfCTermination(c_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue = GetLibraryResidueByNameFromMultipleLibraryFiles(string_c_termination, amino_lib_files);
                if(lib_file_residue != NULL)
                {
                    lib_atoms = lib_file_residue->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card = new PdbAtomCard();
                    pdb_atom_card->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it2 = lib_atoms.begin(); it2 != lib_atoms.end(); it2++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it2).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_c_termination, chain->GetResidueChainId(),
                                                                      chain->GetEndingResidueSequenceNumber(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card->SetAtoms(atom_map);
                    pdb_file->InsertResidueAfter(pdb_atom_card);
                }
            }
        }
        else
        {
            // Zwitterionic in c terminal
            if(chain->GetStringFormatOfSelectedCTermination().find("+") != string::npos || chain->GetStringFormatOfSelectedCTermination().find("-") != string::npos)
            {
                // Add n terminal residue at the beginning of the chain
                PossibleNChainTermination n_termination = chain->GetSelectedNTermination();
                string string_n_termination = chain->GetStringFormatOfNTermination(n_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue = GetLibraryResidueByNameFromMultipleLibraryFiles(string_n_termination, amino_lib_files);
                if(lib_file_residue != NULL)
                {
                    lib_atoms = lib_file_residue->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card = new PdbAtomCard();
                    pdb_atom_card->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it2 = lib_atoms.begin(); it2 != lib_atoms.end(); it2++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it2).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_n_termination, chain->GetResidueChainId(),
                                                                      chain->GetStartingResidueSequenceNumber(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card->SetAtoms(atom_map);
                    pdb_file->InsertResidueBefore(pdb_atom_card);
                }
            }
            else
            {
                // Add c terminal residue at the end of the chain
                PossibleCChainTermination c_termination = chain->GetSelectedCTermination();
                string string_c_termination = chain->GetStringFormatOfCTermination(c_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue_from_c_termination = GetLibraryResidueByNameFromMultipleLibraryFiles(string_c_termination, amino_lib_files);
                if(lib_file_residue_from_c_termination != NULL)
                {
                    LibraryFileSpace::LibraryFileResidue::AtomMap lib_atoms_from_c_termination = lib_file_residue_from_c_termination->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card_for_c_termination = new PdbAtomCard();
                    pdb_atom_card_for_c_termination->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map_for_c_termination;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it3 = lib_atoms_from_c_termination.begin(); it3 != lib_atoms_from_c_termination.end(); it3++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it3).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_c_termination, chain->GetResidueChainId(),
                                                                      chain->GetEndingResidueSequenceNumber(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map_for_c_termination[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card_for_c_termination->SetAtoms(atom_map_for_c_termination);
                    pdb_file->InsertResidueAfter(pdb_atom_card_for_c_termination);
                }
                // Add n terminal residue at the beginning of the chain
                PossibleNChainTermination n_termination = chain->GetSelectedNTermination();
                string string_n_termination = chain->GetStringFormatOfNTermination(n_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue = GetLibraryResidueByNameFromMultipleLibraryFiles(string_n_termination, amino_lib_files);
                if(lib_file_residue != NULL)
                {
                    LibraryFileSpace::LibraryFileResidue::AtomMap lib_atoms = lib_file_residue->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card = new PdbAtomCard();
                    pdb_atom_card->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it2 = lib_atoms.begin(); it2 != lib_atoms.end(); it2++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it2).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_n_termination, chain->GetResidueChainId(),
                                                                      chain->GetStartingResidueSequenceNumber(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card->SetAtoms(atom_map);
                    pdb_file->InsertResidueBefore(pdb_atom_card);
                }
            }
        }
    }
    cout << "Add terminals: Done" << endl;
}
void PdbPreprocessor::UpdateAminoAcidChainsWithTheGivenModelNumber (PdbFileSpace::PdbFile * pdb_file, std::vector< std::string > amino_lib_files, std::vector< std::string > glycam_lib_files, std::vector< std::string > prep_files, PdbPreprocessorChainTerminationVector chain_terminations, int model_number = 1)
Definition at line 2348 of file pdbpreprocessor.cc.
References gmml::dNotSet, PdbFileSpace::PdbFile::GetAllTerCardPositions(), LibraryFileSpace::LibraryFileResidue::GetAtoms(), LibraryFileSpace::LibraryFileAtom::GetCoordinate(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetEndingResidueSequenceNumber(), LibraryFileSpace::LibraryFileAtom::GetName(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetSelectedCTermination(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetSelectedNTermination(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetStartingResidueSequenceNumber(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetStringFormatOfCTermination(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetStringFormatOfNTermination(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetStringFormatOfSelectedCTermination(), PdbPreprocessorSpace::PdbPreprocessorChainTermination::GetStringFormatOfSelectedNTermination(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbAtomCard::SetRecordName(), and PdbFileSpace::PdbFile::SplitAtomCardOfModelCard().
{
    // Before non-amino-acid residue
    for(PdbPreprocessor::PdbPreprocessorChainTerminationVector::iterator it1 = chain_terminations.begin(); it1 != chain_terminations.end(); it1++)
    {
        PdbPreprocessorChainTermination* chain = (*it1);
        pdb_file->SplitAtomCardOfModelCard(chain->GetResidueChainId(), chain->GetEndingResidueSequenceNumber() + 1);
    }
    cout << "Putting TER card after non-amino acid residues: Done" << endl;
    vector<string> glycam_residue_names = this->GetAllResidueNamesFromDatasetFiles(glycam_lib_files, prep_files);
    // Get all TER card positions and split
    vector<pair<char, int> > ter_card_positions = pdb_file->GetAllTerCardPositions(glycam_residue_names);
    for(vector<pair<char, int> >::iterator it1 = ter_card_positions.begin(); it1 != ter_card_positions.end(); it1++)
    {
        pair<char, int> ter_position = *it1;
        char chain_id = ter_position.first;
        int sequence_number = ter_position.second;
        pdb_file->SplitAtomCardOfModelCard(chain_id, sequence_number);
    }
    cout << "Putting TER card after residues with no tail or with at least 2 tails: Done" << endl;
    // Add Terminals
    LibraryFileSpace::LibraryFileResidue::AtomMap lib_atoms;
    for(PdbPreprocessor::PdbPreprocessorChainTerminationVector::iterator it1 = chain_terminations.begin(); it1 != chain_terminations.end(); it1++)
    {
        PdbPreprocessorChainTermination* chain = (*it1);
        // Zwitterionic in n terminal
        if(chain->GetStringFormatOfSelectedNTermination().find("+") != string::npos || chain->GetStringFormatOfSelectedNTermination().find("-") != string::npos)
        {
            // Zwitterionic in c terminal
            if(chain->GetStringFormatOfSelectedCTermination().find("+") != string::npos || chain->GetStringFormatOfSelectedCTermination().find("-") != string::npos)
            {
                // End of chain
                // Do nothing
            }
            else
            {
                // Add c terminal at the end of the chain
                PossibleCChainTermination c_termination = chain->GetSelectedCTermination();
                string string_c_termination = chain->GetStringFormatOfCTermination(c_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue = GetLibraryResidueByNameFromMultipleLibraryFiles(string_c_termination, amino_lib_files);
                if(lib_file_residue != NULL)
                {
                    lib_atoms = lib_file_residue->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card = new PdbAtomCard();
                    pdb_atom_card->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it2 = lib_atoms.begin(); it2 != lib_atoms.end(); it2++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it2).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_c_termination, chain->GetResidueChainId(),
                                                                      chain->GetEndingResidueSequenceNumber(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card->SetAtoms(atom_map);
                    pdb_file->InsertResidueAfterWithTheGivenModelNumber(pdb_atom_card, model_number);
                }
            }
        }
        else
        {
            // Zwitterionic in c terminal
            if(chain->GetStringFormatOfSelectedCTermination().find("+") != string::npos || chain->GetStringFormatOfSelectedCTermination().find("-") != string::npos)
            {
                // Add n terminal residue at the beginning of the chain
                PossibleNChainTermination n_termination = chain->GetSelectedNTermination();
                string string_n_termination = chain->GetStringFormatOfNTermination(n_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue = GetLibraryResidueByNameFromMultipleLibraryFiles(string_n_termination, amino_lib_files);
                if(lib_file_residue != NULL)
                {
                    lib_atoms = lib_file_residue->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card = new PdbAtomCard();
                    pdb_atom_card->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it2 = lib_atoms.begin(); it2 != lib_atoms.end(); it2++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it2).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_n_termination, chain->GetResidueChainId(),
                                                                      chain->GetStartingResidueSequenceNumber(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card->SetAtoms(atom_map);
                    pdb_file->InsertResidueBeforeWithTheGivenModelNumber(pdb_atom_card, model_number);
                }
            }
            else
            {
                // Add c terminal residue at the end of the chain
                PossibleCChainTermination c_termination = chain->GetSelectedCTermination();
                string string_c_termination = chain->GetStringFormatOfCTermination(c_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue_from_c_termination = GetLibraryResidueByNameFromMultipleLibraryFiles(string_c_termination, amino_lib_files);
                if(lib_file_residue_from_c_termination != NULL)
                {
                    LibraryFileSpace::LibraryFileResidue::AtomMap lib_atoms_from_c_termination = lib_file_residue_from_c_termination->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card_for_c_termination = new PdbAtomCard();
                    pdb_atom_card_for_c_termination->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map_for_c_termination;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it3 = lib_atoms_from_c_termination.begin(); it3 != lib_atoms_from_c_termination.end(); it3++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it3).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_c_termination, chain->GetResidueChainId(),
                                                                      chain->GetEndingResidueSequenceNumber(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map_for_c_termination[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card_for_c_termination->SetAtoms(atom_map_for_c_termination);
                    pdb_file->InsertResidueAfterWithTheGivenModelNumber(pdb_atom_card_for_c_termination, model_number);
                }
                // Add n terminal residue at the beginning of the chain
                PossibleNChainTermination n_termination = chain->GetSelectedNTermination();
                string string_n_termination = chain->GetStringFormatOfNTermination(n_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue = GetLibraryResidueByNameFromMultipleLibraryFiles(string_n_termination, amino_lib_files);
                if(lib_file_residue != NULL)
                {
                    LibraryFileSpace::LibraryFileResidue::AtomMap lib_atoms = lib_file_residue->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card = new PdbAtomCard();
                    pdb_atom_card->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it2 = lib_atoms.begin(); it2 != lib_atoms.end(); it2++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it2).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_n_termination, chain->GetResidueChainId(),
                                                                      chain->GetStartingResidueSequenceNumber(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card->SetAtoms(atom_map);
                    pdb_file->InsertResidueBeforeWithTheGivenModelNumber(pdb_atom_card, model_number);
                }
            }
        }
    }
    cout << "Add terminals: Done" << endl;
}
void PdbPreprocessor::UpdateCYSResidues (PdbFileSpace::PdbFile * pdb_file, PdbPreprocessorDisulfideBondVector disulfide_bonds)
Definition at line 979 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbFile::GetAllResidues(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetIsBonded(), PdbFileSpace::PdbResidue::GetResidueAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueAlternateLocation1(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueAlternateLocation2(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueChainId1(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueChainId2(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueInsertionCode1(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueInsertionCode2(), PdbFileSpace::PdbResidue::GetResidueName(), PdbFileSpace::PdbResidue::GetResidueSequenceNumber(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueSequenceNumber1(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueSequenceNumber2(), and PdbFileSpace::PdbFile::UpdateResidueName().
{
    to_be_deleted_atoms_.clear();
    to_be_deleted_residues_.clear();
    PdbFile::PdbResidueVector pdb_residues;
    for(PdbPreprocessorDisulfideBondVector::iterator it = disulfide_bonds.begin(); it != disulfide_bonds.end(); it++)
    {
        PdbPreprocessorDisulfideBond* disulfide_bond = (*it);
        if(disulfide_bond->GetIsBonded())
        {
            PdbAtom* pdb_atom_1 =
                    new PdbAtom(disulfide_bond->GetResidueChainId1(), "HG", "CYS",
                                disulfide_bond->GetResidueSequenceNumber1(), disulfide_bond->GetResidueInsertionCode1(), disulfide_bond->GetResidueAlternateLocation1());
//            pdb_file->DeleteAtom(pdb_atom_1);
            to_be_deleted_atoms_.push_back(pdb_atom_1);
            PdbAtom* pdb_atom_2 =
                    new PdbAtom(disulfide_bond->GetResidueChainId2(), "HG", "CYS",
                                disulfide_bond->GetResidueSequenceNumber2(), disulfide_bond->GetResidueInsertionCode2(), disulfide_bond->GetResidueAlternateLocation2());
//            pdb_file->DeleteAtom(pdb_atom_2);
            to_be_deleted_atoms_.push_back(pdb_atom_2);
            string target_key1;
            stringstream ss_1;
            ss_1 << "CYS" << "_" << disulfide_bond->GetResidueChainId1() << "_" << disulfide_bond->GetResidueSequenceNumber1() << "_" << disulfide_bond->GetResidueInsertionCode1()
                 << "_" << disulfide_bond->GetResidueAlternateLocation1();
            target_key1 = ss_1.str();
            string target_key2;
            stringstream ss_2;
            ss_2 << "CYS" << "_" << disulfide_bond->GetResidueChainId2() << "_" << disulfide_bond->GetResidueSequenceNumber2() << "_" << disulfide_bond->GetResidueInsertionCode2()
                 << "_" << disulfide_bond->GetResidueAlternateLocation2();
            target_key2 = ss_2.str();
            pdb_residues = pdb_file->GetAllResidues();
            for(PdbFile::PdbResidueVector::iterator it1 = pdb_residues.begin(); it1 != pdb_residues.end(); it1++)
            {
                PdbResidue* pdb_residue = (*it1);
                string residue_name = pdb_residue->GetResidueName();
                if((residue_name).compare("CYS") == 0)
                {
                    stringstream ss;
                    string pdb_residue_key;
                    ss << residue_name << "_" << pdb_residue->GetResidueChainId() << "_" << pdb_residue->GetResidueSequenceNumber() << "_" << pdb_residue->GetResidueInsertionCode()
                       << "_" << pdb_residue->GetResidueAlternateLocation();
                    pdb_residue_key = ss.str();
                    if(pdb_residue_key.compare(target_key1) == 0 || pdb_residue_key.compare(target_key2) == 0)
                    {
                        pdb_file->UpdateResidueName(pdb_residue, "CYX");
                    }
                }
            }
        }
    }
    DeleteAllToBeDeletedEntities(pdb_file);
}
void PdbPreprocessor::UpdateCYSResiduesWithTheGivenModelNumber (PdbFileSpace::PdbFile * pdb_file, PdbPreprocessorDisulfideBondVector disulfide_bonds, int model_number = 1)
Definition at line 1034 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbFile::GetAllResidues(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetIsBonded(), PdbFileSpace::PdbResidue::GetResidueAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueAlternateLocation1(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueAlternateLocation2(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueChainId1(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueChainId2(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueInsertionCode1(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueInsertionCode2(), PdbFileSpace::PdbResidue::GetResidueName(), PdbFileSpace::PdbResidue::GetResidueSequenceNumber(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueSequenceNumber1(), PdbPreprocessorSpace::PdbPreprocessorDisulfideBond::GetResidueSequenceNumber2(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    to_be_deleted_atoms_.clear();
    to_be_deleted_residues_.clear();
    PdbFile::PdbResidueVector pdb_residues;
    for(PdbPreprocessorDisulfideBondVector::iterator it = disulfide_bonds.begin(); it != disulfide_bonds.end(); it++)
    {
        PdbPreprocessorDisulfideBond* disulfide_bond = (*it);
        if(disulfide_bond->GetIsBonded())
        {
            PdbAtom* pdb_atom_1 =
                    new PdbAtom(disulfide_bond->GetResidueChainId1(), "HG", "CYS",
                                disulfide_bond->GetResidueSequenceNumber1(), disulfide_bond->GetResidueInsertionCode1(), disulfide_bond->GetResidueAlternateLocation1());
//            pdb_file->DeleteAtomWithTheGivenModelNumber(pdb_atom_1, model_number);
            to_be_deleted_atoms_.push_back(pdb_atom_1);
            PdbAtom* pdb_atom_2 =
                    new PdbAtom(disulfide_bond->GetResidueChainId2(), "HG", "CYS",
                                disulfide_bond->GetResidueSequenceNumber2(), disulfide_bond->GetResidueInsertionCode2(), disulfide_bond->GetResidueAlternateLocation2());
//            pdb_file->DeleteAtomWithTheGivenModelNumber(pdb_atom_2, model_number);
            to_be_deleted_atoms_.push_back(pdb_atom_2);
            string target_key1;
            stringstream ss_1;
            ss_1 << "CYS" << "_" << disulfide_bond->GetResidueChainId1() << "_" << disulfide_bond->GetResidueSequenceNumber1() << "_" << disulfide_bond->GetResidueInsertionCode1()
                 << "_" << disulfide_bond->GetResidueAlternateLocation1();
            target_key1 = ss_1.str();
            string target_key2;
            stringstream ss_2;
            ss_2 << "CYS" << "_" << disulfide_bond->GetResidueChainId2() << "_" << disulfide_bond->GetResidueSequenceNumber2() << "_" << disulfide_bond->GetResidueInsertionCode2()
                 << "_" << disulfide_bond->GetResidueAlternateLocation2();
            target_key2 = ss_2.str();
            pdb_residues = pdb_file->GetAllResidues();
            for(PdbFile::PdbResidueVector::iterator it1 = pdb_residues.begin(); it1 != pdb_residues.end(); it1++)
            {
                PdbResidue* pdb_residue = (*it1);
                string residue_name = pdb_residue->GetResidueName();
                if((residue_name).compare("CYS") == 0)
                {
                    stringstream ss;
                    string pdb_residue_key;
                    ss << residue_name << "_" << pdb_residue->GetResidueChainId() << "_" << pdb_residue->GetResidueSequenceNumber() << "_" << pdb_residue->GetResidueInsertionCode()
                       << "_" << pdb_residue->GetResidueAlternateLocation();
                    pdb_residue_key = ss.str();
                    if(pdb_residue_key.compare(target_key1) == 0 || pdb_residue_key.compare(target_key2) == 0)
                    {
                        pdb_file->UpdateResidueNameWithTheGivenModelNumber(pdb_residue, "CYX", model_number);
                    }
                }
            }
        }
    }
    DeleteAllToBeDeletedEntitiesWithTheGivenModelNumber(pdb_file, model_number);
}
void PdbPreprocessor::UpdateGapsInAminoAcidChains (PdbFileSpace::PdbFile * pdb_file, std::vector< std::string > amino_lib_files, PdbPreprocessorMissingResidueVector gaps)
Definition at line 2806 of file pdbpreprocessor.cc.
References gmml::dNotSet, LibraryFileSpace::LibraryFileResidue::GetAtoms(), LibraryFileSpace::LibraryFileAtom::GetCoordinate(), LibraryFileSpace::LibraryFileAtom::GetName(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetResidueAfterGap(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetResidueBeforeGap(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetSelectedCTermination(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetSelectedNTermination(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetStringFormatOfCTermination(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetStringFormatOfNTermination(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetStringFormatOfSelectedCTermination(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetStringFormatOfSelectedNTermination(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbAtomCard::SetRecordName(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::SetResidueBeforeGap(), and PdbFileSpace::PdbFile::SplitAtomCardOfModelCard().
{
    for(PdbPreprocessor::PdbPreprocessorMissingResidueVector::iterator it1 = gaps.begin(); it1 != gaps.end(); it1++)
    {
        PdbPreprocessorMissingResidue* gap = (*it1);
        pdb_file->SplitAtomCardOfModelCard(gap->GetResidueChainId(), gap->GetResidueAfterGap());
    }
    LibraryFileSpace::LibraryFileResidue::AtomMap lib_atoms;
    for(PdbPreprocessor::PdbPreprocessorMissingResidueVector::iterator it1 = gaps.begin(); it1 != gaps.end(); it1++)
    {
        PdbPreprocessorMissingResidue* gap = (*it1);
        // Zwitterionic in n terminal
        if(gap->GetStringFormatOfSelectedNTermination().find("+") != string::npos || gap->GetStringFormatOfSelectedNTermination().find("-") != string::npos)
        {
            // Zwitterionic in c terminal
            if(gap->GetStringFormatOfSelectedCTermination().find("+") != string::npos || gap->GetStringFormatOfSelectedCTermination().find("-") != string::npos)
            {
            }
            else
            {
                // Add c terminal at the end of the chain
                PossibleCChainTermination c_termination = gap->GetSelectedCTermination();
                string string_c_termination = gap->GetStringFormatOfCTermination(c_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue = GetLibraryResidueByNameFromMultipleLibraryFiles(string_c_termination, amino_lib_files);
                if(lib_file_residue != NULL)
                {
                    lib_atoms = lib_file_residue->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card = new PdbAtomCard();
                    pdb_atom_card->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it2 = lib_atoms.begin(); it2 != lib_atoms.end(); it2++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it2).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_c_termination, gap->GetResidueChainId(),
                                                                      gap->GetResidueBeforeGap(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card->SetAtoms(atom_map);
                    pdb_file->InsertResidueAfter(pdb_atom_card);
                }
            }
        }
        else
        {
            // Zwitterionic in c terminal
            if(gap->GetStringFormatOfSelectedCTermination().find("+") != string::npos || gap->GetStringFormatOfSelectedCTermination().find("-") != string::npos)
            {
                // Add n terminal residue at the beginning of the chain
                PossibleNChainTermination n_termination = gap->GetSelectedNTermination();
                string string_n_termination = gap->GetStringFormatOfNTermination(n_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue = GetLibraryResidueByNameFromMultipleLibraryFiles(string_n_termination, amino_lib_files);
                if(lib_file_residue != NULL)
                {
                    lib_atoms = lib_file_residue->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card = new PdbAtomCard();
                    pdb_atom_card->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it2 = lib_atoms.begin(); it2 != lib_atoms.end(); it2++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it2).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_n_termination, gap->GetResidueChainId(),
                                                                      gap->GetResidueAfterGap(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card->SetAtoms(atom_map);
                    pdb_file->InsertResidueBefore(pdb_atom_card);
                    if(it1 != --gaps.end())
                    {
                        PdbPreprocessorMissingResidue* next_gap = (*(++it1));
                        if(gap->GetResidueChainId() == next_gap->GetResidueChainId())
{
                            (*it1)->SetResidueBeforeGap((*it1)->GetResidueBeforeGap()+1);
                        }
                        it1--;
                    }
                }
            }
            else
            {
                // Add c terminal residue at the end of the chain
                PossibleCChainTermination c_termination = gap->GetSelectedCTermination();
                string string_c_termination = gap->GetStringFormatOfCTermination(c_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue_from_c_termination = GetLibraryResidueByNameFromMultipleLibraryFiles(string_c_termination, amino_lib_files);
                if(lib_file_residue_from_c_termination != NULL)
                {
                    LibraryFileSpace::LibraryFileResidue::AtomMap lib_atoms_from_c_termination = lib_file_residue_from_c_termination->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card_for_c_termination = new PdbAtomCard();
                    pdb_atom_card_for_c_termination->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map_for_c_termination;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it3 = lib_atoms_from_c_termination.begin(); it3 != lib_atoms_from_c_termination.end(); it3++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it3).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_c_termination, gap->GetResidueChainId(),
                                                                      gap->GetResidueBeforeGap(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map_for_c_termination[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card_for_c_termination->SetAtoms(atom_map_for_c_termination);
                    pdb_file->InsertResidueAfter(pdb_atom_card_for_c_termination);
                    if(it1 != --gaps.end())
                    {
                        PdbPreprocessorMissingResidue* next_gap = (*(++it1));
                        if(gap->GetResidueChainId() == next_gap->GetResidueChainId())
{
                            (*it1)->SetResidueBeforeGap((*it1)->GetResidueBeforeGap()+1);
                        }
                        it1--;
                    }
                }
                // Add n terminal residue at the beginning of the chain
                PossibleNChainTermination n_termination = gap->GetSelectedNTermination();
                string string_n_termination = gap->GetStringFormatOfNTermination(n_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue = GetLibraryResidueByNameFromMultipleLibraryFiles(string_n_termination, amino_lib_files);
                if(lib_file_residue != NULL)
                {
                    LibraryFileSpace::LibraryFileResidue::AtomMap lib_atoms = lib_file_residue->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card = new PdbAtomCard();
                    pdb_atom_card->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it2 = lib_atoms.begin(); it2 != lib_atoms.end(); it2++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it2).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_n_termination, gap->GetResidueChainId(),
                                                                      gap->GetResidueAfterGap(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card->SetAtoms(atom_map);
                    pdb_file->InsertResidueBefore(pdb_atom_card);
                }
            }
        }
    }
}
void PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber (PdbFileSpace::PdbFile * pdb_file, std::vector< std::string > amino_lib_files, PdbPreprocessorMissingResidueVector gaps, int model_number = 1)
Definition at line 2947 of file pdbpreprocessor.cc.
References gmml::dNotSet, LibraryFileSpace::LibraryFileResidue::GetAtoms(), LibraryFileSpace::LibraryFileAtom::GetCoordinate(), LibraryFileSpace::LibraryFileAtom::GetName(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetResidueAfterGap(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetResidueBeforeGap(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetSelectedCTermination(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetSelectedNTermination(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetStringFormatOfCTermination(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetStringFormatOfNTermination(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetStringFormatOfSelectedCTermination(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::GetStringFormatOfSelectedNTermination(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbAtomCard::SetAtoms(), PdbFileSpace::PdbAtomCard::SetRecordName(), PdbPreprocessorSpace::PdbPreprocessorMissingResidue::SetResidueBeforeGap(), and PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber().
{
    for(PdbPreprocessor::PdbPreprocessorMissingResidueVector::iterator it1 = gaps.begin(); it1 != gaps.end(); it1++)
    {
        PdbPreprocessorMissingResidue* gap = (*it1);
        pdb_file->SplitAtomCardOfModelCardWithTheGivenModelNumber(gap->GetResidueChainId(), gap->GetResidueAfterGap(), model_number);
    }
    LibraryFileSpace::LibraryFileResidue::AtomMap lib_atoms;
    for(PdbPreprocessor::PdbPreprocessorMissingResidueVector::iterator it1 = gaps.begin(); it1 != gaps.end(); it1++)
    {
        PdbPreprocessorMissingResidue* gap = (*it1);
        // Zwitterionic in n terminal
        if(gap->GetStringFormatOfSelectedNTermination().find("+") != string::npos || gap->GetStringFormatOfSelectedNTermination().find("-") != string::npos)
        {
            // Zwitterionic in c terminal
            if(gap->GetStringFormatOfSelectedCTermination().find("+") != string::npos || gap->GetStringFormatOfSelectedCTermination().find("-") != string::npos)
            {
            }
            else
            {
                // Add c terminal at the end of the chain
                PossibleCChainTermination c_termination = gap->GetSelectedCTermination();
                string string_c_termination = gap->GetStringFormatOfCTermination(c_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue = GetLibraryResidueByNameFromMultipleLibraryFiles(string_c_termination, amino_lib_files);
                if(lib_file_residue != NULL)
                {
                    lib_atoms = lib_file_residue->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card = new PdbAtomCard();
                    pdb_atom_card->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it2 = lib_atoms.begin(); it2 != lib_atoms.end(); it2++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it2).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_c_termination, gap->GetResidueChainId(),
                                                                      gap->GetResidueBeforeGap(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card->SetAtoms(atom_map);
                    pdb_file->InsertResidueAfterWithTheGivenModelNumber(pdb_atom_card, model_number);
                }
            }
        }
        else
        {
            // Zwitterionic in c terminal
            if(gap->GetStringFormatOfSelectedCTermination().find("+") != string::npos || gap->GetStringFormatOfSelectedCTermination().find("-") != string::npos)
            {
                // Add n terminal residue at the beginning of the chain
                PossibleNChainTermination n_termination = gap->GetSelectedNTermination();
                string string_n_termination = gap->GetStringFormatOfNTermination(n_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue = GetLibraryResidueByNameFromMultipleLibraryFiles(string_n_termination, amino_lib_files);
                if(lib_file_residue != NULL)
                {
                    lib_atoms = lib_file_residue->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card = new PdbAtomCard();
                    pdb_atom_card->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it2 = lib_atoms.begin(); it2 != lib_atoms.end(); it2++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it2).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_n_termination, gap->GetResidueChainId(),
                                                                      gap->GetResidueAfterGap(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card->SetAtoms(atom_map);
                    pdb_file->InsertResidueBeforeWithTheGivenModelNumber(pdb_atom_card, model_number);
                    if(it1 != --gaps.end())
                    {
                        PdbPreprocessorMissingResidue* next_gap = (*(++it1));
                        if(gap->GetResidueChainId() == next_gap->GetResidueChainId())
{
                            (*it1)->SetResidueBeforeGap((*it1)->GetResidueBeforeGap()+1);
                        }
                        it1--;
                    }
                }
            }
            else
            {
                // Add c terminal residue at the end of the chain
                PossibleCChainTermination c_termination = gap->GetSelectedCTermination();
                string string_c_termination = gap->GetStringFormatOfCTermination(c_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue_from_c_termination = GetLibraryResidueByNameFromMultipleLibraryFiles(string_c_termination, amino_lib_files);
                if(lib_file_residue_from_c_termination != NULL)
                {
                    LibraryFileSpace::LibraryFileResidue::AtomMap lib_atoms_from_c_termination = lib_file_residue_from_c_termination->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card_for_c_termination = new PdbAtomCard();
                    pdb_atom_card_for_c_termination->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map_for_c_termination;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it3 = lib_atoms_from_c_termination.begin(); it3 != lib_atoms_from_c_termination.end(); it3++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it3).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_c_termination, gap->GetResidueChainId(),
                                                                      gap->GetResidueBeforeGap(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map_for_c_termination[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card_for_c_termination->SetAtoms(atom_map_for_c_termination);
                    pdb_file->InsertResidueAfterWithTheGivenModelNumber(pdb_atom_card_for_c_termination, model_number);
                    if(it1 != --gaps.end())
                    {
                        PdbPreprocessorMissingResidue* next_gap = (*(++it1));
                        if(gap->GetResidueChainId() == next_gap->GetResidueChainId())
{
                            (*it1)->SetResidueBeforeGap((*it1)->GetResidueBeforeGap()+1);
                        }
                        it1--;
                    }
                }
                // Add n terminal residue at the beginning of the chain
                PossibleNChainTermination n_termination = gap->GetSelectedNTermination();
                string string_n_termination = gap->GetStringFormatOfNTermination(n_termination);
                LibraryFileSpace::LibraryFileResidue* lib_file_residue = GetLibraryResidueByNameFromMultipleLibraryFiles(string_n_termination, amino_lib_files);
                if(lib_file_residue != NULL)
                {
                    LibraryFileSpace::LibraryFileResidue::AtomMap lib_atoms = lib_file_residue->GetAtoms();
                    PdbFileSpace::PdbAtomCard* pdb_atom_card = new PdbAtomCard();
                    pdb_atom_card->SetRecordName("ATOM");
                    PdbFileSpace::PdbAtomCard::PdbAtomMap atom_map;
                    int serial_number = 0;
                    for(LibraryFileSpace::LibraryFileResidue::AtomMap::iterator it2 = lib_atoms.begin(); it2 != lib_atoms.end(); it2++)
                    {
                        LibraryFileSpace::LibraryFileAtom* lib_file_atom = (*it2).second;
                        PdbFileSpace::PdbAtom* pdb_atom = new PdbAtom(serial_number, lib_file_atom->GetName(), ' ', string_n_termination, gap->GetResidueChainId(),
                                                                      gap->GetResidueAfterGap(), ' ', lib_file_atom->GetCoordinate(), dNotSet, dNotSet, " ", "");
                        atom_map[serial_number] = pdb_atom;
                        serial_number++;
                    }
                    pdb_atom_card->SetAtoms(atom_map);
                    pdb_file->InsertResidueBeforeWithTheGivenModelNumber(pdb_atom_card, model_number);
                }
            }
        }
    }
}
void PdbPreprocessor::UpdateHISMapping (PdbFileSpace::PdbFile * pdb_file, PdbPreprocessor::PdbPreprocessorHistidineMappingVector histidine_mappings)
Definition at line 1190 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::GetAllResidues(), PdbFileSpace::PdbFile::GetAtomOfResidueByName(), PdbFileSpace::PdbResidue::GetResidueAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorHistidineMapping::GetResidueAlternateLocation(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorHistidineMapping::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), PdbPreprocessorSpace::PdbPreprocessorHistidineMapping::GetResidueInsertionCode(), PdbFileSpace::PdbResidue::GetResidueName(), PdbFileSpace::PdbResidue::GetResidueSequenceNumber(), PdbPreprocessorSpace::PdbPreprocessorHistidineMapping::GetResidueSequenceNumber(), PdbPreprocessorSpace::PdbPreprocessorHistidineMapping::GetSelectedMapping(), PdbPreprocessorSpace::PdbPreprocessorHistidineMapping::GetStringFormatOfSelectedMapping(), gmml::HID, gmml::HIE, and PdbFileSpace::PdbFile::UpdateResidueName().
{
    to_be_deleted_atoms_.clear();
    to_be_deleted_residues_.clear();
    PdbFileSpace::PdbFile::PdbResidueVector pdb_residues = pdb_file->GetAllResidues();
    for(PdbPreprocessorHistidineMappingVector::iterator it = histidine_mappings.begin(); it != histidine_mappings.end(); it++)
    {
        PdbPreprocessorHistidineMapping* histidine_mapping = (*it);
        string target_key;
        stringstream ss;
        ss << "HIS" << "_" << histidine_mapping->GetResidueChainId() << "_" << histidine_mapping->GetResidueSequenceNumber()
           << "_" << histidine_mapping->GetResidueInsertionCode() << "_" << histidine_mapping->GetResidueAlternateLocation();
        target_key = ss.str();
        for(PdbFileSpace::PdbFile::PdbResidueVector::iterator it1 = pdb_residues.begin(); it1 != pdb_residues.end(); it1++)
        {
            PdbResidue* pdb_residue = (*it1);
            string residue_name = pdb_residue->GetResidueName();
            if((residue_name).compare("HIS") == 0)
            {
                stringstream ss1;
                string pdb_residue_key;
                ss1 << residue_name << "_" << pdb_residue->GetResidueChainId() << "_" << pdb_residue->GetResidueSequenceNumber()
                    << "_" << pdb_residue->GetResidueInsertionCode() << "_" << pdb_residue->GetResidueAlternateLocation();
                pdb_residue_key = ss1.str();
                if(pdb_residue_key.compare(target_key) == 0)
                {
                    // HIE residue
                    PdbAtom* HE2 = pdb_file->GetAtomOfResidueByName(pdb_residue, "HE2");
                    PdbAtom* HD1 = pdb_file->GetAtomOfResidueByName(pdb_residue, "HD1");
                    if(HE2 != NULL && HD1 == NULL)
                    {
                        if(histidine_mapping->GetSelectedMapping() == HID)
{
                            // Delete HE2
//                            pdb_file->DeleteAtom(HE2);
                            to_be_deleted_atoms_.push_back(HE2);
                        }
                    }
                    // HID residue
                    if(HE2 == NULL && HD1 != NULL)
                    {
                        if(histidine_mapping->GetSelectedMapping() == HIE)
{
                            // Delete HD1
//                            pdb_file->DeleteAtom(HD1);
                            to_be_deleted_atoms_.push_back(HD1);
                        }
                    }
                    // HIP residue
                    if(HE2 != NULL && HD1 != NULL)
                    {
                        if(histidine_mapping->GetSelectedMapping() == HIE)
{
                            // Delete HD1
                            pdb_file->DeleteAtom(HD1);
                            to_be_deleted_atoms_.push_back(HD1);
                        }
                        if(histidine_mapping->GetSelectedMapping() == HID)
{
                            // Delete HE2
//                            pdb_file->DeleteAtom(HE2);
                            to_be_deleted_atoms_.push_back(HE2);
                        }
                    }
                    pdb_file->UpdateResidueName(pdb_residue, histidine_mapping->GetStringFormatOfSelectedMapping());
                }
            }
        }
    }
    DeleteAllToBeDeletedEntities(pdb_file);
}
void PdbPreprocessor::UpdateHISMappingWithTheGivenNumber (PdbFileSpace::PdbFile * pdb_file, PdbPreprocessorHistidineMappingVector histidine_mappings, int model_number = 1)
Definition at line 1264 of file pdbpreprocessor.cc.
References PdbFileSpace::PdbFile::GetAllResidues(), PdbFileSpace::PdbFile::GetAtomOfResidueByName(), PdbFileSpace::PdbResidue::GetResidueAlternateLocation(), PdbPreprocessorSpace::PdbPreprocessorHistidineMapping::GetResidueAlternateLocation(), PdbFileSpace::PdbResidue::GetResidueChainId(), PdbPreprocessorSpace::PdbPreprocessorHistidineMapping::GetResidueChainId(), PdbFileSpace::PdbResidue::GetResidueInsertionCode(), PdbPreprocessorSpace::PdbPreprocessorHistidineMapping::GetResidueInsertionCode(), PdbFileSpace::PdbResidue::GetResidueName(), PdbFileSpace::PdbResidue::GetResidueSequenceNumber(), PdbPreprocessorSpace::PdbPreprocessorHistidineMapping::GetResidueSequenceNumber(), PdbPreprocessorSpace::PdbPreprocessorHistidineMapping::GetSelectedMapping(), PdbPreprocessorSpace::PdbPreprocessorHistidineMapping::GetStringFormatOfSelectedMapping(), gmml::HID, gmml::HIE, and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    to_be_deleted_atoms_.clear();
    to_be_deleted_residues_.clear();
    PdbFileSpace::PdbFile::PdbResidueVector pdb_residues = pdb_file->GetAllResidues();
    for(PdbPreprocessorHistidineMappingVector::iterator it = histidine_mappings.begin(); it != histidine_mappings.end(); it++)
    {
        PdbPreprocessorHistidineMapping* histidine_mapping = (*it);
        string target_key;
        stringstream ss;
        ss << "HIS" << "_" << histidine_mapping->GetResidueChainId() << "_" << histidine_mapping->GetResidueSequenceNumber()
           << "_" << histidine_mapping->GetResidueInsertionCode() << "_" << histidine_mapping->GetResidueAlternateLocation();
        target_key = ss.str();
        for(PdbFileSpace::PdbFile::PdbResidueVector::iterator it1 = pdb_residues.begin(); it1 != pdb_residues.end(); it1++)
        {
            PdbResidue* pdb_residue = (*it1);
            string residue_name = pdb_residue->GetResidueName();
            if((residue_name).compare("HIS") == 0)
            {
                stringstream ss1;
                string pdb_residue_key;
                ss1 << residue_name << "_" << pdb_residue->GetResidueChainId() << "_" << pdb_residue->GetResidueSequenceNumber()
                    << "_" << pdb_residue->GetResidueInsertionCode() << "_" << pdb_residue->GetResidueAlternateLocation();
                pdb_residue_key = ss1.str();
                if(pdb_residue_key.compare(target_key) == 0)
                {
                    // HIE residue
                    PdbAtom* HE2 = pdb_file->GetAtomOfResidueByName(pdb_residue, "HE2");
                    PdbAtom* HD1 = pdb_file->GetAtomOfResidueByName(pdb_residue, "HD1");
                    if(HE2 != NULL && HD1 == NULL)
                    {
                        if(histidine_mapping->GetSelectedMapping() == HID)
{
                            // Delete HE2
//                            pdb_file->DeleteAtomWithTheGivenModelNumber(HE2, model_number);
                            to_be_deleted_atoms_.push_back(HE2);
                        }
                    }
                    // HID residue
                    if(HE2 == NULL && HD1 != NULL)
                    {
                        if(histidine_mapping->GetSelectedMapping() == HIE)
{
                            // Delete HD1
//                            pdb_file->DeleteAtomWithTheGivenModelNumber(HD1, model_number);
                            to_be_deleted_atoms_.push_back(HD1);
                        }
                    }
                    // HIP residue
                    if(HE2 != NULL && HD1 != NULL)
                    {
                        if(histidine_mapping->GetSelectedMapping() == HIE)
{
                            // Delete HD1
//                            pdb_file->DeleteAtomWithTheGivenModelNumber(HD1, model_number);
                            to_be_deleted_atoms_.push_back(HD1);
                        }
                        if(histidine_mapping->GetSelectedMapping() == HID)
{
                            // Delete HE2
//                            pdb_file->DeleteAtomWithTheGivenModelNumber(HE2, model_number);
                            to_be_deleted_atoms_.push_back(HE2);
                        }
                    }
                    pdb_file->UpdateResidueNameWithTheGivenModelNumber(pdb_residue, histidine_mapping->GetStringFormatOfSelectedMapping(), model_number);
                }
            }
        }
    }
    DeleteAllToBeDeletedEntitiesWithTheGivenModelNumber(pdb_file, model_number);
}
The documentation for this class was generated from the following files:
includes/Resolver/PdbPreprocessor/pdbpreprocessor.hpp
src/Resolver/PdbPreprocessor/pdbpreprocessor.cc