gmmlNew: LibraryFileSpace::LibraryFile Class Reference
LibraryFileSpace::LibraryFile Class Reference
#include <libraryfile.hpp>
Public Types
typedef std::map< std::string,
LibraryFileResidue * > ResidueMap
Public Member Functions
LibraryFile ()
LibraryFile (const std::string &lib_file)
~LibraryFile ()
const std::string & GetFilePath () const
const ResidueMap & GetResidues () const
Return a map of residues including in the file mapped to the names of the residues.
std::vector< std::string > GetAllResidueNames ()
gmml::ResidueNameMap GetAllResidueNamesMap ()
std::vector< std::string > GetAllAtomNamesOfResidue (std::string residue_name)
void SetPath (std::string path)
void SetResidues (ResidueMap residues)
void Read (std::ifstream &in_file)
LibraryFileAtom * ProcessAtom (std::string &line)
Process a line from the atom section of the file and return a new atom object.
LibraryFileResidue * GetLibraryResidueByResidueName (std::string residue_name)
void Write (const std::string &library_file)
void BuildLibraryFile (std::ofstream &out_stream)
void ResolveAtomSection (std::ofstream &stream, LibraryFileResidue *residue)
void ResolveAtomPertInfoSection (std::ofstream &stream, LibraryFileResidue *residue)
void ResolveBoundBoxSection (std::ofstream &stream, LibraryFileResidue *residue)
void ResolveChildSequenceSection (std::ofstream &stream, LibraryFileResidue *residue)
void ResolveConnectSection (std::ofstream &stream, LibraryFileResidue *residue)
void ResolveConnectivitySection (std::ofstream &stream, LibraryFileResidue *residue)
void ResolveHierarchySection (std::ofstream &stream, LibraryFileResidue *residue)
void ResolveNameSection (std::ofstream &stream, LibraryFileResidue *residue)
void ResolvePositionSection (std::ofstream &stream, LibraryFileResidue *residue)
void ResolveResidueConnectSection (std::ofstream &stream, LibraryFileResidue *residue)
void ResolveResiduesSection (std::ofstream &stream, LibraryFileResidue *residue)
void ResolveResiduePdbSequenceNumberSection (std::ofstream &stream, LibraryFileResidue *residue)
void ResolveSolventCapSection (std::ofstream &stream, LibraryFileResidue *residue)
void ResolveVelocitiesSection (std::ofstream &stream, LibraryFileResidue *residue)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 14 of file libraryfile.hpp.
Member Typedef Documentation
typedef std::map<std::string, LibraryFileResidue*> LibraryFileSpace::LibraryFile::ResidueMap
Definition at line 23 of file libraryfile.hpp.
Constructor & Destructor Documentation
LibraryFile::LibraryFile ()
Definition at line 20 of file libraryfile.cc.
: path_("GMML-Generated"){}
LibraryFile::LibraryFile (const std::string & lib_file)
Close the parameter files
Definition at line 22 of file libraryfile.cc.
References Read().
{
    path_ = lib_file;
    std::ifstream in_file;
    if(std::ifstream(lib_file.c_str()))
        in_file.open(lib_file.c_str());
    else
    {
        throw LibraryFileProcessingException(__LINE__, "Library file not found");
    }
    Read(in_file);
    in_file.close();            /// Close the parameter files
}
LibraryFile::~LibraryFile ()
Definition at line 36 of file libraryfile.cc.
{}
Member Function Documentation
void LibraryFile::BuildLibraryFile (std::ofstream & out_stream)
Definition at line 567 of file libraryfile.cc.
References LibraryFileSpace::LibraryFileResidue::GetName(), ResolveAtomPertInfoSection(), ResolveAtomSection(), ResolveBoundBoxSection(), ResolveChildSequenceSection(), ResolveConnectivitySection(), ResolveConnectSection(), ResolveHierarchySection(), ResolveNameSection(), ResolvePositionSection(), ResolveResidueConnectSection(), ResolveResiduePdbSequenceNumberSection(), ResolveResiduesSection(), ResolveSolventCapSection(), and ResolveVelocitiesSection().
Referenced by Write().
{
    out_stream << "!!index array str" << endl;
    for(ResidueMap::iterator it = residues_.begin(); it != residues_.end(); it++)
    {
        LibraryFileResidue* residue = (*it).second;
        out_stream << "\"" << residue->GetName() << "\"" << endl;
    }
    for(ResidueMap::iterator it = residues_.begin(); it != residues_.end(); it++)
    {
        LibraryFileResidue* residue = (*it).second;
        ResolveAtomSection(out_stream, residue);
        ResolveAtomPertInfoSection(out_stream, residue);
        ResolveBoundBoxSection(out_stream, residue);
        ResolveChildSequenceSection(out_stream, residue);
        ResolveConnectSection(out_stream, residue);
        ResolveConnectivitySection(out_stream, residue);
        ResolveHierarchySection(out_stream, residue);
        ResolveNameSection(out_stream, residue);
        ResolvePositionSection(out_stream, residue);
        ResolveResidueConnectSection(out_stream, residue);
        ResolveResiduesSection(out_stream, residue);
        ResolveResiduePdbSequenceNumberSection(out_stream, residue);
        ResolveSolventCapSection(out_stream, residue);
        ResolveVelocitiesSection(out_stream, residue);
    }
}
vector< string > LibraryFile::GetAllAtomNamesOfResidue (std::string residue_name)
Definition at line 73 of file libraryfile.cc.
References LibraryFileSpace::LibraryFileResidue::GetAtoms(), LibraryFileSpace::LibraryFileAtom::GetName(), and GetResidues().
Referenced by PdbPreprocessorSpace::PdbPreprocessor::GetAllAtomNamesOfResidueFromMultipleLibFiles().
{
    vector<string> atom_names_of_residue;
    ResidueMap residue_map = GetResidues();
    LibraryFileResidue* library_file_residue = residue_map[residue_name];
    LibraryFileResidue::AtomMap atoms = library_file_residue->GetAtoms();
    for(LibraryFileResidue::AtomMap::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        LibraryFileAtom* atom = (*it).second;
        atom_names_of_residue.push_back(atom->GetName());
    }
    return atom_names_of_residue;
}
vector< string > LibraryFile::GetAllResidueNames ()
Definition at line 51 of file libraryfile.cc.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::GetAllAtomNamesOfResidueFromMultipleLibFiles(), PdbPreprocessorSpace::PdbPreprocessor::GetAllResidueNamesFromMultipleLibFiles(), and PdbPreprocessorSpace::PdbPreprocessor::GetAllResidueNamesFromMultipleLibFilesMap().
{
    vector<string> residue_names;
    for(LibraryFile::ResidueMap::iterator it = residues_.begin(); it != residues_.end(); it++)
    {
        string residue_name = (*it).first;
        residue_names.push_back(residue_name);
    }
    return residue_names;
}
ResidueNameMap LibraryFile::GetAllResidueNamesMap ()
Definition at line 62 of file libraryfile.cc.
{
    ResidueNameMap residue_names = ResidueNameMap();
    for(LibraryFile::ResidueMap::iterator it = residues_.begin(); it != residues_.end(); it++)
    {
        string residue_name = (*it).first;
        residue_names[residue_name] = residue_name;
    }
    return residue_names;
}
const std::string & LibraryFile::GetFilePath () const
Return the library file path
Definition at line 41 of file libraryfile.cc.
{
    return path_;
}
LibraryFileResidue * LibraryFile::GetLibraryResidueByResidueName (std::string residue_name)
Definition at line 535 of file libraryfile.cc.
References GetResidues().
Referenced by MolecularModeling::Assembly::BuildStructureByDatabaseFilesBondingInformation(), MolecularModeling::Assembly::BuildStructureByLIBFileInformation(), and PdbPreprocessorSpace::PdbPreprocessor::GetLibraryResidueByNameFromMultipleLibraryFiles().
{
    ResidueMap residue_map = this->GetResidues();
    for(ResidueMap::iterator it = residue_map.begin(); it != residue_map.end(); it++)
    {
        string name = (*it).first;
        LibraryFileResidue* residue = (*it).second;
        if(name.compare(residue_name) == 0)
            return residue;
    }
    return NULL;
}
const LibraryFile::ResidueMap & LibraryFile::GetResidues () const
Return a map of residues including in the file mapped to the names of the residues.
Definition at line 47 of file libraryfile.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromLibraryFile(), GetAllAtomNamesOfResidue(), PdbPreprocessorSpace::PdbPreprocessor::GetAllAtomNamesOfResidueNamesFromMultipleLibFiles(), PdbPreprocessorSpace::PdbPreprocessor::GetAllResiduesFromMultipleLibFilesMap(), and GetLibraryResidueByResidueName().
{
    return residues_;
}
void LibraryFile::Print (std::ostream & out = std::cout)
Definition at line 714 of file libraryfile.cc.
{
    for(LibraryFile::ResidueMap::iterator it = residues_.begin(); it != residues_.end(); it++)
    {
        //        for(unsigned int i = 0; i < it -> second -> GetAtoms().size(); i++)
        //        {
        //            for(unsigned int j = 0; j < it->second->GetAtomByIndex(i+1)->GetBondedAtomsIndicies().size(); j++)
        //                cout << it -> second -> GetAtomByIndex(i+1)->GetBondedAtomsIndicies()[j] << ", ";
        //            cout << endl;
        //        }
        //        cout << endl;
        it->second->Print(out);
    }
}
LibraryFileAtom * LibraryFile::ProcessAtom (std::string & line)
Process a line from the atom section of the file and return a new atom object.
Create a stream from the given line
Split the line by space to extract attributes of the atom
Definition at line 515 of file libraryfile.cc.
References gmml::RemoveQuotes().
Referenced by Read().
{
    string name;
    string type;
    int residue_index;
    int atom_index;
    int atomic_number;
    double charge;
    int int_t;
    istringstream ss(line);             /// Create a stream from the given line
    ss >> name >> type >> int_t >> residue_index >> int_t >> atom_index >> atomic_number >> charge;     /// Split the line by space to extract attributes of the atom
    RemoveQuotes(name);
    RemoveQuotes(type);
    LibraryFileAtom* atom = new LibraryFileAtom(type, name, residue_index, atom_index, atomic_number, charge);
    return atom;
}
void LibraryFile::Read (std::ifstream & in_file)
Read the given file and extract all required fileds into the library file data structure
Unable to read file
Skip blank lines at the begining of the file
Process index section
Read the next line
Iterate on all residues indicated in the index section of the file
Process the atom section of the file for the corresponding residue
Get the first line of the section
Iterate until to the next section that indicates by ! at the begining of the read line
Process atom section
Add the atom into the list of atoms of the corresponding residue
Read the next line
Process the atompertinfo section of the file for the corresponding residue
Get the first line of the section
Iterate until to the next section that indicates by ! at the begining of the read line
Process atompertinfo section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
Read the next line
Process the boundbox section of the file for the corresponding residue
Get the first line of the section
Iterate until to the next section that indicates by ! at the begining of the read line
Process boundbox section
If the number written in the first line of the section is negative then boundbox attributes have not been defined in the file
If the number written in the first line of the section is positive then set the attributes of the boundbox section
Read the next line
Process the childsequence section of the file for the corresponding residue
Get the first line of the section
Iterate until to the next section that indicates by ! at the begining of the read line
Process childsequence section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
Process the connect section of the file for the corresponding residue
Get the first line of the section
Iterate until to the next section that indicates by ! at the begining of the read line
Process connect section
Process the connectivity section of the file for the corresponding residue
Get the first line of the section
Iterate until to the next section that indicates by ! at the begining of the read line
Process connectivity section
Read the next line
Process the hierarchy section of the file for the corresponding residue
Get the first line of the section
Iterate until to the next section that indicates by ! at the begining of the read line
Process hierarchy section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
Read the next line
Process the name section of the file for the corresponding residue
Get the first line of the section
Iterate until to the next section that indicates by ! at the begining of the read line
Process name section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
Read the next line
Process the positions section of the file for the corresponding residue
Get the first line of the section
Iterate until to the next section that indicates by ! at the begining of the read line
Process positions section
Read the next line
Process the residueconnect section of the file for the corresponding residue
Get the first line of the section
Iterate until to the next section that indicates by ! at the begining of the read line
Process residueconnect section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
Read the next line
Process the residues section of the file for the corresponding residue
Get the first line of the section
Iterate until to the next section that indicates by ! at the begining of the read line
Process residues section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
Read the next line
Process the residuesPdbSequenceNumber section of the file for the corresponding residue
Get the first line of the section
Iterate until to the next section that indicates by ! at the begining of the read line
Process residuesPdbSequenceNumber section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
Read the next line
Process the solventcap section of the file for the corresponding residue
Get the first line of the section
Iterate until to the next section that indicates by ! at the begining of the read line
Process solventcap section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
Read the next line
Process the velocities section of the file for the corresponding residue
Get the first line of the section
Iterate until to the next section that indicates by ! at the begining of the read line
Process velocities section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
Read the next line
Definition at line 110 of file libraryfile.cc.
References gmml::dNotSet, ProcessAtom(), gmml::RemoveQuotes(), gmml::RemoveSpaces(), LibraryFileSpace::LibraryFileAtom::SetAtomOrder(), and gmml::Trim().
Referenced by LibraryFile().
{
    string line;
    /// Unable to read file
    if (!getline(in_file, line))
    {
        throw LibraryFileProcessingException("Error reading file");
    }
    /// Skip blank lines at the begining of the file
    while(line[0] != '!')
    {
        getline(in_file, line);
    }
    if(line.find("index") != string::npos)
    {
        getline(in_file, line);
        while(line[0] != '!')
        {
            try
            {
                /// Process index section
                RemoveQuotes(line);
                RemoveSpaces(line);
                residues_[line] = new LibraryFileResidue(line);
                getline(in_file,line);      /// Read the next line
            } catch(...)
            {
                throw LibraryFileProcessingException(__LINE__, "Error processing index section");
            }
        }
    }
    /// Iterate on all residues indicated in the index section of the file
    for(LibraryFile::ResidueMap::iterator it = residues_.begin(); it != residues_.end(); it++)
    {
        /// Process the atom section of the file for the corresponding residue
        if(line.find("atoms") != string::npos)
        {
            int order = 0;
            getline(in_file, line);                 /// Get the first line of the section
            while(line[0] != '!')                   /// Iterate until to the next section that indicates by ! at the begining of the read line
            {
                try
                {
                    /// Process atom section
                    order++;
                    LibraryFileAtom* newAtom = ProcessAtom(line);
                    newAtom->SetAtomOrder(order);;
                    it->second->AddAtom(newAtom);               /// Add the atom into the list of atoms of the corresponding residue
                    getline(in_file,line);      /// Read the next line
                } catch(...)
                {
                    throw LibraryFileProcessingException(__LINE__, "Error processing atom section");
                }
            }
        }
        else
        {
            throw LibraryFileProcessingException(__LINE__, "Unknown section or missing section");
        }
        /// Process the atompertinfo section of the file for the corresponding residue
        if(line.find("atomspertinfo") != string::npos)
        {
            getline(in_file, line);                 /// Get the first line of the section
            while(line[0] != '!')                   /// Iterate until to the next section that indicates by ! at the begining of the read line
            {
                try
                {
                    /// Process atompertinfo section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
                    getline(in_file,line);      /// Read the next line
                } catch(...)
                {
                    throw LibraryFileProcessingException(__LINE__, "Error processing atom pert info section");
                }
            }
        }
        else
        {
            throw LibraryFileProcessingException(__LINE__, "Unknown section or missing section");
        }
        /// Process the boundbox section of the file for the corresponding residue
        if(line.find("boundbox") != string::npos)
        {
            getline(in_file, line);                 /// Get the first line of the section
            while(line[0] != '!')                   /// Iterate until to the next section that indicates by ! at the begining of the read line
            {
                try
                {
                    /// Process boundbox section
                    double is_box_set;
                    istringstream ss(line);
                    ss >> is_box_set;
                    if(is_box_set < 0)              /// If the number written in the first line of the section is negative then boundbox attributes have not been defined in the file
                    {
                        getline(in_file, line);
                        it->second->SetBoxAngle(dNotSet);
                        getline(in_file, line);
                        it->second->SetBoxLength(dNotSet);
                        getline(in_file, line);
                        it->second->SetBoxWidth(dNotSet);
                        getline(in_file, line);
                        it->second->SetBoxHeight(dNotSet);
                    }
                    else                        /// If the number written in the first line of the section is positive then set the attributes of the boundbox section
                    {
                        getline(in_file, line);
                        double val;
                        ss.str(line);
                        ss >> val;
                        it->second->SetBoxAngle(val);
                        getline(in_file, line);
                        ss.str(line);
                        ss >> val;
                        it->second->SetBoxLength(val);
                        getline(in_file, line);
                        ss.str(line);
                        ss >> val;
                        it->second->SetBoxWidth(val);
                        getline(in_file, line);
                        ss.str(line);
                        ss >> val;
                        it->second->SetBoxHeight(val);
                    }
                    getline(in_file,line);      /// Read the next line
                } catch(...)
                {
                    throw LibraryFileProcessingException(__LINE__, "Error processing bound box section");
                }
            }
        }
        else
        {
            throw LibraryFileProcessingException(__LINE__, "Unknown section or missing section");
        }
        /// Process the childsequence section of the file for the corresponding residue
        if(line.find("childsequence") != string::npos)
        {
            getline(in_file, line);                 /// Get the first line of the section
            while(line[0] != '!')                   /// Iterate until to the next section that indicates by ! at the begining of the read line
            {
                try
                {
                    /// Process childsequence section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
                    getline(in_file,line);
                } catch(...)
                {
                    throw LibraryFileProcessingException(__LINE__, "Error processing child sequence section");
                }
            }
        }
        else
        {
            throw LibraryFileProcessingException(__LINE__, "Unknown section or missing section");
        }
        /// Process the connect section of the file for the corresponding residue
        if(line.find("connect") != string::npos)
        {
            getline(in_file, line);                 /// Get the first line of the section
            while(line[0] != '!')                   /// Iterate until to the next section that indicates by ! at the begining of the read line
            {
                try
                {
                    /// Process connect section
                    int head_index;
                    istringstream ss(line);
                    ss >> head_index;
                    getline(in_file,line);
                    int tail_index;
                    istringstream sss(line);
                    sss >> tail_index;
                    getline(in_file,line);
                    it->second->SetHeadAtomIndex(head_index);
                    it->second->SetTailAtomIndex(tail_index);
                } catch(...)
                {
                    throw LibraryFileProcessingException(__LINE__, "Error processing connect section");
                }
            }
        }
        else
        {
            throw LibraryFileProcessingException(__LINE__, "Unknown section or missing section");
        }
        /// Process the connectivity section of the file for the corresponding residue
        if(line.find("connectivity") != string::npos)
        {
            getline(in_file, line);                 /// Get the first line of the section
            while(line[0] != '!')                   /// Iterate until to the next section that indicates by ! at the begining of the read line
            {
                try
                {
                    /// Process connectivity section
                    istringstream ss(line);
                    int from;
                    int to;
                    int t_int;
                    ss >> from >> to >> t_int;
                    it -> second -> GetAtomByIndex(from)->AddBondedAtomIndex(to);
                    it -> second -> GetAtomByIndex(to)->AddBondedAtomIndex(from);
                    getline(in_file,line);      /// Read the next line
                } catch(...)
                {
                    throw LibraryFileProcessingException(__LINE__, "Error processing connectivity section");
                }
            }
        }
        else
        {
            throw LibraryFileProcessingException(__LINE__, "Unknown section or missing section");
        }
        /// Process the hierarchy section of the file for the corresponding residue
        if(line.find("hierarchy") != string::npos)
        {
            getline(in_file, line);                 /// Get the first line of the section
            while(line[0] != '!')                   /// Iterate until to the next section that indicates by ! at the begining of the read line
            {
                try
                {
                    /// Process hierarchy section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
                    getline(in_file,line);      /// Read the next line
                } catch(...)
                {
                    throw LibraryFileProcessingException(__LINE__, "Error processing hierarchy section");
                }
            }
        }
        else
        {
            throw LibraryFileProcessingException(__LINE__, "Unknown section or missing section");
        }
        /// Process the name section of the file for the corresponding residue
        if(line.find("name") != string::npos)
        {
            getline(in_file, line);                 /// Get the first line of the section
            while(line[0] != '!')                   /// Iterate until to the next section that indicates by ! at the begining of the read line
            {
                try
                {
                    /// Process name section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
                    getline(in_file,line);      /// Read the next line
                } catch(...)
                {
                    throw LibraryFileProcessingException(__LINE__, "Error processing name section");
                }
            }
        }
        else
        {
            throw LibraryFileProcessingException(__LINE__, "Unknown section or missing section");
        }
        /// Process the positions section of the file for the corresponding residue
        if(line.find("positions") != string::npos)
        {
            int order = 0;
            getline(in_file, line);                 /// Get the first line of the section
            while(line[0] != '!')                   /// Iterate until to the next section that indicates by ! at the begining of the read line
            {
                try
                {
                    /// Process positions section
                    order ++;
                    istringstream ss(line);
                    double x, y, z;
                    ss >> x >> y >> z;
                    Coordinate crd(x, y, z);
                    it->second->GetAtomByOrder(order)->SetCoordinate(crd);
                    getline(in_file,line);      /// Read the next line
                } catch(...)
                {
                    throw LibraryFileProcessingException(__LINE__, "Error processing positions section");
                }
            }
        }
        else
        {
            throw LibraryFileProcessingException(__LINE__, "Unknown section or missing section");
        }
        /// Process the residueconnect section of the file for the corresponding residue
        if(line.find("residueconnect") != string::npos)
        {
            getline(in_file, line);                 /// Get the first line of the section
            while(line[0] != '!')                   /// Iterate until to the next section that indicates by ! at the begining of the read line
            {
                try
                {
                    /// Process residueconnect section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
                    getline(in_file,line);      /// Read the next line
                } catch(...)
                {
                    throw LibraryFileProcessingException(__LINE__, "Error processing residue connect section");
                }
            }
        }
        else
        {
            throw LibraryFileProcessingException(__LINE__, "Unknown section or missing section");
        }
        /// Process the residues section of the file for the corresponding residue
        if(line.find("residues") != string::npos)
        {
            getline(in_file, line);                 /// Get the first line of the section
            while(line[0] != '!')                   /// Iterate until to the next section that indicates by ! at the begining of the read line
            {
                try
                {
                    /// Process residues section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
                    getline(in_file,line);      /// Read the next line
                } catch(...)
                {
                    throw LibraryFileProcessingException(__LINE__, "Error processing residues section");
                }
            }
        }
        else
        {
            throw LibraryFileProcessingException(__LINE__, "Unknown section or missing section");
        }
        /// Process the residuesPdbSequenceNumber section of the file for the corresponding residue
        if(line.find("residuesPdbSequenceNumber") != string::npos)
        {
            getline(in_file, line);                 /// Get the first line of the section
            while(line[0] != '!')                   /// Iterate until to the next section that indicates by ! at the begining of the read line
            {
                try
                {
                    /// Process residuesPdbSequenceNumber section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
                    getline(in_file,line);      /// Read the next line
                } catch(...)
                {
                    throw LibraryFileProcessingException(__LINE__, "Error processing residuePdbSequenceNumber section");
                }
            }
        }
        else
        {
            throw LibraryFileProcessingException(__LINE__, "Unknown section or missing section");
        }
        /// Process the solventcap section of the file for the corresponding residue
        if(line.find("solventcap") != string::npos)
        {
            getline(in_file, line);                 /// Get the first line of the section
            while(line[0] != '!')                   /// Iterate until to the next section that indicates by ! at the begining of the read line
            {
                try
                {
                    /// Process solventcap section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
                    getline(in_file,line);      /// Read the next line
                } catch(...)
                {
                    throw LibraryFileProcessingException(__LINE__, "Error processing solventcap section");
                }
            }
        }
        else
        {
            throw LibraryFileProcessingException(__LINE__, "Unknown section or missing section");
        }
        /// Process the velocities section of the file for the corresponding residue
        if(line.find("velocities") != string::npos)
        {
            getline(in_file, line);                 /// Get the first line of the section
            while(line[0] != '!' && !Trim(line).empty())                   /// Iterate until to the next section that indicates by ! at the begining of the read line
            {
                try
                {
                    /// Process velocities section -> This section doesn't have any useful information -> Ignore the section by reading the file until the next section
                    getline(in_file,line);      /// Read the next line
                } catch(...)
                {
                    throw LibraryFileProcessingException(__LINE__, "Error processing velocities section");
                }
            }
        }
        else
        {
            throw LibraryFileProcessingException(__LINE__, "Unknown section or missing section");
        }
    }
}
void LibraryFile::ResolveAtomPertInfoSection (std::ofstream & stream, LibraryFileResidue * residue)
Definition at line 606 of file libraryfile.cc.
References LibraryFileSpace::LibraryFileResidue::GetName().
Referenced by BuildLibraryFile().
{
    stream << "!entry." << residue->GetName() << ".unit.atomspertinfo table  str pname  str ptype  int ptypex  int pelmnt  dbl pchg" << endl;
    stream << endl;
}
void LibraryFile::ResolveAtomSection (std::ofstream & stream, LibraryFileResidue * residue)
Definition at line 594 of file libraryfile.cc.
References LibraryFileSpace::LibraryFileResidue::GetAtomByOrder(), LibraryFileSpace::LibraryFileAtom::GetAtomicNumber(), LibraryFileSpace::LibraryFileAtom::GetAtomIndex(), LibraryFileSpace::LibraryFileResidue::GetAtoms(), LibraryFileSpace::LibraryFileAtom::GetCharge(), LibraryFileSpace::LibraryFileResidue::GetName(), LibraryFileSpace::LibraryFileAtom::GetName(), LibraryFileSpace::LibraryFileAtom::GetResidueIndex(), and LibraryFileSpace::LibraryFileAtom::GetType().
Referenced by BuildLibraryFile().
{
    LibraryFileResidue::AtomMap atoms = residue->GetAtoms();
    const string FLAG = "131072";
    stream << "!entry." << residue->GetName() << ".unit.atoms table  str name  str type  int typex  int resx  int flags  int seq  int elmnt  dbl chg" << endl;
    for(unsigned int i = 0; i < atoms.size(); i++)
    {
        LibraryFileAtom* atom = residue->GetAtomByOrder(i+1);
        stream << "\"" << atom->GetName() << "\" " << "\"" << atom->GetType() << "\" " << "0" << " " << atom->GetResidueIndex() << " " << FLAG << " "
               << atom->GetAtomIndex() << " " << atom->GetAtomicNumber() << " " << fixed << atom->GetCharge() << endl;
    }
}
void LibraryFile::ResolveBoundBoxSection (std::ofstream & stream, LibraryFileResidue * residue)
Definition at line 612 of file libraryfile.cc.
References gmml::dNotSet, LibraryFileSpace::LibraryFileResidue::GetBoxAngle(), LibraryFileSpace::LibraryFileResidue::GetBoxHeight(), LibraryFileSpace::LibraryFileResidue::GetBoxLength(), LibraryFileSpace::LibraryFileResidue::GetBoxWidth(), and LibraryFileSpace::LibraryFileResidue::GetName().
Referenced by BuildLibraryFile().
{
    stream << "!entry." << residue->GetName() << ".unit.boundbox array dbl" << endl;
    stream << "-1.000000" << endl;
    if(residue->GetBoxAngle() == dNotSet)
        stream << "0.0" << endl;
    else
        stream << residue->GetBoxAngle() << endl;
    if(residue->GetBoxLength() == dNotSet)
        stream << "0.0" << endl;
    else
        stream << fixed << residue->GetBoxLength() << endl;
    if(residue->GetBoxWidth() == dNotSet)
        stream << "0.0" << endl;
    else
        stream << fixed << residue->GetBoxWidth() << endl;
    if(residue->GetBoxHeight() == dNotSet)
        stream << "0.0" << endl;
    else
        stream << fixed << residue->GetBoxHeight() << endl;
}
void LibraryFile::ResolveChildSequenceSection (std::ofstream & stream, LibraryFileResidue * residue)
Definition at line 633 of file libraryfile.cc.
References LibraryFileSpace::LibraryFileResidue::GetName().
Referenced by BuildLibraryFile().
{
    stream << "!entry." << residue->GetName() << ".unit.childsequence single int" << endl;
    stream << endl;
}
void LibraryFile::ResolveConnectivitySection (std::ofstream & stream, LibraryFileResidue * residue)
Definition at line 646 of file libraryfile.cc.
References LibraryFileSpace::LibraryFileResidue::GetAtomByOrder(), LibraryFileSpace::LibraryFileAtom::GetAtomIndex(), LibraryFileSpace::LibraryFileResidue::GetAtoms(), LibraryFileSpace::LibraryFileAtom::GetBondedAtomsIndices(), and LibraryFileSpace::LibraryFileResidue::GetName().
Referenced by BuildLibraryFile().
{
    stream << "!entry." << residue->GetName() << ".unit.connectivity table  int atom1x  int atom2x  int flags" << endl;
    LibraryFileResidue::AtomMap atoms = residue->GetAtoms();
    for(unsigned int i = 0; i < atoms.size(); i++)
    {
        LibraryFileAtom* atom = residue->GetAtomByOrder(i+1);
        vector<int> bonded_atoms_indices = atom->GetBondedAtomsIndices();
        for(vector<int>::iterator it = bonded_atoms_indices.begin(); it != bonded_atoms_indices.end(); it++)
        {
            int bonded_atom_index = (*it);
            if(bonded_atom_index > atom->GetAtomIndex())
            {
                stream << atom->GetAtomIndex() << " " << bonded_atom_index << " " << "1" << endl;
            }
        }
    }
}
void LibraryFile::ResolveConnectSection (std::ofstream & stream, LibraryFileResidue * residue)
Definition at line 638 of file libraryfile.cc.
References LibraryFileSpace::LibraryFileResidue::GetHeadAtomIndex(), LibraryFileSpace::LibraryFileResidue::GetName(), LibraryFileSpace::LibraryFileResidue::GetTailAtomIndex(), and gmml::iNotSet.
Referenced by BuildLibraryFile().
{
    stream << "!entry." << residue->GetName() << ".unit.connect array int" << endl;
    if(residue->GetHeadAtomIndex() != iNotSet)
        stream << residue->GetHeadAtomIndex() << endl;
    if(residue->GetTailAtomIndex() != iNotSet)
        stream << residue->GetTailAtomIndex() << endl;
}
void LibraryFile::ResolveHierarchySection (std::ofstream & stream, LibraryFileResidue * residue)
Definition at line 664 of file libraryfile.cc.
References LibraryFileSpace::LibraryFileResidue::GetName().
Referenced by BuildLibraryFile().
{
    stream << "!entry." << residue->GetName() << ".unit.hierarchy table  str abovetype  int abovex  str belowtype  int belowx" << endl;
    stream << endl;
}
void LibraryFile::ResolveNameSection (std::ofstream & stream, LibraryFileResidue * residue)
Definition at line 669 of file libraryfile.cc.
References LibraryFileSpace::LibraryFileResidue::GetName().
Referenced by BuildLibraryFile().
{
    stream << "!entry." << residue->GetName() << ".unit.name single str" << endl;
    stream << "\"" << residue->GetName() << "\"" << endl;
}
void LibraryFile::ResolvePositionSection (std::ofstream & stream, LibraryFileResidue * residue)
Definition at line 674 of file libraryfile.cc.
References LibraryFileSpace::LibraryFileResidue::GetAtomByOrder(), LibraryFileSpace::LibraryFileResidue::GetAtoms(), LibraryFileSpace::LibraryFileAtom::GetCoordinate(), LibraryFileSpace::LibraryFileResidue::GetName(), Geometry::Coordinate::GetX(), Geometry::Coordinate::GetY(), and Geometry::Coordinate::GetZ().
Referenced by BuildLibraryFile().
{
    stream << "!entry." << residue->GetName() << ".unit.positions table  dbl x  dbl y  dbl z" << endl;
    LibraryFileResidue::AtomMap atoms = residue->GetAtoms();
    for(unsigned int i = 0; i < atoms.size(); i++)
    {
        LibraryFileAtom* atom = residue->GetAtomByOrder(i+1);
        Geometry::Coordinate coordinate = atom->GetCoordinate();
        stream << fixed << coordinate.GetX() << " " << fixed << coordinate.GetY() << " " << fixed << coordinate.GetZ() << endl;
    }
}
void LibraryFile::ResolveResidueConnectSection (std::ofstream & stream, LibraryFileResidue * residue)
Definition at line 685 of file libraryfile.cc.
References LibraryFileSpace::LibraryFileResidue::GetName().
Referenced by BuildLibraryFile().
{
    stream << "!entry." << residue->GetName() << ".unit.residueconnect table  int c1x  int c2x  int c3x  int c4x  int c5x  int c6x" << endl;
    stream << endl;
}
void LibraryFile::ResolveResiduePdbSequenceNumberSection (std::ofstream & stream, LibraryFileResidue * residue)
Definition at line 695 of file libraryfile.cc.
References LibraryFileSpace::LibraryFileResidue::GetName().
Referenced by BuildLibraryFile().
{
    stream << "!entry." << residue->GetName() <<  ".unit.residuesPdbSequenceNumber array int" << endl;
    stream << endl;
}
void LibraryFile::ResolveResiduesSection (std::ofstream & stream, LibraryFileResidue * residue)
Definition at line 690 of file libraryfile.cc.
References LibraryFileSpace::LibraryFileResidue::GetName().
Referenced by BuildLibraryFile().
{
    stream << "!entry." << residue->GetName() << ".unit.residues table  str name  int seq  int childseq  int startatomx  str restype  int imagingx" << endl;
    stream << endl;
}
void LibraryFile::ResolveSolventCapSection (std::ofstream & stream, LibraryFileResidue * residue)
Definition at line 700 of file libraryfile.cc.
References LibraryFileSpace::LibraryFileResidue::GetName().
Referenced by BuildLibraryFile().
{
    stream << "!entry." << residue->GetName() << ".unit.solventcap array dbl" << endl;
    stream << endl;
}
void LibraryFile::ResolveVelocitiesSection (std::ofstream & stream, LibraryFileResidue * residue)
Definition at line 705 of file libraryfile.cc.
References LibraryFileSpace::LibraryFileResidue::GetName().
Referenced by BuildLibraryFile().
{
    stream << "!entry." << residue->GetName() << ".unit.velocities table  dbl x  dbl y  dbl z" << endl;
    stream << endl;
}
void LibraryFile::SetPath (std::string path)
Definition at line 90 of file libraryfile.cc.
{
    path_ = path;
}
void LibraryFile::SetResidues (ResidueMap residues)
Definition at line 95 of file libraryfile.cc.
Referenced by MolecularModeling::Assembly::BuildLibraryFileStructureFromAssembly().
{
    residues_.clear();
    for(ResidueMap::iterator it = residues.begin(); it != residues.end(); it++)
    {
        LibraryFileResidue* residue = (*it).second;
        string residue_name = (*it).first;
        residues_[residue_name] = residue;
    }
}
void LibraryFile::Write (const std::string & library_file)
Definition at line 547 of file libraryfile.cc.
References BuildLibraryFile().
{
    std::ofstream out_file;
    try
    {
        out_file.open(library_file.c_str());
    }
    catch(...)
    {
        throw LibraryFileProcessingException(__LINE__,"File could not be created");
    }
    try
    {
        this->BuildLibraryFile(out_file);
    }
    catch(...)
    {
        out_file.close();
    }
}
The documentation for this class was generated from the following files:
includes/ParameterSet/LibraryFileSpace/libraryfile.hpp
src/ParameterSet/LibraryFileSpace/libraryfile.cc