gmmlNew: TopologyFileSpace::TopologyAtom Class Reference
TopologyFileSpace::TopologyAtom Class Reference
#include <topologyatom.hpp>
Public Types
typedef std::vector< std::string > ExcludedAtomNames
Public Member Functions
TopologyAtom ()
TopologyAtom (int atom_index, std::string atom_name, std::string type, double atom_charge, int atomic_number, double atom_mass, ExcludedAtomNames excluded_atoms, int number_of_excluded_atoms, double radii, double screen, std::string tree_chain_classification, std::string residue_name)
std::string GetAtomName ()
double GetAtomCharge ()
int GetAtomicNumber ()
double GetAtomMass ()
std::vector< std::string > GetExcludedAtoms ()
double GetRadii ()
double GetScreen ()
std::string GetTreeChainClassification ()
int GetNumberOfExcludedAtoms ()
std::string GetType ()
int GetIndex ()
std::string GetResidueName ()
void SetAtomName (std::string atom_name)
void SetAtomCharge (double atom_charge)
void SetAtomicNumber (int atomic_number)
void SetAtomMass (double atom_mass)
void SetExcludedAtoms (std::vector< std::string > excluded_atoms)
void SetRadii (double radii)
void SetScreen (double screen)
void SetTreeChainClasification (std::string tree_chain_classification)
void SetNumberOfExcludedAtoms (int number_of_excluded_atoms)
void SetType (std::string type)
void SetIndex (int index)
void SetResidueName (std::string residue_name)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 11 of file topologyatom.hpp.
Member Typedef Documentation
typedef std::vector<std::string> TopologyFileSpace::TopologyAtom::ExcludedAtomNames
Definition at line 20 of file topologyatom.hpp.
Constructor & Destructor Documentation
TopologyAtom::TopologyAtom ()
Definition at line 11 of file topologyatom.cc.
{}
TopologyFileSpace::TopologyAtom::TopologyAtom (int atom_index, std::string atom_name, std::string type, double atom_charge, int atomic_number, double atom_mass, ExcludedAtomNames excluded_atoms, int number_of_excluded_atoms, double radii, double screen, std::string tree_chain_classification, std::string residue_name)
Member Function Documentation
double TopologyAtom::GetAtomCharge ()
Definition at line 32 of file topologyatom.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveChargeSection().
{
    return atom_charge_;
}
int TopologyAtom::GetAtomicNumber ()
Definition at line 36 of file topologyatom.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveAtomicNumberSection().
{
    return atomic_number_;
}
double TopologyAtom::GetAtomMass ()
Definition at line 40 of file topologyatom.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveMassSection().
{
    return atom_mass_;
}
string TopologyAtom::GetAtomName ()
Definition at line 28 of file topologyatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromTopologyCoordinateFile(), MolecularModeling::Assembly::BuildAssemblyFromTopologyFile(), TopologyFileSpace::TopologyAssembly::GetAtomIndexByName(), and TopologyFileSpace::TopologyFile::ResolveAtomNameSection().
{
    return atom_name_;
}
vector< string > TopologyAtom::GetExcludedAtoms ()
Definition at line 44 of file topologyatom.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveExcludedAtomsListSection(), and TopologyFileSpace::TopologyFile::ResolveNumberExcludedAtomsSection().
{
    return excluded_atoms_;
}
int TopologyAtom::GetIndex ()
Definition at line 68 of file topologyatom.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromTopologyCoordinateFile(), TopologyFileSpace::TopologyResidue::GetAtomByIndex(), TopologyFileSpace::TopologyAssembly::GetAtomIndexByName(), and TopologyFileSpace::TopologyFile::ResolveNonbondedParmIndexSection().
{
    return index_;
}
int TopologyAtom::GetNumberOfExcludedAtoms ()
Definition at line 60 of file topologyatom.cc.
{
    return number_of_excluded_atoms_;
}
double TopologyAtom::GetRadii ()
Definition at line 48 of file topologyatom.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveRadiiSection().
{
    return radii_;
}
string TopologyAtom::GetResidueName ()
Definition at line 72 of file topologyatom.cc.
{
    return residue_name_;
}
double TopologyAtom::GetScreen ()
Definition at line 52 of file topologyatom.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveScreenSection().
{
    return screen_;
}
string TopologyAtom::GetTreeChainClassification ()
Definition at line 56 of file topologyatom.cc.
Referenced by TopologyFileSpace::TopologyFile::ResolveTreeChainClassificationSection().
{
    return tree_chain_classification_;
}
string TopologyAtom::GetType ()
Definition at line 64 of file topologyatom.cc.
Referenced by TopologyFileSpace::TopologyFile::GetAtomTypeIndexMap(), TopologyFileSpace::TopologyFile::ResolveAmberAtomTypeSection(), TopologyFileSpace::TopologyFile::ResolveAtomTypeIndexSection(), and TopologyFileSpace::TopologyFile::ResolveNonbondedParmIndexSection().
{
    return type_;
}
void TopologyAtom::Print (std::ostream & out = std::cout)
Definition at line 140 of file topologyatom.cc.
Referenced by TopologyFileSpace::TopologyResidue::Print().
{
    out << "Index: " << index_ << endl
           << "Residue Name: " << residue_name_ << endl
        << "Atom Name: " << atom_name_ << endl
        << "Charge: " << scientific << setprecision(8) << atom_charge_  << endl
        << "Atomic Number: " << atomic_number_ << endl
        << "Mass: " << scientific << setprecision(8) << atom_mass_ << endl
        << "Excluded Atoms: ";
    for(vector<string>::iterator it = excluded_atoms_.begin(); it != excluded_atoms_.end(); it++)
    {
        string atom_name = (*it);
        out << atom_name << "; ";
    }
    out << endl
        << "Radii: " << scientific << setprecision(8) << radii_ << endl
        << "Screen: " << scientific << setprecision(8) << screen_ << endl
        << "Tree Chain Classification: " << tree_chain_classification_ << endl
        << "Number of Excluded Atoms: " << number_of_excluded_atoms_ << endl
        << "Atom Type: " << type_ << endl << endl;
}
void TopologyAtom::SetAtomCharge (double atom_charge)
Definition at line 84 of file topologyatom.cc.
{
    atom_charge_ = atom_charge;
}
void TopologyAtom::SetAtomicNumber (int atomic_number)
Definition at line 88 of file topologyatom.cc.
{
    atomic_number_ = atomic_number;
}
void TopologyAtom::SetAtomMass (double atom_mass)
Definition at line 92 of file topologyatom.cc.
{
    atom_mass_ = atom_mass;
}
void TopologyAtom::SetAtomName (std::string atom_name)
Definition at line 80 of file topologyatom.cc.
{
    atom_name_ = atom_name;
}
void TopologyAtom::SetExcludedAtoms (std::vector< std::string > excluded_atoms)
Definition at line 96 of file topologyatom.cc.
{
    excluded_atoms_.clear();
    for(vector<string>::iterator it = excluded_atoms.begin(); it != excluded_atoms.end(); it++)
    {
        excluded_atoms_.push_back(*it);
    }
}
void TopologyAtom::SetIndex (int index)
Definition at line 124 of file topologyatom.cc.
{
    index_ = index;
}
void TopologyAtom::SetNumberOfExcludedAtoms (int number_of_excluded_atoms)
Definition at line 116 of file topologyatom.cc.
{
    number_of_excluded_atoms_ = number_of_excluded_atoms;
}
void TopologyAtom::SetRadii (double radii)
Definition at line 104 of file topologyatom.cc.
{
    radii_ = radii;
}
void TopologyAtom::SetResidueName (std::string residue_name)
Definition at line 128 of file topologyatom.cc.
{
    residue_name_ = residue_name;
}
void TopologyAtom::SetScreen (double screen)
Definition at line 108 of file topologyatom.cc.
{
    screen_ = screen;
}
void TopologyAtom::SetTreeChainClasification (std::string tree_chain_classification)
Definition at line 112 of file topologyatom.cc.
{
    tree_chain_classification_ = tree_chain_classification;
}
void TopologyAtom::SetType (std::string type)
Definition at line 120 of file topologyatom.cc.
{
    type_ = type;
}
The documentation for this class was generated from the following files:
includes/FileSet/TopologyFileSpace/topologyatom.hpp
src/FileSet/TopologyFileSpace/topologyatom.cc