gmmlNew: TopologyFileSpace::TopologyAssembly Class Reference
TopologyFileSpace::TopologyAssembly Class Reference
#include <topologyassembly.hpp>
Public Types
typedef std::map< std::string,
TopologyResidue * > TopologyResidueMap
Public Member Functions
TopologyAssembly ()
std::string GetAssemblyName ()
TopologyResidueMap GetResidues ()
TopologyResidue * GetResidueByIndex (int index)
int GetAtomIndexByName (std::string atom_name)
void SetAssemblyName (std::string assembly_name)
void SetResidues (TopologyResidueMap residues)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 13 of file topologyassembly.hpp.
Member Typedef Documentation
typedef std::map<std::string, TopologyResidue*> TopologyFileSpace::TopologyAssembly::TopologyResidueMap
Definition at line 22 of file topologyassembly.hpp.
Constructor & Destructor Documentation
TopologyAssembly::TopologyAssembly ()
Definition at line 12 of file topologyassembly.cc.
{}
Member Function Documentation
string TopologyAssembly::GetAssemblyName ()
Definition at line 17 of file topologyassembly.cc.
{
    return assembly_name_;
}
int TopologyAssembly::GetAtomIndexByName (std::string atom_name)
Definition at line 35 of file topologyassembly.cc.
References TopologyFileSpace::TopologyAtom::GetAtomName(), TopologyFileSpace::TopologyResidue::GetAtoms(), and TopologyFileSpace::TopologyAtom::GetIndex().
{
    for(TopologyResidueMap::iterator it = residues_.begin(); it != residues_.end(); it++)
    {
        TopologyResidue* residue = (*it).second;
        TopologyResidue::TopologyAtomMap atom_map = residue->GetAtoms();
        for(TopologyResidue::TopologyAtomMap::iterator it1 = atom_map.begin(); it1 != atom_map.end(); it1++)
        {
            TopologyAtom* atom = (*it1).second;
            string name = atom->GetAtomName();
            if(name.compare(atom_name) == 0)
            {
                return atom->GetIndex();
            }
        }
    }
    return -1;
}
TopologyResidue * TopologyAssembly::GetResidueByIndex (int index)
Definition at line 25 of file topologyassembly.cc.
References TopologyFileSpace::TopologyResidue::GetIndex().
{
    for(TopologyResidueMap::iterator it = residues_.begin(); it != residues_.end(); it++)
    {
        TopologyResidue* residue = (*it).second;
        if(residue->GetIndex() == index)
            return residue;
    }
    return NULL;
}
TopologyAssembly::TopologyResidueMap TopologyAssembly::GetResidues ()
Definition at line 21 of file topologyassembly.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromTopologyCoordinateFile(), and MolecularModeling::Assembly::BuildAssemblyFromTopologyFile().
{
    return residues_;
}
void TopologyAssembly::Print (std::ostream & out = std::cout)
Definition at line 79 of file topologyassembly.cc.
References TopologyFileSpace::TopologyResidue::Print().
{
    out << "Assembly Name: " << assembly_name_ << endl;
    for(TopologyResidueMap::iterator it = residues_.begin(); it != residues_.end(); it++)
    {
        string residue_name = (*it).first;
        TopologyResidue* residue = (*it).second;
        out << "-------------------------- " << residue_name << " -------------------------" << endl;
        residue->Print(out);
    }
}
void TopologyAssembly::SetAssemblyName (std::string assembly_name)
Definition at line 57 of file topologyassembly.cc.
{
    assembly_name_ = assembly_name;
}
void TopologyAssembly::SetResidues (TopologyResidueMap residues)
Definition at line 61 of file topologyassembly.cc.
References TopologyFileSpace::TopologyResidue::GetResidueName().
{
    residues_.clear();
    for(TopologyResidueMap::iterator it = residues.begin(); it != residues.end(); it++)
    {
        TopologyResidue* residue = (*it).second;
        residues_[residue->GetResidueName()] = residue;
    }
}
The documentation for this class was generated from the following files:
includes/FileSet/TopologyFileSpace/topologyassembly.hpp
src/FileSet/TopologyFileSpace/topologyassembly.cc