gmmlNew: TopologyFileSpace::TopologyFile Class Reference
TopologyFileSpace::TopologyFile Class Reference
#include <topologyfile.hpp>
Public Types
typedef std::map< std::string,
TopologyAtomPair * > TopologyAtomPairMap
typedef std::map< int,
TopologyBondType * > TopologyBondTypeMap
typedef std::map< int,
TopologyAngleType * > TopologyAngleTypeMap
typedef std::map< int,
TopologyDihedralType * > TopologyDihedralTypeMap
typedef std::vector< std::string > RadiusSet
typedef std::map< std::string,
TopologyBond * > TopologyBondMap
typedef std::map< std::string,
TopologyAngle * > TopologyAngleMap
typedef std::map< std::string,
TopologyDihedral * > TopologyDihedralMap
typedef std::map< std::string,
int > TopologyAtomTypeIndexMap
Public Member Functions
TopologyFile ()
TopologyFile (const std::string &top_file)
std::string GetPath ()
std::string GetTitle ()
int GetNumberOfAtoms ()
int GetNumberOfTypes ()
int GetNumberOfBondsIncludingHydrogen ()
int GetNumberOfAnglesIncludingHydrogen ()
int GetNumberOfDihedralsIncludingHydrogen ()
int GetNumberOfBondsExcludingHydrogen ()
int GetNumberOfAnglesExcludingHydrogen ()
int GetNumberOfDihedralsExcludingHydrogen ()
int GetNumberOfHydrogenParameters ()
int GetNumberOfParameters ()
int GetNumberOfExcludedAtoms ()
int GetNumberOfResidues ()
int GetTotalNumberOfBonds ()
int GetTotalNumberOfAngles ()
int GetTotalNumberOfDihedrals ()
int GetNumberOfBondTypes ()
int GetNumberOfAnglesTypes ()
int GetNumberOfDihedralTypes ()
int GetNumberOfAtomTypesInParameterFile ()
int GetNumberOfDistinctHydrogenBonds ()
int GetPerturbationOption ()
int GetNumberOfBondsPerturbed ()
int GetNumberOfAnglesPerturbed ()
int GetNumberOfDihedralsPerturbed ()
int GetNumberOfBondsGroupPerturbed ()
int GetNumberOfAnglesGroupPerturbed ()
int GetNumberOfDihedralsGroupPerturbed ()
int GetStandardPeriodicBoxOption ()
int GetNumberOfAtomsInLargestResidue ()
int GetCapOption ()
int GetNumberOfExtraPoints ()
int GetNumberOfBeads ()
TopologyAtomPairMap GetPairs ()
TopologyBondTypeMap GetBondTypes ()
TopologyAngleTypeMap GetAngleTypes ()
TopologyDihedralTypeMap GetDihedralTypes ()
TopologyAssembly * GetAssembly ()
RadiusSet GetRadiusSet ()
TopologyBondMap GetBonds ()
TopologyAngleMap GetAngles ()
TopologyDihedralMap GetDihedrals ()
TopologyAtomTypeIndexMap GetAtomTypeIndexMap ()
TopologyBondType * GetBondTypeByIndex (int index)
TopologyAngleType * GetAngleTypeByIndex (int index)
TopologyDihedralType * GetDihedralTypeByIndex (int index)
TopologyAtomPair * GetAtomPairByIndex (int index)
void SetPath (std::string path)
void SetTitle (std::string title)
void SetNumberOfAtoms (int number_of_atoms)
void SetNumberOfTypes (int number_of_types)
void SetNumberOfBondsIncludingHydrogen (int number_of_bonds_including_hydrogen)
void SetNumberOfAnglesIncludingHydrogen (int number_of_angles_including_hydrogen)
void SetNumberOfDihedralsIncludingHydrogen (int number_of_dihedrals_including_hydrogen)
void SetNumberOfBondsExcludingHydrogen (int number_of_bonds_excluding_hydrogen)
void SetNumberOfAnglesExcludingHydrogen (int number_of_angles_excluding_hydrogen)
void SetNumberOfDihedralsExcludingHydrogen (int number_of_dihedrals_excluding_hydrogen)
void SetNumberOfHydrogenParameters (int number_of_hydrogen_parameters)
void SetNumberOfParameters (int number_of_parameters)
void SetNumberOfExcludedAtoms (int number_of_excluded_atoms)
void SetNumberOfResidues (int number_of_residues)
void SetTotalNumberOfBonds (int total_number_of_bonds)
void SetTotalNumberOfAngles (int total_number_of_angles)
void SetTotalNumberOfDihedrals (int total_number_of_dihedrals)
void SetNumberOfBondTypes (int number_of_bond_types)
void SetNumberOfAngleTypes (int number_of_angle_types)
void SetNumberOfDihedralTypes (int number_of_dihedral_types)
void SetNumberOfAtomTypesInParameterFile (int number_of_atom_types_in_parameter_file)
void SetNumberOfDistinctHydrogenBonds (int number_of_distinct_hydrogen_bonds)
void SetPerturbationOption (int perturbation_option)
void SetNumberOfBondsPerturbed (int number_of_bonds_perturbed)
void SetNumberOfAnglesPerturbed (int number_of_angles_perturbed)
void SetNumberOfDihedralsPerturbed (int number_of_dihedrals_perturbed)
void SetNumberOfBondsGroupPerturbed (int number_of_bonds_group_perturbed)
void SetNumberOfAnglesGroupPerturbed (int number_of_angles_group_perturbed)
void SetNumberOfDihedralsGroupPerturbed (int number_of_dihedrals_group_perturbed)
void SetStandardPeriodicBoxOption (int standard_periodic_box_option)
void SetNumberOfAtomsInLargestResidue (int number_of_atoms_in_largest_residue)
void SetCapOption (int cap_option)
void SetNumberOfExtraPoints (int number_of_extra_points)
void SetNumberOfBeads (int number_of_beads)
void SetAssembly (TopologyAssembly *assembly)
void SetRadiusSet (RadiusSet radius_set)
void SetBonds (TopologyBondMap bonds)
void AddBond (TopologyBond *bond)
void SetBondTypes (TopologyBondTypeMap bond_types)
void AddBondType (TopologyBondType *bond_type)
void SetAngles (TopologyAngleMap angles)
void AddAngle (TopologyAngle *angle)
void SetAngleTypes (TopologyAngleTypeMap angle_types)
void AddAngleType (TopologyAngleType *angle_type)
void SetDihedrals (TopologyDihedralMap dihedrals)
void AddDihedral (TopologyDihedral *dihedral)
void SetDihedralTypes (TopologyDihedralTypeMap dihedral_types)
void AddDihedralType (TopologyDihedralType *dihedral_type)
void SetAtomPairs (TopologyAtomPairMap pairs)
void AddAtomPair (TopologyAtomPair *pair)
void Read (std::ifstream &in_file)
void ParseSections (std::ifstream &in_stream)
void PartitionSection (std::ifstream &stream, std::string &line, std::stringstream &section)
void ParseTitlePartition (std::stringstream &stream)
void ParsePointersPartition (std::stringstream &stream)
template<typename T >
std::vector< T > ParsePartition (std::stringstream &stream)
template<typename T >
std::vector< T > PartitionLine (std::string line, std::string format)
void Write (const std::string &top_file)
void ResolveSections (std::ofstream &out_stream)
void ResolveTitleSection (std::ofstream &out)
void ResolvePointersSection (std::ofstream &out)
void ResolveAtomNameSection (std::ofstream &out)
void ResolveChargeSection (std::ofstream &out)
void ResolveAtomicNumberSection (std::ofstream &out)
void ResolveMassSection (std::ofstream &out)
void ResolveAtomTypeIndexSection (std::ofstream &out)
void ResolveNumberExcludedAtomsSection (std::ofstream &out)
void ResolveNonbondedParmIndexSection (std::ofstream &out)
void ResolveResidueLabelSection (std::ofstream &out)
void ResolveResiduePointersSection (std::ofstream &out)
void ResolveBondForceConstantSection (std::ofstream &out)
void ResolveBondEquilValueSection (std::ofstream &out)
void ResolveAngleForceConstantSection (std::ofstream &out)
void ResolveAngleEquilValueSection (std::ofstream &out)
void ResolveDihedralForceConstantSection (std::ofstream &out)
void ResolveDihedralPeriodicitySection (std::ofstream &out)
void ResolveDihedralPhaseSection (std::ofstream &out)
void ResolveSceeScaleFactorSection (std::ofstream &out)
void ResolveScnbScaleFactorSection (std::ofstream &out)
void ResolveSoltySection (std::ofstream &out)
void ResolveLennardJonesACoefSection (std::ofstream &out)
void ResolveLennardJonesBCoefSection (std::ofstream &out)
void ResolveBondsIncHydrogenSection (std::ofstream &out)
void ResolveBondsWithoutHydrogenSection (std::ofstream &out)
void ResolveAnglesIncHydrogenSection (std::ofstream &out)
void ResolveAnglesWithoutHydrogenSection (std::ofstream &out)
void ResolveDihedralsIncHydrogenSection (std::ofstream &out)
void ResolveDihedralsWithoutHydrogenSection (std::ofstream &out)
void ResolveExcludedAtomsListSection (std::ofstream &out)
void ResolveHydrogenBondACoefSection (std::ofstream &out)
void ResolveHydrogenBondBCoefSection (std::ofstream &out)
void ResolveHBCutSection (std::ofstream &out)
void ResolveAmberAtomTypeSection (std::ofstream &out)
void ResolveTreeChainClassificationSection (std::ofstream &out)
void ResolveJoinArraySection (std::ofstream &out)
void ResolveIRotatSection (std::ofstream &out)
void ResolveRadiusSetSection (std::ofstream &out)
void ResolveRadiiSection (std::ofstream &out)
void ResolveScreenSection (std::ofstream &out)
void Print (std::ostream &out=std::cout)
template<typename T >
vector< T > ParsePartition (stringstream &stream)
template<typename T >
vector< T > PartitionLine (string line, string format)
Detailed Description
Definition at line 19 of file topologyfile.hpp.
Member Typedef Documentation
typedef std::vector<std::string> TopologyFileSpace::TopologyFile::RadiusSet
Definition at line 29 of file topologyfile.hpp.
typedef std::map<std::string, TopologyAngle*> TopologyFileSpace::TopologyFile::TopologyAngleMap
Definition at line 31 of file topologyfile.hpp.
typedef std::map<int, TopologyAngleType*> TopologyFileSpace::TopologyFile::TopologyAngleTypeMap
Definition at line 27 of file topologyfile.hpp.
typedef std::map<std::string, TopologyAtomPair*> TopologyFileSpace::TopologyFile::TopologyAtomPairMap
Definition at line 25 of file topologyfile.hpp.
typedef std::map<std::string, int> TopologyFileSpace::TopologyFile::TopologyAtomTypeIndexMap
Definition at line 33 of file topologyfile.hpp.
typedef std::map<std::string, TopologyBond*> TopologyFileSpace::TopologyFile::TopologyBondMap
Definition at line 30 of file topologyfile.hpp.
typedef std::map<int, TopologyBondType*> TopologyFileSpace::TopologyFile::TopologyBondTypeMap
Definition at line 26 of file topologyfile.hpp.
typedef std::map<std::string, TopologyDihedral*> TopologyFileSpace::TopologyFile::TopologyDihedralMap
Definition at line 32 of file topologyfile.hpp.
typedef std::map<int, TopologyDihedralType*> TopologyFileSpace::TopologyFile::TopologyDihedralTypeMap
Definition at line 28 of file topologyfile.hpp.
Constructor & Destructor Documentation
TopologyFile::TopologyFile ()
Definition at line 28 of file topologyfile.cc.
References gmml::iNotSet.
{
    title_ = "";
    path_ = "";
    number_of_atoms_ = iNotSet;
    number_of_types_ = iNotSet;
    number_of_bonds_including_hydrogen_ = iNotSet;
    number_of_angles_including_hydrogen_ = iNotSet;
    number_of_dihedrals_including_hydrogen_ = iNotSet;
    number_of_bonds_excluding_hydrogen_ = iNotSet;
    number_of_angles_excluding_hydrogen_ = iNotSet;
    number_of_dihedrals_excluding_hydrogen_ = iNotSet;
    number_of_hydrogen_parameters_ = iNotSet;
    number_of_parameters_ = iNotSet;
    number_of_excluded_atoms_ = iNotSet;
    number_of_residues_ = iNotSet;
    total_number_of_bonds_ = iNotSet;
    total_number_of_angles_ = iNotSet;
    total_number_of_dihedrals_ = iNotSet;
    number_of_bond_types_ = iNotSet;
    number_of_angle_types_ = iNotSet;
    number_of_dihedral_types_ = iNotSet;
    number_of_atom_types_in_parameter_file_ = iNotSet;
    number_of_distinct_hydrogen_bonds_ = iNotSet;
    perturbation_option_ = iNotSet;
    number_of_bonds_perturbed_ = iNotSet;
    number_of_angles_perturbed_ = iNotSet;
    number_of_dihedrals_perturbed_ = iNotSet;
    number_of_bonds_group_perturbed_ = iNotSet;
    number_of_angles_group_perturbed_ = iNotSet;
    number_of_dihedrals_group_perturbed_ = iNotSet;
    standard_periodic_box_option_ = iNotSet;
    number_of_atoms_in_largest_residue_ = iNotSet;
    cap_option_ = iNotSet;
    number_of_extra_points_ = iNotSet;
    number_of_beads_ = iNotSet;
    pairs_ = TopologyAtomPairMap();
    bond_types_ = TopologyBondTypeMap();
    angle_types_ = TopologyAngleTypeMap();
    dihedral_types_ = TopologyDihedralTypeMap();
    assembly_ = new TopologyAssembly();
    radius_set_ = RadiusSet();
    bonds_ = TopologyBondMap();
    angles_ = TopologyAngleMap();
    dihedrals_ = TopologyDihedralMap();
}
TopologyFileSpace::TopologyFile::TopologyFile (const std::string & top_file)
Member Function Documentation
void TopologyFile::AddAngle (TopologyAngle * angle)
Definition at line 525 of file topologyfile.cc.
References TopologyFileSpace::TopologyAngle::GetAngles(), TopologyFileSpace::TopologyAngle::GetAngleType(), and TopologyFileSpace::TopologyAngle::GetResidueNames().
Referenced by MolecularModeling::Assembly::ExtractTopologyAnglesFromAssembly().
{
    vector<string> angles = angle->GetAngles();
    vector<string> residue_names = angle->GetResidueNames();
    TopologyAngleType* angle_type = angle->GetAngleType();
    stringstream ss;
    ss << residue_names.at(0) << ":" << angles.at(0) << "-" << residue_names.at(1) << ":" << angles.at(1) << "-" << residue_names.at(2) << ":" << angles.at(2) << "_" << angle_type;
    angles_[ss.str()] = angle;
}
void TopologyFile::AddAngleType (TopologyAngleType * angle_type)
Definition at line 544 of file topologyfile.cc.
References TopologyFileSpace::TopologyAngleType::GetIndex().
Referenced by MolecularModeling::Assembly::ExtractTopologyAngleTypesFromAssembly().
{
    int index = angle_type->GetIndex();
    angle_types_[index] = angle_type;
}
void TopologyFile::AddAtomPair (TopologyAtomPair * pair)
Definition at line 594 of file topologyfile.cc.
References TopologyFileSpace::TopologyAtomPair::GetPairType().
{
    string atom_pair_types = pair->GetPairType();
    pairs_[atom_pair_types] = pair;
}
void TopologyFile::AddBond (TopologyBond * bond)
Definition at line 491 of file topologyfile.cc.
References TopologyFileSpace::TopologyBond::GetBonds(), TopologyFileSpace::TopologyBond::GetBondType(), and TopologyFileSpace::TopologyBond::GetResidueNames().
Referenced by MolecularModeling::Assembly::ExtractTopologyBondsFromAssembly().
{
    vector<string> bonds = bond->GetBonds();
    vector<string> residue_names = bond->GetResidueNames();
    TopologyBondType* bond_type = bond->GetBondType();
    stringstream ss;
    ss << residue_names.at(0) << ":" << bonds.at(0) << "-" << residue_names.at(1) << ":" << bonds.at(1) << "_" << bond_type;
    bonds_[ss.str()] = bond;
}
void TopologyFile::AddBondType (TopologyBondType * bond_type)
Definition at line 510 of file topologyfile.cc.
References TopologyFileSpace::TopologyBondType::GetIndex().
Referenced by MolecularModeling::Assembly::ExtractTopologyBondTypesFromAssembly().
{
    int index = bond_type->GetIndex();
    bond_types_[index] = bond_type;
}
void TopologyFile::AddDihedral (TopologyDihedral * dihedral)
Definition at line 559 of file topologyfile.cc.
References TopologyFileSpace::TopologyDihedral::GetDihedrals(), TopologyFileSpace::TopologyDihedral::GetDihedralType(), and TopologyFileSpace::TopologyDihedral::GetResidueNames().
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralsFromAssembly().
{
    vector<string> dihedrals = dihedral->GetDihedrals();
    vector<string> residue_names = dihedral->GetResidueNames();
    TopologyDihedralType* dihedral_type = dihedral->GetDihedralType();
    stringstream ss;
    ss << residue_names.at(0) << ":" << dihedrals.at(0) << "-" << residue_names.at(1) << ":" << dihedrals.at(1) << "-"
       << residue_names.at(2) << ":" << dihedrals.at(2) << "-" << residue_names.at(3) << ":" << dihedrals.at(3) << "_" << dihedral_type;
    dihedrals_[ss.str()] = dihedral;
}
void TopologyFile::AddDihedralType (TopologyDihedralType * dihedral_type)
Definition at line 579 of file topologyfile.cc.
References TopologyFileSpace::TopologyDihedralType::GetIndex().
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralTypesFromAssembly().
{
    int index = dihedral_type->GetIndex();
    dihedral_types_[index] = dihedral_type;
}
TopologyFile::TopologyAngleMap TopologyFile::GetAngles ()
Definition at line 257 of file topologyfile.cc.
{
    return angles_;
}
TopologyAngleType * TopologyFile::GetAngleTypeByIndex (int index)
Definition at line 296 of file topologyfile.cc.
References TopologyFileSpace::TopologyAngleType::GetIndex().
Referenced by MolecularModeling::Assembly::ExtractTopologyAnglesFromAssembly().
{
    for(TopologyAngleTypeMap::iterator it = angle_types_.begin(); it != angle_types_.end(); it++)
    {
        TopologyAngleType* angle_type = (*it).second;
        if(angle_type->GetIndex() == index)
            return angle_type;
    }
    return NULL;
}
TopologyFile::TopologyAngleTypeMap TopologyFile::GetAngleTypes ()
Definition at line 236 of file topologyfile.cc.
{
    return angle_types_;
}
TopologyAssembly * TopologyFile::GetAssembly ()
Definition at line 244 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromTopologyCoordinateFile(), and MolecularModeling::Assembly::BuildAssemblyFromTopologyFile().
{
    return assembly_;
}
TopologyAtomPair * TopologyFile::GetAtomPairByIndex (int index)
Definition at line 318 of file topologyfile.cc.
References TopologyFileSpace::TopologyAtomPair::GetIndex().
{
    for(TopologyAtomPairMap::iterator it = pairs_.begin(); it != pairs_.end(); it++)
    {
        TopologyAtomPair* atom_pair = (*it).second;
        if(atom_pair->GetIndex() == index)
            return atom_pair;
    }
    return NULL;
}
TopologyFile::TopologyAtomTypeIndexMap TopologyFile::GetAtomTypeIndexMap ()
Definition at line 265 of file topologyfile.cc.
References TopologyFileSpace::TopologyResidue::GetAtomByIndex(), TopologyFileSpace::TopologyResidue::GetAtoms(), and TopologyFileSpace::TopologyAtom::GetType().
{
    TopologyAtomTypeIndexMap atom_type_index_map;
    int index = 0;
    int count = 1;
    for(int i = 0; i < number_of_residues_; i++)
    {
        TopologyResidue* residue = this->assembly_->GetResidueByIndex(i+1);
        for(unsigned int j = 0; j < residue->GetAtoms().size(); j++)
        {
            TopologyAtom* atom = residue->GetAtomByIndex(index+1);
            index++;
            if(atom_type_index_map[atom->GetType()] == 0)
            {
                atom_type_index_map[atom->GetType()] = count;
                count++;
            }
        }
    }
    return atom_type_index_map;
}
TopologyFile::TopologyBondMap TopologyFile::GetBonds ()
Definition at line 253 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildStructureByTOPFileInformation().
{
    return bonds_;
}
TopologyBondType * TopologyFile::GetBondTypeByIndex (int index)
Definition at line 286 of file topologyfile.cc.
References TopologyFileSpace::TopologyBondType::GetIndex().
Referenced by MolecularModeling::Assembly::ExtractTopologyBondsFromAssembly().
{
    for(TopologyBondTypeMap::iterator it = bond_types_.begin(); it != bond_types_.end(); it++)
    {
        TopologyBondType* bond_type = (*it).second;
        if(bond_type->GetIndex() == index)
            return bond_type;
    }
    return NULL;
}
TopologyFile::TopologyBondTypeMap TopologyFile::GetBondTypes ()
Definition at line 232 of file topologyfile.cc.
{
    return bond_types_;
}
int TopologyFile::GetCapOption ()
Definition at line 216 of file topologyfile.cc.
{
    return cap_option_;
}
TopologyFile::TopologyDihedralMap TopologyFile::GetDihedrals ()
Definition at line 261 of file topologyfile.cc.
{
    return dihedrals_;
}
TopologyDihedralType * TopologyFile::GetDihedralTypeByIndex (int index)
Definition at line 306 of file topologyfile.cc.
References TopologyFileSpace::TopologyDihedralType::GetIndex().
Referenced by MolecularModeling::Assembly::ExtractTopologyDihedralsFromAssembly().
{
    for(TopologyDihedralTypeMap::iterator it = dihedral_types_.begin(); it != dihedral_types_.end(); it++)
    {
        TopologyDihedralType* dihedral_type = (*it).second;
        if(dihedral_type->GetIndex() == index)
        {
            return dihedral_type;
        }
    }
    return NULL;
}
TopologyFile::TopologyDihedralTypeMap TopologyFile::GetDihedralTypes ()
Definition at line 240 of file topologyfile.cc.
{
    return dihedral_types_;
}
int TopologyFile::GetNumberOfAnglesExcludingHydrogen ()
Definition at line 124 of file topologyfile.cc.
{
    return number_of_angles_excluding_hydrogen_;
}
int TopologyFile::GetNumberOfAnglesGroupPerturbed ()
Definition at line 200 of file topologyfile.cc.
{
    return number_of_angles_group_perturbed_;
}
int TopologyFile::GetNumberOfAnglesIncludingHydrogen ()
Definition at line 112 of file topologyfile.cc.
{
    return number_of_angles_including_hydrogen_;
}
int TopologyFile::GetNumberOfAnglesPerturbed ()
Definition at line 188 of file topologyfile.cc.
{
    return number_of_angles_perturbed_;
}
int TopologyFile::GetNumberOfAnglesTypes ()
Definition at line 164 of file topologyfile.cc.
{
    return number_of_angle_types_;
}
int TopologyFile::GetNumberOfAtoms ()
Definition at line 100 of file topologyfile.cc.
{
    return number_of_atoms_;
}
int TopologyFile::GetNumberOfAtomsInLargestResidue ()
Definition at line 212 of file topologyfile.cc.
{
    return number_of_atoms_in_largest_residue_;
}
int TopologyFile::GetNumberOfAtomTypesInParameterFile ()
Definition at line 172 of file topologyfile.cc.
{
    return number_of_atom_types_in_parameter_file_;
}
int TopologyFile::GetNumberOfBeads ()
Definition at line 224 of file topologyfile.cc.
{
    return number_of_beads_;
}
int TopologyFile::GetNumberOfBondsExcludingHydrogen ()
Definition at line 120 of file topologyfile.cc.
{
    return number_of_bonds_excluding_hydrogen_;
}
int TopologyFile::GetNumberOfBondsGroupPerturbed ()
Definition at line 196 of file topologyfile.cc.
{
    return number_of_bonds_group_perturbed_;
}
int TopologyFile::GetNumberOfBondsIncludingHydrogen ()
Definition at line 108 of file topologyfile.cc.
{
    return number_of_bonds_including_hydrogen_;
}
int TopologyFile::GetNumberOfBondsPerturbed ()
Definition at line 184 of file topologyfile.cc.
{
    return number_of_bonds_perturbed_;
}
int TopologyFile::GetNumberOfBondTypes ()
Definition at line 160 of file topologyfile.cc.
{
    return number_of_bond_types_;
}
int TopologyFile::GetNumberOfDihedralsExcludingHydrogen ()
Definition at line 128 of file topologyfile.cc.
{
    return number_of_dihedrals_excluding_hydrogen_;
}
int TopologyFile::GetNumberOfDihedralsGroupPerturbed ()
Definition at line 204 of file topologyfile.cc.
{
    return number_of_dihedrals_group_perturbed_;
}
int TopologyFile::GetNumberOfDihedralsIncludingHydrogen ()
Definition at line 116 of file topologyfile.cc.
{
    return number_of_dihedrals_including_hydrogen_;
}
int TopologyFile::GetNumberOfDihedralsPerturbed ()
Definition at line 192 of file topologyfile.cc.
{
    return number_of_dihedrals_perturbed_;
}
int TopologyFile::GetNumberOfDihedralTypes ()
Definition at line 168 of file topologyfile.cc.
{
    return number_of_dihedral_types_;
}
int TopologyFile::GetNumberOfDistinctHydrogenBonds ()
Definition at line 176 of file topologyfile.cc.
{
    return number_of_distinct_hydrogen_bonds_;
}
int TopologyFile::GetNumberOfExcludedAtoms ()
Definition at line 140 of file topologyfile.cc.
{
    return number_of_excluded_atoms_;
}
int TopologyFile::GetNumberOfExtraPoints ()
Definition at line 220 of file topologyfile.cc.
{
    return number_of_extra_points_;
}
int TopologyFile::GetNumberOfHydrogenParameters ()
Definition at line 132 of file topologyfile.cc.
{
    return number_of_hydrogen_parameters_;
}
int TopologyFile::GetNumberOfParameters ()
Definition at line 136 of file topologyfile.cc.
{
    return number_of_parameters_;
}
int TopologyFile::GetNumberOfResidues ()
Definition at line 144 of file topologyfile.cc.
{
    return number_of_residues_;
}
int TopologyFile::GetNumberOfTypes ()
Definition at line 104 of file topologyfile.cc.
{
    return number_of_types_;
}
TopologyFile::TopologyAtomPairMap TopologyFile::GetPairs ()
Definition at line 228 of file topologyfile.cc.
{
    return pairs_;
}
string TopologyFile::GetPath ()
Definition at line 92 of file topologyfile.cc.
{
    return path_;
}
int TopologyFile::GetPerturbationOption ()
Definition at line 180 of file topologyfile.cc.
{
    return perturbation_option_;
}
TopologyFile::RadiusSet TopologyFile::GetRadiusSet ()
Definition at line 249 of file topologyfile.cc.
{
    return radius_set_;
}
int TopologyFile::GetStandardPeriodicBoxOption ()
Definition at line 208 of file topologyfile.cc.
{
    return standard_periodic_box_option_;
}
string TopologyFile::GetTitle ()
Definition at line 96 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromTopologyCoordinateFile(), and MolecularModeling::Assembly::BuildAssemblyFromTopologyFile().
{
    return title_;
}
int TopologyFile::GetTotalNumberOfAngles ()
Definition at line 152 of file topologyfile.cc.
{
    return total_number_of_angles_;
}
int TopologyFile::GetTotalNumberOfBonds ()
Definition at line 148 of file topologyfile.cc.
{
    return total_number_of_bonds_;
}
int TopologyFile::GetTotalNumberOfDihedrals ()
Definition at line 156 of file topologyfile.cc.
{
    return total_number_of_dihedrals_;
}
template<typename T > std::vector<T> TopologyFileSpace::TopologyFile::ParsePartition (std::stringstream & stream)
template<typename T > vector<T> TopologyFileSpace::TopologyFile::ParsePartition (stringstream & stream)
Definition at line 1608 of file topologyfile.cc.
{
    string line;
    vector<T> section = vector<T>();
    getline(stream, line);
    string format;
    while(!line.empty())
    {
        if(line[0] == '%')
        {
            if(line.find("%FORMAT") != string::npos)
            {
                format = line.substr(line.find_first_of('(', 0) + 1, line.find_last_of(')', line.length()) - line.find_first_of('(', 0) - 1);
            }
        }
        else
        {
            vector<T> line_items = PartitionLine<T>(line, format);
            for(typename vector<T>::iterator it = line_items.begin(); it != line_items.end(); it++)
            {
                section.push_back(*it);
            }
        }
        getline(stream, line);
    }
    return section;
}
void TopologyFile::ParsePointersPartition (std::stringstream & stream)
Definition at line 1544 of file topologyfile.cc.
{
    string line;
    vector<int> items = vector<int>();
    // Section Header
    getline(stream, line);
    // Section Format
    getline(stream, line);
    while(!line.empty())
    {
        string format = "10I8";
        if(line[0] == '%')
        {
            if(line.find("%FORMAT") != string::npos)
            {
                format = line.substr(line.find_first_of('(', 0) + 1, line.find_last_of(')', line.length()) - line.find_first_of('(', 0) - 1);
            }
        }
        else
        {
            vector<int> line_items = PartitionLine<int>(line, format);
            for(vector<int>::iterator it = line_items.begin(); it != line_items.end(); it++)
            {
                items.push_back(*it);
            }
        }
        getline(stream, line);
    }
    number_of_atoms_ = items.at(0);
    number_of_types_ = items.at(1);
    number_of_bonds_including_hydrogen_ = items.at(2);
    number_of_bonds_excluding_hydrogen_ = items.at(3);
    number_of_angles_including_hydrogen_ = items.at(4);
    number_of_angles_excluding_hydrogen_ = items.at(5);
    number_of_dihedrals_including_hydrogen_ = items.at(6);
    number_of_dihedrals_excluding_hydrogen_ = items.at(7);
    number_of_hydrogen_parameters_ = items.at(8);
    number_of_parameters_ = items.at(9);
    number_of_excluded_atoms_ = items.at(10);
    number_of_residues_ = items.at(11);
    total_number_of_bonds_ = items.at(12);
    total_number_of_angles_ = items.at(13);
    total_number_of_dihedrals_ = items.at(14);
    number_of_bond_types_ = items.at(15);
    number_of_angle_types_ = items.at(16);
    number_of_dihedral_types_ = items.at(17);
    number_of_atom_types_in_parameter_file_ = items.at(18);
    number_of_distinct_hydrogen_bonds_ = items.at(19);
    perturbation_option_ = items.at(20);
    number_of_bonds_perturbed_ = items.at(21);
    number_of_angles_perturbed_ = items.at(22);
    number_of_dihedrals_perturbed_ = items.at(23);
    number_of_bonds_group_perturbed_ = items.at(24);
    number_of_angles_group_perturbed_ = items.at(25);
    number_of_dihedrals_group_perturbed_ = items.at(26);
    standard_periodic_box_option_ = items.at(27);
    number_of_atoms_in_largest_residue_ = items.at(28);
    cap_option_ = items.at(29);
    number_of_extra_points_ = items.at(30);
    if(items.size() >= 31)
        number_of_beads_ = items.at(30);
}
void TopologyFile::ParseSections (std::ifstream & in_stream)
Unable to read file
Definition at line 608 of file topologyfile.cc.
References TopologyFileSpace::TopologyAngle::GetAngleType(), TopologyFileSpace::TopologyBond::GetBondType(), TopologyFileSpace::TopologyDihedral::GetDihedralType(), TopologyFileSpace::TopologyDihedral::GetIgnoredGroupInteraction(), TopologyFileSpace::TopologyDihedral::GetIsImproper(), TopologyFileSpace::TopologyAngle::SetAnlgeType(), TopologyFileSpace::TopologyBond::SetBondType(), TopologyFileSpace::TopologyDihedral::SetDihedralType(), TopologyFileSpace::TopologyDihedral::SetIgnoredGroupInteraction(), TopologyFileSpace::TopologyBond::SetIncludingHydrogen(), TopologyFileSpace::TopologyAngle::SetIncludingHydrogen(), TopologyFileSpace::TopologyDihedral::SetIncludingHydrogen(), and TopologyFileSpace::TopologyDihedral::SetIsImproper().
{
    string line;
    /// Unable to read file
    if (!getline(in_stream, line))
    {
        throw TopologyFileProcessingException("Error reading file");
    }
    stringstream other;
    vector<string> atom_names = vector<string>();
    vector<double> charges = vector<double>();
    vector<int> atomic_numbers = vector<int>();
    vector<double> masses = vector<double>();
    vector<int> atom_type_indexes = vector<int>();
    vector<int> number_excluded_atoms = vector<int>();
    vector<int> nonbonded_parm_indexes = vector<int>();
    vector<string> residue_labels = vector<string>();
    vector<int> residue_pointers = vector<int>();
    vector<double> bond_force_constants = vector<double>();
    vector<double> bond_equil_values = vector<double>();
    vector<double> angle_force_constants = vector<double>();
    vector<double> angle_equil_values = vector<double>();
    vector<double> dihedral_force_constants = vector<double>();
    vector<double> dihedral_periodicities = vector<double>();
    vector<double> dihedral_phases = vector<double>();
    vector<double> scee_scale_factors = vector<double>();
    vector<double> scnb_scale_factors = vector<double>();
    vector<double> lennard_jones_acoefs = vector<double>();
    vector<double> lennard_jones_bcoefs = vector<double>();
    vector<int> bonds_inc_hydrogens = vector<int>();
    vector<int> bonds_without_hydrogens = vector<int>();
    vector<int> angles_inc_hydrogens = vector<int>();
    vector<int> angles_without_hydrogens = vector<int>();
    vector<int> dihedrals_inc_hydrogens = vector<int>();
    vector<int> dihedrals_without_hydrogens = vector<int>();
    vector<int> excluded_atoms_lists = vector<int>();
    vector<double> hbond_acoefs = vector<double>();
    vector<double> hbond_bcoefs = vector<double>();
    vector<double> hb_cuts = vector<double>();
    vector<string> amber_atom_types = vector<string>();
    vector<string> tree_chain_classifications = vector<string>();
    vector<string> radius_sets = vector<string>();
    vector<double> radiis = vector<double>();
    vector<double> screens = vector<double>();
    vector<int> ipols = vector<int>();
    while(!line.empty())
    {
        if(line.find("%FLAG") != string::npos)
        {
            stringstream section;
            PartitionSection(in_stream, line, section);
            string in_line;
            //            cout << section.str() << endl;
            getline(section, in_line);
            if(in_line.find("%FLAG TITLE") != string::npos)
            {
                ParseTitlePartition(section);
            }
            else if(in_line.find("%FLAG POINTERS") != string::npos)
            {
                ParsePointersPartition(section);
            }
            else if(in_line.find("%FLAG ATOM_NAME") != string::npos)
            {
                atom_names = ParsePartition<string>(section);
            }
            else if(in_line.find("%FLAG CHARGE") != string::npos)
            {
                charges = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG ATOMIC_NUMBER") != string::npos)
            {
                atomic_numbers = ParsePartition<int>(section);
            }
            else if(in_line.find("%FLAG MASS") != string::npos)
            {
                masses = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG ATOM_TYPE_INDEX") != string::npos)
            {
                atom_type_indexes = ParsePartition<int>(section);
            }
            else if(in_line.find("%FLAG NUMBER_EXCLUDED_ATOMS") != string::npos)
            {
                number_excluded_atoms =ParsePartition<int>(section);
            }
            else if(in_line.find("%FLAG NONBONDED_PARM_INDEX") != string::npos)
            {
                nonbonded_parm_indexes = ParsePartition<int>(section);
            }
            else if(in_line.find("%FLAG RESIDUE_LABEL") != string::npos)
            {
                residue_labels = ParsePartition<string>(section);
            }
            else if(in_line.find("%FLAG RESIDUE_POINTER") != string::npos)
            {
                residue_pointers = ParsePartition<int>(section);
            }
            else if(in_line.find("%FLAG BOND_FORCE_CONSTANT") != string::npos)
            {
                bond_force_constants = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG BOND_EQUIL_VALUE") != string::npos)
            {
                bond_equil_values = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG ANGLE_FORCE_CONSTANT") != string::npos)
            {
                angle_force_constants = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG ANGLE_EQUIL_VALUE") != string::npos)
            {
                angle_equil_values = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG DIHEDRAL_FORCE_CONSTANT") != string::npos)
            {
                dihedral_force_constants = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG DIHEDRAL_PERIODICITY") != string::npos)
            {
                dihedral_periodicities = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG DIHEDRAL_PHASE") != string::npos)
            {
                dihedral_phases = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG SCEE_SCALE_FACTOR") != string::npos)
            {
                scee_scale_factors = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG SCNB_SCALE_FACTOR") != string::npos)
            {
                scnb_scale_factors = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG SOLTY") != string::npos)
            {
            }
            else if(in_line.find("%FLAG LENNARD_JONES_ACOEF") != string::npos)
            {
                lennard_jones_acoefs = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG LENNARD_JONES_BCOEF") != string::npos)
            {
                lennard_jones_bcoefs = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG BONDS_INC_HYDROGEN") != string::npos)
            {
                bonds_inc_hydrogens = ParsePartition<int>(section);
            }
            else if(in_line.find("%FLAG BONDS_WITHOUT_HYDROGEN") != string::npos)
            {
                bonds_without_hydrogens = ParsePartition<int>(section);
            }
            else if(in_line.find("%FLAG ANGLES_INC_HYDROGEN") != string::npos)
            {
                angles_inc_hydrogens = ParsePartition<int>(section);
            }
            else if(in_line.find("%FLAG ANGLES_WITHOUT_HYDROGEN") != string::npos)
            {
                angles_without_hydrogens = ParsePartition<int>(section);
            }
            else if(in_line.find("%FLAG DIHEDRALS_INC_HYDROGEN") != string::npos)
            {
                dihedrals_inc_hydrogens = ParsePartition<int>(section);
            }
            else if(in_line.find("%FLAG DIHEDRALS_WITHOUT_HYDROGEN") != string::npos)
            {
                dihedrals_without_hydrogens = ParsePartition<int>(section);
            }
            else if(in_line.find("%FLAG EXCLUDED_ATOMS_LIST") != string::npos)
            {
                excluded_atoms_lists = ParsePartition<int>(section);
            }
            else if(in_line.find("%FLAG HBOND_ACOEF") != string::npos)
            {
                hbond_acoefs = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG HBOND_BCOEF") != string::npos)
            {
                hbond_bcoefs = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG HBCUT") != string::npos)
            {
                hb_cuts = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG AMBER_ATOM_TYPE") != string::npos)
            {
                amber_atom_types = ParsePartition<string>(section);
            }
            else if(in_line.find("%FLAG TREE_CHAIN_CLASSIFICATION") != string::npos)
            {
                tree_chain_classifications = ParsePartition<string>(section);
            }
            else if(in_line.find("%FLAG JOIN_ARRAY") != string::npos)
            {
            }
            else if(in_line.find("%FLAG IROTAT") != string::npos)
            {
            }
            else if(in_line.find("%FLAG RADIUS_SET") != string::npos)
            {
                radius_sets = ParsePartition<string>(section);
            }
            else if(in_line.find("%FLAG RADII") != string::npos)
            {
                radiis = ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG SCREEN") != string::npos)
            {
                screens= ParsePartition<double>(section);
            }
            else if(in_line.find("%FLAG SOLVENT_POINTERS") != string::npos)
            {
            }
            else if(in_line.find("%FLAG ATOMS_PER_MOLECULE") != string::npos)
            {
            }
            else if(in_line.find("%FLAG BOX_DIMENSIONS") != string::npos)
            {
            }
            else if(in_line.find("%FLAG CAP_INFO") != string::npos)
            {
            }
            else if(in_line.find("%FLAG CAP_INFO2") != string::npos)
            {
            }
            else if(in_line.find("%FLAG SOLVENT_POINTERS") != string::npos)
            {
            }
            else if(in_line.find("%FLAG IPOL") != string::npos)
            {
                ipols = ParsePartition<int>(section);
            }
            else
            {
                // Ignore section
            }
        }
        else
        {
            other << line << endl;
            getline(in_stream, line);
        }
    }
    // Bond types
    for(int i = 0; i < number_of_bond_types_; i++)
    {
        bond_types_[i] = new TopologyBondType(i, bond_force_constants.at(i), bond_equil_values.at(i));
    }
    // Angle types
    for(int i = 0; i < number_of_angle_types_; i++)
    {
        angle_types_[i] = new TopologyAngleType(i, angle_force_constants.at(i), angle_equil_values.at(i));
    }
    // Dihedral types
    for(int i = 0; i < number_of_dihedral_types_; i++)
    {
        dihedral_types_[i] = new TopologyDihedralType(i, dihedral_force_constants.at(i), dihedral_periodicities.at(i), dihedral_phases.at(i),
                                                      scee_scale_factors.at(i), scnb_scale_factors.at(i));
    }
    // Radius set
    for(RadiusSet::iterator it = radius_sets.begin(); it != radius_sets.end(); it++)
    {
        radius_set_.push_back(*it);
    }
    // Lennard Jones coefficients for atom pairs
    for(int i = 0; i < number_of_atoms_; i++)
    {
        string atom_type_1 = amber_atom_types.at(i);
        for(int j = 0; j < number_of_atoms_; j++)
        {
            string atom_type_2 = amber_atom_types.at(j);
            double coefficient_a;
            double coefficient_b;
            int index = nonbonded_parm_indexes.at(number_of_types_ * (atom_type_indexes.at(i) - 1) + atom_type_indexes.at(j) - 1);
            if(index > 0)
            {
                coefficient_a = lennard_jones_acoefs.at(index - 1);
                coefficient_b = lennard_jones_bcoefs.at(index - 1);
            }
            else
            {
                coefficient_a = hbond_acoefs.at(index - 1);
                coefficient_b = hbond_bcoefs.at(index - 1);
            }
            if(pairs_.find(atom_type_1 + "-" + atom_type_2) != pairs_.end()|| pairs_.find(atom_type_2 + "-" + atom_type_1) != pairs_.end())
            {
            }
            else
            {
                pairs_[atom_type_1 + "-" + atom_type_2] = new TopologyAtomPair(atom_type_1 + "-" + atom_type_2, coefficient_a, coefficient_b, index);
//                cout << atom_type_1 + "-" + atom_type_2 << ":" << index << endl;
            }
        }
    }
    // Bonds, Angles, Dihedrals
    //Bonds in topology file
    for(int i = 0; i < number_of_bonds_including_hydrogen_; i++)
    {
        vector<string> bonds = vector<string>();
        vector<string> bond_atoms_residue_names = vector<string>();
        int first_atom_index = (bonds_inc_hydrogens[i*3])/3;
        int second_atom_index = (bonds_inc_hydrogens[i*3+1])/3;
        bonds.push_back(atom_names[first_atom_index]);
        bonds.push_back(atom_names[second_atom_index]);
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(first_atom_index >= start_index && first_atom_index < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                bond_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(second_atom_index >= start_index && second_atom_index < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                bond_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        TopologyBond* topology_bond = new TopologyBond(bonds, bond_atoms_residue_names);
        topology_bond->SetBondType(bond_types_[bonds_inc_hydrogens[i*3+2] - 1]);
        topology_bond->SetIncludingHydrogen(true);
        stringstream key;
        key << bond_atoms_residue_names.at(0) << ":" << bonds.at(0) << "-" << bond_atoms_residue_names.at(1) << ":" << bonds.at(1) << "_" << topology_bond->GetBondType();
        bonds_[key.str()] = topology_bond;
    }
    for(int i = 0; i < number_of_bonds_excluding_hydrogen_; i++)
    {
        vector<string> bonds = vector<string>();
        vector<string> bond_atoms_residue_names = vector<string>();
        int first_atom_index = (bonds_without_hydrogens[i*3])/3;
        int second_atom_index = (bonds_without_hydrogens[i*3+1])/3;
        bonds.push_back(atom_names[first_atom_index]);
        bonds.push_back(atom_names[second_atom_index]);
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j <number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(first_atom_index >= start_index && first_atom_index < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                bond_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        for(int j = 0; j < number_of_residues_; j++)
        {
            int end_index;
            int start_index = residue_pointers.at(j) - 1;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(second_atom_index >= start_index && second_atom_index < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                bond_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        TopologyBond* topology_bond = new TopologyBond(bonds, bond_atoms_residue_names);
        topology_bond->SetBondType(bond_types_[bonds_without_hydrogens[i*3+2] - 1]);
        topology_bond->SetIncludingHydrogen(false);
        stringstream key;
        key << bond_atoms_residue_names.at(0) << ":" << bonds.at(0) << "-" << bond_atoms_residue_names.at(1) << ":" << bonds.at(1) << "_" << topology_bond->GetBondType();
        bonds_[key.str()] = topology_bond;
    }
    // Angles in topology file
    // Angles including hydrogen
    for(int i = 0; i < number_of_angles_including_hydrogen_; i++)
    {
        vector<string> angle_atoms = vector<string>();
        vector<string> angle_atoms_residue_names = vector<string>();
        int atom_index_1 = angles_inc_hydrogens.at(i*4) / 3;
        int atom_index_2 = angles_inc_hydrogens.at(i*4+1) / 3;
        int atom_index_3 = angles_inc_hydrogens.at(i*4+2) / 3;
        angle_atoms.push_back(atom_names.at(atom_index_1));
        angle_atoms.push_back(atom_names.at(atom_index_2));
        angle_atoms.push_back(atom_names.at(atom_index_3));
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(atom_index_1 >= start_index && atom_index_1 < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                angle_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(atom_index_2 >= start_index && atom_index_2 < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                angle_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(atom_index_3 >= start_index && atom_index_3 < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                angle_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        TopologyAngle* angle = new TopologyAngle(angle_atoms, angle_atoms_residue_names);
        angle->SetIncludingHydrogen(true);
        angle->SetAnlgeType(angle_types_[angles_inc_hydrogens.at(i*4+3) - 1]);
        stringstream key;
        key << angle_atoms_residue_names.at(0) << ":" << angle_atoms.at(0) << "-" << angle_atoms_residue_names.at(1) << ":" << angle_atoms.at(1) << "-"
            << angle_atoms_residue_names.at(2) << ":" << angle_atoms.at(2) << "_" << angle->GetAngleType();
        angles_[key.str()] = angle;
    }
    // Angles excluding hydrogen
    for(int i = 0; i < number_of_angles_excluding_hydrogen_; i++)
    {
        vector<string> angle_atoms = vector<string>();
        vector<string> angle_atoms_residue_names = vector<string>();
        int atom_index_1 = angles_without_hydrogens.at(i*4) / 3;
        int atom_index_2 = angles_without_hydrogens.at(i*4+1) / 3;
        int atom_index_3 = angles_without_hydrogens.at(i*4+2) / 3;
        angle_atoms.push_back(atom_names.at(atom_index_1));
        angle_atoms.push_back(atom_names.at(atom_index_2));
        angle_atoms.push_back(atom_names.at(atom_index_3));
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(atom_index_1 >= start_index && atom_index_1 < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                angle_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(atom_index_2 >= start_index && atom_index_2 < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                angle_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        for(int j = 0; j < number_of_residues_; j++)
        {
            int end_index;
            int start_index = residue_pointers.at(j) - 1;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(atom_index_3 >= start_index && atom_index_3 < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                angle_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        TopologyAngle* angle = new TopologyAngle(angle_atoms, angle_atoms_residue_names);
        angle->SetIncludingHydrogen(false);
        angle->SetAnlgeType(angle_types_[angles_without_hydrogens.at(i*4+3) - 1]);
        stringstream key;
        key << angle_atoms_residue_names.at(0) << ":" << angle_atoms.at(0) << "-" << angle_atoms_residue_names.at(1) << ":" << angle_atoms.at(1) << "-"
            << angle_atoms_residue_names.at(2) << ":" << angle_atoms.at(2) << "_" << angle->GetAngleType();
        angles_[key.str()] = angle;
    }
    // Dihedrals in topology file
    // Dihedrals including hydrogen
    for(int i = 0; i < number_of_dihedrals_including_hydrogen_; i++)
    {
        vector<string> dihedral_atoms = vector<string>();
        vector<string> dihedral_atoms_residue_names = vector<string>();
        int atom_index_1 = abs(dihedrals_inc_hydrogens.at(i*5)) / 3;
        int atom_index_2 = abs(dihedrals_inc_hydrogens.at(i*5+1)) / 3;
        int atom_index_3 = abs(dihedrals_inc_hydrogens.at(i*5+2)) / 3;
        int atom_index_4 = abs(dihedrals_inc_hydrogens.at(i*5+3)) / 3;
        dihedral_atoms.push_back(atom_names.at(atom_index_1));
        dihedral_atoms.push_back(atom_names.at(atom_index_2));
        dihedral_atoms.push_back(atom_names.at(atom_index_3));
        dihedral_atoms.push_back(atom_names.at(atom_index_4));
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(atom_index_1 >= start_index && atom_index_1 < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                dihedral_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(atom_index_2 >= start_index && atom_index_2 < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                dihedral_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(atom_index_3 >= start_index && atom_index_3 < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                dihedral_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(atom_index_4 >= start_index && atom_index_4 < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                dihedral_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        TopologyDihedral* dihedral = new TopologyDihedral(dihedral_atoms, dihedral_atoms_residue_names);
        if(dihedrals_inc_hydrogens.at(i*5+2) < 0)
            dihedral->SetIgnoredGroupInteraction(true);
        else
            dihedral->SetIgnoredGroupInteraction(false);
        if(dihedrals_inc_hydrogens.at(i*5+3) < 0)
            dihedral->SetIsImproper(true);
        else
            dihedral->SetIsImproper(false);
        dihedral->SetIncludingHydrogen(true);
        dihedral->SetDihedralType(dihedral_types_[dihedrals_inc_hydrogens.at(i*5+4) - 1]);
        stringstream key;
        key << dihedral_atoms_residue_names.at(0) << ":" << dihedral_atoms.at(0) << "-" << dihedral_atoms_residue_names.at(1) << ":" << dihedral_atoms.at(1) << "-"
            << dihedral_atoms_residue_names.at(2) << ":" << dihedral_atoms.at(2) << "-" << dihedral_atoms_residue_names.at(3) << ":" << dihedral_atoms.at(3) << "_"
            << dihedral->GetDihedralType() << "_"
            << (dihedral->GetIsImproper() ? "IY" : "IN") << "_" << (dihedral->GetIgnoredGroupInteraction() ? "GY" : "GN");
        dihedrals_[key.str()] = dihedral;
    }
    // Dihedrals excluding hydrogen
    for(int i = 0; i < number_of_dihedrals_excluding_hydrogen_; i++)
    {
        vector<string> dihedral_atoms = vector<string>();
        vector<string> dihedral_atoms_residue_names = vector<string>();
        int atom_index_1 = abs(dihedrals_without_hydrogens.at(i*5)) / 3;
        int atom_index_2 = abs(dihedrals_without_hydrogens.at(i*5+1)) / 3;
        int atom_index_3 = abs(dihedrals_without_hydrogens.at(i*5+2)) / 3;
        int atom_index_4 = abs(dihedrals_without_hydrogens.at(i*5+3)) / 3;
        dihedral_atoms.push_back(atom_names.at(atom_index_1));
        dihedral_atoms.push_back(atom_names.at(atom_index_2));
        dihedral_atoms.push_back(atom_names.at(atom_index_3));
        dihedral_atoms.push_back(atom_names.at(atom_index_4));
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(atom_index_1 >= start_index && atom_index_1 < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                dihedral_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(atom_index_2 >= start_index && atom_index_2 < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                dihedral_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(atom_index_3 >= start_index && atom_index_3 < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                dihedral_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        for(int j = 0; j < number_of_residues_; j++)
        {
            int start_index = residue_pointers.at(j) - 1;
            int end_index;
            if(j < number_of_residues_ - 1)
            {
                end_index = residue_pointers.at(j+1) - 1;
            }
            else
            {
                end_index = number_of_atoms_;
            }
            if(atom_index_4 >= start_index && atom_index_4 < end_index)
            {
                stringstream r;
                r << residue_labels.at(j) << "(" << (j+1) << ")";
                dihedral_atoms_residue_names.push_back(r.str());
                break;
            }
        }
        TopologyDihedral* dihedral = new TopologyDihedral(dihedral_atoms, dihedral_atoms_residue_names);
        if(dihedrals_without_hydrogens.at(i*5+2) < 0)
            dihedral->SetIgnoredGroupInteraction(true);
        else
            dihedral->SetIgnoredGroupInteraction(false);
        if(dihedrals_without_hydrogens.at(i*5+3) < 0)
            dihedral->SetIsImproper(true);
        else
            dihedral->SetIsImproper(false);
        dihedral->SetIncludingHydrogen(false);
        dihedral->SetDihedralType(dihedral_types_[dihedrals_without_hydrogens.at(i*5+4) - 1]);
        stringstream key;
        key << dihedral_atoms_residue_names.at(0) << ":" << dihedral_atoms.at(0) << "-" << dihedral_atoms_residue_names.at(1) << ":" << dihedral_atoms.at(1) << "-"
            << dihedral_atoms_residue_names.at(2) << ":" << dihedral_atoms.at(2) << "-" << dihedral_atoms_residue_names.at(3) << ":" << dihedral_atoms.at(3) << "_"
            << dihedral->GetDihedralType() << "_"
            << (dihedral->GetIsImproper() ? "IY" : "IN") << "_" << (dihedral->GetIgnoredGroupInteraction() ? "GY" : "GN");
        dihedrals_[key.str()] = dihedral;
    }
    // Residues in topology file
    int start_index = 0;
    TopologyAssembly::TopologyResidueMap residues;
    for(vector<string>::iterator it = residue_labels.begin(); it != residue_labels.end(); it++)
    {
        string residue_name = *it;
        TopologyResidue::TopologyAtomMap atoms;
        int residue_index = distance(residue_labels.begin(), it) + 1;
        int starting_atom_index = residue_pointers.at(residue_index - 1);
        int ending_atom_index;
        if(residue_index < number_of_residues_)
        {
            ending_atom_index = residue_pointers.at(residue_index);
        }
        else
        {
            ending_atom_index = number_of_atoms_ + 1;
        }
        for(int i = starting_atom_index - 1; i < ending_atom_index - 1; i++)
        {
            TopologyAtom::ExcludedAtomNames excluded_atoms = TopologyAtom::ExcludedAtomNames();
            if(i > 0)
                start_index += number_excluded_atoms.at(i-1);
            for(int j = start_index; j < start_index + number_excluded_atoms.at(i); j++)
            {
                string excluded_atom_residue_name;
                int index = (excluded_atoms_lists.at(j) - 1 == -1) ? 0 : excluded_atoms_lists.at(j) - 1;
                for(int k = 0; k < number_of_residues_; k++)
                {
                    int start_atom_index = residue_pointers.at(k) - 1;
                    int end_atom_index;
                    if(k < number_of_residues_ - 1)
                    {
                        end_atom_index = residue_pointers.at(k+1) - 1;
                    }
                    else
                    {
                        end_atom_index = number_of_atoms_;
                    }
                    if(index >= start_atom_index && index < end_atom_index)
                    {
                        excluded_atom_residue_name = residue_labels.at(k);
                        break;
                    }
                }
                excluded_atoms.push_back(excluded_atom_residue_name + ":" + atom_names.at(index));
            }
            atoms[atom_names.at(i)] = new TopologyAtom(i + 1, atom_names.at(i), amber_atom_types.at(i), charges.at(i), atomic_numbers.at(i), masses.at(i), excluded_atoms,
                                                       number_excluded_atoms.at(i), radiis.at(i), screens.at(i), tree_chain_classifications.at(i), residue_name);
        }
        residues[residue_name] = new TopologyResidue(residue_name, atoms, residue_index, starting_atom_index);
    }
    assembly_ = new TopologyAssembly();
    assembly_->SetAssemblyName(title_);
    assembly_->SetResidues(residues);
}
void TopologyFile::ParseTitlePartition (std::stringstream & stream)
Definition at line 1518 of file topologyfile.cc.
References gmml::Trim().
{
    string line;
    // Section Header
    getline(stream, line);
    // Section Format
    getline(stream, line);
    while(!line.empty())
    {
        string format = "20a4";
        if(line[0] == '%')
        {
            if(line.find("%FORMAT") != string::npos)
            {
                format = line.substr(line.find_first_of('(', 0) + 1, line.find_last_of(')', line.length()) - line.find_first_of('(', 0) - 1);
            }
        }
        else
        {
            title_ += line;
        }
        getline(stream, line);
    }
    title_ = Trim(title_);
}
template<typename T > std::vector<T> TopologyFileSpace::TopologyFile::PartitionLine (std::string line, std::string format)
template<typename T > vector<T> TopologyFileSpace::TopologyFile::PartitionLine (string line, string format)
Definition at line 1637 of file topologyfile.cc.
References gmml::Split(), and gmml::Trim().
{
    vector<T> items = vector<T>();
    if(format.compare("10I8") == 0)
    {
        int number_of_items = 10;
        int item_length = 8;
        for(int i = 0; i < number_of_items && item_length * (i+1) <= (int)line.length(); i++)
        {
            string token = line.substr(i*item_length, item_length);
            token = Trim(token);
            items.push_back(ConvertString<T>(token));
        }
        return items;
    }
    if(format.compare("20a4") == 0)
    {
        int number_of_items = 20;
        int item_length = 4;
        for(int i = 0; i < number_of_items && item_length * (i+1) <= (int)line.length(); i++)
        {
            string token = line.substr(i*item_length, item_length);
            token = Trim(token);
            items.push_back(ConvertString<T>(token));
        }
        return items;
    }
    if(format.compare("5E16.8") == 0)
    {
        int number_of_items = 5;
        int item_length = 16;
        for(int i = 0; i < number_of_items && item_length * (i+1) <= (int)line.length(); i++)
        {
            string token = line.substr(i*item_length, item_length);
            token = Trim(token);
            double base = ConvertString<double>(Split(token, "E")[0]);
            int power = ConvertString<int>(Split(token, "E")[1]);
            stringstream temp, format;
            double result = base * pow10(power);
            format << setw(16) << fixed << setprecision(8);
            temp << format.str() << result;
            T item = ConvertString<T>(temp.str());
            items.push_back(item);
        }
        return items;
    }
    if(format.compare("1a80") == 0)
    {
        int number_of_items = 1;
        int item_length = 80;
        for(int i = 0; i < number_of_items && item_length * (i+1) <= (int)line.length(); i++)
        {
            string token = line.substr(i*item_length, item_length);
            std::replace_if(token.begin(), token.end(), ::isspace, '#');
            token = Trim(token);
            items.push_back(ConvertString<T>(token));
        }
        return items;
    }
    if(format.compare("1I8") == 0)
    {
        int number_of_items = 1;
        int item_length = 8;
        for(int i = 0; i < number_of_items && item_length * (i+1) <= (int)line.length(); i++)
        {
            string token = line.substr(i*item_length, item_length);
            token = Trim(token);
            items.push_back(ConvertString<T>(token));
        }
        return items;
    }
    return items;
}
void TopologyFile::PartitionSection (std::ifstream & stream, std::string & line, std::stringstream & section)
Definition at line 1495 of file topologyfile.cc.
{
    while(line[0] == '%')
    {
        if(line.find("%FLAG") != string::npos)
        {
            section << line << endl;
        }
        if(line.find("%FORMAT") != string::npos)
        {
            section << line << endl;
        }
        getline(stream, line);
    }
    while(line[0] != '%')
    {
        section << line << endl;
        getline(stream, line);
        if(line.empty())
            break;
    }
}
void TopologyFile::Print (std::ostream & out = std::cout)
Definition at line 3015 of file topologyfile.cc.
References TopologyFileSpace::TopologyBondType::Print(), TopologyFileSpace::TopologyAngleType::Print(), TopologyFileSpace::TopologyBond::Print(), TopologyFileSpace::TopologyAngle::Print(), TopologyFileSpace::TopologyAtomPair::Print(), TopologyFileSpace::TopologyDihedral::Print(), and TopologyFileSpace::TopologyDihedralType::Print().
{
    out << "============================ " << title_ << " ===========================" << endl;
    assembly_->Print(out);
    out << "------------------------------ Atom Pairs ------------------------------" << endl;
    for(TopologyAtomPairMap::iterator it = pairs_.begin(); it != pairs_.end(); it++)
    {
        TopologyAtomPair* atom_pair = (*it).second;
        atom_pair->Print(out);
    }
    out << "------------------------------ Bond Types ------------------------------" << endl;
    for(TopologyBondTypeMap::iterator it = bond_types_.begin(); it != bond_types_.end(); it++)
    {
        TopologyBondType* bond_type = (*it).second;
        bond_type->Print(out);
        out << endl;
    }
    out << "------------------------------ Angle Types ------------------------------" << endl;
    for(TopologyAngleTypeMap::iterator it = angle_types_.begin(); it != angle_types_.end(); it++)
    {
        TopologyAngleType* angle_type = (*it).second;
        angle_type->Print(out);
        out << endl;
    }
    out << "------------------------------ Dihedral Types ------------------------------" << endl;
    for(TopologyDihedralTypeMap::iterator it = dihedral_types_.begin(); it != dihedral_types_.end(); it++)
    {
        TopologyDihedralType* dihedral_type = (*it).second;
        dihedral_type->Print(out);
        out << endl;
    }
    out << "------------------------------ Bonds ------------------------------" << endl;
    for(TopologyBondMap::iterator it = bonds_.begin(); it != bonds_.end(); it++)
    {
        TopologyBond* bond = (*it).second;
        bond->Print(out);
    }
    out << "------------------------------ Angles ------------------------------" << endl;
    for(TopologyAngleMap::iterator it = angles_.begin(); it != angles_.end(); it++)
    {
        TopologyAngle* angle = (*it).second;
        angle->Print(out);
    }
    out << "------------------------------ Dihedrals ------------------------------" << endl;
    for(TopologyDihedralMap::iterator it = dihedrals_.begin(); it != dihedrals_.end(); it++)
    {
        TopologyDihedral* dihedral = (*it).second;
        dihedral->Print(out);
    }
}
void TopologyFile::Read (std::ifstream & in_file)
Definition at line 603 of file topologyfile.cc.
{
    this->ParseSections(in_file);
}
void TopologyFile::ResolveAmberAtomTypeSection (std::ofstream & out)
Definition at line 2858 of file topologyfile.cc.
References TopologyFileSpace::TopologyResidue::GetAtomByIndex(), TopologyFileSpace::TopologyResidue::GetAtoms(), and TopologyFileSpace::TopologyAtom::GetType().
{
    out << "%FLAG AMBER_ATOM_TYPE" << endl
        << "%FORMAT(20a4)" << endl;
    int count = 0;
    int index = 0;
    const int MAX_IN_LINE = 20;
    const int ITEM_LENGTH = 4;
    for(int i = 0; i < number_of_residues_; i++)
    {
        TopologyResidue* residue = this->assembly_->GetResidueByIndex(i+1);
        for(unsigned int j = 0; j < residue->GetAtoms().size(); j++)
        {
            TopologyAtom* atom = residue->GetAtomByIndex(index+1);
            index++;
            out << setw(ITEM_LENGTH) << left << atom->GetType();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveAngleEquilValueSection (std::ofstream & out)
Definition at line 2276 of file topologyfile.cc.
References TopologyFileSpace::TopologyAngleType::GetEquilibriumValue().
{
    out << "%FLAG ANGLE_EQUIL_VALUE" << endl
        << "%FORMAT(5E16.8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 5;
    const int ITEM_LENGTH = 16;
    for(int i = 0; i < number_of_angle_types_; i++)
    {
        TopologyAngleType* angle_type = this->GetAngleTypeByIndex(i);
        if(angle_type != NULL)
        {
            out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << angle_type->GetEquilibriumValue();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveAngleForceConstantSection (std::ofstream & out)
Definition at line 2251 of file topologyfile.cc.
References TopologyFileSpace::TopologyAngleType::GetForceConstant().
{
    out << "%FLAG ANGLE_FORCE_CONSTANT" << endl
        << "%FORMAT(5E16.8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 5;
    const int ITEM_LENGTH = 16;
    for(int i = 0; i < number_of_angle_types_; i++)
    {
        TopologyAngleType* angle_type = this->GetAngleTypeByIndex(i);
        if(angle_type != NULL)
        {
            out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << angle_type->GetForceConstant();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveAnglesIncHydrogenSection (std::ofstream & out)
Definition at line 2571 of file topologyfile.cc.
References TopologyFileSpace::TopologyAngle::GetAngles(), TopologyFileSpace::TopologyAngle::GetAngleType(), TopologyFileSpace::TopologyAngle::GetIncludingHydrogen(), and TopologyFileSpace::TopologyAngleType::GetIndex().
{
    out << "%FLAG ANGLES_INC_HYDROGEN" << endl
        << "%FORMAT(10I8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 10;
    const int ITEM_LENGTH = 8;
    for(TopologyAngleMap::iterator it = angles_.begin(); it != angles_.end(); it++)
    {
        TopologyAngle* angle = (*it).second;
        vector<string> atom_names = angle->GetAngles();
        if(angle->GetIncludingHydrogen())
        {
            int atom_index_1 = this->assembly_->GetAtomIndexByName(atom_names.at(0));
            int atom_index_2 = this->assembly_->GetAtomIndexByName(atom_names.at(1));
            int atom_index_3 = this->assembly_->GetAtomIndexByName(atom_names.at(2));
            int angle_type_index = angle->GetAngleType()->GetIndex();
            out << setw(ITEM_LENGTH) << right << (atom_index_1-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            out << setw(ITEM_LENGTH) << right << (atom_index_2-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            out << setw(ITEM_LENGTH) << right << (atom_index_3-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            out << setw(ITEM_LENGTH) << right << angle_type_index+1;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveAnglesWithoutHydrogenSection (std::ofstream & out)
Definition at line 2622 of file topologyfile.cc.
References TopologyFileSpace::TopologyAngle::GetAngles(), TopologyFileSpace::TopologyAngle::GetAngleType(), TopologyFileSpace::TopologyAngle::GetIncludingHydrogen(), and TopologyFileSpace::TopologyAngleType::GetIndex().
{
    out << "%FLAG ANGLES_WITHOUT_HYDROGEN" << endl
        << "%FORMAT(10I8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 10;
    const int ITEM_LENGTH = 8;
    for(TopologyAngleMap::iterator it = angles_.begin(); it != angles_.end(); it++)
    {
        TopologyAngle* angle = (*it).second;
        vector<string> atom_names = angle->GetAngles();
        if(!angle->GetIncludingHydrogen())
        {
            int atom_index_1 = this->assembly_->GetAtomIndexByName(atom_names.at(0));
            int atom_index_2 = this->assembly_->GetAtomIndexByName(atom_names.at(1));
            int atom_index_3 = this->assembly_->GetAtomIndexByName(atom_names.at(2));
            int angle_type_index = angle->GetAngleType()->GetIndex();
            out << setw(ITEM_LENGTH) << right << (atom_index_1-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            out << setw(ITEM_LENGTH) << right << (atom_index_2-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            out << setw(ITEM_LENGTH) << right << (atom_index_3-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            out << setw(ITEM_LENGTH) << right << angle_type_index+1;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveAtomicNumberSection (std::ofstream & out)
Definition at line 1978 of file topologyfile.cc.
References TopologyFileSpace::TopologyResidue::GetAtomByIndex(), TopologyFileSpace::TopologyAtom::GetAtomicNumber(), TopologyFileSpace::TopologyResidue::GetAtoms(), and gmml::iNotSet.
{
    out << "%FLAG ATOMIC_NUMBER" << endl
        << "%FORMAT(10I8)" << endl;
    int count = 0;
    int index = 0;
    const int MAX_IN_LINE = 10;
    const int ITEM_LENGTH = 8;
    for(int i = 0; i < number_of_residues_; i++)
    {
        TopologyResidue* residue = this->assembly_->GetResidueByIndex(i+1);
        for(unsigned int j = 0; j < residue->GetAtoms().size(); j++)
        {
            TopologyAtom* atom = residue->GetAtomByIndex(index+1);
            index++;
            if(atom->GetAtomicNumber() != iNotSet)
                out << setw(ITEM_LENGTH) << right << atom->GetAtomicNumber();
            else
                out << setw(ITEM_LENGTH) << right << 0;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveAtomNameSection (std::ofstream & out)
Definition at line 1922 of file topologyfile.cc.
References TopologyFileSpace::TopologyResidue::GetAtomByIndex(), TopologyFileSpace::TopologyAtom::GetAtomName(), and TopologyFileSpace::TopologyResidue::GetAtoms().
{
    out << "%FLAG ATOM_NAME" << endl
        << "%FORMAT(20a4)" << endl;
    int count = 0;
    int index = 0;
    const int MAX_IN_LINE = 20;
    const int ITEM_LENGTH = 4;
    for(int i = 0; i < number_of_residues_; i++)
    {
        TopologyResidue* residue = this->assembly_->GetResidueByIndex(i+1);
        for(unsigned int j = 0; j < residue->GetAtoms().size(); j++)
        {
            TopologyAtom* atom = residue->GetAtomByIndex(index+1);
            index++;
            out << setw(ITEM_LENGTH) << left << atom->GetAtomName();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveAtomTypeIndexSection (std::ofstream & out)
Definition at line 2037 of file topologyfile.cc.
References TopologyFileSpace::TopologyResidue::GetAtomByIndex(), TopologyFileSpace::TopologyResidue::GetAtoms(), and TopologyFileSpace::TopologyAtom::GetType().
{
    out << "%FLAG ATOM_TYPE_INDEX" << endl
        << "%FORMAT(10I8)" << endl;
    int count = 0;
    int index = 0;
    const int MAX_IN_LINE = 10;
    const int ITEM_LENGTH = 8;
    TopologyAtomTypeIndexMap atom_type_index_map = this->GetAtomTypeIndexMap();
    for(int i = 0; i < number_of_residues_; i++)
    {
        TopologyResidue* residue = this->assembly_->GetResidueByIndex(i+1);
        for(unsigned int j = 0; j < residue->GetAtoms().size(); j++)
        {
            TopologyAtom* atom = residue->GetAtomByIndex(index+1);
            index++;
            out << setw(ITEM_LENGTH) << right << atom_type_index_map[atom->GetType()];
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveBondEquilValueSection (std::ofstream & out)
Definition at line 2226 of file topologyfile.cc.
References TopologyFileSpace::TopologyBondType::GetEquilibriumValue().
{
    out << "%FLAG BOND_EQUIL_VALUE" << endl
        << "%FORMAT(5E16.8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 5;
    const int ITEM_LENGTH = 16;
    for(int i = 0; i < number_of_bond_types_; i++)
    {
        TopologyBondType* bond_type = this->GetBondTypeByIndex(i);
        if(bond_type != NULL)
        {
            out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << bond_type->GetEquilibriumValue();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveBondForceConstantSection (std::ofstream & out)
Definition at line 2201 of file topologyfile.cc.
References TopologyFileSpace::TopologyBondType::GetForceConstant().
{
    out << "%FLAG BOND_FORCE_CONSTANT" << endl
        << "%FORMAT(5E16.8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 5;
    const int ITEM_LENGTH = 16;
    for(int i = 0; i < number_of_bond_types_; i++)
    {
        TopologyBondType* bond_type = this->GetBondTypeByIndex(i);
        if(bond_type != NULL)
        {
            out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << bond_type->GetForceConstant();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveBondsIncHydrogenSection (std::ofstream & out)
Definition at line 2485 of file topologyfile.cc.
References TopologyFileSpace::TopologyBond::GetBonds(), TopologyFileSpace::TopologyBond::GetBondType(), TopologyFileSpace::TopologyBond::GetIncludingHydrogen(), and TopologyFileSpace::TopologyBondType::GetIndex().
{
    out << "%FLAG BONDS_INC_HYDROGEN" << endl
        << "%FORMAT(10I8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 10;
    const int ITEM_LENGTH = 8;
    for(TopologyBondMap::iterator it = bonds_.begin(); it != bonds_.end(); it++)
    {
        TopologyBond* bond = (*it).second;
        vector<string> atom_names = bond->GetBonds();
        if(bond->GetIncludingHydrogen())
        {
            int atom_index_1 = this->assembly_->GetAtomIndexByName(atom_names.at(0));
            int atom_index_2 = this->assembly_->GetAtomIndexByName(atom_names.at(1));
            int bond_type_index = bond->GetBondType()->GetIndex();
            out << setw(ITEM_LENGTH) << right << (atom_index_1-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            out << setw(ITEM_LENGTH) << right << (atom_index_2-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            out << setw(ITEM_LENGTH) << right << bond_type_index+1;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveBondsWithoutHydrogenSection (std::ofstream & out)
Definition at line 2528 of file topologyfile.cc.
References TopologyFileSpace::TopologyBond::GetBonds(), TopologyFileSpace::TopologyBond::GetBondType(), TopologyFileSpace::TopologyBond::GetIncludingHydrogen(), and TopologyFileSpace::TopologyBondType::GetIndex().
{
    out << "%FLAG BONDS_WITHOUT_HYDROGEN" << endl
        << "%FORMAT(10I8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 10;
    const int ITEM_LENGTH = 8;
    for(TopologyBondMap::iterator it = bonds_.begin(); it != bonds_.end(); it++)
    {
        TopologyBond* bond = (*it).second;
        vector<string> atom_names = bond->GetBonds();
        if(!bond->GetIncludingHydrogen())
        {
            int atom_index_1 = this->assembly_->GetAtomIndexByName(atom_names.at(0));
            int atom_index_2 = this->assembly_->GetAtomIndexByName(atom_names.at(1));
            int bond_type_index = bond->GetBondType()->GetIndex();
            out << setw(ITEM_LENGTH) << right << (atom_index_1-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            out << setw(ITEM_LENGTH) << right << (atom_index_2-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            out << setw(ITEM_LENGTH) << right << bond_type_index+1;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveChargeSection (std::ofstream & out)
Definition at line 1950 of file topologyfile.cc.
References TopologyFileSpace::TopologyResidue::GetAtomByIndex(), TopologyFileSpace::TopologyAtom::GetAtomCharge(), and TopologyFileSpace::TopologyResidue::GetAtoms().
{
    out << "%FLAG CHARGE" << endl
        << "%FORMAT(5E16.8)" << endl;
    int count = 0;
    int index = 0;
    const int MAX_IN_LINE = 5;
    const int ITEM_LENGTH = 16;
    for(int i = 0; i < number_of_residues_; i++)
    {
        TopologyResidue* residue = this->assembly_->GetResidueByIndex(i+1);
        for(unsigned int j = 0; j < residue->GetAtoms().size(); j++)
        {
            TopologyAtom* atom = residue->GetAtomByIndex(index+1);
            index++;
            out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << atom->GetAtomCharge();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveDihedralForceConstantSection (std::ofstream & out)
Definition at line 2301 of file topologyfile.cc.
References TopologyFileSpace::TopologyDihedralType::GetForceConstant().
{
    out << "%FLAG DIHEDRAL_FORCE_CONSTANT" << endl
        << "%FORMAT(5E16.8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 5;
    const int ITEM_LENGTH = 16;
    for(int i = 0; i < number_of_dihedral_types_; i++)
    {
        TopologyDihedralType* dihedral_type = this->GetDihedralTypeByIndex(i);
        if(dihedral_type != NULL)
        {
            out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << dihedral_type->GetForceConstant();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveDihedralPeriodicitySection (std::ofstream & out)
Definition at line 2326 of file topologyfile.cc.
References TopologyFileSpace::TopologyDihedralType::GetPeriodicity().
{
    out << "%FLAG DIHEDRAL_PERIODICITY" << endl
        << "%FORMAT(5E16.8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 5;
    const int ITEM_LENGTH = 16;
    for(int i = 0; i < number_of_dihedral_types_; i++)
    {
        TopologyDihedralType* dihedral_type = this->GetDihedralTypeByIndex(i);
        if(dihedral_type != NULL)
        {
            out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << dihedral_type->GetPeriodicity();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveDihedralPhaseSection (std::ofstream & out)
Definition at line 2351 of file topologyfile.cc.
References TopologyFileSpace::TopologyDihedralType::GetPhase().
{
    out << "%FLAG DIHEDRAL_PHASE" << endl
        << "%FORMAT(5E16.8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 5;
    const int ITEM_LENGTH = 16;
    for(int i = 0; i < number_of_dihedral_types_; i++)
    {
        TopologyDihedralType* dihedral_type = this->GetDihedralTypeByIndex(i);
        if(dihedral_type != NULL)
        {
            out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << dihedral_type->GetPhase();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveDihedralsIncHydrogenSection (std::ofstream & out)
Definition at line 2673 of file topologyfile.cc.
References TopologyFileSpace::TopologyDihedral::GetDihedrals(), TopologyFileSpace::TopologyDihedral::GetDihedralType(), TopologyFileSpace::TopologyDihedral::GetIgnoredGroupInteraction(), TopologyFileSpace::TopologyDihedral::GetIncludingHydrogen(), TopologyFileSpace::TopologyDihedralType::GetIndex(), and TopologyFileSpace::TopologyDihedral::GetIsImproper().
{
    out << "%FLAG DIHEDRALS_INC_HYDROGEN" << endl
        << "%FORMAT(10I8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 10;
    const int ITEM_LENGTH = 8;
    for(TopologyDihedralMap::iterator it = dihedrals_.begin(); it != dihedrals_.end(); it++)
    {
        TopologyDihedral* dihedral = (*it).second;
        vector<string> atom_names = dihedral->GetDihedrals();
        if(dihedral->GetIncludingHydrogen())
        {
            int atom_index_1 = this->assembly_->GetAtomIndexByName(atom_names.at(0));
            int atom_index_2 = this->assembly_->GetAtomIndexByName(atom_names.at(1));
            int atom_index_3 = this->assembly_->GetAtomIndexByName(atom_names.at(2));
            int atom_index_4 = this->assembly_->GetAtomIndexByName(atom_names.at(3));
            int dihedral_type_index = dihedral->GetDihedralType()->GetIndex();
            out << setw(ITEM_LENGTH) << right << (atom_index_1-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            out << setw(ITEM_LENGTH) << right << (atom_index_2-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            if(dihedral->GetIgnoredGroupInteraction())
                out << setw(ITEM_LENGTH) << right << -(atom_index_3-1)*3;
            else
                out << setw(ITEM_LENGTH) << right << (atom_index_3-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            if(dihedral->GetIsImproper())
                out << setw(ITEM_LENGTH) << right << -(atom_index_4-1)*3;
            else
                out << setw(ITEM_LENGTH) << right << (atom_index_4-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            out << setw(ITEM_LENGTH) << right << dihedral_type_index+1;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveDihedralsWithoutHydrogenSection (std::ofstream & out)
Definition at line 2738 of file topologyfile.cc.
References TopologyFileSpace::TopologyDihedral::GetDihedrals(), TopologyFileSpace::TopologyDihedral::GetDihedralType(), TopologyFileSpace::TopologyDihedral::GetIgnoredGroupInteraction(), TopologyFileSpace::TopologyDihedral::GetIncludingHydrogen(), TopologyFileSpace::TopologyDihedralType::GetIndex(), and TopologyFileSpace::TopologyDihedral::GetIsImproper().
{
    out << "%FLAG DIHEDRALS_WITHOUT_HYDROGEN" << endl
        << "%FORMAT(10I8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 10;
    const int ITEM_LENGTH = 8;
    for(TopologyDihedralMap::iterator it = dihedrals_.begin(); it != dihedrals_.end(); it++)
    {
        TopologyDihedral* dihedral = (*it).second;
        vector<string> atom_names = dihedral->GetDihedrals();
        if(!dihedral->GetIncludingHydrogen())
        {
            int atom_index_1 = this->assembly_->GetAtomIndexByName(atom_names.at(0));
            int atom_index_2 = this->assembly_->GetAtomIndexByName(atom_names.at(1));
            int atom_index_3 = this->assembly_->GetAtomIndexByName(atom_names.at(2));
            int atom_index_4 = this->assembly_->GetAtomIndexByName(atom_names.at(3));
            int dihedral_type_index = dihedral->GetDihedralType()->GetIndex();
            out << setw(ITEM_LENGTH) << right << (atom_index_1-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            out << setw(ITEM_LENGTH) << right << (atom_index_2-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            if(dihedral->GetIgnoredGroupInteraction())
                out << setw(ITEM_LENGTH) << right << -(atom_index_3-1)*3;
            else
                out << setw(ITEM_LENGTH) << right << (atom_index_3-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            if(dihedral->GetIsImproper())
                out << setw(ITEM_LENGTH) << right << -(atom_index_4-1)*3;
            else
                out << setw(ITEM_LENGTH) << right << (atom_index_4-1)*3;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
            out << setw(ITEM_LENGTH) << right << dihedral_type_index+1;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveExcludedAtomsListSection (std::ofstream & out)
Definition at line 2803 of file topologyfile.cc.
References TopologyFileSpace::TopologyResidue::GetAtomByIndex(), TopologyFileSpace::TopologyResidue::GetAtoms(), TopologyFileSpace::TopologyAtom::GetExcludedAtoms(), and gmml::Split().
{
    out << "%FLAG EXCLUDED_ATOM_LIST" << endl
        << "%FORMAT(10I8)" << endl;
    int count = 0;
    int index = 0;
    const int MAX_IN_LINE = 10;
    const int ITEM_LENGTH = 8;
    for(int i = 0; i < number_of_residues_; i++)
    {
        TopologyResidue* residue = this->assembly_->GetResidueByIndex(i+1);
        for(unsigned int j = 0; j < residue->GetAtoms().size(); j++)
        {
            TopologyAtom* atom = residue->GetAtomByIndex(index+1);
            index++;
            vector<string> excluded_atoms = atom->GetExcludedAtoms();
            for(vector<string>::iterator it = excluded_atoms.begin(); it != excluded_atoms.end(); it++)
            {
                string atom_id = (*it);
                int index = this->assembly_->GetAtomIndexByName(Split(atom_id, ":").at(1));
                out << setw(ITEM_LENGTH) << right << index;
                count++;
                if(count == MAX_IN_LINE)
                {
                    count = 0;
                    out << endl;
                }
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveHBCutSection (std::ofstream & out)
Definition at line 2851 of file topologyfile.cc.
{
    out << "%FLAG HBCUT" << endl
        << "%FORMAT(5E16.8)" << endl;
    //
}
void TopologyFile::ResolveHydrogenBondACoefSection (std::ofstream & out)
Definition at line 2837 of file topologyfile.cc.
{
    out << "%FLAG HBOND_ACOEF" << endl
        << "%FORMAT(5E16.8)" << endl;
    //
}
void TopologyFile::ResolveHydrogenBondBCoefSection (std::ofstream & out)
Definition at line 2844 of file topologyfile.cc.
{
    out << "%FLAG HBOND_BCOEF" << endl
        << "%FORMAT(5E16.8)" << endl;
    //
}
void TopologyFile::ResolveIRotatSection (std::ofstream & out)
Definition at line 2925 of file topologyfile.cc.
{
    out << "%FLAG IROTAT" << endl
        << "%FORMAT(10I8)" << endl;
    //
}
void TopologyFile::ResolveJoinArraySection (std::ofstream & out)
Definition at line 2917 of file topologyfile.cc.
{
    out << "%FLAG JOIN_ARRAY" << endl
        << "%FORMAT(10I8)" << endl;
    //
    out << endl;
}
void TopologyFile::ResolveLennardJonesACoefSection (std::ofstream & out)
Definition at line 2433 of file topologyfile.cc.
References TopologyFileSpace::TopologyAtomPair::GetCoefficientA().
{
    out << "%FLAG LENNARD_JONES_ACOEF" << endl
        << "%FORMAT(5E16.8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 5;
    const int ITEM_LENGTH = 16;
    for(unsigned int i = 0; i < pairs_.size(); i++)
    {
        TopologyAtomPair* atom_pair = this->GetAtomPairByIndex(i+1);
        if(atom_pair != NULL)
        {
            out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << atom_pair->GetCoefficientA();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveLennardJonesBCoefSection (std::ofstream & out)
Definition at line 2459 of file topologyfile.cc.
References TopologyFileSpace::TopologyAtomPair::GetCoefficientB().
{
    out << "%FLAG LENNARD_JONES_BCOEF" << endl
        << "%FORMAT(5E16.8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 5;
    const int ITEM_LENGTH = 16;
    for(unsigned int i = 0; i < pairs_.size(); i++)
    {
        TopologyAtomPair* atom_pair = this->GetAtomPairByIndex(i+1);
        if(atom_pair != NULL)
        {
            out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << atom_pair->GetCoefficientB();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveMassSection (std::ofstream & out)
Definition at line 2009 of file topologyfile.cc.
References TopologyFileSpace::TopologyResidue::GetAtomByIndex(), TopologyFileSpace::TopologyAtom::GetAtomMass(), and TopologyFileSpace::TopologyResidue::GetAtoms().
{
    out << "%FLAG MASS" << endl
        << "%FORMAT(5E16.8)" << endl;
    int count = 0;
    int index = 0;
    const int MAX_IN_LINE = 5;
    const int ITEM_LENGTH = 16;
    for(int i = 0; i < number_of_residues_; i++)
    {
        TopologyResidue* residue = this->assembly_->GetResidueByIndex(i+1);
        for(unsigned int j = 0; j < residue->GetAtoms().size(); j++)
        {
            TopologyAtom* atom = residue->GetAtomByIndex(index+1);
            index++;
            out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << atom->GetAtomMass();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveNonbondedParmIndexSection (std::ofstream & out)
Definition at line 2094 of file topologyfile.cc.
References TopologyFileSpace::TopologyResidue::GetAtomByIndex(), TopologyFileSpace::TopologyResidue::GetAtoms(), TopologyFileSpace::TopologyAtom::GetIndex(), and TopologyFileSpace::TopologyAtom::GetType().
{
    out << "%FLAG NONBONDED_PARM_INDEX" << endl
        << "%FORMAT(10I8)" << endl;
    int index = 0;
    int count = 0;
    const int MAX_IN_LINE = 10;
    const int ITEM_LENGTH = 8;
    TopologyAtomTypeIndexMap atom_type_index_map = this->GetAtomTypeIndexMap();
    vector<string> atom_types = vector<string>();
    for(int i = 0; i < number_of_residues_; i++)
    {
        TopologyResidue* residue = this->assembly_->GetResidueByIndex(i+1);
        for(unsigned int j = 0; j < residue->GetAtoms().size(); j++)
        {
            TopologyAtom* atom = residue->GetAtomByIndex(index+1);
            index++;
            atom_types.push_back(atom->GetType());
        }
    }
    map<string, bool> pair_set = map<string, bool>();
    map<int, int> nonbond_index_map = map<int, int>();
    for(int i = 0; i < number_of_atoms_; i++)
    {
        string atom_type_1 = atom_types.at(i);
        for(int j = 0; j < number_of_atoms_; j++)
        {
            string atom_type_2 = atom_types.at(j);
            if(!pair_set[atom_type_1 + "-" + atom_type_2])
            {
                int nonbond_index = number_of_types_ * (atom_type_index_map[atom_type_1] - 1) + atom_type_index_map[atom_type_2];
                int parameter_index = 0;
                if(pairs_.find(atom_type_1 + "-" + atom_type_2) != pairs_.end())
                {
                    parameter_index = pairs_[atom_type_1 + "-" + atom_type_2]->GetIndex();
                }
                else if(pairs_.find(atom_type_2 + "-" + atom_type_1) != pairs_.end())
                {
                    parameter_index = pairs_[atom_type_2 + "-" + atom_type_1]->GetIndex();
                }
                nonbond_index_map[nonbond_index] = parameter_index;
                pair_set[atom_type_1 + "-" + atom_type_2] = true;
            }
        }
    }
    int size = nonbond_index_map.size();
    for(unsigned int i = 0; i < size; i++)
    {
        out << setw(ITEM_LENGTH) << right << nonbond_index_map[i+1];
        count++;
        if(count == MAX_IN_LINE)
        {
            count = 0;
            out << endl;
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveNumberExcludedAtomsSection (std::ofstream & out)
Definition at line 2066 of file topologyfile.cc.
References TopologyFileSpace::TopologyResidue::GetAtomByIndex(), TopologyFileSpace::TopologyResidue::GetAtoms(), and TopologyFileSpace::TopologyAtom::GetExcludedAtoms().
{
    out << "%FLAG NUMBER_EXCLUDED_ATOMS" << endl
        << "%FORMAT(10I8)" << endl;
    int count = 0;
    int index = 0;
    const int MAX_IN_LINE = 10;
    const int ITEM_LENGTH = 8;
    for(int i = 0; i < number_of_residues_; i++)
    {
        TopologyResidue* residue = this->assembly_->GetResidueByIndex(i+1);
        for(unsigned int j = 0; j < residue->GetAtoms().size(); j++)
        {
            TopologyAtom* atom = residue->GetAtomByIndex(index+1);
            index++;
            out << setw(ITEM_LENGTH) << right << atom->GetExcludedAtoms().size();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolvePointersSection (std::ofstream & out)
Definition at line 1785 of file topologyfile.cc.
References gmml::iNotSet.
{
    out << "%FLAG POINTERS" << endl
        << "%FORMAT(10I8)" << endl;
    if(number_of_atoms_ != iNotSet)
        out << setw(8) << right << number_of_atoms_;
    else
        out << setw(8) << right << 0;
    if(number_of_types_ != iNotSet)
        out << setw(8) << right << number_of_types_;
    else
        out << setw(8) << right << 0;
    if(number_of_bonds_including_hydrogen_ != iNotSet)
        out << setw(8) << right << number_of_bonds_including_hydrogen_;
    else
        out << setw(8) << right << 0;
    if(number_of_bonds_excluding_hydrogen_ != iNotSet)
        out << setw(8) << right << number_of_bonds_excluding_hydrogen_;
    else
        out << setw(8) << right << 0;
    if(number_of_angles_including_hydrogen_ != iNotSet)
        out << setw(8) << right << number_of_angles_including_hydrogen_;
    else
        out << setw(8) << right << 0;
    if(number_of_angles_excluding_hydrogen_ != iNotSet)
        out << setw(8) << right << number_of_angles_excluding_hydrogen_;
    else
        out << setw(8) << right << 0;
    if(number_of_dihedrals_including_hydrogen_ != iNotSet)
        out << setw(8) << right << number_of_dihedrals_including_hydrogen_;
    else
        out << setw(8) << right << 0;
    if(number_of_dihedrals_excluding_hydrogen_ != iNotSet)
        out << setw(8) << right << number_of_dihedrals_excluding_hydrogen_;
    else
        out << setw(8) << right << 0;
    if(number_of_hydrogen_parameters_ != iNotSet)
        out << setw(8) << right << number_of_hydrogen_parameters_;
    else
        out << setw(8) << right << 0;
    if(number_of_parameters_ != iNotSet)
        out << setw(8) << right << number_of_parameters_;
    else
        out << setw(8) << right << 0;
    out << endl;
    if(number_of_excluded_atoms_ != iNotSet)
        out << setw(8) << right << number_of_excluded_atoms_;
    else
        out << setw(8) << right << 0;
    if(number_of_residues_ != iNotSet)
        out << setw(8) << right << number_of_residues_;
    else
        out << setw(8) << right << 0;
    if(total_number_of_bonds_ != iNotSet)
        out << setw(8) << right << total_number_of_bonds_;
    else
        out << setw(8) << right << 0;
    if(total_number_of_angles_ != iNotSet)
        out << setw(8) << right << total_number_of_angles_;
    else
        out << setw(8) << right << 0;
    if(total_number_of_dihedrals_ != iNotSet)
        out << setw(8) << right << total_number_of_dihedrals_;
    else
        out << setw(8) << right << 0;
    if(number_of_bond_types_ != iNotSet)
        out << setw(8) << right << number_of_bond_types_;
    else
        out << setw(8) << right << 0;
    if(number_of_angle_types_ != iNotSet)
        out << setw(8) << right << number_of_angle_types_;
    else
        out << setw(8) << right << 0;
    if(number_of_dihedral_types_ != iNotSet)
        out << setw(8) << right << number_of_dihedral_types_;
    else
        out << setw(8) << right << 0;
    if(number_of_atom_types_in_parameter_file_ != iNotSet)
        out << setw(8) << right << number_of_atom_types_in_parameter_file_;
    else
        out << setw(8) << right << 0;
    if(number_of_distinct_hydrogen_bonds_ != iNotSet)
        out << setw(8) << right << number_of_distinct_hydrogen_bonds_;
    else
        out << setw(8) << right << 0;
    out << endl;
    if(perturbation_option_ != iNotSet)
        out << setw(8) << right << perturbation_option_;
    else
        out << setw(8) << right << 0;
    if(number_of_bonds_perturbed_ != iNotSet)
        out << setw(8) << right << number_of_bonds_perturbed_;
    else
        out << setw(8) << right << 0;
    if(number_of_angles_perturbed_ != iNotSet)
        out << setw(8) << right << number_of_angles_perturbed_;
    else
        out << setw(8) << right << 0;
    if(number_of_dihedrals_perturbed_ != iNotSet)
        out << setw(8) << right << number_of_dihedrals_perturbed_;
    else
        out << setw(8) << right << 0;
    if(number_of_bonds_group_perturbed_ != iNotSet)
        out << setw(8) << right << number_of_bonds_group_perturbed_;
    else
        out << setw(8) << right << 0;
    if(number_of_angles_group_perturbed_ != iNotSet)
        out << setw(8) << right << number_of_angles_group_perturbed_;
    else
        out << setw(8) << right << 0;
    if(number_of_dihedrals_group_perturbed_ != iNotSet)
        out << setw(8) << right << number_of_dihedrals_group_perturbed_;
    else
        out << setw(8) << right << 0;
    if(standard_periodic_box_option_ != iNotSet)
        out << setw(8) << right << standard_periodic_box_option_;
    else
        out << setw(8) << right << 0;
    if(number_of_atoms_in_largest_residue_ != iNotSet)
        out << setw(8) << right << number_of_atoms_in_largest_residue_;
    else
        out << setw(8) << right << 0;
    if(cap_option_ != iNotSet)
        out << setw(8) << right << cap_option_;
    else
        out << setw(8) << right << 0;
    out << endl;
    if(number_of_extra_points_ != iNotSet)
        out << setw(8) << number_of_extra_points_;
    else
        out << setw(8) << right << 0;
    if(number_of_beads_ != iNotSet)
        out << setw(8) << number_of_beads_ << endl;
    else
        out << setw(8) << right << 0 << endl;
}
void TopologyFile::ResolveRadiiSection (std::ofstream & out)
Definition at line 2950 of file topologyfile.cc.
References gmml::dNotSet, TopologyFileSpace::TopologyResidue::GetAtomByIndex(), TopologyFileSpace::TopologyResidue::GetAtoms(), and TopologyFileSpace::TopologyAtom::GetRadii().
{
    out << "%FLAG RADII" << endl
        << "%FORMAT(5E16.8)" << endl;
    int count = 0;
    int index = 0;
    const int MAX_IN_LINE = 5;
    const int ITEM_LENGTH = 16;
    for(int i = 0; i < number_of_residues_; i++)
    {
        TopologyResidue* residue = this->assembly_->GetResidueByIndex(i+1);
        for(unsigned int j = 0; j < residue->GetAtoms().size(); j++)
        {
            TopologyAtom* atom = residue->GetAtomByIndex(index+1);
            index++;
            if(atom->GetRadii() != dNotSet)
                out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << atom->GetRadii();
            else
                out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << 0.0;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveRadiusSetSection (std::ofstream & out)
Definition at line 2932 of file topologyfile.cc.
{
    if(radius_set_.size() != 0)
    {
        string radius_set = radius_set_.at(0);
        std::replace(radius_set.begin(), radius_set.end(), '#', ' ');
        out << "%FLAG RADIUS_SET" << endl
            << "%FORMAT(1a80)" << endl
            << radius_set << endl;
    }
    else
    {
        out << "%FLAG RADIUS_SET" << endl
            << "%FORMAT(1a80)" << endl;
    }
}
void TopologyFile::ResolveResidueLabelSection (std::ofstream & out)
Definition at line 2155 of file topologyfile.cc.
References TopologyFileSpace::TopologyResidue::GetResidueName().
{
    out << "%FLAG RESIDUE_LABEL" << endl
        << "%FORMAT(20a4)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 20;
    const int ITEM_LENGTH = 4;
    for(int i = 0; i < number_of_residues_; i++)
    {
        TopologyResidue* residue = this->assembly_->GetResidueByIndex(i+1);
        out << setw(ITEM_LENGTH) << left << residue->GetResidueName();
        count++;
        if(count == MAX_IN_LINE)
        {
            count = 0;
            out << endl;
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveResiduePointersSection (std::ofstream & out)
Definition at line 2178 of file topologyfile.cc.
References TopologyFileSpace::TopologyResidue::GetStartingAtomIndex().
{
    out << "%FLAG RESIDUE_POINTER" << endl
        << "%FORMAT(10I8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 10;
    const int ITEM_LENGTH = 8;
    for(int i = 0; i < number_of_residues_; i++)
    {
        TopologyResidue* residue = this->assembly_->GetResidueByIndex(i+1);
        out << setw(ITEM_LENGTH) << right << residue->GetStartingAtomIndex();
        count++;
        if(count == MAX_IN_LINE)
        {
            count = 0;
            out << endl;
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveSceeScaleFactorSection (std::ofstream & out)
Definition at line 2376 of file topologyfile.cc.
References TopologyFileSpace::TopologyDihedralType::GetScee().
{
    out << "%FLAG SCEE_SCALE_FACTOR" << endl
        << "%FORMAT(5E16.8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 5;
    const int ITEM_LENGTH = 16;
    for(int i = 0; i < number_of_dihedral_types_; i++)
    {
        TopologyDihedralType* dihedral_type = this->GetDihedralTypeByIndex(i);
        if(dihedral_type != NULL)
        {
            out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << dihedral_type->GetScee();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveScnbScaleFactorSection (std::ofstream & out)
Definition at line 2401 of file topologyfile.cc.
References TopologyFileSpace::TopologyDihedralType::GetScnb().
{
    out << "%FLAG SCNB_SCALE_FACTOR" << endl
        << "%FORMAT(5E16.8)" << endl;
    int count = 0;
    const int MAX_IN_LINE = 5;
    const int ITEM_LENGTH = 16;
    for(int i = 0; i < number_of_dihedral_types_; i++)
    {
        TopologyDihedralType* dihedral_type = this->GetDihedralTypeByIndex(i);
        if(dihedral_type != NULL)
        {
            out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << dihedral_type->GetScnb();
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveScreenSection (std::ofstream & out)
Definition at line 2981 of file topologyfile.cc.
References gmml::dNotSet, TopologyFileSpace::TopologyResidue::GetAtomByIndex(), TopologyFileSpace::TopologyResidue::GetAtoms(), and TopologyFileSpace::TopologyAtom::GetScreen().
{
    out << "%FLAG SCREEN" << endl
        << "%FORMAT(5E16.8)" << endl;
    int count = 0;
    int index = 0;
    const int MAX_IN_LINE = 5;
    const int ITEM_LENGTH = 16;
    for(int i = 0; i < number_of_residues_; i++)
    {
        TopologyResidue* residue = this->assembly_->GetResidueByIndex(i+1);
        for(unsigned int j = 0; j < residue->GetAtoms().size(); j++)
        {
            TopologyAtom* atom = residue->GetAtomByIndex(index+1);
            index++;
            if(atom->GetScreen() != dNotSet)
                out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << atom->GetScreen();
            else
                out << setw(ITEM_LENGTH) << right << scientific << setprecision(8) << 0.0;
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::ResolveSections (std::ofstream & out_stream)
Definition at line 1733 of file topologyfile.cc.
{
    this->ResolveTitleSection(out_stream);
    this->ResolvePointersSection(out_stream);
    this->ResolveAtomNameSection(out_stream);
    this->ResolveChargeSection(out_stream);
    this->ResolveAtomicNumberSection(out_stream);
    this->ResolveMassSection(out_stream);
    this->ResolveAtomTypeIndexSection(out_stream);
    this->ResolveNumberExcludedAtomsSection(out_stream);
    this->ResolveNonbondedParmIndexSection(out_stream);
    this->ResolveResidueLabelSection(out_stream);
    this->ResolveResiduePointersSection(out_stream);
    this->ResolveBondForceConstantSection(out_stream);
    this->ResolveBondEquilValueSection(out_stream);
    this->ResolveAngleForceConstantSection(out_stream);
    this->ResolveAngleEquilValueSection(out_stream);
    this->ResolveDihedralForceConstantSection(out_stream);
    this->ResolveDihedralPeriodicitySection(out_stream);
    this->ResolveDihedralPhaseSection(out_stream);
    this->ResolveSceeScaleFactorSection(out_stream);
    this->ResolveScnbScaleFactorSection(out_stream);
    this->ResolveSoltySection(out_stream);
    this->ResolveLennardJonesACoefSection(out_stream);
    this->ResolveLennardJonesBCoefSection(out_stream);
    this->ResolveBondsIncHydrogenSection(out_stream);
    this->ResolveBondsWithoutHydrogenSection(out_stream);
    this->ResolveAnglesIncHydrogenSection(out_stream);
    this->ResolveAnglesWithoutHydrogenSection(out_stream);
    this->ResolveDihedralsIncHydrogenSection(out_stream);
    this->ResolveDihedralsWithoutHydrogenSection(out_stream);
    this->ResolveExcludedAtomsListSection(out_stream);
    this->ResolveHydrogenBondACoefSection(out_stream);
    this->ResolveHydrogenBondBCoefSection(out_stream);
    this->ResolveHBCutSection(out_stream);
    this->ResolveAmberAtomTypeSection(out_stream);
    this->ResolveTreeChainClassificationSection(out_stream);
    this->ResolveJoinArraySection(out_stream);
    this->ResolveIRotatSection(out_stream);
    this->ResolveRadiusSetSection(out_stream);
    this->ResolveRadiiSection(out_stream);
    this->ResolveScreenSection(out_stream);
}
void TopologyFile::ResolveSoltySection (std::ofstream & out)
Definition at line 2426 of file topologyfile.cc.
{
    out << "%FLAG SOLTY" << endl
        << "%FORMAT(5E16.8)" << endl;
    //
}
void TopologyFile::ResolveTitleSection (std::ofstream & out)
Definition at line 1778 of file topologyfile.cc.
{
    out << "%FLAG TITLE" << endl
        << "%FORMAT(20a4)" << endl
        << title_ << endl;
}
void TopologyFile::ResolveTreeChainClassificationSection (std::ofstream & out)
Definition at line 2886 of file topologyfile.cc.
References TopologyFileSpace::TopologyResidue::GetAtomByIndex(), TopologyFileSpace::TopologyResidue::GetAtoms(), and TopologyFileSpace::TopologyAtom::GetTreeChainClassification().
{
    out << "%FLAG TREE_CHAIN_CLASSIFICATION" << endl
        << "%FORMAT(20a4)" << endl;
    int count = 0;
    int index = 0;
    const int MAX_IN_LINE = 20;
    const int ITEM_LENGTH = 4;
    for(int i = 0; i < number_of_residues_; i++)
    {
        TopologyResidue* residue = this->assembly_->GetResidueByIndex(i+1);
        for(unsigned int j = 0; j < residue->GetAtoms().size(); j++)
        {
            TopologyAtom* atom = residue->GetAtomByIndex(index+1);
            index++;
            if(!atom->GetTreeChainClassification().empty())
                out << setw(ITEM_LENGTH) << left << atom->GetTreeChainClassification();
            else
                out << setw(ITEM_LENGTH) << left << "0";
            count++;
            if(count == MAX_IN_LINE)
            {
                count = 0;
                out << endl;
            }
        }
    }
    if(count < MAX_IN_LINE)
        out << endl;
}
void TopologyFile::SetAngles (TopologyAngleMap angles)
Definition at line 515 of file topologyfile.cc.
{
    angles_.clear();
    for(TopologyAngleMap::iterator it = angles.begin(); it != angles.end(); it++)
    {
        string atom_angle = (*it).first;
        TopologyAngle* angle = (*it).second;
        angles_[atom_angle] = angle;
    }
}
void TopologyFile::SetAngleTypes (TopologyAngleTypeMap angle_types)
Definition at line 534 of file topologyfile.cc.
{
    angle_types_.clear();
    for(TopologyAngleTypeMap::iterator it = angle_types.begin(); it != angle_types.end(); it++)
    {
        int index = (*it).first;
        TopologyAngleType* angle_type = (*it).second;
        angle_types_[index] = angle_type;
    }
}
void TopologyFile::SetAssembly (TopologyAssembly * assembly)
Definition at line 468 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    assembly_ = assembly;
}
void TopologyFile::SetAtomPairs (TopologyAtomPairMap pairs)
Definition at line 584 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    pairs_.clear();
    for(TopologyAtomPairMap::iterator it = pairs.begin(); it != pairs.end(); it++)
    {
        string atom_pair_types = (*it).first;
        TopologyAtomPair* pair = (*it).second;
        pairs_[atom_pair_types] = pair;
    }
}
void TopologyFile::SetBonds (TopologyBondMap bonds)
Definition at line 481 of file topologyfile.cc.
{
    bonds_.clear();
    for(TopologyBondMap::iterator it = bonds.begin(); it != bonds.end(); it++)
    {
        string atom_bond = (*it).first;
        TopologyBond* bond = (*it).second;
        bonds_[atom_bond] = bond;
    }
}
void TopologyFile::SetBondTypes (TopologyBondTypeMap bond_types)
Definition at line 500 of file topologyfile.cc.
{
    bond_types_.clear();
    for(TopologyBondTypeMap::iterator it = bond_types.begin(); it != bond_types.end(); it++)
    {
        int index = (*it).first;
        TopologyBondType* bond_type = (*it).second;
        bond_types_[index] = bond_type;
    }
}
void TopologyFile::SetCapOption (int cap_option)
Definition at line 456 of file topologyfile.cc.
{
    cap_option_ = cap_option;
}
void TopologyFile::SetDihedrals (TopologyDihedralMap dihedrals)
Definition at line 549 of file topologyfile.cc.
{
    dihedrals_.clear();
    for(TopologyDihedralMap::iterator it = dihedrals.begin(); it != dihedrals.end(); it++)
    {
        string atom_dihedral = (*it).first;
        TopologyDihedral* dihedral = (*it).second;
        dihedrals_[atom_dihedral] = dihedral;
    }
}
void TopologyFile::SetDihedralTypes (TopologyDihedralTypeMap dihedral_types)
Definition at line 569 of file topologyfile.cc.
{
    dihedral_types_.clear();
    for(TopologyDihedralTypeMap::iterator it = dihedral_types.begin(); it != dihedral_types.end(); it++)
    {
        int index = (*it).first;
        TopologyDihedralType* dihedral_type = (*it).second;
        dihedral_types_[index] = dihedral_type;
    }
}
void TopologyFile::SetNumberOfAnglesExcludingHydrogen (int number_of_angles_excluding_hydrogen)
Definition at line 364 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    number_of_angles_excluding_hydrogen_ = number_of_angles_excluding_hydrogen;
}
void TopologyFile::SetNumberOfAnglesGroupPerturbed (int number_of_angles_group_perturbed)
Definition at line 440 of file topologyfile.cc.
{
    number_of_angles_group_perturbed_ = number_of_angles_group_perturbed;
}
void TopologyFile::SetNumberOfAnglesIncludingHydrogen (int number_of_angles_including_hydrogen)
Definition at line 352 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    number_of_angles_including_hydrogen_ = number_of_angles_including_hydrogen;
}
void TopologyFile::SetNumberOfAnglesPerturbed (int number_of_angles_perturbed)
Definition at line 428 of file topologyfile.cc.
{
    number_of_angles_perturbed_ = number_of_angles_perturbed;
}
void TopologyFile::SetNumberOfAngleTypes (int number_of_angle_types)
Definition at line 404 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    number_of_angle_types_ = number_of_angle_types;
}
void TopologyFile::SetNumberOfAtoms (int number_of_atoms)
Definition at line 340 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    number_of_atoms_ = number_of_atoms;
}
void TopologyFile::SetNumberOfAtomsInLargestResidue (int number_of_atoms_in_largest_residue)
Definition at line 452 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    number_of_atoms_in_largest_residue_ = number_of_atoms_in_largest_residue;
}
void TopologyFile::SetNumberOfAtomTypesInParameterFile (int number_of_atom_types_in_parameter_file)
Definition at line 412 of file topologyfile.cc.
{
    number_of_atom_types_in_parameter_file_ = number_of_atom_types_in_parameter_file;
}
void TopologyFile::SetNumberOfBeads (int number_of_beads)
Definition at line 464 of file topologyfile.cc.
{
    number_of_beads_ = number_of_beads;
}
void TopologyFile::SetNumberOfBondsExcludingHydrogen (int number_of_bonds_excluding_hydrogen)
Definition at line 360 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    number_of_bonds_excluding_hydrogen_ = number_of_bonds_excluding_hydrogen;
}
void TopologyFile::SetNumberOfBondsGroupPerturbed (int number_of_bonds_group_perturbed)
Definition at line 436 of file topologyfile.cc.
{
    number_of_bonds_group_perturbed_ = number_of_bonds_group_perturbed;
}
void TopologyFile::SetNumberOfBondsIncludingHydrogen (int number_of_bonds_including_hydrogen)
Definition at line 348 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    number_of_bonds_including_hydrogen_ = number_of_bonds_including_hydrogen;
}
void TopologyFile::SetNumberOfBondsPerturbed (int number_of_bonds_perturbed)
Definition at line 424 of file topologyfile.cc.
{
    number_of_bonds_perturbed_ = number_of_bonds_perturbed;
}
void TopologyFile::SetNumberOfBondTypes (int number_of_bond_types)
Definition at line 400 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    number_of_bond_types_ = number_of_bond_types;
}
void TopologyFile::SetNumberOfDihedralsExcludingHydrogen (int number_of_dihedrals_excluding_hydrogen)
Definition at line 368 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    number_of_dihedrals_excluding_hydrogen_ = number_of_dihedrals_excluding_hydrogen;
}
void TopologyFile::SetNumberOfDihedralsGroupPerturbed (int number_of_dihedrals_group_perturbed)
Definition at line 444 of file topologyfile.cc.
{
    number_of_dihedrals_group_perturbed_ = number_of_dihedrals_group_perturbed;
}
void TopologyFile::SetNumberOfDihedralsIncludingHydrogen (int number_of_dihedrals_including_hydrogen)
Definition at line 356 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    number_of_dihedrals_including_hydrogen_ = number_of_dihedrals_including_hydrogen;
}
void TopologyFile::SetNumberOfDihedralsPerturbed (int number_of_dihedrals_perturbed)
Definition at line 432 of file topologyfile.cc.
{
    number_of_dihedrals_perturbed_ = number_of_dihedrals_perturbed;
}
void TopologyFile::SetNumberOfDihedralTypes (int number_of_dihedral_types)
Definition at line 408 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    number_of_dihedral_types_ = number_of_dihedral_types;
}
void TopologyFile::SetNumberOfDistinctHydrogenBonds (int number_of_distinct_hydrogen_bonds)
Definition at line 416 of file topologyfile.cc.
{
    number_of_distinct_hydrogen_bonds_ = number_of_distinct_hydrogen_bonds;
}
void TopologyFile::SetNumberOfExcludedAtoms (int number_of_excluded_atoms)
Definition at line 380 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    number_of_excluded_atoms_ = number_of_excluded_atoms;
}
void TopologyFile::SetNumberOfExtraPoints (int number_of_extra_points)
Definition at line 460 of file topologyfile.cc.
{
    number_of_extra_points_ = number_of_extra_points;
}
void TopologyFile::SetNumberOfHydrogenParameters (int number_of_hydrogen_parameters)
Definition at line 372 of file topologyfile.cc.
{
    number_of_hydrogen_parameters_ = number_of_hydrogen_parameters;
}
void TopologyFile::SetNumberOfParameters (int number_of_parameters)
Definition at line 376 of file topologyfile.cc.
{
    number_of_parameters_ = number_of_parameters;
}
void TopologyFile::SetNumberOfResidues (int number_of_residues)
Definition at line 384 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    number_of_residues_ = number_of_residues;
}
void TopologyFile::SetNumberOfTypes (int number_of_types)
Definition at line 344 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    number_of_types_ = number_of_types;
}
void TopologyFile::SetPath (std::string path)
Definition at line 332 of file topologyfile.cc.
{
    path_ = path;
}
void TopologyFile::SetPerturbationOption (int perturbation_option)
Definition at line 420 of file topologyfile.cc.
{
    perturbation_option_ = perturbation_option;
}
void TopologyFile::SetRadiusSet (RadiusSet radius_set)
Definition at line 473 of file topologyfile.cc.
{
    radius_set_.clear();
    for(RadiusSet::iterator it = radius_set.begin(); it != radius_set.end(); it++)
    {
        radius_set_.push_back(*it);
    }
}
void TopologyFile::SetStandardPeriodicBoxOption (int standard_periodic_box_option)
Definition at line 448 of file topologyfile.cc.
{
    standard_periodic_box_option_ = standard_periodic_box_option;
}
void TopologyFile::SetTitle (std::string title)
Definition at line 336 of file topologyfile.cc.
{
    title_ = title;
}
void TopologyFile::SetTotalNumberOfAngles (int total_number_of_angles)
Definition at line 392 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    total_number_of_angles_ = total_number_of_angles;
}
void TopologyFile::SetTotalNumberOfBonds (int total_number_of_bonds)
Definition at line 388 of file topologyfile.cc.
Referenced by MolecularModeling::Assembly::BuildTopologyFileStructureFromAssembly().
{
    total_number_of_bonds_ = total_number_of_bonds;
}
void TopologyFile::SetTotalNumberOfDihedrals (int total_number_of_dihedrals)
Definition at line 396 of file topologyfile.cc.
{
    total_number_of_dihedrals_ = total_number_of_dihedrals;
}
void TopologyFile::Write (const std::string & top_file)
Close the parm7 files
Definition at line 1712 of file topologyfile.cc.
{
    std::ofstream out_file;
    try
    {
        out_file.open(top_file.c_str());
    }
    catch(...)
    {
        throw TopologyFileProcessingException(__LINE__,"File could not be created");
    }
    try
    {
        this->ResolveSections(out_file);
    }
    catch(...)
    {
        out_file.close();            /// Close the parm7 files
    }
}
The documentation for this class was generated from the following files:
includes/FileSet/TopologyFileSpace/topologyfile.hpp
src/FileSet/TopologyFileSpace/topologyfile.cc