gmmlNew: PdbFileSpace::PdbAtomCard Class Reference
PdbFileSpace::PdbAtomCard Class Reference
#include <pdbatomcard.hpp>
Public Types
typedef std::map< int, PdbAtom * > PdbAtomMap
Public Member Functions
PdbAtomCard ()
PdbAtomCard (std::stringstream &stream_block, std::string index)
std::string GetRecordName ()
PdbAtomMap GetAtoms ()
void SetRecordName (const std::string record_name)
void SetAtoms (PdbAtomMap atoms)
void Print (std::ostream &out=std::cout)
Detailed Description
Definition at line 15 of file pdbatomcard.hpp.
Member Typedef Documentation
typedef std::map<int, PdbAtom*> PdbFileSpace::PdbAtomCard::PdbAtomMap
Definition at line 24 of file pdbatomcard.hpp.
Constructor & Destructor Documentation
PdbAtomCard::PdbAtomCard ()
Definition at line 14 of file pdbatomcard.cc.
: record_name_("ATOM") {}
PdbFileSpace::PdbAtomCard::PdbAtomCard (std::stringstream & stream_block, std::string index)
Member Function Documentation
PdbAtomCard::PdbAtomMap PdbAtomCard::GetAtoms ()
Definition at line 47 of file pdbatomcard.cc.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), PdbFileSpace::PdbFile::GetAllAtomsInOrder(), PdbFileSpace::PdbFile::GetAllAtomsOfResidue(), PdbFileSpace::PdbFile::GetAllAtomsOfResidues(), PdbFileSpace::PdbFile::GetAllResidueNames(), PdbFileSpace::PdbFile::GetAllResidueNamesFromAtomCard(), PdbFileSpace::PdbFile::GetAllResidues(), PdbFileSpace::PdbFile::GetAllResiduesFromAtomCard(), PdbFileSpace::PdbFile::GetAtomBySerialNumber(), PdbFileSpace::PdbFile::GetAtomOfResidueByAtomKey(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    return atoms_;
}
string PdbAtomCard::GetRecordName ()
Definition at line 42 of file pdbatomcard.cc.
Referenced by PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModelCardWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), and PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber().
{
    return record_name_;
}
void PdbAtomCard::Print (std::ostream & out = std::cout)
Definition at line 80 of file pdbatomcard.cc.
References gmml::iNotSet.
{
    out << "Record Name: " << record_name_ << endl <<
           "_________________ Atoms _______________" << endl;
    for(PdbAtomCard::PdbAtomMap::iterator it = atoms_.begin(); it != atoms_.end(); it++)
    {
        out << "Atom Serial Number: ";
        if((it)->first != iNotSet)
            out << (it)->first << endl;
        else
            out << " " << endl;
        (it)->second->Print();
        out << endl;
    }
    out << endl;
}
void PdbAtomCard::SetAtoms (PdbAtomMap atoms)
Definition at line 62 of file pdbatomcard.cc.
Referenced by PdbFileSpace::PdbFile::DeleteAtom(), PdbFileSpace::PdbFile::DeleteAtoms(), PdbFileSpace::PdbFile::DeleteAtomsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteAtomWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidue(), PdbFileSpace::PdbFile::DeleteResidues(), PdbFileSpace::PdbFile::DeleteResiduesWithTheGivenModelNumber(), PdbFileSpace::PdbFile::DeleteResidueWithTheGivenModelNumber(), MolecularModeling::Assembly::ExtractPdbModelCardFromAssembly(), PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains(), PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChainsWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber(), PdbFileSpace::PdbFile::UpdateResidueName(), and PdbFileSpace::PdbFile::UpdateResidueNameWithTheGivenModelNumber().
{
    atoms_.clear();
    for(PdbAtomMap::iterator it = atoms.begin(); it != atoms.end(); it++)
    {
        PdbAtom* atom = (*it).second;
        int serial_number = (*it).first;
        atoms_[serial_number] = atom;
    }
}
void PdbAtomCard::SetRecordName (const std::string record_name)
Definition at line 57 of file pdbatomcard.cc.
Referenced by PdbFileSpace::PdbFile::InsertResidueAfter(), PdbFileSpace::PdbFile::InsertResidueAfterWithTheGivenModelNumber(), PdbFileSpace::PdbFile::InsertResidueBefore(), PdbFileSpace::PdbFile::InsertResidueBeforeWithTheGivenModelNumber(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCard(), PdbFileSpace::PdbFile::SplitAtomCardOfModelCardWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains(), PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChainsWithTheGivenModelNumber(), PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), and PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChainsWithTheGivenModelNumber().
{
    record_name_ = record_name;
}
The documentation for this class was generated from the following files:
includes/FileSet/PdbFileSpace/pdbatomcard.hpp
src/FileSet/PdbFileSpace/pdbatomcard.cc