gmmlNew: gmml Namespace Reference
gmml Namespace Reference
Enumerations
enum PossibleNChainTermination { COCH3 = 1, NH3 = 2 }
enum PossibleCChainTermination { NH2 = 1, NHCH3 = 2, CO2 = 3 }
enum PdbPreprocessorHISMapping { HIE = 1, HIP = 2, HID = 3 }
enum InputFileType {
PDB, LIB, PREP, TOP,
TOP_CRD, MULTIPLE, UNKNOWN
}
enum BuildingStructureOption { DISTANCE, ORIGINAL, DATABASE }
enum ParameterFileType { MAIN = 0, MODIFIED = 1 }
Functions
std::string & Trim (std::string &str)
void RemoveQuotes (std::string &str)
void RemoveSpaces (std::string &str)
std::vector< std::string > Split (std::string line, std::string delim)
template<typename T >
T ConvertString (const std::string &str)
std::string & ExpandLine (std::string &line, int length)
InputFileType ConvertString2AssemblyInputFileType (std::string type)
std::string ConvertAssemblyInputFileType2String (InputFileType type)
BuildingStructureOption ConvertString2AssemblyBuildingStructureOption (std::string option)
std::string ConvertAssemblyBuildingStructureOption2String (BuildingStructureOption option)
double ConvertDegree2Radian (double degree)
Geometry::Coordinate * ConvertInternalCoordinate2CartesianCoordinate (std::vector< Geometry::Coordinate * > coordinate_list, double distance, double angle, double torsion)
Variables
const double dNotSet = 123456789.0
const int iNotSet = -123456
const int iPdbLineLength = 80
const double dSulfurCutoff = 2.5
const double PI_RADIAN = 4.0*atan(1.0)
const double PI_DEGREE = 180.0
const double EPSILON = 0.001
const double dCutOff = 1.6
Enumeration Type Documentation
enum gmml::BuildingStructureOption
Enumerator:
DISTANCE
ORIGINAL
DATABASE
Definition at line 65 of file common.hpp.
    {
        DISTANCE,
        ORIGINAL,
        DATABASE
    };
enum gmml::InputFileType
Enumerator:
PDB
LIB
PREP
TOP
TOP_CRD
MULTIPLE
UNKNOWN
Definition at line 51 of file common.hpp.
    {
        PDB,
        LIB,
        PREP,
        TOP,
        TOP_CRD,
        MULTIPLE,
        UNKNOWN
    };
enum gmml::ParameterFileType
Enumerator:
MAIN
Main parameter file >
MODIFIED
Force modified parameter file >
Definition at line 75 of file common.hpp.
    {
        MAIN = 0,           /*!< Main parameter file >*/
        MODIFIED = 1        /*!< Force modified parameter file >*/
    };
enum gmml::PdbPreprocessorHISMapping
Enumerator:
HIE
HIP
HID
Definition at line 41 of file common.hpp.
    {
        HIE = 1,
        HIP = 2,
        HID = 3
    };
enum gmml::PossibleCChainTermination
Enumerator:
NH2
NHCH3
CO2
Definition at line 31 of file common.hpp.
    {
        NH2 = 1,
        NHCH3 = 2,
        CO2 = 3
    };
enum gmml::PossibleNChainTermination
Enumerator:
COCH3
NH3
Definition at line 22 of file common.hpp.
    {
        COCH3 = 1,
        NH3 = 2
    };
Function Documentation
std::string gmml::ConvertAssemblyBuildingStructureOption2String (BuildingStructureOption option) [inline]
Definition at line 173 of file utils.hpp.
References DATABASE, DISTANCE, and ORIGINAL.
    {
        switch(option)
        {
            case DISTANCE:
                return "Distance";
            case ORIGINAL:
                return "Original";
            case DATABASE:
                return "Database";
            default:
                return "Distance";
        }
    }
std::string gmml::ConvertAssemblyInputFileType2String (InputFileType type) [inline]
Definition at line 128 of file utils.hpp.
References LIB, MULTIPLE, PDB, PREP, TOP, TOP_CRD, and UNKNOWN.
Referenced by MolecularModeling::Assembly::BuildStructure().
    {
        switch(type)
        {
            case PDB:
                return "PDB";
            case LIB:
                return "LIB";
            case PREP:
                return "PREP";
            case TOP:
                return "TOP";
            case TOP_CRD:
                return "TOP_CRD";
            case MULTIPLE:
                return "MULTIPLE";
            case UNKNOWN:
                return "UNKNOWN";
            default:
                return "UNKNOWN";
        }
    }
double gmml::ConvertDegree2Radian (double degree) [inline]
Definition at line 193 of file utils.hpp.
References PI_DEGREE, and PI_RADIAN.
Referenced by ConvertInternalCoordinate2CartesianCoordinate().
    {
        return degree/PI_DEGREE*gmml::PI_RADIAN;
    }
Geometry::Coordinate* gmml::ConvertInternalCoordinate2CartesianCoordinate (std::vector< Geometry::Coordinate * > coordinate_list, double distance, double angle, double torsion) [inline]
Definition at line 206 of file utils.hpp.
References ConvertDegree2Radian(), Geometry::Coordinate::CrossProduct(), EPSILON, Geometry::Coordinate::GetX(), Geometry::Coordinate::GetY(), Geometry::Coordinate::GetZ(), Geometry::Coordinate::Normalize(), PI_DEGREE, and Geometry::Coordinate::Translate().
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPrepFile().
    {
        if(coordinate_list.size() == 0)
            return new Geometry::Coordinate();
        if(coordinate_list.size() == 1)
            return new Geometry::Coordinate(coordinate_list.at(0)->GetX() + distance, 0.0, 0.0);
        if(coordinate_list.size() == 2)
            return new Geometry::Coordinate(coordinate_list.at(1)->GetX() - cos(gmml::ConvertDegree2Radian(angle) * distance),
                                            sin(gmml::ConvertDegree2Radian(angle)) * distance, 0.0);
        else
        {
            torsion = gmml::PI_DEGREE - torsion;
            Geometry::Coordinate great_grandparent_vector = Geometry::Coordinate(coordinate_list.at(0)->GetX(), coordinate_list.at(0)->GetY(), coordinate_list.at(0)->GetZ());
            Geometry::Coordinate grandparent_vector = Geometry::Coordinate(coordinate_list.at(1)->GetX(), coordinate_list.at(1)->GetY(), coordinate_list.at(1)->GetZ());
            Geometry::Coordinate parent_vector = Geometry::Coordinate(coordinate_list.at(2)->GetX(), coordinate_list.at(2)->GetY(), coordinate_list.at(2)->GetZ());
            Geometry::Coordinate v1 = Geometry::Coordinate(grandparent_vector);
            Geometry::Coordinate v2 = Geometry::Coordinate(parent_vector);
            v1.operator-(great_grandparent_vector);
            v2.operator-(grandparent_vector);
            v1.Normalize();
            v2.Normalize();
            if(abs(v1.GetX() + v2.GetX()) < gmml::EPSILON &&
                    abs(v1.GetY() + v2.GetY()) < gmml::EPSILON &&
                    abs(v1.GetZ() + v2.GetZ()) < gmml::EPSILON)
            {
                great_grandparent_vector.Translate(1.0, -1.0, 2);
                v1 = Geometry::Coordinate(grandparent_vector);
                v1.operator-(great_grandparent_vector);
            }
            Geometry::Coordinate r = Geometry::Coordinate(v1);
            r.CrossProduct(v2);
            r.Normalize();
            Geometry::Coordinate p = Geometry::Coordinate(r);
            p.CrossProduct(v2);
            std::vector<double> v = std::vector<double>();
            v.push_back(distance * sin(gmml::ConvertDegree2Radian(angle)) * cos(gmml::ConvertDegree2Radian(torsion)));
            v.push_back(distance * sin(gmml::ConvertDegree2Radian(angle)) * sin(gmml::ConvertDegree2Radian(torsion)));
            v.push_back(distance * cos(gmml::ConvertDegree2Radian(angle)));
            v.push_back(1.0);
            return new Geometry::Coordinate(p.GetX() * v.at(0) + r.GetX() * v.at(1) + v2.GetX() * v.at(2) + parent_vector.GetX() * v.at(3),
                                            p.GetY() * v.at(0) + r.GetY() * v.at(1) + v2.GetY() * v.at(2) + parent_vector.GetY() * v.at(3),
                                            p.GetZ() * v.at(0) + r.GetZ() * v.at(1) + v2.GetZ() * v.at(2) + parent_vector.GetZ() * v.at(3));
        }
    }
template<typename T > T gmml::ConvertString (const std::string & str) [inline]
Definition at line 71 of file utils.hpp.
{
        T val;
        std::stringstream ss(str);
        ss >> val;
//        if (ss >> val)
        return val;
        throw std::invalid_argument("ConvertString: invalid conversion of string " + str);
    }
BuildingStructureOption gmml::ConvertString2AssemblyBuildingStructureOption (std::string option) [inline]
Definition at line 156 of file utils.hpp.
References DATABASE, DISTANCE, and ORIGINAL.
    {
        if(option.compare("Distance") == 0)
            return DISTANCE;
        if(option.compare("Original") == 0)
            return ORIGINAL;
        if(option.compare("Database") == 0)
            return DATABASE;
        else
            return DISTANCE;
    }
InputFileType gmml::ConvertString2AssemblyInputFileType (std::string type) [inline]
Definition at line 106 of file utils.hpp.
References LIB, MULTIPLE, PDB, PREP, TOP, TOP_CRD, and UNKNOWN.
Referenced by MolecularModeling::Assembly::BuildStructure().
    {
        if(type.compare("PDB") == 0)
            return PDB;
        if(type.compare("LIB") == 0)
            return LIB;
        if(type.compare("PREP") == 0)
            return PREP;
        if(type.compare("TOP") == 0)
            return TOP;
        if(type.compare("TOP_CRD") == 0)
            return TOP_CRD;
        if(type.compare("MULTIPLE") == 0)
            return MULTIPLE;
        return UNKNOWN;
    }
std::string& gmml::ExpandLine (std::string & line, int length) [inline]
Definition at line 87 of file utils.hpp.
Referenced by PdbFileSpace::PdbFile::ParseAuthorCard(), PdbFileSpace::PdbFile::ParseCards(), PdbFileSpace::PdbFile::ParseCaveatCard(), PdbFileSpace::PdbFile::ParseCISPeptideCard(), PdbFileSpace::PdbFile::ParseCompoundCard(), PdbFileSpace::PdbFile::ParseConnectivityCard(), PdbFileSpace::PdbFile::ParseCrystallographyCard(), PdbFileSpace::PdbFile::ParseDatabaseReferenceCard(), PdbFileSpace::PdbFile::ParseDisulfideBondCard(), PdbFileSpace::PdbFile::ParseEndCard(), PdbFileSpace::PdbFile::ParseExpirationDateCard(), PdbFileSpace::PdbFile::ParseFormulaCard(), PdbFileSpace::PdbFile::ParseHeaderCard(), PdbFileSpace::PdbFile::ParseHelixCard(), PdbFileSpace::PdbFile::ParseHeterogenCard(), PdbFileSpace::PdbFile::ParseHeterogenNameCard(), PdbFileSpace::PdbFile::ParseHeterogenSynonymCard(), PdbFileSpace::PdbFile::ParseJournalCard(), PdbFileSpace::PdbFile::ParseKeywordCard(), PdbFileSpace::PdbFile::ParseLinkCard(), PdbFileSpace::PdbFile::ParseMasterCard(), PdbFileSpace::PdbFile::ParseMatrixCard(), PdbFileSpace::PdbFile::ParseModelCard(), PdbFileSpace::PdbFile::ParseModelTypeCard(), PdbFileSpace::PdbFile::ParseModificationResidueCard(), PdbFileSpace::PdbFile::ParseNumModelCard(), PdbFileSpace::PdbFile::ParseObsoleteCard(), PdbFileSpace::PdbFile::ParseOriginCard(), PdbFileSpace::PdbFile::ParseRemarkCard(), PdbFileSpace::PdbFile::ParseRevisionDateCard(), PdbFileSpace::PdbFile::ParseScaleCard(), PdbFileSpace::PdbFile::ParseSequenceAdvancedCard(), PdbFileSpace::PdbFile::ParseSequenceResidueCard(), PdbFileSpace::PdbFile::ParseSheetCard(), PdbFileSpace::PdbFile::ParseSiteCard(), PdbFileSpace::PdbFile::ParseSourceCard(), PdbFileSpace::PdbFile::ParseSplitCard(), PdbFileSpace::PdbFile::ParseSupersededEntriesCard(), and PdbFileSpace::PdbFile::ParseTitleCard().
    {
        if((int)line.length() >= length)
            return line;
        else
        {
            int space = length - line.length();
            std::stringstream ss;
            ss << line << std::setw(space) << " ";
            line = ss.str();
            return line;
        }
    }
void gmml::RemoveQuotes (std::string & str) [inline]
Definition at line 35 of file utils.hpp.
Referenced by LibraryFileSpace::LibraryFile::ProcessAtom(), and LibraryFileSpace::LibraryFile::Read().
    {
        str.erase(std::remove(str.begin(), str.end(), '\"'), str.end());
    }
void gmml::RemoveSpaces (std::string & str) [inline]
Definition at line 45 of file utils.hpp.
Referenced by LibraryFileSpace::LibraryFile::Read().
    {
        str.erase(std::remove_if(str.begin(), str.end(), ::isspace), str.end());
    }
std::vector<std::string> gmml::Split (std::string line, std::string delim) [inline]
Definition at line 56 of file utils.hpp.
Referenced by MolecularModeling::Assembly::BuildAssemblyFromPdbFile(), MolecularModeling::Assembly::BuildStructure(), PdbFileSpace::PdbFile::GetAtomOfResidueByAtomKey(), TopologyFileSpace::TopologyFile::PartitionLine(), and TopologyFileSpace::TopologyFile::ResolveExcludedAtomsListSection().
    {
        boost::char_separator<char> separator(delim.c_str());
        boost::tokenizer< boost::char_separator<char> > tokens(line, separator);
        std::vector<std::string> vectorTokens = std::vector<std::string>();
        vectorTokens.assign(tokens.begin(), tokens.end());
        return vectorTokens;
    }
std::string& gmml::Trim (std::string & str) [inline]
Definition at line 23 of file utils.hpp.
Referenced by PrepFileSpace::PrepFileResidue::ExtractImproperDihedral(), PrepFileSpace::PrepFileResidue::ExtractLoops(), PrepFileSpace::PrepFileResidue::LoadFromStream(), PdbFileSpace::PdbFile::ParseAuthorCard(), PdbFileSpace::PdbFile::ParseCards(), PdbFileSpace::PdbFile::ParseCaveatCard(), PdbFileSpace::PdbFile::ParseCISPeptideCard(), PdbFileSpace::PdbFile::ParseCompoundCard(), PdbFileSpace::PdbFile::ParseConnectivityCard(), PdbFileSpace::PdbFile::ParseCrystallographyCard(), PdbFileSpace::PdbFile::ParseDatabaseReferenceCard(), PdbFileSpace::PdbFile::ParseDisulfideBondCard(), PdbFileSpace::PdbFile::ParseEndCard(), PdbFileSpace::PdbFile::ParseExpirationDateCard(), PdbFileSpace::PdbFile::ParseFormulaCard(), PdbFileSpace::PdbFile::ParseHeaderCard(), PdbFileSpace::PdbFile::ParseHelixCard(), PdbFileSpace::PdbFile::ParseHeterogenCard(), PdbFileSpace::PdbFile::ParseHeterogenNameCard(), PdbFileSpace::PdbFile::ParseHeterogenSynonymCard(), PdbFileSpace::PdbFile::ParseJournalCard(), PdbFileSpace::PdbFile::ParseKeywordCard(), PdbFileSpace::PdbFile::ParseLinkCard(), PdbFileSpace::PdbFile::ParseMasterCard(), PdbFileSpace::PdbFile::ParseMatrixCard(), PdbFileSpace::PdbFile::ParseModelCard(), PdbFileSpace::PdbFile::ParseModelTypeCard(), PdbFileSpace::PdbFile::ParseModificationResidueCard(), PdbFileSpace::PdbFile::ParseNumModelCard(), PdbFileSpace::PdbFile::ParseObsoleteCard(), PdbFileSpace::PdbFile::ParseOriginCard(), PdbFileSpace::PdbFile::ParseRemarkCard(), PdbFileSpace::PdbFile::ParseRevisionDateCard(), PdbFileSpace::PdbFile::ParseScaleCard(), PdbFileSpace::PdbFile::ParseSequenceAdvancedCard(), PdbFileSpace::PdbFile::ParseSequenceResidueCard(), PdbFileSpace::PdbFile::ParseSheetCard(), PdbFileSpace::PdbFile::ParseSiteCard(), PdbFileSpace::PdbFile::ParseSourceCard(), PdbFileSpace::PdbFile::ParseSplitCard(), PdbFileSpace::PdbFile::ParseSupersededEntriesCard(), PdbFileSpace::PdbFile::ParseTitleCard(), TopologyFileSpace::TopologyFile::ParseTitlePartition(), TopologyFileSpace::TopologyFile::PartitionLine(), ParameterFileSpace::ParameterFile::ProcessAngle(), ParameterFileSpace::ParameterFile::ProcessAtomType(), ParameterFileSpace::ParameterFile::ProcessBond(), ParameterFileSpace::ParameterFile::ProcessDihedral(), ParameterFileSpace::ParameterFile::ProcessEquivalentSymbols(), ParameterFileSpace::ParameterFile::ProcessHydrogenBond(), ParameterFileSpace::ParameterFile::ProcessHydrophilicAtomType(), ParameterFileSpace::ParameterFile::ProcessImproperDihedral(), ParameterFileSpace::ParameterFile::ProcessPotentialParameter(), LibraryFileSpace::LibraryFile::Read(), CoordinateFileSpace::CoordinateFile::Read(), ParameterFileSpace::ParameterFile::ReadMainParameter(), and ParameterFileSpace::ParameterFile::ReadModifiedParameter().
    {
        str.erase(str.find_last_not_of(" ") + 1);
        str.erase(0, str.find_first_not_of(" "));
        return str;
    }
Variable Documentation
const double gmml::dCutOff = 1.6
Definition at line 17 of file common.hpp.
Referenced by MolecularModeling::Assembly::BuildStructure().
const double gmml::dNotSet = 123456789.0
Definition at line 10 of file common.hpp.
Referenced by ParameterFileSpace::ParameterFileAngle::Print(), PdbFileSpace::PdbScaleN::Print(), PdbFileSpace::PdbOriginXn::Print(), PdbFileSpace::PdbDisulfideResidueBond::Print(), ParameterFileSpace::ParameterFileDihedralTerm::Print(), ParameterFileSpace::ParameterFileBond::Print(), PdbFileSpace::PdbMatrixN::Print(), ParameterFileSpace::ParameterFileDihedral::Print(), Geometry::Coordinate::Print(), PdbFileSpace::PdbCrystallographicCard::Print(), PdbFileSpace::PdbHelix::Print(), ParameterFileSpace::ParameterFileAtom::Print(), LibraryFileSpace::LibraryFileResidue::Print(), PdbFileSpace::PdbAtom::Print(), ParameterFileSpace::ParameterFile::ProcessAtomType(), ParameterFileSpace::ParameterFile::ProcessDoubleDihedralDescription(), ParameterFileSpace::ParameterFile::ProcessPotentialParameter(), LibraryFileSpace::LibraryFile::Read(), ParameterFileSpace::ParameterFile::ResolveAtomTypeSection(), LibraryFileSpace::LibraryFile::ResolveBoundBoxSection(), PdbFileSpace::PdbFile::ResolveCrystallographyCard(), PdbFileSpace::PdbFile::ResolveDisulfideBondCard(), PdbFileSpace::PdbFile::ResolveHelixCard(), PdbFileSpace::PdbFile::ResolveLinkCard(), PdbFileSpace::PdbFile::ResolveMatrixCard(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveOriginCard(), ParameterFileSpace::ParameterFile::ResolvePotentialParameterSection(), PdbFileSpace::PdbFile::ResolveScaleCard(), PdbPreprocessorSpace::PdbPreprocessor::UpdateAminoAcidChains(), PdbPreprocessorSpace::PdbPreprocessor::UpdateGapsInAminoAcidChains(), PrepFileSpace::PrepFileProcessingException::what(), TopologyFileSpace::TopologyFileProcessingException::what(), CoordinateFileSpace::CoordinateFileProcessingException::what(), LibraryFileSpace::LibraryFileProcessingException::what(), ParameterFileSpace::ParameterFileProcessingException::what(), and PdbFileSpace::PdbFileProcessingException::what().
const double gmml::dSulfurCutoff = 2.5
Definition at line 13 of file common.hpp.
Referenced by PdbPreprocessorSpace::PdbPreprocessor::ExtractCYSResidues().
const double gmml::EPSILON = 0.001
Definition at line 16 of file common.hpp.
Referenced by ConvertInternalCoordinate2CartesianCoordinate().
const int gmml::iNotSet = -123456
Definition at line 11 of file common.hpp.
Referenced by PdbFileSpace::PdbConnectCard::Print(), PdbFileSpace::PdbNumModelCard::Print(), PdbFileSpace::PdbModel::Print(), PdbFileSpace::PdbDisulfideBondCard::Print(), PdbFileSpace::PdbAtomCard::Print(), PdbFileSpace::PdbModelCard::Print(), PdbFileSpace::PdbHeterogenAtomCard::Print(), PdbFileSpace::PdbOriginXn::Print(), PdbFileSpace::PdbScaleN::Print(), PdbFileSpace::PdbFormula::Print(), PdbFileSpace::PdbResidueSequence::Print(), PdbFileSpace::PdbSiteResidue::Print(), PdbFileSpace::PdbSheetStrandResidue::Print(), PdbFileSpace::PdbHelixResidue::Print(), PdbFileSpace::PdbSite::Print(), ParameterFileSpace::ParameterFileDihedralTerm::Print(), PdbFileSpace::PdbDisulfideResidueBond::Print(), PdbFileSpace::PdbSheet::Print(), PdbFileSpace::PdbDisulfideResidue::Print(), PdbFileSpace::PdbMatrixN::Print(), PdbFileSpace::PdbHeterogen::Print(), PdbFileSpace::PdbResidueModification::Print(), PdbFileSpace::PdbLinkResidue::Print(), PdbFileSpace::PdbCrystallographicCard::Print(), PdbFileSpace::PdbHelix::Print(), PdbFileSpace::PdbAtom::Print(), ParameterFileSpace::ParameterFile::ProcessImproperDihedral(), PdbFileSpace::PdbFile::ResolveConnectivityCard(), LibraryFileSpace::LibraryFile::ResolveConnectSection(), PdbFileSpace::PdbFile::ResolveCrystallographyCard(), PdbFileSpace::PdbFile::ResolveDisulfideBondCard(), PdbFileSpace::PdbFile::ResolveFormulaCard(), PdbFileSpace::PdbFile::ResolveHelixCard(), PdbFileSpace::PdbFile::ResolveHeterogenCard(), PdbFileSpace::PdbFile::ResolveLinkCard(), PdbFileSpace::PdbFile::ResolveMatrixCard(), PdbFileSpace::PdbFile::ResolveModelCard(), PdbFileSpace::PdbFile::ResolveModificationResidueCard(), PdbFileSpace::PdbFile::ResolveNumModelCard(), PdbFileSpace::PdbFile::ResolveSequenceResidueCard(), PdbFileSpace::PdbFile::ResolveSheetCard(), and PdbFileSpace::PdbFile::ResolveSiteCard().
const int gmml::iPdbLineLength = 80
Definition at line 12 of file common.hpp.
Referenced by PdbFileSpace::PdbFile::ParseAuthorCard(), PdbFileSpace::PdbFile::ParseCards(), PdbFileSpace::PdbFile::ParseCaveatCard(), PdbFileSpace::PdbFile::ParseCISPeptideCard(), PdbFileSpace::PdbFile::ParseCompoundCard(), PdbFileSpace::PdbFile::ParseConnectivityCard(), PdbFileSpace::PdbFile::ParseCrystallographyCard(), PdbFileSpace::PdbFile::ParseDatabaseReferenceCard(), PdbFileSpace::PdbFile::ParseDisulfideBondCard(), PdbFileSpace::PdbFile::ParseEndCard(), PdbFileSpace::PdbFile::ParseExpirationDateCard(), PdbFileSpace::PdbFile::ParseFormulaCard(), PdbFileSpace::PdbFile::ParseHeaderCard(), PdbFileSpace::PdbFile::ParseHelixCard(), PdbFileSpace::PdbFile::ParseHeterogenCard(), PdbFileSpace::PdbFile::ParseHeterogenNameCard(), PdbFileSpace::PdbFile::ParseHeterogenSynonymCard(), PdbFileSpace::PdbFile::ParseJournalCard(), PdbFileSpace::PdbFile::ParseKeywordCard(), PdbFileSpace::PdbFile::ParseLinkCard(), PdbFileSpace::PdbFile::ParseMasterCard(), PdbFileSpace::PdbFile::ParseMatrixCard(), PdbFileSpace::PdbFile::ParseModelCard(), PdbFileSpace::PdbFile::ParseModelTypeCard(), PdbFileSpace::PdbFile::ParseModificationResidueCard(), PdbFileSpace::PdbFile::ParseNumModelCard(), PdbFileSpace::PdbFile::ParseObsoleteCard(), PdbFileSpace::PdbFile::ParseOriginCard(), PdbFileSpace::PdbFile::ParseRemarkCard(), PdbFileSpace::PdbFile::ParseRevisionDateCard(), PdbFileSpace::PdbFile::ParseScaleCard(), PdbFileSpace::PdbFile::ParseSequenceAdvancedCard(), PdbFileSpace::PdbFile::ParseSequenceResidueCard(), PdbFileSpace::PdbFile::ParseSheetCard(), PdbFileSpace::PdbFile::ParseSiteCard(), PdbFileSpace::PdbFile::ParseSourceCard(), PdbFileSpace::PdbFile::ParseSplitCard(), PdbFileSpace::PdbFile::ParseSupersededEntriesCard(), and PdbFileSpace::PdbFile::ParseTitleCard().
const double gmml::PI_DEGREE = 180.0
Definition at line 15 of file common.hpp.
Referenced by ConvertDegree2Radian(), and ConvertInternalCoordinate2CartesianCoordinate().
const double gmml::PI_RADIAN = 4.0*atan(1.0)
Definition at line 14 of file common.hpp.
Referenced by ConvertDegree2Radian().